### ISSUE TITLE
Akka.NET v1.0.2 release - scheduled for Monday

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1016]
meant to do this a lot sooner but got tied up with work :p 

We're going to ship Akka.NET v1.0.2 primarily to push **major** bug fixes for the following modules:

1. Akka (async / await)
2. Akka.Cluster (leader election)
3. Akka.DI (edge cases)

Due date is Monday. Will be putting release notes together before then.

**Any reasons why we should delay?**

We're doing small releases regularly, so "but wait, [thing I care about] isn't done yet!" isn't a valid reason. We'll get it on the next release ;)

"Thing you're about to ship has a breaking change / new bug I just found / etc that needs to be reverted" is a valid reason.

**Comment by rogeralsing** [comment]
4. TaskScheduler replaced with DedicatedThreadScheduler

**Comment by Aaronontheweb** [comment]
Ah, and the XUnit 2.0 TestKit also

**Comment by rogeralsing** [comment]
+ Configurable scheduler

Isnt there even more?

**Comment by Aaronontheweb** [comment]
Akka.Persistence.PostGREs and Akka.Persistence.Cassandra

Lots of new contributors stepped up this month!

**Comment by Horusiath** [comment]
Since Akka 1.0.2 has been released, I'm closing this one.
