### ISSUE TITLE
Getting started example with multiple threads

### ISSUE THREAD

**Issue by varghesep** [akkadotnet/akka.net#1024]
There is a [getting started example](http://getakka.net/docs/Getting%20started) shows how akka.net can be used. At the end of the example, it says "your actor is now ready to consume messages sent from any number of calling threads".

My first question when I read that sentence is (1) 'how to call the actor from multiple threads', secondly (2) can't this application be run in a multi-threaded environment without actors and thirdly (3) is this a good example to explain the concurrency problem and how akka.net actors solve that?

I would suggest enhancing the same example or create a new example that explains the problem and how akka.net solves it.

**Comment by Aaronontheweb** [comment]
1. You call the actor from multiple threads by passing an IActorRef around, fundamentally not any different than any other .NET object you'd want to share about threads.
2. I don't understand this question. This is just a "hello world" sample for actors?
3. That's a good point - we actually don't explain this very well elsewhere in the documentation. 

If you need more of the low-level stuff, http://learnakka.net/ is the best place to learn that in the meantime.
