### ISSUE TITLE
Two phase commit during persisting and raising events

### ISSUE THREAD

**Issue by varghesep** [akkadotnet/akka.net#1035]
The following code is taken from the file EventSourced.cs. As I understand from this code, the event (for example an event like ProductCostReduced) is persisted first and the handler is called. Take a case where the event is persisted but the handler that sets the state threw an exception. You can also assume the system crashed after the event is persisted. This will cause the event is stored and possibly the particular actor dies?

My question is, shouldn't the persistence of the event and the handler action be a transaction so both succeed or fail together? 

        public void Persist<TEvent>(TEvent @event, Action<TEvent> handler)
        {
            _pendingStashingPersistInvocations++;
            _pendingInvocations.AddLast(new StashingHandlerInvocation(@event, o => handler((TEvent)o)));
            _eventBatch.AddFirst(new Persistent(@event));
        }

**Comment by Horusiath** [comment]
In case when event is persisted, but handler invocation throws exception or system crashes, actor gets restarted anyway. In that case if will eventually recover from all events stored in event journal - including already stored one. This way or another it will update it's state based on that event.

**Comment by varghesep** [comment]
I don't understand where else the logic needs to be put other than in the handler logic. In this [example](https://github.com/akkadotnet/akka.net/blob/dev/src/examples/PersistenceExample/ExamplePersistentActor.cs) it is handled in the UpdateState handler.

The events can be internal and external. The internals can be the ones which update it's state of that actor. They can be replayed and brought the actor to it's current state. But the external events are the ones which interact with other actors in other bounded context. They can't be replayed because it will effect the external actors multiple times. This communication pattern is obvious in a CQRS scenario. A couple of these links talk about this issue. [NEventStore](http://blog.jonathanoliver.com/removing-2pc-two-phase-commit/) [CQRS] (https://msdn.microsoft.com/en-us/library/jj591559.aspx) [SO](http://stackoverflow.com/questions/13488982/cqrs-storing-events-and-publishing-them-how-do-i-do-this-in-a-safe-way)

**Comment by Horusiath** [comment]
I think, we misunderstand each other. First I think what you're calling internal/external events is usually named as events/commands by convention.

1. **Commands** are messages that describe a process to be performed. They are not replayed, they are not persisted and when handled they should not change an actor's persistent state. Process, which handles a command, may decide to emit one or more events as result.
2. **Events** are messages that describe facts already done. They are persisted, they are replayed to update actor's state (possibly many times), but they cannot be denied (your business logic cannot deny the received event). Event handlers should not perform any work, that is not related with business logic, they focus only on state update - therefore it's hard for event handler to crash. They shouldn't emit any other CQRS-based events in result.

> Either of them can fail, and Akka.net Persistence handles the first issue but not when MQ fails.

What do you mean, by saying that MQ fails?

**Comment by varghesep** [comment]
Thanks for clarifying the command and events separation. The scenario that you described will work in an intra Aggregate scenario. For example, within an OrderManagement BC. It is highly possible that this BC raised an event (not command) which has impact on a different BC like Forecasting. Any event that OrderManagement raises which impacts Forecasting can be called external. If those events are also persisted and replayed (in the scenario of failure), it will impact the Forecasting BC many times and it's state can become stale.

I suggested the MQ so the external events can be send to the MQ so when the system comes up to life, it may be there or not, so executed based on it's existence and it wont effect the Forecasting BC. In the mean time, the Persistence store will have only internal events. When a Message Queue is also involved, we have to consider a two phase commit.

**Comment by Horusiath** [comment]
As I've said, commands are not data to be persisted. Don't mix the responsibilities of the commands and events. Using your example you can simply send a new command to concerned actor in `Persist` method callback like this:

```csharp
// inside PersistentActor
protected override bool ReceiveCommand(object command)
{
    // process command
    Persist(new DomainEvent(data), e => {
        // this is called when event has been persisted
        State = UpdateState(e);
        forecastingRef.Tell(new DomainCommand(e.Data));
    });
}
```

**Comment by varghesep** [comment]
Thanks for that tip. What if the Forecasting is a BC and lives in a different process or machine? Directly accessing the entities from other Bounded Context is not a DDD principle.

**Comment by Horusiath** [comment]
My code sample was just to clarify the idea. Different processes and/or machines doesn't change a lot - this is what actor location transparency is all about. And as you attached some of the Martin Flower's writings, you probably already figured out that you can use another actor to serve the role of Coordinator or Gateway.

**Comment by rogeralsing** [comment]
Status here? Close?
