### ISSUE TITLE
NoSender actor serialization problems

### ISSUE THREAD

**Issue by ssoshchepkov** [akkadotnet/akka.net#1036]
`NoSender` actor has two serialization related bugs:

1. `Serialization.SerializedActorPath` for `NoSender` returns 'akka://all-systems' instead of 'akka://all-systems/NoSender' because `NoSender` actor's name is a part of `RootActorPath`.
2. When `RemoteActorRefProvider` is used as an actor provider, deserialization of `NoSender` causes `RemoteTransportException`. It happens because `public IActorRef ResolveActorRef(string path)` method of `RemoteActorRefProvider` expects an empty string for `NoSender` actor's path, not 'akka://all-systems' nor 'akka://all-systems/NoSender'.

**Comment by rogeralsing** [comment]
Closed with #1041
