### ISSUE TITLE
nuget/Akka.Persistence.Sql.Common

### ISSUE THREAD

**Issue by patrickede** [akkadotnet/akka.net#1044]
Download of Akka.Persistence.SqlServer does not appear to include Akka.Persistence.Sql.Common, nor does it appear to be available separately.  SqlServerPersistence.Init fails, not finding Akka.Persistence.Sql.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by Aaronontheweb** [comment]
Doh! Thanks for pointing this out - we'll update our build script to take care of that

**Comment by patrickede** [comment]
Cool, happy to help

**Comment by Aaronontheweb** [comment]
Resolved as of Akka.NET v1.0.3.
