### ISSUE TITLE
SqlServer plugin little typo in the setup part of the readme

### ISSUE THREAD

**Issue by Silv3rcircl3** [akkadotnet/akka.net#1047]
In [this](https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/persistence/Akka.Persistence.SqlServer/README.md) readme

```
akka.persistence.snasphot-store.plugin = "akka.persistence.snasphot-store.sql-server"
akka.persistence.snasphot-store.sql-server.connection-string = "<database connection string>"
```

And no look at it for five minutes ;-)
snasphot should be snapshot... drove me crazy :smirk:

**Comment by rogeralsing** [comment]
Fixed :) thanks for reporrting
