### ISSUE TITLE
Akka.Cluster min-nr-of-members per-role doesn't work

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1050]
```xml
akka.cluster{
      [rolename].min-nr-of-members = N
}
```

This should enforce the "don't mark member of role as up until N is satisfied" rule on a per-role basis via HOCON config. Does not currently work.

**Comment by rogeralsing** [comment]
Broken or just not implamented at all?

**Comment by Aaronontheweb** [comment]
Looks broken: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Cluster/ClusterDaemon.cs#L1508

**Comment by thelegendofando** [comment]
This works for me:

```
akka.cluster{
      role.[rolename].min-nr-of-members = N
}
```

**Comment by Aaronontheweb** [comment]
@thelegendofando oh snap, it's just that you need to add the `role` prefix first?

**Comment by thelegendofando** [comment]
Yep :)

**Comment by Aaronontheweb** [comment]
Welp - I'm an idiot. We can close this out.

**Comment by stevenharrap** [comment]
Note that http://getakka.net/docs/clustering/cluster-configuration does not reflect this.
Currently:
cluster {
       seed-nodes = ["akka.tcp://ClusterSystem@127.0.0.1:8081"]
       roles = ["crawlerV1", "crawlerV2"]
       crawlerV1.min-nr-of-members = 3
    }
Should be:
cluster {
       seed-nodes = ["akka.tcp://ClusterSystem@127.0.0.1:8081"]
       roles = ["crawlerV1", "crawlerV2"]
       role.["crawlerV1"].min-nr-of-members = 3
    }
