### ISSUE TITLE
Akka.Persistence.TestKit

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1067]
These three tests will give a false positive on the test result

```
SnapshotStore_should_not_load_a_snapshot_given_an_invalid_persistence_id
SnapshotStore_should_not_load_a_snapshot_given_non_matching_sequence_number_criteria
SnapshotStore_should_not_load_a_snapshot_given_non_matching_timestamp_criteria
```

They all pass, even if there is no real snapshot implementation. e.g. you just throw not impemented exception and the tests will still pass.

**Comment by rogeralsing** [comment]
cc @Horusiath

**Comment by Horusiath** [comment]
I think, that this bug live long enough to become a feature :) . When you're implementing from `SnapshotStore` class, any exception thrown in `LoadAsync` method is equivalent of *snapshot not found*. This is actually an expected behavior.

**Comment by rogeralsing** [comment]
I _think_ this passes even if there is no snapshot provider at all, which seems a bit too optimistic :)

**Comment by rogeralsing** [comment]
Nice :)
