### ISSUE TITLE
Create a remote test base class for two systems

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1077]
There are some tests that do set up a remote system and tests the interaction between the two, but this involves some not completely obvious config string replacements to make system name and port number dynamic.

It would be nice to create a base class for this kind of tests so that we can test remote interaction w/o throwing too much effort on the test setup.
`RemoteRouterSpec` does this and I think this can be pretty much copy pasted into a base type.

I'd like to see better coverage of akka.remote in general, we have had quite a few issues with remote deployment and want to fix this.

Thoughts on this?
Should we abstract the double system setup to a base class in Akka.Remote.Tests?

**Comment by rogeralsing** [comment]
Or is this exactly what the MultiNodeSpec does?

**Comment by Aaronontheweb** [comment]
This is what `MultiNodeSpec` does - but as @Horusiath has ported out, it needs to be documented.
