### ISSUE TITLE
Please allow Akka.DI.StructureMap to depend on >= StructureMap v2.6.3.

### ISSUE THREAD

**Issue by davejclausen** [akkadotnet/akka.net#1078]
Thanks for the Akka.DI.StructureMap NuGet!

One of our projects requires StructureMap dating back to v2.6.3.

I have tested StructureMapDependencyResolver on StructureMap v2.6.3 and it seems to work perfectly well.

Could the Akka.DI.StructureMap NuGet manifest allow >= StructureMap v2.6.3?

Would you prefer me to make a pull request for this?

Many thanks.

**Comment by rogeralsing** [comment]
As long as there are no API changes that prevents Akka.NET from using it then it should be fine.
A PR would be welcome :)

**Comment by davejclausen** [comment]
Will do!  StructureMapDependencyResolver works perfectly well (unchanged) with StructureMap v2.6.3.  Thanks.

**Comment by rogeralsing** [comment]
Status on this one?

**Comment by Aaronontheweb** [comment]
Guess we still need to move the needle back in time on the NuGet package for this.

**Comment by GeertVL** [comment]
Is this still open?

**Comment by Danthar** [comment]
This issue is still open. No PR has been made for this. So if anyone feels like updating this. Go right ahead.
