### ISSUE TITLE
Add concise, clear logging around disassociation messages

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1087]
Lack of good information around disassocations is making it very difficult to debug Akka.Remote and Akka.Cluster. We need to add more details around why a disassociation occurred as well as how endpoint policies are being applied.

**Comment by Aaronontheweb** [comment]
Just spent some time in a new branch working on this. Cleaned up the `ProtocolStateActor` - it's not really responsible for any of the `disassociate` log messages so I thought I'd post that here and save others the trouble :p

**Comment by Telavian** [comment]
I am running into a bunch of disassociation messages which are very sporadic at first and then constant after a few days of running. How would I go about troubleshooting this? I understand failed heartbeats should not be happening however when they do what does that really mean when both sides are running? A simple restart makes everything magically work again.

http://stackoverflow.com/questions/31753052/akka-net-remote-disconnection

**Comment by Aaronontheweb** [comment]
After talking @rkuhn, shutdown messages should be logged as `DEBUG` - not `ERROR`

**Comment by maxcherednik** [comment]
Since it's about clean logging, I can try to look at. Also cleaned some known exception logging in #2438

**Comment by Danthar** [comment]
@maxcherednik sounds good! 👍

**Comment by Aaronontheweb** [comment]
Done as part of 1.1.3
