### ISSUE TITLE
`Skip` attribute on MultiNodeFact does not work

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1088]
Still ran the tests I wanted to skip :\

![image](https://cloud.githubusercontent.com/assets/326939/8315198/afe4bc6a-19a3-11e5-8b76-513ce94e40e7.png)

**Comment by schatekar** [comment]
Looking at the source for `MultiNodeFact` below.

This is returning `null` from skip if the test is run using MultiNodeTestRunner or NodeTestRunner. I am not sure if XUnit treats a null `Skip` value as test not to be skipped or not but if I assume that then clearly any test run using MultiNodeTestRunner would never be skipped, isn't it?

```csharp
    public class MultiNodeFactAttribute : FactAttribute
    {
        public static Lazy<bool> ExecutedByMultiNodeRunner =
            new Lazy<bool>(() =>
            {
                var args = Environment.GetCommandLineArgs();
                if (args.Length == 0) return false;
                var firstArg = args[0];
                return firstArg.Contains("Akka.MultiNodeTestRunner") 
                    || firstArg.Contains("Akka.NodeTestRunner");
            });

        public override string Skip
        {
            get
            {
                return ExecutedByMultiNodeRunner.Value
                    ? null
                    : "Must be executed by multi-node test runner";
            }
            set { base.Skip = value; }
        }
    }
```

**Comment by cpx** [comment]
Just started looking at this as well :) @schatekar, a null value means test should be run, and non-null means it should be skipped.

**Comment by schatekar** [comment]
I think I know how to fix this. If you are not fixing it I can take a crack
at it in few hours.

**Comment by cpx** [comment]
It's all yours :)

**Comment by Aaronontheweb** [comment]
You guys are awesome :)

**Comment by schatekar** [comment]
This is more involved than I had imagined. I would give it another try over the weekend.

**Comment by Aaronontheweb** [comment]
> This is more involved than I had imagined. I would give it another try over the weekend.

I know that feeling well, my friend.

**Comment by barambani** [comment]
I gave a try to this as well, I guess because is less intimidating than the others :), it looks like that removing the null is not enough. I could enable the runner to skip the multinode facts checking the attribute in the

**Comment by schatekar** [comment]
@barambani  I did not get a message that you have worked on the issue as well. I just went ahead and submitted my fix without knowing that you too have submitted a fix.

**Comment by barambani** [comment]
@schatekar no problem, I will close mine.

**Comment by schatekar** [comment]
@barambani Don't close yours just yet. I would leave it to the project leads to accept the best PR

**Comment by barambani** [comment]
@schatekar I looked at your solution and passes all the tests, also brings the skip reason up to the top level to log it. I like it more than mine as well. Mine was a late night hack.
