### ISSUE TITLE
Update mono build targets to exclude MSTest projects

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1100]
MSTest doesn't play nicely on Mono, so we're going to have to create a build configuration for Mono using the `AllTests` FAKE target that doesn't attempt to compile this binary or run any of its associated unit tests.

**Comment by stefansedich** [comment]
This is done as part of the #1103 PR but we are now experiencing further issues, I am closing off this item and creating a new issue realted to our mono issues and builds.
