### ISSUE TITLE
Silent failure

### ISSUE THREAD

**Issue by varghesep** [akkadotnet/akka.net#1104]
I have a persistenceid in the format 

string.Format(@"{0}@{1}\{2}.{3}", serviceId, partitionId, nameof(SamplePersistentActor), Self.Path.Name 

The persistence fails, and I have found out that I can't use backward slash in the persistence id.

Is there a way I can enable logging and see the errors like this?

**Comment by Horusiath** [comment]
1. What persistence backend do you use?
2. What kind of PersistenceId has been generated? Could you provide any example?

You can set logging to DEBUG level using `akka.loglevel = DEBUG` in your HOCON configuration. Optionally you can create supervisor actor over failing actor and define custom SupervisorStrategy - this way you'll be able to catch exceptions incoming from dying persistent actor.

**Comment by skotzko** [comment]
@varghesep any update on these questions?

**Comment by Horusiath** [comment]
I think that this problem was related with #1149 .

**Comment by varghesep** [comment]
@skotzko It was a LocalSnapShotStore. I assume the **\** was generated from **Self.Path.Name**.

**Comment by skotzko** [comment]
@Horusiath should we close this then?

**Comment by Horusiath** [comment]
Yes, this problem has been already issued and fixed with #1150
