### ISSUE TITLE
Hocon Persistence Configuration : connection-string

### ISSUE THREAD

**Issue by mmisztal1980** [akkadotnet/akka.net#1107]
Please consider replacing this key with connection-string-name or something similar. so that We can keep connection strings where ther're supposed to be kept (between 'connectionStrings' tags)

**Comment by Horusiath** [comment]
I think we could give people choice, either they want to insert connection string directly in HOCON using `connection-string` or they want to specify name in the connection string section using `connection-string-name` key.

**Comment by mmisztal1980** [comment]
Yeah, I agree - mutually exclusive choice is good.

**Comment by Horusiath** [comment]
Closed by #1151 and #1306
