### ISSUE TITLE
Cluster does not recover after closing a few nodes

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1111]
I've started a cluster with some 20ish nodes, and if I kill off a few of those nodes, 5+ in about the same time. the cluster doesnt recover in a reasonable amount of time. 
It took some 10 minutes for it to become stable again, which seems a lot for such a small cluster.

(But it did eventually remove the killed nodes and stopped spamming)

**Comment by Aaronontheweb** [comment]
I assume that you had auto-down disabled during this.

A node, if it's suddenly removed from a cluster without first attempting to exit, will be marked as Unreachable but not "down." So the leader won't mark those nodes as down until they rejoin and explicitly exit the cluster without autodown turned off.

**Comment by irperez** [comment]
Could you explain this configuration option?  Like how to set this in the Hocon for us noobs?  I've seen this myself when working with the crawler sample.

**Comment by skotzko** [comment]
Closing this per convo w/ @Aaronontheweb . Issue appears to be expected behavior re: reachability.
