### ISSUE TITLE
LightInject Support

### ISSUE THREAD

**Issue by Rajivhost** [akkadotnet/akka.net#1120]
Hi,
That will be also really great if we can have LightInject (http://www.lightinject.net/) support.

**Comment by Caldas** [comment]
:+1:

-----Mensagem Original-----
De: "Rajiv Mounguengue" <notifications@github.com>
Enviada em: ‎03/‎07/‎2015 19:27
Para: "akkadotnet/akka.net" <akka.net@noreply.github.com>
Assunto: [akka.net] LightInject Support (#1120)

Hi,
That will be also really great if we can have LightInject (http://www.lightinject.net/) support.

**Comment by Danthar** [comment]
We are not going to create a plugin for this DI platform. However you are welcome to start your own repo for a lightinject plugin for akka.net.
