### ISSUE TITLE
Foody for monitoring

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1124]
The JVM side of things uses a lot of Aspect Orientation for injecting monitoring code into actors.
We have looked a bit on PostSharp for this, but there is also **Foody** https://github.com/Fody which we could take a peek at.

Even if Typesafe is working on a monitoring API, this could still be useful for use specific monitoring scenarios.

Anyone here that have used it?

**Comment by cpx** [comment]
From what I've seen, Fody is the most useful when you want to do low-level weaving over an entire codebase, e.g. as in Obsolete.Fody or Janitor.Fody. It doesn't do aspect-oriented weaving by itself; that has to be handled by an add-in. If what you want is high-level AOP for monitoring, I think PostSharp is a more natural fit. It also has the benefit of being actively developed and commercially backed, as opposed to the AOP addins for Fody which sadly seem to be abandoned.
