### ISSUE TITLE
LocalShapshotStore uses raw persistenceId as part of path

### ISSUE THREAD

**Issue by BartAdv** [akkadotnet/akka.net#1149]
This causes crash (FileNotFoundException) [here](https://github.com/akkadotnet/akka.net/blob/cluster-sharding/src/core/Akka.Persistence/Snapshot/LocalSnapshotStore.cs#L185) if the persistenceId contains slashes (which is the case for some system actors for example).

**Comment by Horusiath** [comment]
Ok, in order to fix this we should use `Uri.EscapeDataString(persistenceId)` whenever accessing OS file system from within LocalSnapshotStore.

**Comment by Horusiath** [comment]
Closed by #1150
