### ISSUE TITLE
Reorganizing Examples in the core repo

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1160]
Our current example folder structure is sort of messy.

![examples](https://cloud.githubusercontent.com/assets/647031/8731863/595d2d64-2bfa-11e5-8c87-f2d20d5f58eb.png)

Chat, Stocks, TimeServer, those do not describe at all what features they are built for.

I would like to see the examples grouped by feature.

e.g.
1. GettingStarted
2. Routing
3. Remote
4. Persistence
5. Cluster
6. Cluster.Sharding
   ...

Something along those lines, and then put one or a few examples under each of those.
I think we could have some sort of readme in there aswell and link to the Bootcamp also.

This is somewhat of a non-issue, but as this isnt any real effort, we could just aswell do it right
Thoughts on this? cc @akkadotnet/developers

**Comment by sean-gilliam** [comment]
:+1:

**Comment by Aaronontheweb** [comment]
related: #1171

**Comment by wmeints** [comment]
Looks like a fun job to start with. Mind if I go ahead and give this a shot?

**Comment by skotzko** [comment]
@wmeints go for it, thanks!

**Comment by MECLab** [comment]
Hey team, is anyone working on this? I'm happy to take it as well as help out with some xml docs. These would be a good way to get involved and learn the code base at the some time.

**Comment by rogeralsing** [comment]
@MECLab go for it if you want :+1:

**Comment by marcpiechura** [comment]
@MECLab do you still working on this one?

**Comment by Silv3rcircl3** [comment]
@MECLab do you still working on this one?

**Comment by Silv3rcircl3** [comment]
I have reorganized the examples in the following way (in VS and the filesystem) 
![image](https://cloud.githubusercontent.com/assets/6583600/11808895/959dfc40-a323-11e5-98b9-a00c36696fae.png)

Let me know what you think. 

@rogeralsing 
Can you give me a little more information what you want to see in the readme?
Maybe a short description what every project does?
