### ISSUE TITLE
Add default Ask timeout to HOCON configuration

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1163]
In Scala, ask timeout can be set implicitly, while in C#/F# this is not possible, and therefore it may feel repetitive and not safe (when user decided not to set it at all, there is possibility to hang forever). The idea is to add HOCON config key for setting the default timeout on `IActorRef.Ask` method in case, when user didn't specified it explicitly.

Proposal is to create `akka.actor.ask-timeout` key with TimeSpan value (set to **null** by default to stay backward compatible). This setting should be applied to all [IActorRef.Ask](https://github.com/akkadotnet/akka.net/blob/928ff2b3b23457ea1e4e1d9f0819fca945506a1b/src/core/Akka/Actor/Futures.cs) invocations without explicit timeouts. This should also be reflected in updated documentation.

**Comment by rogeralsing** [comment]
Fxed by #1166
