### ISSUE TITLE
Racy tests fail with out of memory error

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1167]
Is anyone else seeing these failures?
![racyfails](https://cloud.githubusercontent.com/assets/647031/8760857/2435b02c-2d33-11e5-8150-1172161be27b.png)

I get them when I run all the tests, if I re-run them they pass.
I get this on a fresh dev sync so it looks like there is something in the public repo.

**Comment by rogeralsing** [comment]
There seems to be some code that use `ReflectionAbstractionExtensions` and its nothing in our code. 
Is it XUnit? is it Json.NET?

**Comment by Aaronontheweb** [comment]
I've not seen this error occur before. Is there anything new in your fork?

**Comment by Aaronontheweb** [comment]
These are all of the tests that do remote deployment - if you're working on the `Config` stuff it's possible that there could be some sort of loop + copy going on, but I've not seen this before off of `dev`.

**Comment by rogeralsing** [comment]
I have the same problem in a fresh dev branch, so even if I reset the entire repo I get this.

**Comment by rogeralsing** [comment]
I'm closing this one, seems to be an xunit problem on my machine, running a different subset of tests make the same problem appear on other parts of the framework.
