### ISSUE TITLE
Roslyn code analyzers

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1177]
At this point, the codebase is so large that it is hard to get a good overview of it by just reading the code.

Therefore I'm planning to build some Roslyn code analyzers to verify that our codebase does not contain any known anti patterns.
For example, we can find if there is any code that access the `Context` inside a continuation, or if there are any mutable types used in calls to `Tell`
- Fnd cases where we don't close over `Context` in continuations
- Find any mutable message types
- Find variations of TaskContinuationOptions used in continuations
- Find blocking calls to the TPL API, e.g. Task.Wait or Task.Result (which doesn't mean it's wrong, but giving us an overview would be good)

Anyone else interested in this?
Are there other cases that we can automate?

**Comment by Horusiath** [comment]
> Fnd cases where we don't close over Context in continuations

Does this one applies to `Sender` property of an actor as well?

- Find any Tell/Ask calls in actor's recovery method. This is an anti-pattern.

**Comment by rogeralsing** [comment]
>Does this one applies to Sender property of an actor as well?
We could absolutely include that too.

**Comment by rogeralsing** [comment]
cc @Aaronontheweb if we make this as a commandline tool,would it be possible to run this as part of the build/PR process?

It would be nice to auto catch standard code mistakes in every PR

**Comment by rogeralsing** [comment]
I'm already finding a few problems :)

We should also scan for non used types

**Comment by rogeralsing** [comment]
We should probably check for sender/self/context in closures passed to the scheduler also.

**Comment by Aaronontheweb** [comment]
@rogeralsing yep, we could do that - we'd just need to stick the .exe somewhere and add a FAKE build step.

IMHO, best place to stick this type of functionality would be a visual studio extension though.

**Comment by rogeralsing** [comment]
@Aaronontheweb yepp, but it would still be nice to have it handled at build server level too, as we can't expect everyone to install such analyzer in VS. nor that they would comply with the warnings it raises.

**Comment by sean-gilliam** [comment]
See https://github.com/akkadotnet/AkkaAnalyzer
