### ISSUE TITLE
Add dedicated output logger for xUnit2 TestKit

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1184]
With xUnit2 console output has began to be ignored by test runner - authors explain this by parallel test runs messing with console output. Therefore idea is to use [output substitute for xUnit2](http://xunit.github.io/docs/capturing-output.html) and create a dedicated logger for it to be used within TestKit specs by default.

**Comment by Silv3rcircl3** [comment]
Is implemented
