### ISSUE TITLE
Number of routees reported on Clustered Group routers doesn't reflect actual number of routees cluster-wide

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1189]
Issue was originally reported here: https://github.com/petabridge/akkadotnet-code-samples/issues/31

I've been able to verify that this is a bug inside Group routers. Looks like the number of routees correlates to the number of different `routees.paths`, when it should be `routees.paths` count X number of nodes.

**Comment by rogeralsing** [comment]
What does the "ready" tag mean? it's not in the Done column on waffle and its not closed, so what does it mean?

**Comment by Aaronontheweb** [comment]
@rogeralsing I think it means that this issue is queued up to be part of the next major release. @skotzko would know better than I would.

**Comment by matthewma** [comment]
@Aaronontheweb I asked a issue related to this today. Could you provide some information on this issue? and possibly, I could try to fix this?

**Comment by Aaronontheweb** [comment]
@matthewma sure, someone just created a reproduction case for this: https://github.com/idursun/akka.cluster.test

> I have two nodes with different roles, one of them being the seed node. I also have a consisten-hash-group, and when i ask for routees, I get one routee, which is expected. I start another instance of the worker node and ask for routees and i still get one routee. 

Does that help clarify things?

**Comment by Aaronontheweb** [comment]
Possibly related to #1700

**Comment by matthewma** [comment]
@Aaronontheweb Hi, I have stepped the code, I think I did see just one routee. But I am sorry that I think I don't know enough about Akka.NET to fix this issue.

**Comment by alexvaluyskiy** [comment]
All group routers bugs were fixed here https://github.com/akkadotnet/akka.net/pull/2094

**Comment by alexvaluyskiy** [comment]
Fixed https://github.com/akkadotnet/akka.net/pull/2103
