### ISSUE TITLE
Add ConfigR support.

### ISSUE THREAD

**Issue by OlegGavrilov** [akkadotnet/akka.net#1190]
Hello everyone, 

Is it a good idea to add support of [ConfigR](https://github.com/config-r/config-r) config files?

**Comment by Horusiath** [comment]
@OlegGavrilov the major problem here is that HOCON is quite heavily embedded inside akka. Right now the only way I think, this may work without rewriting massive part of the framework, would be to make ConfigR producing HOCON string as the result.

**Comment by rogeralsing** [comment]
Out of scope imo, If someone makes a contrib package that can produce hocon strings like @Horusiath said, that would be fine.
But changing core modules, no.
