### ISSUE TITLE
Create nightly + release build configurations for Akka.Persistence implementations on TeamCity

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1191]
Need to be able to do the following:

1. Each time there's a change on `dev` for this repo, kick off a new nightly integration build for every Akka.Persistence.Contrib implementation
2. Each time there is a release on `master` for this repo, kick off a similar release with the same version numbers for Akka.Persistence.Contrib

This will probably involve modifying the FAKE script for each of those repos.

**Comment by skotzko** [comment]
*raises hand timidly to volunteer*

**Comment by Horusiath** [comment]
I think, we can close this.

**Comment by Silv3rcircl3** [comment]
nightly and release builds are working fine
