### ISSUE TITLE
Akka.NET v1.0.4 Release

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1193]
Held a contributor meeting today and I'm happy to announce that we will be doing a new stable release, v1.0.4, next Tuesday August 4th.

The release will consist of the following:

1. New Akka.Persistence implementations: SqlLite and MongoDB.
2. Bug fixes to Akka.Remote, Akka.Cluster
3. The introduction of Akka.IO - an exciting new way to communicate directly to Akka.NET processes via TCP and UDP.
4. Fixes to serialization via upgrading to JSON.NET 7.0. This fixes the particularly frustrating discriminated union bug for F# users in particular.

And more - anything else I missed? Leave it in the comments below.

**Comment by Horusiath** [comment]
Few additional keys in configuration:

- `akka.actor.ask-timeout` for setting the default timeout on Ask method.
- `connection-string-name` to be used by persistence plugins using Akka.Persistence.Sql.Common

**Comment by rogeralsing** [comment]
And hocon include support for importing external config sections.
