### ISSUE TITLE
Plugin proposal: Akka.Persistence.Kafka

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1197]
This is proposal for the plugin using Apache Kafka as the persistence backend. While I haven't worked on Kafka on my daily basis, it looks like it's perfect fit for akka journal backend.

**Comment by megakid** [comment]
When this has matured, this would be a good MS backed Kafka client to use:

https://github.com/Microsoft/Kafkanet

**Comment by sean-gilliam** [comment]
@akkadotnet/core Should we move this proposal to the AkkaNetContrib org?

**Comment by snekbaev** [comment]
Interesting...

**Comment by sean-gilliam** [comment]
See https://github.com/AkkaNetContrib/Alpakka/pull/32
