### ISSUE TITLE
Plugin proposal: Akka.Cluster.Zookeeper

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1198]
This is the idea for the plugin, that could use Apache Zookeeper for bootstrapping akka cluster. There already exists a similar solution on the JVM space ([link](https://github.com/sclasen/akka-zk-cluster-seed)).

**Comment by rogeralsing** [comment]
:+1:

**Comment by DavidHoerster** [comment]
I'd like to help out on this one.

**Comment by rogeralsing** [comment]
After some research on this, I wonder if Zookeeper is a good fit? 
Zookeeper is CP, and a service discovery (seednode discovery in our case) really should be AP, right?

See https://tech.knewton.com/blog/2014/12/eureka-shouldnt-use-zookeeper-service-discovery/

**Comment by Horusiath** [comment]
@rogeralsing  Zookeeper is centralized configuration server. I think that having hard consistency is desired for this case. However it's also possible to work in read-only mode which is more AP oriented - there is interesting discussion about that in comments section of article, you've linked.

**Comment by sean-gilliam** [comment]
@akkadotnet/core Should we move this proposal to the AkkaNetContrib org?

**Comment by sean-gilliam** [comment]
Moved issue to AkkaNetContrib/Home#25
