### ISSUE TITLE
Outdated FsPickler version in Akka.FSharp can lead to runtime errors when other FsPickler-dependent packages are installed

### ISSUE THREAD

**Issue by rdavisau** [akkadotnet/akka.net#1206]
Hi!

The current version of FsPickler referenced by Akka.FSharp is a pre 1.0 release and the latest version is 1.2.21. Between these versions, there has been a rationalisation of the API surface, making the newer FsPickler incompatible with the version Akka.FSharp has been written against. If another package referencing FsPickler (e.g. [Vagabond](https://github.com/nessos/Vagabond)) is installed alongside Akka.FSharp, NuGet will update FsPickler to the newer, incompatible version. This results in a `MissingMethodException` at runtime when Akka.FSharp attempts to call one of the removed overloads of `Serialize`. 

I will follow this with a PR :rocket:

**Comment by Horusiath** [comment]
Closed by #1207
