### ISSUE TITLE
How to wait synchronously for a message

### ISSUE THREAD

**Issue by mvbaffa** [akkadotnet/akka.net#1214]
Hi, I have a WCF Service, when the service is called I need to send a message to actor and wait for the response message. 

I am using the Ask patterns. Is there a better way to do this?

Thanks in advance

**Comment by rogeralsing** [comment]
WCF supports task based services, which means you can do the same in a WCF service as in WebAPI:
See http://getakka.net/docs/deployment-scenarios/ASP%20NET#interaction-between-controllers-and-akka-net
that is an WebAPI example, but the idea is the same, make your service retur `Task<MyResult>` and then `await` the `Ask` operation of the actor

**Comment by mvbaffa** [comment]
It worked.
Thanks
Em 08/08/2015 04:41, "Roger Johansson" <notifications@github.com> escreveu:
