### ISSUE TITLE
Intermittent test failure:  StructureMapResolverSpec.DependencyResolver_should_dispose_IDisposable_instances_on_Actor_Termination	

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1216]
StructureMap and CastleWindsor appear to be our two weaklings from the results of #1139, and we've had an issue with intermittnet failures with the following spec:

[StructureMapResolverSpec.DependencyResolver_should_dispose_IDisposable_instances_on_Actor_Termination](https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/dependencyInjection/Akka.DI.StructureMap.Tests/StructureMapResolverSpec.cs#L10)

The underlying test method used to execute this test can be found here: https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/dependencyInjection/Akka.DI.TestKit/DiResolverSpec.cs#L354

You can see the output from the build log for a failure of this spec here: http://petabridge-ci.cloudapp.net/viewLog.html?buildId=1835&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetPrBuild&guest=1

Would like someone to take a look and see if this is an issue with StructureMap itself or an issue with the `StructureMapDependencyResolver` inside Akka.DI.StructureMap and see if we can resolve this issue.

**Comment by Silv3rcircl3** [comment]
Containers are now in there own repositories and all specs are passing.
