### ISSUE TITLE
Akka.DI.SimpleInjector

### ISSUE THREAD

**Issue by DavidHoerster** [akkadotnet/akka.net#1224]
I'd like to contribute a dependency resolver for SimpleInjector.  I use that DI container for my projects and would like to contribute to a dependency resolver for Akka if there's interest.

**Comment by nfadmin** [comment]
Very appreciated! We use SimpleInjector as well in our projects (BTW: a great DI container) and will start a new project based on Akka.NET soon. So we have exactly this demand, too. 
Is there any implementation allready available?

**Comment by DavidHoerster** [comment]
I have a branch ready to submit via a pull request.  The only thing I can't figure out is if the solution has a test suite for it.  I thought there used to be one, but maybe I'm wrong on that.  Just have to beef up the readme.md and the PR will be submitted.

**Comment by donamk** [comment]
Akka.DI.SimpleInjector would be awesome. :+1:

**Comment by jslew** [comment]
Hey @DavidHoerster, did anything ever become of this?  Looking for the same, was about to implement it myself.

**Comment by sean-gilliam** [comment]
See #1647

**Comment by Danthar** [comment]
corresponding PR was merged. And the SimpleInjector now has its own repo.
