### ISSUE TITLE
Link developer guidelines from "Contribution to Akka.NET" document page.

### ISSUE THREAD

**Issue by Exef** [akkadotnet/akka.net#1233]
[Contributing to Akka.NET](http://getakka.net/docs/Contributing%20to%20Akka) page has broken "Developer Guidelines" link. Should it link to `CONTRIBUTING.md` instead to [Contributor guidelines](http://getakka.net/docs/Contributor%20guidelines)?

![image](https://cloud.githubusercontent.com/assets/1412001/9191281/998c248a-3fff-11e5-8246-0e248021e286.png)

**Comment by elbaloo** [comment]
Link isn't or doesn't seem to be broken anymore.

**Comment by rogeralsing** [comment]
Thanks
