### ISSUE TITLE
Port Akka.Remote MultiNodeSpec: AttemptSysMsgRedeliverySpec

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1244]
Need to port: https://github.com/akka/akka/blob/master/akka-remote-tests/src/multi-jvm/scala/akka/remote/AttemptSysMsgRedeliverySpec.scala

**Comment by GraemeBradbury** [comment]
I'll give this one a go.

**Comment by Aaronontheweb** [comment]
@GraemeBradbury sent you an invite to be on the "contributor's" team so you can assign this issue to yourself

**Comment by Silv3rcircl3** [comment]
@Aaronontheweb @GraemeBradbury since C#6 features are now allowed could we reuse #1260 ?
