### ISSUE TITLE
Port Akka.Remote MultiNodeSpec: RemoteDeploymentDeathWatchSpec

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1248]
https://github.com/akka/akka/blob/master/akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteDeploymentDeathWatchSpec.scala

**Comment by GeertVL** [comment]
Can I have this one, as Marek took the other one.

**Comment by skotzko** [comment]
@GeertVL go for it!

**Comment by rogeralsing** [comment]
cc @maxim-s open for grabs if you want

**Comment by maxim-s** [comment]
I can try to do it

**Comment by maxim-s** [comment]
PR https://github.com/akkadotnet/akka.net/pull/1415
