### ISSUE TITLE
Port Akka.Remote MultiNodeSpec: RemoteGatePiercingSpec

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1249]
https://github.com/akka/akka/blob/master/akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteGatePiercingSpec.scala

**Comment by Aaronontheweb** [comment]
Assigning this to @GeertVL once he accepts my invite to @akkadotnet/contributors

**Comment by rogeralsing** [comment]
cc @maxim-s open for grabs if you want
