### ISSUE TITLE
Port Akka.Remote MultiNodeSpec: RemoteNodeRestartDeathWatchSpec

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1251]
https://github.com/akka/akka/blob/master/akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteNodeRestartDeathWatchSpec.scala

**Comment by maxim-s** [comment]
PR #1600

**Comment by maxim-s** [comment]
PR #1600 Updated

**Comment by maxim-s** [comment]
Closed by #1600
