### ISSUE TITLE
Port Akka.Remote MultiNodeSpec: RemoteNodeRestartGateSpec

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1252]
https://github.com/akka/akka/blob/master/akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteNodeRestartGateSpec.scala

**Comment by Aaronontheweb** [comment]
@maxim-s think you can get this to pass by rebasing on latest?

**Comment by alexvaluyskiy** [comment]
Closed https://github.com/akkadotnet/akka.net/pull/2120
