### ISSUE TITLE
Port Akka.Remote MultiNodeSpec: RemoteReDeploymentSpec

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1255]
https://github.com/akka/akka/blob/master/akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteReDeploymentSpec.scala

**Comment by alexvaluyskiy** [comment]
@maxim-s could you make PR?

**Comment by maxim-s** [comment]
@alexvaluyskiy sure, but node2 still failed, I don't want to do failed PR

**Comment by alexvaluyskiy** [comment]
Closed https://github.com/akkadotnet/akka.net/pull/2121
