### ISSUE TITLE
Port Akka.Remote MultiNodeSpec: RemoteRoundRobinSpec

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1258]
https://github.com/akka/akka/blob/master/akka-remote-tests/src/multi-jvm/scala/akka/remote/routing/RemoteRoundRobinSpec.scala

**Comment by GeertVL** [comment]
I will work on this one.

**Comment by KadekM** [comment]
@GeertVL oh sorry man, I did most of work at cafe, and noone was assigned to it when I checked...

**Comment by GeertVL** [comment]
@KadekM no problem. I will take something else.
