### ISSUE TITLE
Port Akka.Remote MultiNodeSpec: RemoteScatterGatherSpec

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1259]
https://github.com/akka/akka/blob/master/akka-remote-tests/src/multi-jvm/scala/akka/remote/routing/RemoteScatterGatherSpec.scala

**Comment by schatekar** [comment]
I am working on this

**Comment by Aaronontheweb** [comment]
@schatekar assigned! Good hunting.

**Comment by Silv3rcircl3** [comment]
@schatekar are you still working on this one ?

**Comment by schatekar** [comment]
@Silv3rcircl3  I have not been able to get back to this for some time. Do you want to pick up from where I had left?

**Comment by Silv3rcircl3** [comment]
@schatekar sure :+1:
