### ISSUE TITLE
Discussion: move to VS15 / DNX file format?

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1263]
Related to #992 

.NET is going to be changing a lot over the next year or so; some changes are going to be massive, like the introduction of .NET Core. Others, like the changing of the Visual Studio project structure, will be more incremental.

I want to ask how the community feels about when we should move towards supporting the new VS15 project file format, and what some of the benefits are? 

Ultimately, most of the production users of Akka.NET are going to be sticking with .NET 4.5 and older versions of Visual Studio / NuGet for some time; that's just the nature of the adoption cycle.

However, the contributors to Akka.NET are a bleeding-edge lot and we should always try to enable them to have the best tools and experience possible. So let's discuss it - when should we switch to the new format?

Some switching costs to be made aware of:

1. Changing the project format means we have to rebuild all build server images... That's actually a huge job. 40 hours worth of work, back of the envelope. Might be faster if it's easy to just upgrade the existing VM images to use an updated version of VS versus rebuilding them from scratch.
2. .... Mono support? Can the Mono compilers work with the new project file format? 
3. Switching over all of the Akka.Persistence project implementations?

And so on.

**Comment by adamhathcock** [comment]
The new format offers more flexibility when targeting versions and platforms.  Nuget package management and creation is simpler.

As for the work involved for Akka.NET, I can't say :)

**Comment by axefrog** [comment]
+1 for DNX/Core support. The new project format, among other things, is very nice to work with I think. In fact, though it hasn't deterred me from getting started with akka.net, I admit I felt a pang of disappointment upon discovery that akka.net isn't quite up to date in this regard.

**Comment by rogeralsing** [comment]
I'm all for it, this would allow us to use some of the new language features too. 
e.g. Getter only properties on our built in messages.

**Comment by annymsMthd** [comment]
+1 for the getter improvement

**Comment by gblmarquez** [comment]
+1 for DNX/Core support

**Comment by adamhathcock** [comment]
Any movement or ideas on this?  I'm willing to help from the xproj conversion side.

Basically not much will have to change if the target is still "net45" as opposed to "dnx451" etc.  Of course, the tooling in Visual Studio changes a bit.  Beta 7 required a new install.  Maybe beta 8 will as well.

I guess that might be an argument to wait a bit more then :)

**Comment by bjorn-ali-goransson** [comment]
Won't DNX enable cloud-based implementations (primarily, I guess) to use much less resources ie to be much more economical? How big is the incentive here?

**Comment by Danthar** [comment]
Right now. None. Because meanwhile the .net core  team pulled an 180 on the New project format. 

This had become a non issue since moving project types is no longer a option.

-----Original Message-----

**Comment by bjorn-ali-goransson** [comment]
So this issue should be closed?

**Comment by Danthar** [comment]
Yes

-----Original Message-----
