### ISSUE TITLE
Defined scope for Ninject dependencies ignored when actors are instantiated.

### ISSUE THREAD

**Issue by creepone** [akkadotnet/akka.net#1270]
When using the Akka.DI.Ninject (with the new behavior introduced in v1.0.4) with dependencies defined in the `IKernel` container as having a certain scope (e.g. using `InSingletonScope()`), this scope is being ignored when instantiating an actor.

Every dependency is created within the activation block's scope and therefore always newly instantiated.

While in most cases this is a desirable thing (actor being responsible for lifetime of its dependencies), there are situations where it is desirable to share a dependency between actors. It would be nice to at least be able to opt-in into such behavior.

**Comment by Silv3rcircl3** [comment]
Moved to the new Ninject repository.
