### ISSUE TITLE
Odd cluster behavior, possible deadlock

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1282]
After playing around with my elasticsearch logger and visualizing the cluster events.
I noticed a behavior that looks odd.

Look at the graphs at 08.40.00
I started two new nodes at that time, which can be seen in the NodeCount graph, and also there are two new nodes showing up on the heartbeat graph.

However, for a few seconds, there are zero(!) debug events coming in from _any_ of the other nodes.
It is as if all the nodes pause and start dealing with the new incoming nodes. 
Heartbeats are debug events and heartbeats among the already existing nodes should ofcourse continue to show up during this time.

![akkadashboard](https://cloud.githubusercontent.com/assets/647031/9573513/a83c0d1a-4fbd-11e5-9f3a-7d97ae27a702.png)

This might very well be an issue on my logger side of things, but I cannot see any debug events published during the joining process.

cc @Aaronontheweb

**Comment by rogeralsing** [comment]
NVM, I'm an idiot...

**Comment by Aaronontheweb** [comment]
Didn't have debug logging turned on? ;p
