### ISSUE TITLE
Replace string concatenation log statements with format templates

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1283]
Currently, there are a few cases where we do things like:

`_log.Debug("Foo" + bar + "Baz" + yo);`
This is however incompatible with loggers that use special formatting. (e.g. Serilog)

This should be replaced with:
`_log.Debug("Foo {0} Baz {1}",bar,yo);`

That way, loggers can apply whatever logic they need to the formatting template.

**Comment by alex-kondrashov** [comment]
Can I help on this one? seems to be easy to start with.

**Comment by Dim0N22** [comment]
I've found only [one line](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/Inbox.Actor.cs#L52) with string concatenation in entire solution.
Everything else looks fine to me.

**Comment by rogeralsing** [comment]
Ill see what sources i find, i see some log posts coming in with no message templates in elastic search

**Comment by rogeralsing** [comment]
@Dim0N22 did you also check the other log levels or only Debug?

**Comment by Dim0N22** [comment]
@rogeralsing I've checked all log levels. 
Double checked it with regexp, nothing found. Maybe I missed something?

**Comment by alex-kondrashov** [comment]
I've found couple of places [like this](https://github.com/akkadotnet/akka.net/blob/928ff2b3b23457ea1e4e1d9f0819fca945506a1b/src/core/Akka.Remote.TestKit/MultiNodeSpec.cs#L606)
but I'm not sure if it's relevant.

**Comment by rogeralsing** [comment]
@alex-kondrashov that is absolutely relevant. all dynamic content should be injected through the template. otherwise we can not extract the value using semantic logging

**Comment by rogeralsing** [comment]
Thanks for all the help guys!
