### ISSUE TITLE
Akka.TestKit.Xunit error with Xunit v2

### ISSUE THREAD

**Issue by michaelsync** [akkadotnet/akka.net#1284]
Hello,

I have the following packages in my test project.

```xml
  <package id="Akka" version="1.0.4" targetFramework="net46" />
  <package id="Akka.TestKit" version="1.0.4" targetFramework="net46" />
  <package id="Akka.TestKit.Xunit" version="1.0.4" targetFramework="net46" />
  <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net46" />
  <package id="xunit" version="2.0.0" targetFramework="net46" />
  <package id="xunit.abstractions" version="2.0.0" targetFramework="net46" />
  <package id="xunit.assert" version="2.0.0" targetFramework="net46" />
  <package id="xunit.core" version="2.0.0" targetFramework="net46" />
  <package id="xunit.extensibility.core" version="2.0.0" targetFramework="net46" />
  <package id="xunit.runner.visualstudio" version="2.0.1" targetFramework="net46" />
```

I am getting this error below when I run the test. The method "ExpectMsg" is throwing this exception.  Is it because xunit v2 is not compatible Akka.TestKit.Xunit 1.4?  

Result Message:	System.IO.FileNotFoundException : Could not load file or assembly 'xunit, Version=1.9.2.1705, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The system cannot find the file specified.

**Comment by Aaronontheweb** [comment]
@michaelsync we have two different XUnit packages:

http://www.nuget.org/packages/Akka.TestKit.Xunit/ - supports up to 1.9.2
http://www.nuget.org/packages/Akka.TestKit.Xunit2/ - supports 2.0.0 and later

**Comment by michaelsync** [comment]
Thanks Aaron!
