### ISSUE TITLE
How to intercept the message between actors

### ISSUE THREAD

**Issue by michaelsync** [akkadotnet/akka.net#1289]
Hello,

Is there any way to intercept the message between actors (even on remote or cluster)? I like to add the correlation id or unique identifier or some logic after sending the message and before receiving that message from other actor.

**Comment by Aaronontheweb** [comment]
Parent Proxy Pattern, which you'll be learning about in our training tomorrow :p

**Comment by michaelsync** [comment]
Hi Aaron, 

Thanks! ;-) 

If I use Parent Proxy Pattern then I will have to create a proxy for every message passing. 

What I am looking for is something similar to AroundRecieved method that is triggered before receiving the message. 

Here is an example. (I am just typing the code here (not in VS) so there might be some typo but hope you got what I meant. ;-) )

*Messages*
 
```C#
public class MessageBase{
    public Guid CorrelationId { get; private set; }
}

public class PayBillMessage : MessageBase {
    public int BillId { get; private set; }
    public DateTimeOffset Date { get; private set; }
}
```

*Actors*
 
```C#

public class ActorBase{
   
  public void override BeforeMessageRecieved(MessageBase msg){
        //Some common logic like Log.PushPropertyStart(msg.CorrelationId)  
  }

  public void override AfterMessageRecieved(MessageBase msg){
        //Some common logic like Log.PushPropertyEnd(msg.CorrelationId)  
  }
}

public class BillManagerActor : ActorBase {
    public BillManagerActor(){
         Receive<PayBillMessage>(m => {
                Log.Information("Pay bill");
               
                var otherActor = Context.CreateActorWithRouter<OtherClusterActor>();
                var otherMessage = new OtherMessage() { CorrelationId = m.CorrelationId, OtherProperty = "something" };

                otherActor.Tell(otherMessage);
         });
    }    
}

public class OtherClusterActor : ActorBase {
    public OtherClusterActor (){
         Receive<OtherMessage>(m => {
                Log.Information("Do something");
         });
    }    
}
````

The goal is to execute some common code (such as validation or logging ) before receiving the message and after executing the message.  

Feel free to let me know if you are not clear what I am looking for. Thanks again.

**Comment by michaelsync** [comment]
Sorry. Stephen found the solution. Yes. We can just use AroundReceive

public class ActorBase{

  public void override AroundReceive(MessageBase msg){
        //Before 
        // .....

       var return = base.AroundReceive(r, message);

        //After
        //...

     return return;
  }
 
}

**Comment by Horusiath** [comment]
Be very cautious with `AroundReceive` - remember: 

> With great power comes great responsibility :)
