### ISSUE TITLE
Multiple active result sets exception

### ISSUE THREAD

**Issue by sadprofessor** [akkadotnet/akka.net#1291]
we occasionally see an exception coming from SQL akka persistence moaning about multiple active result sets not being supported. Might it need enabling?

	`System.Data.dll!System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(System.Data.SqlClient.SqlCommand command)	Unknown
 	System.Data.dll!System.Data.SqlClient.SqlConnection.ValidateConnectionForExecute(string method, System.Data.SqlClient.SqlCommand command)	Unknown
 	System.Data.dll!System.Data.SqlClient.SqlCommand.ValidateCommand(string method, bool async)	Unknown
 	System.Data.dll!System.Data.SqlClient.SqlCommand.RunExecuteReader(System.Data.CommandBehavior cmdBehavior, System.Data.SqlClient.RunBehavior runBehavior, bool returnStream, string method, System.Threading.Tasks.TaskCompletionSource<object> completion, int timeout, out System.Threading.Tasks.Task task, bool asyncWrite)	Unknown
 	System.Data.dll!System.Data.SqlClient.SqlCommand.BeginExecuteReaderInternal(System.Data.CommandBehavior behavior, System.AsyncCallback callback, object stateObject, int timeout, bool asyncWrite)	Unknown
 	System.Data.dll!System.Data.SqlClient.SqlCommand.BeginExecuteReaderAsync(System.Data.CommandBehavior behavior, System.AsyncCallback callback, object stateObject)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskFactory<System.Data.SqlClient.SqlDataReader>.FromAsyncImpl<System.Data.CommandBehavior>(System.Func<System.Data.CommandBehavior,System.AsyncCallback,object,System.IAsyncResult> beginMethod, System.Func<System.IAsyncResult,System.Data.SqlClient.SqlDataReader> endFunction, System.Action<System.IAsyncResult> endAction, System.Data.CommandBehavior arg1, object state, System.Threading.Tasks.TaskCreationOptions creationOptions)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskFactory<System.Data.SqlClient.SqlDataReader>.FromAsync<System.Data.CommandBehavior>(System.Func<System.Data.CommandBehavior,System.AsyncCallback,object,System.IAsyncResult> beginMethod, System.Func<System.IAsyncResult,System.Data.SqlClient.SqlDataReader> endMethod, System.Data.CommandBehavior arg1, object state)	Unknown
 	System.Data.dll!System.Data.SqlClient.SqlCommand.ExecuteReaderAsync(System.Data.CommandBehavior behavior, System.Threading.CancellationToken cancellationToken)	Unknown
 	System.Data.dll!System.Data.SqlClient.SqlCommand.ExecuteDbDataReaderAsync(System.Data.CommandBehavior behavior, System.Threading.CancellationToken cancellationToken)	Unknown
 	System.Data.dll!System.Data.Common.DbCommand.ExecuteReaderAsync(System.Threading.CancellationToken cancellationToken)	Unknown
 	Akka.Persistence.Sql.Common.dll!Akka.Persistence.Sql.Common.Journal.JournalDbEngine.ReplayMessagesAsync(string persistenceId, long fromSequenceNr, long toSequenceNr, long max, Akka.Actor.IActorRef sender, System.Action<Akka.Persistence.IPersistentRepresentation> replayCallback)	Unknown
 	Akka.Persistence.SqlServer.dll!Akka.Persistence.SqlServer.Journal.SqlServerJournal.ReplayMessagesAsync(string persistenceId, long fromSequenceNr, long toSequenceNr, long max, System.Action<Akka.Persistence.IPersistentRepresentation> replayCallback)	Unknown
 	Akka.Persistence.dll!Akka.Persistence.Journal.AsyncWriteJournal.HandleReplayMessages(Akka.Persistence.ReplayMessages message)	Unknown
 	Akka.Persistence.dll!Akka.Persistence.Journal.AsyncWriteJournal.Receive(object message)	Unknown
 	Akka.dll!Akka.Actor.ActorBase.AroundReceive(Akka.Actor.Receive receive, object message)	Unknown
 	Akka.dll!Akka.Actor.ActorCell.ReceiveMessage(object message)	Unknown
 	Akka.dll!Akka.Actor.ActorCell.Invoke(Akka.Actor.Envelope envelope)	Unknown
 	Akka.dll!Akka.Dispatch.MessageDispatcher.Dispatch(Akka.Actor.ActorCell cell, Akka.Actor.Envelope envelope)	Unknown
 	Akka.dll!Akka.Dispatch.ConcurrentQueueMailbox.Run.AnonymousMethod__0()	Unknown
 	Akka.dll!Akka.Actor.ActorCell.UseThreadContext(System.Action action)	Unknown
 	Akka.dll!Akka.Dispatch.ConcurrentQueueMailbox.Run()	Unknown
 	Akka.dll!Akka.Dispatch.ThreadPoolDispatcher.Schedule.AnonymousMethod__0(object _)	Unknown
 	mscorlib.dll!System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown`

**Comment by Horusiath** [comment]
@sadprofessor isn't MutlipleActiveResultSets something, that you can simply enable through connection string params?

**Comment by sadprofessor** [comment]
@Horusiath Yes apparently you can. If the persistence code mandates it though it might be best to hardcode it? We started to see this as soon as we had more than one persistent actor.

**Comment by Horusiath** [comment]
This is not strictly a bug from akka itself - this problem may occur, once multiple persistent actors connected to the same journal will try to read/write to it at the same time. But we could actually create some log message warning about this behavior.

**Comment by rogeralsing** [comment]
@Horusiath is this still the case? or was it fixed by the connection per query fix?

**Comment by Horusiath** [comment]
I've added a log message (on WARNING level) if no *MultipleActiveResutSets* flag was set. But this is part of the persistence SQL queries PR.

**Comment by Danthar** [comment]
Close: PR was merged
