### ISSUE TITLE
Port EventBusUnsubscribers

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1296]
In JVM Akka, there is a `EventBusUnsubscribers` (https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/event/EventBusUnsubscribers.scala) 
Which deals with unsubscription from the eventstream for terminated actors.
We don't have that, so if an actor subscribes and then terminates, it will still be registered as a subscriber on the eventstream, thus propagating messages to deadletters.

I am marking this as a bug, because that is what the users are seeing. even if it in reality is more of a "not yet implemented" kind of problem.

**Comment by maxim-s** [comment]
I can try to do it

**Comment by rogeralsing** [comment]
Merged, closing
