### ISSUE TITLE
Round Robin Router Pool restarting all child actors

### ISSUE THREAD

**Issue by AlanGRutter** [akkadotnet/akka.net#1307]
In my application I have defined a round-robin-pool router with 50 instances of an actor. I am deliberately throwing an exception in my child actor when it receives a message as part of trying to learn how the child actors are restarted by the router. 

I am using the default router supervisor strategy (which I believe is One-for-one) but I am seeing the PostStop function of my actors called 50 times. I was expecting it to be called just once.

**Comment by rogeralsing** [comment]
If I recall correctly, the default behavior for routers is to escalate only. Not the same as the "normal" default strategy.
Thus, router escalates to parent, router is restarted and recreates all its children

**Comment by AlanGRutter** [comment]
Roger,
Sorry ,so I'm confused by the documentation. In the section on Supervision withing the Routers section - it states

>Pool routers on the other hand create their own children. The router is therefore also the routee's supervisor.

>By default, routers use the OneForOneStrategy, so if a child dies, only that actor is restarted. If you want to change this behavior, the supervision strategy of the router actor can be configured with the SupervisorStrategy property of the Pool.

I am not throwing the exception in the router, but in one of its routees. According to the above doc reference, it should be managed by the router using a OneForOneStrategy and only the child that dies should get restarted.

**Comment by rogeralsing** [comment]
Ok sorry about that, the docs are out of date in that case.

the same esalate behavior exists in JVM Akka

```scala
object Pool {
  val defaultSupervisorStrategy: SupervisorStrategy = OneForOneStrategy() {
    case _ ⇒ SupervisorStrategy.Escalate
  }
}
```

Im marking this as a bug for the documentation

**Comment by rogeralsing** [comment]
https://github.com/akkadotnet/getakka.net/blob/master/src/docs/working-with-actors/Routers.md

>Pool routers on the other hand create their own children. The router is therefore also the routee's supervisor.
>By default, routers use the OneForOneStrategy, so if a child dies, only that actor is restarted. If you want to change this behavior, the supervision strategy of the router actor can be configured with the SupervisorStrategy property of the Pool.

That section is not correct and needs to be updated.

**Comment by rogeralsing** [comment]
I've updated this
