### ISSUE TITLE
Stashing broken for messages overriding Equals operators

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1312]
See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/akkadotnet-user-list/FQz0ITYtd4E/xye6J9muCgAJ

In short. if a message overrides equals semantics, e.g. F# types, or custom c# types, or even built in types such as String will throw an exception if you try to stash two different messages with the same content, as they are both "equal".

The test should ofcourse check for reference equality, not value equality.
Stashing is an important feature and it is currently broken due to this issue, marking this as critical for this reason.

**Comment by rogeralsing** [comment]
See https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/Stash/Internal/AbstractStash.cs#L67

**Comment by Aaronontheweb** [comment]
@rogeralsing is this now fixed?

**Comment by rogeralsing** [comment]
yes
