### ISSUE TITLE
Resolve<T> ???

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1318]
I found this bit of code today:

``` csharp
            try {
                Resolve.SetResolver(new TestResolver());
                var r = Sys.ActorOf(Props.CreateBy<Resolve<Echo2>>(), "echo"); //<--- the static member holding the resolver can change from the prev line to this line
                Assert.Equal("akka.test://remote-sys@localhost:12346/remote/akka.test/RemotingSpec@localhost:12345/user/echo", r.Path.ToString());
                r.Tell("ping", TestActor);
                ExpectMsg(Tuple.Create("pong", TestActor), TimeSpan.FromSeconds(1.5));
            } finally {
                Resolve.SetResolver(null);
            }
```

Whats the purpose of the `Resolve` class?
This is subject to race conditions.
If you set a static resolver in one test, and another test set it to something else, if they execute in parallel, things will end badly.

Global shared mutable state in a concurrency library :-1:

**Comment by Aaronontheweb** [comment]
Where is this in the actual library? Link please!

**Comment by rogeralsing** [comment]
The above code is from the RemotingSpec.cs
Resolve is part of Akka.dll

**Comment by Danthar** [comment]
Whats the status on this one ?

**Comment by rogeralsing** [comment]
IMO this needs to be redesigned, we can not have tests that run in parallel over global mutable state.
The only thing that prevents this from crashing right now is that all tests assign the same type of value to the mutable field.

**Comment by Aaronontheweb** [comment]
@rogeralsing this is from the `IndirectActorProducer` stuff, right?

**Comment by Aaronontheweb** [comment]
Going through some old issues today - we deleted this class a while back.
