### ISSUE TITLE
F# null bug unit test does not pass

### ISSUE THREAD

**Issue by raymens** [akkadotnet/akka.net#1326]
The test `actor that accepts _ will receive unit message` located in `/src/core/Akka.FSharp.Tests/ApiTests.fs` does not pass.

The test just hangs forever (or whatever the default timeout is) without the timeout.

```fsharp
//[<Fact>]
// FAILS
let ``actor that accepts _ will receive unit message`` () =    
    let timeoutConfig =
        """
        akka { 
            actor {
                ask-timeout = 5s
            }
        }
        """
        |> Configuration.parse 

    let getWhateverHandler (mailbox : Actor<_>) _ = 
        mailbox.Sender() <! "SomethingToReturn"

    let system = System.create "my-system" timeoutConfig
    let aref = spawn system "UnitActor" (actorOf2 getWhateverHandler)

    let response = aref <? () |> Async.RunSynchronously
    response
    |> equals "SomethingToReturn"
```

Related issue #1285 and PR #1317

**Comment by rogeralsing** [comment]
@Horusiath is this one resolved by the removal of the Json hack?

**Comment by Horusiath** [comment]
I'm not 100% sure, but it seems that `()` alone may be interpreted like null, and sending null as a message is not allowed.

**Comment by rogeralsing** [comment]
So is this a bug or just a changed behavior?
`Null` or `()`was never intended to be used as a message so the behavior is undefined IMO.

**Comment by Horusiath** [comment]
I think we can close this one. General resolution: `null` equivalent values are not valid messages and shouldn't be used as such for actor communication.

**Comment by raymens** [comment]
So what is the recommended way of sending an empty message, that may be used to wake-up recurring processes? The sending of `()` was perfect for a background scheduler.

**Comment by Horusiath** [comment]
@raymens any message will do. You can easily pass some constant literal or dedicated `WakeUp` message.
