### ISSUE TITLE
SQL Persistence new transaction failure

### ISSUE THREAD

**Issue by sadprofessor** [akkadotnet/akka.net#1327]
JournalDbEngine:InsertInTransactionAsync

The call to create a new transaction in the using block can fail with 

    A first chance exception of type 'System.Data.SqlClient.SqlException' occurred in System.Data.dll

    Additional information: New transaction is not allowed because there are other threads running in the session.

**Comment by ashshak** [comment]
Just to add, I have noticed theses issues as well, and they started occurring after I made two actors persistent; it worked smoothly for one PersistentActor in the journal.

**Comment by Aaronontheweb** [comment]
Sounds like an issue with concurrency around the SQL Driver. We should probably add a spec to the Akka.Persistence.TestKit that tests for multiple actors writing to the journal, writing snapshots, recovering, and etc concurrently. I've noticed similar issues myself when recovering concurrently across multiple actors.

**Comment by Horusiath** [comment]
This seems to be the result of using single connection per journal combined with async ADO.NET methods utilization. This couldn't be discovered in original implementation, as JDBC doesn't offer async processing. As I understand the problem only occur when we try to do multiple writes, before the previous transaction ends.

Maybe the solution for that would be to introduce the state machine for sql journal combined with write messages stashing. Lets say, introducing `ready`/`pending` behaviors to sql journal. `pending` behavior is tirggered by building transaction. During it, all write request would be stashed and only reads are handled. When transaction ends, behavior switches to `ready` and next message gets unstashed.

**Comment by Horusiath** [comment]
I think, this one is already solved from v1.0.5 (as each journal action uses separate SQL connection with dedicated transaction if necessary).
