### ISSUE TITLE
SQL Persistence no transaction on command

### ISSUE THREAD

**Issue by sadprofessor** [akkadotnet/akka.net#1328]
SqlServerJournal:ReadHighestSequenceNrAsync

This quite often throws:

    BeginExecuteReader requires the command to have a transaction when the connection assigned to the command is in a pending local transaction.  The Transaction property of the command has not been initialized.

**Comment by Horusiath** [comment]
I think, this is already solved (after 1.0.5 each journal operation works on separate SQL connection with dedicated transaction, if necessary).
