### ISSUE TITLE
Xamarin Android/iOS

### ISSUE THREAD

**Issue by Neftedollar** [akkadotnet/akka.net#1330]
Hi. can I use Akka.net with xamarin for Android or Xamarin for iOS?

**Comment by Silv3rcircl3** [comment]
Please use the Gitter room for further questions.

**Comment by Neftedollar** [comment]
@Silv3rcircl3 so should I ask a question that already was asked? Or where I can find that questions and answers without asking and waiting? I think Gitter is a bad idea.

**Comment by Silv3rcircl3** [comment]
@neftedollar yep, ask again in gitter chat, if you don't get an answer in some days, ask again. If you wait for someone to answer the question in this issue you probably have to wait forever ;-) Also we try to use issue for bugs, feature requests or discussion but not for "simple" questions.

**Comment by Neftedollar** [comment]
@Silv3rcircl3 ok, i'll undersrand now

**Comment by Neftedollar** [comment]
I*
