### ISSUE TITLE
Akka.Cluster.Routing.ClusterRouterGroupSettings Mono Linux issue

### ISSUE THREAD

**Issue by evertmulder** [akkadotnet/akka.net#1332]
When creating a cluster router in code the following code works perfectly on windows but fails when running under linux mono
```csharp
using Akka.Cluster.Routing;
using System;
using System.Collections.Immutable;

namespace MonoTestClusterRouterGroupSettings
{
    class Program
    {
        static void Main(string[] args)
        {
            var test = new ClusterRouterGroupSettings(10, false, "sink", ImmutableHashSet.Create("/user/blocklist"));
            Console.WriteLine("OK {0}", test.RouteesPaths.Count);
            Console.ReadLine();
        }
    }
}
```
Running under mono in windows I get the expected OK 1, running under Linux I get 
```
Unhandled Exception:
System.ArgumentException: routeesPaths [/user/blocklist] is not a valid relative actor path.
Parameter name: routeesPaths
  at Akka.Cluster.Routing.ClusterRouterGroupSettings..ctor (Int32 totalInstances, Boolean allowLocalRoutees, System.String useRole, System.Collections.Immutable.ImmutableHashSet`1 routeesPaths) [0x00000] in <filename unknown>:0
  at MonoTestClusterRouterGroupSettings.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: routeesPaths [/user/blocklist] is not a valid relative actor path.
Parameter name: routeesPaths
  at Akka.Cluster.Routing.ClusterRouterGroupSettings..ctor (Int32 totalInstances, Boolean allowLocalRoutees, System.String useRole, System.Collections.Immutable.ImmutableHashSet`1 routeesPaths) [0x00000] in <filename unknown>:0
  at MonoTestClusterRouterGroupSettings.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
```
Tested on Rasbian Linux and Ubuntu 12.04.
Used Akka.Cluster.1.0.5.86-beta

**Comment by Aaronontheweb** [comment]
leading slashes for the win here

**Comment by Aaronontheweb** [comment]
In more detail - "/user/blocklist" is a valid absolute path on Linux. It's a valid relative path on Windows.

Hmmm.... We need to make this workable with Linux... Let me take a look at ClusterRouterGroupSettings.

**Comment by evertmulder** [comment]
Looking at the Akka Jvm implementation http://doc.akka.io/docs/akka/snapshot/scala/cluster-usage.html for example /user/actor in the Akka world is relative. If we run akka on windows or linux should not change this. 

The code in /src/core/Akka/Actor/Address.cs 
if(Uri.IsWellFormedUriString(addr, UriKind.Absolute) || (!Uri.IsWellFormedUriString(addr, UriKind.Relative) 

Is most likely the cause. Perhaps introducing a helper method that only checks actorpaths and not Uri's. I'm not sure how the jave Url.IsAbsolute behaves differently from the DotNet Uri.IsWellFormedUriString. 

I can do some testing on this.

**Comment by evertmulder** [comment]
Ok, found a solution that work both on windows and Linux and also handles the weird behavior when using a hashtag in the Url.

This works:
```csharp
  bool isRelative = Uri.TryCreate(ap, UriKind.Relative, out uri);
```
This does not work, "/user/actor" is resolved as absolute path on Linux (mono)
```csharp
  bool isRelative = !Uri.TryCreate(ap, UriKind.Absolute, out uri);
```
This does not work, "/user/actor#123" is resolved as absolute path by c# dotnet windows (but work on Linux)
```csharp
  bool isRelative = Uri.IsWellFormedUriString(ap, UriKind.Relative);
```

This does not work, "/user/actor" is resolved as absolute path on Linux (mono)
```csharp
  bool isRelative = !Uri.IsWellFormedUriString(ap, UriKind.Absolute);
```

I will create a PR to fix this

**Comment by Aaronontheweb** [comment]
Thanks for fixing this @evertmulder !

**Comment by krgn** [comment]
Would it be possible to cut another prerelease that inlcudes this fix? I'd have to migrate my paket config to use github for all of Akka, which I'd prefer not to have to do. Thx!

**Comment by Aaronontheweb** [comment]
@krgn we're going to be doing another release today or tomorrow hopefully

**Comment by krgn** [comment]
@Aaronontheweb cool, thx!
