### ISSUE TITLE
Akka.IO frequent GC's

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1334]
This might very well be a non issue.
But I'll bring it up anyway.

When running Akka.IO, just listening for connections.
There are a lot of GC hits going on, see image:
![gcpauses](https://cloud.githubusercontent.com/assets/647031/10131006/39b0c69e-65cd-11e5-8ab4-e508121451b0.png)

Those GC ticks does not occur when running e.g. an Akka.Cluster or any other modules.
I only see this when enabling an Akka.IO.

It looks weird and it might be worth investigating.

**Comment by annymsMthd** [comment]
I've noticed this using Akka.IO as well

**Comment by willieferguson** [comment]
I could not replicate this in my environment. Are you using the TCP driver and just binding, i.e are you just doing this:

```csharp
Context.System.Tcp().Tell(new Tcp.Bind(Self, new IPEndPoint(IPAddress.Any, x)));
```

The selection loop currently allocates 2 collections for each iteration of the loop, which is the most likely  cause. Reusing the collections should solve the issue. I will run more tests.

**Comment by rogeralsing** [comment]
Here is the code that I found it in:
https://github.com/rogeralsing/AkkaFsMud/blob/master/FSharpMud/TcpServer.fs#L79

its possible to DL the entire example and just start it and the behavior will be visible after a few sec.
You dont need to connect with anything, its the listener that causes it.

**Comment by willieferguson** [comment]
This issue is resolved in the dev branch, although I'm not sure why. Will dig deeper.

**Comment by rogeralsing** [comment]
as this is fixed (unknown why) but still, I will close this

**Comment by willieferguson** [comment]
The high number of allocations which causes the Gen 1 collections is in Socket.Select. 

Changeset 4af2cfbcaafa33ea04a1a8b1aa6486e78bd6f821 changes the behavior of the select loop to wait for 1ms, which has caused the number of allocations to drop.

Ultimately we'll have to move away from Socket.Select. I'm investigating alternatives, but the most obvious choice it to move to async sockets (with SocketAsyncEventArgs). 

Other interesting alternatives are:
- libuv: The ASP.NET team use libuv in [kestrel](https://github.com/aspnet/KestrelHttpServer)
- Registered IO: Kestrel had some [promising results](https://github.com/aspnet/benchmarks) with RIO

**Comment by rogeralsing** [comment]
:+1:

**Comment by Aaronontheweb** [comment]
Go with the most absolutely lightweight option -'SocketSsyncEventArgs'. No reason to add any dependent assemblies.
