### ISSUE TITLE
Unable to use Ask() extension method with cluster round-robin-group router

### ISSUE THREAD

**Issue by d--g** [akkadotnet/akka.net#1343]
I am not able to use the Ask extension method targeted at a cluster round-robin-group router? E.g.

`var testRouter = Context.System.ActorOf(Props.Empty.WithRouter(FromConfig.Instance), "testrouter");
var result = await testRouter.Ask<string>("SampleMessage", TimeSpan.FromSeconds(5));`

I am currently getting. **'Akka.Routing.RoutedActorRef' does not contain a definition for 'Ask'**

Hocon config under akka.actor.deployment:

```
/testrouter {
	router = round-robin-group
	routees.paths = ["target-actor-path"]
	nr-of-instances = 2
	cluster {
		enabled = on
		allow-local-routees = off
		use-role = testrole
	}
}
```

**Comment by Horusiath** [comment]
@d--g `Ask` is an extension method, which can be found in Akka.Actor namespace.

**Comment by d--g** [comment]
@Horusiath, thanks for the response. I have the namespace in the `using Akka.Actor;` and I am able to see the extension method through intellisense. My code also compiles without an issue. The issue comes when I hit the line at run time.

**Comment by Aaronontheweb** [comment]
Looking into it - going to write a spec for it at least.

**Comment by rogeralsing** [comment]
http://stackoverflow.com/questions/17023523/a-does-not-contain-a-definition-forb-and-no-extension-method-b-accepting

I'm not confident that the descrption of the problem is correct here.
The actual error message _is_ a compile time message.
And it shows when the extension method is applied to the wrong type.

**Comment by d--g** [comment]
@rogeralsing, @Aaronontheweb, Thank you for reviewing and proving out via the Specs that the Ask extension method works with a clustered router as expected.

The code is executed within a NancyFX async Get[] request. I think the issue is as mentioned a compiler issue due to the nature of the compilation of these methods.
