### ISSUE TITLE
Nuget'ify HOCON

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1354]
As our plan is to extract HOCON from this repo to it's own library, (progress here https://github.com/akkadotnet/HOCON) we need to set up build scripts and Nuget'ify it.

Any help here would be welcome.

**Comment by alexpantyukhin** [comment]
I will do this.

**Comment by rogeralsing** [comment]
:+1:

**Comment by Aaronontheweb** [comment]
How's this going?

**Comment by rogeralsing** [comment]
This one is completed
