### ISSUE TITLE
AkkaIOTransport broken

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1357]
The AkkaIOTransport is broken is several ways.

1. Since the introduction of max frame size exceptions, the IO Transport does not read those settings and thus fails to send any messages
2. Connection back to the calling system seems to fail

I have tried this on the Chat examples in the main repo.

cc @willieferguson

**Comment by rogeralsing** [comment]
The reason the connection is not established in my case is that for some reason the remote system decides to resolve my "127.0.0.1" to "192.168.0.1" and tries to respond back to the resolved address.
If I just hack that part of the code to use 127.0.0.1 it does connect and the built in Chat example works fine.

I've also tried the same code in Akka.Cluster, where it _almost_ works, it does connect and moves any incoming worker node to UP, but then nothing more happens.

**Comment by willieferguson** [comment]
There are some issues I'm aware of in the IO Transport implementation, e.g. framing. Will look into these.
