### ISSUE TITLE
Having Actor's Children not destroyed more discoverable

### ISSUE THREAD

**Issue by ondrelogin** [akkadotnet/akka.net#1361]
I attended the Petabridge Akka.net October 1st training and one issue that popped up was how difficult to know that there was a way to not have to recreate Children Actors if the Parent died.  The current way is to override PreRestart and don't call base.PreRestart.  Which isn't descriptive and/or discoverable.

Possible Solutions/Recommendations
- Add new property: `protected virtual bool ShouldDestroyChildrenOnRestart { get { return true; }`
- Add new method: `protected virtual void DestroyChildren() { Context.GetChildren() .. }`
- Or Do Both of the above.

Here could be a sample of the new PreRestart:

```
protected virtual void PreRestart(Exception reason, object message)
{
  if (ShouldDestroyChildrenOnRestart) { DestroyChildren(); }
  PostStop();
}
```

The inner portion of the PreRestart would then get refactored out to a new method.

```
protected virtual void DestoryChildren()
{
  Context.GetChildren().ToList().ForEach(c => 
  {
    Context.Unwatch(c);
    Context.Stop(c);
  });
}
```

**Comment by rogeralsing** [comment]
cc, @akkadotnet/developers 
Should we do anything about this? 
Imo it drifts away from the JVM API without that much benefit. I do get the issue raised by the OP but maybe this should be handled by better documentation and examples?

**Comment by Horusiath** [comment]
I'm not great fan of increasing API complexity in this case. First of all, it's very rare behavior (personally I've never seen need for this) and second, it can be already handled using existing API - just needs a better description.
