### ISSUE TITLE
Write specs to verify Akka.Remote untrusted mode and trusted actorselection paths

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1365]
# Enable untrusted mode for full security of server managed actors, prevents
    # system messages to be send by clients, e.g. messages like 'Create',
    # 'Suspend', 'Resume', 'Terminate', 'Supervise', 'Link' etc.
    untrusted-mode = off
    
    # When 'untrusted-mode=on' inbound actor selections are by default discarded.
    # Actors with paths defined in this white list are granted permission to receive actor
    # selections messages. 
    # E.g. trusted-selection-paths = ["/user/receptionist", "/user/namingService"]   
    trusted-selection-paths = []

**Comment by maxim-s** [comment]
I can try

**Comment by Aaronontheweb** [comment]
Thank you sir - check the JVM source to see if there are specs already. I've looked before but can't remember :(

**Comment by Aaronontheweb** [comment]
Do you expect to have a PR in for this soon @maxim-s ? Giving you some alternative issues per #1475 ;)

**Comment by maxim-s** [comment]
@Aaronontheweb yes, it will be done today

**Comment by maxim-s** [comment]
PR #1535

**Comment by Aaronontheweb** [comment]
#1546 had to revert due to race failure in the spec - could you please review @maxim-s ?

**Comment by Aaronontheweb** [comment]
Reposting my comment from there, with links to the build log:

http://petabridge-ci.cloudapp.net/viewLog.html?buildId=3846&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetPrBuild&guest=1

**Comment by maxim-s** [comment]
PR #1552
