### ISSUE TITLE
VS.NET HOCON intellisense

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1369]
The current user experience with HOCON is pretty bad, there is no way to verify if your HOCON config is valid.
I would like to see a VS.NET plugin that gives us intellisense for Akka.NET HOCON configs.

There are a few options to consider.

1. We could make such plugin know about all the standard Akka.NET modules, e.g. Akka Actor, Akka.Remote, Akka.Cluster etc., So that intellisense take all the modules into consideration always.

2. Or, we could make the plugin check if the project that owns the config file has references to any of the different modules and query the modules for confg schema information, so that Akka.Remote feeds the plugin info on whats valid in the akka.remote { section.

I personally think the latter would be nicest, then we could add modules w/o changing the plugin itself.

We could probably use this as a base for the effort : https://github.com/madskristensen/JSON-Intellisense
There has to be at least some parts that can be reused or learned from there.

**Comment by rogeralsing** [comment]
Duplicate of #723

**Comment by Danthar** [comment]
Closing since its a duplicate
