### ISSUE TITLE
Invent HOCON Schema

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1370]
As an addition to #1369, it would be nice to have schema validation for HOCON files.
I think that would be fairly easy to accomplish too.

Assume we have some HOCON 
```
akka {
    foo = true
    bar {
         xyz = [1,2,3]
         baz = "hello"
         ooo = "Foo.Baz, Foo"
    }
}
```

We could probably describe this using a schema like this:

```
akka {
    foo = bool
    bar {
         xyz = [int]
         baz = string
         ooo = fqn
    }
}
```

then we can simply traverse both trees of HOCON and when we find a scalar value, we check if it is compatible with the type described in the same node in the schema.

There are ofcourse a lot things that isnt covered by this, but it could be a start and it would be fairly easy to implement in this form.
The Akka.NET configurations are never recursive so we could most likely go for a more naive approach than a full fledged XML like schema which needs to deal with recursion and repetitions.

**Comment by tintoy** [comment]
Just out of curiosity, would the design you have in mind be able to cope with something like [this](https://github.com/tintoy/akkadotnet-cluster-test/blob/master/AkkaDotNetClusterTest/App.config)?

Technically there are 3 "akka" nodes in the file (something that seems to be valid HOCON as far as I can tell) but they all have the same schema definition.
