### ISSUE TITLE
Slow to switch between debug and release builds

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1372]
I think this could have started with the Paket PR.
Switching between build modes comes with an 2 minutes freeze in VS.NET (not always, but often)

**Comment by Aaronontheweb** [comment]
Revert the Paket PR if that's the issue then - the problems it solves are pretty trivial compared to interrupting a developer's flow for two whole minutes.

**Comment by rogeralsing** [comment]
According to @Horusiath this have been a problem since pre- Paket.
I will try to revert locally later and see if it solves the problem

**Comment by Silv3rcircl3** [comment]
@rogeralsing Is this still an issue?

**Comment by rogeralsing** [comment]
Dont know if it is on my machine only, but for me it takes about a minute to switch

**Comment by Silv3rcircl3** [comment]
Seems so, I tried it on my machine before I closed the issue and it tooks between 5-10 seconds to switch between debug and release mode back and forth
