### ISSUE TITLE
Deployer does not support wildcards

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1375]
Java Akka supprts wildcards in deployments:

```js
        deployment {

            /foo/"*"/bar {
                router = round-robin-pool
                nr-of-instances = 5
                remote = ""akka.tcp://system2@localhost:8080""
            }
        }
```

There are two issues in Akka.NET here.

1. HOCON parser crashes on this.
2. We do not handle wildcards in the deployer even if we manage to get the wildcard into the path.

**Comment by Aaronontheweb** [comment]
Are you sure that your syntax is correct here? Because this code has worked for months in WebCrawler: https://github.com/petabridge/akkadotnet-code-samples/blob/master/Cluster.WebCrawler/src/WebCrawler.Service/App.config#L38

```
"/api/*/coordinators" {
									router = round-robin-pool
									nr-of-instances = 10
									cluster {
										enabled = on
										max-nr-of-instances-per-node = 2
										allow-local-routees = off
										use-role = crawler
									}
								}   
```

**Comment by rogeralsing** [comment]
The syntax is from a Scala example, I will check it out if it is just an hocon parsing issue then

**Comment by Aaronontheweb** [comment]
:+1:

**Comment by jenspettersson** [comment]
I was the one asking about this in gitter group and the syntax @Aaronontheweb shows works nice. 

However, trying to prefix the wildcard, like this `"/api/prefix-*/coordinators"` doesn't seem to work, but that's probably not supposed to work?

**Comment by rogeralsing** [comment]
There seems to be some problem with wildcards at toplevel elements.

`"/foo/*"` works fine, `"/*"` throws all over the place.
I'll dig into this

**Comment by rogeralsing** [comment]
Given that there is an actor called "remoteactor":

This works
```
            ""/*"" {
                router = round-robin-pool
                nr-of-instances = 5
            }
            ""/*/*"" {                
                remote = ""akka.tcp://system2@localhost:8080""
            }
```

This doesnt

```
            ""/*"" {
                router = round-robin-pool
                nr-of-instances = 5
            }
            ""/remoteactor/*"" {                
                remote = ""akka.tcp://system2@localhost:8080""
            }
```

But this does:

```
            /remoteactor {
                router = round-robin-pool
                nr-of-instances = 5
            }
            ""/remoteactor/*"" {                
                remote = ""akka.tcp://system2@localhost:8080""
            }
```

So it seems like if both parent and child are registered for deployment, both of them must match up.

**Comment by rogeralsing** [comment]
The problem exists in WildcardTree.cs.

I'm really not sure why it was designed the way it is.
it is a tree that holds a root node that then forks out for each `/element` found, and then every sub level branches out ontop of that.

The problem is when there is one `/*` and one `/remoteactor` , both matches the actor name "remoteactor", by design it walks the most specfic path, that is "/remoteactor", which in turn does not have any deployment associated with it (**see the above "This doesnt" section**) 

Thats why the parent / child deployment names needs to match up.
This does not feel right to me.

Going to compare this to scala

**Comment by rogeralsing** [comment]
This seems to be by design, our code matches the Scala code.
I'm going to give it a try on the JVM too to see if it actually behaves this way too just to make sure.

**Comment by rogeralsing** [comment]
Some of the problems I've seen here is related to #1376 , as one of the new actors there was affected by the deployment wildcards.

**Comment by rogeralsing** [comment]
I'm closing this as "by design" as this is how JVM Akka does it.
(#1376 has been fixed)
