### ISSUE TITLE
Inheriting OneForOneStrategy/AllForOneStrategy

### ISSUE THREAD

**Issue by michaelsync** [akkadotnet/akka.net#1384]
Both OneForOneStrategy and AllForOneStrategy have the comment saying that it can't be inherited. Could someone explain me why we can't do that? If it can't really be inherited then should both classes be marked as sealed classes? Thanks! 

`````
   /// <summary>
    ///     Class AllForOneStrategy. This class cannot be inherited.
    /// </summary>

**Comment by Horusiath** [comment]
Once, before 1.0 they were sealed classes. Now, they can be inherited, but the old comment remained.

**Comment by michaelsync** [comment]
haha. :) Thanks for the confirmation!
