### ISSUE TITLE
Message Between Two Cluster Nodes Fails And Raises Unhandled Exception

### ISSUE THREAD

**Issue by jjguzzardo** [akkadotnet/akka.net#1386]
When I attempt to send a message from an actor on one node to a router on another node, I get an exception regarding serialization that says invalid cast between Newtonsoft.Json.Linq.JObject and Newtonsoft.Json.Linq.JValue.  The cluster is healthy before the message is sent because I can see heartbeat messages going back and forth but the message fails to get sent with the exception cited above.  I have also included screenshots of the specific exception in the logs.

Sender configuration:
```
akka {
            # here we are configuring log levels
            log-config-on-start = on
            stdout-loglevel = INFO
            loglevel = INFO
            # this config section will be referenced as akka.actor
            actor {
              provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"
              debug {
                  receive = on
                  autoreceive = on
                  lifecycle = on
                  event-stream = on
                  unhandled = on
              }
            }
            # here we're configuring the Akka.Remote module
            remote {
              log-remote-lifecycle-events = INFO
              helios.tcp {
                  port = 0
                  hostname = "127.0.0.1"
              }
            }
            cluster {
              seed-nodes = ["akka.tcp://StockSystem@127.0.0.1:2551"]
            }
          }
```
Receiver configuration:
```
akka {
            # here we are configuring log levels
            log-config-on-start = on
            stdout-loglevel = INFO
            loglevel = INFO
            # this config section will be referenced as akka.actor
            actor {
              provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"
              debug {
                    receive = on
                    autoreceive = on
                    lifecycle = on
                    event-stream = on
                    unhandled = on
                }
                deployment {
                /stockWorkers {
                    router = round-robin-pool
                    nr-of-instances = 30
                    cluster {
                        enabled = on
                        allow-local-routees = on
                        max-nr-of-instances-per-node = 10
                    }
                  }
                }
            }
            # here we're configuring the Akka.Remote module
            remote {
              log-remote-lifecycle-events = INFO
              helios.tcp {
                  port = 2551
                  hostname = "127.0.0.1"
              }
            }
            cluster {
              seed-nodes = ["akka.tcp://StockSystem@127.0.0.1:2551"]
            }
          }
```

Shared message (in separate assembly) sent between both ndoes:
```
 [Serializable]
    public class InventoryMessage
    {
        public InventoryMessage(string message)
        {
            Payload = message;
        }

        public string Payload { get; }
    }
```

Receiver code:
```
 class Program
    {
        private static ActorSystem system;
        private static IActorRef workerPool;
        private static ILoggingAdapter loggingAdapter;

        static void Main(string[] args)
        {
            system = ActorSystem.Create("StockSystem");
            loggingAdapter = system.Log;

            workerPool = system.ActorOf(Props.Create<StockWorker>().WithRouter(FromConfig.Instance), "stockWorkers");

            system.AwaitTermination();

        }
    }

    public class StockWorker : ReceiveActor
    {
        private readonly ILoggingAdapter logger = Context.GetLogger();

        public StockWorker()
        {
            Receive<InventoryMessage>(m => Handle(m));
        }

        protected override void PreStart()
        {
            logger.Log(LogLevel.InfoLevel, $"Pre Start On {Self.Path}");
            base.PreStart();
        }

        protected override void PreRestart(Exception reason, object message)
        {
            logger.Log(LogLevel.InfoLevel, $"Pre Start On {Self.Path}");
            base.PreRestart(reason, message);
        }

        private void Handle(InventoryMessage message)
        {
            logger.Log(LogLevel.InfoLevel, $"Message received from {Sender.Path}");
        }
    }
```

Sender code:
```
internal class Program
    {
        private static ActorSystem system;
        private static ILoggingAdapter loggingAdapter;
        private static ActorSelection workerPool;
        private static Cluster cluster;

        private static void Main(string[] args)
        {
            system = ActorSystem.Create("StockSystem");
            loggingAdapter = system.Log;

            cluster = Cluster.Get(system);
            cluster.RegisterOnMemberUp(() =>
            {
                workerPool = system.ActorSelection("akka.tcp://StockSystem@127.0.0.1:2551/user/stockWorkers");
                workerPool.Tell(new InventoryMessage("0ADX124"));
            });

            system.AwaitTermination();
        }
    }
```
Image of exception message:

![error](https://cloud.githubusercontent.com/assets/100016/10649216/6cf4efe2-7808-11e5-90a0-a4215cc395ce.png)

The receiver exception was long so here's the top part of the receiver exception message:

![error-continued](https://cloud.githubusercontent.com/assets/100016/10649222/73b7770a-7808-11e5-9f25-ed519e071ba5.png)

**Comment by Horusiath** [comment]
I've tracked down the problem. Reason for this behaviour is that your `StockWorker` type definition is not known to all communicating parties. To fix it you could define it in the shared assembly. 

Besides, you may encounter problems with `public string Payload { get; }` signature in message type, as it seems that Newtonsoft.Json in version 7 (which is an actual one) seems not to be able to deserialize it properly, leaving default value. Changing signature to `public string Payload { get; private set; }` fixes the issue. Also you may decide to change message serializer for your custom messages.

Totally other question is, if in this type of scenario this knowledge about actor type is really necessary - @Aaronontheweb ?

**Comment by jjguzzardo** [comment]
Yes!  This did fix the issue for me.  Thank you!  I see what the issue was.  I was thinking Client/Server and since my client is a member of the cluster, as that is the only way to talk from a client to a sever right now, I didn't think to include the server based actors in my client code.  Since all nodes in a cluster are peer to peer, client/server was the wrong way for me to think about this and it probably makes sense that all nodes would need to know about all actors that could potentially be instantiated in the cluster.  However, how do we deal with API gateway situations?  In my case a web request comes into a NancyFX API gateway.  I would prefer that my web based gateway not have to be a node in the cluster as that doesn't seem to make design sense to me.  I would rather send messages to an actor from my API gateway from outside the cluster.  I know in JVM akka this can be done with Akka.IO, is that the same approach we should be using here?  Is it fully ported yet?

Thanks again for your help!  Really appreciate it!

**Comment by Horusiath** [comment]
@jjguzzardo 

You could communicate with cluster from actor systems not being part of cluster using something called ClusterClient, which is part of Akka.Cluster.Tools - unfortunately it's not released yet (it's in the final phases before pre-release version).

Another option is to communicate using Akka.IO - but in this case you'll need to handle messages directly from byte buffers.
