### ISSUE TITLE
Accessing ChildRestartStats from Decider

### ISSUE THREAD

**Issue by michaelsync** [akkadotnet/akka.net#1387]
Is there any way to access the ChildRestartStats from the customer decider? 

Basically, I like to use the different directive based on max retry. (E.g. Escalate after max retry. ) In ProcessFailture, we can use failedChildStats.RequestRestartPermission(,) to check whether we reach the max attempts or not.  

I look at this code. I think we can easily pass the failedChildStats instead of Child to Handle. I wonder whether it is possible to pass the failedChildStats to Handle in future. As it's not supported, how do I access the ChildRestartStats from the customer decider? Thanks! 

````
  public bool HandleFailure(ActorCell actorCell, Exception cause, ChildRestartStats failedChildStats, IReadOnlyCollection<ChildRestartStats> allChildren)
        {
            var child = failedChildStats.Child;
            var directive = Handle(child, cause);
            switch (directive)
            {
                case Directive.Escalate:
                    LogFailure(actorCell, child, cause, directive);
                    return false;
                case Directive.Resume:
                    LogFailure(actorCell, child, cause, directive);
                    ResumeChild(child, cause);
                    return true;
                case Directive.Restart:
                    LogFailure(actorCell, child, cause, directive);
                    ProcessFailure(actorCell, true, cause, failedChildStats, allChildren);
                    return true;
                case Directive.Stop:
                    LogFailure(actorCell, child, cause, directive);
                    ProcessFailure(actorCell, false, cause, failedChildStats, allChildren);
                    return true;
            }
            return false;
        }
````

**Comment by Danthar** [comment]
@michaelsync Have you perhaps gotten an answer via gitter chat (or otherwise) to this question? If not please direct your questions there, or otherwise post them on StackOverflow. You have a much higher chance to get an answer there.

We wish to keep the issue's log free of user questions, since its a bad place to ask them anyway. And between managing the real issues, questions like these fall between the cracks fairly easily.
Please note: If no response is given, i will close this issue in a few days.

**Comment by rogeralsing** [comment]
Could you please as this on stackoverflow.com? 
It would get more exposure from other users there and we get a better overview of issues here.
Thanks

**Comment by michaelsync** [comment]
yap. Thanks!
