### ISSUE TITLE
Messages not sent to a remote actor don't become dead letters.

### ISSUE THREAD

**Issue by takemyoxygen** [akkadotnet/akka.net#1390]
I was debugging dead letters in Akka.net and discovered that when a message is supposed to be sent to a remote actor and for some reason it's not sent (e.g. connection can't be established), the message is not sent to `DeadLetters`. I've found two reasons:
1. On `PostStop`, `EndpointWriter` sends content of `_prioBuffer` and `_buffer` to `_system.DeadLetters`, but it sends instances of `LinkedListNode<object>` instead of real messages.
2. `RemoteDeadLetterActorRef` doesn't do anything with messages it receives.

I can submit a pull request for this.

**Comment by Horusiath** [comment]
@takemyoxygen Thanks. It would be great if you'd like to submit PR for this one.

**Comment by Horusiath** [comment]
Closed by #1391
