### ISSUE TITLE
Add Become and BecomeStacked to ReceivePersistentActor

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1395]
It looks like `ReceivePersistentActor` is missing implementation of `Become` and `BecomeStacked` equivalent of the `ReceiveActor`. It should be implemented as well and work only on command receiver part of the persistent actor.

**Comment by Aaronontheweb** [comment]
awesome - glad to see this. I wanted some clarification around how `Become` works with the RPA and this helps me understand what the current behavior is.

**Comment by Danthar** [comment]
Closing this issue: A PR was merged
