### ISSUE TITLE
PersistenceExtension - CreatePlugin in race condition

### ISSUE THREAD

**Issue by Zetanova** [akkadotnet/akka.net#1397]
PersistenceExtension.SnapshotStoreFor() is creating the plugin with the help of Lazy<PluginHolder>.
But is not using the LazyThreadSafetyMode.ExecutionAndPublication Flag to lock the initializion Thread.

The Plugin SnapshotStore.sql-server will fail with Cause:
Akka.Actor.InvalidActorNameException: Actor name "akka.persistence.snapshot-store.sql-server" is not unique!

All Lazy<> Helper that initialize complex components should force the initializion to only once
with the help of LazyThreadSafetyMode.ExecutionAndPublication

**Comment by Danthar** [comment]
Closing this issue: A PR was merged
