### ISSUE TITLE
FAKE Build - unable to push NuGet packages to nightly or production NuGet feeds

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1399]
Since #1362 we've not been able to push any NuGet packages to our nightly MyGet feed, because the FAKE script for publishing packages wasn't updated to handle the switch from NuGet to Paket.

See relevant build errors in the log here:

http://petabridge-ci.cloudapp.net/viewLog.html?buildId=2551&buildTypeId=AkkaNet_AkkaNetUnstableNightlyBuilds&tab=buildLog#_focus=10680&guest=1

**Comment by Horusiath** [comment]
@Zetanova reported, that there are some problems with getting .pdb files for nightly builds. Could this be related?

**Comment by Horusiath** [comment]
Reason behind that is, that we are still using nuget package manager for publishing packages. This should be replaced with FAKE [Paket.push](http://fsharp.github.io/FAKE/apidocs/fake-paket.html) command. F# project scaffold does it by default - example [here](https://github.com/Horusiath/Akkling/blob/master/build.fsx#L142).
