### ISSUE TITLE
Akka.Persistence - update code base to akka JVM v2.4

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1402]
Since our akka persistence module has been ported, some changes occurred on the JVM side of it. One of them is introduction of `AtomicWrite` and `ReplayFilter`. Associated with them are abilities to replay corrupted events emitted by overlapping writers and to reject events before they are stored. 

**[EDIT: 2016.02.11]**

List of changes, that probably needs to be included:

- `Persist` on sequence of events should be renamed to `PersistAll` and works as `AtomicWrite` (new kind of message) - either all or none events should be written. If journal doesn't support that it should inform about it.
- Rejecting writes - jorunal can reject saving an event, informing persistent actor about it.
- Obsoleting isPermanent parameter in delete operations - it should be supported for backward compatibility, but for future versions all deletes would be considered a hard ones.
- `Deliver` support for `ActorSelection`.
- Removing `SyncJournal`.
- Renaming all messages with *Replay* prefix to corresponding *Recovery*-prefixed equivalents.
- Introduce `Recovery` config object.
- Sender reference on replayed events should be always DeadLetters.
- Remove `Saved` method from `SnapshotStore`.

Obsoleting persistent view is not possible at the moment - because we still don't have support for Akka.Streams.

**Comment by cconstantin** [comment]
@Horusiath what JVM version is the current code based on? 2.3? Knowing that version might make it easier to identify the differences.

**Comment by Horusiath** [comment]
It's somwhere in 2.3 - major code base comes from 1Q 2015, although some parts (like event adapters) have been added later.

**Comment by cconstantin** [comment]
@Horusiath I'm giving this update a try, will keep you posted.
