### ISSUE TITLE
Akka.net ActorSystem.AwaitTermination triggers DeathWatchNotification when no messages are sent on .NET 4.5.2

### ISSUE THREAD

**Issue by CreepyGnome** [akkadotnet/akka.net#1405]
This message is written to the console in the simplest of Akka.net sample applications.

> [INFO][11/3/2015 7:21:06 PM][Thread 0008][akka://TestActorSystem/user]
> Message DeathWatchNotification from akka://TestActorSystem/user to
> akka://TestActorSystem/user was not delivered. 1 dead letters
> encountered.

This is the very simple code, where all you do is create an actor, but you NEVER send any messages. 

    using System;
    using Akka.Actor;
    namespace AkkaNetTest {
        class Program {
            static void Main(string[] args) {
                ActorSystem testActorSystem = ActorSystem.Create("TestActorSystem");
                Console.WriteLine("Actor system 'TestActorSystem' created");
                IActorRef testActor = testActorSystem.ActorOf<TestActor>("Test");
                Console.WriteLine("Press a key to shutdown the 'TestActorSystem' actor system");
                Console.ReadKey();
                Console.WriteLine("Attempting to shutdown the actor system");
                testActorSystem.Shutdown();
                Console.WriteLine("Waiting for the actor system to terminate.");
                testActorSystem.AwaitTermination();
                Console.WriteLine("Actor system shutdown, press any key to exit");
                Console.ReadKey(); 
            }
        }
        public class TestActor : ReceiveActor { }
    }

The environment I am running in is:

>  - Windows 10 RTM build 10240 
>  - Visual Studio 2013 Update 5 
>  - Akka.Net via NeGet 1.0.4.12 
>  - Target framework .NET 4.5 
>  - Installed framework .NET 4.5.2
>  - Console Application 
>  - Any CPU

When you run this simple application the above Akka.net output occurs as soon as the `ActorSystem.AwaitTermination()` call is made.  

It occurs in all my Akka.net applications I try to create and I was able to get it to reproduce in this simple application. So if I send messages or I don't send them it always occurs. If you comment out the `IActorRef` line then you will not get the message since no actors where created.

This doesn't make any sense why this is happening. If any one can help with explaining why this happens and how to prevent it from happening even when there are no messages that were ever sent then I would appreciate it.

Originally posted on StackOverflow
http://stackoverflow.com/questions/33507519/akka-net-actorsystem-awaittermination-triggers-deathwatchnotification-when-no-me

**Comment by CreepyGnome** [comment]
In case it matters since I have VS 2015 installed as well .NET 4.6 is installed... could be incompatibility with 4.5.2 or 4.6 that isn't accounted for in Akka.net yet.

**Comment by Aaronontheweb** [comment]
@CreepyGnome you're calling `testActorSystem.Shutdown();` - this shuts down the `ActorSystem`. This kills off all of the actors, including the built-in system ones - so `DeathWatchNotification`s are fired as part of the shutdown and cleanup process. In this case the message you're seeing the the `/user` guardian actor shutting itself down, which doesn't get delivered because it's shutting down.

Not a bug and nothing to be worried about, as explained by the docs: http://getakka.net/docs/concepts/message-delivery-reliability#dead-letters-which-are-usually-not-worrisome

**Comment by CreepyGnome** [comment]
I am not sure I understand, I am new to Akka and trying to learn how to use it. When going through your bootcamp or other peoples samples that work for them, I ALWAYS get this on my box and it is freaking annoying as hell.

From a user/developer perspective I should not be getting any messages on my console from Akka about anything unless I write them to the console myself, or I tell Akka I want it to do this via giving it a logger or something.

Also from a user/developer perspective I would think that if I never send a message I should never get an anything stating it could not deliver a message.

Also this doesn't happen because of the Shutdown call it happens because of the AwaitTermination call. Which as I understand it should only block until everything is actually shutdown and terminated. 

If this is okay then why the heck is it logging something to the console that seems to be bad? I didn't hook up anything, didn't ask it to do this, didn't give it a logger or anything. Seems like it this is okay and normal then it should NOT tell me about it. 

Also why does this ONLY happen in very specific .NET versions and not others?

I still think there is a bug here.  

It is either that if this is really okay then Akka should not be telling me about it unless I ask it to tell me about "INFO" things. OR if this only happens in specific .NET versions and not others then there may really be an issue and it is something something unexpected  that it maybe shouldn't be.

**Comment by Aaronontheweb** [comment]
> From a user/developer perspective I should not be getting any messages on my console from Akka about anything unless I write them to the console myself, or I tell Akka I want it to do this via giving it a logger or something.

This is what you have in the default configuration options

```json
akka {
  # Akka version, checked against the runtime version of Akka.
  version = "0.0.1 Akka"
 
  # Home directory of Akka, modules in the deploy directory will be loaded
  home = ""
 
  # Loggers to register at boot time (akka.event.Logging$DefaultLogger logs
  # to STDOUT)
  loggers = ["Akka.Event.DefaultLogger"]
 
  # Loggers are created and registered synchronously during ActorSystem
  # start-up, and since they are actors, this timeout is used to bound the
  # waiting time
  logger-startup-timeout = 5s
 
  # Log level used by the configured loggers (see "loggers") as soon
  # as they have been started; before that, see "stdout-loglevel"
  # Options: OFF, ERROR, WARNING, INFO, DEBUG
  loglevel = "INFO"
 
  # Log level for the very basic logger activated during AkkaApplication startup
  # Options: OFF, ERROR, WARNING, INFO, DEBUG
  stdout-loglevel = "WARNING"
 
  # Log the complete configuration at INFO level when the actor system is started.
  # This is useful when you are uncertain of what configuration is used.
  log-config-on-start = off
 
  # Log at info level when messages are sent to dead letters.
  # Possible values:
  # on: all dead letters are logged
  # off: no logging of dead letters
  # n: positive integer, number of dead letters that will be logged
  log-dead-letters = 10
 
  # Possibility to turn off logging of dead letters while the actor system
  # is shutting down. Logging is only done when enabled by 'log-dead-letters'
  # setting.
  log-dead-letters-during-shutdown = on
}
```

Turn this to `akka.log-dead-letters-during-shutdown = off` if you don't want to see them.

>Also from a user/developer perspective I would think that if I never send a message I should never get an anything stating it could not deliver a message.

That's because these are system messages that Akka uses to control the actor hierarchy. You didn't send them, but when you called `ActorSystem.Shutdown` then a series of `Stop` commands are automatically sent down the entire hierarchy so every actor can attempt to shutdown. This includes built-in actors.

> Also this doesn't happen because of the Shutdown call it happens because of the AwaitTermination call. Which as I understand it should only block until everything is actually shutdown and terminated.

The `AwaitTermination` forces the system to wait until the `RootGuardianSupervisor` receives at least one `DeathWatchNotification` - either from the root `SystemGuardian` or the `UserGuardian` actors. You don't normally see this if you just call `Shutdown` in trivial applications because the system doesn't block until this message gets received and the program just exits. The behavior is different because you're basically waiting to get confirmation that everything has actually shutdown - in Akka.Remote for instance all network transports get closed between `ActorSystem.Shutdown` being called and `ActorSystem.AwaitTermination` returning true.

> Also why does this ONLY happen in very specific .NET versions and not others?

Shutting down the system includes inherently racy behavior - you could get different results with the same platform. As for why it varies across different .NET runtimes. If you're using RyuJit or .NET 4.5.2 IL that's optimized differently then sure - this might come up. We develop and test for .NET 4.5  using LegacyJIT - we make no guarantees for anything else.

> I still think there is a bug here, so a little premature to close in my opinion.

The docs I linked to explain this pretty clearly.

**Comment by CreepyGnome** [comment]
@Aaronontheweb I think the bug is in the DEFAULT behavior then that you ship with then. 

There is a bug here. I mean if you are upsetting a user, or worse yet a potential user, about something going on with your product then there is a bug. How you want to define the bug shouldn't matter and you should write it off and just close it out and try to walk away. 

As no amount of googling or stackoverflow found me that you even have a configuration settings like you just shown. That I pointed this issue out in a bug against your bootcamp and because of this issue I walked away from Akka.net and said its not worth it. So now that there are PluralSight training I started with those and the first thing I get in the beginning of the first intro demo is this error again. So it took way to long to get to the point of how I can TURN OFF THIS MESSAGE, and to even learn that its not a big deal message. Because to me as this happening EVERY TIME, there was never a demo or sample I ran where this didn't happen, that I said why would I use something that yells at me for just using the product in what appears to be a normal way.

Since  you are so unwilling to see that there is a real issue here I hope that eventually a google will stumble on this CLOSED, not fixed bug, and see how they can turn something off that shouldn't be enabled by default.

I mean why would you have something that is normal and okay be automatically logged to the console as you default really? Seems like system messages that are not delivered during a shutdown and await termination that the developer didn't send or care about in almost all situations in which the official guy says that these are "nothing to be worried about" shouldn't be shown in the first place then.

**Comment by CreepyGnome** [comment]
@Aaronontheweb also you providing a JSON looking string doesn't help me change the settings, I have been googling and reading your documentation however I can't find any way to programmatically change any of the akka configuration settings programmatically. I see how to use the app.config in a non-standard .NET way, and I don't see any exposed properties or methods for setting things on your Config class.  There was a small snippet that showed something about ConfigurationFactory.ParseString but it was an obscure example showing something with helios tcp.

I mean it seems like all I really need to do is change "loglevel" to ERROR and "stdout-loglevel" to ERROR and this message will not show because typically most default settings for logging are at the ERROR level, not INFO and maybe if you have category based logging you may set some categories to WARNING. However, setting "log-dead-letters-during-shutdown" to OFF doesn't see like a good idea, leaving it on and letting the system decided that if the dead letter is an ERROR log as error or WARNING log as that, and since it thinks the one I am getting is INFO changing the level to ERROR (or even WARNING) should solve this problem.

So I would suggest that the default for "loglevel" be no lower than WARNING and that this doing this would fix this BUG.

So I am going to keep googling to see if I can find something so I can programmatically change "loglevel" to ERROR and as I don't want to use the app.config for this.

**Comment by rogeralsing** [comment]
The defaults are taken straight from the JVM Akka default configuration.
This is one of the key foundations that was set early on during the project that we should follow JVM Akka as closely as possible.
The same goes for the ability to set configuration settings via code, we have ported the JVM Akka configuration module and that is what we are sticking to.
There are good reasons why we follow JVM Akka; It is a proven successful project so the default can not be that far off for most users and existing knowledge and resources can be re-used when using Akka on .NET.

@Aaronontheweb gave you a clear response on why this is happening and how you can handle it.

**Comment by CreepyGnome** [comment]
@rogeralsing So you are saying that because the Java one did it wrong the .NET one should too? So do I have to get the Java version to fix it before you guys will fix it? So the .NET version is 100% the same as the Java version with no changes? I mean I didn't see lower case method names or other Java specific things.

Yeah typically when projects have been ported from other languages to .NET they are reworked where it makes sense to be .NET like and follow its common and popular conventions. Regardless that is not the issue here. 

The issue is no default logging out of the box should ever be set to INFO.

**Comment by jasmh** [comment]
I read this thoroughly and while I understand the reasons, I'd just like to add that the `log-dead-letters-during-shutdown = off` doesn't seem to work, while `log-dead-letters = 0` does. I checked the latest source and the config setting log-dead-letters-during-shutdown is read in the Settings.cs into the `LogDeadLettersDuringShutdown` property, but that is not subsequently used anywhere. I'd still like to have them logged but not when the system is shut down. Is there anyway how this can currently be achieved or any plans to fix this in the future?

**Comment by MercedeX** [comment]
I got the same issue. It's a very very simple program I tried. just lists all the directories but it failed. all Self.Tell() shows dead letter messages and Woosh! system is down.

Let me list my program here so you can see the behavior:

` 
    class ListerActor: ReceiveActor
    {
        private int _counter = 0;

        public ListerActor()
        {
            Receive<string>((path) => Process(path));
        }

        private void Process(string path)
        {
            var permissions = new UserPermissions(path);
            
            if (permissions.CanRead)
            {
                WriteLine(path);

                if (permissions.CanList)
                    ProcessSubFolders(path);
                else
                    WriteLine("No permissions for child folders");
            }
            else
                WriteLine($"[No permissions] {path}");
        }

        private void ProcessSubFolders(string path)
        {
            try
            {
                WriteLine("Processing subfolders!");
                foreach (var child in (new DirectoryInfo(path)).EnumerateDirectories())
                {
                    Context.Self.Tell(child.FullName);
                    _counter++;
                }
            }
            catch (Exception ex)
            {
                var color = Console.ForegroundColor;
                Console.ForegroundColor = ConsoleColor.Red;
                WriteLine($"{path} : {ex.Message}");
            }            
        }
    }


        static void Main(string[] args)
        {
            var fileExplorer = ActorSystem.Create("FileExplorer");
            var lister = fileExplorer.ActorOf(Props.Create<ListerActor>(SupervisorStrategy.DefaultStrategy), "Lister");
            lister.Tell(@"C:\");
            while (Console.ReadKey().Key != ConsoleKey.Escape);
            fileExplorer.Terminate().Wait();
        }

    internal class UserPermissions
    {
        public UserPermissions(string path)
        {
            var folder = new DirectoryInfo(path);
            foreach(FileSystemAccessRule rule in folder.GetAccessControl().GetAccessRules(true, true, typeof(SecurityIdentifier)))
            {
                CanRead = (rule.FileSystemRights & FileSystemRights.Read) == FileSystemRights.Read;
                CanList = (rule.FileSystemRights & FileSystemRights.ListDirectory) == FileSystemRights.ListDirectory;
                CanTraverse = (rule.FileSystemRights & FileSystemRights.Traverse) == FileSystemRights.Traverse;
                CanReadPermissions = (rule.FileSystemRights & FileSystemRights.ReadPermissions) == FileSystemRights.ReadPermissions;
            }
        }

        public bool CanRead { get;  }
        public bool CanList { get; }
        public bool CanTraverse { get; }
        public bool CanReadPermissions { get; }
    }
`

**Comment by Horusiath** [comment]
@MercedeX I've run your code without issues (maybe except that `folder.GetAccessControl().GetAccessRules` can throw System.UnauthorizedAccessException`).
