### ISSUE TITLE
PingPong benchmark on multicore machines

### ISSUE THREAD

**Issue by AlexeyRokhin** [akkadotnet/akka.net#1412]
PingPong benchmark should be run with Server Garbage Collector on computers with several CPU.
I run benchmark on server with 4 AMD Operon (48 cores total).

Default configuration (Workstation GC):
![gc workstation](https://cloud.githubusercontent.com/assets/4499122/11029434/f9aa6006-86d7-11e5-912e-5d8a48c1f1d2.png)

Server GC (gcServer element with enabled="true" was added to runtime section):
![gc server](https://cloud.githubusercontent.com/assets/4499122/11029441/03908424-86d8-11e5-97e1-7daf7d2eb1d8.png)

You can see that Server GC sometimes allows 120M+ msg/sec.
Workstation GC provides 12M+ msg/sec.
Benchmark was executed as 64bit process.

Used CPU (4x)
![testserver](https://cloud.githubusercontent.com/assets/4499122/11029497/73751f84-86d8-11e5-9da5-fed07e3db8d2.png)

**Comment by rogeralsing** [comment]
Thanks! thats very valuable information, I have wondered this myself why the PingPong example behaves badly on some upscale computers.
127 mil messages per sec is fantastic!

**Comment by sean-gilliam** [comment]
Server GC is enabled in our current working branch as seen here

https://github.com/akkadotnet/akka.net/blob/v1.3/src/benchmark/PingPong/App.config#L4
