### ISSUE TITLE
Create Serializer compatibility test kit

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1414]
This is old idea of creating test suite for user defined serializers to be possibly used as Akka.NET default serializers. List of things the tests should cover:

- Support for surrogates (for `IActorRef` serialization/deserialization).
  - Support for surrogates inside generic collections - right now JSON.NET is not able to correctly deserialize i.e. `IDictionary<TSurrogated, TVal>` where `TSurrogated` is type using surrogates.
- Support for types with private fields and setters.
- Support for types with no parameterless constructors.
- Support for F# algebraic data types - discriminated unions.
- Support for type polymorphism - (instance should be deserialized directly into it's original type with regard to class inheritance, even when no cast was defined).
- Data type version tolerance.
- Support for types without specific contracts/annotations defined.

@rogeralsing anything more?

**Comment by rogeralsing** [comment]
* It needs to be context aware, so that surrogates can be resolved using the active actor system.

I'll fill in more if I come up with more requirements :-)

**Comment by Horusiath** [comment]
I'll start this one.

**Comment by rogeralsing** [comment]
There is a start for this in the new Wire PR

**Comment by rogeralsing** [comment]
See https://github.com/akkadotnet/akka.net/pull/1503/files#diff-4605a9d7ec982959b59efccc45c4e92bR14

**Comment by rogeralsing** [comment]
Can we consider this done? or do we need to add more to it?

**Comment by Horusiath** [comment]
I think we could. If we find some more cases to be included as part of serialization testkit, we just include them when demanded.
