### ISSUE TITLE
TestScheduler + CallingThreadDispatcher dependency

### ISSUE THREAD

**Issue by skotzko** [akkadotnet/akka.net#1417]
Currently, to use `Advance` / `AdvanceTo` and manipulate virtual time in tests via the `TestScheduler`, actors have to be created and explicitly configured to use the `CallingThreadDispatcher`. This can be seen in the [`TestScheduler.Tests`](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.TestKit.Tests/TestSchedulerTests.cs#L23).

Can we either document this better in the code, or do it automatically so that users don't have to do this themselves?

**Comment by sadprofessor** [comment]
Just to clarify technically you don't need to use the CallingThreadDispatcher to use the TestScheduler. What you do need it for is if you're testing that an actor schedules something when receiving a message. If you don't use it in that case the test becomes non deterministic - you may ask the scheduler to advance time before the actor being tested has scheduled the item.

I did try and make it more user friendly by adding a TestConfigs.TestSchedulerConfig but I see your point that it's something the user has to know to do. I'm not sure how it could be done automatically though.
