### ISSUE TITLE
Replace Akka.NET hocon impl with Akka.Hocon nuget

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1419]
We do have a nuget package for our extracted Hocon lib.
We should hook this up with the Akka.NET project so that Akka core uses this package instead.

One important thing is that we need to be backwards compatible as the config section points back to the Akka.dll in existing user code:

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="akka" type="Akka.Configuration.Hocon.AkkaConfigurationSection, Akka" /> <-- this bit needs to stay as users are already using it
  </configSections>
```

Other than that, I _think_ it should be pretty straight forward.

**Comment by alexpantyukhin** [comment]
I already do it.

**Comment by alexpantyukhin** [comment]
Hi! I think that it's possible way to use xslt transformation files to modify old .config files. This way we can just substitute type="Akka.Configuration.Hocon.AkkaConfigurationSection, Akka" with type="Akka.Configuration.Hocon.AkkaConfigurationSection, Akka.Hocon"

**Comment by rogeralsing** [comment]
Is it not possible to keep the `AkkaConfigurationSection` class  in core akka.net ?
(and not have it in the akka.hocon lib)

**Comment by alexpantyukhin** [comment]
It's okay if leave the `AkkaConfigurationSection` only in the core akka.net. But I worried that someone can use `AkkaConfigurationSection` class from the Akka.Hocon dll. (It seems that some people already downloaded from nuget.org and tried Akka.Hocon ).

**Comment by alexpantyukhin** [comment]
Also the `ConfigurationFactory` uses `AkkaConfigurationSection` for initialize Config from the .config file (method Load()). If we can remove this functionality then it's okay.

**Comment by alexpantyukhin** [comment]
@rogeralsing @Aaronontheweb  I have removed `AkkaConfigurationSection` from the Akka.Hocon repo. Is it possible to publish it on nuget? When it will be done I can finish replacing.

**Comment by jden123** [comment]
@rogeralsing I see that HOCON nuget package contains AkkaConfigurationSection but the sources do not. This class was deleted. Also ConfigurationFactory.Load() was deleted(b2db31685720de1ef2a124f19fc1051dc248ffef) but Load method is used in several places(ex: ActorSystem.Create).
Should the nuget package be updated before start working on the issue? Or should we revert removing?
If ConfigurationFactory.Load() is deleted we have to implement it in Akka(for instance like extension method).
If we revert the changes we can rename AkkaConfigurationSection(from HOCON) to HoconConfigurationSection. The HoconConfigurationSection will used in ConfigurationFactory.Load(). AkkaConfigurationSection(from Akka) inherits HoconConfigurationSection and works like alias.
I think the second suggestion is more solid. What do you think?

**Comment by rogeralsing** [comment]
Agree, lets go for the 2nd suggestion.
Doing so would still make things backwards compat, right? as the fully qualified name of the alias type would be the same as before.

**Comment by jden123** [comment]
@rogeralsing I added changes that we need to HOCON (https://github.com/akkadotnet/HOCON/pull/36). Please review. Then we need to update nuget package. And then I can continue with this issue.

**Comment by jden123** [comment]
@rogeralsing 
I've updated HOCON package. And try using the HOCON package in all the projects. ConfigurationFactory.Load() seems to work but there is an issue with ConfigurationFactory.Default() method. The method is in HOCON and it tries to load Default.conf resource from Assembly.GetExecutingAssembly(). It cannot find the configuration for Akka. 

It would be good if we can create a wrapper(ConfigurationFactory in Akka) for ConfigurationFactory(in HOCON) and delegates calls but we cannot because of naming conflict(both have the same name Akka.Configuration.ConfigurationFactory).

Another solution is to rewrite Hocon.Default() to look for all loaded assemblies. If find more than one resource throw exception.
But there are open questions: how to setup configuration resource name? Can we change Pigeon.conf to Default.conf?

**Comment by sean-gilliam** [comment]
see #2586 for further discussion
