### ISSUE TITLE
Any plans on supporting .NET Core?

### ISSUE THREAD

**Issue by caioproiete** [akkadotnet/akka.net#1420]
Hello,

Is there's any plans on start adding support for .NET Core at this point?

**Comment by rogeralsing** [comment]
Hi.

No, not at the moment, .NET Core is far too much of a moving target right now, we will get back to this in the future once things stabilize.

**Comment by caioproiete** [comment]
Thanks @rogeralsing.

I'd be keen to help with that. If/when there's any interest in starting a parallel branch.

**Comment by adamhathcock** [comment]
I have a branch that I occasionally update and post about here: https://github.com/akkadotnet/akka.net/issues/992

Just updated what I've ported to Akka 1.0.5
