### ISSUE TITLE
Race condition with Akka.Persistence FSM

### ISSUE THREAD

**Issue by maxim-s** [akkadotnet/akka.net#1426]
Looks like we have a race condition with Akka.Persistence FSMs:

http://petabridge-ci.cloudapp.net/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=2672#_focus=13023&guest=1

**Comment by Aaronontheweb** [comment]
Thanks @maxim-s !

**Comment by maxim-s** [comment]
looks like it's actor naming problem in the PersistentFSMSpec
