### ISSUE TITLE
Clean up files not used in project

### ISSUE THREAD

**Issue by akoshelev** [akkadotnet/akka.net#1428]
Hi,

I just realized there is a couple of files, possibly leftovers after refactoring, that could be deleted as they're not referenced from project file.

**Akka**
```
LocalActorRefProvider.cs /* Moved to ActorRefProvider.cs */
Utils\AtomicCounterLong.cs /* moved to Utils/Internal/AtomicCounterLong.cs  */
Utils\AtomicCounter.cs /* moved to Utils/Internal/AtomicCounter.cs */
```

May I delete them as unused files?

**Comment by Aaronontheweb** [comment]
Yes, looks like someone goofed when cleaning up those folders - virtually everything inside the Akka/Util root folder is no longer actually referenced by any projects in the solution. All of those files were moved to the relevant internals sub-folder. Please send along a PR to delete them.

**Comment by akoshelev** [comment]
@Aaronontheweb I've checked the whole Akka solution - here is the full list of unused files

```
Akka.TestKit.Tests\TestKit_Config_Tests.cs
Akka.TestKit.Tests\TestEventListenerTests\AllTestForEventFilterBase.cs
Akka.TestKit.Tests\TestEventListenerTests\AllTestForEventFilterBase_Instances.cs
Akka.TestKit.Tests\TestEventListenerTests\ConfigTests.cs
Akka.TestKit.Tests\TestEventListenerTests\CustomEventFilterTests.cs
Akka.TestKit.Tests\TestEventListenerTests\DeadLettersEventFilterTests.cs
Akka.TestKit.Tests\TestEventListenerTests\EventFilterTestBase.cs
Akka.TestKit.Tests\TestFSMRefTests\TestFSMRefSpec.cs
Akka.TestKit.Tests\TestKitBaseTests\AwaitAssertTests.cs
Akka.TestKit.Tests\TestKitBaseTests\RemainingTests.cs
```

All other files in Akka/Util folder seem to be used. Do we need to do anything with unused tests?
