### ISSUE TITLE
 PersistentFSMSpec.PersistentFSM_should_has_function_as_regular_fsm_on_state_timeout failure

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1432]
PersistentFSMSpec.PersistentFSM_should_has_function_as_regular_fsm_on_state_timeout	

http://petabridge-ci.cloudapp.net/viewLog.html?buildId=2730&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetPrBuild&guest=1

**Comment by Aaronontheweb** [comment]
cc @maxim-s

**Comment by maxim-s** [comment]
PR #1457 has been merged
