### ISSUE TITLE
MultiNodeTestRunner hangs writing output to disk

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1433]
Seen multiple permanent hangs on this call

Step 1/1: Writing test state to: D:\BuildAgent\work\49b164d63843fb4\TestResults\Akka.Cluster.Tests.MultiNode-635834684240011612.html

And also the JSON output call.

No exceptions are thrown AFAIK - just never completes. Only seen it happen on our build agents, and they're writing to a temporary D:\ drive on the local VM, although the output they write is later copied into the artifacts repository on the central buildserver.

Any ideas? cc @GraemeBradbury @schatekar

**Comment by schatekar** [comment]
Is the actor that writes html output waiting for a message that it never receives?

**Comment by Aaronontheweb** [comment]
Resolved by #1446 - not sure what the issue is exactly but @GraemeBradbury suspects it has to do with his `CallContext` changes to support AppDomain MN test runners.

**Comment by Aaronontheweb** [comment]
Looks like this isn't finished yet - getting some hangs on spec failures now

**Comment by Horusiath** [comment]
@Aaronontheweb what is the state of this issue? Wasn't it solved by @Silv3rcircl3 PR?

**Comment by Aaronontheweb** [comment]
Yep, should be resolved.
