### ISSUE TITLE
Add ability to use flat JSON config files as an alternative format instead of HOCON

### ISSUE THREAD

**Issue by philiplaureano** [akkadotnet/akka.net#1450]
Given that HOCON can be reduced to a set of key-value pairs, such as:

```
akka {
     some-setting-name = "some-setting-value"
}
```

is equivalent to 

akka.some-setting-name = "some-setting-value"

and the JSON would look like: 

```
{
  "akka": {
    "some-setting-name": "some-setting-value"
  }
}
```

Wouldn't it be simpler just to use a well-known parser such as JSON.NET to parse an array of key-value pairs instead of having to use just a custom HOCON parser? The reason why I'm asking is that having the config settings in JSON will make it easier to serialize and generate new configurations on the fly without having to write custom code to read/write the HOCON, and having automatically-generated config files is crucial to dynamically scaling up/down in a cloud (AWS) environment. In most cases, the deployment machines only have Windows Core, and they don't even have a UI.

**Comment by rogeralsing** [comment]
HOCON is tightly integrated with pretty much every component of Akka.NET (the same in Akka).
It would be a massive effort to change how the configurations are handled in the existing codebase.

Your best bet is to use `WithFallback` and just generate those parts that you need to change in the top level config and then provide the defaults in the fallback config.

**Comment by skotzko** [comment]
@philiplaureano wondering if you could auto-generate config files and store them somewhere else in the cloud, and then have your new nodes fetch those files as part of booting their `ActorSystem`s. Then you could fetch the new version and use `WithFallback` to some solid default setting.

**Comment by philiplaureano** [comment]
@andrew: Having a centralized config would solve part of the problem, but
based on what we've encountered in AWS so far, the biggest pain point that
we've had is getting the right IP Address + Port configuration set up for
each machine that we dynamically spin up once an autoscale event occurs.
Having a static HOCON config per machine makes sense if the machines never
change, but in a cloud environment, we operate on the assumption that any
machine can be easily replaced with a completely new instance, and that
machine may/may not have the same IP configuration as the one in the config
file.

That being said, it's fairly trivial to convert from a string key/value
pair collection to an equivalent HOCON file, so if it's too much work to be
done for Akka.NET, I'll be more than happy to contribute the sample code
that shows how easily it can be done.

I'm just putting this idea out there since this will open up ways to change
the configuration of an application without even touching a config file
(which may or may not be accessible in a cloud machine). As an outsider
looking in, broader question that I'm proposing is that based on what's
currently available in the .NET ecosystem (such as JSON.NET), do we really
need HOCON at all?

**Comment by rogeralsing** [comment]
I'm personally for replacing HOCON, as @philiplaureano points out, it is a pain to work with and we lack tooling around it in .NET land.
HOCON supports a lot of cool features like substitutions, imports and fallbacks. but in reality, it is pretty much only the fallback mechanism that is used in the real world.

But again, it is very tightly coupled with all parts of Akka.NET and also one of the things that make it possible for JVM devs to feel familiar with our port, and there is clear value in that too.

**Comment by manigandham** [comment]
@philiplaureano 

How are you setting the dynamic IP right now? And is it for the remoting public-hostname? We run on a few different cloud providers and just use a `WithFallback()` call to replace a specific key/value on startup:

```
var machinePrivateIpAddress = NetworkUtils.TryGetPrivateIp();
var actorConfig = ConfigurationFactory.Load().WithFallback("akka.remote.helios.tcp.public-hostname = " + machinePrivateIpAddress);
var actorSystem = ActorSystem.Create("Engine", actorConfig);
```

For EC2, private ip is just a HTTP GET at the metadata api: `http://instance-data.ec2.internal/latest/meta-data/local-ipv4` but the startup replace method above works for us on any provider to change specific settings.

I do agree that just sticking with normal JSON would be nicer and easier to deal though considering all the tooling around that, especially with the coming changes in the new .NET framework using JSON config files.

**Comment by marcpiechura** [comment]
We have no plans in dropping Hocon, so I’ll close this one. Feel free top reopen if nesssaccary.
