### ISSUE TITLE
send text file 133KB

### ISSUE THREAD

**Issue by tru3d3v** [akkadotnet/akka.net#1453]
Hi, is it possible if i send text file (133KB) from akka server to client Akka ?. i have try but client is not respond
public class HelloActor : UntypedActor
{
public HelloActor()
{
}
protected override void OnReceive(object request)
{
var data = System.IO.File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory+"myfile.txt");
Sender.Forward(data);
}
}
var actor = System.ActorSelection("HelloActor");
return await actor.Ask<string>(null, TimeSpan.FromHours(1));
is it to large for 133 KB txt file ?
and this is my config hocon at server
remote {
    log-sent-messages = on
    log-received-messages = on
    maximum-frame-size = 10MB

**Comment by rogeralsing** [comment]
Could you please as this on stackoverflow.com? 
It would get more exposure from other users there and we get a better overview of issues here.
Thanks
