### ISSUE TITLE
Ability to add supervisor strategy to router through config or extension method

### ISSUE THREAD

**Issue by melcloud** [akkadotnet/akka.net#1466]
Hello,

I would like to have the ability to add supervisor strategy to router through configuration file or at least expose it as an extension method on FromConfig like what Scala version did. 

Thanks

**Comment by alexvaluyskiy** [comment]
You can do it after this PR https://github.com/akkadotnet/akka.net/pull/2094
```C#
FromConfig.Instance.WithSupervisorStrategy(new OneForOneStrategy(ex => Directive.Restart)).Props()
```

**Comment by alexvaluyskiy** [comment]
Fixed https://github.com/akkadotnet/akka.net/pull/2103
