### ISSUE TITLE
NewtonSoftJsonSerializer.AkkaContractResolver.CreateProperty(MemberInfo, MemberSerialization)': no suitable method found to override

### ISSUE THREAD

**Issue by huoxudong125** [akkadotnet/akka.net#1467]
![qq 20151126105356](https://cloud.githubusercontent.com/assets/3151596/11414130/89ab5f1e-942c-11e5-8c1a-21859d4c6ad0.png)

**Comment by huoxudong125** [comment]
Is there a problem here in akka.project file?
```XML
 <Reference Include="Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\packages\Newtonsoft.Json.7.0.1\lib\net45\Newtonsoft.Json.dll</HintPath>
    </Reference>
```

**Comment by huoxudong125** [comment]
I solve the problem as follow [here](https://github.com/huoxudong125/akka.net/commit/d59883472767478a2615dc642b33ba9f7c540819),I believe there must be a better solution.

**Comment by huoxudong125** [comment]
@Aaronontheweb Is there a way to solve the problem about `Newtonsoft.Json.dll`? in the section <choose>(which is part of project file) how to auto change the path to right(real) path(nuget package file path). Is there a easy way?

**Comment by rogeralsing** [comment]
We have updated the dev branch, please check if the issue you are seeing is fixed

**Comment by huoxudong125** [comment]
@rogeralsing There is still a same problem in the  `Akka.DI.Unity` project  as follow:
>Severity	Code	Description	Project	File	Line
Error	CS0433	The type 'IUnityContainer' exists in both 'Microsoft.Practices.Unity, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.Practices.Unity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	Akka.DI.Unity	D:\TestProjects\GitHub\akka.net\src\contrib\dependencyInjection\Akka.DI.Unity\UnityDependencyResolver.cs	36

**Comment by rogeralsing** [comment]
Thanks, I'll take a look at that

**Comment by Silv3rcircl3** [comment]
Fixed.
