### ISSUE TITLE
Multiple edge-case issues in ActorTaskScheduler

### ISSUE THREAD

**Issue by JeffCyr** [akkadotnet/akka.net#1481]
I reviewed the ActorTaskScheduler and found multiple subtle issues:

##### The failing message is not set in ReceiveActor.PreRestart
see Actor_PreRestart_should_give_the_failing_message.

##### The actor can restart even if the exception is catched in an async receive
see Actor_should_not_restart_if_exception_is_catched.

##### ActorTaskScheduler can execute task concurrently
see ActorTaskScheduler_reentrancy_should_not_be_possible.
This one is bad, it is possible to execute a task in the ActorTaskScheduler concurrently when the actor is busy.

It's because of a wrong usage of CallContext to flow the state in the ActorTaskScheduler. CallContext is only restored in the Task's body, so it is possible that the CallContext has not yet been set in TaskScheduler.QueueTask.

I created a LinqPad gist to expose the issue: https://gist.github.com/JeffCyr/9c0864c0d3d1b31c7823

**Comment by rogeralsing** [comment]
:+1: well spotted
