### ISSUE TITLE
Fix Akka.Persistence.Sqlite default config entry

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1488]
This is easy, but I want to keep track on it. [Default HOCON config for sqlite](https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/persistence/Akka.Persistence.Sqlite/sqlite.conf#L7) contains wrong type name for the journal. Fix it and make sure that all of the type names for journals and snaphot stores are correct.

**Comment by Silv3rcircl3** [comment]
I can do this.
Do you mean the names of all other persistence plugins or just in the sql project?

**Comment by Horusiath** [comment]
Right now I've seen this problem in Sqlite, but I haven't check elsewhere. Note: Sqlite persistence plugin has been incorporated into akka core repo, so fix should be applied right here.

**Comment by Silv3rcircl3** [comment]
I have checked the other persistence plugins and couldn't find any typos.
The only thing I found strange is the plugin name from the cassandra plugin
```
akka.persistence.journal.plugin = "cassandra-journal"
```
Is this correct ?

**Comment by Horusiath** [comment]
It's not following our convention, but actually it's correct in the context of the Akka.Persistence.Cassandra plugin.
