### ISSUE TITLE
TestKit memory leak

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1498]
When running the tests for the Akka.NET project, there are often a handful of tests that fail with out of memory exception.

I have investigated this a bit further and the problem is not in the failing tests, but rather somewhere in the ActorSystem or TestKit.

Each tests will leak a little bit of memory until the last tests eventually go OOM.
I have verified this by adding a memory check into the before test setup in testkit, that throws if the memory is above a certain threshold.
depending on the threshold, one can see that the x first tests pass, and everything after that starts to fail.

We need to find what is eating memory for each test that runs.
I'm currently out of ideas myself on how to mem profile the testkit.

**Comment by Aaronontheweb** [comment]
FYI, memory leaks within Akka.Remote using the `TestTransport` can be solved using the same fix from #1556

**Comment by rogeralsing** [comment]
![mem1](https://cloud.githubusercontent.com/assets/647031/11914208/f4ab59ae-a679-11e5-8da6-15bd33d2fe81.png)

It looks like there are different issues causing this.
For example `ReceivePersistentActorTests` gives a big spike and `ParsingSpec` gives a small spike.

**Comment by rogeralsing** [comment]
![mem2](https://cloud.githubusercontent.com/assets/647031/11914233/c5091e6a-a67a-11e5-8fb9-56a02b026307.png)

From another run.

Cluster tests are consistently leaking a small amount of memory.
Persistence tests are consistently leaking more memory.
And ParsingSpec also triggers a small spike again.

**Comment by rogeralsing** [comment]
cc @Horusiath any idea what can make the persistence tests leak?
Are there any in mem storage that is not cleared? non closed connections?

**Comment by rogeralsing** [comment]
![mem3](https://cloud.githubusercontent.com/assets/647031/11914270/3200803e-a67c-11e5-96e5-00cb786a5b77.png)

Run 3

**Comment by rogeralsing** [comment]
Same pattern.

ParsingSpec, small spike.
Persistene tests, big spike and leaks.

(tests does contain different tests as the test runner seems to chose randomly and the OOM error breaks the tests after different number of test runs.

**Comment by rogeralsing** [comment]
I would guess that the small spike in ParseSpec is the result from compiling regex . so that one is probably not an issue, more a fact that regex does eat memory

**Comment by rogeralsing** [comment]
![mem4](https://cloud.githubusercontent.com/assets/647031/11917860/ae88900e-a719-11e5-846b-08dfbb3f4012.png)

The plot thickens...
When running using the command line build `build runtests`
We see a clear memory dump after each test assembly have been executed.
While we see the same memory retention build up for tests within the same assembly.

My guess is that when running the VS.NET runner, all tests are executed in the same process. while the cmdline runner uses an app domain or process per assembly.

**Comment by rogeralsing** [comment]
cc @bradwilson, any idea why we are seeing different results in the vs runner and the console runner?

**Comment by rogeralsing** [comment]
![mem5](https://cloud.githubusercontent.com/assets/647031/11917905/e0b975c4-a71a-11e5-9966-434bb0401eb3.png)

Here is the same graph but plotting the memory delta between tests intead of total memory.
This might give some more insight of what tests are the worst offenders.

**Comment by bradwilson** [comment]
This is https://github.com/xunit/xunit/issues/662

**Comment by bradwilson** [comment]
We just shipped 2.2 Beta 1, which should include the fix for this. Let me know if you see better results.

http://localhost:4000/release-notes/2015-12-20.html

**Comment by rogeralsing** [comment]
@bradwilson the memory build up we are seeing after each test, is that XUnit storing testresults or something like that?

We are seeing build up even on tests that just use method local data, e.g. collections and such.

I'm trying to figure out if our tests are actually leaking or if the build up is due to something else.
(except for problem before your fix that is)

**Comment by rogeralsing** [comment]
:+1:  @bradwilson , the new bits fixes the problem. all tests run nicely in VS.NET now.

**Comment by bradwilson** [comment]
@rogeralsing asked:

> the memory build up we are seeing after each test, is that XUnit storing testresults or something like that?

In particular, if you ask for XML, we will be stashing the XML for each test result, which could be fairly memory intensive.
