### ISSUE TITLE
Supervisorstrategy does not preserve stacktrace

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/akka.net#1499]
As reported by @stevemesser.
When an unhandled exception gets sent to the Supervisor strategy the stacktrace is not preserved.

This has to do with the way the ActorCell handles faults. It simply rethrows errors.
This can be resolved using the ExceptionDispatchInfo system. 

IMO its very annoying missing out on the stacktrace. Coincidently i've been bit by this yesterday. Ill pick this up myself and make a PR today.

**Comment by Aaronontheweb** [comment]
Resolved by #1500
