### ISSUE TITLE
OOM when cluster can't connect to a seed node

### ISSUE THREAD

**Issue by HakanL** [akkadotnet/akka.net#1506]
Unfortunately I don't have a clear test case yet, but I'm running a couple of Raspberry Pi in an akka.net cluster. If I have my "master" (seed-node) machine off for a few hours (it's a Windows PC, RPi connecting into it) then the process on the RPi starting to eat memory until it's used up all memory. If it's connected then it's fine, this only seems to happen when the cluster can't join, so it keeps retrying and eating a little memory each time.

**Comment by rogeralsing** [comment]
What version of Mono are you running on?

**Comment by HakanL** [comment]
Latest, 4.2.1

/Hakan

**Comment by rogeralsing** [comment]
Might be Mono only, I can't replicate this on .NET.
Steady memory consumption on .NET nodes when leader goes down.

**Comment by HakanL** [comment]
Ah, ok. Let me see if I can set up a simpler test (on Mono) and go from
there, I just noticed it on my RPis, I didn't have a chance to do a good
isolated test yet.

**Comment by Aaronontheweb** [comment]
@HakanL I think this is resolved now as of 1.1 - we had a memory leak in the logging system and that's been confirmed as resolved since.

**Comment by HakanL** [comment]
Ah good, thank you!
