### ISSUE TITLE
Message limit on ActorSelection's Ask<T>()? Can't seem to receive large (>50KB) responses from Ask<T>()

### ISSUE THREAD

**Issue by decius999** [akkadotnet/akka.net#1509]
Hey Guys

I´ve the exact same issue like described here:
https://github.com/akkadotnet/akka.net/issues/252

But I´m using Akka.Net Cluster 1.05.15.Beta and Helios 1.4.2.
Maybe the same issue occurs because I´m using Akka.Net Cluster which is still in beta phase.

So it doesn´t matter what I try to set for "send-buffer-size", "receive-buffer-size" or "maximum-frame-size", it seems to fail when the Message is bigger than ~50kb.

And I´m using ActorSelection with Ask<T>.

Can anybody help me out?

I also have the following configurations:

``` c#
using (var system = ActorSystem.Create(ActorModelConfigurationNames.ACTOR_SYSTEM_NAME))
 {
      var props = Props.Create<EffectCalculationActor>().WithRouter(new ClusterRouterPool(
               new RoundRobinPool(50),
               new ClusterRouterPoolSettings(1000, true, 1000)));
      var actor = system.ActorOf(props, ActorModelConfigurationNames.ACTOR_CALCULATION_NAME);

      Console.ReadKey();
 }
```

Thanks and Best Regards
decius

**Comment by Aaronontheweb** [comment]
@decius999 not sure offhand, but we'll look into this - hearing some similar reports to this one.

FYI - the issue in the cases I've reviewed so far had nothing to do with remoting. It was async / await issues with two things depending on each other waiting on an `Ask` that never comes.

**Comment by Aaronontheweb** [comment]
Could you please post some of the `Ask` code?

**Comment by decius999** [comment]
Hi Aaron
Thx for having a look into it. Here is the Ask Code:

```c#
public async Task<EffectTableDefinition> GetEffectsByTreeItemIdAsync(ActorSelection actor, int treeItemId)
{
     var result = await actor.Ask<EffectTableDefinition>(new EffectWrapperMessage(this.tenantService.TenantName)).ConfigureAwait(false);

     return result;
}
```

**Comment by decius999** [comment]
Do you have any hints for me?
Do you need more config files or Code samples? We want to use Akka.Net in production but we have to fix this issue first. Any help is appreciated. :) 

Best Regards

**Comment by Danthar** [comment]
@decius999 Did you by any chance resolved this issue in the meantime ? (through gitter chat support or otherwise?)

if not. What we need to help you with this is a sample of the code that handles the EffectWrapperMessage, and the code that responds back to with the EffectTableDefinition.
Basically we need to see enough of the code to be able to determine if its an bug in your code, or something else.
