### ISSUE TITLE
Test method naming format

### ISSUE THREAD

**Issue by Silv3rcircl3** [akkadotnet/akka.net#1510]
Currently there is not single convention about the naming format, some are written in [pascal case](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Tests/Actor/ActorSystemSpec.cs#L29) and others with [underscores](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Tests/Actor/ActorSystemSpec.cs#L65).

As discussed with @Horusiath and @rogeralsing, the underscore notation should be used.

**Comment by rogeralsing** [comment]
Related to that, should we care about this?

Arrange Act Assert
Given When Then

**Comment by Horusiath** [comment]
@rogeralsing I think, that when it comes to Akka specs, this is not always possible, as the tests are not unit tests in nature.

Also after 3 sentence long gitter chat on that topic I think, that we all agreed to use underscore case.
