### ISSUE TITLE
Akka.NET CI Structure Changes

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1512]
I can't take credit for this idea - it was something @schatekar suggested that we do in an Akka.Cluster contributor's meeting a while ago.

I would like to change the current build structure from an "all or nothing" build process to one that looks like this:

http://cloud.smartdraw.com/share.aspx/?pubDocShare=374D5BCD2206BDB3D23A4D1121F9D49F3F7

Idea is to improve the following:

1. **Make failures granular and obvious** - Going forward this will indicate where the build failed in Github's build step report on each PR, rather than one giant all-or-nothing red `X`.
1. **Run multiple build steps in parallel** - no need to wait for unit tests to run before we kick off the multi-node tests and performance tests. I'm not entirely sure how TC will accomplish this but I'm going to find out.
1. **Make the build process more extensible** - performance tests are a new category we're going to be adding to the build process soon. But who knows? Maybe we'll also add some additional static analysis at some point in the future. Purpose is to make that more explicit as independent CI steps rather than implementation details in FAKE.
1. **Support multiple-platform builds more easily** - whenever we support CoreCLR or Mono fixes their toolchain, this will make it easier to break out reporting by platform.

**Comment by Aaronontheweb** [comment]
Have an implementation of this up and running now.... Should have some samples soon :)

**Comment by schatekar** [comment]
+1

Wonderful.

And sorry, I could not get to finish this after proposing it.

Regards,
Suhas Chatekar
Skype - suhas.chatekar

**Comment by Aaronontheweb** [comment]
No worries @schatekar! This has been implemented, so closing it.
