### ISSUE TITLE
PipeTo creates an invalid Status.Failure object if task is cancelled

### ISSUE THREAD

**Issue by akoshelev** [akkadotnet/akka.net#1521]
The following code cause problems if `tresult` is cancelled
https://github.com/akkadotnet/akka.net/blob/e724d600283862fe78293c46aa62533fcc3a46a6/src/core/Akka/Actor/PipeToSupport.cs#L29 

``` c#
 if (tresult.IsCanceled || tresult.IsFaulted)
                    recipient.Tell(failure != null
                        ? failure((Exception)tresult.Exception)
                        // if tresult is cancelled, tresult.Exception == null
                        : new Status.Failure((Exception)tresult.Exception), sender);
...
```

If user does not handle this message in `recipient` actor and `akka.actor.debug.unhandled = true`, `NullReferenceException` is thrown, as `UnhandledMessageForwarder` calls `message.ToString()` 
https://github.com/akkadotnet/akka.net/blob/cf7cd6f274cd56af6403afc640a038564dc4d03b/src/core/Akka/Event/LoggingBus.cs#L235

`Status.Failure` does not check the input parameter and `ToString()` overload calls `Cause.ToString()` w/o checking for null.
https://github.com/akkadotnet/akka.net/blob/497442633c2ab91899668998d74d74f7e213e296/src/core/Akka/Actor/ActorBase.cs#L48

What'd be the correct way to fix this? I see a couple of possible fixes:
- Create a `TaskCancelledException` inside `PipeToSupport` class
- Extend `Status.Failure` and allow to create an instance without specifying an exception - maybe indicate that task was cancelled by passing a task instance

**Comment by rogeralsing** [comment]
>Extend Status.Failure and allow to create an instance without specifying an exception  - maybe indicate that task was cancelled by passing a task instance

Do note that the `Failure` class could be passed between nodes, and thus needs to serialize well.
So if we give it an overload for failed `Task` then we need to extract the exception information from it so that we do not hold a reference to the task itself.
Maybe I'm stating the obvious here but whatever solution we go for, `Failure` needs to be serialization friendly.

**Comment by Aaronontheweb** [comment]
> Create a TaskCancelledException inside PipeToSupport class

I've refactored to this method to do this like 3 times, but then I remember that the way it's designed currently is consistent with the JVM design and even enforced via unit test.

Frankly I think the JVM design here is pretty shitty - just throw an exception.

**Comment by akoshelev** [comment]
What if we just create a TaskCancelledException there? It won't break current design, although looks a bit weird, and I see similar code in other modules
https://github.com/akkadotnet/akka.net/blob/cf7cd6f274cd56af6403afc640a038564dc4d03b/src/core/Akka/Actor/Inbox.Actor.cs#L127

**Comment by guessmyname** [comment]
Hello.  Any word on a fix for this issue? I'm getting the same issue. 
I would be happy to work on this bug. Just let me know how I should approach the fix.
Thanks.
Brad

**Comment by Horusiath** [comment]
Related: #3320

**Comment by Aaronontheweb** [comment]
Resolved via https://github.com/akkadotnet/akka.net/pull/5123
