### ISSUE TITLE
GuardianSupervisorStrategyConfigurator from Akka is not implemented

### ISSUE THREAD

**Issue by akoshelev** [akkadotnet/akka.net#1524]
At this time, Akka.NET does not support configuring guardian supervisor strategy: option ```akka.actor.guardian-supervisor-strategy``` is ignored and TODO sections left in the code.

https://github.com/akkadotnet/akka.net/blob/cf7cd6f274cd56af6403afc640a038564dc4d03b/src/core/Akka/Actor/ActorRefProvider.cs#L158

**Comment by Aaronontheweb** [comment]
Closed by #1746
