### ISSUE TITLE
Implement more cluster member life-cycle events 

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1526]
Accordingly to Akka JVM docs, it supports following set of member events:

-  **ClusterEvent.MemberJoined** - A new member has joined the cluster and its status has been changed to Joining. *Missing in .NET implementation*
- **ClusterEvent.MemberUp** - A new member has joined the cluster and its status has been changed to Up.
- **ClusterEvent.MemberExited** - A member is leaving the cluster and its status has been changed to Exiting Note that the node might already have been shutdown when this event is published on another node.
- **ClusterEvent.MemberRemoved** - Member completely removed from the cluster.
- **ClusterEvent.UnreachableMember** - A member is considered as unreachable, detected by the failure detector of at least one other node. *Missing in .NET implementation*
- **ClusterEvent.ReachableMember** - A member is considered as reachable again, after having been unreachable. All nodes that previously detected it as unreachable has detected it as reachable again. *Missing in .NET implementation*

We should implement missing event types.

**Comment by Aaronontheweb** [comment]
@Horusiath we appear to be missing `MemberJoined`, but the others are already implemented.

* [`ClusterEvent.ReachableMember`](http://api.getakka.net/docs/stable/html/4276CB55.htm)
* [`ClusterEvent.UnreachableMember`](http://api.getakka.net/docs/stable/html/B5AC71DB.htm)

**Comment by alexvaluyskiy** [comment]
Fixed here https://github.com/akkadotnet/akka.net/pull/2067

**Comment by alexvaluyskiy** [comment]
Fixed here https://github.com/akkadotnet/akka.net/pull/2067
