### ISSUE TITLE
RemoteWatcher throws ResendUnfulfillableException when a remote client tries to send messages to a remote server which restarts within 5 seconds

### ISSUE THREAD

**Issue by Silv3rcircl3** [akkadotnet/akka.net#1527]
I have created a [project](https://github.com/Silv3rcircl3/AkkaReconnectException) to show the behavior, the complete exception is available as [gist](https://gist.github.com/Silv3rcircl3/d63be628b412aaebc5fb).

Basically what I tried to build was a SignalR clone based on Akka.Remote, especially the information about a connection that got lost (via watching a remote actor) and the feature to automatically reconnect to the remote server.

I have to split this in two parts, because since I upgraded to Akka1.0.5 there is a different behavior. 

#### In Akka 1.0.4
In Akka 1.0.4 you could stop the server, wait until the client received the termination message and then start the server again, but if you have started the server before the client received the termination message, the exception in the gist was thrown and the client never received the termination message and therefore couldn't reconnect to the server. 
If you wan't to reproduce this behavior, you have to downgrade Akka to 1.0.4 and preferably Helios to version 1.4.1 and then execute the following steps: 
1. Start server
2. Start client
3. Wait until the client is connected
4. Restart the server within 5 seconds
5. Wait a few seconds for the exception

[This is how it should look like](https://cloud.githubusercontent.com/assets/6583600/11717097/78e4be64-9f4e-11e5-959c-d3cb7c649278.png)

[and that's how it looks if you restart the server within 5 seconds](https://cloud.githubusercontent.com/assets/6583600/11717141/ce10024a-9f4e-11e5-9527-df812ae471cb.png)

#### In Akka 1.0.5
Now things get even worse :smile: 
Two things that have worked in 1.0.4 aren't working anymore and the behavior described above is working now. 

##### 1. It's not possible to start the client before the server.
That worked well with Akka 1.0.4 as you can see [here](https://cloud.githubusercontent.com/assets/6583600/11717466/f3b1f998-9f50-11e5-932e-a147ca1402b6.png), but since I upgraded to the new version, the client tries to connect to the server all day long as you can see [here](https://cloud.githubusercontent.com/assets/6583600/11717385/88619e46-9f50-11e5-96b0-6c7f2efe4417.png).

##### 2. The client doesn't reconnect if you wait until the termination message has arrived before starting the server again
It then looks like [this](https://cloud.githubusercontent.com/assets/6583600/11717660/259ee9d8-9f52-11e5-987e-ac86354a6427.png) and the client tries to reconnect all day long. To reproduce this behavior, execute the same steps as described above but in step 4 don't start the server until the message  ```Connection terminated``` shows up.

Last but not least, the exception is still thrown if you execute the steps described above, but now the client can successfully reconnect to the server as you can see here [first page](https://cloud.githubusercontent.com/assets/6583600/11717944/c3afa4e0-9f53-11e5-90b3-614d645850b2.png) and [second](https://cloud.githubusercontent.com/assets/6583600/11717953/cf1b471c-9f53-11e5-9821-91986927564d.png)   
  
    
    
cc @Aaronontheweb  @Horusiath

**Comment by Aaronontheweb** [comment]
Related to #1360

**Comment by Silv3rcircl3** [comment]
Is now working with latest dev.
