### ISSUE TITLE
Mark AwaitTermination and Shutdown as deprecated and implement WhenTerminated and Terminate as replacement

### ISSUE THREAD

**Issue by Silv3rcircl3** [akkadotnet/akka.net#1532]
In the scala version ```AwaitTermination``` and ```Shutdown``` are marked as deprecated for version 2.4, ```WhenTerminated``` and ```Terminate``` should be used instead. 

I could implement this as far as I know which version I should use for the deprecated message.

**Comment by SteveTheDataPirate** [comment]
Why did ya'll deprecate AwaitTermination and how do I use WhenTerminated properly?

**Comment by Silv3rcircl3** [comment]
@SteveTheDataPirate 
```csharp
sys.Shutdown();
sys.AwaitTermination();
```

can now be combined in one call

```csharp
sys.Terminate().Wait();
```

If you're using `Shutdown` in one place and `AwaitTermination` somewhere else in your code you can use the following approach

```csharp
sys.Terminate();

//somewhere else in your code
sys.WhenTerminated.Wait();
```

**Comment by SteveTheDataPirate** [comment]
Thank you for the response.
