### ISSUE TITLE
Akka.Remote performance - ActorPath.TryParse + Address.TryParse

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1537]
After investigating the performance in Akka.Remote, We have found a few big hogs.

One of them is `ActorPath.TryParse` this is called multiple times for each remote message sent.
First to resolve what actor to talk to, and then to resolve who is the sender. and then possibly for other `ActorRefs` contained in the message sent.

We use `Uri.TryCreate` which is far too expensive for this.

So we have three options here.

**Cache all ActorPaths:**
I do this in my experimental branch, this gives huge performance gains.
BUT, there is a risk of the static cache growing with thousands or millions of ActorPaths eventually if the system lives for a long time..
We could solve this with some sort of Time to live cache.

**Create a faster parser:**
JVM Akka does not use URI at all for parsing, this was introduced by me very early on, just for being lazy.
We can probably do a better custom parser as ActorPaths wil not contain all the special stuff found in real URI's.

**A combination of the two above:**
We can possibly cache on address only, e.g. if we can substring the address part of a path really fast and use that as a key, then we could cache the address alone. and then take the reminder of the string and create the actor path from that.

Whatever option we go for needs to be extensively performance tested.

**Comment by Horusiath** [comment]
When it comes to caching actor paths - I think the best option here would be introducing circular buffer. TTL itself won't guarantee cache size limit.

**Comment by rogeralsing** [comment]
A circular buffer sounds good, but how can we shape that so we can do hash lookups in it?
if we need to scan the entire buffer we will probably lose perf

**Comment by rogeralsing** [comment]
Please review this attempt at solving this:

https://gist.github.com/rogeralsing/be22e2572adebf8026e1

I have performance tested this and there is virtually 0 overhead of using this approach. absolutely no observable impact at all on lookup performance.

**Comment by JeffCyr** [comment]
- Should use Task.Run instead of Task.Factory.StartNew.
- ToArray will create possibly large buffer and lock the whole dictionary while copying which could create latency. GetEnumerator could be used instead.

> The enumerator returned from the dictionary is safe to use concurrently with
        reads and writes to the dictionary, however it does not represent a moment-in-time snapshot
        of the dictionary.  The contents exposed through the enumerator may contain modifications
        made to the dictionary after <see cref="GetEnumerator"/> was called.

**Comment by rogeralsing** [comment]
I double checked and the Scala code does use their counterpart of Uri in the `ActorPathExtractor`.

It can probably be done with better performance by manual parsing, an ActorPath only consists of an address and then the Uri Segments. so we don't need full suppport to parse the URI.

**Comment by rogeralsing** [comment]
This one is tricky, it turns out that the Uri class is actually pretty fast compared to custom string parsing.
I'm running a test that parses 10 mil Uri's
Just splitting a string on `/` is just about 3.5 times faster than parsing the full URI.
Adding more logic to that brings it down to the same or worse perf.

If anyone feel confident that they can write a Uri parser that still brings significant performance gains over Uri TryCreate feel free to give it a go.

**Comment by Aaronontheweb** [comment]
Try switching from `Uri.TryCreate` to `Uri.Create` and try...catch - might have worse worst case performance but probably better average case performance

**Comment by rogeralsing** [comment]
Done, that gives the same result.

**Comment by danielrodriguez** [comment]
I've found possible ways to reduce the allocations without getting rid of `Uri.TryCreate` (mainly because the ways create custom scheme handlers or regexp yielded worst results).
1. `TryParseAddress` will call `Uri.UserInfo` twice for remote addresses and that property does a substring every time it is called so we can read it only once.
2. `TryParse` uses split and even msdn warns about its usage on critical code (https://msdn.microsoft.com/en-us/library/dd265003.aspx) so most likely we can come up with code that can make better use of allocations. In the same vein, `TryParse `tries to handle the uid/fragment part of the uri manually when we can probably handle it along with the splitting because the / operation in `ActorPath` handles that situation already.

These changes result in modest gains in speed and allocations, are they worth pursuing to close this issue or will  `Uri.TryCreate` will still be the ultimate goal?

**Comment by Aaronontheweb** [comment]
We significantly improved this in 1.4.21 and 1.4.28
