### ISSUE TITLE
Akka.Remote performance - ForkJoinDispatcher

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1538]
We have found the cause of the big perf loss on Akka.Remote. this turned out not to have anything to do with Helios at all, but rather the recent introduction of the ForkJoinDispatcher.

The ForkJoinDispatcher uses the Helios DedicatedThreadPool, which internally uses a BlockingQueue for buffering things to execute.
The blocking queue is just too expensive, it uses locking primitives that cause too much latency.

We need a better way to handle this.
One thing we could try is to port the real fork join thread pool from JVM Akka.
I have no idea how much work that would be but it is one way forward and it would be interesting to see the result.

The reason this was introduced was that we saw a lot of noisy neighbor problems with heartbeats in Akka.Cluster.

However, heartbeats now run on the `DedicatedThreadScheduler` which is not the same as the above.
So heartbeats are not dependant on the DedicatedThreadPool.

**Comment by JeffCyr** [comment]
I created benchmarks some time ago to compare BlockingCollection vs ConcurrentQueue (combined with a single SemaphoreSlim).

ConcurrentQueue was ~2x faster than BlockingCollection, would that be enough?

On a side note, when reviewing the DedicatedThreadPool, I noticed that each worker have its own queue and there is no work stealing, the work items are distributed round-robin to each workers.

So if the workload is not 100% homogeneous, some workers might end up with a lot of items in their queue while others are idle. Could this be the real bottleneck?

**Comment by maxim-s** [comment]
I can try to port fork join thread pool jvm and we can compare it

**Comment by rogeralsing** [comment]
@JeffCyr I think the real issue is not so much the throughput but rather the latency overhead of setting autoreset event or whatever blocking queue uses internally.
That is, once something arrives in the queue, there will be some delay before the worker notices that and starts processing it..

The throughput of a blocking queue should still be in the order of hundreds of thousands if not millions. so that is probably not the problem.

There was significant remoting latency overhead introduced togerther with the fork join dispatcher.

But this is just guessing from my side.

@maxim-s go for it :-)

**Comment by JeffCyr** [comment]
Still a work in progress, but I cloned the Clr ThreadPool from the coreclr repo to create an instantiable version of the ThreadPool.

Results look promising, roughly the same throughput/latency as the global ThreadPool.

**Comment by JeffCyr** [comment]
Here's the results:

##### Throughput test (Queue 10 000 000 items and wait completion)
Global ThreadPool: 00:00:01.1490560
LocalThreadPool  : 00:00:01.1072956
HeliosThreadPool : 00:00:04.0878420

##### Latency test (Sequencially queue 1 000 000 items)
Global ThreadPool: 00:00:01.4135339
LocalThreadPool  : 00:00:00.9904661
HeliosThreadPool : 00:00:23.3648739

**Comment by rogeralsing** [comment]
That looks amazing!!
Are there any non standard or native constructs in the code? 

Skickat från min iPhone

**Comment by JeffCyr** [comment]
@rogeralsing Its all managed code with standard construct and without "unsafe" keyword. There's a little nuance with QueueUserWorkItem because we can't capture the ExecutionContext without the SynchronizationContext like the real ThreadPool does, but I think I can work around that. Otherwise UnsafeQueueWorkItem is the same.

The LocalThreadPool is working with mostly the same code as the original .Net ThreadPool. Right now I only implemented a naive fixed thread count but I'm planning to implement starvation-detection and hill-climbing heuristic inspired by the unmanaged code in coreclr.

**Comment by JeffCyr** [comment]
I'll create a PR with an implementation of ForkJoinDispatcher using the LocalThreadPool when I'll have some free time this week.

When I'm finished implementing the starvation-detection and hill-climbing, I think it could potentially increase the overall performance of the Actor's Mailbox dispatching by enabling work stealing which the ThreadPoolDispatcher does not when using ThreadPool.UnsafeQueueWorkItem.

**Comment by Aaronontheweb** [comment]
This can be closed per #1569
