### ISSUE TITLE
Akka.Remote performance - WriteLoop Tail Recursion

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1541]
This is a minor issue in the Akka.Remote performance story.
The `WriteLoop` in Endpoint.cs is ported from Scala, which uses a tail recursive function.
C# does not have tail recursion and will have to pay the price for full function invocations, allocating stack frames and all that.

This can be transformed into an iterative loop instead.
Fixing this yields a little bit of performance gains, 1-2%ish

**Comment by sean-gilliam** [comment]
Closing the issue since the PR discussion in #1542 provided stats that proved within the margin of error.
