### ISSUE TITLE
ActorSelection fails for ActorPath from remotely deployed actors

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1544]
Right now `ActorSelection` doesn't work when combined with path taken from remotely deployed actor:

``` csharp
// remoteRef is remotely deployed actor
system.ActorSelection(remoteRef.Path).Ask<ActorIdentity>(new Identify(null)).Result;
```

This operation will timeout - actor won't be find under provided path. Also any messages that will be send under actor selection specified that way will be send to dead letters on the remote node.

I don't know what is expected behavior on the JVM side for that.

**Comment by rogeralsing** [comment]
That would be me:

https://github.com/rogeralsing/akka.net/blob/master/src/core/Akka.Remote/RemoteDaemon.cs#L165

**Comment by Horusiath** [comment]
Scaka version for comparison:

```scala
override def getChild(names: Iterator[String]): InternalActorRef = {

    @tailrec
    def rec(s: String, n: Int): (InternalActorRef, Int) = {
      import akka.actor.ActorCell._
      val (childName, uid) = splitNameAndUid(s)
      getChild(childName) match {
        case null ⇒
          val last = s.lastIndexOf('/')
          if (last == -1) (Nobody, n)
          else rec(s.substring(0, last), n + 1)
        case ref if uid != undefinedUid && uid != ref.path.uid ⇒ (Nobody, n)
        case ref ⇒ (ref, n)
      }
    }

    val full = Vector() ++ names
    rec(full.mkString("/"), 0) match {
      case (Nobody, _) ⇒ Nobody
      case (ref, 0)    ⇒ ref
      case (ref, n)    ⇒ ref.getChild(full.takeRight(n).iterator)
    }
  }
```

**Comment by alexpantyukhin** [comment]
I will take it.

**Comment by Horusiath** [comment]
@alexpantyukhin would you also submit a test case to ensure that this won't reappear in the future?

**Comment by alexpantyukhin** [comment]
okay. I will

**Comment by rogeralsing** [comment]
Also, before starting this.
Try the `system.ActorSelection(remoteRef.Path).Ask<ActorIdentity>(new Identify(null)).Result;` and put a breakpoint in RemoteSystemDaemon.GetChild and see if you even get there.

If not, then the issue resides elsewhere.

**Comment by maxim-s** [comment]
Also would be great to port missing specs from https://github.com/akka/akka/blob/master/akka-remote/src/test/scala/akka/remote/RemotingSpec.scala

**Comment by maxim-s** [comment]
Looks like problem with transport protocol matching here
https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Remote/Remoting.cs#L295

but scala version has the same issue for remote ActorSelection e.g.
http://stackoverflow.com/questions/23827275/akka-remote-remotetransportexception-no-transport-is-loaded-for-protocol

local and client systems has different protocols e.g. akka and akka.tcp 
and exception will be like 
```
Akka.Remote.RemoteTransportExceptionNo transport is loaded for protocol: [akka], available protocols: [akka.test,akka.tcp]
```
Also for 
https://github.com/rogeralsing/akka.net/blob/master/src/core/Akka.Remote/RemoteDaemon.cs#L165

I've prepared gist
https://gist.github.com/maxim-s/bd11eae2388b0ea2e7ed

**Comment by Silv3rcircl3** [comment]
@Horusiath @rogeralsing @maxim-s 
Any ideas where to look next ?
The issue with the test transport protocol was fixed as well as the `GetChild` implementation but the bug still exists.

**Comment by maxim-s** [comment]
@Silv3rcircl3 do you have any log files?  I can check but need more details

**Comment by Silv3rcircl3** [comment]
@maxim-s even better, I have a bunch of failing specs for you ;) 
The new remoting spec is failing as well as 10 specs for the local actor selection! Even the `Equals` implementation seems to be broken. 
https://github.com/Silv3rcircl3/akka.net/tree/ActorSelectionSpec

**Comment by Horusiath** [comment]
@Silv3rcircl3 can we consider this solved?

**Comment by Silv3rcircl3** [comment]
@Horusiath nop, it's still not working for deployed actors. See my https://github.com/akkadotnet/akka.net/pull/2196#discussion_r71137646

**Comment by Danthar** [comment]
Looks like this is fixed @Silv3rcircl3  can you confirm ?

**Comment by Silv3rcircl3** [comment]
@danthar nop spec is still failing

**Comment by object** [comment]
Fantastic, thanks guys!

**Comment by Aaronontheweb** [comment]
@object happy to do it - should be rolled into the latest nightlies tonight

**Comment by object** [comment]
Perfect timing for us!
