### ISSUE TITLE
Investigate whether or not dispatchers, DedicatedThreadPools, and other resources are properly disposed on ActorSystem.Shutdown

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1549]
I strongly suspect that the `DedicatedThreadPool` and `ForkJoinDispatcher` instances used by any `ActorSystem` that creates them are not properly shutdown and disposed afterwards, resulting in gradual memory leaks and zombie threads. I would like to investigate this issue and determine if this and any other resources are being leaked after an `ActorSystem` has shut down.

Where this issue will most noticeably show up is inside someone's Akka.NET test suite, where we start and stop lots of `ActorSystem` instances within one process.

**Comment by JeffCyr** [comment]
PR #1569 should fix the issue about DedicatedThreadPool and ForkJoinDispatcher disposal.

**Comment by rogeralsing** [comment]
Hmmm this one could be tricky to deal with.
In theory, single actors could request their own dispatcher using configuration. so the dispatcher lifespan can be everything from that of a single actor, of a group of actors or for the entire actor system.

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb could we close it?
