### ISSUE TITLE
Akka.Remote with F# API: ICanTell.Ask() call can hang indefinitely

### ISSUE THREAD

**Issue by jtmueller** [akkadotnet/akka.net#1551]
Setup
1. Set up two actor systems in F# that communicate with Akka.Remote.
2. Make sure one system calls a remote actor with code similar to...

```fsharp
    open Akka.FSharp
    ...
    async {
        let! result = remoteActor.Ask<SomeType>(arg, timeout)
    }
```

Repro
1. Verify that these calls are working, then shut down the host for the remote actor, and make the same call again.
2. The  `let! result =` call will hang indefinitely, and never return. An exception related to the absence of the remote actor host will get logged, but the exception will not be propagated to the calling code, which, as stated, hangs indefinitely.

If you call the C# Task-returning overload of Ask under these circumstances, and use .ContinueWith() to inspect the resulting Task, you'll discover that the task passed to the ContinueWith function has its IsFaulted property set to false, and its Exception property set to null. However, the act of accessing the Result property will throw an exception.

Knowing this, I can work around this issue by forcing the exception to be thrown before passing the task to Async.AwaitTask, like this:

https://gist.github.com/jtmueller/7502efa7e4c0c08dcaac

The contract for System.Threading.Task is that the ContinueWith function won't be invoked until the task has finished resolving itself to either a concrete result, or an exception. In this case, the task being passed into ContinueWith appears to violate this contract: IsFaulted is false, and the Exception property is null, but accessing the Result property throws an exception. The following is speculation, but it appears that the F# Async.AwaitTask is not returning because it's being handed a Task object that is not in a valid state.

The work-around linked above works by forcing the exception to be thrown (producing a new task that is in a valid state) before invoking Async.AwaitTask. It's not as efficient as starting with a task that resolves the exception before invoking ContinueWith (because an extra Task object must be allocated and garbage-collected for every call) but it's probably an acceptable work-around for the time-being.

**Comment by jtmueller** [comment]
It is likely that a similar fix would need to be applied to the <? operator, but I haven't tested this.

**Comment by jtmueller** [comment]
Looking at the F# source code, Async.AwaitTask will eventually end up calling [TaskHelpers.contineWith on line 1472](https://github.com/fsharp/fsharp/blob/a62def585754e61e128f9e09a6f0e18e7e07084c/src/fsharp/FSharp.Core/control.fs). As you can see, if the task's IsFaulted property is false,  but the Result property throws an exception, that exception will happen on line 1479, with no try/catch block, so none of the three continuation functions will be called, and the F# async block will never advance to the next instruction.

**Comment by Horusiath** [comment]
This seems to be something more as a F# API issue, as a `Task<_>` returned from `Ask` may end up in indeterminable state. What we want is either:

1. `task.IsFaulted` equal false and `task.Result` not throwing an exception in case when response was returned correctly.
2. `task.IsFaulted` equal true and not null `task.Exception` in case when error occurred during reply.
3. `task.IsCanceled` equal true in case, when Ask has timed out.

What we have in this case right now is `task.IsFaulted` equal false and `task.Result` throwing an exception, which is basically undefined behavior.

When shutting down node with remote actor, we were asking, what we want is either having it faulted due to disassociation (more desired?) or cancelled, as the endpoint have not responded.

**Comment by Aaronontheweb** [comment]
@Horusiath the behavior of Ask should definitely not be influenced by whether remoting was involved or not. Behavior should be identical to that of Asking a local actor that does not exist or is too busy to respond.

**Comment by jtmueller** [comment]
@Horusiath, @Aaronontheweb - I apologize if this isn't the appropriate place to bring this up, but I've been quite pleased with [the code I came up with while working around this issue](https://gist.github.com/jtmueller/15e5c8dafbf5bada808b) and I wanted to suggest this or something like it as a possible enhancement to the F# API -- or maybe you could tell me what's not going to work about this approach.

This version of the `Ask` method and `<?` operator don't suffer from the bug under discussion, because the `tryCast` function accesses the Result property before anything gets passed to `Async.AwaitTask`.

I've been bitten by F# code like this before, inside a message handler called by Ask:

```fsharp
async {
    let! data = getSomeData()
    let response = manipulateData data
    return response
} |!> mailbox.Sender()
```

If any of the code inside the async block throws an exception, the sender will receive a `Status.Failure` instance instead of any of the types it was expecting to receive. I would have thought that this would cause an exception to be thrown in the code that calls `Ask` or uses the `<?` operator, but that has not been my experience, and I had a fun time debugging an issue in production where exceptions were being silently lost because code that was receiving a Status.Failure wasn't expecting that type and didn't have a case to handle it.

I suspect that might be an issue with the `|!>` operator, but I haven't looked into it. In any case, the code linked above solves the issue at least in the case of Ask by handling `Status.Failure` and treating it like an exception. Which leads me to...

I've found it more productive to work with a discriminated union returned by `Ask` or `<?` instead of requiring a try/with to be wrapped around every call.

If I don't care to handle any errors, and would rather propagate the exception, I can just access the Value property:

```fsharp
type AccessTokenController() =
    inherit ApiController()

    member x.Get(licenseId: Guid, key: string) =
        async {
            let! remoteActor = getRemoteActor()
            let! (result: AskResult<string>) = remoteActor <? GetAccessToken({ LicenseId=licenseId; Key=key })
            return result.Value
        } |> Async.StartAsTask
```

If I want to handle any errors, I can easily do so:

```fsharp
let private remoteServicePort = int ConfigurationManager.AppSettings.["ServicePort"]
let mutable private remoteActorRoot: IActorRef option = None

let rec getRemoteActor() = async {
    match remoteActorRoot with
    | Some actorRef -> return actorRef
    | None ->
        let selection = select (sprintf "akka.tcp://monitor@localhost:%i/user/monitor-api" remoteServicePort) Global.ActorSystem
        let! result = selection <? Identify("get-remote-monitor")
        match result with
        | Ok(ident: ActorIdentity) ->
            let actorRef = ident.Subject
            if isNull actorRef then
                do! Async.Sleep 100
                return! getRemoteActor()
            else
                Interlocked.Exchange(&remoteActorRoot, Some(actorRef)) |> ignore
                return actorRef
        | Err ex ->
            raise <| exn("Error retrieving remote actor reference.", ex)
            return upcast ActorRefs.Nobody
}
```

And finally, because the `tryCast` function checks for `AskResult` and just passes it along, I can very conveniently forward responses that I got from child actors when using the error kernel pattern. It's concise, and it lets me put error-handling code only in the ultimate recipient, without having to handle exceptions in the forwarding actors.

```fsharp
let getChildActor actorName handler =
    let actor = mailbox.Context.Child(actorName)
    if actor.IsNobody() then
        spawn mailbox.Context actorName (actorOf2 handler)
    else
        actor

let getAccessActor() = getChildActor "access-token" AccessTokenActor.requestHandler

fun msg ->
    logDebugf mailbox "Monitor API request: %A" msg
    match msg with
    | GetAccessToken(clientId) ->
        let sender = mailbox.Sender()
        if Set.contains clientId.Key bannedKeys then
            sender <! Err(DisabledKeyException(sprintf "Key '%s' has been disabled." clientId.Key))
        else
            getAccessActor().Ask<string>(AccessTokenRequest)
            |!> mailbox.Sender()
   // ...
```

**Comment by Horusiath** [comment]
@jtmueller Indeed that sounds nice! :) The only problem I see there, is that Akka.FSharp already hit v1.0, which makes API pretty frozen. That's why I've started fork of it in form of the [Akkling](https://github.com/Horusiath/Akkling) library. If this cannot be used in Akka.FSharp because of breaking API compatibility, maybe would you like to contribute it to the fork? ;)

cc @akkadotnet/developers What do you think about using this approach in Akka.FSharp?

**Comment by Horusiath** [comment]
Closing that for now. As told, the whole API for Akka.FSharp is frozen for now. I've implemented this feature in my experimental fork (see Akkling), which may be merged back into Akka.FSharp in the future.
