### ISSUE TITLE
Add Ask and ActorSelection throughput specs

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1555]
Need to add some specs for Ask that stress test it under the following conditions:

1. From outside an `IActorContext`, i.e. the way you'd ask an actor from within an ASP.NET MVC controller or something like this
2. From inside an `IActorContext` that **is not** using async / await
3. From inside an `IActorContext` that **is** using async / await
4. From inside another TPL task

**Comment by rogeralsing** [comment]
I think it would be good to have some that run multiple Asks in parallel, Ask creates temp actors in the `VirtualPathContainer` how this behaves if there are high workloads are unexplored AFAIK.
That is, they are added and once done they are removed, I would guess that can cause some contention and potential lag, as expected, but we don't know where that limit is atm.

**Comment by Aaronontheweb** [comment]
@rogeralsing have some ideas on how we can benchmark the virtual path container independently? I'm thinking it might be interesting to test some things like how insertion speed changes as the number of concurrent Ask operations increases, which we can simulate by manually adding stuff to the container

**Comment by rogeralsing** [comment]
Ah yes, we could easily just add and random named `ActorRef.NoSender` to an instance of VirtualPathContainer.
Arrange: Pre generate x random names using a Random with the same seed each run. 
Assert: Then use those names in the perf test to add and remove.

That would probably give the most consistent results back.
The VirtualPathContainer is a super slim wrapper ontop of ConcurrentDictionary so we are pretty much testing just that, but still it would be good to know if there are any pauses in the add or remove phase under load.

**Comment by Aaronontheweb** [comment]
Bucketing 'ActorSelection` under this issue too

**Comment by Silv3rcircl3** [comment]
Closed via #1999
