### ISSUE TITLE
Solution does no longer build from Dev

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1563]
In `TestTransportRemoteMessagingThroughputSpec`

There is a line:

```csharp
var remoteAddress = $"test://{actorSystemName}@{ipOrHostname}:{port}";
```

Which uses C#6 string interpolation, while the project itself is set to "Default" on language level.

**Comment by Aaronontheweb** [comment]
Doesn't build on `dev` on which environments? VS2013?

**Comment by rogeralsing** [comment]
I use VS2015 but the project is marked as .NET 4.5 and the language level is set to default, so I guess that means C#5 for a 4.5 project(?)

It didn't build and resharper asked if I wanted to turn on C#6 features for the project

**Comment by rogeralsing** [comment]
It builds correctly in 2015, my Akka.NET solution opens in 2013 and 2013 requires you to enable C#6 features. 

We also agreed to use C#6 on last contrib meeting, so I'm closing this
