### ISSUE TITLE
[Akka.Cluster.Tools] ClusterSingletonManagerSpec MNTK spec

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1572]
This is up for grabs task for making [ClusterSingletonManagerSpec](https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonManagerSpec.cs) work on MultiNode TestKit Runner.

**Comment by alexvaluyskiy** [comment]
Fixed here https://github.com/akkadotnet/akka.net/pull/2102
