### ISSUE TITLE
[Akka.Cluster.Tools] ClusterSingletonManagerLeaveSpec MNTK spec

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1574]
This is up for grabs task for making [ClusterSingletonManagerLeaveSpec](https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonManagerLeaveSpec.cs) work on MultiNode TestKit Runner.

**Comment by alexvaluyskiy** [comment]
Was fixed here https://github.com/akkadotnet/akka.net/pull/2058
