### ISSUE TITLE
[Akka.Cluster.Tools] ClusterClientSpec MNTK spec

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1577]
This is up for grabs task for making [ClusterClientSpec](https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/cluster/Akka.Cluster.Tools.Tests/ClusterClient/ClusterClientSpec.cs) work on MultiNode TestKit Runner.

**Comment by alexvaluyskiy** [comment]
Fixed in #2032
