### ISSUE TITLE
Examine the state of Mono Concurrent queue

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1594]
We currently have `Debug Mono` and `Release Mono` build configurations. 
The only thing they do is to switch out the `ConcurrentQueue` implementation in the actor mailbox.

In earlier versions of Mono, the `ConcurrentQueue` were the subject of race conditions.
If that have since been fixed, e.g. in Mono 4.* we can safely remove the Mono conditional compilation directives and the two custom build configurations.

**Comment by JeffCyr** [comment]
According to this:
http://www.mono-project.com/docs/about-mono/releases/4.0.0/

The following namespaces have been entirely, or almost entirely replaced with ReferenceSource code:

System.Collections
**System.Collections.Concurrent**
System.Collections.Generic
System.Collections.Specialized
System.ComponentModel
System.ComponentModel.Design
System.Diagnostic.Contracts
System.Linq
System.Linq.Parallel
System.Text.RegularExpressions
System.Runtime.CompilerServices
System.Threading.Tasks

Still need to validate if ConcurrentQueue is part of the *entirely replaced* code, but I don't see why it wouldn't.

**Comment by mattnischan** [comment]
The last pre-ReferenceSource version of ConcurrentQueue did not suffer from the previous version's race conditions either.

Looking at the current Mono 4.0 source, it is matching the .Net Reference Source code.
