### ISSUE TITLE
Ask problem with Akka.Remote and discriminated unions.

### ISSUE THREAD

**Issue by fjoppe** [akkadotnet/akka.net#1595]
I am working with Akka.Net (1.0.5), Akka.Fsharp (1.0.4), Akka.Remote (1.0.5).

I have a stateful actor system which I will run as a service (currently a console app with TopShelf). From a webserver's backend-service, I want to contact the actor system using Akka.Remote. Currently, I am prototyping this connection using the F# interactive, just to make sure that the communication goes well. It does not go well.

When running the service (console app), I can make contact from the fsi using Akka.Remote. I can 'tell" a message to a remote actor, using a discriminated union as the message type. I proved this part with breakpoints, logging and debugging. The message is received and processed correctly.

However, if I "ask" the remote actor something from within the fsi, and the remote sends a discriminated union back to the fsi, I cannot convert this response to the DU-type it should be. So the fsi never gets the correct type.

I tried to convert the response to *obj*, with the idea to convert to the correct type later. That proves the issue.I can try to unbox the data:
```fsharp
unbox<MyDUResponse> myData
```

Then I get the following exception:
>System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'MyNamespace.MyDUResponse'.
>   at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
>&gt;    at <StartupCode$FSI_0004>.$FSI_0004.main@() in F:\SomePath\FSharp\CallRemoteActor.fsx:line 53
Stopped due to error

If I look at myData.ToString(), I see something which appears as JSON, and it has the correct data in it:
>val it : string =
>  "{
>  "Case": "YourId",
>  "Fields": [
>    "66379e12-0aef-4c8e-9135-57765c047985"
>  ]
>}"

Note again, this problem occurs with *ask* and I have not seen it with *tell*. For those cases I used *tell* the DU-case did not have data in it, while the *ask* case does have a string in it.

**Comment by Horusiath** [comment]
@fjoppe This is a well known issue of default (JSON.NET based) serializer in Akka.NET. Unfortunately, as long as we use JSON.NET, problem is out of our reach. Currently the best option is to change default serializer to Akka.Serialization.Wire. Optionally you may use [Akkling](https://github.com/Horusiath/Akkling) (some auto promotion here), which already uses Wire as default serializer.

**Comment by fjoppe** [comment]
@Horusiath Thanks for reply. I did some research and I did find the known issue. So I was a little hesitating. Is the issue with data in a DU? I thought it could be different than the known issue, because ask and tell behave different, and I read it would be solved in Newtonsoft 7.x. Anyway, I will try your suggestions, thanks.

**Comment by rogeralsing** [comment]
I highly doubt that the issue is related to `Ask` vs `Tell`, there is nothing in the remoting layer that knows about any difference of Ask and Tell, Ask doesn't really exist its just two Tell's with an awaiting task on the asking side.

We have seen a lot of quirky behavior from Json.NET, we have type names enabled in the json payload, still, some combinations of objects are missing type decorations for unknown reason.
DU's, does not get decorated with typenames but rather with the name of the DU.
Json.NET can resolve that if it know the type of the container. e.g if there is a property of type `MyDU` and the name in the json payload is `DU1` then Json.NET will resolve that to `MyDU.DU1`.

But, if the type of the property is `object` or the container is an `object[]` and the payload contains `MyDU`, there is no way for Json.NET to figure out what the actual DU type is. the `MyDU` part is missing from the equation here.

We have tried to bend Json.NET to our will but after beating this dead horse for two years now, I gave up and wrote Wire instead.

**Comment by rogeralsing** [comment]
Related to #1534

**Comment by rogeralsing** [comment]
Related to #1409

Apparently TimeSpan and GUID is serialized as a string w/o type decorations too.

**Comment by fjoppe** [comment]
@Horusiath @rogeralsing 
Thanks. I could not find Akka.Serialization.Wire, or how to use "Wire" for C# as Fsharp serializer, so I’m going to try Akkling for now. I did see the dependency on Wire. Both initiatives look like great work. Thanks!

**Comment by QuantumWorld-1729** [comment]
> I am working with Akka.Net (1.0.5), Akka.Fsharp (1.0.4), Akka.Remote (1.0.5).
> 
> I have a stateful actor system which I will run as a service (currently a console app with TopShelf). From a webserver's backend-service, I want to contact the actor system using Akka.Remote. Currently, I am prototyping this connection using the F# interactive, just to make sure that the communication goes well. It does not go well.
> 
> When running the service (console app), I can make contact from the fsi using Akka.Remote. I can 'tell" a message to a remote actor, using a discriminated union as the message type. I proved this part with breakpoints, logging and debugging. The message is received and processed correctly.
> 
> However, if I "ask" the remote actor something from within the fsi, and the remote sends a discriminated union back to the fsi, I cannot convert this response to the DU-type it should be. So the fsi never gets the correct type.
> 
> I tried to convert the response to _obj_, with the idea to convert to the correct type later. That proves the issue.I can try to unbox the data:
> 
> ```fsharp
> unbox<MyDUResponse> myData
> ```
> 
> Then I get the following exception:
> 
> > System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'MyNamespace.MyDUResponse'.
> > at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
> > >    at <StartupCode$FSI_0004>.$FSI_0004.main@() in F:\SomePath\FSharp\CallRemoteActor.fsx:line 53
> > Stopped due to error
> 
> If I look at myData.ToString(), I see something which appears as JSON, and it has the correct data in it:
> 
> > val it : string =
> > "{
> > "Case": "YourId",
> > "Fields": [
> > "66379e12-0aef-4c8e-9135-57765c047985"
> > ]
> > }"
> 
> Note again, this problem occurs with _ask_ and I have not seen it with _tell_. For those cases I used _tell_ the DU-case did not have data in it, while the _ask_ case does have a string in it.

How did you do the implemented tell to a actor using discriminated union can you pls help me with it
