### ISSUE TITLE
Build System: add API diffing tool to validate no breaking changes in binary compatibility to build process

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1607]
Addresses an issue that affected us with the 1.0.5 release - accidentally included an overload to an extension method which broke binary compatibility with some of our Akka.Persistence plugins that didn't get updated as part of that release.

I received one suggestion on Twitter on how to go about doing this:

https://twitter.com/danielmarbach/status/682147123429814272

We'll need to modify the FAKE script to do something like this:

http://cloud.smartdraw.com/share.aspx/?pubDocShare=C1F9F8A1A9BF090FA57441521065EE6C6D9

This issue is up for grabs.

**Comment by danielmarbach** [comment]
If noone objects I'll give it a stab. I'll release it if I don't find time until mid-next week

**Comment by Aaronontheweb** [comment]
Resolved per #1608, #1639, and https://github.com/akkadotnet/getakka.net/pull/131

Thanks for your help, @danielmarbach !

**Comment by danielmarbach** [comment]
What API is next?
