### ISSUE TITLE
Akka seems to keep a reference to the last handled message

### ISSUE THREAD

**Issue by boekabart** [akkadotnet/akka.net#1609]
When I send a very large message (object containing an XDocument for a 800-mb xml file) to a ReceiveActor and handle it, then garbage collect, it seems that the 1.7 gb for the document is not being cleaned up. If I follow up the large message with a small message, the large object DOES get cleaned up. Does Akka keep a reference to the last handled message?

**Comment by rogeralsing** [comment]
From the Scala code

```scala
final def invoke(messageHandle: Envelope): Unit = try {
    currentMessage = messageHandle
    cancelReceiveTimeout() // FIXME: leave this here???
    messageHandle.message match {
      case msg: AutoReceivedMessage ⇒ autoReceiveMessage(messageHandle)
      case msg                      ⇒ receiveMessage(msg)
    }
    ///########## current message is cleared here
    currentMessage = null // reset current message after successful invocation
  } catch handleNonFatalOrInterruptedException { e ⇒
    handleInvokeFailure(Nil, e)
  } finally {
    checkReceiveTimeout // Reschedule receive timeout
  }
```

I'm updating the C# code to do the same, I need to verify that it doesn't break async features first.
