### ISSUE TITLE
Akka.Streams - designing an API

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1611]
I think we could discuss a little, how do we see an akka-streams API in .NET land. Currently I'm porting it 1-1 from Scala version - that means, all fluent methods are called just like their Scala equivalents (eg. `Map`, `Filter`). However I think, it's not feasible for us, as most of the C# community already get used to LINQ-inspired naming convention (like `Select`, `Where`).  Rx teams already solved that by using conventions familiar to users of languages - I think, we should follow the same way as long as possible.

Now my question is. How deep we should manage those changes?:

1. Should we create two distinct namespaces - `Akka.Streams.Dsl` that keeps Scala convention and `Akka.Streams.Linq` that keeps LINQ convention? **Note**: for keeping streams syntax in line with `IQueryable` we will probably need a separate namespace anyway.
2. Should we change convention only for the top level API, keeping internal names Scala-like?
3. Should we change convention top to bottom, for all names used inside Akka.Streams project?

Current convention mappings proposal ([Scala docs](http://doc.akka.io/api/akka-stream-and-http-experimental/1.0/index.html#akka.stream.scaladsl.FlowOps) for reference):

- `recover` 
- `map` &rArr; `Select`
- `mapConcat` &rArr; `SelectMany`
- `mapAsync` &rArr; `SelectAsync`
- `mapAsyncUnordered` &rArr; `SelectAsyncUnordered`
- `filter` &rArr; `Where`
- `filterNot` &rArr; `WhereNot` (do we need that?)
- `takeWhile`
- `dropWhile` &rArr; `SkipWhile`
- `collect` &rArr; ?? (it's like a combination of Where + Select)
- `grouped` 
- `sliding`
- `scan` &rArr; (it's like Aggregate, but it's continuous, doesn't require stream to complete)
- `fold` &rArr; `Aggregate`
- `intersperse`
- `groupedWithin`
- `delay`
- `drop` &rArr; `Skip`
- `dropWithin` &rArr; `SkipWithin`
- `take`
- `takeWithin`
- `conflate`
- `expand`
- `buffer`
- `transform`
- `prefixAndTail`
- `groupBy`
- `splitWhen`
- `splitAfter`
- `flatMapConcat` (I'd call it very specific version of SelectMany)
- `flatMapMerge` (similar to `flatMapConcat` but more customizable)
- `initialTimeout`
- `completionTimeout`
- `idleTimeout`
- `keepAlive`
- `throttle`
- `initialDelay`
- `log`
- `zip`
- `zipWith`
- `interleave`
- `merge`
- `mergeOrdered`
- `concat` &rArr; ~~`Union`~~

As you can see, there are missing LINQ primitives - if we change something, we should keep more to Reactive Extensions IMO, as it's conceptually closer to what Akka.Streams will offer.

**Comment by rogeralsing** [comment]
Is `concat` really the same as `Union`? if so that is a really odd name on the Scala side.
Concat reads as Append to me.
While Union is a Set operation.

Other than that, I'm all for your translations, that would be inline with Linq and Rx.

**Comment by Horusiath** [comment]
@rogeralsing Concat is pure, it doesn't alter any collection, always produces a new one. In Append it's not always the case. Agreed that Union isn't in fact correct name, for what we expect.

**Comment by rogeralsing** [comment]
Have you double checked with all .NET RX methods?
My guess is that there are some overlap there, and I think we should go with whatever standards are used there.

**Comment by Silv3rcircl3** [comment]
Closed via #1935
