### ISSUE TITLE
Akka.TestKit.Xunit2 Dependency issue in a Dnx.Console project

### ISSUE THREAD

**Issue by mmisztal1980** [akkadotnet/akka.net#1616]
Hi Guys,

I have a DNX RC1 console project, which is supposed to be my Xunit project, using the ```xunit.runner.dnx``` package.

I've noticed that I'm getting a ```NU1001``` error when adding ```"Xunit" : "2.1.0"``` to my project.json :

```
 "frameworks": {
    "dnx451": {
      "dependencies": {
        "Xunit": "2.1.0",
        "Akka": "1.0.5",
        "Akka.TestKit": "1.0.5",
        "Akka.TestKit.Xunit2": "1.0.5"
      }
    }
  }
```

Which results in the following :
![dnxissue](https://cloud.githubusercontent.com/assets/1357057/12123868/92767616-b3e3-11e5-82c4-00b630be799a.png)

It (Xunit 2.1.0) appears to conflict with ```Akka.TestKit.Xunit2``` dependency on ```Xunit >= 2.0.0``` (which is weird)

Is this an Akka.TestKit.Xunit2 package depedencies or NuGet issue?

/Maciej

**Comment by Horusiath** [comment]
I know that it works fine with xUnit 2.0. Maybe we should change this issue into task to update Akka.TestKit.Xunit2 dependency on xUnit 2.1?

**Comment by Silv3rcircl3** [comment]
Akka.TestKit.Xunit2 was updated to xUnit 2.1 in #2162
