### ISSUE TITLE
Invalid address error when connecting to remote systems and no hostname specified

### ISSUE THREAD

**Issue by thelegendofando** [akkadotnet/akka.net#1619]
If you have no hostname specified in HOCON, you get a "Invalid address" error when trying to connect to seed nodes (only tested with seed nodes running locally).

However, if you specify a hostname of "0.0.0.0", there's no issue.

These's a default applied if the hostname is blank - IpAddress.Any
```c#
Hostname = string.IsNullOrEmpty(configHost) ? IPAddress.Any.ToString() : configHost;
```
Therefore, a blank hostname and a hostname of "0.0.0.0" should behave the same.

I suspect the issue might be here:
```c#
PublicHostname = string.IsNullOrEmpty(publicConfigHost) ? configHost : publicConfigHost;
```
In the case where the hostname is blank, the public-hostname will be assigned blank
In the case where the hostname is "0.0.0.0", the public-hostname will also be assigned "0.0.0.0"

Therefore having the default of Hostname instead of configHost appears to be a simple fix:
```c#
PublicHostname = string.IsNullOrEmpty(publicConfigHost) ? Hostname : publicConfigHost;
```

**Comment by Aaronontheweb** [comment]
@thelegendofando yep, that makes sense - would you like to send in a pull request for this change?

**Comment by thelegendofando** [comment]
@Aaronontheweb done. https://github.com/akkadotnet/akka.net/pull/1621

**Comment by Aaronontheweb** [comment]
Thanks! @thelegendofando

**Comment by thelegendofando** [comment]
@Aaronontheweb For some reason git didn't pick up the removal of the old code. It shouldn't break anything, it's just messy. I've submitted PR https://github.com/akkadotnet/akka.net/pull/1623 to fix
