### ISSUE TITLE
TeamCity is not cleaning out build artifacts in the working directory

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1622]
Saw an issue on #1613 where build output from #1608 was being used. This is a result of us using snapshot dependencies on TeamCity - so we need to modify some settings to have the entire checkout directory blown away when the build chain finishes.

There's a handy setting for doing this in TeamCity that I think should work:
http://stackoverflow.com/a/11887207/377476

**Comment by Aaronontheweb** [comment]
I think this should be fixed now.

**Comment by Aaronontheweb** [comment]
If my current fix didn't do the trick, the alternative is to switch from snapshot dependencies to artifact dependencies - which might also have some added benefits of faster build times and true build parallelization.

**Comment by danielmarbach** [comment]
So does this mean this should make #1608 green as well?

**Comment by Aaronontheweb** [comment]
Damnit - this didn't do the trick. Have to migrate to artifact dependency builds.

**Comment by Aaronontheweb** [comment]
Confirmed by the failure on #1641 - need to migrate to artifact dependencies.

**Comment by Aaronontheweb** [comment]
Resolved.
