### ISSUE TITLE
TestKit EventFilter should support specifying external ActorSystem to filter events

### ISSUE THREAD

**Issue by akoshelev** [akkadotnet/akka.net#1630]
please see https://github.com/akkadotnet/akka.net/pull/1525 for details

**Comment by akoshelev** [comment]
@Aaronontheweb As ```TestKitBase.EventFilter``` is a property, not a method, I'm unable to create an overload. Would you like me to create a separate method, like ```TestKitBase.CreateEventFilter(ActorSystem)``` instead? Another way would be to create overloads for ```EventFilterFactory.Exception```, ```EventFilterFactory.DeadLetter``` etc

**Comment by Aaronontheweb** [comment]
@akoshelev 

> As TestKitBase.EventFilter is a property, not a method, I'm unable to create an overload. Would you like me to create a separate method, like TestKitBase.CreateEventFilter(ActorSystem) instead?

Yes, that's a good idea - would you like to move forward with it?

**Comment by Silv3rcircl3** [comment]
@akoshelev any progress on this ?

**Comment by akoshelev** [comment]
@Silv3rcircl3 As I've received response from the team, I'll continue working on it

**Comment by Silv3rcircl3** [comment]
@akoshelev could you maybe explain again what response you need? The only one I can see here is about the separated method which @aaronontheweb already answered.

**Comment by akoshelev** [comment]
@Aaronontheweb @sadprofessor It's almost done. I've got one more question. After such refactoring, the following code is no longer valid
```csharp
        protected T Intercept<T>(Func<T> func, ActorSystem system, TimeSpan? timeout, int? expectedOccurrences, MatchedEventHandler matchedEventHandler = null)
        {
            var timeoutValue = timeout.HasValue ? _testkit.Dilated(timeout.Value) : TestKitExtension.For(system).TestEventFilterLeeway;

```
The problem lies with TestKitExtension. If I create an actor system, TestKit extensions will not be available for it, so the code above fails with NRE. I may only suggest to always use ```TestKit.Sys``` actor system here, but I'm not sure this is a good way to do it. Any ideas?

**Comment by Silv3rcircl3** [comment]
@akoshelev you could check if the given system has the TestKitExtension and if so use the leeway from it or otherwise use it from the _testkit. 

```
var leeway = system.HasExtension<TestKitSettings>()
       ? TestKitExtension.For(system).TestEventFilterLeeway
       : _testkit.TestKitSettings.TestEventFilterLeeway;

var timeoutValue = timeout.HasValue ? _testkit.Dilated(timeout.Value) : leeway;
```
