### ISSUE TITLE
F# API doesn't have support for ILogReceive

### ISSUE THREAD

**Issue by object** [akkadotnet/akka.net#1636]
We are writing a new application in F# using Akka.NET, and it's essential for us to log all messages received by actors. In Akka.NET messages are not logged unless the actor type implements ILogReceive marker interface, and when using C# it's just a matter of adding this interface to actor's class definition. With F# it doesn't work since F# actors are basically functions with mailbox processing, and all of them internally use FunActor that inherits a helper Actor type. Here's a definition of Actor:

    [<AbstractClass>]
    type Actor() = 
        inherit UntypedActor()
        interface IWithUnboundedStash with
            member val Stash = null with get, set

As you can see, it doesn't implement ILogReceive, so no messages will be logged. So how logging of received messages be enabled for F# actors? With current approach that uses maker interface I can't see any other option except for making Actor implement ILogReceive:

    [<AbstractClass>]
    type Actor() = 
        inherit UntypedActor()
        interface IWithUnboundedStash with
            member val Stash = null with get, set
        interface ILogReceive

This will introduce semantical difference between C# and F# actors: the latter ones will support (but not enable by default) logging incoming messages, while for C# actors logging received messages must be enabled declaratively. However, right now C# and F# are also different in a more negative way: the latter ones don't support incoming message logging at all.

**Comment by Horusiath** [comment]
I don't think that we should add support for `ILogReceive` for F# actors by default. This feature introduces an additional overhead over message processing pipeline, while being extremly rare in it's use cases - tbh. @object you are the first person from over a year I've heard, that uses this feature.

**Comment by object** [comment]
Are you sure the overhead is significant? Here's the only place it's checked:

if (System.Settings.AddLoggingReceive && _actor is ILogReceive) {...}

So in order for the code block to be triggered the logging of received messages must be enabled, and if so, then the user's intension is probably to log received messages. In fact it took me some time to figure out that it's not sufficient to simply add "receive = on" to Akka configuration, I had to go through and add ILogReceive to every actor definition to be able to generate their logs. I see that Scala Akka requires use of LoggingReceive wrapper to enable incoming message logging, so in this respect C# reflects the original Scala design. But this brings us to a question: how can this type of logging be enabled for F# API? Right now, this section of Akka confgiration (and corresponding functionality) is simply ignored.

And being the first user of this feature I might suspect there're simply not very many developers using Akka.NET F# API, are there? I don't think this feature is exotic. I believe it's quite essential for system monitoring.

**Comment by object** [comment]
BTW, if you see any possible option to extend F# API with this feature, I might spend some time on PR, but right now I can't figure out any other way of adding it except for the one I mentioned above.

**Comment by Horusiath** [comment]
From the perspective of a system monitoring in 99,99% of the cases you don't want to log every single message, for few reasons:

- as akka can process millions of messages per second on medicore hardware (default C# impl: ~30mln/sec on 8 cores), logging each one of them would most likely overwhelm your system.
- most of common cases, like actor failures during message processing, undelivered messages etc. are already covered by standard logging mechanism
- in almost any real-life scenario, you don't get 1-2 message per request, instead having whole pipeline of them - in that case logging messages by default without any context won't serve it's role, as you still won't be able to deduce anything from them.

**Comment by object** [comment]
I agree with most of you said about typical Akka use cases, except perhaps that Akka is suitable not only for systems with millions of messages per second, and then this scenario can make more sense, especially during the development phase. But let's not go in that direction, the issue is about lack of support for certain feature in F# API and the question if what can be done to support it, or to rephrase it: what is most logical compromise given that it's impossible to make ILogReceive configuratble:
- Consider this feature as not supported so "receive = on" will have no affect on actors written in F#;
- Respect "receive = on" configuration option and trigger incoming message logging for all F# actors assuming that this is what users want since they turned the flag on in the configuration.

Being biased as an issue raiser I of course lean towards the second alternative, but the best would be to find a way to make F# API configurable, something I am researching now with no resolution so far.

**Comment by Horusiath** [comment]
Why wouldn't you just use `logInfo mailbox (msg.ToString())` or it's formatted version?

**Comment by object** [comment]
Of course this is a viable option that will fit our needs, but it takes away the beauty of standard Akka configuration. I raised this issue not due to the practical needs of our current project, but because current F# API lacks some feature comparing to C# and Scala counterparts.

**Comment by object** [comment]
Looking at Scala, it requires LoggingReceive wrapper which is similar to ILogReceive in C#, here is how it works there:

def receive = LoggingReceive {
                // normal receive here
              }

What if F# has something similar, e.g.:

let loggingReceive (receive: IO<'Message>) = 
    // TODO: implement logging
    receive

Actor where we want message logging to be enabled:
    let rec loop () = actor {
        let! message = loggingReceive <| mailbox.Receive()
        ... continue with message processing

I haven't looked at how this can be implemented, just playing with syntax options.

**Comment by Horusiath** [comment]
@object F# API is kept minimal, there are a lot of features from C#/Scala that are not there, simply because they can be implemented without much effort using standard F# syntax.

**Comment by object** [comment]
I see. If this is intentional, I will try to resolve it in a less generalized way.

**Comment by object** [comment]
I guess this should be good enough for anyone who wants to log received messages. Explicit though but OK.

logDebugf mailbox "%A" message

**Comment by Horusiath** [comment]
I think, we managed to get an explanation for this design decision. Closing this.

**Comment by object** [comment]
Sure. The explanation was convincing. Thanks for sharing your thoughts.
