### ISSUE TITLE
Introduce code contracts library

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1637]
Right now we're providing some level of argument checking by manual assertions with possible `ArgumentException` or `ArgumentNullException` in some of the constructors. While this is step in a good direction, we could make further improvement by more static analysis made by `System.Diagnostics.Contracts` library.

The idea is to replace all `if(assertion) throw ...` with their Code Contracts equivalents. This also means analysis of existing code for places, where such contracts could be applied.

**Comment by Zetanova** [comment]
The TC need to support the ccrewriter plugin and every contributer needs to install it.
I am using it myself mostly for debug time assertions and to make Contracts for argument validation on Interfaces.

**Comment by sean-gilliam** [comment]
It looks like Code Contracts are being phased out according to https://github.com/dotnet/docs/issues/6361. Closing this issue.
