### ISSUE TITLE
Implement split brain resolver for akka cluster

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1640]
Right now there are no good ways to determine downed nodes inside akka.net cluster. The only option is auto-down flag which is not a valid in case of network partition, as it will result in split brain scenario. There are few possible strategies in such case:

- **static quorum** - in static cluster, unreachable node will be downed if it's not visible from more than a half of nodes from provided cluster node size.
- **keep majority** - similar to static quorum, but doesn't depend on static number of nodes set upfront. Instead majority is defined by last reach ability of the node in period prior it's disassociation.
- **keep oldest** - here we consider an oldest node to be a reference point. When node is unreachable, if it doesn't see the oldest node, it will be downed.
- **keep referee** - similar to keep oldest but the reference node is statically defined through config.

On the [JVM side](http://doc.akka.io/docs/akka/rp-15v09p01/scala/split-brain-resolver.html) such resolvera have been implemented already . This task is about to implement them on the .NET side as well.

**Comment by Aaronontheweb** [comment]
should be noted that feature is not OSS on the JVM

**Comment by maxim-s** [comment]
What if implement  [Raft](https://raft.github.io/) on top of akka cluster?

**Comment by rogeralsing** [comment]
IMO, we should close this as out of scope for the project.
I would welcome any such effort but Id rather see it as a 3rd party repo
