### ISSUE TITLE
Fluent configuration

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#165]
I've seen that all of current Akka.NET configuration is created through Hocon strings. It would be nice to provide some in-code mechanism (eg. Fluent NHibernate). This would make programming with Akka safer (compile time type checker), and lower it's entry barrier (intellisense).

I could volunteer with that.

**Comment by rogeralsing** [comment]
@akkadotnet/developers 
Everyone argree on obsoleting the fluent config and closing this?

**Comment by HCanber** [comment]
Yes

**Comment by vchekan** [comment]
Documentation still provides example with Fluent, making new developers troubleshooting problem which does not exist:
http://getakka.net/docs/deployment-scenarios/Console

**Comment by Lavinski** [comment]
The reason for this issue being closed seems to be missing.
