### ISSUE TITLE
Akka.TestKit.NUnit doesn't work with NUnit 3.x

### ISSUE THREAD

**Issue by nelsonwellswku** [akkadotnet/akka.net#1651]
Tested with Akka.TestKit.NUnit 1.0.5 and NUnit 3.0.1

When running the unit tests with ReSharper test runner, the tests are discovered for a split-second but then removed and there's no indication in the UI that they were attempted to be ran. When using the NUnit 3 console runner, the tests simple do not exist.

The Akka.TestKit.NUnit package's dependency is listed as NUnit (≥ 2.6.4) which means there are no dependency issues at installation time. Maybe the Nuget dependency could be changed until a proper fix is in?

**Comment by rogeralsing** [comment]
cc @Silv3rcircl3 are you working on this?

**Comment by Silv3rcircl3** [comment]
@rogeralsing yep will give it a try, or @nelsonwellswku do you want to take this one?
