### ISSUE TITLE
Port Testkit.DeadLettersFilter.Any

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1656]
This would be helpful to have: https://github.com/akka/akka/blob/master/akka-remote/src/test/scala/akka/remote/transport/AkkaProtocolStressTest.scala#L104

There are a number of helper functions that make it easier to work with the `EventFilter` in the Akka.NET TestKit and we should port those.

**Comment by DmitryBatalov** [comment]
Hi, I've looked at current code and looks like it was implemented already. https://github.com/akkadotnet/akka.net/blob/8466b5e4e18df45e2f857e734f3da8fdc46ed56c/src/core/Akka.TestKit.Tests/TestEventListenerTests/DeadLettersEventFilterTests.cs#L39
