### ISSUE TITLE
Make perf tests for cluster sharding

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1661]
It would be actually have some performance metrics on some of thecluster sharding operations. I think, that initial parts we could test would be:
- Average Time to first access local/remote shard.
- Average time to access consecutive local/remote shards, excluding the first try.
- Average time to access entity in shard, when rebalancing triggers - both in case of unexpected and graceful shutdown.

And all of them tested on few different persistent backends to make sure how it's affecting whole process.

**Comment by Aaronontheweb** [comment]
duplicate of #3083
