### ISSUE TITLE
Generate ReferenceSource web site automatically

### ISSUE THREAD

**Issue by JeffCyr** [akkadotnet/akka.net#1662]
This project https://github.com/KirillOsenkov/SourceBrowser give the opportunity to create our own referencesource web site.

http://akkadotnetsource.eastus.cloudapp.azure.com/

It's handy to quickly browse source code without opening the sln in VisualStudio, the navigation is far superior than github source code browsing.

It would be nice if it could be automatically generated on the Docs step.

**Comment by Aaronontheweb** [comment]
This would be a super cool addition to the project - marking it as up for grabs. Happy to lend a hand to whomever wants to take this on and show them where and how the build process would need to be modified to support this. Petabridge would also be happy to provide any Azure hosting / whatever needed to actually host the site.

**Comment by jden123** [comment]
Let me try :)

**Comment by jden123** [comment]
PR #1691
