### ISSUE TITLE
PersistentShard throws NRE on recovery.

### ISSUE THREAD

**Issue by trbngr** [akkadotnet/akka.net#1663]
Looks like we don't respect the `snapshot-after` setting. 

This causes a brand new shard to save a snapshot with null entries. Next time the system boots up, the shard with crash with NRE.

**Comment by trbngr** [comment]
Hmm. Seems like a serialization issue.
`ShardState.Entities` is null in the `SnapshotOffer`.

**Comment by Horusiath** [comment]
I think good approach here would be creating `ShardState.None` being `default(ShardState)` and comparing it with incoming `SnapshotOffer.Snapshot` inside PersistentShard. Example:

```csharp
if ((offer = message as SnapshotOffer) != null && offer.Snapshot is ShardState 
    && !Equals(offer.Snapshot, ShardState.None))  // this is new condition
{
    State = (ShardState)offer.Snapshot;
}
```
