### ISSUE TITLE
Move Dependency Injection plugins out of the core repository

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1672]
This issue is about moving DI frameworks out of the core repository to dedicated repositories inside akkadotnet organization. Reason behind that is simple: core repository has grown big over the time and now it's full of things that are not essentially *core* of the Akka.NET. Other important reason is perspective of release cycles - we don't want to skip important bugfixes and updates in side plugins until the release of core plugins (which as one may expect may have longer release cycle). 

Along with that we could make a call for arms for the people willing to be the "face and spirit" behind each one of them.

Another thing: all DI plugins are based on `Akka.DI.Core` project. This should probably remain in core repo as shared part. Question similar to `Akka.Persistence.Sql.Common` - as this project is quite abstract in nature, we should probably keep it with at least one concrete implementation. Which one?

DI repositories to create:

- Akka.DI.AutoFac
- Akka.DI.CastleWindsor
- Akka.DI.Ninject
- Akka.DI.StructureMap
- Akka.DI.Unity
- Akka.DI.SimpleInjector ??? (see #1647)

**Comment by Danthar** [comment]
Good point.

My vote for the concrete implementation would be Autofac.

**Comment by CarlosTorrecillas** [comment]
Is there any plan on going ahead with this? Would be really interested in get the SimpleInjector implementation in.

Cheers,
Carlos.

**Comment by Danthar** [comment]
@CarlosTorrecillas Yes there are. There is currently already a https://github.com/akkadotnet/Akka.DI.SimpleInjector repos made available. You place a PR there.
