### ISSUE TITLE
Move logging plugins out of the core repository

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1673]
This issue is about moving logging frameworks out of the core repository to dedicated repositories inside akkadotnet organization, namely: 

- Akka.Logger.CommonLogging
- Akka.Logger.log4net
- Akka.Logger.NLog
- Akka.Logger.Serilog
- Akka.Loger.slf4net

Reasons for this are similar as in #1672. Also we would like to have dedicated maintainer on the wall of fame for each of those as well :)

**Comment by Danthar** [comment]
Are we going to keep one concrete lib in, like with the DI ? Or are we relying on the default console logger for this ?

**Comment by Danthar** [comment]
I will work on for starters Serilog in the next few days, and the others after that, if nobody takes them.

**Comment by Horusiath** [comment]
Repositories are prepared

**Comment by Danthar** [comment]
Great!. Thanks :+1:

**Comment by Danthar** [comment]
Ok. Serilog is outta there: https://github.com/akkadotnet/akka.net/pull/1716

**Comment by Danthar** [comment]
NLog is done. log4net is awaiting merge.
2 more to go.

**Comment by Danthar** [comment]
All logging repos are moved out of core.
