### ISSUE TITLE
Move TestKit plugins out of the core repository

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1674]
This issue is about moving TestKit frameworks out of the core repository to dedicated repositories inside akkadotnet organization, specifically:

- Akka.TestKit.NUnit
- Akka.TestKit.NUnit3
- Akka.TestKit.VsTests
- Akka.TestKit.Xunit
- Akka.TestKit.Xunit2 - tbh I don't know if we should remove this one, as it's core plugin for all internal specs.

Reasons are the same as in #1673 and #1672. Dedicated people to take a fame and glory for looking over each of these are also welcome :)

**Comment by Silv3rcircl3** [comment]
I could take the NUnit ones

**Comment by Silv3rcircl3** [comment]
@Horusiath is there a decision weather Xunit2 should remain in the core repository?

**Comment by Silv3rcircl3** [comment]
The XUnit plugins will remain in the core repository and since the other two are removed we can close this one.
