### ISSUE TITLE
Cluster Sharding Issues

### ISSUE THREAD

**Issue by trbngr** [akkadotnet/akka.net#1679]
I have a couple issues with cluster sharding at the moment.

1. I have to wipe out the entire persistence store before I can restart a cluster. Many exceptions are thrown.

~~2. After a while all messages get buffered and never delievered.~~

Here's a repro: https://eventdayapp.blob.core.windows.net/cdn/ShardingProblems.zip

It's referencing akka binaries from the output of contrib/cluster/akka.clustersharding so, you'll need to change the paths to your local machine in ConsoleApplication5.csproj.

**Comment by trbngr** [comment]
I just realized that passivated entities do not completely get terminated. This seems to be the reason why every message eventually gets buffered.

If I take passivation out of the mix, everything runs forever.

**Comment by trbngr** [comment]
The buffering issue was caused by me not stopping my entity. It's a non-issue.

**Comment by trbngr** [comment]
On a hunch that cassandra (and my dirty FS impl) persistence was the problem, I decided to try SQL persistence....and everything just works.

So it seems that the problems are with that particular persistence extension.

**Comment by Aaronontheweb** [comment]
@trbngr I'll work with you on the C* Akka.Persistence implementation if you want to open some issues there

**Comment by trbngr** [comment]
Once I figure out what they are ;)

**Comment by trbngr** [comment]
@Aaronontheweb This might not be an issue with `Akka.Cluster.Sharding` after all. It seems that `Akka.Persistence.Cassandra`is saving empty snapshots of `PersistentShardCoordinator+State`.

And TBH, I think `Akka.Persistence.SqlServer` is having trouble too. When using that, I was receiving `SnapshotFailure` messages.

So...I think we're on the right track...gonna write some tests.

**Comment by trbngr** [comment]
@Aaronontheweb @Horusiath I've narrowed this down to the serializer not being able to deserialize `Akka.Persistence.Serialization.Snapshot, Akka.Persistence` with `Akka.Cluster.Sharding.PersistentShardCoordinator+State, Akka.Cluster.Sharding` as its `Data` property.

The snapshot is written just fine. Just can't deserialize it.

**Comment by trbngr** [comment]
I just realized that this is probably related to #1677

**Comment by trbngr** [comment]
Seems Json.net is unable to deserialize ImmutableCollections if `PreserveReferencesHandling` is used.

**Comment by Aaronontheweb** [comment]
@trbngr merged in #1677 - so is this issue essentially JSON.NET serialization?

**Comment by trbngr** [comment]
Seems to be the case. Everything else in `Cluster.Sharding` appears to use Protobufs for serialization. It's just snapshotting that uses JSON.NET. So I'm currently at a loss on a fix.

**Comment by Aaronontheweb** [comment]
@trbngr change the default serializer for Akka.Persistence to use Wire:

https://gist.github.com/Aaronontheweb/b96ec974eb6bd6354f4e
https://www.nuget.org/packages/Akka.Serialization.Wire/1.0.6.17-beta

JSON.NET's days are numbered as the default serializer for Akka.NET - only reason we haven't officially cut over is that Wire needs more time in the wild to be battle tested and it's a major breaking change.

**Comment by trbngr** [comment]
You sir, are my God!!!

...for today :P

**Comment by Horusiath** [comment]
If changing the serializer to Wire can solve the issue, we could detect if it set as default, and when not, log Warning message informing about that fact - same could apply to distributed pub/sub and cluster client. @Aaronontheweb any thoughts?

**Comment by Horusiath** [comment]
Closing that one. Json.NET serializer warning has been set already.
