### ISSUE TITLE
Resizing Routers and Poison Pills

### ISSUE THREAD

**Issue by shivanan** [akkadotnet/akka.net#1685]
I have an actor (Let's call it _Master_) that receives messages and then spawns child actors (let's call them _Slaves_) to do work and then message back to the Master when they are done.

I've further setup the Master actor to use a RoundRobinPool router.

I had initially setup the RoundRobinPool to use a resizer with a min and max of 1,100 respectively (I'm just experimenting here).

When running a load test against the system, I've found that the the Slave actors are mysteriously getting stopped and not sending messages back to the Master. 
Upon further debugging, I've found that the Master is being sent PoisonPill messages even though I'm not explicitly doing it anywhere.

It took me some time to realize that the Resizer I setup for the Pool was probably stopping instances of the Master actor by sending it a poison pill. 

It seems to me like this behaviour is broken? When the master receives a poisonpill, all slaves are abruptly stopped. I suppose the correct way to normally handle this is to not rely on the PoisonPill message but instead handle it with a custom business-specific message and have code that gracefully handles the shutdown.

But when a resizer is involved, it looks like its directly sending a PoisonPill. 

So my question:
1. Is this intended behaviour?
2. If not, would the correct behaviour be, when constructing the resizer, to specify an alternate message type to send to stop an Actor
3. If the above sounds ok - would you accept a patch for that change?

**Comment by sean-gilliam** [comment]
Hopefully, you've found a solution to your problem. Generally questions should be directed to our gitter chat room https://gitter.im/akkadotnet/akka.net.
Issues are usually reserved for actual bugs. Closing this issue.
