### ISSUE TITLE
Akka.NET's HOCON does not treat triple-quotes correctly.

### ISSUE THREAD

**Issue by BrainSlugs83** [akkadotnet/akka.net#1687]
From the HOCON [Readme](https://github.com/typesafehub/config/blob/master/HOCON.md#multi-line-strings):
> If the three-character sequence """ appears, then all Unicode characters until a closing """ sequence are used unmodified to create a string value. Newlines and whitespace receive no special treatment. Unlike Scala, and unlike JSON quoted strings, Unicode escapes are not interpreted in triple-quoted strings.

The following code demonstrates the issue:
```
var str = @"blah\de-dah";
ConfigurationFactory.ParseString
(
    $"SomeValue = \"\"\"{str}\"\"\""
);
```
The actual contents of that string are evaluated to be:
> SomeValue = """blah\de-dah"""

The runtime error I receive clearly shows that the HOCON parser is trying to read "\d" as an escape sequence instead of two literal unicode characters:
> Unhandled Exception: System.NotSupportedException: Unknown escape code: d
>    at Akka.Configuration.Hocon.HoconTokenizer.PullEscapeSequence()
>    at Akka.Configuration.Hocon.HoconTokenizer.PullTripleQuotedText()
>    at Akka.Configuration.Hocon.HoconTokenizer.PullValue()
>    at Akka.Configuration.Hocon.Parser.ParseValue(HoconValue owner, String currentPath)
>    at Akka.Configuration.Hocon.Parser.ParseKeyContent(HoconValue value, String currentPath)
>    at Akka.Configuration.Hocon.Parser.ParseObject(HoconValue owner, Boolean root, String currentPath)
>    at Akka.Configuration.Hocon.Parser.ParseText(String text, Func`2 includeCallback)
>    at Akka.Configuration.ConfigurationFactory.ParseString(String hocon)

**Comment by rogeralsing** [comment]
I'll take a look at this one

**Comment by rogeralsing** [comment]
PR #1689

**Comment by BrainSlugs83** [comment]
Thanks, Roger!

**Comment by Danthar** [comment]
And its back, or i found another edge case

     ConfigurationFactory.ParseString
     (
            $"SomeValue = ""Data Source=C:\Dev\MyApp\bin\Debug\journal-db.db; Version=3;""
     );

**Comment by rogeralsing** [comment]
There are no tripplequotes in that example """ ?

Skickat från min iPhone

**Comment by Danthar** [comment]
After re-reading the hocon spec. I realised its actually correct behavior. Its just not how i expected it to work. The point is, if you build a filepath string in code with path.combine or whatnot. And pass that in a hocon variable. It throws with `Unknown escape code: <something>` because it parses the single `\` as an escape sequence. 
I expected it to handle file-paths transparently. But it doesn't

**Comment by rogeralsing** [comment]
https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Tests/Configuration/HoconTests.cs#L392

There is a test verifying that tripplequotes can be parsed.
We should add a case for the failing string too

**Comment by Danthar** [comment]
Ill add a testcase

**Comment by Danthar** [comment]
Additional testcase merged
