### ISSUE TITLE
Logging tests fail when using structured logging

### ISSUE THREAD

**Issue by gsimoes** [akkadotnet/akka.net#1690]
When using semantic messages for logging, the TestKit fails to assert that the log message has been sent to the bus:

For example:

`
    #region Messages

    public class NormalOperation { }

    public class ValidData : NormalOperation { }

    #endregion Messages

    public class LoggingActor : ReceiveActor
    {
        private ILoggingAdapter _log = Context.GetLogger();

        public LoggingActor()
        {
            Receive<ValidData>(data =>
            {
                // do some operation with the valid data
                _log.Info("Completed operation with valid data {somedata}", new { somedata = "somedata" });
            });
        }
    }

    [TestFixture]
    public class LoggingActorSpecs : TestKit
    {
        private IActorRef _logger;

        [SetUp]
        public void Setup()
        {
            _logger = Sys.ActorOf(Props.Create(() => new LoggingActor()));
        }

        [Test]
        public void LoggingActor_should_log_info_message_on_valid_operation()
        {
            // listen for specific INFO log message that valid data op should trigger
            // by default, this looks for an exact match on the data passed in
            EventFilter.Info(contains: "Completed").ExpectOne(() =>
            {
                _logger.Tell(new ValidData());
            });
        }
    }
`

The test above fails. I tried changing the configuration without success.

**Comment by Danthar** [comment]
This could be an issue in the Testkit. Or maybe your test definition is wrong. Ill take a look.
Which logging framework are you using ?

**Comment by Danthar** [comment]
Ok. Structured logging is only supported when using the Serilog logging framework. So if you are not using Serilog, structured logging will not work.

Also you need to provide a message formatter when using logging as explained in the docs: http://getakka.net/docs/Serilog.
