### ISSUE TITLE
Fix cluster plugin nuget packages

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1697]
I've noticed that releases of `Akka.Cluster.Tools` and `Akka.Cluster.Sharding` suffer few important problems:

- They don't have *prerelease* tag on them.
- They don't load dependent plugins, which are:
    - For `Akka.Cluster.Tools`: Akka.Cluster, System.Collections.Immutable
    - For `Akka.Cluser.Sharding`: Akka.Cluster.Tools, Akka.Persistence

**Comment by Aaronontheweb** [comment]
Ok, these updates to the FAKE script should be fairly easy.

However, let's take care of #1698 first.

**Comment by Aaronontheweb** [comment]
Resolved by https://github.com/akkadotnet/akka.net/pull/1767
