### ISSUE TITLE
Downgrade System.Collections.Immutable to 1.1.36

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1698]
See previous discussion here: #1676

**Comment by maxwellb** [comment]
The API changes look good. I ran Performance through NBench.. some tests have standard deviations thinner or wider, but averages/maxes don't seem to jump up in any alarming increments.

https://gist.github.com/maxwellb/c1eb44422427a52fa015

**Comment by Aaronontheweb** [comment]
Closed by #1733 #1693
