### ISSUE TITLE
Becoming inside ReceivePersistentActor constructor

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1699]
Send by @nerubseran

> I have been experimenting with akka.persistence (v1.0.5.15) and i ran into an unexpected situation.
In the constructor of my persistent actor, i call a private method (named Working()) to set Command and Recover handlers. When an exception is thrown during writing new events to Journal, i am able to handle PersistenceFailure message. If I change the code in my constructor so that Become method, with "Working" method as parameter, is called instead of the "Working" method i am not able to handle PersistenceFailure message. There isn't any behavior change anywhere in code.

This one handles `PersistenceFailure`:

```csharp
class SampleActor : ReceivePersistentActor
{
    public SampleActor()
    {
        Working();
    }

    private void Working()
    {
        Command<string>(msg =>
        {
            Persist<string>(msg, x =>
            {
                //do what you have to do
            });
        });

        Command<PersistenceFailure>(failure =>
        {
            //Code written here is run when an exception is thrown during writing new events to Journal
        });
    }
}
```

This one does not handle `PersistenceFailure`:

```csharp
class SampleActor2 : ReceivePersistentActor
{
    public SampleActor2()
    {
        Become(Working);
    }

    private void Working()
    {
        Command<string>(msg =>
        {
            Persist<string>(msg, x =>
            {
                //do what you have to do
            });
        });

        Command<PersistenceFailure>(failure =>
        {
            //Code written here is NOT run when an exception is thrown during writing new events to Journal
        });
    }
}
```

**Comment by Horusiath** [comment]
The same issue occurs when trying to call `Become(...)` inside `ReceiveActor` constructor.

**Comment by Danthar** [comment]
Probably related to: https://github.com/akkadotnet/akka.net/issues/1849

**Comment by Danthar** [comment]
#1849 is closed. @Horusiath Do you know if this issue is still occuring?

**Comment by Horusiath** [comment]
Closing that one. Looks like it's solved now.
