### ISSUE TITLE
Persistence is serializing Sender with "Path": "akka://AkkaEventStore/deadLetters"

### ISSUE THREAD

**Issue by vladkosarev** [akkadotnet/akka.net#1704]
I'm trying out EventStore for persistence and it works well enough but as you can see Path is serialized as "akka://AkkaEventStore/deadLetters", that doesn't seem right. Not sure how it's used, it doesn't seem to matter other than looking strange.

```javascript
{
  "$id": "1",
  "$type": "Akka.Persistence.Persistent, Akka.Persistence",
  "Payload": {
    "$id": "2",
    "$type": "AkkaEventStore.Actors.AddedLineItemToBasketEvent, AkkaEventStore",
    "_lineItem": {
      "$id": "3",
      "$type": "AkkaEventStore.Models.LineItem, AkkaEventStore",
      "Id": "e3c28601-31c1-44b3-8ef6-22b212396b44",
      "ProductId": "p1",
      "Quantity": {
        "$": "I20"
      },
      "Price": {
        "$": "I10"
      }
    }
  },
  "Sender": {
    "$id": "4",
    "$type": "Akka.Actor.ActorRefBase+Surrogate, Akka",
    "Path": "akka://AkkaEventStore/deadLetters"
  },
  "PersistenceId": "basket-136",
  "SequenceNr": 94,
  "Manifest": ""
}
```

**Comment by Horusiath** [comment]
@vladkosarev Akka.Persistence will have a little face lifting to upgrade code base to match JVM akka-persistence 2.4 features. Setting sender to dead letters is one of the points - you can read further explanation [here](http://doc.akka.io/docs/akka/current/project/migration-guide-2.3.x-2.4.x.html#Sender_reference_of_replayed_events_is_deadLetters).

**Comment by vladkosarev** [comment]
@Horusiath ah,ok, thank you. You can close this if there's already a to-do for this elsewhere. I didn't know.
