### ISSUE TITLE
Ask and exceptions, InvalidCastException

### ISSUE THREAD

**Issue by angrybug** [akkadotnet/akka.net#1712]
When Futures.Ask<TReturn> is called and the actor returned a Failure message using Tell(failure, Sender), CastTask tries to cast the Failure message to TReturn.

Am I not suppose to deal with failure like that?

**Comment by Danthar** [comment]
Not normally no. Normally you would want to use supervision to detect the error scenario and translate the error back into a suitable response.

When using Ask, you explicitly state that you expect a message of type TReturn. In such case there are 2 ways to handle error scenario's, either by passing the error details in the return message or by setting a timeout on the Ask which you can handle.

In the future please refrain from asking questions here, preferably use SO for that. We want to keep github issues reserved for bugs and problems. You are likely to get a much faster response on SO as well.
