### ISSUE TITLE
TypeLoadException with "Getting started" example?

### ISSUE THREAD

**Issue by TrexinanF14** [akkadotnet/akka.net#1715]
Hi, I'm just getting started with akka so I tried to start out with the basic example from the docs. The project builds fine, but at runtime I get a type load exception. This is running the base akka package version 1.0.6 pulled from nuget, with a clean console project on .net 4.5.1. Nothing else looks out of the ordinary in the project as far as I can tell. When I have a chance I'll try and run from source, but in the mean time does anyone have some ideas? Thanks.

Exception detail:
System.TypeLoadException was unhandled
Message: An unhandled exception of type 'System.TypeLoadException' occurred in mscorlib.dll
Additional information: Could not load type 'Akka.Actor.ActorSystem' from assembly 'akka, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by Horusiath** [comment]
It looks like you've named your project `akka`, making .NET type loader confused, as it doesn't know, which assembly should it refer to (your project or Akka.dll).

**Comment by TrexinanF14** [comment]
Ha, of course. Blindingly obvious. Thanks.
