### ISSUE TITLE
Router with ScatterGatherFirstCompletedRoutingLogic replies with Task<object>

### ISSUE THREAD

**Issue by GorisWW** [akkadotnet/akka.net#1718]
Hi

I think, there is a bug in ScatterGatherFirstCompletedRoutingLogic. Router with it replies with task (with message as result) instead of a message. 
Routers with TailChoppingRoutingLogic reply with normal message.

Test project:
[Program.cs.txt](https://github.com/akkadotnet/akka.net/files/137694/Program.cs.txt)

Output:

> Using ScatterGatherFirstCompletedRoutingLogic = False
> Result is Task'1
> Result is MessageB
> Using ScatterGatherFirstCompletedRoutingLogic = True
> Result is Task'1
> Result is Task'1
> Result is MessageB

If it is not a desired behaviour, maybe additional unwrapping will help at akka.net/src/core/Akka/Routing/ScatterGatherFirstCompleted.cs:87
Smth like: `var any =  Task.Run(async () => await await Task.WhenAny(tasks));`

Thanks

**Comment by annymsMthd** [comment]
Nice catch.
