### ISSUE TITLE
Integrate akka.net with quartz.net

### ISSUE THREAD

**Issue by maxim-s** [akkadotnet/akka.net#1725]
There is no such integration plugin. E.g: https://github.com/theatrus/akka-quartz

**Comment by Aaronontheweb** [comment]
cool - had someone ask about this the other day. I think it'd be a good third-party plugin. We can create a repo for it here if you're interested in maintaining it.

**Comment by maxim-s** [comment]
@akkadotnet/developers I've created repository https://github.com/akkadotnet/Akka.Quartz.Actor , please review
