### ISSUE TITLE
Setup build server support for all stand-alone plugins

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1732]
Need to setup CI for all of the plugins: DI, Logging, TestKits.

**Comment by Danthar** [comment]
Serilog and log4net are setup. 

There are some issues with the plugins build.fsx which is being investigated. The Serilog build file was being used as the template for most of the other plugins.
Which means that if we can fix the issues in the Serilog build.fsx. We can apply the same fixes to the other plugins.

**Comment by Danthar** [comment]
NLog, CommonLogging and slf4net are setup. The latter 2 still need there build scripts updated before CI will properly work.

**Comment by Danthar** [comment]
CommonLogging and slf4Net repos are updated

**Comment by Danthar** [comment]
Testkit and logging are setup. DI is the last one left.

**Comment by Danthar** [comment]
DI is setup as well
