### ISSUE TITLE
CPUs not getting saturated

### ISSUE THREAD

**Issue by shivanan** [akkadotnet/akka.net#1738]
I have an architecture where events are being streamed in and being processed by various actors.
I have a single event listener actor which receives events and then, depending on the event's data, sends it to one of about n processing actors. The processing actor will do some work on the event it received then process the next event in its mailbox.

'n' is typically around 10,000.

When testing, as 'n' increases, the rate at which events are processed decreases.
Which would be fine, except that CPU utilisation never maxes out.
On an 8 virtual core instance (m4.2xlarge in AWS), CPU stays around 60% when I have 10,000 child actors.
The event processing rate maxes out at around 5000 events per second.

Any idea what I'm doing wrong here and how I can utilise all CPU cores to do work?

The actual work is just processing the data through a pipeline. There are no database calls or tasks or threads or sleeps in there.

**Comment by Aaronontheweb** [comment]
you're using a single actor for event processing - that actor is only going to process one message at a time before it routes to a downstream actor. You might be bottlenecked by it. Try using multiple of those with a router.

**Comment by shivanan** [comment]
Thanks for the feedback. After a bit of experimenting, I'm reaching the conclusion that the bottleneck is in Akka.Remote?
After disabling the actual worker actors and fiddling around with using routers and dispatchers, the maximum I could get was about 3k/second (on my Parallels VM with 4 cores) when streaming events over tcp.

When I send messages from within the actor system itself, I'm getting 40k events/second.

Could this be a fundamental bottleneck in Akka.Remote or could  I be doing something wrong?

**Comment by Aaronontheweb** [comment]
Akka.Remote preserves network message order, which means messages are put into the network sequentially. One connection = 1 core at a time. Akka.Remote throughput is still something we're working on improving at the transport layer, but the message ordering guarantees are the bigger determining factor here: every message to and from the network passes through a single actor.

**Comment by Aaronontheweb** [comment]
Multiple connections will use multiple cores though - Akka.Remote is designed to scale linearly across connections

**Comment by shivanan** [comment]
That was helpful. Thanks!
By running multiple load testers (each having their own connection) I was able to get the event rate to about 11k/sec and got close to max CPU on all cores.
So it looks like that was the issue.
