### ISSUE TITLE
Akka.Persistence - Ensure journals do not reset HighestSequenceNr after journal cleanup (deletion of all messages)

### ISSUE THREAD

**Issue by cconstantin** [akkadotnet/akka.net#1739]
See https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Persistence.TestKit/Journal/JournalSpec.cs#L265

**Comment by Danthar** [comment]
Considering that meanwhile the sql persistence is updated. I vote we 'unskip' the test 'Journal_should_not_reset_HighestSequenceNr_after_journal_cleanup'

And close this issue.

/cc @akkadotnet/core

**Comment by cconstantin** [comment]
+1

**Comment by alexvaluyskiy** [comment]
It has already unskipped here https://github.com/akkadotnet/akka.net/pull/1931 and here https://github.com/akkadotnet/akka.net/pull/1937

**Comment by alexvaluyskiy** [comment]
Not actual anymore
