### ISSUE TITLE
Akka.Persistence - Update documentation/README

### ISSUE THREAD

**Issue by cconstantin** [akkadotnet/akka.net#1741]

**Comment by ravengerUA** [comment]
Could we just take the docs from Akka/Scala documentation and convert code examples?

**Comment by cconstantin** [comment]
For sure, I just didn't get around to it after doing the code update.

**Comment by alexvaluyskiy** [comment]
I could take it

**Comment by Horusiath** [comment]
Thanks @alexvaluyskiy !

**Comment by Danthar** [comment]
PR was merged so closing it
