### ISSUE TITLE
ActorSelectionSpec does not cover JVM test criteria

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1748]
Noticed today that our `ActorSelectionSpec` doesn't cover most of the stuff covered in the JVM's version of the spec:

https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSelectionSpec.scala

For instance, https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSelectionSpec.scala#L344 - do we have a test that verifies that a message intended for a non-existent actor goes to DeadLetters? There's lots of others that need ot be covered here.

**Comment by Silv3rcircl3** [comment]
Started with it here https://github.com/Silv3rcircl3/akka.net/commit/fca3fd10d3504eb32d6491953485d6d1e6a7dc0d

Currently 10 specs are failing.
