### ISSUE TITLE
Create VS project template for akka.cluster.sharding

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1759]
The main idea here is lower the learning curve of `Akka.Cluster.Sharding` - which currently needs "a little" configuration - by creating preconfigured project template for it. What that template should contain?:
- Reference to all necessary nuget dependencies:
  - Akka.Cluster.Sharding
  - Akka.Cluster.Tools
  - Akka.Cluster
  - Akka.Persistence
- Prepared HOCON configuration in App.config ([example](https://github.com/akkadotnet/akka.net/blob/dev/src/examples/Cluster/ClusterSharding/ClusterSharding.Node/App.config)).
- Prepared sample implementation of `IMessageExtractor`.

Ideally it should be runnable after creating project itself.

**Comment by Aaronontheweb** [comment]
Finished this recently: https://github.com/akkadotnet/akkadotnet-templates/blob/dev/docs/WebApiTemplate.md
