### ISSUE TITLE
Bring RemoteWatcher up to code with JVM Akka.Remote.RemoteWatcher

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1763]
Our implementation currently has some differences which might be the result of changes that have occurred in the target JVM implementation over time.

For instance https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/RemoteWatcher.scala#L280 on the JVM, looks like https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Remote/RemoteWatcher.cs#L524,

which may be wrong.

**Comment by maxim-s** [comment]
I have stashed changes for it, I can check them
