### ISSUE TITLE
Add ActorMailboxSpec

### ISSUE THREAD

**Issue by cconstantin** [akkadotnet/akka.net#1793]
We should port the tests for mailboxes, such as https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorMailboxSpec.scala

**Comment by wmeints** [comment]
If nobody else is working on this I'd like to take this one up.

**Comment by Silv3rcircl3** [comment]
Go ahead :+1:

**Comment by wmeints** [comment]
I notice there's a file MailboxesSpec in Akka.Test/Dispatcher. This test implements a few test cases for the mailboxes. Would you like to have the new tests in the same spot?

**Comment by Silv3rcircl3** [comment]
@wmeints I think that are different specs, the MailboxesSpec tests a actual implementation weather the ActorMailboxSpec only tests that the actor is using the correct mailbox. 

This seems to be the counterpart of the MailboxesSpec 
https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/dispatch/PriorityDispatcherSpec.scala

**Comment by wmeints** [comment]
:+1: Will write a the tests separate of the mailboxesspec.

**Comment by wmeints** [comment]
Does Akka.NET support bounded mailboxes right now? I'm running into an issue where an actor cannot be created because I used `IBoundedMessageQueueSemantics`.

```
public class BoundedQueueReportingActor : MailboxReportingActor, IRequiresMessageQueue<IBoundedMessageQueueSemantics>
{

}
```

**Comment by wmeints** [comment]
Since there are only a few mailboxes that are supported I'm going to add tests for those and leave the rest for another time. Hope that's okay :-)

**Comment by Horusiath** [comment]
@wmeints no problem ;)

**Comment by Silv3rcircl3** [comment]
@wmeints could you create issues for the missing mailboxes or create a list here? 
We should keep track of them.

**Comment by wmeints** [comment]
Sure, I can do that. Will take a look at it tonight and create issues for the individual mailbox types.

**Comment by wmeints** [comment]
Just noticed that there is a BoundedQueBasedMailbox class. The only thing missing for the bounded mailboxes is BoundedMailbox class. I think this one should, just like the UnboundedMailbox, be an alias for a sane implementation.

**Comment by alexvaluyskiy** [comment]
@wmeints could we close it?
