### ISSUE TITLE
ActorRefs.Nobody is not preserved by remoting

### ISSUE THREAD

**Issue by morganski** [akkadotnet/akka.net#1828]
If a remote actor returns an IActorRef of ActorRefs.Nobody, by the time it is received by the client end it's changed to a remote actor reference. Thus it becomes tricky to check if the remote end returned ActorRefs.Nobody as the object returned has been munged by remoting. I'd suggest that ActorRefs.Nobody is special cased and always turns up at the receiver as what was sent.

**Comment by morganski** [comment]
I asked a question on SO about this recently... http://stackoverflow.com/questions/36021603/actorrefs-nobody-being-translated-by-remoting

**Comment by Aaronontheweb** [comment]
Resolved by #1829
