### ISSUE TITLE
Possible bug: calling `Become` twice in the same method

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1849]
Had a thread in Gitter chat today where it looked like calling `Become` twice produced an unexpected behavior.

Suppose an actor has two behaviors:

A
B

If inside the constructor we call Become(A) and method A calls Become(B), what's the final behavior? It looks like current behavior is to include all of the Receives for both A and B.

**Comment by Danthar** [comment]
I verified that calling Become(A) in the constructor, which calls Become (B) results in that only the handlers for become(A) are active.

**Comment by Aaronontheweb** [comment]
thanks @Danthar - does that seem like the correct behavior? I think so, but cc @akkadotnet/developers

**Comment by Danthar** [comment]
I think it might not be what people expect. They might expect that the handlers from B() are active.
However I also think that the current behaviour is the most straightforward one. 
Im porting the HotSwapSpec to further verify that this behaviour in on par with the jvm.

**Comment by Aaronontheweb** [comment]
@Danthar can we close this then?

**Comment by Danthar** [comment]
Yes
