### ISSUE TITLE
Default journal field has been erased from default persistence config

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1861]
After one of the PRs we've missed that `akka.persistence.journal.plugin = "akka.persistence.journal.inmem"` config value has been erased, making a breaking change in the API. Before, when journal plugin used was not specified explicitly, in-memory journal was used by default. Now it will throw an exception instead.

**Comment by Aaronontheweb** [comment]
@Horusiath ok, please go ahead and put this back in today and we'll do another patch immediately.

**Comment by Aaronontheweb** [comment]
Btw, this is why you need to have "default configuration" specs like how Akka.Remote, Akka.Cluster, and so forth do.

**Comment by Danthar** [comment]
PR was merged
