### ISSUE TITLE
Akka DI Unity Version Issue? 

### ISSUE THREAD

**Issue by amarwadi** [akkadotnet/akka.net#1868]
Hello,
After upgrading to Unity 4.0.1, I started noticing that the Akka.DI.Unity is giving errors due to a dependency on an older version of Unity.

The type 'IUnityContainer' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Practices.Unity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

Is there a way to upgrade the DI.Unity nuget package to reference the newer version of Akka?

Any help would be highly appreciated.

Thanks,
Anup

**Comment by Danthar** [comment]
Alot of the DI plugins are behind in respect of their depedence on their respective DI container. We just did a release of the main repo. Another quick maintenance release is bound to follow soon.
We plan to move the DI containers out of the main repo and into their own to allow for these out of band releases.

For now what you can do, is make a PR that updates the unity container, while making sure that the tests for it pass.

**Comment by Danthar** [comment]
Unity has been extracted into its own repo. PR's can be made there.
