### ISSUE TITLE
Invalid cast to NewtonSoftJsonSerializer in Akka.Persistence.FSharp when using Wire

### ISSUE THREAD

**Issue by object** [akkadotnet/akka.net#1896]
If Wire is set as Akka serializer, attempt to take shapshot of a persistent actor causes the following exception:

> "Unable to cast object of type 'Akka.Serialization.WireSerializer' to type 'Akka.Serialization.NewtonSoftJsonSerializer'."
> System.InvalidCastException: Unable to cast object of type 'Akka.Serialization.WireSerializer' to type 'Akka.Serialization.NewtonSoftJsonSerializer'.
>    at Akka.Persistence.FSharp.FunPersistentActor`3.OnCommand(Object msg)
>    at Akka.Persistence.UntypedPersistentActor.ReceiveCommand(Object message)
>    at Akka.Persistence.UntypedPersistentActor.Receive(Object message)
>    at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
>    at Akka.Persistence.Eventsourced.<ProcessingCommands>b__90_0(Receive receive, Object message)
>    at Akka.Persistence.Eventsourced.AroundReceive(Receive receive, Object message)
>    at Akka.Actor.ActorCell.ReceiveMessage(Object message)
>    at Akka.Actor.ActorCell.Invoke(Envelope envelope)
> 

The exception is caused by the following code:

```
    override x.OnCommand (msg: obj) = 
        match msg with
        | :? 'Command as cmd -> aggregate.exec mailbox state cmd
        | _ -> 
            let serializer = UntypedActor.Context.System.Serialization.FindSerializerForType typeof<obj> :?> Akka.Serialization.NewtonSoftJsonSerializer

```
The cast to NewtonSoftJsonSerializer fails because the serializer is Wire.

**Comment by Silv3rcircl3** [comment]
@object this issue was fixed with your [PR](https://github.com/akkadotnet/akka.net/pull/1900) wasn't it?

**Comment by object** [comment]
Yes,
