### ISSUE TITLE
DI (StructureMap) -- Should the resolver trickle down into child actors?

### ISSUE THREAD

**Issue by matneyx** [akkadotnet/akka.net#1908]
When you create an actor using an IDependencyResolver, should that resolver trickle down into the child actors, so their children automatically benefit from that IDependencyResolver?  Because, as far as I can tell (which, admittedly, isn't very far), it doesn't work with StructureMap.

As it stands now, all of my parent actors have to new up a new resolver (I'd just inject it, but I'm not sure how to inject Context.System) before they make child actors.

Is there a better way?  Am I missing something?

**Comment by Danthar** [comment]
No it should not.

And the docs explain how to create child actors using DI.

http://getakka.net/docs/Dependency%20injection

**Comment by matneyx** [comment]
Thank you, @Danthar.
