### ISSUE TITLE
Akka cluster node is shutting down

### ISSUE THREAD

**Issue by Pisha91** [akkadotnet/akka.net#1914]
Cluster node very often fails to start with error "Failed to startup Cluster. You can try to increase 'akka.actor.creation-timeout'.". Our solution hosted on Azure cloud service with one web role(client role in Akka cluster)  and two worker roles (seed node and working node).

**Comment by Aaronontheweb** [comment]
Looking into this now - testing a fix for it.

**Comment by Aaronontheweb** [comment]
This is now resolved.
