### ISSUE TITLE
Unexpected ConfigurationFactory.ParseString behavior

### ISSUE THREAD

**Issue by mmisztal1980** [akkadotnet/akka.net#1917]
Consider the following code sample (which you'll find to be very similar to the contents of the Lighthouse's HostFactory):

```
var hostName = "127.0.0.1";
var port = "30001";
var heliosString = string.Format(@"akka.remote.helios.tcp.public-hostname = {0} akka.remote.helios.tcp.port = {1}", hostName, port);
var heliosConfig = ConfigurationFactory.ParseString(heliosString);
```

Having debugged this, I've found that:

heliosString: 
```
"akka.remote.helios.tcp.public-hostname = 127.0.0.1 akka.remote.helios.tcp.port = 30001"
```

heliosConfig: 
```
{
  akka : {
    remote : {
      helios : {
        tcp : {
          public-hostname : "127.0.0.1 akka.remote.helios.tcp.port"
        }
      }
    }
  }
  30001 : []
```
That doesn't exactly look right to me - unless somebody disagrees?

**Comment by corneliutusnea** [comment]
@mmisztal1980 I got bitten by the same issue.
The original code in the Lighthouse has the heliosString on TWO lines:
https://github.com/petabridge/lighthouse/blob/master/src/Lighthouse/LighthouseHostFactory.cs#L57

```
string.Format(@""akka.remote.helios.tcp.public-hostname = {0} 
akka.remote.helios.tcp.port = {1}"
```
It's not very clear as it looks like just a string wrapping.
But because it's on two lines it gets in the config file as two lines which when parsed generate:
```
   tcp: {
      public-hostname : "127.0.0.1"
      port: 30001
   }
```
Which is correct.

**Comment by rogeralsing** [comment]
This string var heliosString =
string.Format(@"akka.remote.helios.tcp.public-hostname
= {0} akka.remote.helios.tcp.port = {1}", hostName, port);
Is not valid hocon.
hocon either needs a comma between the two different keys, or a linebreak.

//Roger

**Comment by rogeralsing** [comment]
Hocon either needs a linebreak or a comma between key value pairs.
So @corneliutusnea is correct.

**Comment by mmisztal1980** [comment]
@corneliutusnea & @rogeralsing confirmed - adding a comma fixed it for me - thanks guys :)
