### ISSUE TITLE
Starting a receptionist on more than one node makes the CPU to go to 100%

### ISSUE THREAD

**Issue by schepersk** [akkadotnet/akka.net#1918]
[AkkaClusterClientCpuIssue.zip](https://github.com/akkadotnet/akka.net/files/240568/AkkaClusterClientCpuIssue.zip)

When trying to start a receptionist on all nodes of a single role, from the moment the cluster forms, these nodes together consume 100% of available CPU. When only 1 such node is started, there is no problem.

I have created a sample to demonstrate this which is attached..

Thanks in advance for any remarks..

**Comment by corneliutusnea** [comment]
I think I found the issue.
The DistributedPubSubMediator(s) keep sending each other updates continuously with "new" Deltas thinking that the partner(s) have the wrong version.

One bug is in CollectDelta https://github.com/akkadotnet/akka.net/blob/4acfa7c363bfa83ac71849a5a8487c8d6b1bbcb1/src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs#L350
The filledOtherVersions correctly gets initialized with the version of from the other partners but then in line 351 the version is overridden with 0 thus making the code later in line 368 think the parnter is out of date and re-send the bucket.

Second bug is in https://github.com/akkadotnet/akka.net/blob/4acfa7c363bfa83ac71849a5a8487c8d6b1bbcb1/src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs#L340
That return is incorrect as it returns true always when entry.value > 0 so for every check it think it has to send the update.
I'm preparing a PR for this fix.

**Comment by alexvaluyskiy** [comment]
It has been fixed a long time ago
