### ISSUE TITLE
Akka.Persistence.Redis

### ISSUE THREAD

**Issue by kantora** [akkadotnet/akka.net#1939]
Hello.
I've found out that there's no Redis support fo Persistence module and could not find any plans for its creation. Also, as I can see, now all Persistence plugins moved to separate repositories.

So I created one (https://github.com/kantora/Akka.Persistence.Redis). How can I contribute it (of course in case there is any interest in it)?

**Comment by alexvaluyskiy** [comment]
There is Redis support here: https://github.com/akkadotnet/Akka.Persistence.Redis
But that implementation uses a different Redis package.

**Comment by kantora** [comment]
Ouch!!! How could I miss it ;(
But as I've already written it - if there is any sense in it - please let me know.

**Comment by Horusiath** [comment]
I don't mind incorporating @kantora module instead, as I don't have enough time to work on the Akka.Persistence.Redis to develop it to well working state.

PS: only troubling part I see is setting TTL for journal. There is nothing (or should be nothing) wrong with having journal actor living for the whole actor system lifespan.

**Comment by alexvaluyskiy** [comment]
@Horusiath just a question, why you have used RedisBoost, instead of Stackexchange.Redis or ServiceStack.Redis?

**Comment by Horusiath** [comment]
@alexvaluyskiy API looked simpler, and it has built-in serialization support.

**Comment by kantora** [comment]
>PS: only troubling part I see is setting TTL for journal. There is nothing (or should be nothing) wrong with having journal actor living for the whole actor system lifespan.

In my case - it is working for the whole journal. So you will loose all events for the actor or none of them due to TTL. I think this can be useful in some cases when old obsolete actors leak with there storage.

**Comment by kantora** [comment]
Unfortunately got a problem with this implementation.
I tried to use `Wire` directly to serialize `Persistent` object to the journal. It worked fine in tests but failed in real life. While trying to serialize `ShardRegionRegistered` as a payload it fails with very long stacktrace and `NullReferenceException` message.

I'll try to fix it, but at this moment, lib is not working.

**Comment by Horusiath** [comment]
@kantora Looking at your implementation, the reason why `ShardRegionRegistered` (and any other message containing `IActorRef` fields) will throw an error is that your serialization implementation has no support for surrogates. 

To serialize some of the fields having special characterisitc (like `IActorRef`), serializer must be enchanced by the context of execution environment (in case of akka, it's actor system). Take a look at [Akka.Serialization.Wire](https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/serializers/Akka.Serialization.Wire/WireSerializer.cs) for more clues.

**Comment by kantora** [comment]
@Horusiath thanks for the clue. 
Nevertheless, I've got additional questions.

In `WriteMessagesAsync` method, I am getting the list of `AtomicWrite`. The default implementation uses `Task<IImmutableList<Exception>>.Factory.ContinueWhenAll(tasks)` construction to write to the journal. But this does not guarantee (but it will be in most cases) the order of writes in case there will be several `AtomicWrite` for one `PersistenceId`. Is it ok?

Also, sequence numbers are already enclosed into the `IPersistentRepresentation` objects. So I can expect that journal can get the highest sequence number event to persist and then the lowest one? Is it so and should be treated ok? What should be done in the case of duplicate sequence numbers?

And at last, I was confused with `Data store connection problems must not be signaled as rejections` direction. But should be done in the case of storage denial?

**Comment by Horusiath** [comment]
Order of persisted events depends on the sequence nr, which is generated by `PersistentActor` itself, not the order in which they were written. 

Duplicate sequence numbers can potentially corrupt the persistent stream structure (unless underlying backend will explicitly forbid them i.e. sql journals have unique constraints to ensure that). But this is a problem only when somebody will try to create two persistent actors for the same persistent entity - which is explicitly mentioned as an invalid behavior in akka docs.

The `Data store connection problems must not be signaled as rejections` is about journal actor behavior in case of failued db connections. In case of those, we cannot reject write requests - as they could potentially be considered correct later, after restoring a connection - because the fault is not on their side. This kind of failure affects whole journal.

**Comment by kantora** [comment]
>Order of persisted events depends on the sequence nr, which is generated by PersistentActor itself, not the order in which they were written.
That's a pity :( I desired to get the advantage of Redis lists, where sequence nr will be just position in list with the offset for deleted records... Ok, I'll fix it.

As I understood journal is an actor itself. Will it be a good idea to get rid of TPL Tasks and spawn some child actors instead with ConsistientHash router to do the read/write/serialize job?

**Comment by Horusiath** [comment]
@kantora what would you need it for?

**Comment by kantora** [comment]
This will automatically take care for:
```
        /// Please also note that requests for the highest sequence number may be made concurrently
        /// to this call executing for the same `persistenceId`, in particular it is possible that
        /// a restarting actor tries to recover before its outstanding writes have completed.
        /// In the latter case it is highly desirable to defer reading the highest sequence number
        /// until all outstanding writes have completed, otherwise the <see cref="T:Akka.Persistence.PersistentActor" />
        /// may reuse sequence numbers.
```
as all read/write request will be treated by the same worker actor synchronously (I am going to use PersistenceId as ConsistientHash)

**Comment by Horusiath** [comment]
This won't work with consistent hashing for a reasons I've described in [this SO answer](http://stackoverflow.com/questions/36726026/creating-actor-per-domain-object). This would also cause an explosion of actors (as each persistent actor would need its companion actor behind a journal).

**Comment by kantora** [comment]
I still can't get a problem. Maybe I have some misunderstanding.

The journal actor is a singleton for given configuration. So typically it will be only one journal actor for the whole actor system. Is it right?

If I use fixed-sized `ConsistientHashingPool` router (size is defined in configuration), why should it lead to the explosion of actors?

**Comment by Horusiath** [comment]
This comes from the definition of router itself. Router is nothing else that an actor facade hiding pool of actors behind. If you want to have consistent hashing `with nr-of-instances=1000`, that means, you'll have 1000 actors spawned behind that router. For consistent hashing to work the way you want it to work with persistent actors, the number of routees had to be equal the number of persistent actors.

Other thing is that, you'd need to keep the correlation between routee and persistent actor, which is pretty close to impossible in consistent hashing scenario.

**Comment by kantora** [comment]
I thought that I can create  router with, for example, 10 workers. As I got from the documentation, in the case of 1000 persistent actors it should mean that every worker will take care of requests from approximately 100 different persistent actors (of course I don't want to create a worker actor for every persistent actor). But requests from the same persistent actor will always be proceeded by the same worker (that is what I need).

**Comment by kantora** [comment]
So the number of workers is just a max degree of parallelism in request processing and can work as performance shaper for an external resource.

**Comment by kantora** [comment]
At this moment, serialization problems were fixed. Also fixed work with sequence numbers.

**Comment by alexvaluyskiy** [comment]
@kantora would you mind, if I move your redis project here and update it to Akka 1.1.0?

**Comment by alexvaluyskiy** [comment]
StackExchange.Redis backend much better than RedisBoost as we have in our repo

**Comment by kantora** [comment]
@alexvaluyskiy absolutely not. Cool. Please tell me if anything will be needed from me.

**Comment by alexvaluyskiy** [comment]
Finally we got a Akka.Persistence.Redis plugin here https://github.com/akkadotnet/Akka.Persistence.Redis/issues/5
This plugin was composed from three versions of Redis plugin @Horusiath version, @kantora version, and from scala version

**Comment by alexvaluyskiy** [comment]
@kantora my version of plugin doesn't not support TTL. If you want to have this feature there, you can create an issue.
