### ISSUE TITLE
Hyperion documentation

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1941]
We need to document the features of the Hyperion serializer soonish, as people are starting to use it and need to know how to:
1. Define surrogates
2. Use the Hyperion equivalent of any JSON.NET serialization directives or attributes that might be exposed by Hyperion

EDIT: Changed Wire -> Hyperion (@sean-gilliam)

**Comment by sean-gilliam** [comment]
Need to change this from Wire to Hyperion. :)

**Comment by Aaronontheweb** [comment]
We've actually done a pretty thorough job on this recently - going to close.
