### ISSUE TITLE
Akka.Cluster.Tools - Singleton not available

### ISSUE THREAD

**Issue by mmisztal1980** [akkadotnet/akka.net#1960]
I believe I've configured my cluster singleton and singleton-proxy correctly, however when I try to send messages to the proxy, I'm getting "Singleton not available" error messages.

The cluster is running on a single physical node.

I'm setting my singleton up like this:
```
var props = Props.Create<LogDispatcher>();

var singletonProps = ClusterSingletonManager.Props(
                singletonProps: props,                                     
                terminationMessage: PoisonPill.Instance,
                settings: ClusterSingletonManagerSettings.Create(system));

var dispatcher = system.ActorOf(singletonProps, 
                name: "logDispatcherSingleton");
system.ActorOf(ClusterSingletonProxy.Props(
                singletonManagerPath: "/user/logDispatcherSingleton", 
                settings: ClusterSingletonProxySettings.Create(system)), 
                name: "logDispatcher");
```

And the HOCON looks like this:
```
akka {
            actor {
              serializers {
                akka-singleton = "Akka.Cluster.Tools.Singleton.Serialization.ClusterSingletonMessageSerializer, Akka.Cluster.Tools"
              }
              serialization-bindings {
                "Akka.Cluster.Tools.Singleton.ClusterSingletonMessage, Akka.Cluster.Tools" = akka-singleton
              }
              serialization-identifiers {
                "Akka.Cluster.Tools.Singleton.Serialization.ClusterSingletonMessageSerializer, Akka.Cluster.Tools" = 14
              }
            }
          
            cluster {
							seed-nodes = ["akka.tcp://AkkaFabric@127.0.0.1:30001"]
							roles = []
              
              singleton {
                singleton-name = "logDispatcherSingleton"
                hand-over-retry-interval = 1s
                min-number-of-hand-over-retries = 10
              }
              
              singleton-proxy {
                singleton-name = ${akka.cluster.singleton.singleton-name}
                singleton-identification-interval = 1s
                buffer-size = 1000 
              }
						}					
          }
```

Am I doing anything wrong?

**Comment by Horusiath** [comment]
I'm not sure if lighthouse is not messing with cluster singleton, as it could be recognized as the oldest node but is not aware of singleton being started (this will probably need further investigation). But what you could try is to add role cluster node where singleton should reside - make sure that lighthouse node doesn't share that role.

To set cluster singleton role, use following configuration:

```hocon
akka.cluster {
    roles = [ "<role-name>" ]
    singleton {
        role = "<role-name>"
    }
}
```

**Comment by alexvaluyskiy** [comment]
Try this
```C#
var singletonProps = ClusterSingletonManager.Props(
                singletonProps: props,                                     
                terminationMessage: PoisonPill.Instance,
                settings: ClusterSingletonManagerSettings.Create(system), 'logDispatcherSingleton');
```

**Comment by mmisztal1980** [comment]
@alexvaluyskiy that syntax doesn't appear to be ok...

![image](https://cloud.githubusercontent.com/assets/1357057/15323163/f1ff89ea-1c40-11e6-865a-f8d08a19c972.png)

**Comment by alexvaluyskiy** [comment]
@mmisztal1980 then use double-quotes

**Comment by mmisztal1980** [comment]
@alexvaluyskiy are you sure that ```ClusterSignetonManager.Props``` takes a string argument? I'm not seeing such an overload

**Comment by alexvaluyskiy** [comment]
Do you have this line in config? It is mandatory
```hocon
akka.actor.provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"
```

And in your example you have a variable for manager, but you don't have for proxy. Are you sure you are sending messages to the proxy, not to manager?

**Comment by mmisztal1980** [comment]
Found it. 
The node containing the singleton didn't join the cluster properly due to a small dns problem. I've tweaked some settings and now it works fine - the singleton is receiving the messages as expected.

Thanks guys, and sorry to trouble you :)
