### ISSUE TITLE
Bring RemoteDeathWatch up to code with JVM; use SendSystemMessage instead of Tell for DW messages

### ISSUE THREAD

**Issue by veblush** [akkadotnet/akka.net#1976]
When an actor who has child actors is due to stop, all child actors will stop before their parent. When an actor stops, it sends a notification message to a parent to tell the stop event by DeathWatchNotification but a recipient of this message, a dying parent discards a message so this is forwarded to a DeadLetterListener and makes it to write unnecessary logs.

Check out following source. It creates an actor who has two child actors and stops it. (This example runs on Akka.NET 1.0.8)

```csharp
public class OneActor : UntypedActor {
    protected override void OnReceive(object message) {
        if (message is string) {
            var msg = message as string;
            Console.WriteLine($"{Self.Path}: {msg}");
            if (msg.StartsWith("!")) {
                var child = Context.ActorOf<OneActor>(msg.Substring(1));
                child.Tell("*");
            }
        }
        else Unhandled(message);
    }
}

class Program {
    static void Main(string[] args) {
        var system = ActorSystem.Create("MySystem");
        var actor = system.ActorOf<OneActor>("A");
        actor.Tell("!B");
        actor.Tell("!C");

        actor.Tell(PoisonPill.Instance);
        Thread.Sleep(1000);
        Console.WriteLine("--- A stopped");

        actor.Tell("*");
        Thread.Sleep(1000);
        Console.WriteLine("--- End");
    }
}
```

Following is output and you can see 3 dead letters. First 2 letters are unnecessary messages from children to a parent. Last one is necessary one to test DeadLetterListener work well.

```
akka://MySystem/user/A: !B
akka://MySystem/user/A/B: *
akka://MySystem/user/A: !C
akka://MySystem/user/A/C: *
[INFO][TIMESTAMP][Thread 0005][akka://MySystem/user/A] Message DeathWatchNotification from akka://MySystem/user/A to akka://MySystem/user/A was not delivered. 1 dead letters encountered.
[INFO][TIMESTAMP][Thread 0005][akka://MySystem/user/A] Message DeathWatchNotification from akka://MySystem/user/A to akka://MySystem/user/A was not delivered. 2 dead letters encountered.
--- A stopped
[INFO][TIMESTAMP][Thread 0005][akka://MySystem/user/A] Message String from NoSender to akka://MySystem/user/A was not delivered. 3 dead letters encountered.
--- End
```

Because I'm not sure this works under the intended way, I write same example on Akka 2.3.11.

```java
public static class OneActor extends UntypedActor {
    public void onReceive(Object message) {
        if (message instanceof String) {
            String msg = (String)message;
            System.out.format("%s: %s\n", getSelf().path(), msg);
            if (msg.startsWith("!")) {
                final ActorRef child = getContext().actorOf(Props.create(OneActor.class), msg.substring(1));
                child.tell("*", getSelf());
            }
        }
        else unhandled(message);
    }
}

public static void main(String[] args) {
    final ActorSystem system = ActorSystem.create("MySystem");
    final ActorRef actor = system.actorOf(Props.create(OneActor.class),"A");
    actor.tell("!B", ActorRef.noSender());
    actor.tell("!C", ActorRef.noSender());
    
    actor.tell(PoisonPill.getInstance(), ActorRef.noSender());
    try { Thread.sleep(1000); } catch (InterruptedException e) { }
    System.out.println("--- A stopped");

    actor.tell("", ActorRef.noSender());
    try { Thread.sleep(1000); } catch (InterruptedException e) { }
    System.out.println("--- End");
}
```

Following is output and you can see just 1 dead letter. Unnecessary messages which Akka.NET shows are gone. 

```
akka://MySystem/user/A: !B
akka://MySystem/user/A: !C
akka://MySystem/user/A/B: *
akka://MySystem/user/A/C: *
--- A stopped
[INFO] [TIMESTAMP] [MySystem-akka.actor.default-dispatcher-4] [akka://MySystem/user/A] Message [java.lang.String] from Actor[akka://MySystem/deadLetters] to Actor[akka://MySystem/user/A#54395235] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
--- End
```

While delve into this problem, I've found out that there are subtle differences between scala version and .net version of Akka. But still now I cannot find why they act in a different way and which is correct. Any ideas?

**Comment by Aaronontheweb** [comment]
The `DeathWatch` implementation in Akka.NET is a bit out of date - I wrote a Roslyn analyzer which helped me detect a number of instances where we were using the wrong methods for transmitting the system messages that power it. `IInternalActorRef.Tell` instead of `IInternalActorRef.SendSystemMessage`. A lot of the handling specifc to death watch notifications is built into `SendSystemMessage` and those paths aren't hit right now.

I'll be publishing the Roslyn Analyzer here later this week as part of our 1.1 release effort: https://github.com/akkadotnet/CodeAnalyzer

**Comment by veblush** [comment]
Oh my gosh, I found out what caused this problem finally and PR is in progress. BTW, it will be cool to have the analyzer helps writing robust code.

**Comment by Aaronontheweb** [comment]
@veblush I'll keep this issue open and use it as the official issue for bringing DeathWatch up to code

**Comment by Aaronontheweb** [comment]
Resolved. But see #2024 for actorcell shutdown.
