### ISSUE TITLE
Shutdown seems to have a race condition for blocking further actor creation.

### ISSUE THREAD

**Issue by veblush** [akkadotnet/akka.net#1979]
In fixing [ActorCell.StopChildren bug](https://github.com/akkadotnet/akka.net/pull/1978), I found out a test `Reliable_deny_creation_of_actors_while_shutting_down` failed sometimes, which is linked to race condition :cry:.

This test just terminates the actor system while creating bunch of actors to check system deal with this situation well.

```csharp
public void Reliable_deny_creation_of_actors_while_shutting_down() {
    var sys = ActorSystem.Create("DenyCreationWhileShuttingDone");
    Task.Delay(500).ContinueWith(_ => sys.Terminate());
    var created = new HashSet<IActorRef>();
    while (!sys.WhenTerminated.IsCompleted) {
        try {
            var t = sys.ActorOf<Terminater>();
            created.Add(t);
        }
        catch (InvalidOperationException) {}
    }
    Assert.Empty(created.Cast<ActorRefWithCell>().Where(a => !a.IsTerminated));
}
```

This test sometimes failed because some of created actors are not terminated. What?

ActorOf method calls following `MakeChild` function to create new actor. `MakeChild` reads `IsTerminating` property to check ok to go. This method looks fine.

```csharp
IInternalActorRef ActorCell.MakeChild(...) {
    if (IsTerminating) // IsTerminating == ChildrenContainer.IsTerminating
        throw new InvalidOperationException("Cannot create ...");
    // (stripped)
```

Who sets IsTerminating? It is `Terminate` method. In stopping self, it makes IsTerminating true by calling SetChildrenTerminationReason(Termination).

```csharp
void ActorCell.Terminate() {
    // (stripped)
    StopChildren();
    // RACE AREA
    // following SetChildrenTerminationReason makes IsTerminating true
    if (SetChildrenTerminationReason(SuspendReason.Termination.Instance))
    // (stripped)
```

Here you are. Calling StopChildren makes all children stop. But new actors created between StopChildren and SetChildrenTerminationReason are added successfully and missed for calling Stop. That's why this test fails.

I've tried to find out a difference with scala one but failed. There must be something. Any ideas?

**Comment by JeffCyr** [comment]
This is because ActorSystem.ActorOf is not using AttachChild like the jvm does.
See https://github.com/akkadotnet/akka.net/issues/1762#issuecomment-221516072

**Comment by veblush** [comment]
Awosome! I got it. Thanks! I just see a dragon, `RepointableActorRef`.
