### ISSUE TITLE
Implement RemoteRouterConfig

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#198]
http://doc.akka.io/docs/akka/snapshot/scala/routing.html
Remote Deployed Routees

We can currently not create Pool routers that deploy their routees to other systems.

**Comment by Aaronontheweb** [comment]
Update on this - I've implemented this feature and have the common case working well. Some of the configuration edge cases (i.e. remotely deploying a router that remotely deploys its routees) are still failing their unit tests but I'm working on fixing it now.

When I submit a PR for this, it will also satisfy #349 - all of the tests within `RemoteRouterSpec` do remote deployments between two actor systems.

**Comment by Aaronontheweb** [comment]
This has been implemented.
