### ISSUE TITLE
Cluster: API for pluggable cluster downing

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#1982]
API for pluggable cluster downing

https://github.com/akka/akka/pull/20320
It was implemented in Akka 2.4.5

**Comment by Aaronontheweb** [comment]
I think this was added to support some of the proprietary auto-downing components that Typesafe / Lightbend developed for the Reactive Platform, but it's a good idea. I could see someone writing a plugin that uses the ARM / AWS APIs to get data about whether or not a node has been removed or not and automatically downing it.

**Comment by Aaronontheweb** [comment]
Implemented in #2284
