### ISSUE TITLE
Port Akka.Cluster MultiNodeSpec: ClientDowningNodeThatIsUnreachableSpec

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#1992]
https://github.com/akka/akka/blob/master/akka-cluster/src/multi-jvm/scala/akka/cluster/ClientDowningNodeThatIsUnreachableSpec.scala

**Comment by alexpantyukhin** [comment]
I don't know why but my PR didn't attached automatically. Please find it there https://github.com/akkadotnet/akka.net/pull/2033

**Comment by alexpantyukhin** [comment]
please find my PR there https://github.com/akkadotnet/akka.net/pull/2034

**Comment by maxim-s** [comment]
Close via #2037
