### ISSUE TITLE
Port Akka.Cluster MultiNodeSpec: ClusterAccrualFailureDetectorSpec

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#1994]
https://github.com/akka/akka/blob/master/akka-cluster/src/multi-jvm/scala/akka/cluster/ClusterAccrualFailureDetectorSpec.scala

**Comment by alexpantyukhin** [comment]
I will look on this task.

**Comment by Silv3rcircl3** [comment]
Closed via #2043

**Comment by Silv3rcircl3** [comment]
Sorry my fault, @alexpantyukhin you need to create another method, mark this with the attribute and call the other three test methods from there. That's what we're doing in the other tests as well when we have multiple tests.

**Comment by maxim-s** [comment]
thank you @alexpantyukhin , close via #2044

**Comment by maxim-s** [comment]
regarding http://petabridge-ci.cloudapp.net/viewLog.html?buildId=11417&buildTypeId=AkkaNet_AkkaNetWindowsMultiNodeTests&tab=buildLog#_state=12289&focus=13179 and ```[RUNNER][12:03 PM]: Test run completed in [00:00:03.0188758] with 0/0 specs passed.```

**Comment by Aaronontheweb** [comment]
This is fixed in https://github.com/akkadotnet/akka.net/pull/2054 (waiting to be merged)

**Comment by Silv3rcircl3** [comment]
Closed via #2054
