### ISSUE TITLE
Port Akka.Cluster MultiNodeSpec: LeaderDowningAllOtherNodesSpec

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2003]
https://github.com/akka/akka/blob/master/akka-cluster/src/multi-jvm/scala/akka/cluster/LeaderDowningAllOtherNodesSpec.scala

**Comment by alexvaluyskiy** [comment]
I've implemented this spec. It doesn't pass, because cluster doesn't implement this feature itself
https://github.com/alexvaluyskiy/akka.net/commit/fb36849565a94dcffb2304d131779aca1e9ea8d7

**Comment by Aaronontheweb** [comment]
Closed by #2099
