### ISSUE TITLE
Port Akka.Cluster MultiNodeSpec: SurviveNetworkInstabilitySpec

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2015]
https://github.com/akka/akka/blob/master/akka-cluster/src/multi-jvm/scala/akka/cluster/SurviveNetworkInstabilitySpec.scala

**Comment by Aaronontheweb** [comment]
Going to move this to 1.2 - need to spend some time investigating issues with the `Conductor` in `Akka.Remote.TestKit`

**Comment by alexvaluyskiy** [comment]
Still two specs are commented

**Comment by Aaronontheweb** [comment]
In the name of putting a stop to scope creep and finally getting this release out, bumped the milestone back to 1.5.

**Comment by alexvaluyskiy** [comment]
Done https://github.com/akkadotnet/akka.net/pull/2773
