### ISSUE TITLE
ActorCell updates, rewrites to support proper child termination / recreation

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2024]
I spent the past day or so debugging issues with Cluster Deathwatch. Turns out this was the culprit.

The entire way we handle child create / terminate is out of date or incorrectly implemented. See: https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-actor/src/main/scala/akka/actor/ActorCell.scala#L421

TL;DR; - we need to be able to guarantee the following:

1. That all children are shutdown before a parent calls `FinishTerminate`.
2. That no children can be allocated while the parent is shutting down.
3. That system messages that don't have anything to do with the shutting down of children during termination are stashed.

The JVM has all of this implemented, but this will be a multi-day project for someone. The good news? The `ActorSystemSpec.Reliable_deny_create_on_shutdown` spec and scores of other unit tests will EXPLODE if this is implemented incorrectly. The bad news? This will require some yak-shaving.

**Comment by Aaronontheweb** [comment]
Symptoms of the issue:

https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/ActorCell.FaultHandling.cs#L214 - this `else` block will never be hit if we switch to a `ChildTerminating` container, because right now we don't properly account for the termination of children inside the `ChildContainer`. I watched the `UserGuardian` completely fail to shutdown (and thus, stop the actor system from terminating) as soon as it had any children. I could confirm that all of the children were properly shutdown, but the `UserGuardian` itself never did.

**Comment by Aaronontheweb** [comment]
For the time being - I'm going to continue use the buggy `StopChildren` implementation, because at least that still allows the system to be shutdown.

**Comment by alexvaluyskiy** [comment]
Persistence spec often fails in ActorCell.ReserveChild because it is possible that UnreserveChild won't executed in some cases. Is it related with this issue?

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy can't say for certain but it would not suprise me.

**Comment by Aaronontheweb** [comment]
```scala
  private[akka] def attachChild(props: Props, systemService: Boolean): ActorRef =
    makeChild(this, props, randomName(), async = true, systemService = systemService)
  private[akka] def attachChild(props: Props, name: String, systemService: Boolean): ActorRef =
    makeChild(this, props, checkName(name), async = true, systemService = systemService)
```

AttachChild impl should call `makeChild`, currently calls `ActorOf`
