### ISSUE TITLE
Actor tracing

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#2027]
As Aaron proposed, we could introduce some way of distributed tracing of actors execution contexts. For this I would propose an integration plugin for [Zipkin](http://zipkin.io/) directly of through [Opentracing](http://opentracing.io/).

I think that plugin should consist of 3 major components:
- `Traced<T>` message wrapper, that would carry all of the necessary information about current call contexts between actors. For zipkin itself this wrapper should wrap message payload + 3 extra fields:
  - `TraceId: ulong` which is an identifier of the whole trace (call context)
  - `SpanId: ulong` which is an identifier of the current span (part of the call context that takes place in the current actor).
  - `ParentSpanId: ulong?` which is a nullable identifier of a span of actor being the message sender.
  - (extra) `Sample: bool` which determines if this zipkin span is threaded as sampled.
- `Tracer` context, which should be present in each actor and handling things such as setting up current trace, generate ids, wrapping/unwrapping messages, adding annotations, and sending all of those data to collectors:
  - Each span can have a list of annotations. Annotation is a struct with some string value, timestamp and endpoint. 4 most important string values determine events such as Client send a request (cs), Server received request (sr), Server send a response (ss), and client received a response (cr) - those values are used to later display spans in zipkin UI. Beside that we can also annotate span with custom values. Notes:
    - Endpoint is struct with IPv4 address (int), port, and name of the service/actor to identify location of current span.
    - Timestamp needs to be serialized in microseconds (btw. in .NET each tick is exactly 1/10 of microsecond).
- `Collector` which could be a dedicated actor responsible for serializing and sending data to zipkin. Possibly there could be more than one collector at the time. AFAIK Zipkin handles 3 different transports:
  - **Scribe** which is a Thrift service and is not advised to be used right now. By default Zipkin has scribe listener up and running on port 9410.
  - **HTTP** which is a direct HTTP request with either JSON or Thrift message body - second one is more compact as it's binary serialization format. In that case message should be send as POST on _http://(zipkin-server-addr):9411/api/v1/spans_. Request body should contain an list of spans to be saved. Necessary HTTP headers: _Content-Type=application/x-thrift_ , _Content-Length=(length of thrift message body in bytes)_ , (optionally) _Host=(hostname)_ . Zipkin server can respond with OK or TryLater message - second one should trigger retry mechanism (should we use exponential backoff?).
  - **Kafka** which also uses thrift-encoded list of spans as a payload.

Thrift can be downloaded from [here](https://thrift.apache.org/download). To generate C# serialization classes, you'll also need their [thrift definitions](https://github.com/openzipkin/zipkin/blob/master/zipkin-thrift/src/main/thrift/com/twitter/zipkin/zipkinCore.thrift) and the simply run: `thrift -r --gen csharp zipkinCore.thrift`.

To generate trace/span IDs you'll need to generate an 56-bit long unsigned integer (here's [why 56 bits](https://github.com/twitter/zipkin/issues/199)).

**Comment by rogeralsing** [comment]
Can this be done without major changes to the internal infrastructure?
If we start wrapping Envelope in some extra envelope carrying more information, that would affect the normal path execution.
is there any way we can still keep the current internals while still having this?

**Comment by Danthar** [comment]
Is this something which could flow through the logging infrastructure ? Or does it needs to work on a lower level ?
Im asking because if we are going to make changes for this, it would probably be worthwhile to make them in such a way that we can support the issues described here https://github.com/akkadotnet/akka.net/issues/2031 as well.

Sounds to me that the collector is nothing more then a variant of the loggingactor plugin. I think we could support this without making major changes to the internal infrastructure by defining a custom trace message which gets published on the bus, and to which a collector actor subscribes.

**Comment by Scooletz** [comment]
This is a note from a person that barely knows Akka :)
To do not blow up `Envelope` out of proportion a sparse approach could be used. For each envelope passing through, add a simple `long` field which would be a unique local identifier for it (obtained by `Interlocked.Increment(ref counter)`. Having an identifier for each envelope, would enable to allocate a block of memory upfront and use this identifier as an index. The struct mentioned by @Horusiath would take:

1. TraceId: `ulong`
1. SpanId: `ulong`
1. ParentSpanId: `ulong` (nullable flag stored with the last field)
1. Flags: byte for nullability and the Sample (they can get to the top two bits of the last)
1. EnvelopeId: `long` written as a guard of whole record with `Volatile.Write`.

This gives 4 longs, which is 32 bytes. To store information about 1million ongoing messages it'd need 32MB. This would be treated as a circular buffer, overridden as soon as the counter overlaps. One additional advantage is that you could come up with other scenarios like this and simply create other buffers when needed. 
What do you think?

**Comment by Horusiath** [comment]
@Scooletz  Applying that as default for each `Envelope` brings few issues:

1. It's would be some potentially big distinction from JVM akka. And since on the JVM side there is already quite handy [akka-tracing](https://github.com/levkhomich/akka-tracing) I guess, they won't try to do this natively anytime soon.
2. We hoped to get rid of implicit senders (so probably also an `Envelope`) entirely somewhere in the far future. The main reason is to keep basic stuff minimal - don't force people to pay for the things they don't use. 

Beside that this would be interesting thing to explore in a feature branch - and to benchmark as well, since I think, that potential performance drop will be the biggest concern against this approach. Also it could give logs some contextual meaning (and maybe open possibility to optimize Ask pattern).

**Comment by cwe1ss** [comment]
fyi, We are working on a C# implementation of the user-facing OpenTracing API here: https://github.com/opentracing/opentracing-csharp

Think of it like the new Abstractions packages from Microsoft - e.g. Microsoft.Extensions.Logging.Abstractions. This would be the library that you would use if you decide to support OpenTracing. It only contains the interfaces to create spans/logs etc.

I guess the library will be ready in 2-3 weeks. Feedback is welcome :)

I'll probably start creating a Zipkin implementation afterwards.

**Comment by nate-dahlin** [comment]
Checking to see what the status of this is?
Thanks

**Comment by annymsMthd** [comment]
We are starting to use OpenTracing with Jaeger in our k8s cluster with some akka .net projects. This would be a big win to try to get going.

**Comment by cwe1ss** [comment]
There's a pretty stable version of [OpenTracing's C# API](https://www.nuget.org/packages/OpenTracing/) now. 

However, even though I'm one of the authors of that library, I'd still recommend you look at .NET's `DiagnosticSource/Activity` types first for library/framework instrumentation. They are only roughly based on OpenTracing and they don't have as many features, but those types are built into the framework so they give you zero-dependency instrumentation and the widest reach right now. 

Profilers like Application Insights automatically pick up these events. I've also created an [OpenTracing bridge for `Activity`-events](https://github.com/opentracing-contrib/csharp-netcore) (it's .NET Core only though) so if anyone is using an OpenTracing-compatible tracer (like [Jaeger](https://github.com/jaegertracing/jaeger-client-csharp)), you'd still get these events without too much configuration.

The latest guidance for instrumentation with DiagnosticSource / Activity (by the Application Insights / .NET team) is currently being worked on and can be found [here](https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/917). The other documents can be found [here](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md) and [here](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md). 
These types are also used in CoreFx to [instrument outgoing HTTP calls](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs) and in ASP.NET Core to [instrument incoming HTTP requests](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplicationDiagnostics.cs).

**Comment by Zetanova** [comment]
If we extend to the Envelope message an ambient field that would contain a reference to an immutable object, then it would be possible to implement an opentracing/diagnostic extension.

The new ambient field would be implicitly copied to all outgoing message.
The actor can explicitly overwrite the current ambient value inside its message handler.

The immutable object of the ambient field could then be processed by an IAmbientHandler extension. One example would be OpenTracing and AkkaLogger. 

In a local system scenario this new ambient field would not much decrease the performance.
but it could make some with akka.remoting.

**Comment by rogeralsing** [comment]
Some lessons from doing all of this on that other project:

Adding an extra field onto Envelope message adds another 4 bytes to every message sent in Akka.NET.
Which might not sound much, but could have a considerable impact on high load systems.
A cost that all systems would have to carry, even if they do not use tracing.

You would also have to somehow copy this value over whenever doing someActorRef.Tell
Meaning Tell on every impl of ActorRef would have to know about this ambient value.

Adding some form of API for this ontop of it all is likely a more solid way forward.

My 2 cents

**Comment by Zetanova** [comment]
I don't know, if it is possible.
Maybe to general add multiple envelope message
NoEnvelope => direct message handling (EmptyAmbient, NoSender)
Envelope => unwrap envelope (EmptyAmbient, Envelope.Sender)
AdvEnvelope => unwrap envelope (Envelope.Ambient, Envelope.Sender, maybe more)

**Comment by Zetanova** [comment]
If the unwrap code of the envelope message gets moved into the actor-plan 
then it would possible to get rid of the envelope message itself or extend it.

The ActorBase would need to set the Sender field of the IActorContext 
this i currently a readonly property.

**Comment by Danthar** [comment]
This is a solved problem. https://phobos.petabridge.com/articles/index.html
I know, this is a payed product by @Aaronontheweb but it proves there is no need to make sweeping changes in the akka.net codebase to support this.

Anyone is free to create an free OSS variant for Akka.net that does the same thing. But i think that the rest of the @akkadotnet/core agrees with me that we will not be spending much effort on this topic. Since we have plenty of other stuff that needs solving.

Therefore i am closing this issue.

**Comment by SchroterQuentin** [comment]
Are you sure that the codebase used by Phobos is the same as the open source akka.net ? I read a lot of code of this project and there isn't a single expanding point allowing us to monitor actors. I actually feel that the code was written in a way that we can't monitor actors without Phobos... Maybe Phobos use weaving ?

**Comment by Aaronontheweb** [comment]
Phobos is a proprietary library we developed many years after Akka.NET was originally architected. We outline the approach we use https://phobos.petabridge.com/articles/index.html#how-it-works - which works by swapping out the `IActorRefProvider` with a decorated one that injects telemetry.

Beyond just simple tracing and metrics, Phobos also deals with more complex real-world observability issues like noise filtering, trace compression, and performance tuning - all of which is driven by the feedback of users who trace 100m+ of actor interactions per day. 

We're not going to make Phobos available for free - I personally spend hundreds of hours per year diagnosing and updating the library for paid customers to solve these types of issues that come up. The income those customers pay is what allows me to hire people to work on Akka.NET full-time, hence why we ship high quality releases frequently with documentation and responsive support in our Discord.

I will note that we are working on another observability solution that will be available with a perpetual free tier but that's not going to include tracing - if you're interested you can attend our [February 8th, 2023 Akka.NET Community Standup](https://discord.gg/fp2gcTa9WF?event=1042477247904366673) where I'll be presenting more on it.
