### ISSUE TITLE
Bug: need to properly dispose of all dispatchers on shutdown

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2028]
Especially `PinnedDispatcher` and `ForkJoinDispatcher` instances. Right now these are left running even after the `ActorSystem` terminates.

This should be a simple fix - just need to add a termination hook for `Dispatchers`.

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb could we close it?

**Comment by Aaronontheweb** [comment]
Yep
