### ISSUE TITLE
Semantic logging context with akka.Net

### ISSUE THREAD

**Issue by tocsi-hun** [akkadotnet/akka.net#2031]
In Serilog the logged event can have more properties than the ones actually included in th message.  Those extra values can come from the log context. In that log context it is possible to store properties for each log message (`Serilog.ILoger.ForContext` or `Serilog.Context.logContext.PushProperty`). It is very useful because it can help to keep the actual log call short while maintaining a consistent set of logged data. Behind the scenes it uses a thread local static collection for properties. 

I do not know any similar possibility in akka.Net logging. And although I consider this serilog feature very useful I cannot use it with akka.Net because of the following issues:
- cannot use the .ForContext for obvious reasons - decoupled interfaces
- I still can however add a reference from my actors project to serilog and then I could use the Serilog.Context.logContext.PushProperty. But first of all i would like to leave the logging as decoupled as possible (fully :)) and anyway it couldn't work because of the nature of akka.Net which just creates a log message and puts it on the queue. So the actual processing will be done on a separate thread (serilog context based on a thread local collection).

akka.Net has the LogEvent and LogMessage. The LogEvent is actually an akka message.
akka.Logger.Serilog uses the LogEvent to set the serilog context before actually logging.

**So I think:**
The LogEvent could contain context information like serilog context has - simple name-value pairs. In the actor it could be possible to push name-value pairs into that context. Then any logger adapter could use those extra info - in case of a semantic logger like Serilog it can be used to extend the logged data.

I'm a bit biased for Serilog because we use it. I have no clue how useful this LogEvent 'improvement' could be in general, but I hope other might find it useful.
What is your opinion about this?

**Comment by Aaronontheweb** [comment]
Doesn't the serilog plugin already do this?

**Comment by tocsi-hun** [comment]
It is possible that I missed something, but I doubt it has a chance at all. The Serilog author could tell it for sure, though.
The plugin relies on the event messages of akka. Akka is the one who actually creates and sends the messages. Therefore, it uses the message classes defined in akka (LogEvent and its descendants). The context information should be in the LogEvent message (at least I couldn’t find any another way to carry it along) and the info should be inserted at the “akka side”. I checked the code but couldn’t find anything where that extra information could go. And couldn’t find any sign of a function that could be used for it. Also checked the code of the serilog plugin. It really sets up the serilog context, but it has only that few, fixed amount of information can be found in the LogEvent (event time, event thread and event source).
If you start thinking about it and look around you might find that the LogMessage already has an object for the message parameters. But that cannot be used for several reasons (for example message formatters). And anyway, for context information the best place is the context of the message which is the LogEvent.

I try to describe what I mean with some code snippets. 
I would like to something like this (strongly simplified) in an actor base class:

```
protected readonly ILoggingAdapter Logger;

ctor {
Logger = Context.GetLogger();

Receive(typeof (DocumentMessage), msg =>
{
   //doing pre handling

	//here could set the logging context - now with some pseudo code
	LogContext.Add("DocumentId", msg.Document.Id);
	LogContext.Add("Sender", msg,Document.SenderAddress);
	LogContext.Add("....

	//calling the actual document handler
	HandleDocumentMessage(msg);

	LogContext.Remove("DocumentId")  //note that Serilog uses a using syntax, that could fit here as well instead of these separated add and remove
	LogContext.Remove("...

   //doing after handling 
});
}

protected abstract void HandleDocumentMessage(msg);


```
In an actor implementation:

```
override HandleDocumentMessage(msg)
{
   //do whatever
   Logger.Error("Oops, I cannot access this file: {File}", fileName);
   // in this piece of code a lot of log message could be written.
   // note that I did not have to include the actual document in the log call, still did not loose the information.
   ...
}
```

Now akka would assemble the message to the event bus. It should put the "LogContext" information (key value pairs) into the LogEvent.  Until this point the akka code should be touched, but this is only the half of the story.
Then the message would be sent and the serilog plugin - or any plugin - could receive it. Those plugins should take this info into account. In case of Serilog it uses the code below to set the context information:

```
private ILogger SetContextFromLogEvent(ILogger logger, LogEvent logEvent)
{
    logger = logger
                .ForContext("Timestamp", logEvent.Timestamp)
                .ForContext("LogSource", logEvent.LogSource)
                .ForContext("Thread", logEvent.Thread.ManagedThreadId.ToString().PadLeft(4, '0'));

    return logger;
}
```

after the akka modification something like the code below could be added here: 

```
foreach (var contextProperty in logEvent.ContextProperties)
{
     logger = logger.ForContext(contextProperty.Name, contextProperty.Value);
}
```

And finally in the log I would have a log entry something like this
```
{
	"message": " Oops, I cannot access this file: C:\somefolder\somefile.txt",
	"properties": {
		"File": "C:\somefolder\somefile.txt",
		"DocumentId": 12345,
		"Sender": "Big company",
		"Timestamp": "2016-06-01",
		"LogSource": "[akka://MySystem/user/CommunicationModuleActivatorGateway/s00] ",
		"Thread": "0021"
	}
}

```

I hope my explanation is not obfuscated. If there already is something with which I can achieve the same outcome, then please enlighten me. Otherwise please consider my idea.

**Comment by Danthar** [comment]
Tosci is right. The semantic logging as it is now. Captures the context of the seriloggeractor instead of the actor that publishes the logevent on the bus.

-----Original Message-----

**Comment by timoch** [comment]
We can solve the issue by letting the logger plugins provide both a LoggingAdapter that produces the LogEvents and a LoggerActor that receives the LogEvent.
Whatever custom functionality can then be supported by encapsulating them in implementation specific LogEvent classes.

It can already be done now but it does not feel right. Getting a ILoggerAdapter is done through calling a static extension method on the actor's context -- so we can just substitute that static call for another one. At the same time setting up the LoggerActor is done through configuration. 2 weights 2 measures here. 

On the other hand, using Serilog's specifics inside the actors implementation forfeits any chance at switching logging implementation with minimum impact. Which IMO reduces the benefit of having 'transparent' logging support through the actor context

I for my part am going to use Serilog directly for my own logging and plug the SerilogActor to get the internal Akka log messages.

What do you think ?

**Comment by tocsi-hun** [comment]
**A**
To allow to customize the logging adapter requires a lot of things.

1. The GetLogger method should not use the new BusLogging()  
2. for this some configuration should be implemented
3. For the custom ILoggingAdapter implementation - if we want to keep the logging on the event bus and why wouldn’t we – for each type of log a new subclass should be defined (Debug, Info, Warning, Error) with the extra information we need there
4. In the custom ILoggingAdapter implementation we have to use those new subclasses.
5. Have to find out how to communicate our context information to the custom ILoggingAdapter implementation, since its interface does not have such a thing.

 
**B**
To use my proposed solution would require

1. Adding a key-value collection to the LogEvent class
2. Have to find out how to communicate our context information to the BusLogging. For which a thread local dictionary like object would do.

**C**
Or you can still avoid using the logging adapter and use whatever logger you want in the way you like. But – as it was pointed out – it makes the logging api switch a nightmare. And with that you probably would lose the async logging behavior which also affects the performance.

I guess we could agree that the case C is a bad idea.

Although allowing custom logging adapters (case A) could open up more possibilities I doubt it worth the effort. And it could end up in a pretty big mess anyway by mandating dedicated logging adapter for a lot of log plugins and for different groups of plugins etc.  Even the implementation of a logger plugin would be much more complicated, because you might need your own logging adapter or might not. 

So I might be wrong, but I would still prefer my original idea (case B).

**Comment by timoch** [comment]
I agree with you on point B being a good option. But point 2 requires to plugin an configurable ILoggingAdapter. Otherwise it is yet another abstraction that needs to be introduced.

BusLogging could be used as a base ILoggingAdapter implementation, simply add virtual factory methods for events of each log level.
A SerilogBusLogging would fetch its ambient properties and stuff them in the key-value collection of LogEvent. It won't have to care how the messages reach the SerilogLogger..

As for C being a bad idea, I don't know. As soon as you start using advanced logging features like Serilog's ForContext, you are tying yourself with that specific library unless you explicitly abstract it away on your own. Performance-wise, Serilog, log4net and I believe all the major libraries already support async logging out-of-the box. So if you look at the pure performance, I can only guess it would be better to use those libraries directly. On the other hand, using Akka's abstractions enable treating log events the same as any other information stream and may enable modeling use cases like auditing using the same level of abstraction as the other functionalities.

**Comment by Danthar** [comment]
Closing outdated issue. Nowadays the OpenTracing spec with Phobos solved most if not all tracing needs for akka.net. 
Also there is some semblance of structured logging available via the Serilog logger integration for akka.net
