### ISSUE TITLE
Test scheduler not working with ScheduleTellOnceCancelable

### ISSUE THREAD

**Issue by qwoz** [akkadotnet/akka.net#2052]
I'm running into a strange issue with `ScheduleTellOnceCancelable` and testing. My test code uses:
```
        private TestScheduler Scheduler
        {
            get
            {
                return (TestScheduler)Sys.Scheduler;
            }
        }
```
and inside the actor I want to test I have:
```
        Context.System.Scheduler.ScheduleTellOnceCancelable(TimeSpan.FromSeconds(60), ...);
```
When the Tell fires, I send a message back to the calling actor. If my test code uses:
```
        Scheduler.Advance(TimeSpan.FromSeconds(61));
        ExpectMsg<Message>();
```
then it fails. If I change this to:
```
        //Scheduler.Advance(TimeSpan.FromSeconds(61));
        ExpectMsg<Message>(TimeSpan.FromSeconds(61));
```
then everything works. Is there something I need to do inside the actor I'm testing to have it use the appropriate scheduler, whether production or testing? Or is this a bug?

**Comment by Silv3rcircl3** [comment]
@qwoz this is working for me
```csharp
        public Spec()
            : base(TestConfigs.TestSchedulerConfig)
        {

        }

        [Fact]
        public void Scheduler()
        {
            var actor = ActorOf<SchedulerActor>();
            actor.Tell("schedule", TestActor);
            Thread.Sleep(500);
            ((TestKit.TestScheduler)Sys.Scheduler).Advance(TimeSpan.FromSeconds(61));
            ExpectMsg("Ping");
        }

        private class SchedulerActor : UntypedActor
        {
            protected override void OnReceive(object message)
            {
                Context.System.Scheduler.ScheduleTellOnceCancelable(TimeSpan.FromSeconds(60), Sender, "Ping", Self);
            }
        }
```

Some notes:
- make sure that the message is processed _before_ you call `Advance`, you could also use a different dispatcher, [as explained in this issue](https://github.com/akkadotnet/akka.net/issues/1417), instead of using `Thread.Sleep`.
- set the `TestActor` as `sender` explicit, because otherwise it is set to dead letters

**Comment by qwoz** [comment]
I don't set the sender or add a delay to my other tests which all pass. However I tried changing my calls to use the pattern `actor.Tell(message, TestActor)` and I added `Thread.Sleep(500)` before the `Scheduler.Advance` call. I was hoping that `Advance` would provide the happy path experience of ensuring that enough time was allotted to deliver the messages, plus the `ExpectMsg` call gives it three additional seconds to process anyways.

Regardless, after trying those changes it still doesn't work if I remove the `TimeSpan.FromSeconds(61)` parameter from the `ExpectMsg` call. It works when I add it back in.

I'll see if I can provide some minimal code that demonstrates this issue.

**Comment by qwoz** [comment]
Here's some simple code that demonstrates the issue. This uses NUnit. Note that the only difference between the messages "start" and "start2" is that "start" does a `ScheduleTellOnceCancelable` with a 1 second delay, otherwise the logic is the same.

```C#
    [TestFixture]
    public class FailureTestCase : TestKit
    {
        public FailureTestCase() : base(@"akka.scheduler.implementation = ""Akka.TestKit.TestScheduler, Akka.TestKit""") { }

        private TestScheduler Scheduler
        {
            get
            {
                return (TestScheduler)Sys.Scheduler;
            }
        }

        [Test]
        public void SimpleTest()
        {
            IActorRef act = Sys.ActorOf(Props.Create(() => new TestActor()));
            act.Tell("start");
            Scheduler.Advance(TimeSpan.FromSeconds(61));
            ExpectMsg<string>();
        }

        [Test]
        public void SimpleTest2()
        {
            IActorRef act = Sys.ActorOf(Props.Create(() => new TestActor()));
            act.Tell("start2");
            Scheduler.Advance(TimeSpan.FromSeconds(61));
            ExpectMsg<string>();
        }
    }

    public class TestActor : ReceiveActor
    {
        public TestActor()
        {
            Receive<string>(message =>
            {
                switch (message)
                {
                    case "start":
                        ICancelable c = Context.System.Scheduler.ScheduleTellOnceCancelable(TimeSpan.FromSeconds(1), Self, "continue", Sender);
                        break;

                    case "start2":
                        Self.Tell("continue", Sender);
                        break;

                    case "continue":
                        Sender.Tell("done");
                        break;

                    default:
                        break;
                }
            });
        }
    }
```

**Comment by Silv3rcircl3** [comment]
> I don't set the sender or add a delay to my other tests which all pass.

Yeah ignore the sender note, it's obviously not your problem since it's working when you're setting the timeout via `ExpectMsg`, it was however an issue for me while I wrote the example code, that's the reason I mentioned it. I need to investigate why that happened in my example.

> I was hoping that Advance would provide the happy path experience of ensuring that enough time was allotted to deliver the messages, plus the ExpectMsg call gives it three additional seconds to process anyways.

That 500 ms are not for the scheduled message, they ensure that this `actor.Tell("schedule", TestActor);` message was processed from the actor __before__ `Advance` is called, so the additional three seconds from the `ExepctMsg` call are irrelevant here. What the `TestScheduler` basically does is to store all scheduled messages and if you call `Advance` it iterates over all scheduled messages and sends the ones that are scheduled in the given time range, so if you call `Advance` __before__ your actor has scheduled a message, the message isn't sent until you call `Advance` a second time.

This is working for me

```csharp
        [Test]
        public void SimpleTest()
        {
            IActorRef act = Sys.ActorOf(Props.Create(() => new TestActor()));
            act.Tell("start");
            //ensure that the actor has processed the start message 
            //and scheduled the continue message before we call Advance
            Thread.Sleep(500);         
            Scheduler.Advance(TimeSpan.FromSeconds(61));
            ExpectMsg<string>();
        }

        [Test]
        public void SimpleTest2()
        {
            IActorRef act = Sys.ActorOf(Props.Create(() => new TestActor()));
            act.Tell("start2");
            //nothing to schedule here
            //Scheduler.Advance(TimeSpan.FromSeconds(61));
            ExpectMsg<string>();
        }
```

![image](https://cloud.githubusercontent.com/assets/6583600/16166070/2aa158b8-34e8-11e6-9657-4fae78d4b16f.png)

**Comment by qwoz** [comment]
Yep, that does work for me as well. I have a more complicated test involving a hierarchy of actors where the various modifications don't work. I'll see if I can narrow down the cause further.

**Comment by qwoz** [comment]
I've found the issue. It appears to be the way I'm (ab)using `.Ask` when getting info from another actor within the code I'm testing. Here's an example:

```C#
            Receive<int>(message =>
            {
                // This fails
                var ok = Self.Ask<bool>(true).Result;
                Sender.Tell(message);
            });

            Receive<char>(message =>
            {
                // This succeeds
                var ok = Self.Ask<bool>(true).ContinueWith(x =>
                {
                    return message;
                }, TaskContinuationOptions.AttachedToParent & TaskContinuationOptions.ExecuteSynchronously).PipeTo(Sender);
            });

            Receive<bool>(message =>
            {
                Sender.Tell(message);
            });
```
So this has nothing to do with scheduling at all. I was hoping I could use `actor.Ask(...).Result` as a shortcut to keep my code mostly inline. In my case one actor can process _n_ similar messages, each one depends on retrieving info (of the same type, but with varying identifiers) contained in the message.

Looks like I'll need to read up on https://github.com/petabridge/akkadotnet-code-samples/tree/master/PipeTo and figure out how best to structure this code so that I can retrieve the info, then resume processing the message I had originally received.

**Comment by rogeralsing** [comment]
Asking self and directly waiting for a result will deadlock your actor.
That being said, do you really need to send a message to ask what you want?
Why not just extract that code to a method you can call?

**Comment by qwoz** [comment]
Asking self was just a trivial example to identify why my test was failing. In my code, the `.Ask` is to a completely different actor in a separate part of the hierarchy. Similar to the bootcamp code example:
```C#
pendingJobReplies = _coordinator.Ask<Routees>(new GetRoutees())
      .Result.Members.Count();
```
I know that's not asynchronous, so I changed my actor code to instead use something like:
```C#
ReceiveAsync<Foo>(async message =>
{
    var data = await OtherActor.Ask<Bar>();
    // do something with the data
}
```
This works quite well. The bulk of all the logic (including creating child actors, pub/sub, even a database request) happens in under 200ms (I added copious logging with a stopwatch to log elapsed milliseconds). I can see that prior to `Scheduler.Advance` I create my scheduled tell on a delay. After that, the schedule is advanced, the `ExpectMsg()` call waits its default 3 seconds, then the test fails as the message I trigger after the scheduled tell is received never gets sent.

What I think is happening is that the actor that calls `ScheduleTellOnceCancelable` is doing so on a separate thread from the one being used for the test, which is why adding a delay to `ExpectMsg` greater than the delay used for the scheduled tell works. Any pointers on how to track this down?

**Comment by qwoz** [comment]
Some further information: I modified my trivial test (which now passes) to use a scheduled tell and I debug up to the point of the `ExpectMsg()` call, watching the "Threads" panel to see which threads are active. I compared that to debugging my real test up to the same point, also watching the "Threads" panel. One difference is that my real test shows `Akka.dll!Akka.Actor.DedicatedThreadScheduler..ctor.AnonymousMethod__0` as a worker thread, which my trivial test doesn't have.

**Comment by qwoz** [comment]
After digging into the `Akka.TestKit.NUnit` implementation and `TestKitBase`, I see that `TestKitBase` has its own `ActorSystem` implementation, so having my own custom `[SetupFixture]` and `[Setup]` to construct my ActorSystem is not going to fly.

I modifed this by initializing non-actor parts of my system within my custom `[SetupFixture]` and `[Setup]` code, then within each test I initialize the actor-related parts for the remainder of my system, passing in the `Sys` ActorSystem from TestKitBase. Everything now works as expected.

Thanks @Silv3rcircl3 and @rogeralsing for your time on this.
