### ISSUE TITLE
Port Akka.Cluster MultiNodeSpec: QuickRestartSpec

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2064]
https://github.com/akka/akka/blob/v2.4.7/akka-cluster/src/multi-jvm/scala/akka/cluster/QuickRestartSpec.scala

**Comment by Aaronontheweb** [comment]
Starting on this one

**Comment by Aaronontheweb** [comment]
Ah, this relates to one of the recent bug fixes that Patrik mentioned to me: https://github.com/akka/akka/issues/20523
