### ISSUE TITLE
Ask pattern and serialize all messages

### ISSUE THREAD

**Issue by jasmh** [akkadotnet/akka.net#2083]
Hi,

I enabled `serialize-messages = on` in HOCON and setup the custom serializer which is just a wrapper around wire serializer, so that I could console log and see what types are serialized/deserialized. I noticed that the ask response messages are not serialized/deserialized. After going through your source code, I figured out that the `Futures.Ask` method creates `FutureActorRef`,  which inherits from `MinimalActorRef`, which overrides the `TellInternal` method with empty code. On the other hand `LocalActorRef` overrides `TellInternal` with the `_cell.Post(sender, message)`, which in its body has the code that does the serialization depending on the `serialize-messages` configuration.

I was under impression that `serialize-messages = on` were supposed to be used in tests, so that correct serialization logic can be tested outside of the actual remoting/cluster system. I find its current mode especially problematic since one can currently only test the sending part of the serialization and not the receiving part when using the ask pattern. I guess I could implement my own ask pattern logic which accomplishes this, but was just trying to check if this was by design or it should be considered as a bug. I'd appreciate someone to elaborate further.

Thanks

**Comment by rogeralsing** [comment]
The temporary actors used in Ask are always on the same process/system as the asking actor/method.
Thus, serialization never need to occur in this case.

Serialization will however occur between the temporary actor and the "asked" actor.

Asked <-- serialization --> temp actor <----> Asking

**Comment by rogeralsing** [comment]
Tjat being said, the serialization part is handled by the remoting layer. So you are probably correct, if there is no remoting between the asked and the temp actor, no serialization will probably occur .
This needs to be verified

**Comment by Aaronontheweb** [comment]
@rogeralsing there's some code missing inside the `Tell` method on one of the `IActorRef` base classes that checks for this; noticed it while working on #2086 but I can't remember where exactly.

**Comment by jasmh** [comment]
It seems you fixed this. I'm not sure when, but I'm seeing the correct behavior in the version 1.4.0-beta4.

**Comment by Aaronontheweb** [comment]
@jasmh thanks - we did a lot of work around around getting `serialize-all-messages` to play nice. Been a lot of changes to that code over the course of 1.4.0 beta push.
