### ISSUE TITLE
It takes 20 seconds to create the ActorSystem

### ISSUE THREAD

**Issue by eightrivers** [akkadotnet/akka.net#2085]
The following is the config string of AKKA we used:

`akka {
stdout-loglevel = OFF
loglevel = OFF
log-config-on-start = on
  actor {provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"}
  remote {
    log-remote-lifecycle-events = ERROR
    helios.tcp {
	maximum-frame-size = 100000000b 
	hostname = "localhost"
	port = 9001}
  }
}`

The code we used to create ActorSystem is  

`_actorSystem = ActorSystem.Create(ClusterName, GetConfig());`

We started and stopped the process with AKKA several hundred times. In most of cases the ActorSystem could be created in 1 seconds, while we also noticed that occasionally, it will take about 20 seconds to created the ActorSystem object. 

Not sure what was happened internally, and how to avoid it.

**Comment by Aaronontheweb** [comment]
@eightrivers thanks for reporting this - do you have any logs to go along with it?

**Comment by eightrivers** [comment]
@Aaronontheweb Thanks for your quickly reply. By default the log of AKKA is turn off in our application. We can turn it on and submit the AKKA log soon.

**Comment by Aaronontheweb** [comment]
@eightrivers thanks! That would be helpful. I'm in the process of modifying the code that determines how all of the guardian actors allocate their children (which includes the remoting system, the loggers, and all of your user defined actors) and it might be the previous versions of that code which may be responsible for this slow startup, so anything that can help me pinpoint where the issue might be would be very helpful :+1:

**Comment by eightrivers** [comment]
@Aaronontheweb  The following is the AKKA log we extracted from the test environment. Please kindly take a look. 



`[DEBUG][2016/6/11 13:46:15][Thread 0009][EventStream] StandardOutLogger started
[DEBUG][2016/6/11 13:46:15][Thread 0009][EventStream(DefaultCluster)] Logger log
1-DefaultLogger [DefaultLogger] started
[DEBUG][2016/6/11 13:46:15][Thread 0009][EventStream(DefaultCluster)] StandardOu
tLogger being removed
[DEBUG][2016/6/11 13:46:15][Thread 0009][EventStream(DefaultCluster)] Logger log
1-DefaultLogger [DefaultLogger] started
[DEBUG][2016/6/11 13:46:15][Thread 0009][EventStream(DefaultCluster)] StandardOu
tLogger being removed
[DEBUG][2016/6/11 13:46:15][Thread 0009][EventStream(DefaultCluster)] Default Lo
ggers started
[INFO][2016/6/11 13:46:15][Thread 0009][remoting] Starting remoting
[DEBUG][2016/6/11 13:46:15][Thread 0022][remoting] Starting prune timer for endp
oint manager...
[INFO][2016/6/11 13:46:15][Thread 0009][remoting] Remoting started; listening on
 addresses : [akka.tcp://DefaultCluster@200.31.225.56:3001]
[INFO][2016/6/11 13:46:15][Thread 0009][Cluster] Cluster Node [akka.tcp://Defaul
tCluster@200.31.225.56:3001] - Starting up...
[ERROR][2016/6/11 13:46:35][Thread 0004][Cluster] Failed to startup Cluster. You
 can try to increase 'akka.actor.creation-timeout'.
Cause: System.Threading.Tasks.TaskCanceledException: 已取消一个任务。 // The Chinese in here means: One task has been canceled. 
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   在 Akka.Cluster.Cluster.<GetClusterCoreRef>d__10.MoveNext()
[INFO][2016/6/11 13:46:35][Thread 0004][Cluster] Cluster Node [akka.tcp://Defaul
tCluster@200.31.225.56:3001] - Shutting down...
[INFO][2016/6/11 13:46:35][Thread 0004][Cluster] Cluster Node [akka.tcp://Defaul
tCluster@200.31.225.56:3001] - Successfully shut down
[INFO][2016/6/11 13:46:35][Thread 0028][[akka://DefaultCluster/system/cluster/co
re/daemon]] No seed-nodes configured, manual cluster join required
[WARNING][2016/6/11 13:46:35][Thread 0009][ActorSystem(DefaultCluster)] NewtonSo
ftJsonSerializer has been detected as a default serializer. It will be obsoleted
 in Akka.NET starting from version 1.5 in the favor of Wire (for more info visit
: http://getakka.net/docs/Serialization#how-to-setup-wire-as-default-serializer
). If you want to suppress this message set HOCON `akka.suppress-json-serializer
-warning` config flag to on.
[WARNING][2016/6/11 13:46:35][Thread 0009][ActorSystem(DefaultCluster)] {
  akka : {
    stdout-loglevel : DEBUG
    loglevel : DEBUG
    log-config-on-start : on
    actor : {
      provider : "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"
    }
   remote : {
      log-remote-lifecycle-events : ERROR
      helios : {
        tcp : {
          maximum-frame-size : 100000000b
          hostname : 200.31.225.56
          port : 3001
        }
      }
    }
  }
}
[INFO][2016/6/11 13:46:35][Thread 0005][akka://DefaultCluster/deadLetters] Messa
ge Subscribe from akka://DefaultCluster/user/ActorName_Communication to akka://D
efaultCluster/deadLetters was not delivered. 1 dead letters encountered.
[INFO][2016/6/11 13:46:35][Thread 0034][akka://DefaultCluster/system/cluster/cor
e] Message DeathWatchNotification from akka://DefaultCluster/system/cluster/core
 to akka://DefaultCluster/system/cluster/core was not delivered. 2 dead letters
encountered.
[INFO][2016/6/11 13:46:35][Thread 0034][akka://DefaultCluster/system/cluster] Me
ssage DeathWatchNotification from akka://DefaultCluster/system/cluster to akka:/
/DefaultCluster/system/cluster was not delivered. 3 dead letters encountered.
[INFO][2016/6/11 13:46:35][Thread 0034][akka://DefaultCluster/system/cluster] Me
ssage DeathWatchNotification from akka://DefaultCluster/system/cluster to akka:/
/DefaultCluster/system/cluster was not delivered. 4 dead letters encountered.
[INFO][2016/6/11 13:46:35][Thread 0021][akka://DefaultCluster/system/cluster] Me
ssage DeathWatchNotification from akka://DefaultCluster/system/cluster to akka:/
/DefaultCluster/system/cluster was not delivered. 5 dead letters encountered.
[INFO][2016/6/11 13:46:35][Thread 0005][akka://DefaultCluster/system/cluster/cor
e] Message DeathWatchNotification from akka://DefaultCluster/system/cluster/core
 to akka://DefaultCluster/system/cluster/core was not delivered. 6 dead letters
encountered.`

The key info in the log is that : 

`[INFO][2016/6/11 13:46:15][Thread 0009][Cluster] Cluster Node [akka.tcp://Defaul
tCluster@200.31.225.56:3001] - Starting up...
[ERROR][2016/6/11 13:46:35][Thread 0004][Cluster] Failed to startup Cluster. You
 can try to increase 'akka.actor.creation-timeout'.`

We can noticed that it took about 20 seconds to try to start up the AKKA, but return with a error message. 

The version of AKKA we are using is 1.0.8, downloaded from nuget. This error will appear once in about 10-15 tests. And it has been verified that this issue is not related about the machine, the port or the instance of the process. Seems it appears randomly.

**Comment by Aaronontheweb** [comment]
```
[INFO][2016/6/11 13:46:15][Thread 0009][Cluster] Cluster Node [akka.tcp://Defaul tCluster@200.31.225.56:3001] - Starting up... [ERROR][2016/6/11 13:46:35][Thread 0004][Cluster] Failed to startup Cluster. You can try to increase 'akka.actor.creation-timeout'.
```

Aha! Thanks for sharing this. Yep, this was a known bug which we fixed in https://github.com/akkadotnet/akka.net/pull/1977

This fix will be released in Akka.NET 1.1, which we're running a bit behind on but not by much.

**Comment by eightrivers** [comment]
@Aaronontheweb Thanks for your kindly reply! 

So would you please kindly let us know the schedule of AKKA.Net 1.1? Will it be released in several weeks, or can we can a hot fix for this issue :)

**Comment by Aaronontheweb** [comment]
@eightrivers it was supposed to be released today but we're running a bit behind on it (1 week or so I think.)

In the meantime, you can use our nightly builds: http://getakka.net/docs/akka-developers/nightly-builds

**Comment by eightrivers** [comment]
@Aaronontheweb Nice to hear that the new version will be released soon ! I am eager to taste it :) 

Thanks for your kindly help again!

**Comment by eightrivers** [comment]
@Aaronontheweb BTW, is there the plan to update the version of Helios in AKKA.Net 1.1, since the Helios has also released some newest version recently to fix some hot issues?

**Comment by Danthar** [comment]
https://petabridge.com/blog/akkadotnet-2015-roadmap/
