### ISSUE TITLE
Cluster: Accept joining to be WeaklyUp during network split

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2100]
https://github.com/akka/akka/pull/18398

**Comment by Rattenkrieg** [comment]
This issue already has pending PR #2330 (which is not mentioning it) Have stumbled upon it when ported almost all code to my local branch :grimacing:
Also there is another one related akka/akka#20634

**Comment by Aaronontheweb** [comment]
This was finished a long time ago.
