### ISSUE TITLE
Using Different read/write models for Akka.persistence

### ISSUE THREAD

**Issue by SeanFarrow** [akkadotnet/akka.net#2114]
Hi,

What is the best way of using different read/write models for Akka.Persistence?
I'm migrating a legacy project that uses EventSourcing on the write side and elasticSearch on the read side.
Cheers
Sean.

**Comment by Silv3rcircl3** [comment]
http://doc.akka.io/docs/akka/current/scala/persistence-query.html  Is propably what you're looking for, a PR is waiting to be merged which add's these capabilities to the sql based persistence providers

**Comment by SeanFarrow** [comment]
Hi,
That looks good, so if I’m write I would need another actor to subscribe to this in my event sourced write model, and then transform a stream to the read model.
I suppose the other question arising from this is How would the PersistentRecieveActor know which (read/writ model) to use?
Cheers
Sean.

**Comment by Silv3rcircl3** [comment]
Haven't much knowledge about this module so I redirect this to @cconstantin and @Horusiath

**Comment by Silv3rcircl3** [comment]
@SeanFarrow maybe you have a better chance when you ask this question again in gitter :wink:

**Comment by alexvaluyskiy** [comment]
Akka.Persistence.Query has already released. You could try it
