### ISSUE TITLE
GracefulStop causes an unnecessary DeadLetter.

### ISSUE THREAD

**Issue by veblush** [akkadotnet/akka.net#2157]
The following code makes an unnecessary `DeadLetter` while executing `GracefulStop`.

```csharp
var greeter = system.ActorOf<GreetingActor>("greeter");
greeter.Tell(new Greet("World"));
greeter.GracefulStop(TimeSpan.FromSeconds(1)).Wait();
```

DeadLetter log is

```
[akka://MySystem/deadLetters]
Message DeadLetter from akka://S/user/greeter to akka://S/deadLetters was not delivered.
1 dead letters encountered.
```

This is caused because there is a difference between Akka and Akka.NET.

`GracefulStop` of [Akka](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/pattern/GracefulStopSupport.scala#L54)
sends `Unwatch` message only when the target actor is not terminated because it is not necessary.

But `GracefulStop` of [Akka.NET](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/GracefulStopSupport.cs#L63) always
sends `Unwatch` message even when the actor is terminated, which makes `DeadLetter` message.

**Comment by alexvaluyskiy** [comment]
@veblush could you make a PR with the fix and test for it?

**Comment by veblush** [comment]
@alexvaluyskiy what kinds of test do you mean? there seem to be three tests for `GracefulStop` in PatternSpec.cs.

**Comment by alexvaluyskiy** [comment]
yes, but none of them was failed before

**Comment by alexvaluyskiy** [comment]
Test - subscribe to deadletters and send a terminate request

**Comment by veblush** [comment]
@alexvaluyskiy ok, I got the point. it's a good idea.
