### ISSUE TITLE
Akka.Remote.HeliosTransport fails to bind on  IPV6; DNS under some circumstances

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2161]
Related to https://github.com/akkadotnet/akka.net/issues/1971

Based on some user reports from 1.1 we know we have some regressions that affected DNS binding.

Reproduction spec report thus far:

![image](https://cloud.githubusercontent.com/assets/326939/16705012/bfada6e0-4533-11e6-807f-b97709eee837.png)

**Comment by Aaronontheweb** [comment]
Verified that Helios 2.1.1 does the right thing with each of these settings: https://github.com/helios-io/helios/pull/113

**Comment by Aaronontheweb** [comment]
Found the culprit for at least some of the issues: we can't parse IPV6 addresses from an `ActorPath` properly... 

See https://tools.ietf.org/search/rfc1924 and https://tools.ietf.org/html/rfc5952

JVM has struggled with this also: https://github.com/akka/akka/issues/17911

**Comment by Aaronontheweb** [comment]
I have this bug fixed in #2162 but I need to clean up some of the XUnit 2.1 upgrade aftermath in there.

**Comment by Aaronontheweb** [comment]
Not quite done yet; have some DNS resolution issues that are still in progress.

**Comment by kantora** [comment]
Sorry for disturbing.
After recent update to latest Akka night build and latest Helios, I cant't make Akka cluster to work back. It looks like that problem is related with this issue, but I am not sure.
I am using docker and mono with several containers as a sandbox. One service is a seed and other worker nodes.

After start, worker nodes doesn't show any errors, but they don't have a cluster welcome message either.
However, on the seed node I receive this error:
```
[36mseed_1 | [0m2016-07-14 16:02:48 [Error] Error caught channel ["::ffff:172.18.0.5:3090"->"::ffff:172.18.0.2:50152"] (Id="ChannelId(-1914377680)")
[36mseed_1 | [0mSystem.Net.Sockets.SocketException: Operation aborted
[36mseed_1 | [0m  at Helios.Channels.Sockets.SocketChannelAsyncOperation.Validate () <0x42187b20 + 0x00057> in <filename unknown>:0
[36mseed_1 | [0m  at Helios.Channels.Sockets.AbstractSocketByteChannel+SocketByteChannelUnsafe.FinishRead (Helios.Channels.Sockets.SocketChannelAsyncOperation operation) <0x421926a0 + 0x0013b> in <filename unknown>:0
[36mseed_1 | [0m2016-07-14 16:02:48 [Information] "Message Disassociated from NoSender to akka://ClusterKit/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FClusterKit%40%5B%3A%3Affff%3A172.18.0.2%5D%3A50152-3 was notdelivered. 3 dead letters encountered."
```
`172.18.0.5` is ip address of the seed and `172.18.0.2` is an address of worker node, but both of them configured to use fixed port `3090` and string public host names.

**Comment by Aaronontheweb** [comment]
> both of them configured to use fixed port 3090 and string public host names.

Yeah, this is currently broken due to the system using IPV6 for DNS resolution. I'm publishing a fix to Helios that I'm going to bring into Akka.Remote shortly to patch this issue to make the IP version configurable, and have it default back to IPV4 so no one else's app breaks upon upgrade.

**Comment by Aaronontheweb** [comment]
But thanks for verifying it for me @kantora - I have a spec that shows this failing too.

**Comment by kantora** [comment]
Updated to the latest Akka.Net night build (1.1.1.248-beta) and Helios 2.1.2.
Still can't make the cluster work. This time, the errors above happens not every time, but sometimes. Remote nodes can't join (self-join is ok).

**Comment by kantora** [comment]
Ehm... Suppose it is another bug... related to linux/mono environment...
DNS is working well, but addressing is not.
`::ffff:172.18.0.2` - this is not the same as `172.18.0.2` so connection cannot be made
```
root@52e368960bf4:/opt/clusterkit# ping 172.18.0.2
PING 172.18.0.2 (172.18.0.2) 56(84) bytes of data.
64 bytes from 172.18.0.2: icmp_seq=1 ttl=64 time=0.060 ms
64 bytes from 172.18.0.2: icmp_seq=2 ttl=64 time=0.086 ms
64 bytes from 172.18.0.2: icmp_seq=3 ttl=64 time=0.049 ms
64 bytes from 172.18.0.2: icmp_seq=4 ttl=64 time=0.106 ms
^C
--- 172.18.0.2 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 2997ms
rtt min/avg/max/mdev = 0.049/0.075/0.106/0.023 ms
root@52e368960bf4:/opt/clusterkit# ping6 ::ffff:172.18.0.2
PING ::ffff:172.18.0.2(::ffff:172.18.0.2) 56 data bytes
ping: sendmsg: Network is unreachable
ping: sendmsg: Network is unreachable
ping: sendmsg: Network is unreachable

```

**Comment by kantora** [comment]
I'll create a separate issue for this
