### ISSUE TITLE
PoisonPill and IActorRef.Stop() - possibility to pass a terminate value

### ISSUE THREAD

**Issue by baio** [akkadotnet/akka.net#2166]
Sometimes it is useful to have possibility pass some values to watchers after actor terminated.

**Comment by Aaronontheweb** [comment]
@baio you can pass a value *just before* an actor finishes terminating, inside the `PostStop` method on the actor. We will not be modifying those system messages to do this, but I'd recommend using that approach.

**Comment by baio** [comment]
Thank @Aaronontheweb 
How could pass value to watcher in this case?
How could I find watchers which are subscribed to this actor ?
