### ISSUE TITLE
HOCON beautifier

### ISSUE THREAD

**Issue by nomailme** [akkadotnet/akka.net#2174]
Hi!

I've just dived into akka.net and actor model in general. Everything goes fine until I have to edit HOCON in app.config. I am always missing braces and can't understand what is where. 

So my question is how do you format HOCON config file?  Are there any plugins for any free text editor that can help me?

Thanks,
Iskander

**Comment by kantora** [comment]
I am using sublime text and a plugin in it. Also I moved hocon out of app.config and apply it separately.

**Comment by jpierson** [comment]
I've found [this extension for VSCode](https://forums.spongepowered.org/t/hocon-syntax-highlighting-plugin-for-vscode/7041) but it doesn't appear to be available in the gallery and I haven't tried it myself.

**Comment by sean-gilliam** [comment]
This issue probably should be directed to our HOCON repo. 

https://github.com/akkadotnet/HOCON
