### ISSUE TITLE
Gitter channels for working groups

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#2175]
I think it's a good idea to move some of the parts we're working on right now into separate channels on Gitter. Reason for that is better communication and cooperation between people willing to work on specific fragments of akka runtime. We already done so with Akka.Streams and it worked great.

Proposed channels:
- akka.io - ( @Silv3rcircl3 , @Lewis-H )
- .net core - ( @alexvaluyskiy , @annymsMthd , @Aaronontheweb )
- ddata (aka. Akka.DistributedData) - ( @maxim-s )

Some other propositions?

**Comment by alexvaluyskiy** [comment]
I need a gitter channel for NetCore.
And I need your help in NetCore for FSharp projects.

**Comment by alexvaluyskiy** [comment]
And we could create just one gitter room for all clustering stuff (Cluster/Tools/Sharding/Ddata)
