### ISSUE TITLE
Sqlite journal persistence auto initialize failure due to invalid config is not captured

### ISSUE THREAD

**Issue by sillyotter** [akkadotnet/akka.net#2181]
I recently stumbled across a problem with the sqlite persistence module and submitted a PR (#2180) to deal with the core issue.  While investigating it though, I ran into some other related issues that I'm unsure of the need to fix, and also unsure of the how to fix, but I thought I'd capture them here.  

The core of the PR mentioned above is that the SQLite persistence modules were looking for a database table name in the variable meta-table-name, whereas the defaults and the core persistence modules were looking for the table name in the variable metadata-table-name.  I was not setting meta-table-name in my config file, and that broke things.  While the PR fixes that so that the defaults work again, there is a different related issue.

In the pre PR world, or post PR, if you were to set metadata-table-name to an empty string, and you set the auto-initialize variable to on, you will get a partially created database, with no metadata-table created, but no errors are generated or displayed for the user, regardless of logging levels.  Your app will appear to be working, but any persistent actors you have created will never get any messages delivered to them.

If you have auto-initialize set to off, then when the sqlite module tries to use this half way defined database structure from the auto initialize step you will get an appropriate, though somewhat cryptic, sql exception.  At least you know something is going wrong though.  But in the case where you have auto-initialize set to true, it will hide the exceptions and simply prevent your actor from being used.

I have no idea how that is happening, just that it is.  https://github.com/sillyotter/AkkaTest2 is a project that shows the issue if you run it against the current nuget versions of persistence.  That versions server (akkatest2 project) does not set meta-table-name to journal-metadata, and it has auto-initializie set to on. Run it with some break points set in the various persistent actors command callbacks. (StatefulActor, in the shared library).  They never get called. It doesn't complain any, just refuses to work correctly. 

With the above mentioned PR, you are not likely to get the error unless you forcibly set the metadata-table-name variable to something invalid like an empty string and auto-initialize = on.  But it is still possible.

**Comment by alexvaluyskiy** [comment]
@sillyotter thank you
