### ISSUE TITLE
Streams: Performance Flow.flatMapMerge

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2185]
To implement this PR from Akka 2.4.3
https://github.com/akka/akka/pull/19701

I'm waiting for these changes, because I need them for netcore work

**Comment by Silv3rcircl3** [comment]
Fixed in https://github.com/alexvaluyskiy/akka.net/pull/1

**Comment by alexvaluyskiy** [comment]
@Silv3rcircl3 Why have you done it in netcore branch? We should merge these changes into dev branch.

**Comment by Silv3rcircl3** [comment]
@alexvaluyskiy ah right, will created another one .
