### ISSUE TITLE
HOCON can't parse IPV6 addresses

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2187]
HOCON barfs and fails to start Akka.Remote if I use `[::1]` as a hostname for IPV6. Didn't capture any more details than that during my brief foray into it but I wanted to log the bug.

**Comment by rogeralsing** [comment]
According to specification, unquoted strings may not start with `:`
List of illegal chars `"{}[]:=,#`^?!@*&\`

I don't know why this is, maybe we should call in one of the JVM devs(?)

**Comment by Aaronontheweb** [comment]
@rogeralsing ah, maybe that's it - just need to quote IPV6 addresses?

**Comment by rogeralsing** [comment]
Yes

**Comment by Aaronontheweb** [comment]
if that's the case then we can mark this as resolved then. PEBKAC
