### ISSUE TITLE
i get this exception， when i use ‘for’ loop to create actors

### ISSUE THREAD

**Issue by TopSpoofer** [akkadotnet/akka.net#2212]
in Akka.Actor.Internal.NormalChildrenContainer.Reserve(String name)
in Akka.Actor.ActorCell.<>c__DisplayClass178_0.<ReserveChild>b__0(IChildrenContainer c)
in  Akka.Util.Internal.InterlockedSpin.Swap[T](T& reference, Func`2 updater)
in Akka.Actor.ActorCell.ReserveChild(String name)
in Akka.Actor.ActorCell.MakeChild(Props props, String name, Boolean async, Boolean systemService)
  in Akka.Actor.ActorCell.ActorOf(Props props, String name, Boolean isAsync, Boolean isSystemService)
in Akka.Actor.ActorCell.ActorOf(Props props, String name)

**Comment by Danthar** [comment]
It looks like you are attempting to create actors with the same name? When posting these kind of questions, always make sure to at least include the snippet of code your using that triggers the error. 

Because unfortunately, we don't have a crystal ball.

**Comment by TopSpoofer** [comment]
@Danthar  yes, After I make the Actor name diff, I haven't get this err  . thank !
