### ISSUE TITLE
Update Json.NET to version 9.0.1

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2223]
We are using some features from C#6 in our sources (like auto properties), but Json.Net 7.0.1 doesn't support it.

**Comment by maxim-s** [comment]
is it up for grabs or is it in progress?

**Comment by alexvaluyskiy** [comment]
Up for grabs

**Comment by alexpantyukhin** [comment]
@alexvaluyskiy Sorry. I didn't saw your PR for this task. It seems that you forgot to update the reference in Akka.Tests. I did it manually in my PR and it seems to be working now.

**Comment by maxim-s** [comment]
#2237  merged
