### ISSUE TITLE
akka.net for Xamarin.Forms

### ISSUE THREAD

**Issue by JimSEOW** [akkadotnet/akka.net#2224]
Has anyone tried to compile using the akka.net's NetCore brunch?

**Comment by Danthar** [comment]
Nope. the NetCore branch is still very much in development. But you are welcome to try.

**Comment by JimSEOW** [comment]
The other option is to bring it native (e.g. Xamarin.Forms.Platform.UWP)  while waiting for the NetCore brunch to be more mature.

**Comment by Silv3rcircl3** [comment]
Please use the Gitter room if you have further questions in that area.
