### ISSUE TITLE
Wrong versioning for FsPickler in Akka.FSharp Nuget package configuration file

### ISSUE THREAD

**Issue by mariosangiorgio** [akkadotnet/akka.net#2227]
The [Nuget package configuration](https://github.com/akkadotnet/akka.net/blob/fe69c8408fa5a49de4871262746d77a08e73fd2f/src/core/Akka.FSharp/packages.config#L3) file specifies
`<package id="FsPickler" version="1.2.21" targetFramework="net45" />`, which according to the [Nuget documentation](https://docs.nuget.org/create/versioning) means any version greater or equal to `1.2.21`.

In a project I'm working on Packet resolved that version to `3.0.0`, which causes the following exception:
`System.TypeLoadException: Could not load type 'Akka.FSharp.Serialization+ExprSerializer' from assembly 'Akka.FSharp, Version=1.1.1.27, Culture=neutral, PublicKeyToken=null'.`

**Comment by lambdakris** [comment]
I think I experienced a related problem. I kept getting the exception
`Could not load type 'Nessos.FsPickler.BinarySerializer' from assembly 'FsPickler, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.`

I resolved by pinning the FsPickler version to 2.4.0 in my paket.dependencies file

**Comment by kunjee17** [comment]
@lambdakris Face the same issue. Pinning up version worked. thanks man.

**Comment by sean-gilliam** [comment]
See #2306
