### ISSUE TITLE
Run cluster with F# problem

### ISSUE THREAD

**Issue by baio** [akkadotnet/akka.net#2228]
Hi, I have a problem with creating cluster with F#, basically it is running
```
Akka.Cluster.ClusterCoreDaemon: Node [akka.tcp://globomantics@127.0.0.1:4053] is JOINING, roles [lighthouse]
Akka.Cluster.ClusterCoreDaemon: Leader is moving node [akka.tcp://globomantics@127.0.0.1:4053] to [Up]
Akka.Cluster.ClusterCoreDaemon: Node [akka.tcp://globomantics@127.0.0.1:56585] is JOINING, roles [server]
Akka.Cluster.ClusterCoreDaemon: Node [akka.tcp://globomantics@127.0.0.1:56576] is JOINING, roles [api]
```

but then I encounter following messages

```
[INFO][8/2/2016 10:53:41 AM][Thread 0018][[akka://globomantics/system/cluster/core/daemon#1931584917]] Welcome from [akka.tcp://globomantics@127.0.0.1:4053]
[INFO][8/2/2016 10:53:43 AM][Thread 0018][akka://globomantics/user/ReaderActor] Message JObject from akka://globomantics/deadLetters to akka://globomantics/user/ReaderActor was not delivered. 1 dead letters encountered.
[INFO][8/2/2016 10:53:45 AM][Thread 0007][akka://globomantics/user/ReaderActor] Message JObject from akka://globomantics/deadLetters to akka://globomantics/user/ReaderActor was not delivered. 2 dead letters encountered.
```

Couldn't find any clue why this happening, if you could please check my repo

https://github.com/baio/akka-fs-cluster

Also I want to add what there is lack of good F# example how to create clusters.

Thanks.

**Comment by Horusiath** [comment]
This is a serialization issue of F# data types (usually Discriminated Unions) using current default serializer. You may want to change it to Wire. [Here](http://getakka.net/docs/Serialization#how-to-setup-wire-as-default-serializer) is the quick description, how to do it.

**Comment by baio** [comment]
Using Wire protcol, gives the same error
Here is the branch
https://github.com/baio/akka-fs-cluster/tree/wire

Also updating Wire package to latest version throw this exception when trying load config 
`System.create "globomantics" (Configuration.load())`
```
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll

Additional information: Exception has been thrown by the target of an invocation.
```

**Comment by Horusiath** [comment]
@baio  I've run your example, and besides broken config for router it works fine.

**Comment by baio** [comment]
For wire branch ?
Could you please say where router config is broken ???

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="akka"
             type="Akka.Configuration.Hocon.AkkaConfigurationSection, Akka" />
  </configSections>  
  <startup> 
      <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
  <akka>    
    <hocon>
      <![CDATA[
          akka {
            log-config-on-start = off
            stdout-loglevel = INFO
            loglevel = INFO                        
            
            actor {
            
              serializers {
                wire = "Akka.Serialization.WireSerializer, Akka.Serialization.Wire"
              }
              serialization-bindings {
                "System.Object" = wire
              }            
              
              provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"
              
              deployment {          
                /ReaderActor {
                  router = round-robin-group
                  nr-of-instances = 1
                  routees.paths = ["/user/ReaderActor"]
                  cluster {
                    enabled = on
                    max-nr-of-instances-per-node=1
                    allow-local-routees = off
                    use-role = api
                  }
                }
              }  
              
            }
            remote {
               helios.tcp {
                  hostname = "127.0.0.1"
                  port = 0                  
               }
            }
            
            cluster {
              seed-nodes = ["akka.tcp://globomantics@127.0.0.1:4053"]
              roles = [server]
            }
       }
      ]]>
    </hocon>
  </akka>  
</configuration>
```

**Comment by Horusiath** [comment]
First. Your router config specifies *round-robin-group* - that means, router won't create routee actors by itself, instead it will join existing ones. However, you haven's created any concrete `ReaderActor` (only router for it). If you want your router to manage its actors and create them on demand - use *round-robin-pool* instead.

Second. You defined your routees to be limited to cluster nodes having *api* role. This means that:
    - *api* nodes are supposed to host your `ReaderActor` routees
    - *server* nodes will host your `WriterActor` and router
What's problematic here is that `ReaderActor` logic tries to reach `WriterActor` using its relative/local path. This way writer will never be reached by readers, as they live on the different nodes.

**Comment by baio** [comment]
Working now, thanks

https://github.com/baio/akka-fs-cluster/tree/wire.1
