### ISSUE TITLE
Persistence AsyncWriteJournal is not realy async

### ISSUE THREAD

**Issue by kantora** [akkadotnet/akka.net#2247]
I've encountered the very strange issue while executing the performance tests in my application.
I am using ClusterSharding and PersistentFSM for main actors, that represent business entities. For the storage, I use `Akka.Persistence.Redis` plugin (that is expected to be fast). Also, I configured `TaskDispather` as default one.

Unfortunately, performance was much lower than I expected. Investigation showed that every actor in the system had empty message queue except for `/system/akka.persistence.journal.redis` with more than hundred messages (I am still working, but as for now, entity actors spawn rather large amount events to persist). Every time I measured it was always `WriteMessages` in the process. 

That is strange, as it seems to me from code that `AsyncWriteJournal.HandleWriteMessages` should spawn async task and proceed to other messages. So it should be fast.

I used `dotTrace` to look at it a little bit closer. 
![2016-08-10 11 29 00](https://cloud.githubusercontent.com/assets/1901708/17547081/da99688a-5eed-11e6-8f4a-018af9c75724.png)

Now I am sure that everything is processed in the strictly single thread, So all my multithreaded application is depended on it as all actors are waiting their queue to persist.

**Comment by kantora** [comment]
Or I misunderstood something and this is the expected behaviour?

**Comment by alexvaluyskiy** [comment]
I've found this issue
https://github.com/akkadotnet/Akka.Persistence.Redis/blob/c9713ce0a42ea1e75555d7343ebfbc7a7a694321/src/Akka.Persistence.Redis/Journal/RedisJournal.cs#L79

Could you create the same issue in the Redis repo? It will be fixed in the next version of Redis plugin

**Comment by alexvaluyskiy** [comment]
@kantora It would be fixed in the next version of Redis plugin. But this version could be incompatible with 0.1.0 (snapshots)

**Comment by kantora** [comment]
@alexvaluyskiy are you sure that this is the Redis plugin issue? I suppose that even if `WriteMessagesAsync` is completely sync itself, nevertheless it should be called in a separate task/thread from `HandleWriteMessages`.

**Comment by kantora** [comment]
I cloned this issue to the Redis plugin repo.
https://github.com/akkadotnet/Akka.Persistence.Redis/issues/9

**Comment by kantora** [comment]
Suppose, at the end,  it was local Akka.Persistence.Redis problem and it is fixed now.

**Comment by Horusiath** [comment]
Closing this now. The issue resolution can be tracked on redis repo.
