### ISSUE TITLE
Write performance tests (NBench) for Akka.Persistence

### ISSUE THREAD

**Issue by cconstantin** [akkadotnet/akka.net#2249]

**Comment by alexvaluyskiy** [comment]
JVM version has perf test in their testkit
https://github.com/akka/akka/blob/master/akka-persistence-tck/src/main/scala/akka/persistence/journal/JournalPerfSpec.scala

**Comment by alexvaluyskiy** [comment]
JournalPerfSpec was implemented in Akka.Persistence.TCK
