### ISSUE TITLE
Update to match akka persistence jvm 2.4.8

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2252]
Too implement these pull requests
- [x] https://github.com/akka/akka/pull/20702 (on recovery timeout for persistent actors)
- [x] https://github.com/akka/akka/pull/20115 (InvalidActorNameException in EventAdapterSpec)
- [x] https://github.com/akka/akka/pull/20097 (avoid NPE in recoveryRunning)
- [x] https://github.com/akka/akka/pull/19850 (pop the internal stash when the writing was finished in the processing commands state)
- [x] https://github.com/akka/akka/pull/20266 ([PersistentFSM] getting StateTimeout for state witout timeout after restart)
- [x] https://github.com/akka/akka/pull/20753 (Better recovery timeout for persistent actors)
- [x] https://github.com/akka/akka/pull/20303 (make sure ReplayFilter works OK if no previous writer ID was seen)

**Comment by Horusiath** [comment]
Updated first comment to get task list integrated with github.

**Comment by alexvaluyskiy** [comment]
Closed via https://github.com/akkadotnet/akka.net/pull/2245
