### ISSUE TITLE
Problem with replaying events by tag

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#2257]
I've noticed a problem with offsetting in replay events by tag in current SQL implementation: the problem  lies in the fact, that events are replayed in batches, not all at once. More over, the windowing is implemented in form of an offset. So replaying events **theoretically** looks like this:

```
Event stream: |p1:0-----------------------------p-1:n>|
 EventsByTag: |----------|--------------|-------------| 
              offset:0   offset:100     offset:200
```

However this is false. In **practice** there we have multiple event streams (event stream: a collection of events/rows, which belong to a single PersistenceId), that we query at once. In current SQL implementation, we simply put them in line by ordering by PersistenceId and then by SequenceNr.

```
Event stream 1: |p1:0------>|
Event stream 2: |           |p2:0----->|
Event stream 3: |           |          |p3:0---------->|
    Result set: |--------------------------------------|
   EventsByTag: |--------------|-----------|-----------|
                offset:0       offset:100  offset:200
```

In this case, if we try to apply offset to successive queries, we can miss some of the events, while others will be replayed more than once - this will happen because some of the persistent actors may persist events in between two database calls, causing the previous offset to be not longer valid.
#### 1. Special event stream for tags

My initial implementation of tagging was actually solving this issue:

Instead of having `tags` column to query on, we implement each particular tag as a separate persistence id (we can use some prefix to distinguish them from user-defined persistence ids). We will need some other way to identify event rows however (let's say, we have auto-incremented ID column). Once  persist event request with tags attached comes in, we store as a row in the database, get its ID and store another row in the same table, where the Payload column is a an ID of that row, and PersistenceId is a tag name.

Pros:
- No need to introduce additional tables.

Cons: 
- The logic used to store event ID as a payload can get complicated. We either do that as a 2 database calls (one to retrieve event ids from event stream related with target tag, second to retrieve those events), or try to do it in a single recursive SQL query - even harder to make right.
- SQL migration script will be complex. 
#### 2. Separate tags table

Second option is to create a separate Tags table. It could look like this:

``` sql
CREATE TABLE EventTags (
    Tag NVARCHAR(100) NOT NULL,
    Offset BIGINT NOT NULL,
    EventPersistenceId NVARCHAR(200) NOT NULL,
    EventSequenceNr BIGINT NOT NULL,
    CONSTRAINT PK_TagOffset PRIMARY KEY (Tag, Offset),
    FOREIGN KEY FK_EventJournal(EventPersistenceId, EventSequenceNr) 
    REFERENCES EventJournal(PersistenceId, SequenceNr)
)
```

Then we could fetch all tag events in a simple query with join between Tags and EventJournal column.

Pros:
- We keep tag- and event-data in separate tables.
- Probably easier to implement.

Cons:
- Another (4th) table required by Akka.Persistence.
- We need to increment EventTags.Offset column, but only in scope of a current Tag. This must be done on the database level.

Personally I'd go for second - it's less magic, and allows user to execute SQL queries with tags by himself/herself.

**Comment by alexvaluyskiy** [comment]
Which way has been chosen here?
https://github.com/dnvriend/akka-persistence-jdbc

**Comment by Horusiath** [comment]
@alexvaluyskiy looks like they have our current ;) (using LIKE on tags column).

**Comment by Horusiath** [comment]
I think that the jdbc version treat an offset a little bit differently than I've expected - I was assuming, that offset blocks are expected to be continuous. This means, when you are requesting (offset=0, max=N) you'll get a block of `EventEnvelope`s with offsets 1-N, so the next time you can simply call (offset=N, max=N), (offset=N*2, max=N)... and so on. This doesn't seem to be the case.

What we have here is that after calling (offset=0, max=N), before we can send the next request, we first must to wait for the current stream to complete and store the last offset number (because it can be bigger than N), so we'll know where to start from with the next request &rArr; (offest=lastEventEnvelopeOffset, max=N).

This would require to keep track on incoming event offsets - irritating from user point of view. What I could propose in this case is:

- Add auto_incremented Offset column to all SQL implementations and use it for ordering.
- Change materialized value type returned from persistent query to something like `QueryMetadata(eventsRead: long, lastOffset: long)`.

Any comments on that?

**Comment by cconstantin** [comment]
@Horusiath the Cassandra plugin uses a timestamp column (which is a time guid) as the offset. HTH
