### ISSUE TITLE
Couldn't build an actor materializer settings. `akka.stream.materializer` config path is not defined.

### ISSUE THREAD

**Issue by mikhailshilkov** [akkadotnet/akka.net#2263]
```
Couldn't build an actor materializer settings. `akka.stream.materializer` config path is not defined.
   at Akka.Streams.ActorMaterializerSettings.Create(ActorSystem system)
   at RxStreams\Program.cs:line 27
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
```

is thrown when the following code is executed with default config (no HOCON):

``` cs
using (var sys = Akka.Actor.ActorSystem.Create("TestSystem"))
{
    var settings = ActorMaterializerSettings.Create(sys); // fails
}
```

`Materializer` factory copes with this by injecting the default configuration
``` cs
system.Settings.InjectTopLevelFallback(DefaultConfig());
```

I guess `ActorMaterializerSettings` needs a default fallback too.

**Comment by Horusiath** [comment]
Have you tried to create materializer via `system.Materializer()`?

**Comment by mikhailshilkov** [comment]
Yes, it works, but I need a materializer with custom settings.
Settings creation also works if I prepend the following line:
``` cs
system.Settings.InjectTopLevelFallback(Akka.Configuration.ConfigurationFactory.FromResource<ActorMaterializer>("Akka.Streams.reference.conf"));
```

**Comment by Horusiath** [comment]
How are you trying to create custom settings? If you specify them through constructor, it won't throw an error. If you'll specify them under `akka.stream.materializer` HOCON section, they should also be applied without error - also there's no need to create `ActorMaterializerSettings` in the second case.

**Comment by mikhailshilkov** [comment]
I gave an example in my first message. Here is my current code:
``` cs
using (var system = Akka.Actor.ActorSystem.Create("ServiceBusSystem"))
{
    Decider decider = cause => Directive.Resume;
    system.Settings.InjectTopLevelFallback(Akka.Configuration.ConfigurationFactory.FromResource<ActorMaterializer>("Akka.Streams.reference.conf"));
    var settings = ActorMaterializerSettings.Create(system).WithSupervisionStrategy(decider);
    using (var mat = system.Materializer(settings)) ...
```

It doesn't work without `InjectTopLevelFallback` line.

**Comment by Horusiath** [comment]
Concerning the issue: what should be fixed here is providing default values to `ActorMaterializerSettings.Create(Config)` method - right now it will throw if the config value was not provided in the HOCON config. There is override over `config.GetInt`, `config.GetString` etc. methods, where a default value can be provided in the case when config hasn't provided one. It could be used to fix this issue.

PS: you don't need to use `ConfigurationFactory.FromResource` - you may use `ActorMaterializer.DefaultConfig` instead.
