### ISSUE TITLE
Occasional KeyNotFoundException when publishing to Akka.NET Distributed Pub/Sub

### ISSUE THREAD

**Issue by jpierson** [akkadotnet/akka.net#2268]
I'm using Akka.Cluster 1.1.1 and Akka.Cluster.Tools 1.0.6 and I'm noticing that I get KeyNotFoundException cases when publishing to the mediator. Looking at the code for [DistributedPubSubMediator](https://github.com/akkadotnet/akka.net/blob/31d11ec1fcfdc19c33b99135d778d932ddcaf526/src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs#L499) it looks like this should be impossible unless there is a bug in the implementation of ImmutableDictionary.ContainsKey or some other type of compiler/CLR issue as @Horusiath suggested.

Gitter conversation: https://gitter.im/akkadotnet/akka.net?at=57befcc87c2d386059a1e768

StackOverflow post: [What is causing occasional KeyNotFoundException in Akka.NET Distributed Pub/Sub](http://stackoverflow.com/questions/39147588/what-is-causing-occasional-keynotfoundexception-in-akka-net-distributed-pub-sub)

**Comment by jpierson** [comment]
Ah, it looks like the [DistributedPubSubMediator code in 1.0.6](https://github.com/akkadotnet/akka.net/blob/v1.0.6/src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs#L440) didn't have this check. Since there is no more recent stable release of Akka.Cluster.Tools 1.0 that has this fix is there any chance a patch release could be made or is Akka.Cluster.Tools 1.1 stable release right around the corner?

**Comment by jpierson** [comment]
Looking into the original bug fix for this issue, it appears was originally made by @alexvaluyskiy in https://github.com/akkadotnet/akka.net/commit/b8f025ba15eb0ce5bbea8c77680402b3c8944fcd#diff-cb8a9e2b098344b9fba5e384b7c7baadL444.

**Comment by jpierson** [comment]
I verified that in my case after updating to _Akka.Cluster.Tools 1.1.1.28-beta_ I no longer see this issue.

**Comment by Danthar** [comment]
There is talk about doing a maintenance release sometime soon. But im not sure when. @Aaronontheweb  ?

**Comment by Silv3rcircl3** [comment]
Fix was released with 1.1.2
