### ISSUE TITLE
Config.GetStringList : Collection was not of fixed size

### ISSUE THREAD

**Issue by mmisztal1980** [akkadotnet/akka.net#2274]
# Description
When reading a configuration containing an empty list of seed nodes using ```Config.GetStringList``` I was trying to inject an item into the list and got a 

>Collection was not of fixed size

# Expected
```Config.GetStringList``` 's signature and name imply that an ```IList<string>``` is returned, which is true, however in this case an empty array was returned, preventing me from adding any additional items to the list. I don't believe it should be that way - this prevents users from injecting items to the configuration in a way which is done in Lighthouse (for example).

I'll be making a PR regarding this today.

**Comment by Danthar** [comment]
PR was merged
