### ISSUE TITLE
Add the capability to add command to ShardRegion

### ISSUE THREAD

**Issue by SeanFarrow** [akkadotnet/akka.net#2276]
Given that in some cases ShardRegion could be used to manage aggregate and aggregate root-style actors in ddd, it would be nice to be able to add commands directly to ShardRegion. I'm thinking specifically where I want to use querying commands, such as give me all entities that have a property above a certain value.
Given that ShardRegion's creation is closed, this seems hard to do. Perhaps we could have a virtual method AddCommands that would provide this facility.
I'm happy to do this, if the interest is there.
Cheers
Sean.

**Comment by Danthar** [comment]
ClusterSharding is meant to transparently distribute actors across your cluster. Im don't think this is conceptually the right place to add these kind of features.

You want to query the state of your system. I'd explicitly design your actors system to be able to handle that request, regardless of how your actors are distributed or deployed. 

Distributed PubSub sounds like a way you could implement this. But using dedicated projections is also an option.

**Comment by Horusiath** [comment]
@SeanFarrow I don't see, how adding commands to `ShardRegion` is going to help you to filter entities by their property. Each actor's state is isolated and cannot be accessed by other actors in any other way than message passing. So shard region won't be able to filter those actors better than any other actor. 

A lot better option would be to have a separate (Single Responsibility Principle) actor responsible for grouping actors by certain rules and able to response for queries. Then simply have notify it by publish\subscribe pattern - either directly, by using distributed pub/sub or by using EventBus.
