### ISSUE TITLE
Cluster.LeaveAsync() 

### ISSUE THREAD

**Issue by kostrse** [akkadotnet/akka.net#2280]
Currently, to leave cluster before termination one needs to subscribe to `RegisterOnMemberRemoved`, do `Leave(cluster.SelfAddress)` and wait for member removal event.

This pattern is very easy to implement wrong. There are also edge cases when event doesn't guarantee arrive (member is in Joining state etc.), thus very easy to hang the process.

Situation becomes more complicated with support of CancellationToken etc.

I'd want to propose to add a convenience method `Task LeaveAsync()` into the Cluster.

The example code could look like this:

``` c#
// with or without cancellation token
await Cluster.Get(_actorSystem).LeaveAsync(cancellationToken);
await _actorSystem.Terminate();
```

Naive implementation as extension method, just for reference:

``` c#
public static Task LeaveAsync(this Cluster cluster)
{
    var tcs = new TaskCompletionSource<bool>();

    cluster.RegisterOnMemberRemoved(() => { tcs.TrySetResult(true); });
    cluster.Leave(cluster.SelfAddress);

    return tcs.Task;
}
```

**Comment by Horusiath** [comment]
Actually, leaving the cluster gracefully should be done automatically as part of `await _actorSystem.Terminate()`. That doesn't change the fact that `Cluster.LeaveAsync` method would be valuable addition, as it may be used for graceful leaving i.e. from control actors, without being followed by shutdown of the whole actor system.

**Comment by kostrse** [comment]
For auto leaving on termination we could have a configuration flag like this:

``` hocon
akka {
    cluster {
        leave-on-termination = on
    }
}
```

**Comment by Aaronontheweb** [comment]
@kostrse @Horusiath I really like both of these ideas. This will solve a major usability problem. For now I'd propose having "leave-on-termination" off by default (never ambush a user with a sudden change in default behavior) but introduce it in a new revision release now to get people to start using it. Possibly make it the default later in a major/minor version release.

**Comment by ayoung** [comment]
@Horusiath I have found that `_actorSystem.Terminate().Wait()` does leave on termination. Can you confirm?

**Comment by Aaronontheweb** [comment]
@ayoung currently it does not; leaving the cluster gracefully requires two rounds of communication first.

**Comment by ayoung** [comment]
@Aaronontheweb So for now, `.Leave()` and then `.Terminate()` is the recommended approach?

**Comment by Aaronontheweb** [comment]
@ayoung `LeaveAsync` now available per the nightlies
