### ISSUE TITLE
Question around clustering

### ISSUE THREAD

**Issue by oliviervaillancourt** [akkadotnet/akka.net#2283]
Hi guys,

We are new to Akka.Net (and Akka for that matter).  We have a setup where users can upload CSV data into and https endpoint.  From there that data must make it's way to proprietary storage.  That storage has an interface which requires a TCP connection to stay open per customer store.  All of this is in the cloud of course.

Our goal was to have Akka.net with a simple actor (instance) per customer.  When a new file comes in, the https endpoint would route that message to the right actor and this guy would use its already opened TCP connection to insert into our storage.

We have a prototype that seem to work on a single Akka.net node.  

Our problem is we would like to have clustering for 2 reasons:
 - scaling out (when having a large # of customer, it would be nice to distribute this load over different machine)
 - redundancy

We have tried to get a sample going but we are struggling to route message to always the same actor instance in the cluster.  It seems to always be routed to the local node.  Ideally, we would not want to have multiple instance of the actor for the same customer as this would open unnecesary TCP connection into our storage.

Any idea on how to do that?
(apologies for the very long text ;) )

**Comment by Danthar** [comment]
Cluster sharding sounds like the way to go. http://getakka.net/docs/clustering/cluster-sharding

**Comment by kostrse** [comment]
> We have tried to get a sample going but we are struggling to route message to always the same actor instance in the cluster. It seems to always be routed to the local node.

How does your router configuration look like?

**Comment by oliviervaillancourt** [comment]
Will try to work on a cluster sharding as @Danthar mentionned 'cause it seems to fit the bill.  If we run into issues within the next few days, we will try to post the prototype solution and link to it.

**Comment by Silv3rcircl3** [comment]
@oliviervaillancourt closing this one, if you have further question please use the Gitter room.
