### ISSUE TITLE
Disposing ActorSystem does not wait until resources are actually disposed

### ISSUE THREAD

**Issue by dandago** [akkadotnet/akka.net#2291]
If you dispose the ActorSystem and let the application terminate, PostStop() does not get called on a custom logger. I describe this behaviour in my article on [Custom Loggers in Akka .NET](http://gigi.nullneuron.net/gigilabs/custom-loggers-in-akka-net/).

To reproduce the issue, you can use the [code from same article](https://bitbucket.org/dandago/gigilabs/src/9e72a25e3cc80c76aced415e95f8f6c12f5c7636/AkkaNetCustomLogger/?at=master). You will notice that there are two Console.ReadLine()s. The second one was introduced specifically to give PostStop() time to run before the application exits. Remove it, and put a breakpoint in the PostStop() method of the custom logger you're using. You will see that it doesn't get hit.

The problem here is that ActorSystem disposal seems to be firing off something asynchronously, but yields control to the caller before cleanup actually takes place. Thus resources may not really be gracefully cleaned up.

**Comment by Aaronontheweb** [comment]
We do guarantee that children are terminated in the correct order and all actors are stopped before the `ActorSystem.WhenTerminated` completes... but I wonder if it's possible that the `Terminated` message that is fired is sent before `PostStop` is called. That would explain this.

**Comment by Horusiath** [comment]
@AndreSteenbergen have you tried `await actorSystem.Terminate()`?

**Comment by Aaronontheweb** [comment]
I think this has been fixed for some time now
