### ISSUE TITLE
Akka.Net Wire Serializer Repository?

### ISSUE THREAD

**Issue by shivanan** [akkadotnet/akka.net#2299]
I found a couple of issues/gaps in the Wire serializer and would like to contribute some pull requests. I noticed that the github.com/akkadotnet/Wire repository doesn't have an Issues tab (it used to because Google search shows some but I guess it got removed?)

Is https://github.com/AsynkronIT/Wire the source of truth? Should I send my PRs over there?

**Comment by Aaronontheweb** [comment]
@shivanan yep, Roger moved it over there last night
