### ISSUE TITLE
Remoting security

### ISSUE THREAD

**Issue by tomaszchacuk** [akkadotnet/akka.net#2300]
Is there a way to restrict access to actor system ?  I would like to create some kind of plugin system that would be connecting to the main system using akka net remoting but only on localhost (multiple services in multiple languages but always on the same machine). 

I don't want to  give the plugin access to the whole system, but rather some kind of restricted "API". I have two options i guess:
1. Let the plugin connect to the base server (actor system)  and restrict the actors that it can acces (as I read the docs this is not supported and violating assumptions of Akka)
2.Create a separate server with restricted API  plugin 
<--> plugin-server <---> main-server
The main problem here is to not allow the plugin connecting to main-server . Is it possible to achieve such behaviour purely by Akka ?  Please have in mind this will only be going on in localhost

**Comment by Aaronontheweb** [comment]
@tomaszchacuk Untrusted mode is what you want: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Remote/Configuration/Remote.conf#L98 - just whitelist the trusted selection paths on the line below.
