### ISSUE TITLE
Akka.TestKit.NUnit3 works only with outdated NUnit 3.0.0

### ISSUE THREAD

**Issue by andreyleskov** [akkadotnet/akka.net#2326]
Hi guys, I'm using Akka.TestKit.NUnit3 and it seems it works only with NUnit 3.0.0.
On any higher version up to latest 3.4.1 I', receiving error 
"Has no TestFixtures" from runner
![image](https://cloud.githubusercontent.com/assets/2056093/18884647/fdd16d60-84f0-11e6-9971-5fba3716e8a3.png)

Sample code: 
```
using Akka.TestKit.NUnit3;
using NUnit.Framework;

namespace GridDomain.Tests.Framework
{
    [TestFixture]
    public class TestAkkaKit: TestKit
    {
        [Test]
        public void RunMe()
        {
            
        }
    }
}
```

**Comment by Silv3rcircl3** [comment]
@andreyleskov we already have an issue on the NUnit project for it, see https://github.com/akkadotnet/Akka.TestKit.Nunit/issues/10 
I will close this issue and take a look in the next days and update the existing issue on the NUnit repository. 

Anyway, thanks for reporting.

**Comment by andreyleskov** [comment]
@Silv3rcircl3 thank you, I've missed original ticket akkadotnet/Akka.TestKit.Nunit#10.
