### ISSUE TITLE
Support .Net standard

### ISSUE THREAD

**Issue by jbtibor** [akkadotnet/akka.net#2359]
Tried to use Akka.NET in a .Net core class library targeting .Net Standard 1.6 (this is the default in Visual Studio 2015) and package restore failied with this message:
Package Akka 1.1.2 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Akka 1.1.2 supports: net45 (.NETFramework,Version=v4.5)

**Comment by Silv3rcircl3** [comment]
@jbtibor see #2153 , MyGet URL for .Net Standard is in the last comment.
