### ISSUE TITLE
Log no exceptions upon node gracefully terminating Akka.Remote connection

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2367]
This is a smell issue for a lot of users - Helios throws benign exceptions when its async socket is closed (it's how we wake up the read) and the remoting system itself also uses an exception to force disposal and clean-up of its hierarchy. We get complaints from panicked developers in Gitter chat who are terrified that they did something wrong, even though this isn't the case.

We need to go through the following layers and destroy all traces of exceptions from appearing in the logs in the following areas:

- [ ] Akka.Remote transports
- [ ] Akka.Remote ReliableDeliverySupervisor
- [ ] Akka.Remote EndpointReader
- [ ] Akka.Remote EndpointWriter
- [ ] Akka.Remote ProtocolStateActor

This will help reduce many of the support questions that come into Gitter, as well as help decrease the "spook" factor Akka.Remote can give to end users who don't know what the exceptions are for (and that they're harmless.)

**Comment by maxcherednik** [comment]
#2438 #2439 - the issue was addressed here

**Comment by Danthar** [comment]
Closing this. If you feel more work is needed @Aaronontheweb you can reopen at anytime :P

**Comment by Aaronontheweb** [comment]
@Danthar I think it's safe to close this thanks to the heroics of @maxcherednik
