### ISSUE TITLE
[50804] buffered messages in EndpointWriter for ["akka.tcp://NodeSystem@IP:8004"]. You should probably implement flow control to avoid flooding the remote connection.

### ISSUE THREAD

**Issue by leonelcm** [akkadotnet/akka.net#2371]
Hi,

I am generating a huge amount of messages and sending these messages to a remote actor. I am getting the following warning:
[50804] buffered messages in EndpointWriter for ["akka.tcp://NodeSystem@IP:8004"]. You should probably implement flow control to avoid flooding the remote connection.

Is it possible to throttling messages in Akka.net to avoid this issue? Any suggestions to avoid this warning?

Regards,
Leonel

**Comment by sean-gilliam** [comment]
Hopefully, you've found a solution to your problem. Generally questions should be directed to our gitter chat room https://gitter.im/akkadotnet/akka.net.
Issues are usually reserved for actual bugs. Closing this issue.
