### ISSUE TITLE
Type safety feature as in Akka 2.4.1

### ISSUE THREAD

**Issue by beachwalker** [akkadotnet/akka.net#2373]
Any plans to implement type safety features as for Akka itself?
http://doc.akka.io/docs/akka/2.4.1/scala/typed.html

Because the lack of type safety resulting in the missing IDE support (already at compile time instead of runtime failures) is the thing what gets me away from Akka.net. From DDD perspective the Tell(<putanythinghere>) aproach seems like a design flaw. MS Orleans has the type safety but I would like to stay with Akka instead. This is more a question than a bug but I didn't knew where to post such things. ;-)

**Comment by rogeralsing** [comment]
Akka.NET is an exact port of JVM Akka, no more, no less. 
As Akka does not provide typesafety for the core modules, Akka.NET doesn't either.

That being said, the Akka team is working on "Akka Typed" which do solve this.
When/If Akka Typed is ported to .NET, this will be solved.

It is also quite easy to create your own generic wrapper that wraps an ActorRef and only provide a Tell method using the generic argument.

There is also some community effort to make an Orleans like API ontop of Akka.NET.
(Hopefully someone here can provide a link, I do not remember the name of it)

**Comment by Horusiath** [comment]
@beachwalker In case of akka it's quite easy to extend existing mechanics to use generic actor refs. This is already done in Akkling (my Akka F# fork). The same case was already mentioned in #2334 - in that topic you'll be able to see gist for fast implementation of the [TypedRef](https://gist.github.com/Horusiath/f5c77e043ee17e02d0311315bcde9c79). 

When it comes to Orleans style of communication, in akka there's an Akka.Interfaced plugin, which work very similar.
