### ISSUE TITLE
Unicode characters in actor names? Currently not supported

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2383]
Comment from a customer:

> We just ran into a problem on our usage of actor names, as we had not realized the constraint of those to asci character
> We have been using natural names for the actors as for example on Product – we use the productid that the custumers uses, which could contain all kind of non ascii characters (read national/Scandinavian special characters like øæåÆØÅ Ü) 
 
Hmmm.... what would be the best way to support unicode characters? And what all needs to change to support this? Should we support this?

**Comment by rogeralsing** [comment]
Actor paths are validated as uri's, allowing Unicode chars would force us to change this.
It would probably introduce additional overhead in actorref resolution (remote resolve actorref)
This would also affect the virtual path containers.
They use uri encoding to encode entire actor paths. Eg in remote deployment.

**Comment by Aaronontheweb** [comment]
Yep, looks like they came to the same conclusion on the JVM. Nevermind.
