### ISSUE TITLE
Mark custom exception types as serializable.

### ISSUE THREAD

**Issue by basbossink** [akkadotnet/akka.net#2400]
A large number of exception types in the akka.net codebase are not marked as `[Serializable]`, this can lead to problems when instances of these exception types are received by callers in a different `AppDomain`. MSDN's documentation about designing exception types is a bit lacking, FxCop has a number of specific messages related to exceptions and serialization though. Below some links about this topic:
- [MSDN: Defining Exception Classes](https://msdn.microsoft.com/en-us/library/ms173163.aspx#Anchor_1)
- [StackOverflow](http://stackoverflow.com/questions/94488/what-is-the-correct-way-to-make-a-custom-net-exception-serializable)

## Proposal
- Add a `[Serializable]` attribute to all exception types that do not already have it (CA2237)
- Resolve the following set of FxCop warnings:
   - [CA1032](https://msdn.microsoft.com/en-us/library/ms182151.aspx)
   - [CA1064](https://msdn.microsoft.com/en-us/library/bb264484.aspx)
   - [CA2229](https://msdn.microsoft.com/en-us/library/ms182343.aspx)
   - [CA2235](https://msdn.microsoft.com/en-us/library/ms182349.aspx)
   - [CA2236](https://msdn.microsoft.com/en-us/library/ms182326.aspx)
   - [CA2237](https://msdn.microsoft.com/en-us/library/ms182350.aspx)
   - [CA2238](https://msdn.microsoft.com/en-us/library/ms182344.aspx)
   - [CA2239](https://msdn.microsoft.com/en-us/library/ms182362.aspx)
   - [CA2240](https://msdn.microsoft.com/en-us/library/ms182342.aspx)
   For commit 40b0c553ea on dev this results in roughly 161 warnings.
- Replace all IActorRef properties on exceptions with string properties, and fill them with:
  `Serialization.Serialization.SerializedActorPath(actor)` since the actor ref can only be deserialized in a given actor system and this is not available upon deserialization. The constructors can still take an actor ref, the implementation can use the above method to store the actor path in the exception object and this string value can be serialized without problems.

**Comment by alexvaluyskiy** [comment]
`SerializableAttribute` makes sense only if you are using Binary Serialization. Akka.NET does not use it and does not recommend it.

Akka.NET 1.3 will have a dedicated serializer for exceptions with custom properties (also support serializing ActorRefs)
