### ISSUE TITLE
Helios.Codecs.TooLongFrameException

### ISSUE THREAD

**Issue by kantora** [akkadotnet/akka.net#2412]
I have a cluster with several nodes. All nodes have the same network configuration, but different roles. All nodes are run in mono environment.

In some conditions under load (can't catch the exact conditions) I get disassociation error when specific node are excluded from cluster (the node is always the same). On startup after all sharding managers and sharding proxies started - it is disassociated.

Deep log hunt gave me this.
The disassociated node have this log message before everything crashed:

```
"Depth": 0,
  "ClassName": "Helios.Codecs.TooLongFrameException",
  "Message": "Adjusted frame length exceeds 52428800: 539784306 - discarded",
  "Source": "Helios",
  "StackTraceString": "  at Helios.Codecs.LengthFieldBasedFrameDecoder.Fail (System.Int64 frameLength) [0x00044] in <39e0fd5af425401aaa3db56db0b54051>:0 \n  at Helios.Codecs.LengthFieldBasedFrameDecoder.FailIfNecessary (System.Boolean firstDetectionOfTooLongFrame) [0x00042] in <39e0fd5af425401aaa3db56db0b54051>:0 \n  at Helios.Codecs.LengthFieldBasedFrameDecoder.Decode (Helios.Channels.IChannelHandlerContext context, Helios.Buffers.IByteBuf input) [0x00145] in <39e0fd5af425401aaa3db56db0b54051>:0 \n  at Helios.Codecs.LengthFieldBasedFrameDecoder.Decode (Helios.Channels.IChannelHandlerContext context, Helios.Buffers.IByteBuf input, System.Collections.Generic.List`1[T] output) [0x00000] in <39e0fd5af425401aaa3db56db0b54051>:0 \n  at Helios.Codecs.ByteToMessageDecoder.CallDecode (Helios.Channels.IChannelHandlerContext context, Helios.Buffers.IByteBuf input, System.Collections.Generic.List`1[T] output) [0x0002c] in <39e0fd5af425401aaa3db56db0b54051>:0 "
```

Immediately after this the other node got:

```
"Depth": 0,
  "ClassName": "System.Net.Sockets.SocketException",
  "Message": "Operation aborted",
  "Source": "Helios",
  "StackTraceString": "  at Helios.Channels.Sockets.SocketChannelAsyncOperation.Validate () [0x00010] in <39e0fd5af425401aaa3db56db0b54051>:0 \n  at Helios.Channels.Sockets.AbstractSocketByteChannel+SocketByteChannelUnsafe.FinishRead (Helios.Channels.Sockets.SocketChannelAsyncOperation operation) [0x0003d] in <39e0fd5af425401aaa3db56db0b54051>:0 ",
```

At first, I thought that the second node sends a mega-sized message (no idea where it could get half gigabyte message), but then I've found that `EndpointWriter` have the protection and such message should be blocked before sending (not in receiving procedure).

So this time I am out of ideas and even not sure whether this is the problem of application code or some deep Akka/Helios/mono network problem and would appreciate any hints to dig further.

**Comment by kantora** [comment]
Also - all nodes are run in docker compose. So the network is completely virtual.

**Comment by kantora** [comment]
I wonder if in any way `pdu` can become corrupted during send. Any race conditions? Getting this errors only under load, or on node start, after sharding initialization, when other nodes sharding proxies have massive amount of buffered messages.

**Comment by kantora** [comment]
Hmm... found class `RemoteConnection`, in method `private static void ApplyChannelPipeline(IChannel channel, IChannelHandler handler)` it generates `LengthFieldBasedFrameDecoder` with const  `maxFrameLength` as `10000`. The configuration contains the parameter with the same name and it may differ from this. This is just the guess. 
But I changed this manually and haven't got new exceptions yet (maybe I am just lucky). I'll continue testing and further investigation to track this parameter. Need to learn all the akka network part :(

**Comment by kantora** [comment]
Nope, that was used only in testkit...

**Comment by kantora** [comment]
I have a theory.., Maybe someone can tell if this can be true.
In this test, I use the `Sharding` with persistence FSM actors as entities. When the node comes up and joins the cluster the sharding mechanism brings up hundreds of actors. Each of the actors starts restoring itself (I use Akka.Persistance.Redis). So I am getting hundreds of parallel redis requests as `RedisJournal` implements `AsyncWriteJournal` and all redis negotiation are run in individual tasks with `PipeTo` connection to actor network. I suppose that this can lead to crush / hang all network activities and lead to unpredicted results.

This http://softwareengineering.stackexchange.com/questions/234672/is-there-are-problem-holding-large-numbers-of-open-socket-connections-for-length article confirms that too many open sockets is not well supported in .Net.

In case I am right, `AsyncWriteJournal` should be considered evil (along with 'PipeTo' if it involves network actions). I'll suggest to replace it with a model of parent actor and a number of workers under router that should limit the number of parallel connections to a persistence data source.

**Comment by kantora** [comment]
I'll try to create new RedisJournal implementation with suggested model to see if it will take the problem away.

**Comment by kantora** [comment]
No... Unfortunately, that hasn't fixed the problem. Possibly, there is some bug in Helios itself... But it is marked deprecated... Any news on DotNetty migration?

**Comment by Aaronontheweb** [comment]
@kantora yep, just got an update on it this morning. Underway, have a bunch of tests that still need to pass but we're getting there.

**Comment by kantora** [comment]
@Aaronontheweb good news! In this case, I suppose that this issue can be closed as obsolete. As after DotNetty migration either this problem will disappear or I'll get completely other exception and stack trace (in case there is some high-level issue).

**Comment by sean-gilliam** [comment]
Helios is replaced by DotNetty and is no longer under active development.
