### ISSUE TITLE
Akka.NET CI Bot Account

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2413]
Professionalizing the CI process! Need to do the following:

1. [x] Setup bot account for Github
2. [x] Give bot account ability to publish API status changes
3. [x] Give bot NuGet publish keys
4. [x] Decouple of the above from my personal account

**Comment by Danthar** [comment]
@Aaronontheweb does the akka project has its own email domain per chance ? I was thinking it might be cool to create the bot under akkabot@akka.net

**Comment by Aaronontheweb** [comment]
@Danthar we have some pre-existing email address at getakka.net at the moment, not sure where those emails are going right now though :p 

Either way, we could use that for a bot

**Comment by Danthar** [comment]
We could use this account for the nuget packages: https://www.nuget.org/profiles/akkadotnet

**Comment by Aaronontheweb** [comment]
@Danthar yep, that's the plan - going to have the Github bot and the NuGet publish account both map to that identity.

**Comment by Aaronontheweb** [comment]
Running a test on a PR right now to see if @AkkaDotNet-CI's mug shows up instead of mine on the step where I used its OAuth token instead of mine. 99% sure it has the correct rights but just want to verify before I change it throughout the templates.

**Comment by Aaronontheweb** [comment]
Cool, looks like that worked:

![image](https://cloud.githubusercontent.com/assets/326939/21736988/b94fb8da-d429-11e6-941e-2ed576942606.png)

**Comment by Aaronontheweb** [comment]
@Danthar have the bot running all of the status checks for Akka.NET and Hyperion now, but will need some help cutting it over for the plugins since aren't able to use a TeamCity template for the status checks since each repository has to be named individually :(

**Comment by Danthar** [comment]
Updated all contrib and current persistence projects. Still need to test, so I hope I did it right, else ill have to redo the whole thing :P

**Comment by Aaronontheweb** [comment]
Published the 1.1.3 release using the bot; website is being updated via the bot now; and all CI is run using it. Good to go.
