### ISSUE TITLE
cluster singleton not honoring roles

### ISSUE THREAD

**Issue by gamemachine** [akkadotnet/akka.net#2415]
this is using 1.1.2.30-beta for cluster related packages, 1.1.2 for akka core stuff.

The seed is the default lighthouse setup.  No changes to the config I can think of, lighthouse is in the lighthouse role.

The other node, call it the app node, is in it's own role.

This is the role specific section of the app node cluster config.  Note that I tried setting the singleton role on lighthouse just to see what would happen, and no difference there.

roles = [game]
singleton {
  role = "game"
}

On the app node I startup the singleton and proxy via code.  Not sure how to correctly copy/paste code here so put it into a gist https://gist.github.com/gamemachine/f6a3c83a45a30aff6b981f3992bedaa3.

If I start lighthouse then the app node, I see the singleton actor started.  But I don't see the singleton identified message like I normally do.  And messages to the singleton via the proxy don't get there.

If I start the app node without lighthouse running, I see singleton identified and the singleton works fine, we have been using it in a game that's in beta now for a couple of months, just running a single app node.

If I then stop the seed, this is what I see on the app node:

[INFO][12/16/2016 1:34:21 AM][Thread 0008][Cluster] Cluster Node [akka.tcp://DuoFun@127.0.0.1:4054] - Leader is auto-downing unreachable node [akka.tcp://DuoFun@127.0.0.1:4054]
[INFO][12/16/2016 1:34:21 AM][Thread 0008][[akka://DuoFun/system/cluster/core/daemon#1270790603]] Marking unreachable node [akka.tcp://DuoFun@127.0.0.1:4053] as [Down]
[INFO][12/16/2016 1:34:21 AM][Thread 0022][[akka://DuoFun/system/cluster/core/daemon#1270790603]] Leader is removing unreachable node [akka.tcp://DuoFun@127.0.0.1:4053]
[INFO][12/16/2016 1:34:21 AM][Thread 0022][[akka://DuoFun/user/ClusterInfoActor#1664040289]] Member is Removed: Member(address = akka.tcp://DuoFun@127.0.0.1:4053, status = Removed, role=[lighthouse], upNumber=1)
[INFO][12/16/2016 1:34:21 AM][Thread 0023][[akka://DuoFun/user/manager#91960789]] Member removed [akka.tcp://DuoFun@127.0.0.1:4053]
[INFO][12/16/2016 1:34:21 AM][Thread 0022][[akka://DuoFun/user/managerProxy#1259361088]] Singleton identified at [akka://DuoFun/user/manager/singleton]

**Comment by gamemachine** [comment]
Fyi port 4054 is the app node, 4053 is lighthouse.

**Comment by gamemachine** [comment]
So this turned out to be a configuration issue.  I didn't have a singleton-proxy config with the role set.

**Comment by Aaronontheweb** [comment]
@gamemachine here I was, all excited about fixing a bug in `Cluster.Tools.Singleton`... :p
