### ISSUE TITLE
Cluster gets confused when node restarts too quickly

### ISSUE THREAD

**Issue by ayoung** [akkadotnet/akka.net#2419]
Suppose we have a seed node and a node hosted in IIS (web-node). If we go ahead and restart the web-node in IIS, the stop and start happen so fast that the cluster thinks that there are now two web-nodes on the cluster.

I will update this issue with more info shortly.

**Comment by Aaronontheweb** [comment]
@ayoung I'm curious to see how this is possible - the UID system should be able to automatically detect a node restart and kill the old incarnation automatically. Are you sure the port numbers aren't changing?

**Comment by ayoung** [comment]
Can I send you the code directly? I have an example but it has some
proprietary code in it.

**Comment by Aaronontheweb** [comment]
Go for it

**Comment by Danthar** [comment]
Status on this? Can we close this ?

**Comment by ayoung** [comment]
No. I was going to privately send Aaron an example. Sorry, haven't done this yet. I'll get to it either today or tomorrow.
