### ISSUE TITLE
Impossible to notice failed approval tests when running in console

### ISSUE THREAD

**Issue by Rattenkrieg** [akkadotnet/akka.net#2423]
This is due to weak support of XUnit2 by ApprovalTests.Net

Instead of prompt for verification/approval it fails with internal NRE and prints stacktrace which naturally get overwriten by subsequent outputs.
No matter of that final report prints juicy "OK":

![default](https://cloud.githubusercontent.com/assets/6948307/21406443/beabe528-c7dc-11e6-84ae-645816ae83f9.png)

Fix already has been provided approvals/ApprovalTests.Net#171 as well as workaround.
Don't think that this actually urgent, but let this issue be there as a reminder to upgrade package when upgrade arrives.

**Comment by marcpiechura** [comment]
ApiApproval is working fine in the builds as well as locally, including build failures, so I’ll close this one.
