### ISSUE TITLE
Actor with Resume strategy does not clear child actor's CurrentMessage

### ISSUE THREAD

**Issue by ali-ince** [akkadotnet/akka.net#2426]
I have discovered a strange behavior when using an actor with a kind of pool router configured with a OneForOneStrategy returning Directive.Resume.

When one of the child actors of the router fails due to an exception on one of its receive handlers, router's strategy returns resume directive which seems to work as expected. However, when I inspect that resumed child actor I see that its Cell.CurrentMessage property is not cleared up - which is not the case when using standalone actors.

Here is a small console application code to demonstrate the issue. Child actors' CurrentMessage properties are dumped in the console.

```csharp
    class Program
    {

        public class TestActor : ReceiveActor
        {

            public TestActor()
            {
                Receive<string>(m => HandleError(), m => m.Equals("error"));
                Receive<string>(m => HandleNormal(), m => m.Equals("normal"));
            }

            private void HandleError()
            {
                throw new Exception("Test Exception");
            }
            
            private void HandleNormal()
            {
                Thread.Sleep(500);
            } 

        }


        static void Main(string[] args)
        {
            ActorSystem sys = ActorSystem.Create("TestSystem");

            OneForOneStrategy commonOneForOneStrategy = new OneForOneStrategy(exc =>
            {
                return Directive.Resume;
            });

            RouterConfig defaultPoolConfig =
                new RoundRobinPool(5)
                    .WithSupervisorStrategy(commonOneForOneStrategy);

            Props tstActorProps = Props.Create<TestActor>(() => new TestActor());

            IActorRef tstActor = sys.ActorOf(tstActorProps.WithRouter(defaultPoolConfig), "tstActor");

            tstActor.Tell("error");
            tstActor.Tell("normal");
            tstActor.Tell("normal");
            tstActor.Tell("normal");
            tstActor.Tell("normal");

            IEnumerable<IActorRef> children = ((dynamic) tstActor).Children;
            foreach (IActorRef actorRef in children)
            {
                LocalActorRef localActorRef = actorRef as LocalActorRef;

                if (localActorRef != null)
                {
                    Console.WriteLine("{0} CurrentMessage: {1}", localActorRef.Path.Uid, localActorRef.Cell.CurrentMessage ?? "null");
                }
            }
        }
    }
```

When we have huge messages, those messages are pinned to memory and GC does not collect them since they're referenced by the CurrentMessage property - increasing process memory. Although this happens until a new message hits that specific child actor, that may take time depending on message throughput.

I guess it to be a bug, any comments?

**Comment by Rattenkrieg** [comment]
Hi, @ali-ince you are saying 

> However, when I inspect that resumed child actor I see that its Cell.CurrentMessage property is not cleared up - which is not the case when using standalone actors.

I have not found any evidence of such behavior in code. You can check it [here](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/ActorCell.FaultHandling.cs#L114)
Also I have created test to demonstrate that after resuming local actor cell is preserving last message
https://github.com/Rattenkrieg/akka.net/blob/pool-clear-currentmsg-after-resume-2426/src/core/Akka.Tests/Routing/RoundRobinSpec.cs#L377

**Comment by ali-ince** [comment]
Hi,

Based on your test, I created another version of the test where the exact behavior can be seen. You can have a look at https://github.com/ali-ince/akka.net/blob/dev/src/core/Akka.Tests/Routing/RoundRobinSpec.cs#L337

**Comment by Rattenkrieg** [comment]
I completely agree with your statement about routed actor - it keeps current message after resume. What I'm argue is behavior of standalone actor - it is also keeps current message after resume till new message arrives.

**Comment by ali-ince** [comment]
Ok, I will try to create test cases for different scenarios and list the outcomes.  

I did examined the code and I guess [this line](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/ActorCell.DefaultMessages.cs#L83) should be moved to finally block - but I suspect that it may have some severe side effects for custom supervisor strategy deciders.

**Comment by Rattenkrieg** [comment]
I have checked jvm akka [source code](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorCell.scala#L497). It is also follows logic of nulling currentMessage in very last line of try block.

**Comment by Rattenkrieg** [comment]
I found reason why we can't simple null out _CurrentMessage_ in finally block.
Imagine that we moved nulling logic in finally block:
When actor fails with exception akka wraps catched exception with context into system message and [**sends(!)**](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/ActorCell.FaultHandling.cs#L246) it to parent. Now parent's supervision logic (**P**) and rest of actorcell code (**C**) runs asynchronously!
And if **P** is relying on _CurrentMessage_ in some place (and it does when supervisor decides to restart actor, so it have to send _CurrentMessage_ in actor's _PreRestart_) it may found that **C** already had nulled out _CurrentMessage_. Now your custom _PreRestart_ logic is broken.

So as workaround you can null out current message in supervisor (by sending dummy message to failed actor), but since router's supervisors have no access to Context.Sender, you have to introduce special actor in hierarchy and do such hack in its overriden supervision strategy.

**Comment by ali-ince** [comment]
I have written some test cases about this issue which shows that this is a problem with pooled actors. You can have look at it [here](https://github.com/ali-ince/akka.net/blob/7bfd61252a1319ec9b15b5a72f75a308ec62f99c/src/core/Akka.Tests/Actor/FailingActorSpec.cs#L16).

If you have any comments on the test cases, it is welcome :)

**Comment by Rattenkrieg** [comment]
Hi @ali-ince in your test ``simple_child_actor_must_clear_currentmessage_after_failure_and_resume`` you are [creating child actor](https://github.com/ali-ince/akka.net/blob/7bfd61252a1319ec9b15b5a72f75a308ec62f99c/src/core/Akka.Tests/Actor/FailingActorSpec.cs#L70) with custom _SupervisorStrategy_ not the parent. So parent gets default one, which restarts child on failure, so thats why _CurrentMessage_ is nulled. Simply add [``.WithSupervisorStrategy(strategy)``](https://github.com/ali-ince/akka.net/blob/7bfd61252a1319ec9b15b5a72f75a308ec62f99c/src/core/Akka.Tests/Actor/FailingActorSpec.cs#L223) when instantiating parent's props and observe failing test.

**Comment by ali-ince** [comment]
Ok I've fixed that test case and now all tests are failing as you've already pointed out. Besides I've written a sample application on Java and I see that it also does not clear out currentMessage property.

Another fix approach to be taken may be nulling out this property on [this line](https://github.com/ali-ince/akka.net/blob/dev/src/core/Akka/Actor/ActorCell.FaultHandling.cs#L43).

Anyhow, what do you think this issue is - a bug or "not an issue at all"?

**Comment by Aaronontheweb** [comment]
@ali-ince IMHO, send in a pull request with your failing unit tests.  That should make it really easy for us to see which ones aren't behaving consistently and look further from there. Issue might be that the `RoutedActorCell`, which the router uses, is overriding something in an inconsistent way. Should be easy to tell once the PR is in.
