### ISSUE TITLE
Wire serialisation issue with ImmutableList

### ISSUE THREAD

**Issue by pikulearns** [akkadotnet/akka.net#2435]
I upgraded the serializer to Wire in my project and when serialising an object with an ImmutableList, serialisation does not work. 
If I change it to List or IEnumerable it works fine. Any suggestions?

Akka.Serialization.Wire:1.1.2.30 beta
Akka.NET: 1.1.2

Error [Object of type 'XYZ.SerialiseCompleted1[System.String][]' cannot be converted to type 'System.Collections.Generic.IEnumerable1[System.String]'.] [ at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast) at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr) at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig) at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at Wire.SerializerFactories.ImmutableCollectionsSerializerFactory.<>cDisplayClass5_0.<BuildSerializer>b1(Stream stream, DeserializerSession session) at Wire.ValueSerializers.ObjectSerializer.ReadValue(Stream stream, DeserializerSession session) at Wire.StreamExtensions.ReadObject

**Comment by Aaronontheweb** [comment]
@pikulearns we're switching from Wire to [Hyperion](https://github.com/akkadotnet/Hyperion) (a fork of Wire), and this issue has been resolved there. We'll be releasing an Akka.NET 1.1.3 update this week (knock on wood) with an updated version of Hyperion that resolves this issue.

**Comment by pikulearns** [comment]
thanks @Aaronontheweb

**Comment by Aaronontheweb** [comment]
@pikulearns no problem, we'll close that issue once that release is out.

**Comment by Danthar** [comment]
Closing, since a new version has been released.
