### ISSUE TITLE
NuGet binary wrongly in the repository

### ISSUE THREAD

**Issue by SeanFarrow** [akkadotnet/akka.net#2440]
Having spoken with @aaronontheweb, it appears that the NuGet 3.4 binary has been erroneously commited in to the .NuGet folder of the repository.

I am proposing we remove this file along with the NuGet.targets and pull them from the users cache, ensuring that they are appropriately added to the .gitignore file.

The rationale behind this change would be that most developers have NuGet on there system already, and if they don't we can just refresh the file from the web. I'm happy to create a PR for this in the next few days.

**Comment by Danthar** [comment]
Deleting the NuGet.targets breaks the build atm. But if you can resolve that. Go for it.
The simpler solution would be to only delete the NuGet.exe and add it to the .gitignore file (if its not in there already).
A PR is always welcome.

**Comment by SeanFarrow** [comment]
The fact that removing the NuGet.targets file breaks the build means one or more projects is relying on the file. I'm looking at this currently, so should have something for you later today. Also, I'm sure this was in the .gitignore, so it shouldn't have been added in the first place.
