### ISSUE TITLE
ClusterClientConfig API InitialContacts issue

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/akka.net#2468]
So the ClusterClientConfig takes an parameter called InitialContacts. 
Currently the public API to set that forces the user to specify an IImmutableSet. This is a case of leaky abstraction. A user should just be able to specify any enumerable of ActorPaths. And let the ClusterClient or ClusterClientConfig transform that to an Immutable Collection type.

**Comment by alexvaluyskiy** [comment]
Each initial contact should be unique, that why we are using `Set` here. And .NET does not have a read only versions of `ISet` interface. That why we are using `IImmutableSet`

**Comment by Danthar** [comment]
I understand why `IImutableSet` is used. Im merely stating that a user should just be able to provide an IEnumerable and its the ClusterClientConfig's responsibility to turn that into an unique set.

**Comment by alexvaluyskiy** [comment]
Make sense. Could you make a pull request, please?

**Comment by Danthar** [comment]
Certainly
