### ISSUE TITLE
Add Obsolete attribute on WireSerializer class

### ISSUE THREAD

**Issue by sean-gilliam** [akkadotnet/akka.net#2481]
We should mark the WireSerializer class (src/contrib/serializers/Akka.Serialization.Wire/WireSerializer.cs) with the [Obsolete] attribute stating that we're transitioning towards Hyperion.

**Comment by siudeks** [comment]
I'm looking for some warm-up in akka.net project and this one looks as a deadly simple one. Is it really only about only marking WireSerializer as obsolete? One line change?

**Comment by sean-gilliam** [comment]
Yea it's a really simple one-liner.

**Comment by Aaronontheweb** [comment]
@siudeks all yours dude

**Comment by sean-gilliam** [comment]
Closed by #2579
