### ISSUE TITLE
Migrate the build from Fake to Cake

### ISSUE THREAD

**Issue by SeanFarrow** [akkadotnet/akka.net#2488]
Have spoken to @aaronontheweb, it has become apparent that Fake is not supporting .net core/standard. Given this, I am proposing we migrate the Akka.net build from Fake to Cake. This allows us to run under .net Standard and, in the future, could provide other improvements such as providing release notes given a list of issues closed on GitHub.

I am happy to do this if no-one has any objections.

**Comment by DustinVenegas** [comment]
@SeanFarrow, FAKE has [.NET Core extensions](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/DotNetCLIHelper.fs) and [Git Support](https://github.com/fsharp/FAKE/tree/master/src/app/FakeLib/Git) for release notes. The FAKE build appears to be working fine for the project. 

From my personal experience with both, CAKE is more verbose and less mature than FAKE. CAKE things like debugging, streaming PowerShell execution, and .NET Core have been personally lacking. At least that's my $0.02.

**Comment by SeanFarrow** [comment]
If that’s the case, then we might not need to do anything, I’l leave it for @aaronontheweb to make the final call.

**Comment by Aaronontheweb** [comment]
@DustinVenegas @SeanFarrow I definitely like this solution way better. Much less work to add a shim to our FAKE files than it is to port everything to CAKE

**Comment by SeanFarrow** [comment]
Probably worth closing this then, we can piggy-back off the .netCore issue when it’s merged if there’s problems!
