### ISSUE TITLE
TestActorRef broken for ReceiveAsync

### ISSUE THREAD

**Issue by thomastomanek** [akkadotnet/akka.net#2491]
See this gist
https://gist.github.com/thomastomanek/9cb4df6476d24c60442c04ff9f7a93d4

If you run the test and look at the output you will see that the receive handler for SomeMessage in the 'Loading' behavior is being used, which from reading the code looks impossible. If in the test setup you create a regular actor with Sys.ActorOf then this test works fine, suggesting that something in the TestActorRef isn't happy.

Also worth noting that if you take out the await in the ReceiveAsync block it's also ok.

**Comment by thomastomanek** [comment]
After more investigation this looks like it's being caused by the custom SynchronizationContext used in the TestKit (huzzah). The context that you end up with in the continuation (the rest of the ReceiveAsync method) is the context for the TestActor and not the user actor, meaning the Become is pushing the beahvior onto a different stack. This then explains why the next message is handled by the wrong receiver.

#907 seems to cover the nuts and bolts and the reasons this SyncCtx was implemented, and I'm sure the initiated will understand it. This change was quite a while ago though, I can't entirely believe it's gone this long without being noticed (unless no one is unit testing ReceiveAsyncs....)

**Comment by Aaronontheweb** [comment]
closed via https://github.com/akkadotnet/akka.net/pull/4861
