### ISSUE TITLE
Cluster.MemberRemoved does not always fire

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2492]
Looks like #2455 is a symptom of this issue.

Under some circumstances, `MemberRemoved` is not correctly propagated from the leader to its children.

Some context from an end-user in our Gitter chat earlier today:

> When a node gets into this state it doesn't leave cleanly. It tries to, I have a monitor running in all service discovery nodes (2 of them). They both report the cluster status that they see. When this problem happens the cluster status us everything UP and everything Seen. The leader gets the request that the node is exiting and this is logged every second that it is moving the node to exiting but it never exits. After 15 seconds my windows service will kill the service and failure detection will kick in. I manually down the node although just starting it again causes the cluster to see the new node and remove the old one. The cluster monitors both report the node is removed. The node rejoins and gets stuck.

Not entirely clear what the exact issue is, but this should give us enough information to go looking for it.

**Comment by maxcherednik** [comment]
@Aaronontheweb I was able to reproduce similar case. The setup is really easy:
1 seed node and 4-5 normal nodes. Every node has a graceful shutdown logic, which waits for member removed and then closes the application. I run all the nodes locally and then very fast one by one send Ctrl+C to every node but the seed node. Sometimes 1 node fail to stop.

**Comment by crucifieddreams** [comment]
Apologies for the delay in posting a reply folks. It takes a bit of time to get approval to post logs and screenshots (i'm pretty sure glaciers move faster) as well as gather data that may be useful and illustrate the problem. 

I believe as @maxcherednik has already reproduced that you are correct @Aaronontheweb. I've attached a log as a PDF of our SEQ logs (getting things out of the network is tedious even with approval :), pdf was about the best I could manage apologies) showing an exit from the cluster as well as screenshots of before and after the event as reported in one of our cluster monitor nodes. The monitors are a WCF service hosted inside our process running our service discovery actor systems. The service discovery essentially being lighthouse with a few extra bits (we've yet to move to cluster client which would allow us to do the same thing as the hosted WCF service provides). 

![hurrah](https://cloud.githubusercontent.com/assets/13729156/22528690/4e054f9c-e8cc-11e6-88c1-d86ae8f4f9ff.png)
![oops](https://cloud.githubusercontent.com/assets/13729156/22528694/506053f4-e8cc-11e6-8421-d533528317c7.png)

[export-8d44aab76e75165.xlsx.pdf](https://github.com/akkadotnet/akka.net/files/746366/export-8d44aab76e75165.xlsx.4.pdf)

I've highlighted the important leader events in color so you can find them pages 1,2 and 10 (you'll likely need to zoom in to read the text).

This particular log shows our timeout kicking in for an exit from the cluster and an issue of a DOWN as the service dies. What I have noticed when we arrive in this state is that issuing a down (be it as the service dies or manually downing via our WCF service) ensures the node never rejoins the cluster (when it tries to we never get convergence ...until I start nuking nodes on the cluster until the node gets marked as up). This made me think of the issue @maxcherednik mentioned on Gitter whereby sending a leave to a joining member ensures it also never rejoins. I will try to post a log of the rejoin tomorrow (although the screenshot of SEQ below shows a node rejoining after the same issue and the leader attempting to bring it up).  I've yet to get time to look at this particular part of the Akka.NET source code so won't make any assumptions that they are related.  

I have also attached a screenshot of the leader events if we remove the DOWN as a service dies and let the node try to exit the cluster over a period of time (essentially removing the timeout from our manual reset event in our service stop as suggested by @maxcherednik). The leader just continually tries to move the node to EXITING

![seq](https://cloud.githubusercontent.com/assets/13729156/22529134/25f2d55e-e8ce-11e6-9681-6e10745c79bf.png)

**Comment by Aaronontheweb** [comment]
@crucifieddreams I think I see the issue here... leader removes the unreachable node, who also happens to be the node attempting to exit. That looks like the race condition to me.

**Comment by Aaronontheweb** [comment]
Some of the edge cases caused by this appear to be addressed in #2516

**Comment by Aaronontheweb** [comment]
So far this looks like it's been resolved on `dev`, but I'll leave it open until after the 1.2 release has had a chance to gather some dust. Expect that to come soon. Waiting on `Reactive.Streams` to get RTMed so we can RTM Akka.Streams as well.

**Comment by Aaronontheweb** [comment]
This was resolved by #2773, same root cause as #2584
