### ISSUE TITLE
 adaptive load balancing strategy

### ISSUE THREAD

**Issue by kennyup** [akkadotnet/akka.net#2520]
I want to know is that has  adaptive load balancing strategy in akka.net routing strategy.

**Comment by Danthar** [comment]
What do you mean with adaptive load balancing? Load balance based on what metrics ?

Note that Routers in akka.net are nothing more then actors with specific logic themselves. 
So you can easily create your own router actor, which routes messages based on your own metrics.

**Comment by kennyup** [comment]
I see. Thank you for the explanation！
