### ISSUE TITLE
How to configure Hyperion

### ISSUE THREAD

**Issue by brains4math** [akkadotnet/akka.net#2533]
I seem to be following the documentation, but getting an error.
Configuration string is as follows:

            akka {  
                log-config-on-start = on
                stdout-loglevel = DEBUG
                loglevel = DEBUG
                actor { 
                    serializers {
                          wire = "Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion"
                    }
                    serialization-bindings {
                      "System.Object" = wire
                    }
                    provider = "Akka.Remote.RemoteActorRefProvider, Akka.Remote"
                }
                remote {
                    helios.tcp {
                        transport-class = "Akka.Remote.Transport.Helios.HeliosTcpTransport, Akka.Remote"
                        applied-adapters = []
                        transport-protocol = tcp
                        port = 8081
                        hostname = localhost
                    }
                }
            }

The error (from output window)

[WARNING][2/27/2017 7:23:44 PM][Thread 0001][ActorSystem(MyServer)] The type name for serializer 'wire' did not resolve to an actual Type: 'Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion'

Then is binds using Newtonsoft.Json.10.0.1-beta1, warns again

[WARNING][2/27/2017 7:23:44 PM][Thread 0001][ActorSystem(MyServer)] Serialization binding to non existing serializer: 'wire'

And starts to shut down after

> System.Runtime.Serialization.SerializationException: Serializer not found for type Object
   at Akka.Serialization.Serialization.FindSerializerForType(Type objectType)
   at Akka.Actor.Internal.ActorSystemImpl.WarnIfJsonIsDefaultSerializer()
   at Akka.Actor.Internal.ActorSystemImpl.Start()
   at Akka.FSharp.System.create(String name, Config config)

Could someone help what is wrong with the configuration?

**Comment by Horusiath** [comment]
@brains4math it looks like a hyperion serializer type cannot be found within loaded assemblies. Are you sure that you've got [Akka.Serialization.Hyperion](https://www.nuget.org/packages/Akka.Serialization.Hyperion/) package from nuget, and that a correct .dll is referenced in your project?

**Comment by brains4math** [comment]
Yes, Mr Sypytkowski, thank you! That was exactly the problem: I installed Hyperion from nuget, but did not have Akka.Serialization.Hyperion package!

**Comment by virenderkverma** [comment]
My application showing following exception

> An exception of type 'System.Runtime.Serialization.SerializationException' occurred in Akka.dll but was not handled in user code
> 
> Additional information: Serializer not found for type Object

Already installed **Akka.Serialization.Hyperion**

![image](https://user-images.githubusercontent.com/976073/29811676-f3622444-8cc1-11e7-9cb1-5de38ff5ae87.png)

**Comment by virenderkverma** [comment]
This error is fixed. Now facing a new problem.
![image](https://user-images.githubusercontent.com/976073/29812532-8b18c76e-8cc4-11e7-86f7-96c2b84c0fa4.png)

**Comment by Danthar** [comment]
Looks like your missing config in your hocon
```

serialization-bindings {
      "System.Object" = hyperion
}
```

**Comment by Danthar** [comment]
And in the future, please create a new issue, instead of necromancing an old one.
