### ISSUE TITLE
ClusterSingletonManager sending HandOverToMe to [null]

### ISSUE THREAD

**Issue by optiks** [akkadotnet/akka.net#2534]
This looks to be the same bug as Akka 2.2 http://stackoverflow.com/questions/16305194/akka-2-2-clustersingletonmanager-sending-handovertome-to-none.

Basically, the setup is that there's a ClusterSingletonManager with only *one* CSM node configured in the cluster. After the master has dropped and then rejoined the cluster, it tries to handover from the previous master (itself) a number of times. 

Retry [10], sending HandOverToMe to [null]
Retry [9], sending HandOverToMe to [null]
Retry [8], sending HandOverToMe to [null]
Retry [7], sending HandOverToMe to [null]
Retry [6], sending HandOverToMe to [null]
Retry [5], sending HandOverToMe to [null]
Retry [4], sending HandOverToMe to [null]
Retry [3], sending HandOverToMe to [null]
Retry [2], sending HandOverToMe to [null]
Retry [1], sending HandOverToMe to [null]

Is this an expected behaviour?

**Comment by Aaronontheweb** [comment]
cc @Horusiath - looks like a bug to me at least. Was this ever reported on the JVM?

**Comment by Aaronontheweb** [comment]
This is fixed in https://github.com/akkadotnet/akka.net/pull/2267
