### ISSUE TITLE
Consider adding an Analyzer which enforces .ConfigureAwait

### ISSUE THREAD

**Issue by 0x53A** [akkadotnet/akka.net#2551]
There are currently a few issues with async / await (https://github.com/akkadotnet/akka.net/pull/2550)

It is recommended, to always call .ConfigureAwait(false) in library code. (here is one reference https://github.com/dotnet/roslyn/issues/7673)

Would you consider adding a roslyn based analyzer which enforces this? One example would be https://www.nuget.org/packages/ConfigureAwaitChecker.Analyzer.

As far as i understand it, the Analyzer is nuget based, so it will work automagically on all developer machines, and even in the serverbuild.

Here is how it would look like with severity set to error:
![image](https://cloud.githubusercontent.com/assets/4236651/23681465/5ca6fe78-038f-11e7-87ea-21e6ee0e8f7c.png)

**Comment by alexvaluyskiy** [comment]
it is not in the scope of Akka.NET project. You could use the analyser from this package
https://github.com/olohmann/AsyncAwaitAnalyzer
