### ISSUE TITLE
What to obsolete before v1.5

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#2557]
Because we want to release v1.2 soon, it would be good to think about things we could possibly remove from v1.5. This way we give people enough time to acknowlege incoming changes. I know each person on @akkadotnet/core team has probably it's own propositions on what should we get rid of, so we can disscuss about it here.

Some of my ideas:

- Obsolete `TypedActor` (it's bad, most of the people who actually want to use it think about something closer to [this](http://doc.akka.io/docs/akka/current/scala/typed-actors.html) in shape).
- Obsolete [ActorProducerPipelineResolver](http://api.getakka.net/docs/stable/html/10E77023.htm) - it's a flawed implementation, that probably noone is actually using.
- Possibly also obsolete at least some parts of the `ActorProducer` itself - in general the pipeline of building an actors is really complicated in current akka implementation and it makes things such as Dependency Injection hard to implement. As we need to provide some alternative to this, this may be obsoleted later.

I will probably find some more parts. Any other ideas?

**Comment by alexvaluyskiy** [comment]
I think this one should be obsoleted before 1.2 https://github.com/akkadotnet/akka.net/pull/2553

**Comment by alexvaluyskiy** [comment]
PersistentView should be removed in 1.5 (deprecated in Scala Akka 2.5)

**Comment by Horusiath** [comment]
Agree on PersistentView, but first we should provide some form of support for persistent queries for the plugins we have under our control.

**Comment by Danthar** [comment]
Took a quick look at the `ActorProducerPipelineResolver`. Am I correct in stating it allows you to apply a decorator like pattern to your actor ?

**Comment by alexvaluyskiy** [comment]
@Horusiath We could also deprecate `Actor DSL` https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/Dsl/Act.cs

It is an interesting idea to have this DSL, but should it be a part of the core library?

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy nah, keep it. It's not doing any harm by staying there and it does get used.

**Comment by Aaronontheweb** [comment]
In general, don't deprecate things because we can. Deprecate them because they are either broken abstractions or they've been / will be replaced with something better.
