### ISSUE TITLE
Cluster.JoinSeedNodes not electing leader/initializing cluster.

### ISSUE THREAD

**Issue by danbopes** [akkadotnet/akka.net#2563]
See sample service fabric test here: https://github.com/danbopes/akka-service-fabric-test

When the cluster initially starts, [seed nodes are not configured](https://github.com/danbopes/akka-service-fabric-test/blob/master/Lighthouse/App.config#L47). After joining the cluster [here](https://github.com/danbopes/akka-service-fabric-test/blob/master/Lighthouse/Lighthouse.cs#L84), the cluster doesn't elect a leader, or mark nodes as UP.

**Comment by Aaronontheweb** [comment]
Please include some log files here.

**Comment by danbopes** [comment]
Below are some of the service fabric logs. Messages that start with [Lighthouse] were my own debugging messages, one of which you can find [here](https://github.com/danbopes/akka-service-fabric-test/blob/master/Lighthouse/Lighthouse.cs#L82).

[_Node_2] INFO - Starting remoting
[_Node_1] INFO - Starting remoting
[_Node_2] INFO - Remoting started; listening on addresses : [akka.tcp://testapp@localhost:32138]
[_Node_2] INFO - Remoting now listens on addresses: [akka.tcp://testapp@localhost:32138]
[_Node_0] INFO - Starting remoting
[_Node_2] INFO - Cluster Node [akka.tcp://testapp@localhost:32138] - Starting up...
[_Node_2] INFO - Cluster Node [akka.tcp://testapp@localhost:32138] - Started up successfully
[_Node_1] INFO - Remoting started; listening on addresses : [akka.tcp://testapp@localhost:31135]
[_Node_1] INFO - Remoting now listens on addresses: [akka.tcp://testapp@localhost:31135]
[_Node_2] INFO - No seed-nodes configured, manual cluster join required
[_Node_1] INFO - Cluster Node [akka.tcp://testapp@localhost:31135] - Starting up...
[_Node_1] INFO - Cluster Node [akka.tcp://testapp@localhost:31135] - Started up successfully
[_Node_1] INFO - No seed-nodes configured, manual cluster join required
[_Node_0] INFO - Remoting started; listening on addresses : [akka.tcp://testapp@localhost:30138]
[_Node_0] INFO - Remoting now listens on addresses: [akka.tcp://testapp@localhost:30138]
[_Node_0] INFO - Cluster Node [akka.tcp://testapp@localhost:30138] - Starting up...
[_Node_0] INFO - Cluster Node [akka.tcp://testapp@localhost:30138] - Started up successfully
[_Node_0] INFO - No seed-nodes configured, manual cluster join required
[_Node_1] [Lighthouse] Waiting for more cluster nodes to start up.
[_Node_0] [Lighthouse] Joining cluster: akka.tcp://testapp@localhost:32138, akka.tcp://testapp@localhost:31135, akka.tcp://testapp@localhost:30138
[_Node_2] [Lighthouse] Joining cluster: akka.tcp://testapp@localhost:31135, akka.tcp://testapp@localhost:30138, akka.tcp://testapp@localhost:32138
[_Node_1] [Lighthouse] Joining cluster: akka.tcp://testapp@localhost:32138, akka.tcp://testapp@localhost:30138, akka.tcp://testapp@localhost:31135

At this point, none of the nodes communicate, mark members as up, or elect a leader.

**Comment by Aaronontheweb** [comment]
Going to investigate this. Did some manual testing and it looks like there's some inconsistent behavior in `Cluster.JoinSeedNodes` that is either:

* Behavior that works as intended, but not as advertised
* An actual bug

**Comment by Aaronontheweb** [comment]
Nevermind, I figured your issue out and it's not related to mine.

Your problem is that your seed node configuration is inconsistent. 

I just added some color to our documentation on the subject to explain what's going on here:

> NOTE: A special rule applies the first time a cluster forms: the first seed node declared in a `akka.cluster.seed-nodes` list *must be up*. Otherwise the cluster will not form. This is designed to prevent a split brain from forming the first time a cluster launches. And in general, as a best practice: **always use an identical seed node list on every node, including the seed nodes**. This will give you the most consistent behavior and results.

PR is here: https://github.com/akkadotnet/getakka.net/pull/237

**Comment by danbopes** [comment]
There's no way to prevent split brain behavior? In the service fabric, the initial seed node list is not able to be determined until the nodes initialize, which eliminates the ability for me to use `akka.cluster.seed-nodes`. Can we add this as a feature request to have `Cluster.JoinSeedNodes` support joining if the cluster hasn't been initially setup?

**Comment by Aaronontheweb** [comment]
this technique *does* prevent split brain behavior. Think of it this way: when your cluster first boots, in order to ensure that everyone is talking to *the same cluster* we require the first node in the seed node list to be up. If the first seed node is a totally different node for everyone else, no one knows who the first seed node is.

Sort your seed nodes into a the same order for each node and this should work.

**Comment by Aaronontheweb** [comment]
If it doesn't I'll reopen the issue.

**Comment by kostrse** [comment]
I was thinking myself on how to properly host **seed nodes** in Service Fabric, and so far I didn't find a working solution.

Service Fabric environment is a dynamic, so Akka cluster nodes need to know at least one another cluster node which is can be statically accessed (by well known, never changing IP). As long as they all can access such static node, then they can discover each other too.

It's problematic to host seed node itself in Service Fabric cluster, and make it accessible by a predefined, well-known static address, it goes contrary with Service Fabric idea.

### Quick solution

Host a few seed nodes outside of Service Fabric, just as windows services.
And have them defined in `akka.cluster.seed-nodes` for Service Fabric hosted Akka nodes.


### Possible more sophisticated approach

The more sophisticated, theoretical, solution would be something like this:

* Host seed nodes as a separated Service Fabric application with availability -1 (i.e. on all Service Fabric nodes).

* Never shut down the seed Service Fabric application when the main Service Fabric application with other Akka cluster nodes being upgraded / restarted.

* The main application Service Fabric services should obtain a list of seed nodes not from the naming service, but from Service Fabric's node list. i.e. it should be assumed that all Service Fabric nodes have a seed service on a predefined port. If seed node absent on a Service Fabric node, then this is should be considered as a problem.

* There should be no problem when a new Service Fabric node added to the cluster.

* There will be a problem to remove a Service Fabric node from the Service Fabric cluster.

This topic needs further research.

**Comment by Horusiath** [comment]
@kostrse Akka seed nodes don't have to be available under static IP, however this IP must be a well known address at the moment of joining node to the cluster.

A common approach I've found is to use service discovery feature of Service Fabric. When node starts, it looks in service discovery for another service (akka cluster node) and it's IP. If it has not been found, it then registers itself and starts as a cluster seed node. On graceful shutdown it unregisters itself.

Another case is unexpected shutdown:

 - I'm not familar enough to say if SF health check service can be used to down unreachable cluster nodes, but quite natural approach is to build a dedicated actor working in cluster singleton mode (so it's only one instance of that actor in the entire cluster, migrating from dead nodes to alive ones) that monitors a cluster nodes and removes them from a service discovery register when it recognizes them as dead.
- Another approach is to add timestamp notifying last activity. Each node has an actor obligated to periodically update that timestamp for current node. All service registry entries with timestamp older than specified threshold are considered dead.

**Comment by kostrse** [comment]
```
A common approach I've found is to use service discovery feature of Service Fabric. When node starts, it looks in service discovery for another service (akka cluster node) and it's IP. If it has not been found, it then registers itself and starts as a cluster seed node. Otherwise it joins an existing one. On graceful shutdown it unregisters itself.
```

Agree, but here is a problem that when you have several seed nodes, and you're starting them simultaneously (when you're starting a Service Fabric application, services being started  all nodes at the same time), they all will receive from the Naming Service that no seed nodes registered, and each of them will assume that they are alone and form independent clusters.

There's no *transactional* consistency in Naming Service to prevent it.

If is possible to manually babysit deployment of seed nodes, manually installing them one by one... increasing availability to a node after node... So they not compete.

But not very clear how to make a reliable and reusable solution out of it.

**Comment by Horusiath** [comment]
@kostrse this is not really an issue, it has been solved in multiple systems already. The simplest (and working) way is to introduce a random pause for each service before it tries to join to the cluster i.e. `TimeSpan.FromMilliseconds(random.Next(x) * y)` where `x` depends on the number of nodes trying to simultaneously join the cluster (the more nodes, the higher upper bound is necessary) and `y` depends on the average time necessary for coordinator (in this case service discovery provider) to respond.
