### ISSUE TITLE
Akka.net persistence actor doesn't get connection string from Fallback Config?

### ISSUE THREAD

**Issue by amalshalika** [akkadotnet/akka.net#2565]
I have my main hocon config in app.config file and try to set connection string from code behind using fallback config. but when actor system start it doesn't working. here is my hocon config and C# code as below.

Hocon config i have comment out connnection-string to take it from fallback config
akka.persistence {
              
              journal {
                plugin = "akka.persistence.journal.sql-server"                
                sql-server {
                      class = "Akka.Persistence.SqlServer.Journal.SqlServerJournal, Akka.Persistence.SqlServer"
                      plugin-dispatcher = "akka.actor.default-dispatcher"

                      # connection string used for database access
                      # connection-string = "Data Source=ES-NB-046\\MSSQLSERVER_2014;Initial Catalog=PSAkka;User ID=sa;Password=1qaz2wsx@;"
                      # can alternativly specify: connection-string-name

                      # default SQL timeout
                      connection-timeout = 30s

                      # SQL server schema name
                      schema-name = dbo

                      # persistent journal table name
                      table-name = EventJournal

                      # initialize journal table automatically
                      auto-initialize = on

                      timestamp-provider = "Akka.Persistence.Sql.Common.Journal.DefaultTimestampProvider, Akka.Persistence.Sql.Common"
                      metadata-table-name = Metadata
                }
              }

C# code behind file

 static void Main(string[] args)
        {

            var mainConfig = ConfigurationFactory.Load();

            string connectionString = @"akka.persistence.journal.sql-server.connection-string = ""Data Source=Data Source=ES-NB-046\\MSSQLSERVER_2014;Initial Catalog=PSAkka;User ID=sa;Password=1qaz2wsx@;""";
            //string text1 = @"akka.persistence.journal.sql-server.abc = ""Data Source=Data Source=ES-NB-046\\MSSQLSERVER_2014;Initial Catalog=PSAkka;User ID=sa;Password=1qaz2wsx@;""";

            var conStringConfig = ConfigurationFactory.ParseString(connectionString);

            mainConfig = mainConfig.WithFallback(conStringConfig);

            System = ActorSystem.Create("Game", mainConfig);

            PlayerCoordinator = System.ActorOf<PlayerCoordinatorActor>("PlayerCoordinator");

**Comment by Horusiath** [comment]
Have you tried to reverse `mainConfig.WithFallback(conStringConfig)` to `conStringConfig.WithFallback(mainConfig)`?

**Comment by amalshalika** [comment]
Yes i did it also but not work

**Comment by Horusiath** [comment]
What error did you get exactly? May it be malformed connection string? (the one you've shown in your snipped probably is)

Optionally if you want to load connection string from <connectionStrings /> *.config section you may use `connection-string-name`.

**Comment by amalshalika** [comment]
Actually error i am getting is 

[ERROR][3/22/2017 8:29:43 AM][Thread 0006][[akka://Game/user/PlayerCoordinator#1256963396]] Persistence failure when replaying events for persistenceId [player-coordinator]. Last known sequence number [0] Cause: Akka.Persistence.RecoveryTimedOutException: Recovery timed out, didn't get event within 30s, highest sequence number seen 0.

connection string load from config file is working fine. as you can see I was comment out that one because i have a requirement of setting it from C# code behind just before actor system initialize. I just comment connection-string key from config file and instead used fallback config with same key and same connection string values. but it doesn't load and unable to replay message and deliver

**Comment by amalshalika** [comment]
Yes connection is malformed. it is my fault once it corrected work fine thanks for help me
