### ISSUE TITLE
Invalid reference to System.Collections.Immutable

### ISSUE THREAD

**Issue by AndreyAkinshin** [akkadotnet/akka.net#2572]
There are following lines in the `StreamsExamples.csproj` file:
```xml
<Reference Include="System.Collections.Immutable, Version=1.1.36.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
  <HintPath>..\..\..\packages\System.Collections.Immutable.1.1.36\lib\portable-net45+win8+wp8+wpa81\System.Collections.Immutable.dll</HintPath>
  <Private>True</Private>
</Reference>
```
However, the corresponded `packages.config` doesn't include reference to `System.Collections.Immutable`. Also there is no reference to `System.Collections.Immutable.1.1.36` in other projects (only version `1.3.1` is used). Thus, we don't have the `..\..\..\packages\System.Collections.Immutable.1.1.36\lib\portable-net45+win8+wp8+wpa81\System.Collections.Immutable.dll` file after NuGet restore.

**Comment by Aaronontheweb** [comment]
@AndreyAkinshin thanks, we'll get this fixed. This is in the latest source I take it?

**Comment by AndreyAkinshin** [comment]
Yep, the `dev` branch: https://github.com/akkadotnet/akka.net/blob/dev/src/examples/Streams/StreamsExamples/StreamsExamples.csproj#L40
