### ISSUE TITLE
Port Akka MultiJVM Tests

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#258]
http://doc.akka.io/docs/akka/snapshot/dev/multi-jvm-testing.html

A number of the bugs that have been reported by Akka.NET end-users lately have been of the "behavior in one or more remote actors systems is not as expected" variety. That's ultimately good news, because it means our users are working towards realistic Akka.NET production scenarios that involve multiple machines. Yay!

However, I think the project's at a point now where it's worth expending some effort to recreate some of Akka's MultiJVM tests - these are essentially remote actor system integration tests.

I came up with a very simple structure for doing this inside Helios that I'm pretty happy with: 

https://github.com/Aaronontheweb/helios/blob/master/tests/Helios.MultiNodeTests/TestKit/MultiNodeTest.cs (base class)
https://github.com/Aaronontheweb/helios/blob/master/tests/Helios.MultiNodeTests/LargeMessageTests.cs (concrete test case)

I think we could do something similar to this that leverages parts of the existing Akka.TestKit.

I've been in communication with @smalldave about helping him implement Akka.Cluster, which is the next big thing on my company needs to scale our usage of Akka.NET. As part of working on that initiative, I'd like to kick off a port of the MultiJVM tests too.

Any ideas or suggestions for how best to implement this?

**Comment by smalldave** [comment]
@Aaronontheweb anything you want to do on this or should it be closed?

**Comment by Aaronontheweb** [comment]
We can close it - I think we both know which tests need to be ported :p
