### ISSUE TITLE
intervalSum must be >= 0, got -2146468163

### ISSUE THREAD

**Issue by kostrse** [akkadotnet/akka.net#2581]
Got this exception in logs from two Lighthouse instances:

Exception message:
```
intervalSum must be >= 0, got -2146468163
Parameter name: intervalSum
```
Source: `akka://FooBar/system/cluster/core/daemon/heartbeatSender`

Looks like some counter overlapped.
Don't know yet, is it harmless or not, keeping for records for now.

Akka 1.1.3

**Comment by Aaronontheweb** [comment]
Interesting, looks like this is an issue with the `PhiAccrualFailureDetector`

**Comment by Aaronontheweb** [comment]
Yeah, looks like there's some sort of math issue where a value that's deducted from the `intervalSum` on `DropOldest` is greater than the sum of the parts, which shouldn't be able to happen... That's more likely the issue than an `overflow` (which would throw a different type of exception.)

I think I can reproduce this.

**Comment by Aaronontheweb** [comment]
This looks like the culprit to me:

```
/// <summary>
        /// The default clock implementation used by the <see cref="PhiAccrualFailureDetector"/>
        /// </summary>
        /// <returns>A clock instance.</returns>
        /// <remarks>
        /// Fixed: sign will no longer flip, but the tickcount will go back down to zero every 24.9 days 
        /// </remarks>
        public static readonly Clock DefaultClock = () => Environment.TickCount & Int32.MaxValue;
```

It's possible that when a system has been running in production for some time (~25 days or so) when we start dropping older intervals from the range of memorized values that we can slip into territory where the `intervalSum` will be reported as negative.

**Comment by Aaronontheweb** [comment]
Hmmm... tested with a non-monotonic counter and it looks like it's still working fine...

**Comment by Aaronontheweb** [comment]
Ok, got my reproduction failure working now:

```
// handle an edge case when the Clock rolls over
        // see https://github.com/akkadotnet/akka.net/issues/2581
        [Fact]
        public void PhiAccrualHistory_can_roll_over()
        {
            unchecked
            {
                var absoluteTimes = new List<long>
                {
                    (Int32.MaxValue - 300) & Int32.MaxValue,
                    (Int32.MaxValue - 200) & Int32.MaxValue,
                    (Int32.MaxValue - 100) & Int32.MaxValue,
                    (Int32.MaxValue)  & Int32.MaxValue,
                    (Int32.MaxValue + 100)  & Int32.MaxValue,
                    (Int32.MaxValue + 200)  & Int32.MaxValue,
                    (Int32.MaxValue + 300)  & Int32.MaxValue,
                };

                // compute intervals
                var timeIntervals = new List<long>();

                for (var i = 0; i < absoluteTimes.Count-1; i++)
                {
                    timeIntervals.Add(absoluteTimes[i+1] - absoluteTimes[i]);
                }

                var fd =
                    FailureDetectorSpecHelpers.CreateFailureDetector(
                        FailureDetectorSpecHelpers.FakeTimeGenerator(timeIntervals));
                foreach (var i in timeIntervals)
                {
                    fd.HeartBeat();
                    Assert.True(fd.IsAvailable);
                }
            }
```

Fails with a similar error message to this one.

**Comment by Aaronontheweb** [comment]
Oh man, so this was a stupid issue....

Problem was caused by the fact that the intervals we report are 64 bit, but the clock calculation function was 32bit:

```
public static readonly Clock DefaultClock = () => Environment.TickCount & Int32.MaxValue;
```

When a rollover happens here, you just get a giant negative value back when you calculate the next interval.

Changed this clock function to just use the `MonotonicClock` instead, and that will roll over at 25^32 days, so basically never. Even if it did, modified this test to make sure that the math still works. Sending in a PR now.

**Comment by kostrse** [comment]
Awesome 😃

**Comment by garrardkitchen** [comment]
@Aaronontheweb @alexvaluyskiy @kostrse  If it helps, I can confirm that this issue has been observed in version 1.0.8.24.
