### ISSUE TITLE
HOCON parser from the NuGet library

### ISSUE THREAD

**Issue by kostrse** [akkadotnet/akka.net#2586]
Do we have any plans to reference HOCON NuGet package rather than using bundled HOCON parser from `/src/core/Akka/Configuration/Hocon` ?

It probably would be much easier to maintain and evolve it as an independent and self-sufficient library.

Moving forward, frankly, I would even want from core Akka library to not know about HOCON anything at all. The configuration interface could be completely abstract and pluggable.
HOCON could be just a default and officially supported configuration provider.

There are many different use cases how could you manage your application configuration depending on your hosting environment, and core Akka should be abstracted from all of them.

For example, while hosting Akka inside of Service Fabric, it would be convenient to supply environment-specific variables to HOCON configuration file from Service Fabric configuration package. It could be easily done, if configuration providers would be pluggable.

**Comment by slorion** [comment]
Recently I started working on a big modernization project on .NET Core and I was thinking of using HOCON. Today, seeing that the nuget package only targets net45, I went to the repo only to see it is basically dead and that HOCON is still integrated into Akka.Core. This is frankly a bit saddening ...

**Comment by Danthar** [comment]
@slorion Yes the repo hasn't been updated in a while. But having said that. There hasn't been any large changes in the meantime. We made some perf improvements. But thats it.
So it _is_ very usable.
If you want to use it in your project, but want it to target a higher .net version. We accept PR's :)

@kostrse I don't see us creating an configuration abstraction in akka.net any time soon. For us, it would be a non trivial amount of work, for little gain. Akka.net is very dependant on the specific features HOCON offers. 
In your example about Service Fabric, sound to me you could solve that with config-transforms in combination with a custom integration that generates your HOCON upon start/deployment.
But those are my 2ct's im not sure how the others thing about this.

**Comment by slorion** [comment]
@Danthar With .NET moving so fast, I totally understand HOCON nuget not being ported yet as it is low priority. What I find surprising is that HOCON code is duplicated and updates are made here and not in the "official" package repo. Say I go ahead and port Akka.Hocon to .NET Core, what will happen with the implementation inside Akka.Core ? As @kostrse suggests,

> It probably would be much easier to maintain and evolve it as an independent and self-sufficient library.

**Comment by slorion** [comment]
@sean-gilliam Are you closing this issue as done or wont-fix ? I looked at the repo but did not see any related commit. No pressure intended, just would like a current status. Thanks!

**Comment by sean-gilliam** [comment]
Basically wont-fix. It would place an undue dependency on the main akka.net package for little gain. We like our packages to be as self-contained as possible.

It was broken out because some people were asking for it. Like @Danthar mentioned, please feel free to send PRs if you'd like to enhance the package though.

**Comment by slorion** [comment]
Ah, I'm not sure I am following you .. Are you talking about a dependency from HOCON to the main library ? If so, I totally agree and I would even say it makes no sense, it should be the other way around. The akka-config from Akka does not even depend on scala-library. 

As for making a PR, any idea what is required to make the main library depends on HOCON ? Any blockers ?
