### ISSUE TITLE
Issues found by PVS-Studio

### ISSUE THREAD

**Issue by VasilievSerg** [akkadotnet/akka.net#2588]
Hello,
I have found a few bugs using PVS-Studio analyzer. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

Analyzer warnings:
- V3010 The return value of function 'Reverse' is required to be utilized. PersistentFSMBase.cs 511
[A link to the source code.](https://github.com/akkadotnet/akka.net/blob/17d5dfdbcebd9c47ff5aec767cb25f099bdefd1b/src/core/Akka.Persistence/Fsm/PersistentFSMBase.cs#L511)
- V3010 The return value of function 'Reverse' is required to be utilized. PersistentFSMBase.cs 532
[A link to the source code.](https://github.com/akkadotnet/akka.net/blob/17d5dfdbcebd9c47ff5aec767cb25f099bdefd1b/src/core/Akka.Persistence/Fsm/PersistentFSMBase.cs#L532)
- V3095 The 'youngerData.Oldest' object was used before it was verified against null. Check lines: 711, 712. ClusterSingletonManager.cs 711
[A link to the source code.](https://github.com/akkadotnet/akka.net/blob/17d5dfdbcebd9c47ff5aec767cb25f099bdefd1b/src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs#L711)
- V3095 The 'becomingOldest.PreviousOldest' object was used before it was verified against null. Check lines: 850, 851. ClusterSingletonManager.cs 850
[A link to the source code.](https://github.com/akkadotnet/akka.net/blob/17d5dfdbcebd9c47ff5aec767cb25f099bdefd1b/src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs#L850)

In addition, I suggest having a look at the emails, sent from @pvs-studio.com. 

Best regards, 
Sergey Vasiliev

**Comment by sean-gilliam** [comment]
that's really weird. i thought one of @alexvaluyskiy PRs fixed the first two items.

anyways this

```csharp
var replies = upcomingState.Replies;
replies.Reverse();
foreach (var reply in replies)
{
	Sender.Tell(reply);
}
```

should be replaced with

```csharp
for (int i = upcomingState.Replies.Count - 1; i >= 0; i--)
{
    Sender.Tell(upcomingState.Replies[i]);
}
```

the last two could probably use a bit of null propagation/coalescing


thanks @VasilievSerg for pointing these out :+1:

**Comment by alexvaluyskiy** [comment]
@sean-gilliam I've fixed it only in `FSM`, not in `PersistenceFSM`. I will fix it later

**Comment by Szer** [comment]
This one should be closed. PR has been merged in upstream
