### ISSUE TITLE
Issue running unit tests on Debian CI builds using Mono

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2589]
We've noticed some test failures running unit tests on Mono in our CI system.  The test failures are inconsistent, with tests failing that have not failed in a long time and likely shouldn't fail.

We're seeing the build logs throwing this error, `W: Conflicting distribution: http://download.mono-project.com wheezy/snapshots/4.6.2.16 InRelease (expected wheezy/snapshots but got wheezy)` which might hint at a root cause in our Docker-based CI, but we're still investigating.

Mostly a heads up to contributors that this seems to be more of an infrastructure issue and we're addressing it.

**Comment by Aaronontheweb** [comment]
@heynickc didn't we determine that this wasn't an issue after all?

**Comment by heynickc** [comment]
We didn't confirm that it was or wasn't.  We don't have a root cause still, but at the time I put this issue in that was one an error noticed in the logs.

**Comment by heynickc** [comment]
@Aaronontheweb I see now what you were asking - whether this entire issue *was in fact an issue.  The test failures are still prevalent, but I'm not sure this is an infrastructure issue.  Maybe a Mono-specific issue but really there's no clear root cause.

**Comment by alexvaluyskiy** [comment]
Right now we have completely different CI. It is not an issue anymore
