### ISSUE TITLE
Backport changes from Streams 2.4.14

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2600]
## 2.4.14 (29.10.2016 - 18.11.2016)

- [x] - [FlattenMerge should propagate outer attributes](https://github.com/akka/akka/pull/21805)
- [ ] - [Move compression tests over from akka-http + fix for ByteStringParser](https://github.com/akka/akka/pull/21872)
- [ ] - [Move (de)compression helpers to akka-stream module ](https://github.com/akka/akka/pull/21409)
- [ ] - [Failing tcp spec fix](https://github.com/akka/akka/pull/21685)
- [x] - [expose `within` for both TestSubscriber and TestPublisher](https://github.com/akka/akka/pull/21851)
- [ ] - [Fix ByteStringParser backpressure](https://github.com/akka/akka/pull/21853)
- [x] - [Correct errors from InputStreamSinkStage when first read times out](https://github.com/akka/akka/pull/21821)
- [x] - [Fix race in BroadcastHub shutdown and new registrations](https://github.com/akka/akka/pull/21855)
- [x] - [use SimpleLinearGraphStage to reduce the boilerplate code](https://github.com/akka/akka/pull/21829)
- [x] - [rewrite Buffer as a GraphStage](https://github.com/akka/akka/pull/21635)
- [x] - [Fixed error handling behaviour of Fold and Reduce](https://github.com/akka/akka/pull/21797)
- [ ] - [Close Tls connection if Inbound closed before receiving peer's close_notify](https://github.com/akka/akka/pull/21786)
- [ ] - [foldAsync test using mapAsync](https://github.com/akka/akka/pull/21720)
- [ ] - [move compression tests](https://github.com/akka/akka/pull/21876)

**Comment by alexvaluyskiy** [comment]
@Silv3rcircl3 We could move all tasks related to compression into a separate issue. We don't have Http and maybe this task is not too important for us at the moment. What do you think?

**Comment by Silv3rcircl3** [comment]
@alexvaluyskiy I agree, we don't even have the `ByteStringParser` stage, so we would need to port it first but I think that isn't necessary until we start with akka http.

**Comment by Silv3rcircl3** [comment]
@Horusiath have you already fixed [Failing tcp spec fix](https://github.com/akka/akka/pull/21685) in your branch?
