### ISSUE TITLE
Backport changes from Streams 2.5.5

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2601]
## 2.4.16 (19.11.2016 - 20.12.2016)

- [x] - [fix SourceQueue docs inconsistencies](https://github.com/akka/akka/pull/21877)
- [x] - [Fixed the case when identity flow appended to Source combining materialized values](https://github.com/akka/akka/pull/21956)
- [x] - [less noisy logging of idle-timeout (for akka-http specifically](https://github.com/akka/akka/pull/21989)
- [x] - [asOutput stream close race](https://github.com/akka/akka/pull/21896)
- [x] - [InputStream from StreamConverters.asInputStream respects read() contract](https://github.com/akka/akka/pull/21954)
- [x] - [Fix handling of escape sequences in JsonObjectParser](https://github.com/akka/akka/pull/21975)
- [x] - [add note on (non)guarantees of materializer SPI](https://github.com/akka/akka/pull/21935)
- [x] - [Lazy source](https://github.com/akka/akka/pull/21081)
- [x] - [Tree flattening should be separate from Fusing](https://github.com/kkasravi/akka/commit/73ed75a66967ca3692b9ed86775d7d81b54feb4e)
- [x] - [Fixed the bug in Attributes.getFirst(default : T)](https://github.com/akka/akka/pull/21846)

## 2.4.17 (21.12.2016 - 10.02.2016)
- [x] [add Java API for NegotiateNewSession](https://github.com/akka/akka/pull/22280)
- [x] [fix typo in GraphStage port validations](https://github.com/akka/akka/pull/22062)

## 2.4.18
- [x] [fixed corruption of ordering in MergePreferred caused by using emit](https://github.com/akka/akka/pull/22569)
- [x] [Fail all stages on abrupt termination](https://github.com/akka/akka/pull/22809)
- [x] [Truncated contents in existing files for FileIO.toPath/toFile](https://github.com/akka/akka/pull/22807)
- [x] [Make viaMat on identity Flow preserve upstreams/downstreams](https://github.com/akka/akka/pull/22649)
- [x] [ClassCastException in SubSink](https://github.com/akka/akka/pull/22567)
- [x] [Fail framing for negative frame sizes](https://github.com/akka/akka/pull/22562)
~- [Failed: CompressionIntegrationSpec](https://github.com/akka/akka/pull/22557)~ Artery spec
- [x] [GroupedWithin cold emit fix](https://github.com/akka/akka/pull/22555)
- [x] [rewrite Source.empty to GraphStage](https://github.com/akka/akka/pull/22479)
- [x] [Fix invalid ranges in ByteStringSpec](https://github.com/akka/akka/pull/22392)
~~[Close Java Stream after completion](https://github.com/akka/akka/pull/22307)~~ Only relevant for Java
~~[fix FileIO parameter type to OpenOptions](https://github.com/akka/akka/pull/22770)~~ Only relevant for JVM

those three are ported in #2737
- [Don't leak sub flows when mat fails](https://github.com/akka/akka/pull/22647)
- [Add startPosition option for FileIO API](https://github.com/akka/akka/pull/22657)
- [Lazy sink wait for init](https://github.com/akka/akka/pull/22033)

**Comment by alexvaluyskiy** [comment]
Fixed https://github.com/akkadotnet/akka.net/pull/2710 and https://github.com/akkadotnet/akka.net/pull/2737

**Comment by Silv3rcircl3** [comment]
Not done yet, I still need to port some parts for 2.4.18

**Comment by Silv3rcircl3** [comment]
@alexvaluyskiy yup working on it tomorrow

**Comment by Aaronontheweb** [comment]
@Silv3rcircl3 is this finished?

**Comment by Silv3rcircl3** [comment]
@aaronontheweb not yet, but hopefully in a few hours, definitely by end of the weekend

**Comment by Silv3rcircl3** [comment]
more to do than expected, will take another few days, but nothing that needs to be in 1.3.

**Comment by alexvaluyskiy** [comment]
## Akka.Streams 2.5.0
- [create StreamConverters form java.util.stream.Stream](https://github.com/akka/akka/issues/19443)
- [Make NoMaterializer public, so Play does not have to reimplement it](https://github.com/akka/akka/issues/21926)
- [Fix incorrect materialized types = Unit in stream documentation](https://github.com/akka/akka/pull/21938)
- [FAILED: OutputStreamSourceSpec](https://github.com/akka/akka/issues/20737)
- [asOutput stream close race](https://github.com/akka/akka/pull/21896)
- [splitAfter should not emit additional empty substream if last element matches](https://github.com/akka/akka/issues/20448)
- [less noisy logging of idle-timeout (for akka-http specifically)](https://github.com/akka/akka/issues/22005)
- [-str #21423 remove deprecated Stage references](https://github.com/akka/akka/pull/21919)
- [JsonObjectParser doesn't handle escape sequences properly](https://github.com/akka/akka/issues/21961)
- [Flow.fromSinkAndSource with "attached" cancelation/completion](https://github.com/akka/akka/issues/22297)
- [WebSockets provide a way to Flow.fromSinkAndSourceBoundCompletion()](https://github.com/akka/akka/issues/21549)
- [FAILED akka.stream.io.TcpSpec](https://github.com/akka/akka/issues/21903)
- [Lazy sink wait for init](https://github.com/akka/akka/pull/22033)
- [stream: GC: remove iterators in Graph.scala/Broadcast...onPush...tryPull](https://github.com/akka/akka/issues/22113)
- [Missing API: expectNextPF doesn't take a timeout](https://github.com/akka/akka/issues/21314)
- (Mat) [Make inputBuffer attributes work again](https://github.com/akka/akka/issues/22424)
- (Mat) [Make FlowSpec work again](https://github.com/akka/akka/issues/22435)
- (Mat) [Fix actor creation to be the same (or close) to the old one](https://github.com/akka/akka/issues/22426)
- (Mat) [Make dispatchers and async work again](https://github.com/akka/akka/issues/22428)
- [Rewrite Source.empty to GraphStage](https://github.com/akka/akka/issues/22448)
- (Mat) [Fix low level interpreter tests](https://github.com/akka/akka/issues/22423)
- (Mat) [Implement subfusing](https://github.com/akka/akka/issues/22425)
- (Mat) [Failing tests for new materializer](https://github.com/akka/akka/issues/22463)
- (Mat) [Implement missing Phases (most likely only TLS)](https://github.com/akka/akka/issues/22430)
- (Mat) [Use OptionVals where makes sense](https://github.com/akka/akka/issues/22438)
- (Mat) [Eliminate `require` calls](https://github.com/akka/akka/issues/22437)
- (Mat) [speedup island name creation](https://github.com/akka/akka/issues/22493)
- (Mat) [Investigate attributes semantics](https://github.com/akka/akka/issues/22436)
- (Mat) [Restore debug statements in `ActorGraphInterpreter` and `GraphInterpreter`](https://github.com/akka/akka/issues/22433)
- (Mat) [Improve performance and design of the materializer](https://github.com/akka/akka/issues/22387
- (Mat) [Remove inOwnerId and outOwnerId from Connection](https://github.com/akka/akka/issues/22447)
- (Mat) [Review the materializer's and the GraphStagePhase's uses of arrays (ArrayList, ArrayDeque, etc)](https://github.com/akka/akka/issues/22429)
- (Mat) [Harden layout classes error handling](https://github.com/akka/akka/issues/22432)
- [fixed corruption of ordering in MergePreferred](https://github.com/akka/akka/pull/22480)
- [NPE in GraphInterpreter when `GraphStageLogic` never called `setHandler`](https://github.com/akka/akka/issues/22552)
- (Mat) [Deprecate the auto-fusing configuration](https://github.com/akka/akka/issues/22431)
- [JavaDSL [SubFlow/SubSource].zip emitting wrong Pair type](https://github.com/akka/akka/issues/22527)
- (Mat) [make stream impl internal](https://github.com/akka/akka/issues/22506)
- [Source that flattens a Future[Source] but keeps the materialized value](https://github.com/akka/akka/issues/22359)
- [FAILED: TlsSpec](https://github.com/akka/akka/issues/22124)
- [FAILED: TlsSpec](https://github.com/akka/akka/issues/20368)
- [short path for Source.fromFuture and fromFutureSource](https://github.com/akka/akka/issues/22602)
- [FAILED: FlowLogSpec](https://github.com/akka/akka/issues/22128)
- [GraphInterpreter leak when a submaterialized flow throws during materialization](https://github.com/akka/akka/issues/22358)
- [Stream.delay can leave some elements in the buffer indefinitely](https://github.com/akka/akka/issues/22416)

**Comment by alexvaluyskiy** [comment]
## Akka.Streams 2.5.1
- [startPosition option for FileIO.fromFile](https://github.com/akka/akka/issues/19483)
- [Make FileSource extensible again, via OpenOption instead StandardOpenOption](https://github.com/akka/akka/issues/22666)
- [FAILED: akka.stream.io.TcpSpec](https://github.com/akka/akka/issues/22503)
- [Unignore and rewrite Java DSL tests to use GraphStage](https://github.com/akka/akka/issues/18863)
- [Docs for Sink.last(Option) are wrong about failure](https://github.com/akka/akka/issues/22691)
- [Consider adding a GroupedWeightedWithin stage](https://github.com/akka/akka/issues/22711)

**Comment by alexvaluyskiy** [comment]
## Akka.Streams 2.5.2
- [CoupledTerminationFlow should take Graph[Sink...] etc](https://github.com/akka/akka/issues/22808)

## Akka.Streams 2.5.3
- [Documentation of the new materializer system](https://github.com/akka/akka/pull/22699)
- [=str break out a few source implementations into separate files](https://github.com/akka/akka/pull/23110)
- [Docs for Source.queue incorrectly state that the materialized source is for single thread usage only](https://github.com/akka/akka/issues/23081)
- [RecoverWith should recover for maximumRetries == 0](https://github.com/akka/akka/issues/22917)

**Comment by alexvaluyskiy** [comment]
## Akka.Streams 2.5.4
- [Contradictory documentation on backpressure for throttle methods](https://github.com/akka/akka/issues/22791)
- [Can merging of multiple sources be prioritized?](https://github.com/akka/akka/issues/22865)
- [SourceQueue.watchCompletion scaladoc is misleading](https://github.com/akka/akka/issues/23119)
- [Inaccurate documentation on Flow.fromSinkAndSource](https://github.com/akka/akka/issues/23274)
- [JsonObjectParser fails on escape sequence \"C:\\\"](https://github.com/akka/akka/issues/23280)
- [Rewrite MaybeSource as a GraphStage](https://github.com/akka/akka/issues/22789)
- [LengthFieldFramingStage decrement length by offset bytes](https://github.com/akka/akka/issues/22129)
- [Unzip class in Graph.scala has incorrect documentation](https://github.com/akka/akka/issues/23333)
- [Increase stream tck test timeouts](https://github.com/akka/akka/issues/20241)
- [QueueSource does not complete onComplete future on abrupt termination](https://github.com/akka/akka/issues/23118)
- [Restartable Flow, Source and Sink](https://github.com/akka/akka/issues/19950)
- [Docs: Improve `TwitterStreamQuickstartDocSpec` fiddle code](https://github.com/akka/akka/issues/23435)
- [Inaccurate documentation on StreamConverters.fromInputStream](https://github.com/akka/akka/issues/23165)
- [SelectionHandler may keep references to connection ActorRefs which in turn may keep whole GraphStages alive](https://github.com/akka/akka/issues/23437)
- [Document what stages implement supervision](https://github.com/akka/akka/issues/23376)
- [Obsolete documentation for ExtendedActorMaterializer](https://github.com/akka/akka/issues/23385)
- [groupedWeightedWithin can't handle zero weight cost function](https://github.com/akka/akka/issues/23398)
- [Streams: InputStreamSink is blocked when used mapMaterializedValue](https://github.com/akka/akka/issues/23187)
- [Invalid stack trace because reused exception code is defined as val](https://github.com/akka/akka/issues/23416)
- [Add BalancingHub stream elements](https://github.com/akka/akka/issues/21880)

**Comment by alexvaluyskiy** [comment]
## Akka.Streams 2.5.5
- [Failed: akka.stream.scaladsl.RestartSpec](https://github.com/akka/akka/issues/23484)
- [[Docs] Streams "Working with streaming IO" has broken snippet](https://github.com/akka/akka/issues/23513)
- [materializedValue of GraphDSL.Builder emits unexpected value](https://github.com/akka/akka/issues/23577)

**Comment by Aaronontheweb** [comment]
@marcpiechura @alexvaluyskiy just reviewing this now as I get ready to document some more Akka.Streams issues - was all of this implemented or are the things in blue still in need of being implemented?
