### ISSUE TITLE
Akka.DI.Autofac Actor creation delay

### ISSUE THREAD

**Issue by donamk** [akkadotnet/akka.net#2631]
I create some actors followed by the document(http://getakka.net/docs/Dependency%20injection)
However, cannot deliver a message to child actor using system.ActorSelection().

```
[INFO][24/04/2017 1:50:11 AM][Thread 0006][akka://DiTestSystem/user/Manager1/Worker1] Message String from akka://DiTestSystem/deadLetters to akka://DiTestSystem/user/Manager1/Worker1 was not delivered. 1 dead letters encountered. 
```

The only way I found to solve this issue is using Thread.Sleep().

Why this things happen? and how can I create an actor without DI delay creation?

```
public class Worker: ReceiveActor
{
    public Worker()
    {
        Receive<string>(m => Console.WriteLine("Worker is working"));
    }
}
    
public class WorkerManager : ReceiveActor
{
    public WorkerManager()
    {
        Receive<string>(m => Console.WriteLine("Manager start supervise"));
    }
    
    protected override void PreStart()
    {
        Context.ActorOf(Context.DI().Props<Worker>(), "Worker1");
    }
}
        
class Program
{
    static void Main(string[] args)
    {
        ContainerBuilder builder = new ContainerBuilder();
        builder.RegisterType<WorkerManager>();
        builder.RegisterType<Worker>();
            
        var system = ActorSystem.Create("DiTestSystem");

        IContainer container = builder.Build();
        IDependencyResolver resolver = new AutoFacDependencyResolver(container, system);

        var manageRef = system.ActorOf(system.DI().Props<WorkerManager>(), "Manager1");

        Thread.Sleep(30); // ADDED THIS LINE
        manageRef.Tell("Hello");
        system.ActorSelection("/user/Manager1/Worker1").Tell("Hello");

        Console.ReadLine();
    }
}
```

**Comment by Szer** [comment]
That is not Autofac problem because there is race condition between PreStart in your WorkerManager and ActorSelection.Tell()
You should redesign your code to initialize manager properly (in constructor for example or make it switch behaviour between Uninitialized and Initialized phase with Become).

**Comment by donamk** [comment]
@Szer Thank you for teach me there is race condition.  However, I test Worker1 create code , Context.ActorOf(Context.DI().Props<Worker>(), "Worker1"), move into Manager1 constructor, it still same as my original code. It is not solve the race condition.

I know how to switch behvaiour but I still hard to understand to solve problem with swtich behaviours. Could you show me code?

**Comment by Danthar** [comment]
The race condition does not go away when you move the `Context.ActorOf(Context.DI().Props<Worker>(), "Worker1");` to the constructor.

Actors run "on their own thread", this means that if you create an actor using `sys.ActorOf` or `Context.ActorOf`. If that method returns, the only thing you can sure of, is that a name has been reserved for it, in the actor hierarchy, and that its mailbox is available.
However that does not have to mean that the actor is fully started.
If you call `actorRef.Tell` immediately after, then the message will be queued in the actors mailbox until it is ready to process it. So in short, the `Tell` on an `ActorRef` allows you to send a message to an actor that does not fully **exist** yet.

If you use an ActorSelection however. That works differently. Read http://getakka.net/docs/concepts/addressing for more information

**Comment by donamk** [comment]
@Danthar Thank you for your explanation. I think I understand.
