### ISSUE TITLE
General Questions about Akka

### ISSUE THREAD

**Issue by jt4000** [akkadotnet/akka.net#2648]
Hello, I'm newbie in Akka and I got some questions.
1.
What is Akka?

2.
What benefit can I use Akka?

3.
What business value or technical value can Akka provide?

Thank you!

**Comment by Danthar** [comment]
Go read the docs? http://getakka.net/docs/

**Comment by sean-gilliam** [comment]
Please direct non-issue related questions to our gitter channel https://gitter.im/akkadotnet/akka.net
