### ISSUE TITLE
Actor implementing IWithUnboundedStash could not use custom priority mailbox

### ISSUE THREAD

**Issue by zdjohn** [akkadotnet/akka.net#2649]
After upgrade to 1.2 from 1.0
i noticed if actor is using stash, whenever i try to use custom mailbox type. I got exception:

`ArgumentException: produced message queue type of [Akka.Dispatch.MessageQueues.UnboundedPriorityMessageQueue] does not fulfill requirement for actor class [xxx.ReceiverActor].Must be a subclass of [Akka.Dispatch.MessageQueues.IMessageQueue]
`

However if i use either of them, it compiles and works as expected:
i.e.:
Actor uses priority mailbox without implementing IWithUnboundedStash. 
Or. Actors implementing IWithUnboundedStash without using priority mailbox.

**Comment by jaydeboer** [comment]
We are having the same issue adding a custom mailbox to persistent actors as well.   Any ETA on a fix?

**Comment by Aaronontheweb** [comment]
@jaydeboer I'll take a look at this. Thanks for bringing it back up. I'll see if we can get this fixed in 1.3

**Comment by Aaronontheweb** [comment]
(due out later this week)

**Comment by Danthar** [comment]
For reference offending line of code: 
https://github.com/akkadotnet/akka.net/blob/v1.3/src/core/Akka/Dispatch/Mailboxes.cs#L285

Ill try to reproduce this using the default docs for this stuff: http://getakka.net/docs/working-with-actors/Mailbox#configuring-custom-mailboxes

**Comment by Danthar** [comment]
Confirmed bug. Once you add the `IWithUnboundedStash` interface to your actor. It adds an extra requirement to the mailbox type, namely the `IUnboundedDequeBasedMessageQueueSemantics`. Which is not supported by the `UnboundedPriorityMailbox`. Or technically the `UnboundedPriorityMessageQueue` which is used by the mailbox. 

The message being given is wrong as it communicates the wrong subclass type.
Working on a fix for both.

**Comment by Danthar** [comment]
To be clear. Adding stashing support for prioritymailbox. Does add some odd behavior. Which we will be providing some docs on.
We dont recommend using stashing in combination with the prioritymailbox. But at least now, it wont throw an exception in your face if you do 📦
