### ISSUE TITLE
Add info about akka-netcore to akka docs (in nightly-builds section)

### ISSUE THREAD

**Issue by siudeks** [akkadotnet/akka.net#2657]
It could be useful to find in akka documentation info about **akka-netcore** binaries available currently at https://www.myget.org/F/akka-netcore/api/v3/index.json. I think location http://getakka.net/docs/akka-developers/nightly-builds is the best place for that.

**Comment by alexvaluyskiy** [comment]
Done https://github.com/akkadotnet/getakka.net/pull/247
