### ISSUE TITLE
Rewrite "Scheduler` article in the documentation

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2671]
The "Scheduler" article is outdated and consists examples from pre1.0 versions
http://akkanetdocfx.azurewebsites.net/articles/utilities/scheduler.html

Original article: http://doc.akka.io/docs/akka/2.5/scala/scheduler.html

**Comment by Danthar** [comment]
So im not sure why. But the site http://akkanetdocfx.azurewebsites.net/articles/utilities/scheduler.html isnt updated. So either CI is busted, or i updated the wrong doc (?)

**Comment by sean-gilliam** [comment]
IIRC @alexvaluyskiy was doing a manual push since CI isn't set up for that site yet.

**Comment by Aaronontheweb** [comment]
@Danthar @sean-gilliam we'll need to setup CI to push automatically, which is something @heynickc and I can work on.
