### ISSUE TITLE
Finish "Testing Actor Systems" article in the documentation

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2672]
This article should be finished and all examples should be converted to C#
http://akkanetdocfx.azurewebsites.net/articles/actors/testing-actor-systems.html

Original article: http://doc.akka.io/docs/akka/2.5/scala/testing.html

**Comment by alexvaluyskiy** [comment]
Also, it would be good to add more examples about `EventFilter` event muting and `FilterEvents`, because they were implemented differently (or wrongly) from Akka JVM

**Comment by Aaronontheweb** [comment]
Closed by #2808
