### ISSUE TITLE
During DI actor creation the complete DI container is serialized

### ISSUE THREAD

**Issue by kantora** [akkadotnet/akka.net#2677]
I've just updated to Akka.Net 1.2 and encountered the following problem.
I am using DI to create actors (with Castle.Windsor as DI provider).
The actor creation with something like this: `sys.ActorOf(sys.DI().Props(typeof(NameSpaceActor)), path[0])` now fails:
```
Hyperion.ValueSerializers.UnsupportedTypeException
Ambiguous match found.
   at Hyperion.ValueSerializers.UnsupportedTypeSerializer.WriteManifest(Stream stream, SerializerSession session)
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Akka.Serialization.HyperionSerializer.ToBinary(Object obj)
   at Akka.Actor.ActorCell.MakeChild(Props props, String name, Boolean async, Boolean systemService)
   at Akka.Actor.ActorCell.AttachChild(Props props, Boolean isSystemService, String name)
   at ClusterKit.Core.ActorSystemUtils.StartNameSpaceActorsFromConfiguration(ActorSystem sys) in C:\Dropbox\Sources\Git\ClusterKit\ClusterKit.Core\ClusterKit.Core\ActorSystemUtils.cs:line 88
   at ClusterKit.Core.Tests.Configuration.ConfigurationTest.NameSpaceActorTest() in C:\Dropbox\Sources\Git\ClusterKit\ClusterKit.Core\ClusterKit.Core.Tests\Configuration\ConfigurationTest.cs:line 86
```

The further investigation showed that during actor creation process the props serialization performed. The DI props contains `Akka.DI.CastleWindsor.WindsorDependencyResolver` as first argument (wich has IWindsorResolver as property). So all `IWindsorResolver` is going to serialization, wich is now failing (I don't think that it is meant to be serialized).

Is this a bug or I just do something wrong?

**Comment by kantora** [comment]
Just found out that I had `akka.actor.serialize-creators = on` in tests. But strange that tests worked normally before the upgrade. Nevertheless, I suppose that some protection should be made to avoid serializing DI container in Props

**Comment by alexvaluyskiy** [comment]
@kantora SerializedCreators had worked wrong previously. We have fixed it.  Probably we should add `INoSerializationVerificationNeeded` interface to `IWindsorResolver`

**Comment by kantora** [comment]
@alexvaluyskiy the problem with marking classes with interfaces is that you just can't mark classes from third-party libs :)
Maybe. Will it be a good idea to create some config section for it?

**Comment by kantora** [comment]
Also, you can get both IWindsorResolver and Akka.DI.CastleWindsor.WindsorDependencyResolver as props parameter. And it seems to me that serializing DI().Props is a much more complex thing that it seems to be. What is expected behavior when you start such actor on a foreign node? Should it use serialized arguments from the original node or should it resolve them locally?

**Comment by Danthar** [comment]
@kantora your remark is exactly why DI in a remote-deploy scenario is not supported atm. 

Im curious though, why are you using 'serialize-creators'. As its something I wouldn't expect users to be using. Are you using it in Tests? Or also in production code ? And if so, to what end ?

**Comment by kantora** [comment]
@Danthar just in test. Some time ago considered that for tests serialize-creators and serialize-messages should be useful. This failed only now and it took some time to get why.

**Comment by kantora** [comment]
@Danthar @alexvaluyskiy suppose this issue can be closed as not supported.

**Comment by srogovtsev** [comment]
@Danthar, you say that "DI in a remote-deploy scenario is not supported atm". What would happen if I add implement `ISurrogated` on my DI implementation? `Props` for `DI` always seem to reference the DI currently specified on the `ActorSystem`, and `FromSurrogate` gets `ActorSystem` as well, so the should not be an issue to get it, or is there?

**Comment by Danthar** [comment]
@srogovtsev that is not the issue here. The fact that the DI container instance was being serialized was a bug. It is highly impractical to send your entire DI container instance across the wire. Which is what you would end up trying to do when implementing ISurrogated on your DI container.
In short, you'd be trying to solve the wrong problem.

What you would want to do in theory, is just send the props across the network, and have the remote systems own DI container instance, resolve the Prop. 
Idea's are being worked on by @Horusiath but whether that means we support DI for remote actors, i dont know.

**Comment by srogovtsev** [comment]
It seems I wasn't clear (or maybe it was simply a mistake in hijacking a thread that is only related to my actual question).

> The fact that the DI container instance was being serialized was a bug. 

This I don't doubt at all.

> Which is what you would end up trying to do when implementing ISurrogated on your DI container. In short, you'd be trying to solve the wrong problem.

But this isn't what I meant.

So let's backtrack a bit, and consider typical DI-based props: `sys.DI().Props(typeof(NameSpaceActor))`. When serialized (whether for remoting or persistence, the latter being my actual case), they would containe `typeof(DIActorProducer)` in `Type` and `[dependencyResolver, typeof(NameSpaceActor)]` in `Arguments`. All of this - but for `dependencyResolver` would serialize nicely. What I _wanted_ for Akka to do is to avoid serializing `dependencyResolver` at all, and use target `ActorSystem`'s one on deserialization. Which I thought might be achieved with the following:

```
//adding ISurrogated to the dependency resolver
public class AutoFacDependencyResolver : ISurrogated...
{
  ISurrogated.ISurrogate ToSurrogate(ActorSystem system)
    => return new Surrogate();

  private class Surrogate: ISurrogate
  {
      public ISurrogated FromSurrogate(ActorSystem system)
        => system.GetDependencyResolver(); //this one doesn't exist yet, but can be easily done via DIExt    
  }
}
```

(which kinda matches your "what you would want to do in theory")

I haven't yet had the time to see whether this would actually work, but what are potential pitfalls of this approach?

**Comment by Danthar** [comment]
I am not sure. I have no idea if the actor creation system takes actorproducer types into account, when creating an actor from serialized props.
But you'd find out pretty quick by simply trying.
