### ISSUE TITLE
Can UnboundedMailboxQueue.cs be renamed to match the class it contains?

### ISSUE THREAD

**Issue by spankr** [akkadotnet/akka.net#2696]
The **Akka/Dispatch/MessageQueues/UnboundedMailboxQueue.cs** file contains one class, named **UnboundedMessageQueue**. Can those names be sync'd?

It was a little difficult to find that class when browsing through github.

**Comment by spankr** [comment]
I came across that as I've been learning about mailboxes so I thought I'd mention it.

**Comment by Aaronontheweb** [comment]
@spankr renaming the files is easy - please go ahead and submit a PR for that.

**Comment by spankr** [comment]
I was hoping you'd say that. 👍

**Comment by Aaronontheweb** [comment]
Closed by #2698
