### ISSUE TITLE
Testrunner throws System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain. This can happen if the test(s) started a thread but did not stop it. Make sure that all the threads started by the test(s) are stopped before completion.

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#270]
```
System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain. This can happen if the test(s) started a thread but did not stop it. Make sure that all the threads started by the test(s) are stopped before completion.
```

Are we starting non-background threads somewhere and not killing them ?

**Comment by bladeoflight16** [comment]
I'm seeing this as well. To be more specific, I'm seeing it during test teardown, when I call either `CassiniDevServer.StopServer()` or `CassiniDevServer.Dispose()`. I'm using the [NUnit Test Adapter](http://nunit.org/index.php?p=vsTestAdapter&r=2.6.3) (version 1.2) in Visual Studio. I'm not seeing it outside Visual Studio using the Gallio runner.

**Comment by rogeralsing** [comment]
Is this still a problem now that xUnit 2 is out?
