### ISSUE TITLE
Akka on .Net core

### ISSUE THREAD

**Issue by carol-braileanu** [akkadotnet/akka.net#2704]
Hello everyone,

I just discovered Akka and I am interested in integrating it into my projects. However, my code is written in .NET core, and it seems that the version of Akka that is now on NuGet is not compatible with .Net Core. Is there currently any version that supports .net core/.net standard?

Thank you!

**Comment by dustinchilson** [comment]
It's actively being worked on. See #2153 and the [netcore](https://github.com/akkadotnet/akka.net/labels/netcore) tag.

**Comment by Corstiaan84** [comment]
Whats the status of this? Thanks!

**Comment by Horusiath** [comment]
@Corstiaan84 Akka.NET is compatible with .NET Standard v1.6 since summer 2017.

**Comment by Corstiaan84** [comment]
Thanks

Op za 27 jan. 2018 om 14:18 schreef Bartosz Sypytkowski <
notifications@github.com>
