### ISSUE TITLE
Isn't there any officially released version of Persistence package?

### ISSUE THREAD

**Issue by fleed** [akkadotnet/akka.net#2707]
On Nuget I can only find beta versions of the package up to 1.2, but no official release for 1.0 or 1.1

Can the beta version be considered stable/reliable? Any planning available (even just in terms of quarters)?

**Comment by alexvaluyskiy** [comment]
@fleed not yet. We are planning to release it in the next minor version

**Comment by Silv3rcircl3** [comment]
@fleet please use the Gitter room next time for those questions.

**Comment by fleed** [comment]
Thank you @alexvaluyskiy .
Apologies for the mistake, @Silv3rcircl3

**Comment by Silv3rcircl3** [comment]
@fleed no worries, alll good ;-)
