### ISSUE TITLE
Speed up the Akka.NET CI process

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2717]
**Reduce the amount of work per-build**

* [ ] Use VCS filters to not trigger unit tests for documentation-only changes (markdown files)
* [x] Use git diffs to perform incremental builds / test runs to avoid running the entire test suite on each individual change
* [ ] Look into streamlining file copying / folder output to help reduce compile time

**Improve parallelization**
* [ ] Tune the XUnit / FsCheck suites to be able to run with full parallelization with no side-effects
* [x] Split the .NET Core / NETFX builds to run on their own machines
* [ ] Execute XUnit in parallel for specs with no side effects in one run, run a second XUnit run for specs that have side effects and need to be run sequentially

**Comment by kantora** [comment]
Maybe this will help.
I've noticed that running `dotnet build` or `dotnet pack` against whole solution runs much much faster than running it against individual projects.

**Comment by Aaronontheweb** [comment]
Just merged in https://github.com/akkadotnet/akka.net/pull/2818, which implements incremental builds... That should help reduce the overall per-PR workload significantly for all work on modules that aren't Akka core.

**Comment by Aaronontheweb** [comment]
Done
