### ISSUE TITLE
Configure CI to build and publish new docfx-based docs

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2733]
Need to update build.fsx with Azure deployment after "DocFx" build of docs and double check that TeamCity can publish them correctly.

**Comment by alexvaluyskiy** [comment]
@heynickc is it ready to close?

**Comment by alexvaluyskiy** [comment]
@heynickc is it ready?

**Comment by heynickc** [comment]
@alexvaluyskiy Yes, ready.
