### ISSUE TITLE
Which AKKA.Net pattern good to replace SSIS Package which call WCF service 

### ISSUE THREAD

**Issue by sadanlives14** [akkadotnet/akka.net#2734]
Hi, I have a SSIS package which run every night has WCF service tasks execute in sequence (WCF service 1, 2, 3). I need to replace this(SSIS Scheduler) using akka.net. So wanted to know which Akka.net design pattern good for this use case. Appraciate for your help.

**Comment by Danthar** [comment]
Why do you need to replace this using akka.net ? What problem do you currently have that akka.net would solve in this case ?
Without knowing more, its hard to advise you on a possible solution.

In general if you need long-term scheduling capabilities. I would advise to use the [Quartz ](https://github.com/akkadotnet/Akka.Quartz.Actor) plugin for akka.
