### ISSUE TITLE
Errors when nodes are being shutdown / not leaving the cluster correctly

### ISSUE THREAD

**Issue by nvivo** [akkadotnet/akka.net#2754]
I get lots of these errors daily, mostly when nodes are restarted, but some when there are actual connection errors:

![image](https://user-images.githubusercontent.com/202449/27038924-c4046a96-4f62-11e7-9a65-e91826ecd506.png)

I noticed that when this happens, this is all I see in the log:
```
12 Jun 2017 05:00:01.025 Marked address [akka.tcp://SICluster@10.0.0.50:10007] as [Leaving]
```
In contrast to other times the node was restarted and no errors appear:
```
12 Jun 2017 09:00:08.023 Remoting shut down.
12 Jun 2017 09:00:07.944 Remote daemon shut down; proceeding with flushing remote transports.
12 Jun 2017 09:00:07.942 Shutting down remote daemon.
12 Jun 2017 09:00:07.920 Cluster Node [akka.tcp://SICluster@10.0.0.50:10007] - Successfully shut down
12 Jun 2017 09:00:07.920 Cluster Node [akka.tcp://SICluster@10.0.0.50:10007] - Shutting down...
12 Jun 2017 09:00:07.915 Exiting completed.
12 Jun 2017 09:00:07.913 Exiting, starting coordinated shutdown.
12 Jun 2017 09:00:01.025 Marked address [akka.tcp://SICluster@10.0.0.50:10007] as [Leaving]
```

I'm trying to diagnose some network issues between some VMs, and I want to rule out any issues with the library, but currently they look mixed up.

Any idea on what may be going on here?

**Comment by Aaronontheweb** [comment]
@nvivo that error is being caught at the socket level by DotNetty - might have to do with how cleanly the connection is being terminated (if we allowed the graceful shutdown signal at the socket level to be receive completely.) 

Sometimes there are also issues when nodes in a cluster restart and two nodes attempt to connect to each other at the same time and one of those connections has to be aborted since we don't allow multiple associations. However, we can make this less scary when this happens - @maxcherednik did a good job with that on the old Helios transport. We'll have to perform a similar cleanup here for DotNetty now that the underlying messages are different.

**Comment by nvivo** [comment]
@Aaronontheweb, I found one of the reasons for the errors was that CoordinatedShutdown default timeout of 10 seconds for tasks. Both cluster leave and actor system termination was taking more than 10s for me sometimes, so the process was terminated before everything finishes gracefully. So, an idea to reduce these errors is increase the default timeouts for CoordinatedShutdown.

I put a 60 second timeout to test, and cluster leave usually takes between 4 to 8 seconds, but occasionally takes up to 11 seconds. Sometimes when nodes are stuck joining, other nodes cannot leave also, and many nodes timeout after 60 seconds and PBM shows me "leaving unreacheable" for them.

As for the actor system, I guess it depends on what each person does. I have many actors that need to flush data to the database on stop, so when many nodes stop, there is some waiting before the database can finish writing everything, and it may take more than 10 seconds. But I guess a 60 second timeout wouldn't hurt as a default.

**Comment by gengle** [comment]
@Aaronontheweb, I'm not sure issue #2860 is in-fact a related bug.  After reviewing my client code, I mocked up the following:

```
try
{
  var client = system.ActorOf(Props.Create<ClientActor>(), "client");
  return client.Ask<ClientEvent.RequestStatus>(command, TimeSpan.FromMinutes(command.Timeout))
    .ContinueWith(x =>
    {
      system.Log.Info("{@Result}", x.Result);
      return x.Result;
    });
}
finally
{
  Console.ReadLine();
  system.Log.Info("leaving cluster...");
  Cluster.Get(system).LeaveAsync().Wait();
  system.Log.Info("left cluster");
}
```

Note the `Console.ReadLine()` above. I believe there was a race condition preventing cluster termination before.

I now no-longer receive `System.Net.Sockets.SocketException` on the other nodes.  

**Role->api**
> [08:31:15 INF] Planner loading
> [08:31:17 INF] Progress {ReceivedTotal=1, AcceptedTotal=0, IgnoredTotal=0, Elapsed=00:00:24.6390000}
> [08:31:18 INF] Progress {ReceivedTotal=1, AcceptedTotal=0, IgnoredTotal=0, Elapsed=00:00:25.6520000}
> [08:31:19 INF] Progress {ReceivedTotal=41386, AcceptedTotal=41385, IgnoredTotal=0, Elapsed=00:00:26.6590000}
> [08:31:20 INF] Progress {ReceivedTotal=101678, AcceptedTotal=101677, IgnoredTotal=0, Elapsed=00:00:27.6690000}
> [08:31:21 INF] Progress {ReceivedTotal=164032, AcceptedTotal=164032, IgnoredTotal=0, Elapsed=00:00:28.6810000}
> [08:31:22 INF] Progress {ReceivedTotal=226591, AcceptedTotal=226590, IgnoredTotal=0, Elapsed=00:00:29.6890000}
> [08:31:25 WRN] unhandled event Akka.Cluster.ClusterEvent+MemberExited(Member=Member(address = akka.tcp://scheduler@127.0.0.1:5822, Uid=1490588018 status = Exiting, role=[client], upNumber=3)) in state Oldest
> [08:31:25 INF] Exiting confirmed [akka.tcp://scheduler@127.0.0.1:5822]

**Role->lighthouse**
> Akka.Cluster.ClusterCoreDaemon: Node [akka.tcp://scheduler@127.0.0.1:5930] is JOINING, roles [client]
> Akka.Cluster.ClusterCoreDaemon: Leader is moving node [akka.tcp://scheduler@127.0.0.1:5930] to [Up]
> Akka.Cluster.ClusterCoreDaemon: Leader is moving node [akka.tcp://scheduler@127.0.0.1:5930] to [Exiting]
> Akka.Cluster.ClusterCoreDaemon: Exiting confirmed [akka.tcp://scheduler@127.0.0.1:5930]
> Akka.Cluster.ClusterCoreDaemon: Leader is removing confirmed Exiting node [akka.tcp://scheduler@127.0.0.1:5930]
> 

**Role->client**

> [08:31:14 INF] Starting remoting
> [08:31:14 INF] Remoting started; listening on addresses : [akka.tcp://scheduler@127.0.0.1:5822]
> [08:31:14 INF] Cluster Node [akka.tcp://scheduler@127.0.0.1:5822] - Starting up...
> [08:31:14 INF] Cluster Node [akka.tcp://scheduler@127.0.0.1:5822] - Started up successfully
> [08:31:15 INF] Welcome from [akka.tcp://scheduler@127.0.0.1:4053]
> [08:31:15 INF] executing {"Partner": "CCIC", "Capability": "LogClaimCapability", "Timeout": 15, "$type": "RunCapabilityOption"}
> [08:31:15 INF] {"ExitCode": 0, "$type": "RequestAccepted"}
> [08:31:15 INF] Received {"$type": "ClusterAvailableEvent"}
> [08:31:15 INF] Received {"$type": "ClusterAvailableEvent"}
> [08:31:15 INF] Received {"MessageId": "a9e7d713-8de6-41f7-9cfe-c374c1c24671", "$type": "Accepted"}
> [08:31:23 INF] leaving cluster...
> [08:31:23 INF] Marked address [akka.tcp://scheduler@127.0.0.1:5822] as [Leaving]
> [08:31:25 INF] Exiting, starting coordinated shutdown.
> [08:31:25 INF] Exiting completed.
> [08:31:25 INF] Cluster Node [akka.tcp://scheduler@127.0.0.1:5822] - Shutting down...
> [08:31:25 INF] Cluster Node [akka.tcp://scheduler@127.0.0.1:5822] - Successfully shut down
> [08:31:25 INF] left cluster
> [08:31:25 INF] Starting coordinated shutdown from CLR termination hook.
> [08:31:25 INF] Message MemberRemoved from akka://scheduler/system/cluster/core/publisher to akka://scheduler/system/cluster/core/daemon/heartbeatSender was not delivered. 1 dead letters encountered.
> [08:31:25 INF] Message MemberRemoved from akka://scheduler/system/cluster/core/publisher to akka://scheduler/system/cluster/core/daemon/heartbeatSender was not delivered. 2 dead letters encountered.
> [08:31:25 INF] Shutting down remote daemon.
> [08:31:25 INF] Remote daemon shut down; proceeding with flushing remote transports.
> [08:31:25 INF] Remoting shut down.

**Comment by Aaronontheweb** [comment]
@gengle what exactly does the `Console.ReadLine` do in this case? Like, were you terminating the cluster immediately after starting it before?

**Comment by gengle** [comment]
`Console.ReadLine` does nothing but wait for me to press `<enter>`.  I believe I was terminating the cluster too soon before.

**Comment by Aaronontheweb** [comment]
too soon after starting a node?

**Comment by gengle** [comment]
Correct, that's my feeling so far as my original issue goes away now. Also the changes made in TcpTransport (going from memory here)  are structurally identical to how Helicos was handled.

I can reproduce the error above by terminating the actor system without leaving the cluster first. Would that scenario be considered a defect?

**Comment by Aaronontheweb** [comment]
@gengle if the `ActorSystem` was aborted by having something like the process exit without letting the `ActorSystem.Terminate` task complete that would cause the problem... Because that would literally abort the socket connection on process exit. It'd be the OS doing that, not Akka.NET code.

**Comment by gengle** [comment]
That makes sense. Also calling cluster.get(..).LeaveAsync () too soon never returns a completed task.

Regarding this issue specifically, is it still an open confirmed bug? If so I can still dig into this even though it nolonger relates to my original issue.

**Comment by Aaronontheweb** [comment]
@gengle 

> calling cluster.get(..).LeaveAsync () too soon never returns a completed task.

now THAT, is an interesting problem.... Think it's because the node hasn't actually joined the cluster yet? When, exactly, is "too soon" ?

**Comment by gengle** [comment]
I'll mock up a sample soon. I ran into this issue earlier. I believe it happens if I remove the console.readline.

**Comment by gengle** [comment]
@Aaronontheweb - Here is a quick illustration on `Cluster.Get(system).LeaveAsync()` blocking.

1.  Make the following changes to `ClusterToolsExample.Node`

```
static void Main(string[] args)
{
	Console.Title = "Attached node";
	using (var system = ActorSystem.Create("singleton-cluster-system"))
	{
		//RunClusterSingletonClient(system);
		RunDistributedPubSubClient(system);
		//RunClusterClient(system);
		Console.WriteLine("leaving cluster");
		Cluster.Get(system).LeaveAsync().Wait();
		Console.WriteLine("exited cluster");
	}
}
```
2. start `ClusterToolsExample.Seed.exe`
3. start `ClusterToolsExample.Node.exe`

**Notice** that we never receive `exited cluster` in the log.

> λ ClusterToolsExample.Node.exe
> [DEBUG][7/18/2017 7:01:38 PM][Thread 0001][EventStream] StandardOutLogger started
> [DEBUG][7/18/2017 7:01:38 PM][Thread 0001][EventStream(singleton-cluster-system)] Logger log1-DefaultLogger [DefaultLogger] started
> [DEBUG][7/18/2017 7:01:38 PM][Thread 0001][EventStream(singleton-cluster-system)] StandardOutLogger being removed
> [INFO][7/18/2017 7:01:38 PM][Thread 0001][remoting] Starting remoting
> [INFO][7/18/2017 7:01:38 PM][Thread 0001][remoting] Remoting started; listening on addresses : [akka.tcp://singleton-cluster-system@127.0.0.1:19997]
> [INFO][7/18/2017 7:01:38 PM][Thread 0001][Cluster] Cluster Node [akka.tcp://singleton-cluster-system@127.0.0.1:19997] - Starting up...
> [INFO][7/18/2017 7:01:38 PM][Thread 0001][Cluster] Cluster Node [akka.tcp://singleton-cluster-system@127.0.0.1:19997] - Started up successfully
> leaving cluster
> Actor [[akka://singleton-cluster-system/user/$a#1590916349]] has subscribed to topic [echo]
> [INFO][7/18/2017 7:01:39 PM][Thread 0020][[akka://singleton-cluster-system/system/cluster/core/daemon#829176857]] Welcome from [akka.tcp://singleton-cluster-system@127.0.0.1:2551]
> hello world
> hello world
> hello world
> hello world
> hello world
> hello world
> ...
> ...

**Comment by Aaronontheweb** [comment]
`Cluster.LeaveAsync` should probably be deprecated - `CoordinatedShutdown.Run()` was introduced later and does a more comprehensive job of implementing the same thing.

**Comment by gengle** [comment]
`CoordinatedShutdown `causes the other nodes to generate the `SocketException` noted earlier.  This happens automatically after the CLR termination hook kicks in.

This is what appears on the other nodes:

> [19:43:58 ERR] Error caught channel [[::ffff:127.0.0.1]:28414->[::ffff:127.0.0.1]:28434](Id=350e7a22)
> System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
>    at DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()
>    at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
> [19:43:58 WRN] Association with remote system akka.tcp://scheduler@127.0.0.1:28432 has failed; address is now gated for 5000 ms. Reason is: [Akka.Remote.EndpointDisassociatedException: Disassociated
>    at Akka.Remote.EndpointWriter.PublishAndThrow(Exception reason, LogLevel level, Boolean needToThrow)
>    at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
>    at Akka.Actor.UntypedActor.Receive(Object message)
>    at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
>    at Akka.Actor.ActorCell.ReceiveMessage(Object message)
>    at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
>    at Akka.Actor.ActorCell.Invoke(Envelope envelope)]
>

**Comment by gengle** [comment]
running `CoordinatedShutdown.Get(system).Run().Wait()` resulted in a task failure for [cluster-leave].  I'll experiment a bit more with this.

> [20:05:23 WRN] Task [leave] failed in phase [cluster-leave]: null
> [20:05:33 WRN] Coordinated shutdown phase [cluster-exiting] timed out after 00:00:10
> [20:05:33 INF] Exiting completed.
> [20:05:33 INF] Cluster Node [akka.tcp://scheduler@127.0.0.1:28732] - Shutting down...
> [20:05:33 INF] Cluster Node [akka.tcp://scheduler@127.0.0.1:28732] - Successfully shut down
> [20:05:33 INF] Message MemberRemoved from akka://scheduler/system/cluster/core/publisher to akka://scheduler/system/cluster/core/daemon/heartbeatSender was not delivered. 1 dead letters encountered.
> [20:05:33 INF] Message MemberRemoved from akka://scheduler/system/cluster/core/publisher to akka://scheduler/system/cluster/core/daemon/heartbeatSender was not delivered. 2 dead letters encountered.
> [20:05:33 INF] Message MemberRemoved from akka://scheduler/system/cluster/core/publisher to akka://scheduler/system/cluster/core/daemon/heartbeatSender was not delivered. 3 dead letters encountered.
> [20:05:33 INF] Shutting down remote daemon.
> [20:05:33 INF] Remote daemon shut down; proceeding with flushing remote transports.
> [20:05:33 INF] Remoting shut down.
> terminating...

**Comment by Aaronontheweb** [comment]
@gengle I believe @nvivo mentioned to me that he had to increase the timeout for that phase for his cluster, although I don't remember how large it was. 20ish?

**Comment by jalchr** [comment]
Hi,
I have experiencing similar (random) errors.
![akka net errors](https://user-images.githubusercontent.com/295421/28512124-2fd4c560-7059-11e7-834e-7ed49eb21d5c.PNG)

Any thoughts how to overcome them ?
