### ISSUE TITLE
Tests hangs occasionally. Bug in xUnit. How to avoid.

### ISSUE THREAD

**Issue by HCanber** [akkadotnet/akka.net#276]
I've tracked down a bug in xUnit 1.9.2 that can cause our tests to hang (not sure why they hang and not crashes) in Resharper´s test runner.
 
Basically what happens is that xUnit replaces Console.Out with a StringWriter. After the test is finished it reverts back to the original writer. It then calls ToString on the StringWriter it created. If one of our threads (running system shutdown) get's hold of the StringWriter before Console.Out was changed back, we have to threads operating on the same StringBuilder (that's used internally in StringWrite). StringBuilder isn't thread safe.

I've submitted a PR to xUnit. For more info see:
https://github.com/xunit/xunit/issues/164

While waiting for a new version of xUnit, if you get test's that hangs, make sure debug logging is set to a minimal. The less we log, the less likely this race condition occurs.

**Comment by rogeralsing** [comment]
Are we still seeing this bug? we are still using 1.9.2 of xUnit, but I can't recall seeing the hangups for a long time.
Status?
