### ISSUE TITLE
Install .NET CLI in Docker image: akkadotnet/mono-base:latest

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2766]
To improve speed of builds in CI, pre-install .NET Core CLI on the Docker image used by TeamCity.

**Comment by alexvaluyskiy** [comment]
@heynickc I've looked at our build logs. Download and install take only 5-10 sec.

**Comment by heynickc** [comment]
@alexvaluyskiy ok sounds good thanks.
