### ISSUE TITLE
akka.persistence: snapshot-store auto-start

### ISSUE THREAD

**Issue by zbynek001** [akkadotnet/akka.net#2770]
Looks like snapshot stores which should auto-start are red from "akka.persistence.journal" config, instead of  "akka.persistence.snapshot-store"

**Comment by alexvaluyskiy** [comment]
How to reproduce it?

**Comment by zbynek001** [comment]
It's happening here:

https://github.com/akkadotnet/akka.net/blob/v1.3/src/core/Akka.Persistence/Persistence.cs#L111

`_config.GetStringList("journal.auto-start-snapshot-stores")
`

should be

`_config.GetStringList("snapshot-store.auto-start-snapshot-stores")
`

**Comment by Aaronontheweb** [comment]
closed by #2806
