### ISSUE TITLE
When using clustered pool, if use-local-routees is on, it seems to ignore the use-role property

### ISSUE THREAD

**Issue by jrlost** [akkadotnet/akka.net#2783]
I'm attempting to implement a simple two node cluster (example: https://github.com/jrlost/AkkaNetRoutingTest). I'm seeing that when using a clustered pool, if use-local-routees is on, it seems to ignore the use-role property. Similar to what's outlined here: https://github.com/akka/akka/issues/15042

**Comment by Aaronontheweb** [comment]
I'll investigate this for 1.2.2

**Comment by Aaronontheweb** [comment]
Turns out we had a test that was commented out for `UseRoleIgnored`... uncommented it and it passes just fine. 

Just for a sanity check, which version of Akka.NET are you using?

**Comment by Aaronontheweb** [comment]
Aha. Spoke to soon. The spec fails; I just needed to do a full rebuild first. Got it reproduced. Will have a fix soon.

**Comment by Aaronontheweb** [comment]
closed by #2802
