### ISSUE TITLE
Cannot create actor via DI using Remote and Hyperion with props serialization

### ISSUE THREAD

**Issue by andreyleskov** [akkadotnet/akka.net#2784]
I've updated to Akka 1.2.0, and my Unity-based DI stops working with "serialize-creators = on" option. 
```
  public class Hyperion_DI_test
    {
        [Fact]
        public void Just_create_an_actor()
        {
            var system = ActorSystem.Create("test",
                                                 @"akka {
                   actor {
                       serialize-creators = on
                       serializers { hyperion = ""Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion""  
                                     wire = ""Akka.Serialization.WireSerializer, Akka.Serialization.Wire""}
                       serialization-bindings { ""System.Object"" = hyperion}
                   }
                   actor.provider = ""Akka.Remote.RemoteActorRefProvider, Akka.Remote""
                   remote {
                       helios.tcp { transport-class = ""Akka.Remote.Transport.Helios.HeliosTcpTransport, Akka.Remote""
                                    transport-protocol = tcp
                                    hostname = 127.0.0.1 }
                   }
            }");

            system.AddDependencyResolver(new UnityDependencyResolver(new UnityContainer(), system));
            system.ActorOf(system.DI().Props<MyActor>());
        }
        class MyActor : ReceiveActor { }
    }
```

Packages used: 
"Akka" version="1.2.0"
"Akka.DI.Core" version="1.2.0"
"Akka.DI.Unity" version="1.1.0"
"Akka.Remote" version="1.2.0"
"Akka.Serialization.Hyperion" version="1.2.0.36-beta"

Got an error on actor creating by props: 

```

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
The most fitting overloaded method (translation from 'Наиболее подходящий перегруженный метод' )для "Hyperion.SerializerFactories.ArraySerializerFactory.WriteValues<System.ValueType>(System.ValueType[], System.IO.Stream, System.Type, Hyperion.ValueSerializers.ValueSerializer, Hyperion.SerializerSession)" has several invalid arguments (translated from 'имеет несколько недопустимых аргументов')
   в CallSite.Target(Closure , CallSite , ArraySerializerFactory , Object , Stream , Type , ValueSerializer , SerializerSession )
   в System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   в Hyperion.SerializerFactories.ArraySerializerFactory.<>c__DisplayClass4_0.<BuildSerializer>b__1(Stream stream, Object arr, SerializerSession session)
   в Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   в lambda_method(Closure , Stream , Object , SerializerSession )
   в Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   в lambda_method(Closure , Stream , Object , SerializerSession )
   в Akka.Serialization.HyperionSerializer.ToBinary(Object obj)
   в Akka.Actor.ActorCell.MakeChild(Props props, String name, Boolean async, Boolean systemService)
   в Akka.Actor.ActorCell.AttachChild(Props props, Boolean isSystemService, String name)
   в GridDomain.Tests.XUnit.CommandsExecution.Hyperion_DI_test.Just_create_an_actor() в P:\GridDomain\GridDomain.Tests.XUnit\CommandsExecution\Hyperion_DI_test.cs:строка 31
```

same test for wire and packages  
"Akka" version="1.1.3" targetFramework="net461"
"Akka.DI.Core" version="1.1.3" targetFramework="net461"
Akka.DI.Unity" version="1.1.0" targetFramework="net461"

works ok

**Comment by Danthar** [comment]
Adding this for reference:
https://github.com/akkadotnet/akka.net/pull/2587/files#diff-eb4064364ece54e933d8a274ecd863cbL400

These changes might have impact here.

**Comment by Danthar** [comment]
Same problem occurs with the Autofac DI as well.

**Comment by Danthar** [comment]
Funny thing. Does not happen when using the default newtonsoft serializer

**Comment by Danthar** [comment]
Updated Unity, Autofac and Windsor integrations on their respective dev branches which fixes this issue.
/cc @goodisontoffee 

Windsor is not netcore compatible though, so updating to latest akka.net is an issue

**Comment by andreyleskov** [comment]
@Danthar is their any nighty build with fix? tried Akka.DI.Unity 1.1.0.3-beta with no success

**Comment by Danthar** [comment]
Nope. net yet. The current builds for unity and windsor are failing. Quite possibly due to not being dotnetcore compatible.

**Comment by Danthar** [comment]
Ok, Windsor is fixed and updated to 1.2.2 as well.
Unity will be as well once https://github.com/akkadotnet/Akka.DI.Unity/pull/8 is merged.

Nightlies for Windsor are available. Ill run them for Unity as well once the PR is merged.

**Comment by andreyleskov** [comment]
@Danthar  thank you a lot ! Will upgrade akka from 1.1.3 at last )

**Comment by Danthar** [comment]
Note that no release is pushed yet. But i expect it will be soon.

**Comment by Danthar** [comment]
Windsor is released. Rest will have nightlies available after today. All 3 are updated to 1.2.3

**Comment by sean-gilliam** [comment]
Closing this issue since it appears to have been resolved. Feel free to re-open it if that's not the case.

**Comment by mrxrsd** [comment]
Its seems to affect simpleinjector as well. It is working fine with newtonsoft but with hyperion only works when I disable "serialize-creators".
