### ISSUE TITLE
Add no-op RunTestsNetCore step in build.fsx for dev branch

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2786]
For dev branch PRs, unless we put some kind of no-op in its build.fsx - the `RunTestsNetCore` step will try to run on the new TeamCity build configurations and throw an error and fail the build.  TeamCity doesn't support filtering PRs based on which branch they are being submitted to.

Will need to add something like `Target "RunTestsNetCore"...` that does nothing.

**Comment by Aaronontheweb** [comment]
Good idea

**Comment by Aaronontheweb** [comment]
Closed by #2787
