### ISSUE TITLE
Remove everything marked Obsolete just before releasing v1

### ISSUE THREAD

**Issue by HCanber** [akkadotnet/akka.net#280]
In order to be backward compatible when making changes, many members have been marked with the `[Obsolete]` attribute. 
These members should be removed just before we release version 1.

**Comment by rogeralsing** [comment]
@akkadotnet/developers status on this one?
Are we removing the obsolete stuff for V1?

**Comment by HCanber** [comment]
Yes, I think we should.

**Comment by HCanber** [comment]
Or, rather, I suggest we follow this pattern:
1. In version _n_, mark something as obsolete with warnings when compiling
2. In version _n+x_ where _x&#x2265;1_, change obsolete to compile with errors
3. In version _n+y_ where _y&#x2265;2_, remove it completely

So for now:
- Remove everything that's was obsolete in v0.7.1
- Change all Obsolete attributes that was around for version v0.8 to compile with errors.
- Everything newer than that should be kept, as it provides guidance to the user what to change to.

**Comment by Aaronontheweb** [comment]
What all needs to be removed this time around?

**Comment by HCanber** [comment]
Here's what needs to be done:
1. Check out v0.7.1. Find all usages of `ObsoleteAttribute`. Either make a note of where these are, or delete these directly, commit, and later rebase the change on `dev`
2. Check out v0.8.  Find all usages of `ObsoleteAttribute`. Either make a note of where these are, or make the change directly: Add `true` to the attribute: `[Obsolete("...", true)]` also add comment saying `Marked obsolete in v0.8`, commit, and later rebase the change on `dev`
3. Checkout `dev`, make all changes. Add a comment saying `Marked obsolete in v1.0` to the rest of the places where `ObsoleteAttribute` is used

**Comment by Horusiath** [comment]
As Akka.NET 1.0 was already released I think it's no longer an issue.
