### ISSUE TITLE
Akka.Streams.Tests 107 test failures when tests are run against RELEASE build vs DEBUG

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2800]
We have previously been using `dotnet xunit` to run our tests, which defaults to running `dotnet build -c Debug`, so we are testing Debug configuration instead of Release.  #2771 fixes this by adding `dotnet xunit -c Release`.  Building and running tests with target framework `netcoreapp1.1` along with `-c Release` causes 100+ additional tests to fail in the Akka.Streams.Tests project.

**Comment by heynickc** [comment]
cc @Horusiath @Silv3rcircl3 and anyone else who might have any clues as to why this happens.  Once we resolve this, I can merge #2771 and we'll see better feedback about issues that are from .NET Core vs .NETFX in CI.

**Comment by alexvaluyskiy** [comment]
@heynickc Why we can't merge your PR before this fix?

**Comment by heynickc** [comment]
@alexvaluyskiy we could, but I didn't want to radically change the build script until this issue was resolved since we should be running tests against Release for all PRs.

**Comment by heynickc** [comment]
Also, I was mistaken when I said this is only a `netcoreapp1.1` issue - it also occurs running tests against `net452`.

**Comment by Arkatufus** [comment]
Tests against net452 runs fine on my computer though

**Comment by Arkatufus** [comment]
It was the compiler code optimization. I added this to Akka.Streams.csproj:
`<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard1.6|AnyCPU'">
  <Optimize>False</Optimize>
</PropertyGroup>`
All of the tests passed.

**Comment by alexvaluyskiy** [comment]
Fixed
