### ISSUE TITLE
TcpMessage.Write should not allow ack = null

### ISSUE THREAD

**Issue by quartusdev** [akkadotnet/akka.net#2801]
The method [`Tcp.Message.Write(ByteString data, Tcp.Event ack = null)` ](https://github.com/akkadotnet/akka.net/blob/v1.3/src/core/Akka/IO/Tcp.cs#L1270) defaults to setting ack to `null`. After the data is sent, the acknowlegement is sent like this:
[`if (!(_ack is Tcp.NoAck)) _commander.Tell(_ack);`](https://github.com/akkadotnet/akka.net/blob/v1.3/src/core/Akka/IO/TcpConnection.cs#L704)
For the case where ack is null, the check passes and a null message is sent to `_commander`. This causes an [exception](https://github.com/akkadotnet/akka.net/blob/95b07aba9367624c729a1a233e2083cff101b5b0/src/core/Akka/Actor/Message.cs#L28) to be thrown, which then causes the connection to be closed.

I think it makes no sense deliberately crashing the connection actor like this, since it is hard to track down the cause. The condition should be extended to something like `!(_ack is Tcp.NoAck) && _ack != null`, possibly logging _ack being null.
The method `Tcp.Message.Write` should either throw an exception when ack is null or should default to using [`NoAck.Instance`](https://github.com/akkadotnet/akka.net/blob/v1.3/src/core/Akka/IO/Tcp.cs#L343).

I would gladly implement my proposed changes, if they are OK.

**Comment by Aaronontheweb** [comment]
cc @Horusiath

**Comment by Horusiath** [comment]
From what I see, the solution is just to assign `Tcp.NoAck.Instance` in `Tcp.Write(ByteString, Tcp.Event)` constructor in case if passed ack was null.

**Comment by Horusiath** [comment]
Fixed in #2683
