### ISSUE TITLE
Update F# API FSharp.Core to 4.2.1

### ISSUE THREAD

**Issue by tjaskula** [akkadotnet/akka.net#2822]
To keep up pace with newer versions of `FSharp.Core`, update to  `FSharp.Core` from v 4.1 to 4.2.1.

**Comment by tjaskula** [comment]
I'm on it

**Comment by tjaskula** [comment]
Where should I PR to 1.3 or dev branch ?

**Comment by Horusiath** [comment]
v1.3 is our current branch. It will be changed after corresponding release.

**Comment by tjaskula** [comment]
Ok, however FSharp projects are not in the Akka.sln. Is that on purpose ?

**Comment by Horusiath** [comment]
No, it's because branch v1.3 comes with update to C# 7 / .NET core / VS2017. The last piece (VS2017) is particularly painful to work with when it comes to F#.

**Comment by alexvaluyskiy** [comment]
@Horusiath F# projects was ported by me and works good, but I did not add them to the solution

**Comment by tjaskula** [comment]
@alexvaluyskiy If you want I may do it, or wait for you to do it. As you want

**Comment by alexvaluyskiy** [comment]
@tjaskula We will add these project to the solution once VS 2017 start support F# on NetCore

**Comment by 0x53A** [comment]
Why do you actually need to update FSharp.Core? Does Akka no longer work with an older version? Otherwise this will only cause pain downstream and force everyone to update.

If you are concerned about binding-redirects, then I think that is a battle that can't be won.
Imo a lib should reference the **lowest** version it can get away with.

**Comment by tjaskula** [comment]
@0x53A as this will be the .NET core release, why not picking the latest available version

**Comment by alexvaluyskiy** [comment]
@tjaskula @Horusiath My fault, F# was not updated for NetCore, because we have two problems
`FSharp.Community.Linq` does not support NetCore
`FSharp.Quotations.Evaluator` which could do the same does not support NetCore as well

Also `Akka.FSharp.Tests` does not compile at all

**Comment by tjaskula** [comment]
@alexvaluyskiy ok, that makes sense. I'll keep an eye on that one.

**Comment by tjaskula** [comment]
FYI I'm looking into the dependencies to make them work on .NET core. I'll update my progress ASAP

**Comment by tjaskula** [comment]
It seems that we've missed a deadline for the release. Updating `FSharp.Quotations.Evaluator` took some time on release related tasks. Any news/progress since then on other F# Api related tasks ?

**Comment by Horusiath** [comment]
@tjaskula no. Akka.FSharp still waits for its turn.

**Comment by tjaskula** [comment]
Ok, after holidays I'll start working on that

**Comment by tjaskula** [comment]
Sorry guys, still taking time on FSharp.Quote.Evaluator side. I'm giving some nudges to move this forward. F# is still out of the deployment for the core version ?

**Comment by Danthar** [comment]
Yes. For now. We simply don't have the people / time. So any contributions are greatly appreciated.

**Comment by sean-gilliam** [comment]
Closing this issue since the current F# API uses FSharp.Core v4.2.3.

https://github.com/akkadotnet/akka.net/blob/master/src/core/Akka.FSharp/Akka.FSharp.fsproj
