### ISSUE TITLE
Unknown build target according to XUnit2 with the Akka.net 1.3 branch

### ISSUE THREAD

**Issue by SeanFarrow** [akkadotnet/akka.net#2824]
When trying to compile the akka.net 1.3 branch with a build all, I get an unknown target from XUnit2. The unknown target is coreapp1.1. It does however find a .net452 target.

I'm not sure what assembly is causing this as XUnit does not seem to give this information, however it happens either during or after the NBench performance tests are run.

**Comment by Arkatufus** [comment]
Does it say "Unknown target framework 'netcoreapp1.1'" right after "Detecting target frameworks"?
If that's the case, then it's nothing to worry about,

**Comment by Danthar** [comment]
Status here ?
