### ISSUE TITLE
Add NetCore support for FSharp projects

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2826]
F# was not updated for NetCore, because we have two problems
FSharp.Community.Linq does not support NetCore
FSharp.Quotations.Evaluator which could do the same does not support NetCore as well

Also Akka.FSharp.Tests does not compile at all

@tjaskula @Horusiath

**Comment by Horusiath** [comment]
It looks like we may need another quotation expression evaluator. There are few others with various degree of speed:

1. [Unquote](https://github.com/SwensenSoftware/unquote) which is more useful in tests.
2. [QuotationCompiler](https://github.com/eiriktsarpalis/QuotationCompiler) which is pretty great, but as far as I know, it brings whole FCS as a depdendency.

@tjaskula anything, you'd add here?

**Comment by alexvaluyskiy** [comment]
@Horusiath Both of them without NetStandard support.
`FSharp.Quotations.Evaluator` supports PCL, so it would be easy to convert it to NetStandard

**Comment by tjaskula** [comment]
FYI, I'll be converting to .NET Core `FSharp.Quotations.Evaluator`.

**Comment by alexvaluyskiy** [comment]
Just to track it https://github.com/fsprojects/FSharp.Quotations.Evaluator/issues/15

**Comment by Aaronontheweb** [comment]
@heynickc has been working on this here and it's a bit of a tire fire: https://github.com/akkadotnet/akka.net/pull/2941

Looks like FSharp.Quotations.Evaluator hasn't merged @tjaskula's PR yet, which is a bummer. We'll have to do a separate release to get .NET Standard support for the F# API at a later date (1.3.1)

**Comment by JacobChang** [comment]
any progress on this ?

**Comment by tjaskula** [comment]
`FSharp.Quotations.Evaluator` had some issues compiling with .NET Core. I'll have to check it out again and I'll keep you posted.

**Comment by ivog** [comment]
@tjaskula I’ve created a pull request for FSharp.Quotations.Evaluator which solve the compile issues. Hopefully it can be merged soon!

**Comment by ivog** [comment]
FSharp.Quotations.Evaluator has a new nuget package targetting netstandard2.0 now

**Comment by kennethito** [comment]
Just found this.  I did some similar work when I noticed the FSharp.Quotations.Evaluator release to see how feasible a netstandard fsharp release was.  I'm currently running the tests from a netcoreapp2.0 only entrypoint and I think I might be seeing more issues.

My branch is here, feel free to take anything that's useful.
https://github.com/kennethito/akka.net/commit/dd122b73711e3879fc33241acd201c84819f73ad

I was additionally seeing the following problems
* The Akka.FSharp.Tests.ApiTests.`can serialize expression decider` test was failing with a Fsharp.Quotations.Evaluator problem described here https://github.com/fsprojects/FSharp.Quotations.Evaluator/issues/23 
* The incoming expressions from spawning actors being received here, https://github.com/kennethito/akka.net/commit/dd122b73711e3879fc33241acd201c84819f73ad#diff-cb227eb037ca1b51ac88982788d34601R389, were in a different structure than expected.  They were essentially already in the form the original code was modifying the incoming structure to be in.

**Comment by ivog** [comment]
@tjaskula  Now that #3369 is merged can this issue be closed and can a new Akka.FSharp release be created? Or are there more hurdles to overcome?

**Comment by tjaskula** [comment]
Of course. However I'm not allowed to do anything but commenting.

**Comment by marcpiechura** [comment]
We‘re planning to release 1.3.6 shortly, so it should be available once it’s up on nuget. 

CC @aarontheweb

**Comment by mariomeyrelles** [comment]
As a normal user, does this mean that we will have support for F# and .NET Core in this next release?

**Comment by marcpiechura** [comment]
@mariomeyrelles yup

**Comment by j-alexander** [comment]
[Akka.Persistence.FSharp](https://www.fuget.org/packages/Akka.Persistence.FSharp) was not included?  Looks like it targets net45 only?  Any recommendations for that one?
