### ISSUE TITLE
Incremental testing: need to add a condition for IsRunnable on Windows .NET Core vs Windows .NETFX, etc...

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2831]
Removed the use of FAKE globbing for getting "tests to run vs tests to ignore" per platform and moved it into `BuildIncremental.IncrementalTests.getUnitTestProjects()` but we still need to be able to ignore tests that don't run on .NET Core vs .NET 4.5, e.g. Akka.API.Tests.

**Comment by Aaronontheweb** [comment]
Completed as part of #3158
