### ISSUE TITLE
Akka.TestKit.NUnit nuget is still at version 1.2.1

### ISSUE THREAD

**Issue by gengle** [akkadotnet/akka.net#2850]
Not sure if this was an over site but I see Akka.TestKit.NUnit nuget is still at 1.2.1 instead of the 1.2.3
https://www.nuget.org/packages/Akka.TestKit.NUnit/

**Comment by gengle** [comment]
I'll submit a PR shortly

**Comment by sean-gilliam** [comment]
Please log issues / PRs related to NUnit to our repo here [Akka.TestKit.Nunit](https://github.com/akkadotnet/Akka.TestKit.Nunit).

**Comment by gengle** [comment]
Thanks @sean-gilliam, I'll close this one.  I created a new issue and submitted a PR on the other repo.
