### ISSUE TITLE
NuGet Release for v1.3

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2855]
NuGet Release prep for Akka v1.3:

- [x] Fix `dotnet publish` source (bin instead of build)
- [x] Add key and url parameters to TeamCity
- [x] Add TeamCity build configuration "Akka.NET v1.3 Nightlies"
- [x] Release Notes parsing
  - [x] Update .nuspec with details, release notes
  - [x] Update .csproj files with version numbers?
- [x] Pre-release tag for nightlies (-beta)
  - [x] Append build number from TeamCity to version number
- [ ] Validation that all nightly packages work
- [ ] Considerations for .exe releases (dependencies, cli tool vs .exe)

**Comment by heynickc** [comment]
TODO:

- [ ] fix `dotnet publish` source (bin instead of build)
- [x] Add key and url parameters to TeamCity
- [x] Add TeamCity build configuration "Akka.NET v1.3 Nightlies"
- [ ] Release Notes parsing
  - [ ] Update .nuspec with details
  - [ ] Update .csproj files with version numbers?
- [ ] Pre-release tag for nightlies (-beta)
- [ ] Validation that all nightly packages work
- [ ] considerations for .exe releases (dependencies, cli tool vs .exe)

**Comment by alexvaluyskiy** [comment]
@heynickc we don't have any `nuspec` files in v1.3

**Comment by heynickc** [comment]
@alexvaluyskiy they are generated on the fly during `dotnet pack`

**Comment by alexvaluyskiy** [comment]
We can store the main version number in `common.props` file and to change `versionsuffix` via parameters. We don't need the hacks with `nuspec` and with Release Notes parsing`

**Comment by heynickc** [comment]
@alexvaluyskiy Ok sounds good, we do need to get that release notes text into the `dotnet pack` command somehow.  It might even be a param we can pass into `DotNetCli.Pack`

**Comment by heynickc** [comment]
@alexvaluyskiy I may even suggest we continue parsing the Release Notes version number into the `common.props` file so we can't make the mistake of not doing that on a release - based myself making that mistake in the past :)

**Comment by alexvaluyskiy** [comment]
Do you mean the release notes text, like this https://www.nuget.org/packages/Akka/1.2.0 ?
I never like this release notes, looks ugly and unreadable 
@Aaronontheweb

**Comment by heynickc** [comment]
Yea, just something that describes what the latest release is all about

**Comment by alexvaluyskiy** [comment]
We could use a link to github tag
https://github.com/akkadotnet/akka.net/releases/tag/v1.2

**Comment by heynickc** [comment]
We also need a mechanism to add `-beta` to the names of our nightly packages when `build.cmd Nuget nugetprerelease=dev...` is called

**Comment by alexvaluyskiy** [comment]
It has already implemented
`build Nuget versionsuffix=beta-4`

**Comment by heynickc** [comment]
added to TODO list: `- [ ] Append build number from TeamCity to version number`

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy the release notes are helpful. Not my fault that NuGet doesn't support markdown

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb Why the whole release notes text is better than a link to github?

**Comment by sean-gilliam** [comment]
Does NuGet support HTML? Maybe when packaging, we could convert the markdown into HTML if it supports it.

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy I mean, we could do both? Today I link to the list of closed issues on the milestone. But pushing the tag is also what triggers the NuGet package, but it'd be easy enough to guess the URL.

Either way it's semantics because I don't think anyone reads that stuff anyway

**Comment by heynickc** [comment]
These 3 todos were resolved by #2878:

- Update .csproj files with version numbers
- Pre-release tag for nightlies (-beta)
- Append build number from TeamCity to version number

**Comment by heynickc** [comment]
Current `v1.3` branch projects with no .nupkgs being generated (as compared with `dev` branch):

```
Akka.FSharp
Akka.MultiNodeTestRunner
Akka.Persistence.FSharp
Akka.Persistence.TestKit
```

**Comment by alexvaluyskiy** [comment]
@heynickc could we close it?
