### ISSUE TITLE
Switch to Automatic Nuget package restore, i.e. remove MS Build package restore

### ISSUE THREAD

**Issue by HCanber** [akkadotnet/akka.net#289]
Currently Nuget packages are restored on build using MS Build targets. For a while now Nuget has this functionality built in, and we should switch.
I think this is what needs to be done:

1. Move `src/.nuget/nuget.exe` to `tools/nuget.exe`. We need the nuget executable when building.
1. Follow the instructions here: http://docs.nuget.org/docs/workflows/migrating-to-automatic-package-restore
1. Update the path to nuget in `build.cmd`
1. I'm guessing this needs to be done as well: 
Update `build.fsx` to restore nuget packages. See 
http://docs.nuget.org/docs/reference/package-restore#Command-Line_Package_Restore

More info on Package Restore:
http://docs.nuget.org/docs/reference/package-restore

**Comment by rogeralsing** [comment]
Is this a pre Fake issue or is this still relevant?

**Comment by Aaronontheweb** [comment]
We moved to doing NuGet package restore inside FAKE on-build a while back.
