### ISSUE TITLE
Upgrade all targeted net45 projects to net452

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2893]
Need to upgrade projects like Akka, Akka.Remote, Akka.Streams, etc. from `<TargetFrameworks>net45;netstandard1.6</TargetFrameworks>` to `<TargetFrameworks>net452;netstandard1.6</TargetFrameworks>`

**Comment by sean-gilliam** [comment]
Closing this issue since work is currently being done to target the projects to netstandard2.0. See #3452
