### ISSUE TITLE
Remove SerializableAttribute and NonSerializedAttribute attributes

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2897]
I think it is a good time to completely remove `SerializableAttribute` from the code base because they are useless. Only `BinaryFormatter` use these attributes. All other serializers just ignore it.

**Comment by angrybug** [comment]
.NET Core 2.0 doesn't seem to be able to deal with two types with the same namespace, same type name.  So referencing Akka libraries appears to mean you can't use the [Serializable] attribute

**Comment by Horusiath** [comment]
I agree. The only reason I saw to keep them, was that some of the custom serializers may want to use this attribute to identify serializable classes at system start.

**Comment by Aaronontheweb** [comment]
Done
