### ISSUE TITLE
Got many dead letters errors when reconnecting

### ISSUE THREAD

**Issue by wavebit** [akkadotnet/akka.net#2900]
Hello,
If I shut down the client then reconnect to server, then ther srever will raise many errors shown below.
(Centos 7.3 & mono 5, Both Akka.NET and Akka.Remote version are 1.2.3 from NuGet)
![cap2](https://user-images.githubusercontent.com/11334491/28526750-0af1beb2-70bb-11e7-9089-38585ebec343.PNG)
Before shuting down, the client have received the response from server, I don't know why the server pop them?
I want to deploy akka.net on end-user's PC as client, maybe the server will receive huge number of errors every second...
After searching the issues, I know the port can not be 0, so I change the client's port to 33443, but this time the server crash when reconnecting:( The stack trace is here.[crash.txt](https://github.com/akkadotnet/akka.net/files/1170015/crash.txt)

And below is the test project, a modified version of the chat example. 
https://github.com/wavebit/AkkaTest.git

**Comment by Aaronontheweb** [comment]
This has nothing to do with the design of Akka.NET. Has everything to do with the design of that sample. The connection being severed between client and server will automatically terminate those ActorRefs. Need to `Context.Watch` them and remove them from publish list once we receive a `Terminated` message from them.
