### ISSUE TITLE
MNTR to .NET Core - need to include Akka.Cluster.Sharding.Tests.MultiNode

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2930]
Once #2836 and #2929 are merged (Akka.Serialization.Hyperion targeting .NET Core), we should be able to add Akka.Cluster.Sharding.Tests.MultiNode to the .NET Core MNTR test suite.

**Comment by Aaronontheweb** [comment]
Added this to the 1.3 milestone

**Comment by Aaronontheweb** [comment]
Closed via #2953
