### ISSUE TITLE
HOCON substitution does not work (OutOfMemory)

### ISSUE THREAD

**Issue by KirillSleta** [akkadotnet/akka.net#2950]
When using a substitution in configuration to set the seed nodes in cluster the following result has been produced:  all memory on a laptop is loaded by akka.net process (up to 9Gb in several minutes) and process is terminated after all

- Akka.Net version I'm using - netcore branch https://github.com/akkadotnet/akka.net/tree/v1.3  
- windows 10 netstandart1.6 
- unit test to reproduce the issue:
[Fact]
        public void Can_concatenate_substituted_unquoted_string_OOM()
        {
            var hocon = @"akka.cluster.name = rucluster
  akka.cluster.seed-nodes =[akka.tcp://${akka.cluster.name}@127.0.0.1:4053] ";
            Assert.Equal("[akka.tcp://rucluster@127.0.0.1:4053", ConfigurationFactory.ParseString(hocon).GetString("akka.cluster.seed-nodes"));
        }

**Comment by rogeralsing** [comment]
@alexvaluyskiy 
I did some work on substitution in the old "HOCON" repo (very long ago)
Was any of that ever merged over to the core repo?

**Comment by alexvaluyskiy** [comment]
@rogeralsing We have a support for substitution, but it is quite limited here and in the Hocon repo.

@KirillSleta Actually there are two different bugs.
```
[Fact]
public void Can_substitute_with_concated_string()
{
	var hocon = @"
		akka.cluster.name = cluster
		akka.cluster.seed-node = ""akka.tcp://${akka.cluster.name}@127.0.0.1:4053""";

	var config = ConfigurationFactory.ParseString(hocon);
	config.GetString("akka.cluster.seed-node").Should().Be("akka.tcp://cluster@127.0.0.1:4053");
}

[Fact(Skip = "throws OutOfMemoryException")]
public void Can_parse_unquoted_string_list()
{
	var hocon = @"akka.cluster.seed-nodes = [akka.tcp://Cluster@127.0.0.1:4053]";

	var config = ConfigurationFactory.ParseString(hocon);
	config.GetStringList("akka.cluster.seed-nodes").Should().Contain("akka.tcp://Cluster@127.0.0.1:4053");
}
```

**Comment by KirillSleta** [comment]
@alexvaluyskiy thanks!
