### ISSUE TITLE
Add a section detailing remoting config

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/akka.net#2979]
We need to add the remoting configuration to the docs. Ideally in such a way that its self-updating. But at the same time will be indexed by the site-search. 

The added value here is that it helps bring awareness to people who are learning what remoting is all about. And it helps with searching for solutions if you run into problems: For example https://github.com/akkadotnet/akka.net/issues/796#issuecomment-322227012

The config can be found here:
https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Remote/Configuration/Remote.conf

**Comment by sean-gilliam** [comment]
DocFX has an include file directive

https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#file-inclusion

**Comment by sean-gilliam** [comment]
Closed by #3388
