### ISSUE TITLE
Add a section detailing Testkit config

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/akka.net#2990]
We need to add the TestKit configuration to the docs. Ideally in such a way that its self-updating. But at the same time will be indexed by the site-search.

https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.TestKit/Configs/TestScheduler.conf

**Comment by sean-gilliam** [comment]
DocFX has an include file directive

https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#file-inclusion

**Comment by Danthar** [comment]
Won't work as you expect. 
``[!code-json[ConfigReference](path/reference.conf)]`

Works better

**Comment by sean-gilliam** [comment]
Closed by #3388
