### ISSUE TITLE
Add a section detailing default persistence config

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/akka.net#2991]
We need to add the default Persistence configuration to the docs. Ideally in such a way that its self-updating. But at the same time will be indexed by the site-search.

https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Persistence/persistence.conf

**Comment by sean-gilliam** [comment]
DocFX has an include file directive

https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#file-inclusion

**Comment by sean-gilliam** [comment]
Closed by #3388
