### ISSUE TITLE
Cluster client example fails at runtime (is not an 'ExtensionId', skipping...)

### ISSUE THREAD

**Issue by jameswilddev** [akkadotnet/akka.net#3006]
I am following the example/tutorial at http://getakka.net/articles/clustering/cluster-client.html#an-example, which recommends adding the line:

    akka.extensions = ["Akka.Cluster.Tools.Client.ClusterClientReceptionist"]

to your HOCON.  However, after doing this, I see errors during startup:

	[ERROR][18/08/2017 08:43:05][Thread 0010][ActorSystem(Repro)] [Akka.Cluster.Tools.Client.ClusterClientReceptionist] is not an 'ExtensionId', skipping...
	Cause: Unknown

I've had a look at the code which generates this error:

https://github.com/akkadotnet/akka.net/blob/a478c5e8c8d5de97dcf7bcea7e2a80fbaa5e6cc8/src/core/Akka/Actor/Internal/ActorSystemImpl.cs#L270-L277

This seems to take the strings in akka.extensions and look them up as types using Type.GetType.  This part fails as there is no assembly name (change the configuration to `akka.extensions = ["Akka.Cluster.Tools.Client.ClusterClientReceptionist, Akka.Cluster.Tools"]` and it can now find the type).  

But then, a subsequent check fails; the type specified needs to implement Akka.Actor.IExtensionId, which Akka.Cluster.Tools.Client.ClusterClientReceptionist does not:

https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterClientReceptionist.cs#L20

Am I doing something wrong?

Thanks.

**Comment by Horusiath** [comment]
Have you tried to use `Akka.Cluster.Tools.Client.ClusterClientReceptionistExtensionProvider, Akka.Cluster.Tools`?

**Comment by jameswilddev** [comment]
Thanks, that's what I was looking for, but I was searching for direct implementations of IExtensionId in the namespace rather than abstract classes.
