### ISSUE TITLE
i want use 1.5 in the unity3d 2017,but..

### ISSUE THREAD

**Issue by cnbryan** [akkadotnet/akka.net#3014]
i inport the 1.5 into the unity3d 2017
but it only work in editor, can not build it.
the System.Collections.Immutable.dll can not used.
can i get some help?

**Comment by alexvaluyskiy** [comment]
Unity3D is not supported at the moment

**Comment by cnbryan** [comment]
but can run in the editor player, only can not build

**Comment by Arkatufus** [comment]
When you say you can not build, does that mean it failed when you click the build button, or when you tried to run the game?

**Comment by cnbryan** [comment]
unity3d player view is ok
build is not ok

**Comment by Arkatufus** [comment]
fail to compile build or can not run exe

**Comment by cnbryan** [comment]
fail to compile build and can not run exe

**Comment by Arkatufus** [comment]
have you tried copying the dll to the assets/plugins directory?

**Comment by Arkatufus** [comment]
Maybe you need to use the Mono version of System.Collections.Immutable.dll?
BTW,  this is out of scope of what we can support. Officially, we don't support Unity as a target platform.

**Comment by cnbryan** [comment]
i will try it,tks

**Comment by cnbryan** [comment]
the bad news...
used Mono version of System.Collections.Immutable.dll....
Can Build  Successful;
But Run Error...
Some things are different...
-------------
FieldAccessException: Field `System.Collections.Immutable.ImmutableDictionary`2:Empty' is inaccessible from method `Akka.Actor.Internal.EmptyChildrenContainer:.cctor ()'

Rethrow as TypeInitializationException: The type initializer for 'Akka.Actor.Internal.EmptyChildrenContainer' threw an exception.
Akka.Actor.ActorCell..ctor (Akka.Actor.Internal.ActorSystemImpl system, Akka.Actor.IInternalActorRef self, Akka.Actor.Props props, Akka.Dispatch.MessageDispatcher dispatcher, Akka.Actor.IInternalActorRef parent) (at <97a7ae8416674263923a4807be4bf3ef>:0)
Akka.Actor.LocalActorRef+<>c__DisplayClass7_0.<.ctor>b__0 (Akka.Actor.LocalActorRef self) (at <97a7ae8416674263923a4807be4bf3ef>:0)
Akka.Actor.LocalActorRef..ctor (Akka.Actor.ActorSystem system, Akka.Actor.Props props, Akka.Dispatch.MessageDispatcher dispatcher, System.Func`1[TResult] createMailbox, Akka.Actor.IInternalActorRef supervisor, Akka.Actor.ActorPath path, System.Func`2[T,TResult] createActorCell) (at <97a7ae8416674263923a4807be4bf3ef>:0)
Akka.Actor.LocalActorRef..ctor (Akka.Actor.Internal.ActorSystemImpl system, Akka.Actor.Props props, Akka.Dispatch.MessageDispatcher dispatcher, System.Func`1[TResult] createMailbox, Akka.Actor.IInternalActorRef supervisor, Akka.Actor.ActorPath path) (at <97a7ae8416674263923a4807be4bf3ef>:0)
Akka.Actor.RootGuardianActorRef..ctor (Akka.Actor.Internal.ActorSystemImpl system, Akka.Actor.Props props, Akka.Dispatch.MessageDispatcher dispatcher, System.Func`1[TResult] createMailbox, Akka.Actor.IInternalActorRef supervisor, Akka.Actor.ActorPath path, Akka.Actor.IInternalActorRef deadLetters, System.Collections.Generic.IReadOnlyDictionary`2[TKey,TValue] extraNames) (at <97a7ae8416674263923a4807be4bf3ef>:0)
Akka.Actor.LocalActorRefProvider.CreateRootGuardian (Akka.Actor.Internal.ActorSystemImpl system) (at <97a7ae8416674263923a4807be4bf3ef>:0)
Akka.Actor.LocalActorRefProvider.Init (Akka.Actor.Internal.ActorSystemImpl system) (at <97a7ae8416674263923a4807be4bf3ef>:0)
Akka.Remote.RemoteActorRefProvider.Init (Akka.Actor.Internal.ActorSystemImpl system) (at <104702e5b6bc48239382e187dba753ec>:0)
Akka.Actor.Internal.ActorSystemImpl.Start () (at <97a7ae8416674263923a4807be4bf3ef>:0)
Akka.Actor.ActorSystem.CreateAndStartSystem (System.String name, Akka.Configuration.Config withFallback) (at <97a7ae8416674263923a4807be4bf3ef>:0)
Akka.Actor.ActorSystem.Create (System.String name, Akka.Configuration.Config config) (at <97a7ae8416674263923a4807be4bf3ef>:0)
Net.Start () (at Assets/Net.cs:34)

**Comment by Arkatufus** [comment]
It seems like the mono implementation of ImmutableDictionary sets the Empty field as internal.
What you can do is, download the mono source from https://github.com/mono/ImmutableCollections, change the Empty field into a read only property or constant and compile it for your project.

**Comment by cnbryan** [comment]
yes, del the read only, itis work.
but i donot know There are other mistakes

**Comment by cnbryan** [comment]
i used akka.net 1.5;
the 1.3 is use dotnetty, it is not support sunity3d

**Comment by cnbryan** [comment]
the 1.5 is work;
but the 1.3 is not ok...
---------------same code,just change the dll for 1.3
TaskCanceledException: A task was canceled.
Rethrow as AggregateException: One or more errors occurred.
System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2157)
System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:562)
System.Threading.Tasks.Task`1[TResult].get_Result () (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:532)
Akka.Event.LoggingBus.AddLogger (Akka.Actor.Internal.ActorSystemImpl system, System.Type loggerType, Akka.Event.LogLevel logLevel, System.String loggingBusName, System.TimeSpan timeout) (at <04abce1a076a4de798e918663142d699>:0)
Akka.Event.LoggingBus.StartDefaultLoggers (Akka.Actor.Internal.ActorSystemImpl system) (at <04abce1a076a4de798e918663142d699>:0)
Rethrow as ConfigurationException: Logger [Akka.Event.DefaultLogger] specified in config cannot be loaded: System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
--- End of inner exception stack trace ---
System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2157)
System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:562)
System.Threading.Tasks.Task`1[TResult].get_Result () (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:532)
Akka.Event.LoggingBus.AddLogger (Akka.Actor.Internal.ActorSystemImpl system, System.Type loggerType, Akka.Event.LogLevel logLevel, System.String loggingBusName, System.TimeSpan timeout) (at <04abce1a076a4de798e918663142d699>:0)
Akka.Event.LoggingBus.StartDefaultLoggers (Akka.Actor.Internal.ActorSystemImpl system) (at <04abce1a076a4de798e918663142d699>:0)
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
Akka.Event.LoggingBus.StartDefaultLoggers (Akka.Actor.Internal.ActorSystemImpl system) (at <04abce1a076a4de798e918663142d699>:0)
Akka.Actor.LocalActorRefProvider.Init (Akka.Actor.Internal.ActorSystemImpl system) (at <04abce1a076a4de798e918663142d699>:0)
Akka.Remote.RemoteActorRefProvider.Init (Akka.Actor.Internal.ActorSystemImpl system) (at <2a9a07cc138647759d398248296d28c9>:0)
Akka.Actor.Internal.ActorSystemImpl.Start () (at <04abce1a076a4de798e918663142d699>:0)

---------------

**Comment by Arkatufus** [comment]
What do you mean by 1.5 and 1.3?

**Comment by cnbryan** [comment]
And the other  problem:
in the akka.remote.dll
some where import system.windows.form.dll
it is can not run at unity3d android ios app

**Comment by Danthar** [comment]
There is no akka.net version 1.5 We have just released 1.3.
And akka remote does not reference system.windows.forms.dll. Nor do its dependencies. 
So if you are seeing system.windows.forms.dll I am 99% certain its your code.

**Comment by cnbryan** [comment]
i just import dll into unity3d whitout my code;
when i del the akka.remote  ; unity3d build ok! ..

**Comment by Arkatufus** [comment]
Please see https://github.com/Arkatufus/Akka.Unity.Sample for a working sample on building Akka.Net in Unity3D.
