### ISSUE TITLE
Set up redirects for the removed documentation pages

### ISSUE THREAD

**Issue by stijnherreman** [akkadotnet/akka.net#3037]
As mentioned in akkadotnet/getakka.net#251, a bunch of documentation pages have been moved.
Is it possible to set up redirects? This would benefit users coming from a search engine (which now contain a bunch of broken links) and users who point at documentation in their source code or internal documentation.

If this isn't possible, I think the error message should be improved to point users to the new documentation index. The current one isn't very helpful:

> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by Danthar** [comment]
Unfortunately its an artifact of the docfx documentation stuff. We are currently publishing a static file only site. Regarding the error page. Not sure how much we can do there, there might be a setting in docfx which we can use ? (PR's are welcome :D)

Regarding the redirect. Yeah this is something we should do. A simple redirect from getakka.net/docs/* to getakka.net/articles/<some default landing page> would help alot.

/cc @heynickc

**Comment by Aaronontheweb** [comment]
@stijnherreman yeah part of the issue here is that DocFx doesn't offer many of the actual amenities you'd want for properly migrating a website, so we might have to manually come up with something there....

**Comment by Danthar** [comment]
We are hosting in IIS rights. A simple IIS redirect Rule could go a long way?

**Comment by Aaronontheweb** [comment]
Yeah actually, that might be possible. We're using Azure Websites. That'd be a much easier solution.

**Comment by Aaronontheweb** [comment]
@Danthar there we go, explains how to do it via a `.config` file: https://stackoverflow.com/questions/18004077/azure-website-301-redirect-where-do-i-put-it
