### ISSUE TITLE
Automatic HOCON reference.conf loading

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3054]
In order to better resolve issues like:

https://github.com/akkadotnet/akka.net/issues/3031
https://github.com/akkadotnet/akka.net/issues/3051

I propose that we do the following:

* Standardize on having exactly one `reference.conf` file per NuGet package and always stored in the same place.
* Automatically scan all assemblies in the same folder as the root `Akka.dll` and if they match a known assembly name / convention (i.e. core Akka.NET assemblies or Persistence plugins following the `Akka.Persistence.*` convention), chain those configurations together in a topologically sorted way.
* Prepend the user-defined configuration to that fallback chain.
* Delete all of our configuration loading / injection hacks from the code base.

This is how the JVM does it using the `reference.conf` files that ship as parts of the JAR files they deliver with each module, loaded via some of the tools in the stand-alone HOCON package: 
https://github.com/typesafehub/config/blob/master/config/src/main/java/com/typesafe/config/ConfigFactory.java
https://github.com/typesafehub/config/blob/master/config/src/main/java/com/typesafe/config/DefaultConfigLoadingStrategy.java#L25

This will avoid many of the issues we have with lots of plugins and forcing the end-user to have to manually include fallbacks for built-in libraries in their bootstrapping code.

**Comment by ismaelhamed** [comment]
What about having the HOCON section moved to its own file (ie, application.conf) too?

**Comment by Aaronontheweb** [comment]
Closing this - moved the issue to https://github.com/akkadotnet/HOCON/issues/48
