### ISSUE TITLE
The type of the materialised value in the Flow returned by Bidiflow JoinMat() is incorrect

### ISSUE THREAD

**Issue by ianclegg** [akkadotnet/akka.net#3055]
The generic type parameters of the flow returned from the current implementation of Bidiflow's JoinMat method are incorrect.

The type of the materialised value in the new flow should reflect the return type of the user supplied `combine` functor. By using the wrong type, the current implementations forces the combine function to always return the same type as the a Keep.Left.

Current method signature:
```public Flow<TIn1, TOut2, TMat> JoinMat<TMat2, TMat3>(Flow<TOut1, TIn2, TMat2> flow, Func<TMat, TMat2, TMat3> combine)```

Correct method signature:
```public Flow<TIn1, TOut2, TMat3> JoinMat<TMat2, TMat3>(Flow<TOut1, TIn2, TMat2> flow, Func<TMat, TMat2, TMat3> combine)```

Some minor changes are required in the method to ensure the type is propagated.

**Comment by Aaronontheweb** [comment]
closed by #3056
