### ISSUE TITLE
PersistenceMessageSerializer fails with wrong exception if non-supported type provided

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#3067]
If I send a string into `PersistenceMessageSerializer` I except that I get an error `ArgumentException`, but it fails on this line instead:

https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Persistence/Serialization/PersistenceMessageSerializer.cs#L35

**Comment by Danthar** [comment]
Plugins are expected to use the `IPersistentRepresentation`

**Comment by alexvaluyskiy** [comment]
Serializer expects `IMessage`, like `IPersistenceRepresentation` or `AtLeastOnceDeliverySnapshot`. But if we provide some different type, it should be handled properly. We should not call `GetGenericTypeDefinition()` on non-generic types

**Comment by alexvaluyskiy** [comment]
We should change it to
```
if (obj.GetType().IsGenericType && obj.GetType().GetGenericTypeDefinition() == typeof(PersistentFSM.PersistentFSMSnapshot<>))
{
}
```
