### ISSUE TITLE
Fix MNTK specs for DData: DurableDataSpec

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#3076]
Code needs to be updated - last port was before delta-state CRDT PR:

- [x] Durable_CRDT_should_work_in_a_single_node_cluster
- [x] Durable_CRDT_should_work_in_a_multi_node_cluster
- [x] Durable_CRDT_should_be_durable_after_gossip_update
- [x] Durable_CRDT_should_handle_Update_before_Load
- [x] Durable_CRDT_should_stop_Replicator_if_Load_fails
- [x] Durable_CRDT_should_reply_with_StoreFailure_if_store_fails

**Comment by Arkatufus** [comment]
Need to wait for #4414 for the fix to work
