### ISSUE TITLE
Add DData shards to Akka.Cluster.Sharding

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#3081]
Akka.Cluster.Sharding can work in one of two modes:

- Using persistent shard (utilizing `PersistentShardCoordinator` and `PersistentShard`) - **this is the only mode we have in .NET right now**.
- Using distributed data CRDTs - this is current default for akka.cluster.sharding module on the JVM.

The case is that we need to port DDataShard to C#. The design problem is that on the JVM both `PersistentShard` and `DDataShard` inherit from common `Shard` actor, which has a lot of cluster sharding logic in itself - something hard to embed. `PersistentShard` extending `Shard` is possible thanks to the fact that `PersistentActor` is Scala trait - something we cannot achieve in .NET.

My initial approach was to modify Akka.Persistence to be able to be exposed as embedded component rather than a class to inherit from, while maintaining backward compatibility (see #2917). But to achieve this goal other options are also welcome.

**Comment by Aaronontheweb** [comment]
I think you've actually done this already, although it's still in a beta stage.
