### ISSUE TITLE
Specify persistence format for Akka.DistributedData.LightningDb

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#3084]
To avoid confusion, that happened in Akka.Persistence serialization, we should take a lesson and setup up front expectations about stored binary payload for Akka DData CRDTs. JVM version uses protobuf - if you feel brave you may try to port [their implementation](https://github.com/akka/akka/blob/master/akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatedDataSerializer.scala) (yes, this is handwritten code). Good luck with that.

In short: the problem of protobuf is that it doesn't support generics, while CRDTs are highly generic data structures. 

- Current default is hyperion - it deals well with remote serialization, but it has not been designed for long-living persistence.
- Another option is to use JSON+GZip (VectorClocks use a lot of repeatable strings for node addresses, therefore GZip is a viable option here). For JSON.NET a custom converter will be necessary.
- Another (most liked by me) option is to use Microsoft Bond - which sort of resembles Thrift format, but it has support for generics and all .NET standard data types. However it's a next serializer in Akka.NET space...

This will also be necessary for `akka.cluster.sharding.remember-entities=on` option if akka.cluster.sharding is going to support DData (see: #3081).

**Comment by Aaronontheweb** [comment]
This got fixed back in 1.4[.1|.2]
