### ISSUE TITLE
ClusterShardingMessageSerializer Exception after upgrade from 1.2.0 to 1.3.1 

### ISSUE THREAD

**Issue by amichel** [akkadotnet/akka.net#3087]
After upgrading my project with sharded cluster from 1.2.0 to 1.3.1 and switching serializer from wire to Hyperion, I get this exception at ClusterSharding.Get(system) :

**> Attempt by method 'Akka.Cluster.Sharding.Serialization.ClusterShardingMessageSerializer..ctor(Akka.Actor.ExtendedActorSystem)' to access method 'Akka.Serialization.SerializerIdentifierHelper.GetSerializerIdentifierFromConfig(System.Type, Akka.Actor.ExtendedActorSystem)' failed.**

My config looks like:
provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"
serializers {
wire = "Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion"
}
serialization-bindings {
"System.Object" = wire
}
no special entries or custom fallbacks for sharding

**Comment by amichel** [comment]
When I reference assemblies built from dev branch it doesn't happen. When I switch back to nuget I get same exception again.

**Comment by Aaronontheweb** [comment]
This is a confirmed issue with the way we've using the `SerializerId` for the dedicated Cluster.Sharding serializer.... We'll see about getting it fixed in 1.3.2

**Comment by Aaronontheweb** [comment]
@amichel this should be fixed in tonight's nightly build; would you mind giving that a try and let us know if it resolves your issue? http://getakka.net/community/getting-access-to-nightly-builds.html

**Comment by Aaronontheweb** [comment]
Nightlies run at midnight UTC usually, so it should be ready for you guys by tomorrow AM.

**Comment by amichel** [comment]
Great. Will give it a try in the morning. Actually like I mentioned, it
did't happen to me when I referenced debug mode assemblies from dev branch,
only with nuget packages.
So I used this as kind of workaround to avoid downgrading solution, but of
course I can't checkin like that.

**Comment by amichel** [comment]
I can confirm that this bug was solved when using nightly build (beta426).

I have other issues now preventing cluster from starting related to SQL persistence changes. Will try to dig more info on them.

**Comment by Aaronontheweb** [comment]
@amichel are you using the latest Akka.Persistence.Sql driver? We just pushed out an update for those packages last week

**Comment by amichel** [comment]
I updated all packages from nightly build. Will try test with empty db to
isolate replaying of events.
