### ISSUE TITLE
Release netstandard1.6 build is Optimize false

### ISSUE THREAD

**Issue by kennethito** [akkadotnet/akka.net#3088]
Is there a reason for this?

https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Akka.csproj#L64

**Comment by Aaronontheweb** [comment]
@kennethito yes, the .NET Standard 1.6 compiler had an optimization bug that broke the Akka.Streams test suite. This is supposed to be fixed in the 2.0 compiler so we'll turn optimization back on once #3066 is merged.

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy this was resolved via https://github.com/akkadotnet/akka.net/pull/3066, no?

**Comment by alexvaluyskiy** [comment]
yes
