### ISSUE TITLE
Ask does not set exception on the underlying TaskCompletionSource when callee responds with Failure

### ISSUE THREAD

**Issue by ondrejpialek** [akkadotnet/akka.net#3091]
Hello,

I am running Akka.net 1.3.0 on .NET Core, and came across the following issue:

I am calling `Ask<TResult>` from outside of the system and would like to have Ask throw an exception at the call site if the underlying actor responds with `new Failure() { Exception = ex }` instead of `TResult`.

This behaviour is described in the docs:

> To complete the Task with an exception you need send a Failure message to the sender. This is not done automatically when an actor throws an exception while processing a message.

- http://getakka.net/articles/actors/receive-actor-api.html#ask-send-and-receive-future
- http://getakka.net/articles/actors/untyped-actor-api.html#ask-send-and-receive-future

This feature is however not implemented, if you look at https://github.com/akkadotnet/akka.net/blob/a478c5e8c8d5de97dcf7bcea7e2a80fbaa5e6cc8/src/core/Akka/Actor/ActorRef.cs#L129 the `FutureActorRef` sets the result of the task without inspecting whether the message is a `Failure`.

This then breaks `Ask<TResult>` as the underlying extension method tries to cast `Failure` to `TResult`.

Unless I am mistaken the following modification could be used:
```
if (message is Failure failure) {
    _result.TrySetException(failure.Exception ?? new SomeDefaultException())
} else {
    _result.TrySetResult(message);
}
```

I am assuming this is still a behaviour you want to support. If not then the docs should be updated so that they don't put peoples hopes up :)

Many thanks,
Ondrej.

**Comment by ondrejpialek** [comment]
Upon further inspection of the source code it seems like `Status.Failure` is used instead internally among Actors to signal an error in processing. If this feature is to be implemented `Status.Failure` would probably be a better fit.

**Comment by marcpiechura** [comment]
This will probably be fixed in https://github.com/akkadotnet/akka.net/pull/3339 , see also https://github.com/akkadotnet/akka.net/pull/3329 for detailed discussion
