### ISSUE TITLE
Move Hocon parser to separate package

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#3093]
This was already discussed several times over past few months. The idea here is to move HOCON-handling code from `Akka.Configuration` namespace to the separate package - I think that the proposition for package/assembly/project name was simply `Hocon`. Ideally it could be a target of some code cleanups, performance optimizations etc. 

My personal idea was also to evaluate usefulness of implementing Hocon in terms of [Microsoft.Extensions.Configuration.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Abstractions/) library. This is related to what I've proposed in #3050, but it's a "nice to have" - not a crux of this issue.

**Comment by marcpiechura** [comment]
@Aaronontheweb you’re working on this one right? So we could remove up for grabs

**Comment by Aaronontheweb** [comment]
correct!

**Comment by boekabart** [comment]
Any update on this, @Aaronontheweb ? We've recently started doing dotnet core style applications, and would love to use HOCON not just for Akka but for everything, but in the MS.Extensions.Configuration way, and we wondering if we should pick up creating a ConfigurationProvider for this, or depend on/wait for this to happen here or in #3050 .

**Comment by Aaronontheweb** [comment]
@boekabart this is finished - HOCON v1.0.0 and HOCON.Extensions.Configuration is now live on NuGet https://www.nuget.org/packages/Hocon/1.0.0
