### ISSUE TITLE
Expose the 'areEqual' parameter through the 'ExpectMsgAllOf' methods

### ISSUE THREAD

**Issue by stijnherreman** [akkadotnet/akka.net#3098]
File: https://github.com/akkadotnet/akka.net/blob/bc3fdb827dd5dc84827bc434659249db24aea819/src/core/Akka.TestKit/TestKitBase_Expect.cs

`InternalExpectMsgAllOf` has `Func<T, T, bool> areEqual = null` as a parameter, but it is not exposed through the public `ExpectMsgAllOf` methods.

Is this omission intentional, or can the parameter be added to the public methods? Without this parameter, it is necessary to override `Equals` and `GetHashCode` just so the tests would work.

**Comment by nbparrell** [comment]
I will be working on this.

**Comment by nbparrell** [comment]
Hey @marcpiechura want to clarify what is desired by making this change.

I believe they are asking for the code to be changed to public IReadOnlyCollection<T> ExpectMsgAllOf<T>(TimeSpan max, Func<T, T, bool> areEqual = null, params T[] messages)
        {
            max.EnsureIsPositiveFinite("max");
            var dilated = Dilated(max);
            return InternalExpectMsgAllOf(dilated, messages);
        }

by doing this I want to confirm that I am exposing the Func<T, T, bool> areEqual = null and achieving the desired purpose.

**Comment by stijnherreman** [comment]
@nbparrell note that there are two overloads of `ExpectMsgAllOf`, and you need to pass the parameter to `InternalExpectMsgAllOf`. Thanks for looking into this 😃

**Comment by nbparrell** [comment]
@stijnherreman Okay thanks, when you were talking about getting tests to work was there a specific test set in mind that you were having trouble with or was it specifically for personal testing that you were having trouble. If personal do you have an example of the code you were testing so that I can test changes against to confirm that it is working as desired.
