### ISSUE TITLE
`Sender` is not preserved in `ReceivePersistentActor.Persist` callback

### ISSUE THREAD

**Issue by andersstorhaug** [akkadotnet/akka.net#3105]
As outlined in the documentation [here](http://getakka.net/articles/persistence/event-sourcing.html):

>  An event handler may close over persistent actor state and mutate it. The sender of a persisted event is the sender of the corresponding command. This allows event handlers to reply to the sender of a command (not shown).

However, when I attempt to do this, from within a `Persist` callback, `Sender` is `akka://System/deadLetters`. The `Sender` property however is correct when accessed in the outer command handler.

As an aside, simple workaround here is to use a closure over `Sender` in the `Persist` callback.

This is with FX 4.7 and Akka 1.3.1.

**Comment by ismaelhamed** [comment]
@andersstorhaug  This was fix via #3779 for the `BatchingJournal`. And for the classic journal this shouldn't be an issue at all at this point.

**Comment by Aaronontheweb** [comment]
Closed as part of 1.3.14
