### ISSUE TITLE
Akka.NET Platforms

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#3114]
# Akka.NET Platforms

*Clarification: it is for discussion only. It does not mean that Akka.NET Team will implement it. We just want to hear a feedback*

## Current status
Currently we are targeting three platforms
- .NET Framework 4.5 (via net45 target on Windows)
- .NET Core 1.1 (via .NET Standard 1.6 target on Windows and Linux)
- Mono 5.0 (via net45 target on Linux)

We are testing .NET Standard 1.6 under .NET Core 1.1 on Windows and Linux. 

We are testing .NET 4.5 target under .NET Framework 4.5.2 on Windows, and on Mono 5.0 on Linux

## Plans
Ine the one of the next major versions we could start target .NET Standard 2.0 and to support these platforms
- .NET Framework 4.6.1 (via .NET Standard 2.0 target)
- .NET Core 2.0 (via .NET Standard 2.0 target)
- Xamarin.iOS
- Xamarin.Android
- Unity

## Xamarin platforms
Xamarin is supporting .NET Standard 2.0, so it should work almost without any changes.

### Questions
- How to test that Akka.NET could work on Xamarin iOS AOT? Is it support to run xunit tests?
- Which TFM to choose, `netstandard2.0` or `xamarinios10`/`monoandroid` ?
- We could use Xamarin Test Cloud, but it is not exactly what we want to do. We only need some type of API Checker which checks that we don't use some APIs (like IL Emit)

### Which modules could be ported
- Akka
- Akka.Streams
- Akka.Testkit

### Platform limitations
- [Xamarin Android](https://developer.xamarin.com/guides/android/advanced_topics/limitations/)
- [Xamarin iOS](https://developer.xamarin.com/guides/ios/advanced_topics/limitations/)

### Real-world scenarious
- TODO

## Unity platform
Unity is an even more restricted platform than Xamarin. It does not support NuGet and it does not have specific TFM for Unity. The most of Akka.NET dependencies don't work on Unity at the moment. And almost all supported platforms are using AOT compilation with add more limitations.

### Questions
- Should we publish the code into Unity's Asset Store, or distribute it as a source code on github?
- How to test that Akka.NET could work on Unity/IL2CPP? Is it support to run xunit tests?
- Which TFM to choose?

### Which modules could be ported
- Akka
- Akka.Streams
- Akka.Testkit

### Platform limitations
- https://docs.unity3d.com/Manual/ScriptingRestrictions.html

### Real-world scenarious
- TODO

**Comment by kennethito** [comment]
I think there's some confusion here.  

First net461, netcoreapp2.0, and xamarin are already supported by the netstandard1.6 target.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Moving to netstandard2.0 will allow you to use the full api surface of 2.0, but it will actually reduce the number of places you can use akka.net.  For instance, mono 5.0 will no longer be supported, mono 5.4 (currently alpha) will be required.  This is because mono 5.0 doesn't implement all the api's required by netstandard2.0.  You actually want to target the lowest possible netstandard that you are able to in order to maximize the number of places that akka.net can be used.

**Comment by alexvaluyskiy** [comment]
> You actually want to target the lowest possible netstandard that you are able to in order to maximize the number of places that akka.net can be used.

I know that and I watched a lot of videos from @terrajobst but it is only in a theory. In practice, ASP.NET team dropped `netstandard1.x` in all `Microsoft.AspNet.*`, `Microsoft.Extensions.*`, `Microsoft.Data.Sqlite` because they don't want to support it.

> For instance, mono 5.0 will no longer be supported, mono 5.4 (currently alpha) will be required

Akka.NET has limited support for Mono and usually supports only the latest version. And right now `.Net Core` is recommended platform for Linux/MacOs.

**Comment by kennethito** [comment]
There's nothing wrong with moving to 2.0.  I just wanted to make sure it was a properly informed decision since the majority of platforms you plan to support by moving to 2.0 are already supported.  

Additionally you will be removing support for netcoreapp < 2.0, mono < 5.4, xamarin ios < 10.14, xamarin android < 10.14

**Comment by kennethito** [comment]
RE: Which TFM to choose, netstandard2.0 or xamarinios10/monoandroid

I vote netstandard.  No need to add additional frameworks unless there is some specific reason to do so.

**Comment by annymsMthd** [comment]
We are currently running Akka.net in mono 5.0.1.1 in about 30 remote systems soon to be 330. We are also running Akka.net in Android in over 500 deployed systems. It would be nice to have the lowest netstandard possible. I know mono has some breaking changes around the mkbundler in newer versions and netstandard2.0 would force us to deal with that. Unless there is some api you need in the new standard I'd say it's not worth it.

**Comment by Aaronontheweb** [comment]
closing this issue, as we adopted .NET Standard 2.0 some time ago and in our published roadmap we've added plans to bring back dual targeting for .NET 5 / .NET 6 in the near future as part of Akka.NET 2.0.
