### ISSUE TITLE
CRUD operations

### ISSUE THREAD

**Issue by codenakama** [akkadotnet/akka.net#3117]
Hi.

I'm learning Akka.Net and loving it so far. So much I want to use it on my next project. However, coming from a classic ASP.NET background I am a bit confused about how to persist and read data in AKKA.
What are the right patterns? Are there any examples of CRUD operations?
Can/Should I use entity framework?

For example, should I have a "ProductsActor" that has a DbContext?

Any insight would be useful and I hope my question also makes sense.

**Comment by Silv3rcircl3** [comment]
Hi @codenakama, please use [Gitter chat](https://gitter.im/akkadotnet/akka.net) for questions.

**Comment by lugrugzo** [comment]
@codenakama, Did you able to find any useful example codebase about this topic?

**Comment by codenakama** [comment]
@lugrugzo I didnt find anything in specific I just went with my assumptions and what I was confirmed with in the Gitter chat. Just build your controllers as usual and then pass info to your actors to handle tasks. sometimes you will find that you don't need a controller - for example when you need to pass data from a microservice to another - you can just have your actors communicate remotely.
