### ISSUE TITLE
DistributedPubSub does not Send messages to remotely deployed actors

### ISSUE THREAD

**Issue by sbacquet** [akkadotnet/akka.net#3129]
Provided I have 2 actors running in a cluster :
- 1 locally deployed on node1, path = /user/MyActor
- 1 remotely deployed from node1 onto node2, path = /user/MyActor

When I do : 
`mediator.Tell(new SendToAll("/user/MyActor", "Hello"));`

I expect "Hello" to be sent on both actors. But the actor deployed on node1 is the only one to receive the message.

After debugging, it appears that the actor remotely deployed onto node2 is registered in the DistributedPubSub's mediator registry with path "/remote/.../user/MyActor", hence not matching the search key "/user/MyActor".

To fix it, I suggest to remove the "/remote/..." part from the path key when registering the actor ref in DistributedPubSub mediator's registry.

Akka.Net version : 1.3.1
Platform : Windows 7 Pro 64b
.NET : 4.5

**Comment by sbacquet** [comment]
Added to the PR a unit test revealing the issue

**Comment by Aaronontheweb** [comment]
Sorry for the delay on this, @sbacquet - going to take a look at your PR again for this soon

**Comment by Aaronontheweb** [comment]
closed via #4207
