### ISSUE TITLE
Why does Akka.TestKit.Xunit depend on a prerelease version of xUnit.net?

### ISSUE THREAD

**Issue by stijnherreman** [akkadotnet/akka.net#3141]
The [current stable version](https://www.nuget.org/packages/Akka.TestKit.Xunit/1.3.1) of Akka.TestKit.Xunit depends on a prerelease version of xUnit.net (>= 2.3.0-beta5-build3769).

Any reason you need to use a prerelease version instead of the stable xUnit.net 2.2.0? Is it feasible to to relax the version restriction?

**Comment by Aaronontheweb** [comment]
cc @alexvaluyskiy on that one
