### ISSUE TITLE
Broken link in intro/what-are-actors.md

### ISSUE THREAD

**Issue by rmcc13** [akkadotnet/akka.net#3143]
There is a link on the [What Are Actors](http://getakka.net/articles/intro/what-are-actors.html#usage-of-message-passing-avoids-locking-and-blocking) page that is not rendered correctly. Attached is a screenshot that shows the broken link.
![screen shot 2017-10-05 at 11 20 38 pm](https://user-images.githubusercontent.com/6742231/31261939-a040e9cc-aa25-11e7-8f0a-b655d07e45ed.png)

**Comment by sbacquet** [comment]
Pull request #3154

**Comment by Aaronontheweb** [comment]
Resolved via #3154
