### ISSUE TITLE
Discussion: Alternative to unreachable nodes in Akka Cluster

### ISSUE THREAD

**Issue by nvivo** [akkadotnet/akka.net#3144]
As I add more nodes to my cluster, I see more and more instability from the cloud providers. VMs get shutdown unexpectedly and replaced by new ones, networking issues come and go, etc. I came to believe depending on clean cluster leave is a luxury we cannot have on public clouds.

A few months ago I made the decision to use auto-down in production with a 10-minute timeout, and decided to not depend on anything that could be an issue with a split-brain scenario and I still believe that was the right decision.

Still, everytime a node goes down due to networking issues, I need to detect it and restart the node because it's auto-downed and I cannot reconnect it later. And then there is still the 10-minute timeout for convergence. I thought about reducing this value, but network issues are quite common on AWS. This is becoming more and more of a problem as the # of nodes go up.

As I look for solutions and automate more, more I think that this an issue that could be avoided. I understand Akka Cluster has some measures to avoid split-brain, and it won't allow nodes to rejoin until restarted, etc. But would it be possible to simply not care about these things? Why not allow a dead node to rejoin? Why after having 2 leaders that become aware of each other, just choose one and merge the cluster? 

It seems the only implication of that is not have some features like cluster singletons, but it is a pretty good price to pay to have a more stable and distributed cluster that doesn't break daily.

I'm not sure if I'm the only one with these problems, but I'm almost looking at removing Akka Cluster and using Akka.Remote + Consul to manage the cluster, but I'd like to know, from people with more knowledge of Akka Cluster, what would it take for me to remove these restrictions and what else would break that I'm not thinking about.

Would it be possible to have a "simpler akka cluster" with less restrictions and more flexibility?

**Comment by Zetanova** [comment]
Please provide, how do you host on aws and if you are using one aws-site only or over multiple cities? 
You can add to the autoscaling-feature a terminate hook, that the node can shutdown itself propertly.
If you are using aws-ecs there is somewhere for a task too.

**Comment by nvivo** [comment]
I'm currently running everything on a single region, in Brazil. I do use auto-scaling,

Currently, if instances are terminated correctly even from auto-scaling policies, they leave the cluster correctly. The issue is when they are terminated by unexpected reasons, like if the machine stop responding. That's where I'm trying to do something. I cannot depend on correct shutdown to keep the cluster working.

**Comment by Aaronontheweb** [comment]
@nvivo there's an event that is published on the `EventStream` called [`ThisActorSystemQuarantinedEvent`](http://getakka.net/api/Akka.Remote.ThisActorSystemQuarantinedEvent.html) - it's an Akka.Remote thing, but IIRC that event should fire in the event that a downed node tries to rejoin the cluster. What I'd do in this scenario is give your service the ability to reboot its `ActorSystem` when this is detected. 

We're in the process of writing some more cluster devOps tooling now and this is something I'm looking at modularizing, but for the time being you can give that a try yourself.

**Comment by Horusiath** [comment]
@nvivo if you're interested, I was doing some [Consul integration](https://github.com/Horusiath/Akka.Cluster.Discovery) in the past: it's not published, but the node discovery and health checks are there. The only missing part is consul-based downing provider. That being said, I know there are issues with the consul itself and it's not a pain-free path.

There are several things that might help you:

1. Tuning auto-down to a lower value (like 60sec), but you need to measure it by yourself.
2. There is a ready PR #3099 which introduces an extra `weakly-up` state - it allows you to join nodes to the cluster without having full convergence. This means you can add new nodes even when there are unreachable ones still waiting to be downed.
3. Writing custom downing provider - I'm going to introduce few of them on time when v1.4 is going to happen.

**Comment by nvivo** [comment]
Hi, first of all sorry for the long delay on replying and thanks for all the feedback.

@Horusiath thanks for the info on consul. I'm still looking for alternatives, and for now I'm just managing as I can. Looks like the weakly up state might help, lets see.

@Aaronontheweb I'll look into that event to see if I can use it.

In the meanwhile, I'll close this issue. I'll open a new one if the provided solutions don't work in the long run.

Thanks.
