### ISSUE TITLE
ASP.NET use-case

### ISSUE THREAD

**Issue by gelambert** [akkadotnet/akka.net#3152]
Hello,

I am using Akka.Net v1.3.1.
I would like to use Akka.Net in an ASP.NET MVC 5.2.3 application.

Two years ago, I developed a similar application with Akka.Net 1.0.4 and I used the code below to shutdown my ActorSystem.
```
protected void Application_End(object sender, EventArgs e)
{
        ActorSystem.Shutdown();
}
```

However, I have seen that the Shutdown method is now obsolete.
I found [this link](http://getakka.net/articles/intro/use-case-and-deployment-scenarios.html) which helps me but it does not describe how to shutdown the ActorSystem.
Could you help me with that ?

Thanks.

**Comment by Danthar** [comment]
`system.Terminate().Wait();` or `await system.Terminate();`

**Comment by gelambert** [comment]
Thank you sir.
I am not sure if I can mark the `Application_End ` method with the async modifier so I will use `system.Terminate().Wait();`
