### ISSUE TITLE
AtLeastOnceDeliveryReceiveActor has issues with consistent-hashing-group routers

### ISSUE THREAD

**Issue by jalchr** [akkadotnet/akka.net#3159]
The "router" setup already working fine in my cluster. Once I added the "Persistence" features, it didn't work as expected. Somehow the Deliver method fails to "use" the router.

I'm trying to make the Akka.Persistence.AtLeastOnceDeliveryReceiveActor v1.3.1
```
Deliver(commandRouter.Path,
                    messageId =>
                    new ReliableDeliveryEnvelope<StartJob>(startJob, messageId));
```
Where commandRouter is defined like this
```
var commandRouter = ClusterSystem.ActorOf(Props.Empty.WithRouter(FromConfig.Instance), "tasker");
```
and has following hocon config:
```
/tasker {
                  router = consistent-hashing-group
                  routees.paths = ["/user/api"]
                  virtual-nodes-factor = 8
                  cluster {
                      enabled = on
                      max-nr-of-instances-per-node = 1
                      allow-local-routees = on
                      use-role = web
                  }
```
The message never reaches the destination actor. If I use an actor instead of a router, it works fine !
So this works
```
Deliver(SystemActors.ApiMaster.Path,
                    messageId =>
                    new ReliableDeliveryEnvelope<StartJob>(startJob, messageId));
```

This is what I get from the logs
```
2017-10-18 12:09:36,257 [35] WARN  Akka.Routing.ConsistentHashingRoutingLogic - Message [ReliableDeliveryEnvelope`1] must be handled by hashMapping, or implement [IConsistentHashable] or be wrapped in [ConsistentHashableEnvelope]
2017-10-18 12:09:41,939 [41] WARN  Akka.Routing.ConsistentHashingRoutingLogic - Message [ReliableDeliveryEnvelope`1] must be handled by hashMapping, or implement [IConsistentHashable] or be wrapped in [ConsistentHashableEnvelope]
```

**Comment by jalchr** [comment]
After checking the logs:
```
2017-10-18 12:09:36,257 [35] WARN  Akka.Routing.ConsistentHashingRoutingLogic - Message [ReliableDeliveryEnvelope`1] must be handled by hashMapping, or implement [IConsistentHashable] or be wrapped in [ConsistentHashableEnvelope]
2017-10-18 12:09:41,939 [41] WARN  Akka.Routing.ConsistentHashingRoutingLogic - Message [ReliableDeliveryEnvelope`1] must be handled by hashMapping, or implement [IConsistentHashable] or be wrapped in [ConsistentHashableEnvelope]
```

I added the interface
```
    public class ReliableDeliveryEnvelope<TMessage> : IConsistentHashable
    {
        public ReliableDeliveryEnvelope(TMessage message, long messageId)
        {
            Message = message;
            MessageId = messageId;
        }

        public TMessage Message { get; private set; }

        public long MessageId { get; private set; }
        public object ConsistentHashKey { get; }
    }
```

Now everything works. 
Question: is it normal to decorate a **message class** with specific interface ?

**Comment by Horusiath** [comment]
@jalchr interface markers are quite common pattern in akka. They are used in mutliple scenarios, most commonly in custom serializers. 

Regarding `IConsistentHashable`, it's better to fully understand, how does consistent hashing work and what tradeoffs come with it. From the post about [Akka.Cluster.Sharding](https://petabridge.com/blog/introduction-to-cluster-sharding-akkadotnet/#why-not-just-use-consistent-hash-cluster-routers-to-distribute-state):

> In consistent hashing scenarios a whole key space is spliced between the number of actors we had defined in our router configuration. What does that actually mean? A single actor instance is responsible for handling whole range of key. For example: let’s say that we have a key space of numbers 1-100 shared equally between 5 actors behind consistent hash router. That means, first actor will be responsible for handling all messages with IDs 1-20, second actor 21-40, third one 41-60 etc. If your goal is to have a unique actor per identifier, this is not a valid scenario for your case...

>Consistent hash routers are pretty much static and they don’t play well in situations, where you want to resize your cluster. Do you remember the concept of spliced key space, we’ve mentioned previously? Imagine how it will behave once we change actual number of actors/nodes assigned to it. Of course, those key ranges will have to change as well. So an actor that previously handled messages with IDs from 1-20, after cluster resize may now handle different range (i.e. 1-15). This is called a “partition handoff.”

**Comment by jalchr** [comment]
Very well ... thanks
