### ISSUE TITLE
Akka.Persistence

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#316]
I want to know, what plans have @akkadotnet/developers for this library. No one has mentioned it up to this moment.

I must admit, I've spent some time on that concept this week - also started some specs/implemetation already for it. I've dropped implementation of classes already obsolete in original Akka, since version 2.3.4 greatly simplifies persistence API.

**Comment by mickdelaney** [comment]
+1 and @mmisztal1980 +10

**Comment by rogeralsing** [comment]
This has been merged to Dev, open individual issues for subtasks
