### ISSUE TITLE
You may only call Receive-methods when constructing the actor and inside Become()

### ISSUE THREAD

**Issue by wbradney** [akkadotnet/akka.net#3163]
I have an actor (pub sub subscriber) that does something like this:

```
public class MyActor : ReceiveActor
    {
        private ILoggingAdapter Log { get; } = Context.GetLogger();
        private readonly IActorRef _mediator;

        public MyActor()
        {
            _mediator = DistributedPubSub.Get(Context.System).Mediator;

            _mediator.Tell(new Subscribe("events", Self));

            Become(Subscribing);
        }

        public void Subscribing(object message)
        {
            Receive<SubscribeAck>(ack =>
            {
                Log.Info($"{Self} subscribed to 'events'");
            });
        }
}

```
This throws an InvalidOperationException at the Receive method. I'm a bit confused about how Become() is supposed to work in light of this exception. Of course, this works:

```
        public void Subscribing(object message)
        {
            switch (message)
            {
                case SubscribeAck ack:
                    Log.Info($"{Self} subscribed to 'events'");
                    break;
            };
        }

```
But does this mean Receive is useless inside ReceiveActors that change state?

**Comment by Danthar** [comment]
You are using it wrong.

It should be
`public void Subscribing() {}`

The fact that the exception is triggered at the Receive method is because the handlers are resolved upon receiving a message. So its only then that your "bug" comes to light.

Either way. Ditch the object message parameter.

**Comment by wbradney** [comment]
Ah, thanks - I missed the redundant parameter.

**Comment by robvangeloven** [comment]
Sorry to open something so long dead, but the official documentation (https://getakka.net/articles/actors/receive-actor-api.html) still uses the "object message" as parameter in the examples

**Comment by seungyongshim** [comment]
https://getakka.net/articles/actors/receive-actor-api.html was wrong
waste 2hrs

**Comment by Aaronontheweb** [comment]
@robvangeloven @seungyongshim sorry about that - I'll submit a PR for it

**Comment by Aaronontheweb** [comment]
Should be resolved here: https://github.com/akkadotnet/akka.net/pull/4958
