### ISSUE TITLE
Enabling log of every message (in DEBUG level) create millions of logs

### ISSUE THREAD

**Issue by delfuria** [akkadotnet/akka.net#3167]
Hi,
i have tried to follow this directions for enable logging in my app
https://getakka.net/articles/utilities/logging.html
and with these others infos
https://stackoverflow.com/questions/34738496/how-to-configure-akka-net-to-log-all-messages-received-by-actors
i'm able to log every messages but in this way if i enable the DEBUG log i get milions of messages  and not only the messages between actors!!!
What has been wrong ?
Thanks

**Comment by Danthar** [comment]
Well, its in the original question of the SO thread.

```
receive = on # log any received message
            autoreceive= on # log automatically received messages, e.g. PoisonPill
            lifecycle = on # log actor lifecycle changes
            event-stream = on # log subscription changes for Akka.NET event stream
            unhandled = on # log unhandled messages sent to actors
```

This tells akka.net to log any and all messages, including infrastructure stuff. If you don't want that. Then turn off autoreceive, lifecycle, event-stream and maybe unhandled as well.

**Comment by delfuria** [comment]
Thanks for the reply, but is there a way of log only the messages that an actor send to another actor ?
Thanks again
