### ISSUE TITLE
Tests with Akka.FSharp always throw timeout

### ISSUE THREAD

**Issue by ForNeVeR** [akkadotnet/akka.net#3170]
Initialize .NET Core 2.0 F# project with the following dependencies:

```
    <PackageReference Include="Akka.FSharp" Version="1.2.3" />
    <PackageReference Include="Akka.TestKit" Version="1.3.2" />
    <PackageReference Include="Akka.TestKit.Xunit2" Version="1.3.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170628-02" />
    <PackageReference Include="xunit" Version="2.3.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
```

Then, write `Tests.fs` with the following contents:

```fsharp
namespace Tests

open Akka.Actor
open Akka.TestKit.Xunit2
open Akka.TestKit
open Akka.FSharp
open Xunit

type Test() =
    inherit TestKit()

    [<Fact>]
    member this.``actor should send the message back to the probe``() =
        let probe = this.CreateTestProbe()
        let actor = spawn this.Sys "testactor" (actorOf(fun msg -> probe <! msg))
        actor <! "hello"
        probe.ExpectMsg("hello")
```

The test actor should simply send every message to the `probe`, but it doesn't. The test fails with the message `Failed: Timeout 00:00:03 while waiting for a message of type System.String`

I'm testing it on Windows 10, .NET Core 2.0.0.

**Comment by Horusiath** [comment]
I'm afraid that at this point F# plugins don't support .net core.

**Comment by ForNeVeR** [comment]
@Horusiath yes I'm aware of that. It does seem to actually work with my simple actors, but I understand that it could break at any moment. I've reported that issue as something we'd want to check after sorting out #2826 / #2941.

**Comment by pjvds** [comment]
With the latest releases I'm able to run this test without any problem. 👍
