### ISSUE TITLE
Akka.Persistence Cannot query snapshots from SQLServer after upgrade to 1.3.2

### ISSUE THREAD

**Issue by mwpro** [akkadotnet/akka.net#3171]
Hello,

- Which Akka.Net version you are using: 1.3.2, on 1.3.1 issue does not occur
- On which platform you are using Akka.Net: .NET Framework 4.6.2 , Windows 10 64bit

After updating my application to Akka 1.3.2, SQL Server persistence feature stopped working properly. It seems like SelectSnapshot query in QueryExecutor.cs is not database engine neutral, as LIMIT is not supported by Microsoft Sql Server (https://github.com/akkadotnet/akka.net/blob/master/src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/QueryExecutor.cs#L277)

I've created a repo that reproduces the issue https://github.com/mwpro/AkkaPersistenceLimitIssue, after setting up a connection string in App.config, the example fails with following exception
```
[ERROR][23.10.2017 08:33:14][Thread 0003][[akka://someActorSystem/user/$a#352981356]] Persistence failure when replaying events for persistenceId [SomePersistenceId]. Last known sequence number [0]
Cause: System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'LIMIT'.
   w System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Akka.Persistence.Sql.Common.Snapshot.AbstractQueryExecutor.<SelectSnapshotAsync>d__27.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Akka.Persistence.Sql.Common.Snapshot.SqlSnapshotStore.<LoadAsync>d__20.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Akka.Util.Internal.AtomicState.<CallThrough>d__7`1.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w Akka.Util.Internal.AtomicState.<CallThrough>d__7`1.MoveNext()
ClientConnectionId:68456155-920c-4610-987e-73c3341f0836
Error Number:102,State:1,Class:15
```
there is also a branch with Akka 1.3.1 used which works perfectly https://github.com/mwpro/AkkaPersistenceLimitIssue/tree/rollback-to-1.3.1

**Comment by Horusiath** [comment]
While Akka.Persistence.Sql.Common has been already upgraded to 1.3.2, I think, that Akka.Persistence.SqlServer is not there yet and still needs to be upgraded to v1.3.2.

**Comment by Danthar** [comment]
Once the sql server package is updated to 1.3.2, i'd expect a whole host of unit tests to fail :P But yeah that non-neutral SQL is pretty nasty. I suppose we missed it since sqlite does support it.

**Comment by Aaronontheweb** [comment]
@Horusiath https://github.com/akkadotnet/Akka.Persistence.SqlServer - need a PR with release notes so I can do a push.

**Comment by Danthar** [comment]
Merged and released.
