### ISSUE TITLE
Akka.TestKit.Xunit2 failed to nuget push on 1.3.2

### ISSUE THREAD

**Issue by kennethito** [akkadotnet/akka.net#3173]
With the recent release of 1.3.2, it looks like Akka.TestKit.Xunit2 failed to nuget push.

At the time of writing, https://www.nuget.org/packages/Akka.TestKit.Xunit2 has 1.3.1 as the latest version.  This breaks the build for anything with a dependency on Akka.TestKit.Xunit2.

**Comment by Aaronontheweb** [comment]
@kennethito yeah, not sure why this happened. I'll look into it right now.

**Comment by Aaronontheweb** [comment]
Hmmm, looking at the logs it appears that the XUnit testkits were never even in the package output list. Might be an issue with our build script. I'll double check.

**Comment by Aaronontheweb** [comment]
Welp, found the issue - the `dotnet pack` command arbitrarily determined that neither of the XUnit packages were packable. No indication that it was our changes that are responsible for this. Must have been an issue with the SDK. I've fixed this by adding an explicit:

```
  <PropertyGroup>
    <!-- WORKAROUND: for some reason starting at Akka.NET 1.3.2 this package was determined as "unpackable" by default via DOTNET CLI -->
    <IsPackable>true</IsPackable> 
  </PropertyGroup>
```

To both of the affected projects. Very strange.

**Comment by Aaronontheweb** [comment]
Fixed via #3174, but I have the packages going live on another process. Should be available on NuGet in a minute or two.

**Comment by Aaronontheweb** [comment]
@kennethito packages are now live on NuGet:

https://www.nuget.org/packages/Akka.TestKit.Xunit/1.3.2
https://www.nuget.org/packages/Akka.TestKit.Xunit2/1.3.2

**Comment by kennethito** [comment]
Awesome!  Thanks a bunch
