### ISSUE TITLE
NullReferenceException in DistributedPubSubMediator.PublishMessage

### ISSUE THREAD

**Issue by AngieRayor** [akkadotnet/akka.net#3177]
-Akka.net 1.2.3 
-.net 4.5
-Windows Server 2012
```csharp
System.NullReferenceException: Object reference not set to an instance of an object.
  at Akka.Cluster.Tools.PublishSubscribe.DistributedPubSubMediator.PublishMessage(String path, Object message, Boolean allButSelf)
```
This exception sometimes appears when an actor Publish a message, but in differents nodes that use PubSub.

https://github.com/akkadotnet/akka.net/blob/28cff8c3bd69fa42f18ab524799b48445f42e14a/src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs#L516

![pubsubmediator](https://user-images.githubusercontent.com/26433092/32041107-44ddd766-ba33-11e7-83a3-e6a0c12cc7af.png)

```csharp
private void Handler(SomeMessage message)
{
	var mediator = DistributedPubSub.Get(Context.System).Mediator;	  
	mediator.Tell(new Publish("topic", new SomeOtherMessage() ));	
}
```

**Comment by Horusiath** [comment]
Good catch. The `valueHolder.Ref.Equals(ActorRefs.Nobody)` should be indeed replaced with `Equals(valueHolder.Ref, ActorRefs.Nobody)`.

**Comment by ismaelhamed** [comment]
@Horusiath we'll send a PR later today, just wanted to make sure this wasn't already fixed in 1.3.x

**Comment by ismaelhamed** [comment]
@Horusiath On a second look, couldn't the PublishMessage method as it stands, potentially be calling `SendToDeadLetters` multiple times for the same message? What about a refactor to get it more aligned with the scala implementation?

```csharp
private void PublishMessage(string path, object message, bool allButSelf = false)
{
    IEnumerable<IActorRef> Refs()
    {
        foreach (var entry in _registry)
        {
            var address = entry.Key;
            var bucket = entry.Value;

            if (!(allButSelf && address == _cluster.SelfAddress) && bucket.Content.TryGetValue(path, out var valueHolder))
            {
                if (valueHolder != null && !Equals(valueHolder.Ref, ActorRefs.Nobody))
                    yield return valueHolder.Ref;
            }
        }
    }

    if (!Refs().Any()) SendToDeadLetters(message);
    else Refs().ForEach(r => r?.Forward(message));
}
```

**Comment by Aaronontheweb** [comment]
@ismaelhamed go for it
