### ISSUE TITLE
ByteString.ToArray throws sometimes

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3183]
Version: Akka.NET v1.3.2

This error is not stable, but here it is:

```
[ERROR][11/2/2017 3:03:37 PM][Thread 0018][[akka://demo/user/StatsD-%5BUdp-%3E127.0.0.1%3A8125%5D0/StreamSupervisor-12/Flow-0-0-unknown-operation#737196236]] Error in stage [UdpSink]: Provided index is outside the bounds of the buffer to copy to.
Parameter name: index
Cause: System.ArgumentOutOfRangeException: Provided index is outside the bounds of the buffer to copy to.
Parameter name: index
   at Akka.IO.ByteString.CopyTo(Byte[] buffer, Int32 index, Int32 count)
   at Phobos.Monitoring.StatsD.Streams.UdpSink.UdpSinkLogic.SendToSocket(ByteString bytes)
   at Akka.Streams.Implementation.Fusing.GraphInterpreter.Execute(Int32 eventLimit)
```

The `ByteString` was created via a `ByteString.FromString` operation earlier.

**Comment by Horusiath** [comment]
This will be hard to detect actually. Maybe use FsCheck to test `ByteString.CopyTo`?

**Comment by Aaronontheweb** [comment]
I think an FsCheck spec is a good way to go here.

**Comment by Horusiath** [comment]
@Aaronontheweb is this actually an issue or can we close it?

**Comment by Aaronontheweb** [comment]
I think we still need to keep it open for a bit, but it doesn't need to be part of the 1.3.3 milestone any longer.

**Comment by vasily-kirichenko** [comment]
I think the bug is not in `ByteString`, but in the calling code, which passes wrong combination of `buffer` and `index`:

https://github.com/akkadotnet/akka.net/blob/952154e361de5dde2830fd64b91072d059d329e4/src/core/Akka/Util/ByteString.cs#L487

**Comment by Aaronontheweb** [comment]
@vasily-kirichenko I'll double check the code that threw it, but AFAIK I wasn't calling that method you linked directly. I was calling some of the higher level `ByteString.FromString` methods, which is where I think the bug might be.
