### ISSUE TITLE
DeviceGroupQuery tutorial example will always time out?

### ISSUE THREAD

**Issue by marklam** [akkadotnet/akka.net#3194]
Looking at this code, it seems to me that the query agent terminates when there are no replies (which can't happen), rather than no outstanding requests.

https://github.com/akkadotnet/akka.net/blob/dc946b4e6daef098e3f6f575f2d8f4c62bd2b356/docs/examples/Tutorials/Tutorial4/DeviceGroupQuery.cs#L109

**Comment by marklam** [comment]
The java example in the akka project:
https://github.com/akka/akka/blob/f38b928e139a11cb92605b496adf1d76fab60e29/akka-docs/src/test/java/jdocs/tutorial_5/DeviceGroupQuery.java#L110

**Comment by marcpiechura** [comment]
Was fixed in https://github.com/akkadotnet/akka.net/pull/3221 so closing this one
