### ISSUE TITLE
Recursive call in Akka.IO

### ISSUE THREAD

**Issue by andreichuk** [akkadotnet/akka.net#3203]
Akka 1.3.2

[This method](https://github.com/akkadotnet/akka.net/blob/74ab3ce8aff710585b28586cd688220e2fae000a/src/core/Akka/IO/TcpConnection.cs#L833-L849) in Akka.IO uses recursive calls of itselft and that may lead to StackOverflowException because C# does not care about tail-call optimization. The code can be converted to while-loop -- any objections?

**Comment by Aaronontheweb** [comment]
Resolved via https://github.com/akkadotnet/akka.net/pull/3206
