### ISSUE TITLE
CLEAR error logging

### ISSUE THREAD

**Issue by d4e666** [akkadotnet/akka.net#3215]
Windows AKKA v1.3.2

how hard is it to add REAL debugging messages instead of constantly hiding your own fuck ups? I try to implement a custom snapshotstore and journal. I HAVE MY OWN EXCEPTION AND I ONLY SEE "Failure during [akka://TiActorSystem/system/akka.persistence.journal.sql-server#212337664] initialization." WHY DO YOU KEEP HIDING SHIT WHEN IT GOES WRONG????? even in debug THERE IS NO USEFUL INFO HIDDEN IN THE SHITLOAD OF MESSAGES

**Comment by Aaronontheweb** [comment]
> how hard is it to add REAL debugging messages instead of constantly hiding your own fuck ups?

The contributors on our project work hard to fix bugs and make improvements all the time, but this sort of attitude is totally toxic and thankfully pretty rare in open source projects. I'm sorry you're frustrated, but no one, myself included, is going to rush to fix these issues for jerks. 

That being said, would you like to edit the issue and post some more information about what you expect versus what you saw?

**Comment by Horusiath** [comment]
@d4e666 the error message should be there (the message is logged using standard `Log.Error` semantics). The log itself usually signals that connection with database couldn't be established or requested operation thrown an error. You could show your logs if you want some help here.

Also if you want to implement your own custom snapshot store or journal, you may want to use [Akka.Peristence.TCK](https://www.nuget.org/packages/Akka.Persistence.TCK/1.3.2-beta) or [Akka.Persistence.Sql.TestKit](https://www.nuget.org/packages/Akka.Persistence.Sql.TestKit/) (for SQL engines only) - they are compatibility test kits which have defined a basic collection of tests (using xUnit) used to check if a particular implementation of a journal/snapshot store will work fine with Akka.Persistence. You can see example implementation of them [here](https://github.com/akkadotnet/akka.net/tree/dev/src/contrib/persistence/Akka.Persistence.Sqlite.Tests).
