### ISSUE TITLE
Huge memory leak hosting Akka in an ASP.NET Core app on IIS

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/akka.net#3229]
I have a simple Giraffe (asp.net core) server, which has a number of Akka actors running in it. They are making http requests to a small number of hosts and keep a (very small, few MB approx) in memory cache. **It works totally OK being run locally as a console app (`dotnet my.dll`), no memory leaks at all.** I deployed it to IIS and mentioned that dotnet process quickly eats memory (it takes it about 5 minutes to grab 2GB starting from 150MB), after that IIS kills it and start a new process. 

Profiling with dotMemory showed that unmanaged memory is the problem:

![image](https://user-images.githubusercontent.com/873919/34437124-a8ae2b5a-ecac-11e7-9e12-f2dcbaf13a8c.png)

Before that there was no Akka in the server and there was no memory leaks at all - clients made ~20 req/s for few days without any memory leak.

I suspect that a new `ActorSystem` is created on each request or something like this. I create one with this code:
```fsharp
// A singleton (I hope), which creates an ActorSystem
type HostStates(options: IOptionsMonitor<Configuration.Main>) =
    let config = Configuration.parse """
akka {
    log-config-on-start = off
    stdout-loglevel = DEBUG
    loglevel = DEBUG
    actor {
      debug {
          receive = on
          autoreceive = on
          lifecycle = on
          event-stream = off
          unhandled = on
      }
    }
  }"""

    let system = ActorSystem.Create ("host-states-system", config)
    let stateActor = spawn system "host-states" (StateActor.props())
    let pollingCoordinator = spawn system "polling-coordinator" (PollingCoordinator.props (fun _ -> options.CurrentValue.Hosts) stateActor)

    // Returns the (immutable) cache to the http server handler
    member __.GetState() : Async<StateActor.State> = stateActor <? StateActor.Message.Get

...

let configureApp (app : IApplicationBuilder) =
    app.UseCors(configureCors)
       .UseGiraffeErrorHandler(errorHandler)
       .UseStaticFiles()
       .UseMiddleware<ForwardAuthHeadersMiddleware>()
       .UseGiraffe(webApp)
    
    // warm up the actors
    app.ApplicationServices.GetService<HostStates>() |> ignore

let configureServices (services : IServiceCollection) =
    services
        .AddCors()
        .Configure<IISOptions>(fun (x: IISOptions) -> x.AutomaticAuthentication <- true)
        .Configure<Configuration.Main>(config.GetSection "Main")
        .AddSingleton<HostStates>()  // <-----------------------------------------
        .AddDataProtection()
    |> ignore
```

I'm appreciate any help from you guys as you are much more experienced in all this stuff than me. 

Thanks!

**Comment by vasily-kirichenko** [comment]
A made the actor system static:
```fsharp
module ActorSystem =
    let config = Configuration.parse """
    akka {
        log-config-on-start = off
        stdout-loglevel = DEBUG
        loglevel = DEBUG
        actor {
          debug {
              receive = on
              autoreceive = on
              lifecycle = on
              event-stream = off
              unhandled = on
          }
        }
      }"""

    let system = ActorSystem.Create ("host-states-system", config)
```
It's not helped at all :(

About 5 minutes restarts - the app pool was configured to be recycled every 5 minutes. Set it to 60 minutes, will see how much memory it will grab...

**Comment by Horusiath** [comment]
What are you using your actors for? Maybe some of them are created per request and never stopped?

**Comment by vasily-kirichenko** [comment]
no, all of them (~40) are started on start and live forever. The only API for entire Akka system is that `GetState` method which makes an Ask to the coordinator actor.

**Comment by Horusiath** [comment]
This sounds like issue #2380 we had in the past.

**Comment by vasily-kirichenko** [comment]
@Horusiath I doubt, the Asks are always very quick because it just return the actor's internal state, no waiting for anything at all.

OK, maybe it's not an issue. The process quickly reaches 2.2GB of memory, then almost stabilized: it's got  2.6GB of memory after running for an hour. I removed 1-hour IIS pool restarting policy, will see what it looks like tomorrow. 

Sorry that disturbed you, I'm closing it for now.
