### ISSUE TITLE
Make writing custom stream stages more type safe

### ISSUE THREAD

**Issue by marcpiechura** [akkadotnet/akka.net#3231]
As pointed out in #3225 it's quite easy to skip the type checking by using one of the overloads which take an `Inlet` instead of an `Inlet<T>` , e.g.
```csharp
var outlet = new Outlet<int>("someOutlet");
Push(outlet, "hello world");
``` 

Proposal would be to restrict the public api to methods which only take  `Inlet<T>` or `Outlet<T>` and keep the ones without type argument internal, if we need them at all.

cc @Horusiath

**Comment by Aaronontheweb** [comment]
I like this idea - shot myself in the foot writing some custom sinks earlier in the year doing this exact thing.
