### ISSUE TITLE
Is it possible to configure a cluster router in code?

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/akka.net#3238]
```
deployment {
  /router1 {
    router = round-robin-pool
    nr-of-instances = 3
    cluster {
      enabled = on
      allow-local-routees = on
      max-nr-of-instances-per-node = 2
    }
  }
}
```
Looking at the documentation, it seems impossible. All I can do is create a specific router, but how to set cluster-specific options?

```csharp
var props = Props.Create<Worker>().WithRouter(new RoundRobinPool(5));
var actor = system.ActorOf(props, "worker");
```

**Comment by to11mtm** [comment]
I think you should be able to do so by specifying a `ClusterRouterPool` or `ClusterRouterGroup`. Both will take the internal routing type in their constructor:

```
var myClusterPoolSettings = new ClusterPoolSettings(3 /*max instances*/, 2 /*Instances per node*/, true /*allow local routees*/, useRole : null /*This is default, change to not use null*/)
var props = Props.Create<Worker>().WithRouter(new ClusterRouterPool(new RoundRobinPool(5), myClusterPoolSettings);
```

**Comment by vasily-kirichenko** [comment]
@to11mtm thanks, it works :)

However, the size of `RoundRobinPool` (5) is unclear to me. How it's related to `max instances` value?

**Comment by Danthar** [comment]
@vasily-kirichenko i assume you found the answer to your question. But with these settings what you are configuring is the following:

- I want max 3 workers in my pool (cluster wide)
- I want a max of 2 workers per node

The other settings are pretty clear i believe. The nr of instances parameter  of the `RoundRobinPool(5)` constructor is ignored when using the clusterRouterPool.

**Comment by vasily-kirichenko** [comment]
Yes, the 5 in RoundRobinPool ctor was unclear. Thanks. However, I find this API design a bit strange.

**Comment by raskolnikoov** [comment]
> ClusterRouterGroup

Where can I find ClusterPoolSettings? I dont find it in Akka.Cluster, Akka.Cluster.Tools nuget packages.

**Comment by Aaronontheweb** [comment]
@raskolnikoov it's in the `Akka.Cluster.Routing` package: 

https://getakka.net/api/Akka.Cluster.Routing.ClusterRouterPool.html
https://getakka.net/api/Akka.Cluster.Routing.ClusterRouterPoolSettings.html

**Comment by raskolnikoov** [comment]
@aaronontheweb thanks! But the ClusterRouterPoolSettings is marked obsolete. What is the recommended way?

**Comment by Aaronontheweb** [comment]
@raskolnikoov the class isn't obsolete, just some of the constructors - try this one: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Cluster/Routing/ClusterRoutingConfig.cs/#L145
