### ISSUE TITLE
Correct errors in Akka.NET Serilog Documentation

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3247]
The [Serilog integration page](http://getakka.net/articles/utilities/serilog.html) has a number of small issues with it that make the code un-runnable right out of the gate:

* [x] Need to install a specific logging sink to get the example running
* [x] Need to install another Serilog package to read in the configuration settings from file

And other minor issues like that. We should address all of these in order to provide a "it just works" experience right out of the box.

**Comment by wtarr** [comment]
Hi, I see what you mean about the example not running out of the box.  Serilog has various sinks available on nuget for depending on what you want to do.  In this case it is using a _colored console sink_ as a dependency in the code sample.

So the following is required: Install-Package Serilog.Sinks.ColoredConsole

As for the configuration, you also need the "Serilog.Settings.AppSettings" nuget package, there is a link on the page to the serilog documentation, but it should probably state this package requirement up front.

Install-Package Serilog.Settings.AppSettings

If no one else (first time contributor) wants to pick this up, I can correct it as I put allot of that page together originally.

**Comment by Danthar** [comment]
Go for it

**Comment by stijnherreman** [comment]
The default Console logger uses this format when using :

```
.WriteTo.Console(
    outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}")
```

Akka.NET users will probably want something like this instead:

**Comment by Aaronontheweb** [comment]
closed via https://github.com/akkadotnet/akka.net/pull/3254
