### ISSUE TITLE
Node is unreachable by some nodes, but not all

### ISSUE THREAD

**Issue by nvivo** [akkadotnet/akka.net#3250]
While looking into unreachability problems, I found this curious situation that may or not be some bug. Just want to make sure.

There are 45 nodes with the same docker image running this. Only one of them had this issue this night. The seed node has been registering this same message for about an hour, and the leader cannot perform its duties:

```
[akka.tcp://SICluster@10.0.12.132:10050 -> UniqueAddress: (akka.tcp://SICluster@10.0.12.163:10051, 630239608): Reachable [Reachable] (19)], 
[akka.tcp://SICluster@10.0.12.132:10050 -> UniqueAddress: (akka.tcp://SICluster@10.0.12.163:10050, 1987347457): Unreachable [Unreachable] (15)]
[akka.tcp://SICluster@10.0.12.136:10050 -> UniqueAddress: (akka.tcp://SICluster@10.0.12.163:10050, 1987347457): Unreachable [Unreachable] (7)]
[akka.tcp://SICluster@10.0.12.10:10051 -> UniqueAddress: (akka.tcp://SICluster@10.0.12.163:10051, 630239608): Reachable [Reachable] (17)], 
[akka.tcp://SICluster@10.0.12.10:10051 -> UniqueAddress: (akka.tcp://SICluster@10.0.12.163:10050, 1987347457): Unreachable [Unreachable] (13)]
[akka.tcp://SICluster@10.0.12.11:10050 -> UniqueAddress: (akka.tcp://SICluster@10.0.12.163:10050, 1987347457): Unreachable [Unreachable] (3)]
[akka.tcp://SICluster@10.0.12.161:10050 -> UniqueAddress: (akka.tcp://SICluster@10.0.12.163:10050, 1987347457): Unreachable [Unreachable] (9)]
```

That points to 10.0.12.163 being unreachable by some of these nodes, but not all.

I had unreachable nodes before due to high CPU and memory usage, but this one seems fine:
![image](https://user-images.githubusercontent.com/202449/34605825-2593c642-f1f4-11e7-9e52-a2c19f6d3178.png)

Also, I connected to these nodes, and they all can reach that node, like this one:

![image](https://user-images.githubusercontent.com/202449/34605852-4548945e-f1f4-11e7-8b65-c740028537e7.png)

Looking at my application logs, 10.0.12.163 is working fine. Akka is running, the actors are processing messages.

I looked for when the problem started, and the first message was a `EndpointDisassociatedException` from another app disassociating from 10.0.12.163. The node itself didn't had any log message from akka within 10 minutes before or after that time, then it began showing messages like this one:

```
Caused by: [System.AggregateException: One or more errors occurred. (Connection refused tcp://SICluster@10.0.12.163:10050) ---> Akka.Remote.Transport.InvalidAssociationException: Connection refused tcp://SICluster@10.0.12.163:10050
   at Akka.Remote.Transport.DotNetty.TcpTransport.<AssociateInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.<Associate>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Akka.Remote.Transport.ProtocolStateActor.<>c.<InitializeFSM>b__11_54(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
---> (Inner Exception #0) Akka.Remote.Transport.InvalidAssociationException: Connection refused tcp://SICluster@10.0.12.163:10050
   at Akka.Remote.Transport.DotNetty.TcpTransport.<AssociateInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.<Associate>d__22.MoveNext()<---
]
```

Other nodes show similar messages pointing to it.

So, it seems the node is up, working, the network is fine, but Akka reports it as being unreachable.

Could it be that akka or dotNetty are getting to a state where the heartbeat port are not accepting new connections for some reason?

I'll try to enable debug for these nodes, but would appreciate some insight from someone else.

**Comment by Aaronontheweb** [comment]
@nvivo barring a bug with Akka.Remote itself, it's definitely possible for two nodes in a cluster to have differing views as to the "reachability" of a third node. That'd be determined by whose messages are getting through and whose are not. 

That "connection refused" error message is odd though - that'd seem to indicate that the inbound endpoint became unavailable; i.e. an actual network problem and not just the CPU being busy. Is it possible that there was an issue on the AWS network itself while all this was going on?

**Comment by nvivo** [comment]
I can't rule out AWS. I'm am confident that they have issues where an instance may slow down for external reasons, and this to cause problems as threads don't run when they have to. But that doesn't seem to be the case in this node. I looked at the node, the process was fine for an entire hour and the application was processing everything just fine.

It seems that something happened and akka simply didn't recover. After an hour and a half, I restarted the container and manually downed the previous node for things to go back to normal.

**Comment by nvivo** [comment]
I'm getting more confident that this and #3252 are somehow related. With a hundred nodes, 3 to 10 nodes are constantly unreachable. But looking at the gossips, these nodes are seen by most other nodes, but the network doesn't ever converge. There is always a new unreachable node and they keep shifting.

**Comment by Aaronontheweb** [comment]
So we are not obeying the original Akka.Cluster specification here: https://doc.akka.io/docs/akka/current/common/cluster.html#failure-detector

Key paragraph:

> In a cluster each node is monitored by a few (default maximum 5) other nodes, and when **any of these detects the node as unreachable that information will spread to the rest of the cluster through the gossip. In other words, only one node needs to mark a node unreachable to have the rest of the cluster mark that node unreachable**.
> 
> The nodes to monitor are picked out of neighbors in a hashed ordered node ring. This is to increase the likelihood to monitor across racks and data centers, but the order is the same on all nodes, which ensures full coverage.
> 
> Heartbeats are sent out every second and every heartbeat is performed in a request/reply handshake with the replies used as input to the failure detector.
> 
> The failure detector will also detect if the node becomes reachable again. **When all nodes that monitored the unreachable node detects it as reachable again the cluster, after gossip dissemination, will consider it as reachable**.

Emphasis mine. No one should be marking anyone as reachable if the any of the observers on the heartbeat ring disagree.

**Comment by nvivo** [comment]
> So we are not obeying the original Akka.Cluster specification here
...
> No one should be marking anyone as reachable if the any of the observers on the heartbeat ring disagree.

I'm lost here. Isn't this is what's happening? The node appears as unreachable to the cluster because one of the nodes is seeing it as unreachable?

That makes sense, but at the same time it sounds like the larger the cluster, the higher the probability that at least one node will be unreachable at some point, and so the higher the probability the cluster will not converge.

**Comment by Aaronontheweb** [comment]
> The node appears as unreachable to the cluster because one of the nodes is seeing it as unreachable?

That's correct. But no one should be marking that node as "reachable" again until all observers can reach it. One thing worth trying is to change the following setting:

```
akka.cluster.monitored-by-nr-of-members = 5 #default
```

By default, every node can only be monitored by up to 5 other members. In a 6 node cluster everyone monitors everyone else except them selves, but from there you start having some diversity in terms of who monitors whom. The `HeartbeatNodeRing` class we have implemented is supposed to guarantee an even distribution of monitors across the cluster. One of my notes on my "process of elimination" list for this issue is to double-check that that is being done correctly. We have all of the same specs the JVM does and they haven't failed in years, including one that heavily randomizes the "shape" of the cluster, so I think that's all working as intended.

**Comment by Aaronontheweb** [comment]
Edited previous comment to fix the HOCON
