### ISSUE TITLE
Possible incorrect documentation for the default supervisor strategy

### ISSUE THREAD

**Issue by stijnherreman** [akkadotnet/akka.net#3251]
http://getakka.net/articles/actors/fault-tolerance.html#default-supervisor-strategy says:

> `Escalate` is used if the defined strategy doesn't cover the exception that was thrown.
> 
> When the supervisor strategy is not defined for an actor the following exceptions are handled by default:
> 
> * `ActorInitializationException` will stop the failing child actor
> * `ActorKilledException` will stop the failing child actor
> * `Exception` will restart the failing child actor
> * Other types of `Exception` will be escalated to parent actor

The implementation doesn't match this behaviour: https://github.com/akkadotnet/akka.net/blob/feecd5e149cf7a22631293b8ab438080bc19cba4/src/core/Akka/Actor/SupervisorStrategy.cs#L104-L107

https://doc.akka.io/docs/akka/current/fault-tolerance.html#default-supervisor-strategy says:

> `Escalate` is used if the defined strategy doesn’t cover the exception that was thrown.
> 
> When the supervisor strategy is not defined for an actor the following exceptions are handled by default:
> 
> * `ActorInitializationException` will stop the failing child actor
> * `ActorKilledException` will stop the failing child actor
> * `DeathPactException` will stop the failing child actor
> * `Exception` will restart the failing child actor
> * Other types of `Throwable` will be escalated to parent actor

It's important to note here that there is no similar class for `Throwable` in .NET, that is, a base class for `Exception`.

~~I also found that at one point, akka did escalate `Throwable` but it was removed, so *possibly* their docs are out-of-date as well. See https://github.com/akka/akka/commit/f05447408cc3e84c8a30bdc81d14e2b239a0752f#diff-c831999efea2141bffe949611799a66b for the relevant commit removing it.~~
The default in akka is to restart on `Exception` and escalate on other types of `Throwable`. See https://gitter.im/akka/akka?at=5a4f8140ce68c3bc7480943c

Relevant gitter discussions:

* https://gitter.im/akkadotnet/akka.net?at=5a4f6d33232e79134dcc1c2e
* https://gitter.im/akka/akka?at=5a4f7c7dedd2230811169f7a

**Comment by marcpiechura** [comment]
Since we don’t have `Throwable` in .Net in Akka.net the strategy is `Restart` by default, so yes the docs are a bit misleading and it was fixed in https://github.com/akkadotnet/akka.net/pull/3308 therefore closing this one.
