### ISSUE TITLE
Using Akka.NET in micro services

### ISSUE THREAD

**Issue by VenkateshSrini** [akkadotnet/akka.net#3255]
Is there a way that we can share the actor system created in service across multiple services. I ask this because as per 12 factor recommendation our services should be stateless. By creating an Akka.NET object in startup does not farewell. when I will not be able to share the actor system. So why do we use Akka.NET with 12 factor micro services design principles

**Comment by mrrd** [comment]
Akka.NET as with Java Akka is simply a toolset like any other, its up to you to build such rules on top of it, either that or use a pre-defined "platform" such as Orleans where such things as actor location and spawning are handled entirely transparently for you but which is also slower and far less flexible as a consequence.

**Comment by marcpiechura** [comment]
@VenkateshSrini please use the Gitter room for those questions. Thanks!
