### ISSUE TITLE
Logic error in KeepMajority SplitBrainStrategy

### ISSUE THREAD

**Issue by mrrd** [akkadotnet/akka.net#3265]
In order to solve some connectivity issues we have been experiencing and allowing our cluster to recover itself we backported SplitBrainStrategy into 1.3.2 by copying the class and config into our projects.

During production use we have found some instances where inside the Apply method in the KeepMajority strategy (which is what we have chosen to use) sometimes the "remaining" and "unreachable" variables contain zero elements which causes an error in the else statement on the following line that it contains no elements:

        var oldest = remaining.Union(unreachable).First();

To get around this we have locally patched this method (and tidied the code to the following at the suggestion of Refactor to remove the redundant else if's):

        public IEnumerable<Member> Apply(NetworkPartitionContext context)
        {
            var remaining = MembersWithRole(context.Remaining);
            var unreachable = MembersWithRole(context.Unreachable);

            if (remaining.Count < unreachable.Count) return context.Remaining;
            if (remaining.Count > unreachable.Count) return context.Unreachable;
            if (remaining.IsEmpty && unreachable.IsEmpty) return new Member[0];

            // if the parts are of equal size the part containing the node with the lowest address is kept.
            var oldest = remaining.Union(unreachable).First();
            return remaining.Contains(oldest)
                ? context.Unreachable
                : context.Remaining;
        }

The line we added is:

        if (remaining.IsEmpty && unreachable.IsEmpty) return new Member[0];

this prevents the error later down the line.

**Comment by Horusiath** [comment]
@mrrd nice catch! Would you mind sending a PR (ideally with test case)?

**Comment by Aaronontheweb** [comment]
Closed via https://github.com/akkadotnet/akka.net/pull/3266
