### ISSUE TITLE
Implement TerminationHooks

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#327]
Used as part of graceful shutdown for built-in system actors - in particular it's for actors like the `RemoteDaemon` and others who need to send final `DeathWatch` notifications during the shut-down process.

**Comment by smalldave** [comment]
Looks like the JVM Akka issue has been completed. 
I need this to shutdown remoting correctly.
I'm happy to pick this up.
Any discussion to be had or just follow the JVM version?

**Comment by Aaronontheweb** [comment]
@smalldave I think following the JVM solution is the best way to start. Can modify it later if there's something that doesn't translate well into .NET.

**Comment by HCanber** [comment]
`ActorSystem` has a `AwaitTermination` that waits for a task to complete. Isn't it working or is that functionality not complete? It looks like the Task is completed when `Stop()` is called. I think I wrote it once :)
Could that not be used or extended?

**Comment by smalldave** [comment]
On my phone so can't check this but I think the difference is that await termination allows you to wait for the actor system to terminate. Termination hooks stop the root guardian from terminating until all actors that register a hook reply with TerminationHookDone. This allows you to tidy up while the actor system is still running. I'm not 100% on how AwaitTermination works but I'm pretty sure there is no feedback to the system / root guardian

**Comment by HCanber** [comment]
Ahh, ok. Thanks!
