### ISSUE TITLE
Use ValueTuple instead of Tuple  

### ISSUE THREAD

**Issue by marcpiechura** [akkadotnet/akka.net#3276]
We should switch to `ValueTuple`s to reduces allocations and improve readability, since this would be quite a big chance if introduced at once we split it up in several chunks. 

The first place would be [Keep.Both](https://github.com/akkadotnet/akka.net/blob/a478c5e8c8d5de97dcf7bcea7e2a80fbaa5e6cc8/src/core/Akka.Streams/Dsl/Keep.cs#L47) .

**Comment by Horusiath** [comment]
You have my sword :)

**Comment by vasily-kirichenko** [comment]
Yes!

**Comment by vasily-kirichenko** [comment]
https://github.com/akkadotnet/akka.net/pull/3282

**Comment by Aaronontheweb** [comment]
@marcpiechura since this would constitute a new package dependency and possibly some API changes, going to propose that we dovetail this into the 1.4 branch.

**Comment by NickPolyder** [comment]
Is this issue resolved ?

**Comment by marcpiechura** [comment]
@NickPolyder yup, the PR https://github.com/akkadotnet/akka.net/pull/3282 is not merged but the work is done, at least for Akka.Streams. Out of my head I don’t know if we have other places where it would make sense, I’ll try to find some and create a new issue you could work on 😉

**Comment by NickPolyder** [comment]
@marcpiechura  Thank you for your quick response 👍

**Comment by marcpiechura** [comment]
@NickPolyder After a quick look the "other places" are everywhere :stuck_out_tongue: 
So if you want to start with it you need to target the V1.4.0 branch and reference  System.ValueTuple version 4.4.0.
You can pick any of the projects you want except for Akka.Streams.XXX since those are already done. 
If you need any help let us know, of course you could also pick a different task if you want.

**Comment by NickPolyder** [comment]
@marcpiechura i have done most of the job on my branch [here](https://github.com/NickPolyder/akka.net/tree/issue-3276) although i have some kind of knock back on the compilation due to error on the compilation of the docs [error CS1569: Error writing to XML documentation file: Object reference not set to an instance of an object.](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1569) did you ever had this problem ?

Thanks for your time.

**Comment by marcpiechura** [comment]
@NickPolyder haven't seen this before and your branch builds just fine after a clean checkout. 
![image](https://user-images.githubusercontent.com/6583600/36392906-c599fa6c-15ad-11e8-8a48-d0dc2aa74154.png)

Maybe you could delete your local folder an try it with a fresh cloned repo ?

**Comment by NickPolyder** [comment]
@marcpiechura Okay i think that i'm ready.
 Is there any process besides those noted at [Contributor guidelines](http://getakka.net/community/contributor-guidelines.html) that i must take to ensure that the pull request will run smoothly ?
I tried to run all the unit tests but it seems to take forever for some of them to finish.

As for the error i mentioned above it was about a change on the comments from Tuple to ValueTuple. For some reason the compiler just throws.

Thanks for the time you have given me and please forgive me if i am doing a lot of questions. I just want to make it as close to the "ideal" as possible to avoid problems with the pull request.

**Comment by marcpiechura** [comment]
@NickPolyder have you run the Api Approval tests ? 
http://getakka.net/community/public-api-changes.html

No need to run all unit tests, we have a build server for it ;-) 
I would suggest that you check the api approval, if you haven’t already and then create the PR. 

No worries, we‘re glad someone takes the time to work on it and we‘re happy to assist 👍

**Comment by NickPolyder** [comment]
@marcpiechura okay i will make the public api changes. Then i will do a little bit of clean up on my commits to make them more compact and fewer and then i will submit the PR.

Thanks again for your time.

**Comment by Aaronontheweb** [comment]
Resolved as part of Akka.NET 1.4.0-beta3
