### ISSUE TITLE
Source.Maybe ignores element if it is default(T), i.e. 0 for int

### ISSUE THREAD

**Issue by marcpiechura** [akkadotnet/akka.net#3286]
On the JVM `Source.Maybe` materializes into a `Promise[Option[T]]`  and if you pass in `None` the source will complete without pushing an element. 
We try to model the `None` case via
https://github.com/akkadotnet/akka.net/blob/a478c5e8c8d5de97dcf7bcea7e2a80fbaa5e6cc8/src/core/Akka.Streams/Implementation/CompletedPublishers.cs#L134
which works fine for reference types but not so much for value types, i.e. `completion.SetResult(0)` is considered as `None` and 0 is not pushed downstream. 

So we should change the API and make the `None` case explicit via `Option<T>` .

I found this issue while porting the PartitionHub specs, so this spec
PartitionHub_must_ensure_that_from_two_different_speed_consumers_the_slower_controls_the_rate should be fixed afterwards.

**Comment by NickPolyder** [comment]
Hello, just to make sure that i understood what you are writing.
You want to change the Task.Result to from `TResult` to `Option<TResult>` ??

Thank you,

**Comment by marcpiechura** [comment]
Kind of :) 
So let’s assume your stream looks like this: 

Source<int, TaskCompletionSource<int>> source = Source.Maybe<int>().....

What we want to change is TaskCompletionSource<int> to TaskCompletionSource<Option<int>>, so that we can check for Task.Result != Option.None instead of !Task.Result.IsDefaultForType() and the user can call completion.SetResult(None) as signal for completing the stream without sending any elements whereas completion.SetResult(0) results in an element ( 0 ) which is pushed downstream. With the current behavior completion.SetResult(0) is considered as the None case because it’s default for int and therefore the stream is completed without sending 0 downstream. 

Hope that helps.

**Comment by NickPolyder** [comment]
@marcpiechura Hello, cool yes i think i've got it.
Let me try this one and get back to you with any questions.

Thanks,

**Comment by marcpiechura** [comment]
Fixed by #3342
