### ISSUE TITLE
A network partition detected - unreachable nodes: [], remaining: all

### ISSUE THREAD

**Issue by nvivo** [akkadotnet/akka.net#3290]
Using the 1.3 nightlies and the new split brain resolver, every couple minutes I see this log message coming one from every node:

```
A network partition detected - unreachable nodes: [], remaining: [ <all nodes> ]
```

![image](https://user-images.githubusercontent.com/202449/35274005-a63f880e-0021-11e8-80d6-f8859759183b.png)

Currently using this setting:
```
akka.cluster : {
  allow-weakly-up-members : on
  downing-provider-class : "Akka.Cluster.SplitBrainResolver, Akka.Cluster"
  split-brain-resolver : {
	active-strategy : keep-oldest
	keep-oldest : {
	  down-if-alone : on
	}
  }
}
```

If none is unreachable, it shouldn't be logging that a partition was detected, right?

Edit: This still happens on 1.3.3 stable.

**Comment by Aaronontheweb** [comment]
Fixed this a while back
