### ISSUE TITLE
Mailboxes:VerifyRequirements log message does not seem to be correct

### ISSUE THREAD

**Issue by spankr** [akkadotnet/akka.net#3292]
I'm getting an exception when I'm trying to integrate in a custom mailbox/queue and my log message is confusing:

```
ArgumentException: produced message queue type of 
[Sample.NoisyUnboundedMessageQueue] does not fulfill requirement for actor class
 [Sample.Actors.SamplePersistentActor]. Must be a subclass of [Sample.NoisyUnboundedMessageQueue]
```

My message queue needs to be a subclass of itself? (Its just a clone of UnboundedMessageQueue, for experimentation purposes)

I traced this down to line 285-286 in Akka/Dispatch/Mailboxes.cs

```
if (HasRequiredType(actorType) && !actorRequirement.Value.IsAssignableFrom(mqType.Value))
  throw new ArgumentException($"produced message queue type of [{mqType.Value}] does not fulfill requirement for actor class [{actorType}]." + $"Must be a subclass of [{mqType.Value}]");
```

This could just be me but that `{mqType.Value}` at the end doesn't appear to be the correct input.

**Comment by spankr** [comment]
On a side note, if you are playing with custom mailboxes (and/or queues) on persistent actors and find yourself here, my exception was resolved by implementing `IUnboundedDequeBasedMessageQueueSemantics` on my custom NoisyUnboundedMessageQueue.

Persistent actors require that their mailbox queues support that interface.

**Comment by Horusiath** [comment]
@spankr if you want, you may try to make it your contribution ;) Also good catch with persistent actor's mailbox rules, probably related to #3184.

**Comment by spankr** [comment]
Woot!
