### ISSUE TITLE
Inconsistencies in ActorPath construction and ActorSelection Resolution

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3296]
Version: Akka.NET 1.3.2

Ran into this issue yesterday; not sure if there's a bug yet or a meaningful semantic difference that I'm overlooking. But here's the setup:

```
var address = Address.Parse("akka.tcp://MySystem@127.0.0.1:9330/user/
var actorPath1 = new RootActorPath(address) / "user/myName";
var actorPath2 = new RootActorPath(address) / "/user/myName";
var actorPath3 = address + "/user/myName";
```

All three of these actor paths are different and only `actorPath3` was able to successfully be delivered to an actor living at that address via Akka.Remote. On the surface, all of these look similar enough to me despite the trailing / leading slash semantics on actor path 1 and 2. Why should `actorPath3` be the only deliverable one in this scenario?

**Comment by NickPolyder** [comment]
Hello. 
I tried what you suggest. 
I was able to use `actorPath1` and `actorPath3` 
The `actorPath2` creates an invalid link (has 2 slashes '/' ).
Is this the same output for you ? 

> ActorPath 1: akka.tcp://MySystem@127.0.0.1:9330/user/MyName
> ActorPath 2: akka.tcp://MySystem@127.0.0.1:9330//user/MyName
> ActorPath 3: akka.tcp://MySystem@127.0.0.1:9330/user/MyName

If this issue is completed maybe close this ? 

Thanks

**Comment by Aaronontheweb** [comment]
@NickPolyder might be! and good catch - we should add some specs to confirm though.

**Comment by Aaronontheweb** [comment]
Nope, definitely still a bug... Also worth noting though: `ActorSelection` behavior varies depending on whether or not you're calling `Sys.ActorSelection` or `Context.ActorSelection` because the root anchors are different, and I've determined that the way `ActorPath`s are constructed can affect this in ways it should not.

Works when used inside and outside of actors:

```
var actorPath = new RootActorPath(Sys2Address) / "user" / "actorA";
```

Works when used inside of actors; __fails__ when used outside of actors:

```
var actorPath = new RootActorPath(Sys2Address) / "user/actorA";
```

**Comment by Aaronontheweb** [comment]
Ok, got this one fixed....

```
var actorPath = new RootActorPath(Sys2Address) / "user/actorA";
```

The above is __not a supported use case for the `/` operator in Akka.NET__. The correct syntax here is:

```
var actorPath = new RootActorPath(Sys2Address) / "user" / "actorA";
```

In the end, it was end-user error all along. 

Now, this _is_ supported:

```
var actorPath3 = address + "/user/myName";
```

Because we're concatenating an `ActorPath` onto an `Address` to form a full, absolute `RootActorPath`. Works differently than the `/` operator on `ActorPath`, which is designed to append a single node to the existing path - not multiple nodes parsed from a string.

**Comment by Danthar** [comment]
Since this has costed quite abit of time. Might be prudent to better clarify this in the docs ?

**Comment by Aaronontheweb** [comment]
Yeah... we should mention this somewhere. It'd kind of miscellaneous, but it should be spelled out in the literature somewhere.
