### ISSUE TITLE
DData replicator is always assigned

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#3297]
As @zbynek001 pointed out, after 1.3.3, the Akka.Cluster.Sharding update is no longer binary compatible - the reason for that is that we initialize DistributeData replicator even thou we didn't use it.

The line which causes an issue: https://github.com/akkadotnet/akka.net/blob/e607088d00e60b318897da3f01b8982666a5f6cc/src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingGuardian.cs#L225

The problem is that I've missed the initialization code. Replicator should not be initialized via explicit `DistributedData.DistributedData.Get(Context.System).Replicator` call, but rather a `Replicator` method defined few lines below: https://github.com/akkadotnet/akka.net/blob/e607088d00e60b318897da3f01b8982666a5f6cc/src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingGuardian.cs#L252

You can see that error only refers to `StartProxy` command. Standard `Start` command works as designed.

**Comment by Aaronontheweb** [comment]
We'll get this out as part of a 1.3.4 release shortly.
