### ISSUE TITLE
Ensure that PipeTo supports Task cancellations

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#3320]
At this moment our `PipeTo` support scenarios of failed or succeed task execution. However it turned out, that it may not work when a Task is being cancelled - the code in theory should work, however in practice it may not be the case.

We need tests in [PipeToSupportSpec](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Tests/Actor/PipeToSupportSpec.cs) which will confirm that task cancellation is handled correctly.

Also another matter - something to discuss about - is what the correct behavior should be in case if this case is not handled at this moment. 

1. As @OnurGumus in case of cancellation `task.Exception` can be null. I this is the only case (I haven't heard about the case when `task.IsFailed` is true and no exception has been provided), we could propagate null exception and i.e. add `IsCancelled` property to `Status.Failure`.
2. We could explicitly convert null exceptions to `OperationCancelledException` and forward it to failure case of `PipeTo` method. Afaik this is the closest to actual JVM Akka behavior - *Akka Futures don't have cancellations, but if future times out a `Status.Failure` with `TimeOutException` is returned*.
3. We can also add third case (like `Status.Cancelled`), however I'm afraid that this will increase complexity of the overall solution.

**Comment by Aaronontheweb** [comment]
Believe this has been resolved via https://github.com/akkadotnet/akka.net/pull/5123
