### ISSUE TITLE
Akka.Remote running in docker with different local and external ports

### ISSUE THREAD

**Issue by daninden** [akkadotnet/akka.net#3357]
I'm trying to build an Akka.NET cluster using Akka.NET 1.3.5 on an AWS ECS instance (docker/dotnetcore) with the dotnetty transport.
The problem I'm facing is that the Remoting port used on the inside of the ECS instance is different from the outside port (Docker port mapping).

It seems that for Akka there is a configuration option for this scenario (https://doc.akka.io/docs/akka/2.5/remoting.html#remote-configuration-nat) using bind-port and bind-hostname.
For the bind-hostname problem I can use the 'public-hostname' as the outward facing IP address, and bind on the 'hostname' adres.
For the port number there is no such option.

I've taken a a look at the sources, and I think it can be fixed in the DotNettyTransport.cs class in the Listen function, by binding on the port, but returning the public-port (new config option) in the address.

**Comment by daninden** [comment]
I created a PR #3358

**Comment by Aaronontheweb** [comment]
Makes sense to me @daninden - I'll review your PR and see if we can get this merged in for 1.3.6.

**Comment by Aaronontheweb** [comment]
Closed via #3390

**Comment by Aaronontheweb** [comment]
You can see the new `public-port` setting for Akka.Remote on our newly added configurations page here: http://getakka.net/articles/configuration/akka.remote.html
