### ISSUE TITLE
Is Akka.Persistence.MongoDB Part of the core Akka platform

### ISSUE THREAD

**Issue by waelemara** [akkadotnet/akka.net#3360]
Hi,
Just wondering if Akka.Persistence.MongoDB is part of the core platform, we are missing a lot in this package, Please refer to my issue here 
https://github.com/AkkaNetContrib/Akka.Persistence.MongoDB/issues/35#issuecomment-373071786

**Comment by Aaronontheweb** [comment]
Hi @waelemara - no it is not. It's a community-maintained plugin, although we provide infrastructure and assistance when we can.
