### ISSUE TITLE
Akka.net actors in UWP

### ISSUE THREAD

**Issue by vpopescu** [akkadotnet/akka.net#3365]
How does Akka.NET work inside a UWP app? Or rather, does it?

I have a net standard 2.0 assembly which is referenced by my UWP app.
The assembly contains a class with a factory call that returns me an IActorRef.
This works fine in WPF (Net Framework 4.6-4.7)
When I try it in UWP, I get an indefinite hang early on, when my library calls ActorSystem.Create("name").

**Comment by NickPolyder** [comment]
Hello, Could you provide some code that can be used as a reference ?

**Comment by vpopescu** [comment]
If you create a blank UWP project in VS, you can simply add two lines.

1. Open visual studio
2. Create a blank UWP app (Set Target and min version to Fall Creators Update, otherwise nuget will fail)
3. Open nuget and add Akka 1.3.5 to the solution.
4. Open MainPage.xaml.cs and add a using Akka.Actor
5. in Constructor, add a var sys = ActorSystem.Create("MYSample") after InitalizeComponent
6. run the project

If you put a breakpoint on the statement on line 5, you will see it never returns. I added the sample solution, but it's easier to just create your own. 

[app2.zip](https://github.com/akkadotnet/akka.net/files/1913635/app2.zip)

**Comment by NickPolyder** [comment]
Yes you must use your actor in a background thread.
Your actor system is Using the resources of the UI thread and thus your application cannot continue.
(If i'm wrong please correct me on this.)

I used it in my own UWP apps Creating the system in a background thread and it works fine.

Thanks,
