### ISSUE TITLE
Watch() in Cluster Environment

### ISSUE THREAD

**Issue by feitzi** [akkadotnet/akka.net#3367]
I want watch some actors inside of my singleton Monitor Actor. To do that i use the `watch()` method of my Monitor Actor. According to the [Akka.net documentation](http://getakka.net/articles/remoting/deathwatch.html) i get a `Terminate` message on a network failure. But i want the termination message only if the Actor graceful terminates or the node, in which the watched actor lives, is declared as down (removed from the cluster). 
Is it possible to combine `watch()` with the current Cluster State? And how can i do this?

**Comment by sean-gilliam** [comment]
Hopefully, you've found a solution to your problem. Generally questions should be directed to our gitter chat room https://gitter.im/akkadotnet/akka.net.
Issues are usually reserved for actual bugs. Closing this issue.
