### ISSUE TITLE
Akka.Net Streams and remoting (Sink.ActorRefWithAck)

### ISSUE THREAD

**Issue by xlegalles** [akkadotnet/akka.net#3371]
I've posted my problem to [StackOverflow](https://stackoverflow.com/questions/49360099/akka-net-streams-and-remoting-sink-actorrefwithack) first because I may have done something wrong. But did not get much success... 

Actually, I just try to make `Sink.ActorRefWithAck` work with remoting. I have first made a local UT which works. But as soon as both parties are in different processes, it fails: the Ack message sent back to the sender just finishes as a dead letter in the remote system. All debug messages are ON and I don't see anything related to the lifecycle of this actor that sent the init message but never received the response.

One detail I can add is that the stream is created from a `Receive()` handler as an async task with `PipeTo()`.
If you could at least give me some ideas about how to debug this problem?

Thank you.

**Comment by marcpiechura** [comment]
@xlegalles 
Currently don’t have the time to look into it but if it’s not time critical I would wait for StreamRefs, it’s basically Streams over the network and does all the havy lifting for you, see https://github.com/akkadotnet/akka.net/pull/3321

You could try it out by building the V1.4 branch manually.

**Comment by marcpiechura** [comment]
V1.4 branch is up on myget so you could grab StreamRefs from there. 

https://www.myget.org/F/akkadotnet-v14/api/v3/index.json

Feel free to reopen the issue or ask in gitter chat if you’ve further questions.

**Comment by ShahuN-107** [comment]
Any ETA on 1.4's release? I'm quite interested in this fix, but not so interested in grabbing the beta.
