### ISSUE TITLE
Enforce Props.Create(...) Roslyn Enhancement

### ISSUE THREAD

**Issue by nathvi** [akkadotnet/akka.net#3377]
I know that right now the correct way of creating `Props` is to call the `Props.Create(...)` method, which is not enforced by the compiler. I'm thinking that it would be a cool project to work on an extension where if somebody used `new Props(...)`, the compiler would throw an error and offer a code fix to reflect the correct way of creating a `Props` object.

**Comment by Horusiath** [comment]
I think, that the easiest way to solve this particular issue, is to obsolete public Props constructor.

**Comment by Danthar** [comment]
I think, but im not sure, that its needed for serialization purposes. In Remote deployment cases we are sending serialized props across the wire.

**Comment by Aaronontheweb** [comment]
Resolved via https://github.com/akkadotnet/akka.analyzers
