### ISSUE TITLE
Dependency Injection Documentation Has Dead Link

### ISSUE THREAD

**Issue by nathvi** [akkadotnet/akka.net#3378]
On the website:
http://getakka.net/articles/actors/dependency-injection.html#other-frameworks

The link to:
http://getakka.net/articles/actors/DI%20Core

Is broken. I'm not sure where it should be.

**Comment by marcpiechura** [comment]
We’ve moved our docs from the old repo https://github.com/akkadotnet/getakka.net/ into the main repo a few month ago but it looks like we forgot to move the DI Core article as well. The old one can be found here https://github.com/akkadotnet/getakka.net/blob/master/src/docs/DI%20Core.md might want to migrate it into the new format and send a PR?

**Comment by MostafaTrade** [comment]
I think nobody works on this one - so I am taking it up.

**Comment by jdsartori** [comment]
@MostafaTrade If you don't mind, I am going to take a stab at porting over the DI Core file.

**Comment by sean-gilliam** [comment]
Closed via #3729
