### ISSUE TITLE
Endpoint  Disassociated 

### ISSUE THREAD

**Issue by JTrotta** [akkadotnet/akka.net#3387]
When creating a new issue, please make sure the following information is part of your issue description. (if applicable). Thank You!

- Which Akka.Net version you are using: Last
- On which platform you are using Akka.Net: Windows & Linux 
- A list of steps to reproduce the issue. Or an gist or github repo which can be easily used to reproduce your case.

Hello I created a simple cluster among 2 server: 1 Linux  1 Windows. Same application.
Firewall are stopped.
As far as the cluster is not initialized, everything works fine. When one server start the cluster manually, the cluster is formed, the other server join the cluster regularly but in few seconds becomes unreachable, and a lot of errors come up in logging. One of the most significant errors are:
2018/04/14 11:41:18.760|Error|Akka.Logger.NLog.NLogLogger.LogEvent|Error caught channel [192.168.0.30:60066->192.168.0.31:32211](Id=30ea2cb4).

The cluster becomes unstable. 
Is there some configuration I missed? This is the config used by both server:
`akka {  
    loglevel = DEBUG
	  loggers =["Akka.Logger.NLog.NLogLogger, Akka.Logger.NLog"]
    actor {
        provider = cluster
    }
    remote {
        dot-netty.tcp {
  		    port = 32211
  		    hostname = 192.168.0.30
          public-hostname = 192.168.0.30
        }
    }
    cluster {
       seed-nodes = []
    }
}
`

**Comment by Aaronontheweb** [comment]
@JTrotta what's the full error message? Are you getting a length-frame encoding error?

**Comment by JTrotta** [comment]
@Aaronontheweb  That's the full log:
[logakka.txt](https://github.com/akkadotnet/akka.net/files/1913069/logakka.txt)
As you can see there are a lot of "Associated" and "Disassociated" events.

May it be a serialize/deserialize issue like here: [3031](https://github.com/akkadotnet/akka.net/issues/3031) ?

**Comment by Aaronontheweb** [comment]
Could be, although I don't see anything in the error logs here that would indicate that.

Looks to me like you've never had a functional cluster, poking through the logs here, so this smells like a borked configuration more than anything else. Can you guarantee that the addresses you're using are reachable?

**Comment by Aaronontheweb** [comment]
I don't see any serialization issue in the logs (which are formatted rather weirdly, FYI) - do you see that error showing up elsewhere?

**Comment by JTrotta** [comment]
What you mean for  

> do you see that error showing up elsewhere?
I have two application running one on  a server Centos, and one on my laptop for debugging. The log is a copy and paste from my console app.
O the server I have a similar log on a NLog file. It is the same of my console app.
Find attached the NLOG server log 
[server.log](https://github.com/akkadotnet/akka.net/files/1957396/server.log)

**Comment by Aaronontheweb** [comment]
It looks like there is something off with this node:

```
Akka.Remote.Transport.InvalidAssociationException: connection timed out: 192.168.0.103:32211
```

All of the disassociation errors are occurring when attempting to connect to this node. Are the serailization settings different on this node vs the others?

**Comment by JTrotta** [comment]
You were right, some differences between the two serialization settings.
Problem solved.
Thank you @Aaronontheweb
