### ISSUE TITLE
Akka.NET home page broken link and copyright

### ISSUE THREAD

**Issue by kevinmcfarlane** [akkadotnet/akka.net#3393]
A partial regression of #3106. 

Link non-functional: "Learn about Akka for the JVM **here**." The "here" is not active.

Copyright in footer: Year should be 2018. Could add some JavaScript to make it roll over each year, unless there's a reason for not having JS in footer?

**Comment by Aaronontheweb** [comment]
@kevinmcfarlane thanks for reporting this. Sounds like an artifact from the website redesign.
