### ISSUE TITLE
Akka.Fsharp.Tests need to be fixed and included in the build process

### ISSUE THREAD

**Issue by ivog** [akkadotnet/akka.net#3403]
Akka.Fsharp.Tests should be fixed and they should be run as part of the the CI process.

**Comment by chrisjhoare** [comment]
[This change] (https://github.com/akkadotnet/akka.net/commit/f346ce8949d7e4943a7ec49617525adad6b65384) Fixes the test - but I'm not entirely sure of the context around this.

**Comment by Aaronontheweb** [comment]
@chrisjhoare is that in a PR somewhere? I might need to update the FAKE script `build.fsx` to include the FSharp specs.
