### ISSUE TITLE
ClusterSharding.Get() with default actor.provider throws Exception

### ISSUE THREAD

**Issue by Lutando** [akkadotnet/akka.net#3408]
If you do a `ClusterSharding.Get(actorSystem)` using default configs an exception gets thrown here.

When changing the provider to 

`akka.actor.provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"`

It seems to be fine. I have trouble finding out about this on any of the documentation, is this intended behaviour?

**Comment by Horusiath** [comment]
Cluster sharding needs an operating cluster in order to work. For that actor provider must be configured to cluster.

**Comment by Lutando** [comment]
I see, thanks :)
