### ISSUE TITLE
Update to akka 1.3.6 - Donetty wont work.

### ISSUE THREAD

**Issue by JTrotta** [akkadotnet/akka.net#3415]
When creating a new issue, please make sure the following information is part of your issue description. (if applicable). Thank You!

- Which Akka.Net version you are using: 1.3.6
- On which platform you are using Akka.Net: windows/ mono 
- A list of steps to reproduce the issue. Or an gist or github repo which can be easily used to reproduce your case.

Just updated to akka 1.3.6, starting Actor System: ` ActorSystem.Create("ACTORSystem", akkaConfig);`
Got this error:
`[INFO][23/04/2018 08:50:41][Thread 0001][remoting] Starting remoting
[ERROR][23/04/2018 08:50:42][Thread 0011][Akka.Remote.Transport.DotNetty.TcpTran
sport] Failed to bind to 192.168.0.103:32211; shutting down DotNetty transport.
Cause: System.MissingMethodException: Impossibile trovare il metodo 'Void DotNet
ty.Buffers.UnpooledByteBufferAllocator..ctor()'.
   in Akka.Remote.Transport.DotNetty.DotNettyTransport.ServerFactory()
   in Akka.Remote.Transport.DotNetty.DotNettyTransport.<NewServer>d__20.MoveNext
()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'ecc
ezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   in System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAw
aiter.GetResult()
   in Akka.Remote.Transport.DotNetty.DotNettyTransport.<Listen>d__21.MoveNext()
[ERROR][23/04/2018 08:50:42][Thread 0001][remoting] Remoting error: [Startup fai
led] []
Cause: Unknown`
Attached find the configuration HOCON file.
[akka.txt](https://github.com/akkadotnet/akka.net/files/1937328/akka.txt)

**Comment by JTrotta** [comment]
May it be related to this: [#3410](https://github.com/akkadotnet/akka.net/pull/3410).
In that case how to fix it using nuget library?

**Comment by stijnherreman** [comment]
I had a similar "failed to bind to ..." error with DotNetty 0.4.7

Open the NuGet Package Manager in Visual Studio, go to the Installed tab. For each DotNetty package, select version 0.4.6 and click the Update button. You may have to manually modify binding redirects, replacing `<bindingRedirect oldVersion="0.0.0.0-0.4.7.0" newVersion="0.4.7.0" />` with `<bindingRedirect oldVersion="0.0.0.0-0.4.6.0" newVersion="0.4.6.0" />`.

**Comment by Aaronontheweb** [comment]
Yeah, as I mentioned here: https://github.com/akkadotnet/akka.net/issues/3327

Don't upgrade to DotNetty v0.4.7. It's broken and can't be fixed with any work-arounds. The solution is to simply not upgrade beyond what Akka.Remote uses, which is DotNetty v0.4.6.  

In the meantime, in our [next release we've locked down the DotNetty version to v0.4.6](https://github.com/akkadotnet/akka.net/pull/3410) so upgrades can't happen by accident. Supposedly v0.4.8 is going to be shipped soon but we have no control over that.

Going to close this - just downgrade your DotNetty version to v0.4.6 in the meantime.

**Comment by gemr142388** [comment]
@Aaronontheweb It is working with DotNetty v0.4.8?

**Comment by Aaronontheweb** [comment]
Yes, this is working now with Akka.NET v1.3.8 which uses DotNetty v0.4.8.
