### ISSUE TITLE
Akka Testkit not compatible with xUnit 2.3.1

### ISSUE THREAD

**Issue by CJToennies** [akkadotnet/akka.net#3418]
We are using Akka 1.3.6 on Windows 10.
As testframework we are using xUnit.
As we used xUnit 2.3.0 we didn't have a problem, but as we switched to 2.3.1 we are getting file not found exceptions:

  Dummy_IT.ConfigurationTest.NumberOfLocations [FAIL]
      System.IO.FileNotFoundException : Could not load file or assembly 'xunit.assert, Version=2.3.0.3820, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The system cannot find the file specified.
      Stack Trace:
           at Akka.TestKit.Xunit2.XunitAssertions.AssertTrue(Boolean condition, String format, Object[] args)
           at Akka.TestKit.TestKitBase.FishForMessage[T](Predicate`1 isMessage, Nullable`1 max, String hint)

This happens only when using the xunit.console.runner, not in Visual Studio (we are using the resharper testrunner).

I stripped the test down as much as possible to find the source of this behaviour. As soon as 
I removed the *FishForMessage* call the problem disappeared. But that can't be solution for it.

**Comment by Aaronontheweb** [comment]
@CJToennies I'll take a look at this. I upgraded to XUnit 2.3.1 in some projects recently but haven't run into this issue. 

If I can confirm this issue, that would mean that this is a breaking binary incompatibility in XUnit, not an issue with Akka.TestKit.XUnit per-say. Guess we'd want to upgrade then.
