### ISSUE TITLE
Fix search bar on documentation website

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3423]
We've known that the search functionality on the site has been busted for a while, but I received an email from an end-user that explains how to fix it (they also use DocFx):

```
<?xml version="1.0"?>

<configuration>

    <system.webServer>

        <staticContent>

            <mimeMap fileExtension=".json" mimeType="application/json" />

                </staticContent>

    </system.webServer>

</configuration>
```

Since we're using Azure Websites to host the docs, which IIRC is running on IIS, we should be able to slap that configuration at the root of the website and fix it that way.

**Comment by Aaronontheweb** [comment]
Longer version of the steps for fixing this: https://blogs.msdn.microsoft.com/africaapps/2013/06/07/how-to-serve-static-json-files-from-a-windows-azure-website/

**Comment by Aaronontheweb** [comment]
Trying this out on another project where we use a similar DocFx setup to Akka.NET

**Comment by Aaronontheweb** [comment]
Also going to need to enable a specific DocFx step in order to get this working: https://github.com/dotnet/docfx/issues/2679#issuecomment-383953842

**Comment by Aaronontheweb** [comment]
(that step produces the index.json)

**Comment by mmisztal1980** [comment]
@Aaronontheweb  I can have a look at this. Where are the search bar & the index.json located in code?

**Comment by mmisztal1980** [comment]
I've forked & cloned the docs site repo. However I've run into this:

```
grunt
Loading "sync.js" tasks...ERROR
>> TypeError: Cannot read property 'length' of undefined
Loading "livereload.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "sync" not found. Use --force to continue.
```

Can anyone advise how to get past that? Unfortunately grunt is not my speciality (I'm more of a gulp/webpack person).

**Comment by mmisztal1980** [comment]
Also, I seem to be unable to locate the docfx.json to add the `ExtractSearchIndex` postprocessor...

**Comment by sean-gilliam** [comment]
The old documentation repo located at (https://github.com/akkadotnet/getakka.net) has been abandoned and is only there for legacy / information purposes.
It was a pain to work with, used a for pay 3rd party theme, and was in desperate need of a facelift.

So we ported everything over to using DocFx and is now located in our main repo (https://github.com/akkadotnet/akka.net/tree/dev/docs).
That's where you'll find the docfx.json file.

@akkadotnet/core We should probably put a huge disclaimer on the old repo and point them to the docfx stuff.

**Comment by mmisztal1980** [comment]
@sean-gilliam can you tell me how do I run the site locally to test the fix? Is this a static site served from IIS?

**Comment by Aaronontheweb** [comment]
If you clone the main repo, just need to run `serve-docs.cmd` and that will build the website. Make sure you run `build.cmd buildrelease` first so the binaries are up to date.
