### ISSUE TITLE
Add Exception parameter overloads to all logging methods

### ISSUE THREAD

**Issue by pshrosbree** [akkadotnet/akka.net#3424]
The following overloads are needed, probably in `Akka.Event.ILoggingAdapter`:

`public void Debug(Exception cause, string format, params object[] args)`

`public void Info(Exception cause, string format, params object[] args)`

`public void Warning(Exception cause, string format, params object[] args)`

` public void Log(LogLevel logLevel, Exception cause, string format, params object[] args)`

@Aaronontheweb

**Comment by Aaronontheweb** [comment]
Sending in a PR that will address this as part of the v1.4.0 release.

**Comment by sean-gilliam** [comment]
Closed via #3520
