### ISSUE TITLE
Potential Memory Leak With Log Events

### ISSUE THREAD

**Issue by jschneider1207** [akkadotnet/akka.net#3425]
I noticed an Akka.Net application I'm developing seems to have a memory leak.  As it ran the memory very slowly increased, and when it stopped doing any work it never went back down.  I did some profiling with DotMemory and noticed there are a ton of log event object instances not getting collected.  These include:
* `Akka.Event.LogMessage`
* `Akka.Event.Error`
* `Akka.Event.Info`
* `Akka.Event.Warning`

We're using the Serilog adapter (`"loggers": ["Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog"]` in our config) and an Elasticsearch sink for that.  Is there something specific we need to be doing to ensure these events get consumed properly?

The references to these event instances are all `Akka.Actor.Envelope[32]` instances wgucg are references by `ConcurrentQueue<Envelope>`s.

Akka.Net version: 1.3.2
Platform: .NET Framework 4.6.2

**Comment by sschneider1207** [comment]
I have two DotMemory workspace files that contain many snapshots showing the issue if it would help.  I'm currently checking with my organization for whether they are okay to share.

**Comment by Aaronontheweb** [comment]
@sschneider1207 we had this exact issue with all loggers in general a long time ago, but that's been fixed for a couple of years.  I thought we had added a spec to check for this scenario exactly but apparently not.

That being said, I'm skeptical. We have users running large workloads (100k - 1m msg / s range) who haven't reported this being an issue. What does your Serilog configuration look like? I've run into issues before where Serilog itself has been the issue. And are you still seeing output emitted to your Serilog sink while this memory buildup is occurring?

**Comment by sschneider1207** [comment]
Here's our Serilog configuration, it's pretty basic:
```csharp
Log.Logger = GetLogger(logUrl, logIndexFormat);
...
private static ILogger GetLogger(string logUrl, string indexFormat) => new LoggerConfiguration()
            .Enrich.WithThreadId()
            .Enrich.WithExceptionDetails()
            .MinimumLevel.Verbose()
            .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri(logUrl))
            {
                IndexFormat = indexFormat,
                AutoRegisterTemplate = true,
                TemplateName = "voyager-doc-updater-template",
                MinimumLogEventLevel = LogEventLevel.Verbose,
                CustomFormatter = new ElasticsearchJsonFormatter(renderMessage: true),
                
            })
            .CreateLogger();
```

We have noticed at times that serilog will completely stop emitting events.

**Comment by Danthar** [comment]
@sschneider1207 it could very well be that its something in the Elasticsearch logging sink which is causing this. 
What if you replace it with a simple rollingfilelogger ? That would eliminate the network being a factor here.
It could very well be that the Elasticsearch sink becomes congested due to some reason.

**Comment by sschneider1207** [comment]
We had the the same thought and tried the normal (not rolling) file logger, it had the same behaviour.  We're thinking about trying the NLog adapter instead of serilog to see if that is the problem.

**Comment by Danthar** [comment]
@sschneider1207 Did you end up trying it with the NLog adapter ?

**Comment by Aaronontheweb** [comment]
@sschneider1207 so I did some local testing earlier this week to see if the default Akka.NET logging implementation leaked and I was unable to find any evidence of "memory creep" after running the application continuously logging 100 events per second for 4-5 hours.

I'll try out the default Serilog library and see if I can reproduce that issue there, but so far it looks like the default Akka infrastructure runs fine.

**Comment by sschneider1207** [comment]
We very briefly tested with the NLog adapter and didn't see any problem, but we have been side tracked by some other projects lately so we haven't had too much time to look into it.

**Comment by sschneider1207** [comment]
I was finally able to test a bit more with NLog, unfortunately it looks like the adapter just doesn't work very much so we won't be able to use it.  Every message logged through `Context.GetLogger....` throws format exceptions and only logs `{0}`.

**Comment by Aaronontheweb** [comment]
@sschneider1207 how out of date is that adapter?

**Comment by sschneider1207** [comment]
The NLog adapter?  I tried with the most recent version, 1.3.1

**Comment by Aaronontheweb** [comment]
And it really doesn't log anything? Is it throwing format exceptions because you were using Serilog-format strings from before?

**Comment by sschneider1207** [comment]
I hadn't used NLog before, but based on [their wiki](https://github.com/nlog/NLog/wiki/How-to-use-structured-logging) basic format strings from serilog should still work with it.

My test log was:
```csharp
Context.GetLogger().Info("My path: {path}", Self.Path);`
```

That threw a FormatException and logged `{0}`

I very briefly stepped through to see what the adapter was doing to see if I could fix it and I noticed the `NLogLogger` class creates a `LogEventInfo` via 
```csharp
new LogEventInfo(level, logger.Name, null, "{0}", new[] { message }, exception);
``` 
in the `LogEvent/5` function, where `message` is a `Akka.Event.LogMessage` object, which doesn't seem to be able to format

**Comment by Danthar** [comment]
@sschneider1207 So yeah. Correct, this particular logging format wont work with NLOG. This is because NLOG does not support semantic logging formats.

So you need to this instead: 

``` 
Context.GetLogger().Info("My path: {0}", Self.Path);
```

**Comment by sschneider1207** [comment]
I did try that and it works however that flattens the log message and does not add any of the format parameters are log properties like Serilog does, so it isn't usable for us.

**Comment by snakefoot** [comment]
@Danthar NLog 4.5 supports Serilog Message Templates. Created PR: https://github.com/AkkaNetContrib/Akka.Logger.NLog/pull/36

**Comment by Danthar** [comment]
@sschneider1207 i understand that. But then, wasn't the goal to verify if the memory leak occurs in nlog as well ?

@snakefoot thanx. Ill take a look.

**Comment by sschneider1207** [comment]
You're correct, I didn't make it that far in testing NLog once I noticed the log messages wouldn't work.  I'll update this once I've been able to more thoroughly try it out.

**Comment by sschneider1207** [comment]
I tested some more with NLog, and I noticed a similar problem as well as a potential reason.  The NLog elasticsearch sink was making batch index requests each containing a single log instead of actually batching them up.  This caused log messages to build up in memory as they were getting created faster than it could ship them.  

I'm not very familiar with NLog but I suspect the sink is not supposed to do this.  I'm going to test some more with Serilog to see if it is exhibiting the same behaviour.

**Comment by snakefoot** [comment]
@sschneider1207 You can use `AsyncTargetWrapper` or `<targets async="true">` and NLog will do batching for you,

**Comment by sschneider1207** [comment]
Worked as expected once I added the wrapper.  It looks like there is no memory leak here, the logger just can not keep up with how many messages we're sending it.  I double checked with Serilog that that is the issue.  

Besides tweeking batch settings on the log sinks themselves, is there anything that can be configured for this in Akka itself?  Perhaps something like additional logger actors or being able to deploy them on different servers via the cluster package?

**Comment by sschneider1207** [comment]
Another quick question, is there any way to configure the logger to discard logs once a backlog reaches a certain length?

**Comment by snakefoot** [comment]
Both NLog and Serilog can perform discard in their async-wrapper when overflow occurs.


Sent from my Samsung device


-------- Original message --------

**Comment by sschneider1207** [comment]
I don't think the logs are getting that far, they are getting backed up in
the logging actors mailbox

**Comment by Aaronontheweb** [comment]
Going to mark this as closed since we haven't heard anything about this issue in years.
