### ISSUE TITLE
Issue with PubSub Configuration 

### ISSUE THREAD

**Issue by yesh-nadella** [akkadotnet/akka.net#3426]
I'm using Akka 1.3.4 and running it on Windows. There are three nodes: two windows services and a web app. One of the windows services acts as a seed node. The PubSub extension is only used on the WebApp node - the mediator is only activated on this node. I noticed the below issues with different configuration settings:

**If extension setting is not added on all the nodes, I get the below errors. As noted above, Mediator is used only in the WebApp node, so why do I have to add this setting on all the nodes?**

**Extension Setting**
extensions = ["Akka.Cluster.Tools.PublishSubscribe.DistributedPubSubExtensionProvider,Akka.Cluster.Tools"]

**Errors**
[Akka.Remote.EndpointWriter] [ERROR] : AssociationError [akka.tcp://TestCluster@localhost:4053] <- akka.tcp://TestCluster@localhost:4057: Error [Cannot find serializer with id [9]. The most probable reason is that the configuration entry 'akka.actor.serializers' is not in sync between the two systems.] [   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)

[Akka.Actor.EmptyLocalActorRef] [INFO] : Message Status from akka.tcp://TestCluster@localhost:4057/system/distributedPubSubMediator to akka://TestCluster/system/distributedPubSubMediator was not delivered. 1 dead letters encountered.

**Should pub-sub role setting be added on all the nodes? If I add this setting to all the nodes I get these two errors.**

pub-sub Setting
pub-sub {
   role = "WebApp"
 }

[Akka.Actor.OneForOneStrategy] [ERROR] : Error while creating actor instance of type Akka.Cluster.Tools.PublishSubscribe.DistributedPubSubMediator with 1 args: (Akka.Cluster.Tools.PublishSubscribe.DistributedPubSubSettings)

[Akka.Actor.EmptyLocalActorRef] [INFO] : Message Status from akka.tcp://TestCluster@localhost:4057/system/distributedPubSubMediator to akka://TestCluster/system/distributedPubSubMediator was not delivered. 1 dead letters encountered.

**Comment by Horusiath** [comment]
If you need distributed pub-sub only on a subset of all nodes, simply initialize them with some role and use it to narrow the scope of nodes used. Keep in mind that:

1. Other nodes, which don't use pub sub should not initialize DistributedPubSub extension.
2. DistributedPubSub uses extra configuration - often to avoid potential problems you may want to add `DistributePubSub.DefaultConfig()` as a fallback to your configuration.

**Comment by asubabu** [comment]
Should the extension setting and the default settings be added to all the nodes then?

**Comment by Danthar** [comment]
@asubabu no, only the nodes you want to let take part in the distributed pubsub
