### ISSUE TITLE
Akka.Persistence LocalSnapshotStore file open race conditions

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3431]
Version: Akka.NET v1.3.6

Looks like, based on some persistence IDs that are used and the presence of special characters like `/` or `\` might throw `System.IO.FileNotFoundException: Unable to find the specified file.` exceptions inside the `LocalSnapshotStore`.

I'm thinking that we need to either come up with some way of encoding the PersistenceID safely or throw a more explicit exception if that's the case. Going to add a spec to reproduce first.

**Comment by Horusiath** [comment]
If I remember correctly Peristent ID is escaped using URI data escape method. Maybe we need something stronger?

**Comment by Aaronontheweb** [comment]
@Horusiath yeah, I need to rename the issue - after looking at the logs looks like the issue is actually a bit of a race condition - tried to write to the file before it was open.

**Comment by Aaronontheweb** [comment]
https://github.com/akkadotnet/akka.net/blob/9c1bc9fbe980335a1bc34d61a02ab4afd4203a37/src/core/Akka.Persistence/Snapshot/LocalSnapshotStore.cs#L202-L214

Looks like the `MoveTo` command is failing for some reason.

**Comment by Aaronontheweb** [comment]
some possibilities I am considering here:

* Some other process is mangling the temp files before they have a chance to be moved;
* There are multiple competing snapshot stores running on the same machine;
* Etc...

I do see an error that looks like this elsewhere in the same set of logs:

```
2018-04-23 18:06:11 [Error] (akka://someSys/someActor) Unable to save ReliableMailmanActor snapshot with id "foo"
System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\BD\MMS Fk\Mms.Fk.UpstreamProxy\snapshots\snapshot-foo-0-636601323711494050.tmp' because it is being used by another process.
```

I'm going to see if I can rule out that this is an issue with one isolated `LocalSnapshotStore` happily doing its thing on its own and see if we can determine if it was an issue with the end-user environment that caused this.

**Comment by Aaronontheweb** [comment]
The issue is that since we’re not incrementing the sequence number (using the Journal) in Akka.Persistence, two snapshots taken close together are going to have the same filename since the timestamp will also match. Given that the `LocalSnapshotStore` processes snapshot save requests concurrently, we’re going to run into trouble if the filenames are identical, and that’s what is happening here.

It’s not clear yet if we can patch this at all inside Akka.NET, for two reasons:

1. Snapshots are supposed to be incremented along with the journal, thus the sequence number of the snapshot increases monotonically over time; however there are cases such as this one where users can use snapshots only and never really increment the sequence number at all. While technically we allow that and we allow overwriting of existing snapshots, it’s not a fully supported use case.
2. Fixing this issue would come with some severe performance limitations - essentially, we’d have to force all writes to occur serially for a given persistence id. Not sure that’s worth it in this case.

If you run into this issue, there are a couple of things you can do to fix it:

1. Use an Akka.Persistence `SnapshotStore` implementation backed by an actual database. They can resolve the lock / contention issues that a basic filesystem can't.
2. Use the journal and increment the sequence numbers. That will eliminate file collisions.

Going to close this since it's a won't-fix, IMHO.
