### ISSUE TITLE
Upgrade downstream dependencies (v1.3.* or v1.4)

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3438]
Weighing whether or not we should do this in a v1.4.0 release or do it in a maintenance patch between now and then.

We're using older versions of:

* [x] Newtonsoft.Json
* [x] Hyperion (DData, specifically - and is it even needed there?)
* [x] Google.Protobuf
* [x] FluentAssertions
* [x] XUnit
* [x] TeamCity.MessageHelpers

And probably more that I'm not remembering.

Should we go through and update these in our next big feature release? Or incrementally upgrade them (i.e. change one thing at a time...)

I'm of the opinion that the serializer stuff should probably be upgraded since there's performance / compat fixes in there that would stand to benefit our users. The rest is mostly dressing for the project internally.

Thoughts? cc @akkadotnet/contributors

**Comment by Danthar** [comment]
The FluentAssertions, XUnit and TCHelpers can go in the next release. The serializers, im not sure if there are any big changes between the protobuf we are using now and the current released version. But i would not expect it to be anything big. So updating that will probably be rather harmless (famous last words).
As for the rest, doing incremental updates does have the benefit of increased flexibility and lowering our perceived impact per release. But it also has the potential to let issues drag out across multiple releases.
So im not sure if doing it incrementally would bring us or our users any real benefit. If unforeseen stuff breaks, our users can use the previous release, while we work to get a fix out. 
So I guess i don't have a real preference on that, there are pro's and con's to each approach.
