### ISSUE TITLE
Azure Functions

### ISSUE THREAD

**Issue by eaba** [akkadotnet/akka.net#3442]
Hi, this is just a thought: Akka.net Azure functions support?
Can this be ever possible?

**Comment by eaba** [comment]
Am thinking if `server less` is possible with Akka.Net

**Comment by Horusiath** [comment]
@eaba serverless is made for stateless applications. Akka.NET (and actor model in general) are designed with statefull applications in mind. That being said, akka.net would be good as a foundation to build a serverless framework on top of (see [OpenWhisk](https://openwhisk.apache.org/) which is a serverless platform build on top of Akka JVM).

**Comment by eaba** [comment]
@Horusiath thanks....basically I should that thought of my head...it works the other way round.
