### ISSUE TITLE
NullReferenceException when using stash with persistent actor

### ISSUE THREAD

**Issue by Sam13** [akkadotnet/akka.net#3462]
Akka.Net version: 1.3.7, platform: Windows, .NET 4.6.1

When trying to use the the stash (`IWithUnboundedStash`) on an actor which derives from `AtLeastOnceDeliveryReceiveActor` or `ReceivePersistentActor` a `NullReferenceException` is thrown after calling `Stash.UnstashAll()`.
When deriving from `ReceiveActor` the stash works.

`System.NullReferenceException HResult=0x80004003 Message=Object reference not set to an instance of an object. Source=Akka.Persistence StackTrace: at Akka.Persistence.Eventsourced.PeekApplyHandler(Object payload)`

Example unit test which reproduces the problem: https://gist.github.com/Sam13/4d4a0f66d8ab50990d9df4aaa2345de0

**Comment by Horusiath** [comment]
@Sam13 in your example you're implementing `IWithUnboundedStash` however, you're not implementing a Stash property (it's commented). Is this right?

**Comment by Aaronontheweb** [comment]
@Horusiath I don't think the actor would be able to compile if that were the case unless the interface was already implemented on an underlying base class.

**Comment by Sam13** [comment]
@Horusiath The stash property is already implemented by the persistence base class. I'd just left the interface there - when you comment / uncomment some stuff you can "convert" it to a non persistent actor in which the stash works...

**Comment by Arkatufus** [comment]
I tried replicating the problem with the test case but could not really duplicate it, have it been fixed?

**Comment by Arkatufus** [comment]
@Sam13 Can you confirm that this is still a problem?

**Comment by Sam13** [comment]
@Arkatufus Sorry I'm not working with Akka.NET at the moment. But if the unit test I provided is running fine now it may have been fixed...

**Comment by Arkatufus** [comment]
I'll close this issue then, thank you for the report.
