### ISSUE TITLE
Akka.Persistence.Fsharp doesn work with FSharp.Core 4.3.4

### ISSUE THREAD

**Issue by IvanAntipov** [akkadotnet/akka.net#3465]
My project:
F# 
FSharp.Core 4.3.4
net471
Akka.Persistence.Fsharp 1.3.7

I copied example from
[https://github.com/akkadotnet/akka.net/blob/3f924fda8d6ca55c5af90a710d23be8ce36d5c7a/src/examples/PersistenceExample.FsApi/Program.fs]
```
        open Akka.Persistence.FSharp
        let s0 = 
            spawnPersist system "s0" {
                state = []
                apply = fun m s e -> 
                    Console.WriteLine (sprintf "Apply %A %A %A" m s e)
                    e::s
                exec = fun m s e -> 
                    m.PersistEvent
                    Console.WriteLine  (sprintf "Exec %A %A %A" m s e)
                    m.PersistEvent (fun e -> e::s) [e]
            } []
        s0 <! "foo"
        s0 <! "bar"
        s0 <! "baz"
```
Method spawnPersist throws exception

> Unhandled Exception: System.Exception: Doesn't match System.Linq.Expressions.Expression`1[System.Func`1[Akka.Persistence.FSharp+FunPersistentActor`3[System.Object,System.Object,Microsoft.FSharp.Collections.FSharpList`1[System.Object]]]] System.Func`1[Akka.Persistence.FSharp+FunPersistentActor`3[System.Object,System.Object,Microsoft.FSharp.Collections.FSharpList`1[System.Object]]]
>    at FileCopying.Linq.PersistentExpression.ToExpression[Command,Event,State](Expression`1 f) in 

I fixed it with my own implementation of spawnPersist
```
        let spawnPersist1 (actorFactory : IActorRefFactory)  (name : PersistenceId) (aggregate: Aggregate<'Command, 'Event, 'State>) (options : SpawnOption list)  =
            let props = applySpawnOptions (Props.Create (fun () -> new FunPersistentActor<'Command, 'Event, 'State>(aggregate, name))) options
            actorFactory.ActorOf(props, name)
```
So, no Expression transformation needed with FSharp.Core 4.3.4 anymore, F# lamda now compiles to System.Linq.Expressions.Expression.

**Comment by kennethito** [comment]
I noticed the same thing when fsharp was being updated for .net core. https://github.com/akkadotnet/akka.net/issues/2826#issuecomment-375804430 .  If I remember right, when I changed the test project to be netcoreapp2.0 tests would fail on the same error when spawning actors.  

The related link in my comment has one possible way to deal with the issue.

**Comment by j-alexander** [comment]
It seems this exception `Doesn't match` (above) continues to be an issue with the latest versions:

`FSharp.Core 4.6.2`
`net472`
`Akka.Persistence.FSharp 1.3.13`

I see no exception using the workaround above, but I wasn't able to get it working successfully, either. :)

**Comment by Aaronontheweb** [comment]
I'll try publishing a new nightly build - we just moved onto .NET Standard 2.0 and so we should probably update the underlying F# dependencies. Would love some help figuring out what we need to do there to resolve this
