### ISSUE TITLE
SqlCommands with connections are not garbagecollected, just disposed.

### ISSUE THREAD

**Issue by jarlrasm** [akkadotnet/akka.net#3471]
`Akka.Persistence.Sql.Common.Journal.SqlJournal` is using a single `CancellationToken` for all db-operations, that is only disposed on shutdown, if I understand the code correcly. This indirectly keeps references to all `SqlCommands`, which again have references to connections and so on, preventing GC. I believe this can be fixed with creating a new `CancellationTokenSource` with `CreateLinkedTokenSource` for each command, however I am not quite sure why the implementation is as it is, so I would like to have some feedback from the developers before I fix it and create a pullrequest.

**Comment by Horusiath** [comment]
@jarlrasm If I remember correctly, the idea was to interrupt all in-progress commands, when the journal is going to die.

**Comment by Aaronontheweb** [comment]
closed via https://github.com/akkadotnet/akka.net/pull/3494
