### ISSUE TITLE
How to redirect a request based on rules 

### ISSUE THREAD

**Issue by virenderkverma** [akkadotnet/akka.net#3478]
I have 3 servers AAA, BBB, CCC hosted web.api when API called from a client I want the process some special parameterized request into a specific server for example if the request contains parameter like AA then process into AAA, and BB then process into BBB and if DDD then process into any server based on round robin or least workload. 

And return a response to the client.  

How it possible to achieves through akka.net?

**Comment by sean-gilliam** [comment]
Hopefully, you've found a solution to your problem. Generally questions should be directed to our gitter chat room https://gitter.im/akkadotnet/akka.net.
Issues are usually reserved for actual bugs. Closing this issue.
