### ISSUE TITLE
WatchTermination Task returns too soon when stream is run with a MergeHub sink

### ISSUE THREAD

**Issue by anton-pt** [akkadotnet/akka.net#3488]
Akka.NET version: 1.3.8 running on .NET Core on a Mac.

When running the following code, I'd expect the `waitToFinish` `Task` to complete only after the all the elements in the stream have reached the `Sink`. However, the `Task` completes immediately after stream materialisation.

```csharp
using (var sys = ActorSystem.Create("Test-System"))
using (var materializer = sys.Materializer())
{
	var mergeHubSink =
		MergeHub.Source<int>()
                        .Throttle(1, TimeSpan.FromSeconds(1), 1, ThrottleMode.Shaping)
			.To(Sink.ForEach<int>(Console.WriteLine))
		        .Run(materializer);

	Console.WriteLine("Starting source...");
	var waitToFinish =
		mergeHubSink.RunWith(
			Source.From(Enumerable.Range(1, 3))
		              .WatchTermination(Keep.Right),
			materializer);

	waitToFinish.Wait();
	Console.WriteLine("Source terminated.");

	Console.ReadLine();
}
```

**Actual output**

```
Starting source...
Source terminated.
1
2
3
```

**Expected output**

```
Starting source...
1
2
3
Source terminated.
```

**Comment by vasily-kirichenko** [comment]
There is (implicit) buffer (of size 16 by default) between your source and sink, try something like `Enumerable.Range(1, 20)` or set `.Buffer(0)` (or WithBuffer, I don’t remember).

So, you are watching the source, which happily pushes 3 elements into the buffer and terminates.
Stream back pressured, but there are buffers between stages.

**Comment by anton-pt** [comment]
Looks like you are right about the cause but not the solution.

```csharp
using (var sys = ActorSystem.Create("Test-System"))
using (var materializer = ActorMaterializer.Create(sys, ActorMaterializerSettings.Create(sys).WithInputBuffer(1, 1)))
{
	var mergeHubSink =
		MergeHub.Source<int>()
		.Buffer(1, OverflowStrategy.Backpressure)
		.Throttle(1, TimeSpan.FromSeconds(1), 1, ThrottleMode.Shaping)
		.Buffer(1, OverflowStrategy.Backpressure)
		.To(Sink.ForEach<int>(Console.WriteLine))
		.Run(materializer);

	Console.WriteLine("Starting source...");
	var waitToFinish =
		Source.From(Enumerable.Range(1, 20))
		.Buffer(1, OverflowStrategy.Backpressure)
		.WatchTermination(Keep.Right)
		.Buffer(1, OverflowStrategy.Backpressure)
		.To(mergeHubSink)
		.Run(materializer);

	waitToFinish.Wait();
	Console.WriteLine("Source terminated.");

	Console.ReadLine();
}
```

This produces the output:
```
Starting source...
1
... 2-5
6
Source terminated.
7
... 8-19
20
```

A buffer of leads to no output - it seems the stream crashes.

**Comment by vasily-kirichenko** [comment]
Try `MergeHub.Source<int>(perProducerBufferSize: 1)`

**Comment by anton-pt** [comment]
That helps but it seems that there is still a buffer size of 4 somewhere:

```
Starting source...
1
... 2-15
16
Source terminated.
17
18
19
20
```

**Comment by marcpiechura** [comment]
@anton-pt try to remove the '.Buffer' calls

**Comment by anton-pt** [comment]
Yup, that's helped... nearly there ;-)

```csharp
using (var sys = ActorSystem.Create("Test-System"))
using (var materializer = ActorMaterializer.Create(sys, ActorMaterializerSettings.Create(sys).WithInputBuffer(1, 1)))
{
	var mergeHubSink =
		MergeHub.Source<int>(1)
				.Throttle(1, TimeSpan.FromSeconds(1), 1, ThrottleMode.Shaping)
				.To(Sink.ForEach<int>(Console.WriteLine))
				.Run(materializer);

	Console.WriteLine("Starting source...");
	var waitToFinish =
		Source.From(Enumerable.Range(1, 5))
              .WatchTermination(Keep.Right)
		      .To(mergeHubSink)
              .Run(materializer);

	waitToFinish.Wait();
	Console.WriteLine("Source terminated.");

	Console.ReadLine();
}
```

produces the output:

```
Starting source...
1
2
3
Source terminated.
4
5
```

**Comment by marcpiechura** [comment]
You will never get the termination in the last line, what happens is that the source emits the last item and then signals completion downstream, the WatchTermination receives the signal and completes the task even if the last elements are still in flight. 
So termination doesn’t signal if the complete stream is done, only the part that is upstream.
If you want to wait to the end you need to wait for the task that is produced by Sink.ForEach

**Comment by marcpiechura** [comment]
The problem is that you’re calling MergeHub.Source only once and than reuse the materialzed sink for many sources, so the task produced by the call would only work for one source but not for the others which can be attached at any point in time later. 

Maybe you could explain what you’re trying to archive and based on that we mind find a solution that works. Also, for discussions like that it would be easier to continue in Gitter char ;-)

**Comment by anton-pt** [comment]
Having thought about it more carefully, the behaviour with `MergeHub.Source(1)` makes perfect sense for my application. I'll close the issue.
