### ISSUE TITLE
Implement Remote deployment tests

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#349]
See #347 

We lack solid tests for remote deployment.

**Comment by Aaronontheweb** [comment]
I think we can mark this as closed - we know there's some work to be done on the serialization of `Props` and `SupervisorStrategy`, but we now have tests that actually do lots of remote deployments now per the work that went into resolving #198.

Marking this as closed for now unless someone else feels that we should revisit.
