### ISSUE TITLE
Static log initialisation errors if first log message is in async callback

### ISSUE THREAD

**Issue by chrisalexander** [akkadotnet/akka.net#3502]
Hello, first of all apologies for a reasonably vague issue. I noticed this in production and am still working through reproducing it on my machine, but I thought it might be helpful to get it out there early to see if anyone has more expertise in this area and can advise.

Akka.Net version: v1.3.8
Platform: C#; .NET 4.6.1; Windows 10 / 7

I have an actor which initialises a logger as per usual:

    private static readonly ILoggingAdapter Log = Logging.GetLogger(Context);

The actor extends ReceiveActor, and then has a very simple constructor similar to below:

```
public MyClass : ReceiveActor
{
    public MyClass(IActorRef otherActor)
    {
        Receive<Message>(m =>
        {
            otherActor
                .Ask<OtherMessage>(new object())
                .ContinueWith(t =>
                {
                    Log.Info("Message received");
                    return t.Result; // Bad practice etc. but for demo...
                })
                .PipeTo(Self);
        }
    }
}
```

I then get an exception with a stack that looks like this:

```
Unhandled message from akka://app/deadLetters : Failure: System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'app.MyActor' threw an exception. ---> System.NotSupportedException: There is no active ActorContext, this is most likely due to use of async operations from within this actor.
   at Akka.Actor.ActorBase.get_Context()
   at Akka.Actor.UntypedActor.get_Context()
   at app.MyActor..cctor() in D:\a\1\s\MyActor.cs
```

I am just trying sending a log message while in the Receive<Message> rather than in the ContinueWith to see if that sorts it out, but I'm pretty sure I have done it in the past without issue...

**Comment by chrisalexander** [comment]
Thanks Aaron. To first address your questions:

1. The error occurs when the message is being processed, specifically once the Ask<T> has completed and the ContinueWith is invoked. Actor starts fine.
2. I believe I was able to get 100% hit rate on it, but due to upstream reasons, had trouble with repro on my machine.

I haven't had a chance to build the above pseudocode yet, I suspect this will repro pretty easily if someone gets a second to do that.

**Comment by Aaronontheweb** [comment]
@chrisalexander thanks Chris - I'll give this a stab next week and see if I can reproduce the issue. Provided that it's as straightforward as it sounds here, should be able to get it into the 1.3.9 release (which I expect we'll push in the next week or so.)

**Comment by chrisalexander** [comment]
Thanks, please let me know if you run into issues reproducing it, I will see if I can get it again

**Comment by Aaronontheweb** [comment]
I wonder if https://github.com/akkadotnet/akka.net/pull/4424 would resolve this? cc @IgorFedchenko
