### ISSUE TITLE
Update to 1.3.8 - Cluster does not work anymore

### ISSUE THREAD

**Issue by JTrotta** [akkadotnet/akka.net#3528]
After update to 1.3.8 cannot create the cluster.

- Which Akka.Net version: **1.38**
- On which platform you are using Akka.Net: **Windows & Linux**
- A list of steps to reproduce the issue:
Using 1.3.6 I was able to create a cluster with Hyperion serializer. After update to 1.3.8 (and the update of all related libraries), I got this error:
`[WARNING][26/06/2018 09:11:59][Thread 0008][[akka://ENNIOSystem/system/endpointM
anager/reliableEndpointWriter-akka.tcp%3A%2F%2FENNIOSystem%40192.168.0.30%3A3221
3-1/endpointWriter#438411329]] AssociationError [akka.tcp://ENNIOSystem@192.168.
0.103:32213] -> akka.tcp://ENNIOSystem@192.168.0.30:32213: Error [Association fa
iled with akka.tcp://ENNIOSystem@192.168.0.30:32213] []
[WARNING][26/06/2018 09:12:00][Thread 0008][remoting] Tried to associate with un
reachable remote address [akka.tcp://ENNIOSystem@192.168.0.30:32213]. Address is
 now gated for 5000 ms, all messages to this address will be delivered to dead l
etters. Reason: [Association failed with akka.tcp://ENNIOSystem@192.168.0.30:322
13] Caused by: [Akka.Remote.Transport.AkkaProtocolException: The remote system e
xplicitly disassociated (reason unknown).
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   in System.Runtime.CompilerServices.ConfiguredTaskAwaitable'1.ConfiguredTaskAw
aiter.GetResult()
   in Akka.Remote.Transport.AkkaProtocolTransport.<Associate>d__19.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'ecc
ezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   in System.Runtime.CompilerServices.ConfiguredTaskAwaitable'1.ConfiguredTaskAw
aiter.GetResult()
   in Akka.Remote.EndpointWriter.<AssociateAsync>d__23.MoveNext()]`

Obviously nothing ha been changed but akka libraries (firewall is disabled).
JJ

**Comment by Aaronontheweb** [comment]
@JTrotta could you share your HOCON configuration? The only big change in 1.3.7 or 1.3.8 that might be at the root of this is the upgrade to DotNetty v0.4.8. Are all nodes running the same version of Akka.NET?

**Comment by JTrotta** [comment]
@Aaronontheweb Hello,
of course nodes are identical. Hocon is the same I used with 1.3.6:
akka {  
	loglevel = DEBUG
	loggers =["Akka.Logger.NLog.NLogLogger, Akka.Logger.NLog"]
	actor {
	   provider = cluster
	   serializers {
		   akka-pubsub = "Akka.Cluster.Tools.PublishSubscribe.Serialization.DistributedPubSubMessageSerializer, Akka.Cluster.Tools"
		   hyperion = "Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion"
	   }
	   serialization-identifiers {
		   "Akka.Cluster.Tools.PublishSubscribe.Serialization.DistributedPubSubMessageSerializer, Akka.Cluster.Tools" = 9
	   }
	   serialization-bindings {
		   "System.Object" = hyperion
	   }
	}
	remote {
	   dot-netty.tcp {
		   port = 32213 
		   hostname = 192.168.0.103
		   public-hostname = 192.168.0.103
	   }
	}
	cluster {
	   seed-nodes = []
	}
}

**Comment by JTrotta** [comment]
Yes, I got the above errors.

**Comment by JTrotta** [comment]
Do you have any news?
May I help you in such a way?
Thank you.

**Comment by Aaronontheweb** [comment]
Not at the moment - running clusters on .NET Core and .NET Framework with v1.3.8 and I'm not running into any issues at all, so I'm inclined to think this is a configuration issue on your end possibly. I'd like to take a look at the Hyperion bits some but we haven't had any reports about that being an issue either.

**Comment by JTrotta** [comment]
Is, in your opininion, this part of Hocon correct ?:
`                                    actor {
                                       provider = cluster
		                               serializers {
			                               akka-pubsub = "Akka.Cluster.Tools.PublishSubscribe.Serialization.DistributedPubSubMessageSerializer, Akka.Cluster.Tools"
                                           hyperion = "Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion"
                                       }
		                               serialization-identifiers {
			                               "Akka.Cluster.Tools.PublishSubscribe.Serialization.DistributedPubSubMessageSerializer, Akka.Cluster.Tools" = 9
		                               }
                                       serialization-bindings {
                                           "System.Object" = hyperion
                                       }
                                    }`

**Comment by JTrotta** [comment]
Solved.
Weird problem, even though everything correct compiled and working, dotnetty now needs the library System.Runtime.CompilerServices.Unsafe, I did not copy to the remote machine.
Sorry for the waste time.
