### ISSUE TITLE
Formally deprecate / hide Akka.Persistence.TestKit package

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3533]
So this is probably my fault for doing too much work on not enough sleep, but I was pulling my hair out trying to figure out why https://www.nuget.org/packages/Akka.Persistence.TestKit/ doesn't support Akka.NET 1.3*, .NET Core, etc...

And the reason is because we cleaned up the name a while back and renamed this package to the Akka.Persistence.TCK: https://www.nuget.org/packages/Akka.Persistence.TCK

IMHO, we should push a deprecation notice up to the old package or just de-list it altogether. Just to save sleep-deprived people like me the trouble of debugging FAKE for 15 minutes before figuring it out :p

**Comment by Danthar** [comment]
de-list it

**Comment by Aaronontheweb** [comment]
@Danthar sounds good - I'll go that route then.

**Comment by Aaronontheweb** [comment]
Replaced this with a real Akka.Persistence.TestKit implementation.
