### ISSUE TITLE
Hocon Configuration

### ISSUE THREAD

**Issue by stefanobianco** [akkadotnet/akka.net#3545]
Hello,

I'm trying to merge 2 Akka config files. My purpose is to find any missing keys from the first file and add them to the second file.
I tried to use "WithFallback" method, but it preserve in the cache of the config and it doesn't save merged content in the Root.

Any ideas?

I'm using Akka.dll v4.0.30319 (.NET)

Thank you for your support

**Comment by ismaelhamed** [comment]
Something like this would work:

```csharp
 var finalConfig = ConfigurationFactory.ParseString(File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + "resource.conf"))
    .WithFallback(ConfigurationFactory.ParseString(File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + "application.conf")));
```

Note that in this case, any key in `resource.conf` will take precedence.

**Comment by sean-gilliam** [comment]
Hopefully, you've found a solution to your problem. Generally questions should be directed to our gitter chat room gitter.im/akkadotnet/akka.net.
Issues are usually reserved for actual bugs. Closing this issue.
