### ISSUE TITLE
Error joining node without ClusterClient to cluster with ClusterClient registered

### ISSUE THREAD

**Issue by Martinay** [akkadotnet/akka.net#3548]
Hello,

i'm using Akka.Cluster 1.3.8 on Windows. I was trying to connect a cluster node to an akka cluster and got the following error:
`[WARNING][7/13/2018 8:29:02 AM][Thread 0010][[akka://ActorSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FActorSystem%40127.0.0.1%3A50000-1#1559459487]] Association with remote system akka.tcp://ActorSystem@127.0.0.1:50000 has failed; address is now gated for 5000 ms. Reason is: [System.Runtime.Serialization.SerializationException: Cannot find serializer with id [9]. The most probable reason is that the configuration entry 'akka.actor.serializers' is not in sync between the two systems.
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.Serialization.WrappedPayloadSupport.PayloadFrom(Payload payload)
   at Akka.Remote.Serialization.MessageContainerSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.MessageSerializer.Deserialize(ActorSystem system, Payload messageProtocol)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, Payload message, IActorRef senderOption)
   at Akka.Remote.EndpointReader.<Reading>b__11_1(InboundPayload inbound)
 `

The existing cluster had the ClusterClient via `ClusterClientReceptionist.Get(actorSystem);` registered. I was only able to connect the second cluster node to the cluster, if I also initialized the ClusterClient on the second cluster node. In your documentation ([http://getakka.net/articles/clustering/cluster-client.html](http://getakka.net/articles/clustering/cluster-client.html)) it's said 

> The receptionist is supposed to be started on all nodes, or all nodes with specified role, in the cluster.
 
Does this means, that I don't need to initialize the cluster client on every node? 
If the cluster has registered ClusterClient do then all other nodes have to register the ClusterClient, even if they don't use it?
It seems that ClusterClient send specific messages to nodes, even if they don't take part in ClusterClient.

I created an github repo, so you can verify this [https://github.com/Martinay/AkkaClusterClientIssue](https://github.com/Martinay/AkkaClusterClientIssue)

Thank you for your support

**Comment by Aaronontheweb** [comment]
Ah, this is just a configuration issue.

You need to specify _which roles in the cluster host the `ClusterClientReceptionist`_, which you can do via `akka.cluster.client.receptionist.role` setting described here:

http://getakka.net/articles/clustering/cluster-client.html#configuration

If you do that, the `ClusterClientReceptionist` won't try to contact the other nodes that aren't attempting to host it.

**Comment by Martinay** [comment]
Thank you for The clarification
