### ISSUE TITLE
BidiFlow.AtopMat method has wrong return type

### ISSUE THREAD

**Issue by mayorovp** [akkadotnet/akka.net#3563]
version: current
platforms: all

https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Streams/Dsl/BidiFlow.cs#L281

Current signature: 
BidiFlow<..., TMat> BidiFlow<..., TMat>.AtopMat(BidiFlow<..., TMat2>, Func<TMat, TMat2, TMat3> combine)

combine's result is TMat3, but it is used as TMat

**Comment by marcpiechura** [comment]
@mayorovp good catch! Might want to fix it and send a PR?

**Comment by marcpiechura** [comment]
@mmisztal1980 yup, thanks for the reminder. 

Closed via https://github.com/akkadotnet/akka.net/pull/3595
