### ISSUE TITLE
GetOrElse NullReferenceException

### ISSUE THREAD

**Issue by zbynek001** [akkadotnet/akka.net#3564]
looks like there is possibility of `NullReferenceException` inside `GetOrElse` extension method, in case `obj` is null

https://github.com/akkadotnet/akka.net/blob/9d5bc4c4ba2884f05dbebb18500418446e753116/src/core/Akka/Util/Internal/Extensions.cs#L147

Did run into it when accessing `ClusterReadView.Self`.

Is that a bug? If so, I can prepare PR

**Comment by Aaronontheweb** [comment]
@zbynek001 yeah, looks like a bug.

**Comment by Aaronontheweb** [comment]
Should add a spec to validate that this can't happen anymore once we patch it too
