### ISSUE TITLE
Possible issue with MultiNodeTestRunner on Unix environments

### ISSUE THREAD

**Issue by Lutando** [akkadotnet/akka.net#3573]
when running this in a net452 environment this does not happen, this only seems to happen on *nix (in my case OSX)

when running:

`dotnet run --project Akka.MultiNodeTestRunner.csproj -f netcoreapp1.1 "/Users/*/Workspace/Akka/akka.net/src/core/Akka.Cluster.Tests.MultiNode/bin/Debug/netcoreapp1.1/Akka.Cluster.Tests.MultiNode.dll" -Dmultinode.enable-filesink=on`

I get:
```
Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Akka.MultiNodeTestRunner.Program.Main(String[] args) in /Users/*/Workspace/Akka/akka.net/src/core/Akka.MultiNodeTestRunner/Program.cs:line 311
```
I am not particularly sure where the issue stems from but on gitter, Aaron said it might be a file globbing issue and its not using environment agnostic `Path.Join()`'s

**Comment by Aaronontheweb** [comment]
I'm on it! Want to use this to help sniff out #3506

**Comment by Lutando** [comment]
Seems like the error was due to the filesinks not being able to write to that location. However I now have a new problem!

on windows if I do: 
```
dotnet run --project .\Akka.MultiNodeTestRunner\Akka.MultiNodeTestRunner.csproj -f netcoreapp2.1 "C:\Workspace\Akka\akka.net\src\core\Akka.Cluster.Tests.MultiNode\bin\Debug\netcoreapp2.1\Akka.Cluster.Tests.MultiNode.dll" "-Dmultinode.platform=netcore"
```
I get the following error

`A fatal error was encountered. The library 'hostpolicy.dll' required to execute
the application was not found in 'C:\Workspace\Akka\akka.net\src\core\Akka.Multi
NodeTestRunner\bin\Debug\netcoreapp2.1\'.
Failed to run as a self-contained app. If this should be a framework-dependent a
pp, add the C:\Workspace\Akka\akka.net\src\core\Akka.MultiNodeTestRunner\bin\Deb
ug\netcoreapp2.1\Akka.MultiNodeTestRunner.runtimeconfig.json file specifying the
 appropriate framework.
`

Similarly on mac if I run:

```
dotnet run --project Akka.MultiNodeTestRunner.csproj -f netcoreapp2.1 “/Users/lutando/Workspace/Akka/akka.net/src/core/Akka.Cluster.Tests.MultiNode/bin/Debug/netcoreapp2.1/Akka.Cluster.Tests.MultiNode.dll” “-Dmultinode.platform=netcore”
```

I get the error (similarly)
`A fatal error was encountered. The library ‘libhostpolicy.dylib’ required to execute the application was not found in ’/Users/lutando/Workspace/Akka/akka.net/src/core/Akka.MultiNodeTestRunner/bin/Debug/netcoreapp2.1/ . . . on so on`

Trying to get clustered tests up in Unix environment is proving a little bit tricky  for me 🤔

**Comment by Lutando** [comment]
Ok

Taking inspiration from the  [build scripts](https://github.com/akkadotnet/akka.net/blob/2ad84eefe474962aa0afe023caa6a4d11714460b/build.fsx#L306) it was more simple than I thought.

`dotnet build Akka.MultiNodeTestRunner.csproj -c Release -r osx-x64 -f netcoreapp2.1`

`dotnet Akka.MultiNodeTestRunner.dll "/Users/lutando/Workspace/Akka/akka.net/src/core/Akka.Cluster.Tests.MultiNode/bin/Debug/netcoreapp2.1/Akka.Cluster.Tests.MultiNode.dll" "-Dmultinode.platform=netcore"`

**Comment by Aaronontheweb** [comment]
So that worked? Any interest in updating our build scripts to support Linux?

**Comment by Lutando** [comment]
I can do that :)

**Comment by Aaronontheweb** [comment]
Let's keep this issue open to support that then <3

**Comment by Lutando** [comment]
So here is the idea for a solution in build.fsx

I believe we will need to change the hardcoded `win7-x64` runtime identifier that is in the build to something that is configured at build time dynamically (using isWindows or isLinux)

The problem I am having is this [getAffectedProjects.Value](https://github.com/akkadotnet/akka.net/blob/2ad84eefe474962aa0afe023caa6a4d11714460b/build.fsx#L182) is always a None option (IsNone==true). So I am wondering if this has something to do with Incramentalist, a tool I am not too sure of. digging into the build script I think that [this](https://github.com/akkadotnet/akka.net/blob/2ad84eefe474962aa0afe023caa6a4d11714460b/build.fsx#L78) is the culprit. If incrementalist is not run there wont be any projects to be built.

also I assume that this is for supporting build scripts to do `MultiNodeTestsNetCore` and `RunTestsNetCore` targets? all the nuget package stuff afterwards wouldnt make much sense right?

**Comment by Lutando** [comment]
Also is there a way to specify the library target frameworks and the test target frameworks, it looks like to get the build script adapted to both windows and *nix scenarios i would need to know which projects are libraries and which are tests and use the correct targets for them being netstandard2.0 and netcoreapp2.1 respectively.
