### ISSUE TITLE
Actorsystem not stopping

### ISSUE THREAD

**Issue by robvangeloven** [akkadotnet/akka.net#3583]
When using Akka.Net on .Net Core 2.1 Actorsystem shutdown either via Terminate or CoordinatedShutdown never completes.

Log for CoordinatedShutdown:
[DEBUG][28-Aug-18 13:08:25][Thread 0001][EventStream(TestActorSystem)] Logger log1-DefaultLogger [DefaultLogger] started
[DEBUG][28-Aug-18 13:08:25][Thread 0001][EventStream(TestActorSystem)] StandardOutLogger being removed
[DEBUG][28-Aug-18 13:08:25][Thread 0001][EventStream(TestActorSystem)] Default Loggers started
[DEBUG][28-Aug-18 13:08:33][Thread 0008][Akka.Actor.CoordinatedShutdown] Performing phase [before-service-unbind] with [0] tasks.
[DEBUG][28-Aug-18 13:08:33][Thread 0006][Akka.Actor.CoordinatedShutdown] Performing phase [service-unbind] with [0] tasks.
[DEBUG][28-Aug-18 13:08:33][Thread 0003][Akka.Actor.CoordinatedShutdown] Performing phase [service-requests-done] with [0] tasks.
[DEBUG][28-Aug-18 13:08:33][Thread 0006][Akka.Actor.CoordinatedShutdown] Performing phase [service-stop] with [0] tasks.
[DEBUG][28-Aug-18 13:08:33][Thread 0004][Akka.Actor.CoordinatedShutdown] Performing phase [before-cluster-shutdown] with [0] tasks.

Log for Terminate: 
[DEBUG][28-Aug-18 13:10:46][Thread 0001][EventStream(TestActorSystem)] Logger log1-DefaultLogger [DefaultLogger] started
[DEBUG][28-Aug-18 13:10:46][Thread 0001][EventStream(TestActorSystem)] StandardOutLogger being removed
[DEBUG][28-Aug-18 13:10:46][Thread 0001][EventStream(TestActorSystem)] Default Loggers started
[DEBUG][28-Aug-18 13:10:49][Thread 0008][ActorSystem(TestActorSystem)] System shutdown initiated

Code for this is based on the WebCrawler.CrawlService console app with the exception of not joining a cluster or creating any agents.

For reference: the CrawlService demo doesn't terminate either.

Tested with Akka 1.3.9 on Windows 10

**Comment by Aaronontheweb** [comment]
@robvangeloven so the `Task` returned by `CoordinatedShutdown` never completes? Is that what you mean?

**Comment by robvangeloven** [comment]
Hi,

Yes. The task never finishes. I was going to write a unit test for it but
time constraints mean I haven't been able to yet
