### ISSUE TITLE
Shouldn't the TotalInstances property of ClusterRouterGroupSettings limit the number of routees available?

### ISSUE THREAD

**Issue by ismaelhamed** [akkadotnet/akka.net#3584]
Given the following code:

```csharp
const int NumberOfWorkers = 10;
const string WorkersPath = "/user/supervisor/worker-*";

Enumerable.Range(1, NumberOfWorkers).ForEach(i => Context.ActorOf(Worker.Props(), $"worker-{i}"));

var router = Context.ActorOf(Props.Empty.WithRouter(new ClusterRouterGroup(
    new RoundRobinGroup(WorkersPath),
    new ClusterRouterGroupSettings(5, ImmutableHashSet.Create(WorkersPath), true))), "workers");
router.Tell(new Broadcast(AcceptingWorkers.Instance));
```
I was expecting `totalInstances` to limit the number of available workers for this router to 5, even though there are 10 workers total available. Otherwise I don't get the purpose of that property.

**Comment by Aaronontheweb** [comment]
Yes, it should limit the number of routees available.

**Comment by ismaelhamed** [comment]
@Aaronontheweb Seems like the wildcard in the `WorkersPath` above is not resolved by the router, so internally it only counts as one routee. If I change this line:
```csharp
const string WorkersPath = "/user/supervisor/worker-*";
```
 with an explicit array of paths, then it behaves correctly.

**Comment by Aaronontheweb** [comment]
I see - in this case the router is working as expected. One routee == 1 route in this case. If that route includes a wildcard, which can select multiple destination actors, then that's up to the user. The router doesn't resolve the `ActorSelection` - it just creates messages to it and sends it.
