### ISSUE TITLE
Is a Dynamic-Referee-Split Brain Resolver viable?

### ISSUE THREAD

**Issue by Haukinger** [akkadotnet/akka.net#3610]
I desire a split brain resolver that will always shut down all clusters but one in case of a network partition (like `KeepReferee`) , but does not depend on the presence of a single node (like `KeepOldest`). And I'd prefer to have your input before I start coding and come across an insurmountable problem later on.

My idea is to have a referee that is moved to another node if the current referee node leaves the cluster gracefully. In my (perhapse naiive) thinking, that should be fail-safe, because:

- as long as the referee is alive, it works like the existing `KeepReferee`
- if the referee dies, everything will go down
- if a network partition occurs while the referee leaves, either the old referee is still usable or all nodes go down

One has to make sure, though, that all nodes in the cluster acknowledge the referee-change.

What do you guys think? Can this work? How would you do the "all-nodes-acknowledge-this"-part?

**Comment by Aaronontheweb** [comment]
So you're just looking for a way to figure out how to move the referee around... But the hitch is, the referee MUST LEAVE THE CLUSTER CLEANLY or the entire cluster goes offline?

**Comment by Haukinger** [comment]
I think, the whole cluster going down is less of a problem for me than the cluster doing the wrong thing undetected (splitting into two independent clusters). I can always fall back to local processing while rebooting a new cluster, but I want a cluster that I can trust that it's the only cluster.

**Comment by Aaronontheweb** [comment]
> the whole cluster going down is less of a problem for me than the cluster doing the wrong thing undetected 

just use keep majority then. The minority side of the split brain will down itself automatically. 

https://github.com/akkadotnet/akka.net/blob/83b13f00fbc2b31a7b60163e2318fd997ebb72db/src/core/Akka.Cluster/SplitBrainResolver.cs#L130-L144

**Comment by Aaronontheweb** [comment]
Worth bearing in mind, when you look at the split brain resolver code: if there are two partitions, there are two leaders. Both leaders run this code. If the leader on the "losing" side of the partition determines that it's on the loser, it downs itself and everyone on the same side as it.

Hence why it's a split brain resolver - preserves the winning partition and kills the loser. All of them do this. Does that help?

**Comment by Haukinger** [comment]
This certainly helps, but I'm unsure because of this in the docs:

> 1.Two parts of the cluster may make their decision based on the different state of the cluster, as it's relative for each node. In practice, the risk of it is quite small.

To me that reads: _two different parts of the cluster may both think they are the larger part and both stay alive_.

The referee avoids this risk but adds dependency on a single node. If we could reliably move the referee, we can have both (no risk of not downing a partition that should be downed  and not being dependent on one node).

**Comment by Horusiath** [comment]
@Haukinger equally probable scenario could be that given cluster of 10 nodes, you'll hit with network split 2/8 while the referee is on the smaller part. In that case you'll arbitrarily kill most of the cluster (and in result probably the entire cluster will go down as well, since remaining 2 nodes will now have to serve requests, that were split onto 10 nodes so far).
