### ISSUE TITLE
Rewrite MultiNodeTestRunner as .NET Core tool

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3615]
Having done this recently for NBench: https://github.com/petabridge/NBench/pull/240/ 

I think that it'd be an end-user experience improvement to leverage .NET Core's built-in tooling for the MNTR. We can go down the global tool route or use a downloadable package. But what I like about this idea is that it makes it possible for us to target the `.csproj` file used for the multi-node project rather than the output assemblies. This will help simplify build scripts significantly and in particular will make projects that need to support multi-targeting, like Akka.NET itself, easier to work with.

**Comment by igormcoelho** [comment]
Perhaps related to: https://github.com/akkadotnet/akka.net/issues/3696

**Comment by IgorFedchenko** [comment]
@Aaronontheweb So something like this?
```
<ItemGroup>
  <DotNetCliToolReference Include="dotnet-mntr" />
</ItemGroup>
```

**Comment by Aaronontheweb** [comment]
Yeah I'd either do it via:

1. The way you suggested;
2. Writing a Visual Studio plugin so `dotnet test` and the VS Test Runner can pick up MNTR specifications and we can attach a debugger to them. You can see some examples of how to do this here: https://github.com/microsoft/VSSDK-Extensibility-Samples

**Comment by Aaronontheweb** [comment]
I've had a lot of issues getting `dotnet nbench` to perform consistently well across multiple versions of .NET Core - ultimately ran into the same kinds of problems the xUnit project did with `dotnet xunit` - that's why they deprecated it after xUnit 2.3.1 and change their guidance to recommend that all developers start using `dotnet test` instead - that was Visual Studio becomes responsible for finding all of the right framework / runtime binaries instead of your program.

**Comment by IgorFedchenko** [comment]
@Aaronontheweb So seems like we have so things to implement here:
1. Rewrite MNTR to include custom test runner supported by `dotnet test`, so that running `dotnet test` after installing our nuget packages (like `xunit` and `xunit.runner.visualstudio`) would run MNTR tests for given project.
This does not seem to be related to Visual Studio, since it is just using `dotnet test` command with custom test runner (as described [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21#description))

2. Write VS extension that will detect MNTR specifications. Speaking of that, JetBrains Rider already suggests me to run MNTR spec:
![image](https://user-images.githubusercontent.com/9683660/73286886-654e7180-4209-11ea-9f5c-e20b5c3f05c1.png)
I guess it will try to run dotnet test with this spec as a parameter, so maybe after implementing custom test runner this point will start working out of the box (not sure about debugger, will see how this works).

**Comment by Aaronontheweb** [comment]
@IgorFedchenko oh nice, we only need an `MNTR.TestRunner` project or some such to plugin to `dotnet test`? Not a full blown Visual Studio plugin?

**Comment by IgorFedchenko** [comment]
@Aaronontheweb I hope so. At least, since we having out runner based on xunit specs discovery, and VS seem to have auto-detection of those, there is a good chance that making `dotnet test` run multi-node tests will be all we need.

But there is still a question about debugging code on individual nodes (since we are running same specs in separate processes), also this is possible that VS has some built-in "plugin" to support xunit test runner (while it is still required as a package reference), and maybe it will not work out of the box with another test runner.

At least, there is a change that all will be simpler then it could be. I will start with `dotnet test` MNTR support anyway, since we need to be able to start mntr from cli - and then it will be clear what should be done to add full support of this in VS.

**Comment by Aaronontheweb** [comment]
I'd say we get `dotnet test` working first - that'd allow us to do things like close out #3696 for instance.

Once that's working, a VS plugin would be a good bonus.

**Comment by IgorFedchenko** [comment]
Here is xunit repo we may use as a sample of creating test runner, that is used by xunit to work with VS: https://github.com/xunit/visualstudio.xunit

This is common setup to have xunit tests up and running:
```
<ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdkVersion)" />
    <PackageReference Include="xunit" Version="$(XunitVersion)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="$(XunitVersion)" />
</ItemGroup>
```
That [`xunit.runner.visualstudio` package](https://www.nuget.org/packages/xunit.runner.visualstudio/2.4.1) is built from repo I mentioned above and does not seem to have dependencies on packages other then `Microsoft.NET.Test.Sdk` - which gives a hope that all we need is to use same approach as in this standalone repo to update MNTR. 
Having this `akka.multinode.runner.visualstudio` package implemented, we should have `dotnet test` working, and hopefully VS intergration as well.

**Comment by IgorFedchenko** [comment]
Here is also NUnit runner (just as a backup sample): https://github.com/nunit/nunit3-vs-adapter

**Comment by IgorFedchenko** [comment]
> That `xunit.runner.visualstudio` package is built from repo I mentioned above and does not seem to have dependencies on packages other then Microsoft.NET.Test.Sdk

That's not true - nuget.org does not display this, but `xunit.runner.visualstudio` has references like:
```
<ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.0.28" PrivateAssets="all" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
    <PackageReference Include="xunit.runner.reporters" Version="$(XunitVersion)" PrivateAssets="All" />
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="16.4.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Label="Package">
    <None Include="build\xunit.runner.visualstudio.desktop.props" PackagePath="build\net452\xunit.runner.visualstudio.props" Pack="true" />
    <None Include="$(NuGetPackageRoot)xunit.runner.reporters\$(XunitVersion)\lib\net452\*.dll" PackagePath="build\net452" Pack="true" Visible="false" />
    <None Include="$(NuGetPackageRoot)xunit.runner.utility\$(XunitVersion)\lib\net452\*.dll" PackagePath="build\net452" Pack="true" Visible="false" />
    <None Include="$(NuGetPackageRoot)xunit.abstractions\2.0.3\lib\netstandard1.0\*.dll" PackagePath="build\net452" Pack="true" Visible="false" />

    <None Include="build\xunit.runner.visualstudio.dotnetcore.props" PackagePath="build\netcoreapp2.1\xunit.runner.visualstudio.props" Pack="true" />
    <None Include="$(NuGetPackageRoot)xunit.runner.reporters\$(XunitVersion)\lib\netcoreapp1.0\*.dll" PackagePath="build\netcoreapp2.1" Pack="true" Visible="false" />
    <None Include="$(NuGetPackageRoot)xunit.runner.utility\$(XunitVersion)\lib\netcoreapp1.0\*.dll" PackagePath="build\netcoreapp2.1" Pack="true" Visible="false" />
    <None Include="$(NuGetPackageRoot)xunit.abstractions\2.0.3\lib\netstandard2.0\*.dll" PackagePath="build\netcoreapp2.1" Pack="true" Visible="false" />

    <None Include="build\xunit.runner.visualstudio.uwp.props" PackagePath="build\uap10.0.16299\xunit.runner.visualstudio.props" Pack="true" />
    <None Include="build\xunit.runner.visualstudio.uwp.targets" PackagePath="build\uap10.0.16299\xunit.runner.visualstudio.targets" Pack="true" />
    <None Include="$(NuGetPackageRoot)xunit.runner.reporters\$(XunitVersion)\lib\netstandard1.5\*.dll" PackagePath="build\uap10.0.16299" Pack="true" Visible="false" />
    <None Include="$(NuGetPackageRoot)xunit.runner.utility\$(XunitVersion)\lib\netstandard1.5\*.dll" PackagePath="build\uap10.0.16299" Pack="true" Visible="false" />
    <None Include="$(NuGetPackageRoot)xunit.runner.utility\$(XunitVersion)\lib\uap10.0\*.dll" PackagePath="build\uap10.0.16299" Pack="true" Visible="false" />
    <None Include="$(NuGetPackageRoot)xunit.runner.utility\$(XunitVersion)\lib\uap10.0\*.pri" PackagePath="build\uap10.0.16299" Pack="true" Visible="false" />
  </ItemGroup>
```

So lots of versions for different frameworks are referenced - and most likely we will need our implementation for this `xunit.runner.*` package family.

Will see if we could simplify this, at least for starting.

**Comment by IgorFedchenko** [comment]
Also some really helpful info and links here: https://stackoverflow.com/questions/38100057/how-to-create-and-install-test-adapter-in-visual-studio

**Comment by Aaronontheweb** [comment]
Sounds like it may not be so straight forward after all....

**Comment by IgorFedchenko** [comment]
Indeed.
But since our test runner is going to be based on XUnit's one (since we inherit their attributes and can almost fully reuse their files/tests discovery), I hope that it will be simpler then implementing runner from scratch.

**Comment by IgorFedchenko** [comment]
@Aaronontheweb Maybe we should update issue title to reflect the fact that instead of packing MNTR as a .net global tool or dotnet cli custom command we are implementing custom test adapter (see [attached PR](https://github.com/akkadotnet/akka.net/pull/4177) description)?

**Comment by IgorFedchenko** [comment]
Closing since MNTR moved to separate repository. Ported issue: https://github.com/akkadotnet/Akka.MultiNodeTestRunner/issues/7
