### ISSUE TITLE
HOCON substitution from environment variables

### ISSUE THREAD

**Issue by kaffepanna** [akkadotnet/akka.net#3617]
Are there any plans on supporting environment-variable substitution in Akka.Config and also the conditional substitution syntax `${?` For example:

```
akka {
    actor.provider = cluster
    remote {
        dot-netty.tcp {
            port = 20200
            hostname = localhost
            hostname = ${?SERVICE_NAME}
        }
    }
}
```

**Comment by boekabart** [comment]
I think the plans described in #3050 would implement that (by allowing you to use Hocon as *a*, not *the* source of all truth.)

**Comment by Aaronontheweb** [comment]
This is already implemented as part of the stand-alone HOCON library, which will be integrated into Akka.NET in v1.4.0
