### ISSUE TITLE
StreamRef subscription time out does not get canceled after handshake

### ISSUE THREAD

**Issue by NielsHoogeveen** [akkadotnet/akka.net#3621]
In Akka 1.4 beta 4, when using stream refs, the stream receives a timeout after as much time as is defined in  stream.materializer.stream-ref.subscription-timeout. The OnSubscribeHandshake message is never received and as a result the CancelTimer(SubscriptionTimeoutKey) call (line 630 of Akka.Streams/Dsl/StreamRefs.cs) is never made. As a result the stream can only last as long as the subscription timeout.

**Comment by NielsHoogeveen** [comment]
Is there anything I can do, to make this a confirmed bug?

**Comment by Horusiath** [comment]
Sorry @NielsHoogeveen , I'll pick up this issue as soon as I'll got a second of spare time.

**Comment by sean-gilliam** [comment]
Closed via #3649
