### ISSUE TITLE
Akka.Actor: Inconsistent application of SupervisorStrategy on Pool routers

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3626]
Version: 1.3.9

Splitting up the bug that was reported here from its original issue: https://github.com/akkadotnet/akka.net/issues/3597#issuecomment-426872642

> Thanks for looking into this @Aaronontheweb
> 
> I just observed one more weird behavior. Not sure if this would be any help.
> 
> With one small change while creating the router, Directive.Resume is working for me. But Directive.Escalate still does not work
> 
> If I create the router with this code, router is killed without any issue after broadcasting Poisonpill.
> 
> ```
> _childRouter = Context.ActorOf(
>                              Props.Create(() => new ChildActor())
>                             .WithRouter(new RoundRobinPool(100).WithSupervisorStrategy(new OneForOneStrategy(0, 0, ex => Directive.Resume)))
>                             ,"ChildRouter");
> ```
> But this one does not work :
> 
> ```
> _childRouter = Context.ActorOf(
>                             Props.Create(() => new ChildActor())
>                             .WithRouter(new RoundRobinPool(100))
>                             .WithSupervisorStrategy(new OneForOneStrategy(0, 0, ex => Directive.Resume))
>                             ,"ChildRouter");
> ```
> Difference between these two is only where I define the supervisor strategy.

**Comment by Arkatufus** [comment]
The `RoundRobinPool` with `Directive.Escalate` bug where it fails to supervise routee with exceptions are fixed in #4393, closing this issue.
