### ISSUE TITLE
Akka.Remote: No Support for Using Installed Certificate with Thumbprint

### ISSUE THREAD

**Issue by to11mtm** [akkadotnet/akka.net#3632]
The Dotnetty Transport currently only supports using certificates specified by file and password. Being able to use an installed certificate specified by Thumprint allows deployments in scenarios where an organization does not wish to have these files/passwords visible.

I've created a [pull request](https://github.com/akkadotnet/akka.net/pull/3629) that adds this capability.

**Comment by Aaronontheweb** [comment]
closed via #3629
