### ISSUE TITLE
routee node can‘t receive all message

### ISSUE THREAD

**Issue by heyixiaoran** [akkadotnet/akka.net#3640]
- Akka.Net 1.3.9
- netcoreapp2.1
- repo ：https://github.com/heyixiaoran/AkkaTest

I set a seed node (Server1) and two client node (Client1 and Client2). Then send a message from Client1 to Client2. But now Client2 only can receive dual messages （2，4，6)

The routee node count is 2. Why is not 1? 
 If i set nr-of-members =1 .Client2 can not receive any messages.

![image](https://user-images.githubusercontent.com/5743795/47975864-ba750380-e0ea-11e8-8be1-cb60f8a524c2.png)

**Comment by Aaronontheweb** [comment]
Duplicate of https://github.com/akkadotnet/akka.net/issues/3506

Workaround for the time being is to downgrade off of .NET Core 2.1 until we can get DotNetty patched. Being actively worked on right now.

**Comment by heyixiaoran** [comment]
@Aaronontheweb  I think it's my conf  error.   Probably the other messages received by the other routee actor. But I don't know how to config to make it work well.

**Comment by heyixiaoran** [comment]
Sorry. I forgot to set role
