### ISSUE TITLE
Akka .NET tcp port issue

### ISSUE THREAD

**Issue by IrvinDominin** [akkadotnet/akka.net#3645]
In our cluster we have five nodes composite of:
- 2 seed nodes (backend)
- 1 worker
- 2 webapi on IIS

I'm using Akka.Persistence.SQL with AtLeastOnceDelivery.

The cluster is joined, up and running; but often I see this in my worker console:
![image](https://user-images.githubusercontent.com/1533624/48300134-4d8daf00-e4d8-11e8-8eb6-a4b037ff35f3.png)

This point me out to the IIS ip.

Here is my IIS config:

```
<hocon>
  <![CDATA[
        akka.loglevel = INFO
        akka.log-config-on-start = off
        akka.stdout-loglevel = INFO
        akka.actor {
            provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"
            deployment {
              /Process {
                router = round-robin-group
                routees.paths = ["/user/Process"] # path of routee on each node
                # nr-of-instances = 3 # max number of total routees
                cluster {
                    enabled = on
                    allow-local-routees = off
                    use-role = Process
                }
              }
            }
            debug {
              receive = on
              autoreceive = on
              lifecycle = on
              event-stream = on
              unhandled = on
            }
        }
        akka.remote {
            helios.tcp {
                # transport-class = "Akka.Remote.Transport.Helios.HeliosTcpTransport, Akka.Remote"
                # applied-adapters = []
                # transport-protocol = tcp
                port = 0
                hostname = 172.16.1.8
            }
            log-remote-lifecyclo-events = DEBUG
        }
        akka.cluster {
          seed-nodes = [
            "akka.tcp://ClusterActorSystem@172.16.1.8:2551",
            "akka.tcp://ClusterActorSystem@172.16.1.8:2552"
          ]
          roles = [Send]
          auto-down-unreachable-after = 10s
          # how often should the node send out gossip information?
          gossip-interval = 1s
          # discard incoming gossip messages if not handled within this duration
          gossip-time-to-live = 2s
        }
        # http://getakka.net/docs/persistence/at-least-once-delivery
        akka.persistence.at-least-once-delivery.redeliver-interval = 300s
        # akka.persistence.at-least-once-delivery.redelivery-burst-limit =
        # akka.persistence.at-least-once-delivery.warn-after-number-of-unconfirmed-attempts =
        akka.persistence.at-least-once-delivery.max-unconfirmed-messages = 1000000
        akka.persistence.journal.plugin = "akka.persistence.journal.sql-server"
        akka.persistence.journal.publish-plugin-commands = on
        akka.persistence.journal.sql-server {
            class = "Akka.Persistence.SqlServer.Journal.SqlServerJournal, Akka.Persistence.SqlServer"
            plugin-dispatcher = "akka.actor.default-dispatcher"
            table-name = EventJournal
            schema-name = dbo
            auto-initialize = on
            connection-string-name = "HubAkkaPersistence"
            refresh-interval = 1s
            connection-timeout = 30s
            timestamp-provider = "Akka.Persistence.Sql.Common.Journal.DefaultTimestampProvider, Akka.Persistence.Sql.Common"
            metadata-table-name = Metadata
        }
        akka.persistence.snapshot-store.plugin = ""akka.persistence.snapshot-store.sql-server""
        akka.persistence.snapshot-store.sql-server {
          class = "Akka.Persistence.SqlServer.Snapshot.SqlServerSnapshotStore, Akka.Persistence.SqlServer"
          plugin-dispatcher = ""akka.actor.default-dispatcher""
          connection-string-name = "HubAkkaPersistence"
          schema-name = dbo
          table-name = SnapshotStore
          auto-initialize = on
        }
  ]]>
</hocon>
```
inside the global.asax we create a new router to the cluster:

    ClusterActorSystem = ActorSystem.Create("ClusterActorSystem");

    var backendRouter =
        ClusterActorSystem.ActorOf(
            Props.Empty.WithRouter(FromConfig.Instance), "Process");

    Send = ClusterActorSystem.ActorOf(
        Props.Create(() => new Common.Actors.Send(backendRouter)),
        "Send");

in the Application_End I have this code commented:

            //ClusterActorSystem.ActorSystem.Shutdown();

            ////wait up to two seconds for a clean shutdown
            //ClusterActorSystem.ActorSystem.AwaitTermination(TimeSpan.FromSeconds(2));

            //ClusterActorSystem.Terminate();

I rememebr that if I activate this code the cluster break when IIS goes down...what do I have to do?

**Comment by Aaronontheweb** [comment]
Is this issue happening only when a node restarts?

**Comment by IrvinDominin** [comment]
@Aaronontheweb  I have to check it asap; I add two more informations, sometimes I see a huge number of members like:
![image](https://user-images.githubusercontent.com/1533624/51075257-6b6ac200-1689-11e9-9342-988c287d081f.png)

but they are 9...

And if i stop a backend service and start it again it isn't joining the cluster, i close it in this way when you close my console app with Topshelf:
```
        public async void Stop()
        {
            //this is where you stop your actor system
            if (this.ClusterActorSystem != null)
                await this.ClusterActorSystem.Terminate();
        }
```

is it wrong? I can't understand why it isn't joining the cluster again

**Comment by Aaronontheweb** [comment]
If the node gets stuck in a joining state, might be because:

1. The node starts on a different address each time - this will definitely happen if you are bound to port zero - and the previous incarnation of that node didn't leave the cluster cleanly. Run await CoordinatedShutdown.Run instead of ActorSystem.Terminate to fix that.
2. The port is already in use from a previous instance, in which case Akka.Remote will scream loudly and fail (correct behavior.) 
3. Someone else in the cluster is unreachable - turn on "allow weakly up members" in your clustering settings to bypass this.

**Comment by IrvinDominin** [comment]
Ok, on non seed node I use 0 port, I see that the Coordinated shutdown is fired automatically: https://getakka.net/articles/actors/coordinated-shutdown.html#invoking-coordinatedshutdownrun-on-process-exit

Can you pleaes guide me in the correct way? Also what is the correct way on the IIS setup?

**Comment by Aaronontheweb** [comment]
CoordinatedShutdown on process exit can get intercepted inside Topshelf - need to run it manually inside the service stop method and let the Task it returns complete all the way.

**Comment by Aaronontheweb** [comment]
Same deal inside global.asax - need to block exit until CoordinatedShutdown runs to completion.

I'd also enable weakly up members too - it's a HOCON setting and it needs to be enabled on all members. It will help.

**Comment by IrvinDominin** [comment]
So with the code in the starting issue I'm destroying the whole actorsystem 🤯 rigth? I'll work on this asap and on the hokon config

**Comment by Aaronontheweb** [comment]
Correct - CoordinatedShutdown will destroy the ActorSystem

**Comment by IrvinDominin** [comment]
Ok, but with CoordinatedShutdown the node leaves the cluster in a clean way, and it stili works and can reenter rigth? With terminate it's completely destroyed and must be restarted?

**Comment by IrvinDominin** [comment]
Currently when I deploy (front-end or worker) I restart the whole system, can the inconsistence be cause of the not clean shutdown?

**Comment by IrvinDominin** [comment]
Currently when I deploy (front-end or worker) I restart the whole system, can the inconsistence be cause of the not clean shutdown?
