### ISSUE TITLE
InvalidAssociationException is lost in the task pipe line

### ISSUE THREAD

**Issue by peirens-bart** [akkadotnet/akka.net#3646]
Akka version: 1.3.10
Akka.Remote: 1.3.10
.Net frm : 4.6.1
App type: wpf 

I'm trying to use akka for updating a wpf application that is using prism.
```
try
                    {
                        Context.ActorSelection(depotzoneSelectionName)
                        .Ask<SystemDepotZoneInformationResponse>(new SystemDepotZoneInformationRequest(depotzone.Key))
                        .PipeTo(Self, Self
                            , success: response =>
                             {
                                 SystemDepotZoneInformationResponseWrapper wrapper = new SystemDepotZoneInformationResponseWrapper(null, 0, null);
                                 if (response is SystemDepotZoneInformationResponse)
                                 {
                                     wrapper = new SystemDepotZoneInformationResponseWrapper(response, depotzone.Key, depotzone.Value);
                                 }
                                 else
                                 {
                                     _eventAggregator.GetEvent<AddWarningCommand>().Publish($"did not get correct answer from depotzone {depotzone.Value}");
                                 }
                                 return wrapper;
                             }
                            , failure: exception =>
                             {
                                 return new Status.Failure(exception);
                             }
                        );
                    }
                    catch (AggregateException aggrEx)
                    {
                        _eventAggregator.GetEvent<AddWarningCommand>().Publish(aggrEx.GetBaseException().Message);
                        break;
                    }
                    catch (Exception ex)
                    {
                        _eventAggregator.GetEvent<AddWarningCommand>().Publish(ex.Message);
                        break;
                    }

```
I never get into any exception, wath is something expected since task is none blocking, but I expect to go in failure of the pipeto if there is no actor on the other side of the selction.
in the output window i see 

> [WARNING][12/11/2018 13:31:02][Thread 0012][[akka://wmsinsightc0a339c4ee974e4d92b56771988c5fce/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FWmsDepot%400.0.0.0%3A8910-1/endpointWriter#1858159558]] AssociationError [akka.tcp://wmsinsightc0a339c4ee974e4d92b56771988c5fce@0.0.0.0:59246] -> akka.tcp://WmsDepot@0.0.0.0:8910: Error [Association failed with akka.tcp://WmsDepot@0.0.0.0:8910] []
[WARNING][12/11/2018 13:31:02][Thread 0013][remoting] Tried to associate with unreachable remote address [akka.tcp://WmsDepot@0.0.0.0:8910]. Address is now gated for 5000 ms, all messages to this address will be delivered to dead letters. Reason: [Association failed with akka.tcp://WmsDepot@0.0.0.0:8910] Caused by: [System.AggregateException: Er zijn één of meer fouten opgetreden. ---> Akka.Remote.Transport.InvalidAssociationException: Kan geen verbinding maken omdat de doelcomputer de verbinding actief heeft geweigerd tcp://WmsDepot@0.0.0.0:8910
   bij Akka.Remote.Transport.DotNetty.TcpTransport.<AssociateInternal>d__1.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Akka.Remote.Transport.DotNetty.DotNettyTransport.<Associate>d__22.MoveNext()
   --- Einde van intern uitzonderingsstackpad ---
   bij System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bij System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bij System.Threading.Tasks.Task`1.get_Result()
   bij Akka.Remote.Transport.ProtocolStateActor.<>c.<InitializeFSM>b__11_54(Task`1 result)
   bij System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   bij System.Threading.Tasks.Task.Execute()
---> (Interne uitzondering #0) Akka.Remote.Transport.InvalidAssociationException: Kan geen verbinding maken omdat de doelcomputer de verbinding actief heeft geweigerd tcp://WmsDepot@0.0.0.0:8910
   bij Akka.Remote.Transport.DotNetty.TcpTransport.<AssociateInternal>d__1.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Akka.Remote.Transport.DotNetty.DotNettyTransport.<Associate>d__22.MoveNext()<---
]

do I handle this type of exception incorrect or is thtis exception lost in threading?
Maybe this is related to #3250

**Comment by Arkatufus** [comment]
`Context.ActorSelection().Ask<T>()` will not throw any exceptions when no actors are found, instead, it will send the failed message into `DeadLetter`.
If you want to catch non-existing actor selection, maybe you should use `Context.ActorSelection().ResolveOne()` instead?

**Comment by Arkatufus** [comment]
There are several problems:
1. In the sample code, `Ask<T>()` isn't awaited.
2. `Context.ActorSelection().Ask<T>()` does not throw an exception when no actors are found, instead, it will send the message to `DeadLetter` instead.
3. Maybe the sample code should've used `ActorSelection.ResolveOne()` instead if you want to catch a missing/non-existent actor selection?

**Comment by peirens-bart** [comment]
@Arkatufus Ask isn't awaited on purpose because i want to have a real async call in my WPF application and I don't always knonw if i come from the UI thread or not. I'm using prism event aggregator to send an event back the viewmodel once the call is finished so the UI can be updated.

in case 3 the issue can still occure if the remote actor (what the actor is) is gone between the resolving and the ask. 
I still would think i need to get an exception, if I do an ask in give a the ask a timeout i receive a timeout exception (https://getakka.net/api/Akka.Actor.AskTimeoutException.html). So why is this not the case if there is no assosiation possible, it's in the logging so the problem is known?
If my understanding is correct, an ask will create a temporary actor that will do a tell and wait on a tell to come back. if that actor knows it can't find the remote actor it could send a failure (https://getakka.net/api/Akka.Actor.Failure.html) back with the Akka.Remote.Transport.InvalidAssociationException as teh exception and then i can go into the failure step and hanlde the problem.

I fixed it now to create my own temp actor who gets the event aggregator in his ctor and then do a tell and wait for a tell to come back, or a cancable schedular so i known the answer will not come.

**Comment by Arkatufus** [comment]
There is a difference because a timeout exception happens locally, while an invalid association can happen remotely and we don't know where and how the invalid association will happen.

If you have found a workaround that works with your need, can we close this issue?

**Comment by peirens-bart** [comment]
So what you are saying is that if you do an ask to a remote actor and that remote system is not running, you just have bad luck and you never known? mayby the title is then 

> InvalidAssociationException are not thrown.

For me it's ok to close the ticket, my app is working at the momment.
