### ISSUE TITLE
shard send message error 

### ISSUE THREAD

**Issue by heyixiaoran** [akkadotnet/akka.net#3650]
I'm a newer and my english is not good. So some docs can not understand very clear.
Now I try to use shard to send message from sender to receiver. But some error happened. I don't know how to do. Please help me to use shard. tks.

question:
Why seed-node must be one ? before I set three.  error. 

repo: https://github.com/heyixiaoran/AkkaTest.git   . test2 branch

sender: 
![1](https://user-images.githubusercontent.com/5743795/48541267-3d6e3900-e8f7-11e8-9ff6-833afb7eba97.png)

receiver:
![2](https://user-images.githubusercontent.com/5743795/48541281-45c67400-e8f7-11e8-9139-4f70d4c23890.png)

**Comment by Horusiath** [comment]
@heyixiaoran from the error message (*Cannot find serializer with id [9]...*) it looks like one of your nodes has DistributedPubSub initialized (it's serializer ID is 9), while other has not.

**Comment by heyixiaoran** [comment]
@Horusiath the  serializer part in config are both same. How to make it correct?

**Comment by Horusiath** [comment]
`DistributedPubSub` extends config with its own serializer when the plugin is initialized. This means, that somewhere in your code you have called `DistributedPubSub.Get` on one node but not on the other. If I remember correctly, `DistributedPubSub` is also a transitive dependency for ClusterClient plugin: so if you don't use `DistributedPubSub` directly but you use cluster client, the same rule applies for cluster client.

**Comment by heyixiaoran** [comment]
as Aaronontheweb reply

 you'll want to add this to your HOCON configuration at the time you create your ActorSystem:
`
var actorSystem = ActorSystem.Create("clusterNodes", config
                .WithFallback(ClusterClientReceptionist.DefaultConfig())
                .WithFallback(DistributedPubSub.DefaultConfig()));
`

serializer 9 is DistributedPubSub
