### ISSUE TITLE
Enhancement: add ability to retrieve subscriber / topic stats from DistributedPubSubMediator

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3663]
I'm thinking it'd be nice to add a metadata querying capability similar to what we have for Cluster.Sharding https://petabridge.com/blog/cluster-sharding-technical-overview-akkadotnet/#getting-shard-metadata for DistributedPubSub. 

I'd like the ability to query:

* All topics and the total number of subscribers on the current node for each - can currently get the topics by sending the mediator a message.
* List of all groups for a given topic on the current node and the number of subscribers in each group.
* The list of all nodes PubSub-ing.
* The ability to scatter-gather any of the above commands to the other mediators and gather responses back from all nodes.

My reasons for wanting these features:
1. Monitoring, whether via hand-rolled actors or perhaps via a [Petabridge.Cmd module](https://cmd.petabridge.com/articles/commands/index.html)
2. Run-time debugging - I can imagine some scenarios where I might to dump the state of the mediator to see if someone is / is not subscribed to something they should or should not be.

Bad (IMHO) reasons for wanting to have this feature:

1. Runtime flow-control - people should not be performing a request->response query against the subscriber list to check for subscribers every time they want to publish. That would be a no-no and would significantly limit the benefits of having a topic broker to begin with.

Are there any other bad reasons or objections to adding something like this?

**Comment by Zetanova** [comment]
Yes, they feature to query the state of the `DistributedPubSubMediator`  is missing. 

one addition to it would be great:
* Add an option to the settings to suppress DeathLetter messaging

Reasons:
* An instance of an `DistributedPubSubMediator` can be create inside a service and used to publish events or send commands to-all-but-not-self without the need to know, if there are any subscribers or listeners registered.

**Comment by ismaelhamed** [comment]
@Zetanova I've been willing to find some time to port [#23615](https://github.com/akka/akka/pull/23615)

**Comment by Zetanova** [comment]
@Aaronontheweb Your post is from 2018. 

Instead of providing new monitoring pull-commands 
would it be better to use/send the PubSub-StatusInfos to Akka.Metrics?

I didn't got time to take a look into the new Akka.Metrics.
