### ISSUE TITLE
'akka.actor.provider' is not a valid type name : 'Akka.Cluster.ClusterActorRefProvider, Akka.Cluster'

### ISSUE THREAD

**Issue by senzacionale** [akkadotnet/akka.net#3669]
I am using latest version of Akka.net and try to use cluste with hocon

My config file:

```
akka {	

	stdout-loglevel = DEBUG
    loglevel = DEBUG
	loggers=["Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog"]
    log-config-on-start = on  

	actor {
		provider = "cluster"
	}
						
	remote {
		dot-netty.tcp {
				hostname = "127.0.0.1"
				port = 8081
				maximum-frame-size = 256000b
			}
	}			

	cluster {
		seed-nodes = ["akka.tcp://tradex@127.0.0.1:4053"] # address of seed node
		roles = ["ordersync", "logger"] # roles this member is in
		role.["ordersync"].min-nr-of-members = 3 # crawler role minimum node count

		# auto downing is NOT safe for production deployments.
		# you may want to use it during development, read more about it in the docs.
		#
		# auto-down-unreachable-after = 10s
	}
}
```

but I am always receiving this error

> Akka.Configuration.ConfigurationException
>   HResult=0x80131500
>   Message='akka.actor.provider' is not a valid type name : 'Akka.Cluster.ClusterActorRefProvider, Akka.Cluster'
>   Source=Akka
>   StackTrace:
>    at Akka.Actor.Settings..ctor(ActorSystem system, Config config)
>    at Akka.Actor.Internal.ActorSystemImpl..ctor(String name, Config config)
>    at Akka.Actor.ActorSystem.Create(String name, Config config)

I found this code:
https://www.codefactor.io/repository/github/akkadotnet/akka.net/source/dev/src/core/Akka/Actor/Settings.cs

Looks like cluster is supported but why this message then?

**Comment by senzacionale** [comment]
Missing DLL in the project

**Comment by vaibhav-kla** [comment]
Install akka.net cluster package

**Comment by senzacionale** [comment]
Hahaha you need 3 years to respond :) Deprecated in the meanwhile
