### ISSUE TITLE
SqlReadJournal.EventsByPersistenceId does not stream new PersistenceId

### ISSUE THREAD

**Issue by angrybug** [akkadotnet/akka.net#3685]
Akka.Net 1.3.11
All platform

SqlReadJournal.EventsByPersistenceId doesn't return new persistence IDs

See https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs#L137

Doesn't look like persistenceIds gets populated with anything.

Just wanted to make a note of it - I might get around to fixing it later.

**Comment by Horusiath** [comment]
@angrybug `EventsByPersistenceId` only give you PIDs known to the current moment. If you want to have continuous stream of all PIDs (both existing and newly created ones), use `AllEventsByPersistenceId`.

**Comment by angrybug** [comment]
I did a search for AllEventsByPersistenceId in the source code - doesn't exist.

Do you mean the difference between: EventsByPersistenceId and CurrentEventsByPersistenceId

**Comment by Horusiath** [comment]
Yes, you're right @angrybug . My mistake. This may be a sign of a bug in our code.

**Comment by angrybug** [comment]
False alarm.  Was trying to work out how the unit tests are passing.

It looks to be deliberate behaviour.  Just had another look at this. It turns out EventsByPersistenceIdPublisher uses a timer to trigger the new events to be published.  https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/persistence/Akka.Persistence.Query.Sql/EventsByPersistenceIdPublisher.cs#L147

The HashSet at SqlJournal.cs Line 137 seems unnecessary, so I guess the only thing needs doing is probably tidy it up.

Sorry for the false alarm.
