### ISSUE TITLE
Will an exception thrown in the constructor of an actor be caught by the supervisor?

### ISSUE THREAD

**Issue by DoubleCouponDay** [akkadotnet/akka.net#3694]
I noticed when I throw a custom exception in an actor's constructor, the supervising strategy is not fetched. How can I gain this kind of supervision / logging?

**Comment by Aaronontheweb** [comment]
@DoubleCouponDay do you mean the supervision strategy of the parent actor? That should be what intercepts the exception.

**Comment by DoubleCouponDay** [comment]
@Aaronontheweb Yes this is the supervision strategy concept I am referring to. It does not seem to be used at all when it crashes. I considered using a logging sink in hopes that such problems are handled there. Would this be a step in the right direction?

**Comment by DoubleCouponDay** [comment]
supervising actor: https://pastebin.com/ZJEKQvZv
subordinate actor: https://pastebin.com/2rfgeVtR

it will crash in subordinate actor line 44. When a break point is placed in supervising actor line 71, it will not be hit under this scenario.

**Comment by ismaelhamed** [comment]
@DoubleCouponDay this does definitely work:

```csharp
public class SupervisorActor : ReceiveActor
{
    protected override SupervisorStrategy SupervisorStrategy()
    {
        return new AllForOneStrategy(0, 0, localOnlyDecider: exception =>
        {
            return Directive.Escalate;
        });
    }

    protected override void PreStart()
    {
        base.PreStart();
        Context.ActorOf(Props.Create<FaultyActor>());
    }
}

public class FaultyActor : ReceiveActor
{
    public FaultyActor()
    {
        throw new InvalidOperationException();
    }
}
```

**Comment by DoubleCouponDay** [comment]
Thank you!
