### ISSUE TITLE
MultiNodeTestRunner not working on Linux / dotnet

### ISSUE THREAD

**Issue by igormcoelho** [akkadotnet/akka.net#3696]
When creating a new issue, please make sure the following information is part of your issue description. (if applicable). Thank You!

- Which Akka.Net version you are using
1.3.10
- On which platform you are using Akka.Net
Linux / dotnet 2.2
- A list of steps to reproduce the issue. Or an gist or github repo which can be easily used to reproduce your case.

This error was discussed here: https://github.com/dotnet/cli/issues/10452

Akka MultiNodeTestRunner seems not to work on Linux/dotnet.
```
dotnet new console
dotnet add package akka.multinodetestrunner
dotnet build
```

The problem seems to be here: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.MultiNodeTestRunner/Akka.MultiNodeTestRunner.nuspec.template#L19

@peterhuene helped me there on dotnet repo and indicated me as follows:

This is copying platform-specific assets into what should be only managed dependencies to reference. Additionally, I see a ton of native files from the framework itself in lib/netcoreapp1.1; this suggests that this package also published in a self-contained fashioned.

The correct layout for this package should be only managed assemblies to reference (both at compile-time and run-time) in lib/ and put the native assets into runtimes/ to copy for run-time only.

While we do get a warning for each PE without managed metadata in lib/netcoreapp1.1 for this package, 16.x MSBuild does fail with an internal error:
```
usr/local/share/dotnet/sdk/3.0.100-preview-009812/Microsoft.Common.CurrentVersion.targets(2114,5): error MSB4018: The "ResolveAssemblyReference" task failed unexpectedly. [/Users/peterhuene/tmp/repro/repro.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview-009812/Microsoft.Common.CurrentVersion.targets(2114,5): error MSB4018: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Unexpected CopyLocal flag. [/Users/peterhuene/tmp/repro/repro.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview-009812/Microsoft.Common.CurrentVersion.targets(2114,5): error MSB4018:    at Microsoft.Build.Tasks.CopyLocalStateUtility.IsCopyLocal(CopyLocalState state) [/Users/peterhuene/tmp/repro/repro.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview-009812/Microsoft.Common.CurrentVersion.targets(2114,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.LogResults(ReferenceTable dependencyTable, List`1 idealAssemblyRemappings, List`1 idealAssemblyRemappingsIdentities, ArrayList generalResolutionExceptions) [/Users/peterhuene/tmp/repro/repro.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview-009812/Microsoft.Common.CurrentVersion.targets(2114,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader) [/Users/peterhuene/tmp/repro/repro.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview-009812/Microsoft.Common.CurrentVersion.targets(2114,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute() [/Users/peterhuene/tmp/repro/repro.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview-009812/Microsoft.Common.CurrentVersion.targets(2114,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/peterhuene/tmp/repro/repro.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview-009812/Microsoft.Common.CurrentVersion.targets(2114,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/peterhuene/tmp/repro/repro.csproj]
```
The RAR task should probably be more resilient to incorrect packages by warning then ignoring any non-managed PEs in lib/.

**Comment by igormcoelho** [comment]
Perhaps related to https://github.com/akkadotnet/akka.net/issues/3573

**Comment by Aaronontheweb** [comment]
Believe this has been fixed by https://github.com/akkadotnet/Akka.MultiNodeTestRunner, which runs as a `dotnet test` adapter.
