### ISSUE TITLE
CurrentEventsByTag does not return more than a 100 events

### ISSUE THREAD

**Issue by ptjhuang** [akkadotnet/akka.net#3697]
Akka.Net 1.3.11
.NET Core Windows
Call SqlReadJournal.CurrentEventsByTag with empty an event log throws ArgumentException: To offset must be a positive number

Test Case: https://gist.github.com/ptjhuang/fc44fa9ca80e87fe7835f71e06aa40da

Looked at the Scala version and it looks different.  Is this a bug?

[Scala version](https://github.com/akka/akka/blob/master/akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByTagPublisher.scala#L188)

[.NET version](https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/persistence/Akka.Persistence.Query.Sql/EventsByTagPublisher.cs#L197)

**Comment by ismaelhamed** [comment]
LIMIT for CurrentEventsByTag is controlled by the `query.journal.sql.max-buffer-size` option --which is 100 by default. See line [#85](https://github.com/akka/akka/blob/b52795331089f1ec7d4cd4134171a6f0ef96486e/akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByTagPublisher.scala#L85).

Any differences with the Scala version might be worth looking at, in case they made any improvements. 

cc @Horusiath @Aaronontheweb

**Comment by Horusiath** [comment]
`CurrentEventsByTag` should return all events, then complete the stream, once it reached the end. MaxBufferSize only describes the size of the batched, in which we internally poll for the data from the database.

**Comment by ismaelhamed** [comment]
In the current implementation `CurrentEventsByTag` will poll the database only once, hence why the `query.journal.sql.max-buffer-size` acts as a limit here. **Potential bug** then?

**Comment by Aaronontheweb** [comment]
close via #3698
