### ISSUE TITLE
CoordinatedShutdown should run automatically upon SIGTERM in .NET Core

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3711]
Verison: Akka.NET v1.3.11

When I originally implemented `CoordinatedShutdown`, I left this little "TODO" in the source because .NET Standard 1.6 didn't expose an easy way for me to hook into process shutdown events, so I thought at least:

https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/CoordinatedShutdown.cs#L682

Found this issue while working on https://github.com/petabridge/Cluster.WebCrawler/issues/7

So, is there a way to implement this in .NET Standard 1.6 today? Or do we need to look at doing this within the confines of .NET Standard 2.0+?

**Comment by nagytech** [comment]
From .NET Standard 1.6 `AssemblyLoadContext`: https://apisof.net/catalog/System.Runtime.Loader.AssemblyLoadContext.Unloading


And, from .NET core 2.0 the AppDomain hooks are supported: https://apisof.net/catalog/System.AppDomain

If you need to support netstandard, then sample code is below.  Otherwise, everything can use AppDomain.

~~~
#if APPDOMAIN
                // run all hooks during termination sequence
                AppDomain.CurrentDomain.ProcessExit += (sender, args) =>
                {
                    // have to block, because if this method exits the process exits.
                    coord.RunClrHooks().Wait(coord.TotalTimeout);
                };
#elif CORECLR
                AssemblyLoadContext.Default.Unloading += (ctx) =>
                {
                    coord.RunClrHooks().Wait(coord.TotalTimeout);
                }
#endif
~~~

**Comment by nagytech** [comment]
Actually, I just noticed this PR that implies all future builds will target .NET Core 2.0+.  

https://github.com/akkadotnet/akka.net/pull/3790/files#diff-6195930459ca65f0430c590b03b0e226

Is Akka.NET going to be dropping support for .NET Standard 1.6?

**Comment by Aaronontheweb** [comment]
Yep, that's correct!
