### ISSUE TITLE
FSM: exception in LogTermination changes stopEvent.Reason to Shutdown

### ISSUE THREAD

**Issue by stijnherreman** [akkadotnet/akka.net#3723]
When stopping an FSM with `return Stop(new Failure(null))`, at first sight it seems to work. But this actually causes an exception in `LogTermination(Reason reason)` at https://github.com/akkadotnet/akka.net/blob/41c116d2a3d280481e584401608ec848dc147632/src/core/Akka/Actor/FSM.cs#L1353

Later on in `OnTermination`, the type of `stopEvent.Reason` will be `Shutdown` instead of `Failure`.

I'd expect one of these to happen:
* an `ArgumentNullException` is thrown when calling `new Failure(null)`
* exceptions in `LogTermination(...)` are caught so the original stop reason is preserved

**Comment by eaba** [comment]
@Aaronontheweb I have investigated this issue on this [branch](https://github.com/eaba/akka.net/tree/%233723)
````csharp
private void Terminate(State<TState, TData> upcomingState)
        {
            if (_currentState.StopReason == null)
            {
                var reason = upcomingState.StopReason;

                //we need to set the cause if null and reason is failure here
                if (reason is Failure f)
                {
                    if (f.Cause is null)
                        reason = new Failure(new ArgumentNullException("cause"));
                }
                LogTermination(reason);
                foreach (var t in _timers)
                {
                    t.Value.Cancel();
                }
                _timers.Clear();
                _timeoutFuture?.Cancel();
                _currentState = upcomingState;
                
                var stopEvent = new StopEvent<TState, TData>(reason, _currentState.StateName, _currentState.StateData);
                _terminateEvent(stopEvent);
            }
        }
````

**Comment by ismaelhamed** [comment]
`LogTermination` should handle the case when `Cause` is null and don't log. If that is not the desired behavior, `LogTermination` can always be overridden.

**Comment by eaba** [comment]
@ismaelhamed ?:
````csharp
protected virtual void LogTermination(Reason reason)
        {
            var failure = reason as Failure;
            if (failure != null)
            {
                if (failure.Cause is Exception)
                {
                    _log.Error(failure.Cause.AsInstanceOf<Exception>(), "terminating due to Failure");
                }
                else if(!(failure.Cause is null))
                {
                    _log.Error(failure.Cause.ToString());
                }
            }
        }
````

**Comment by Arkatufus** [comment]
> 
> 
> `LogTermination` should handle the case when `Cause` is null and don't log. If that is not the desired behavior, `LogTermination` can always be overridden.

I'd rather have the reverse, LogTermination will always log an error, regardless if Cause is null or not. If this is not the desired behavior, LogTermination can be overriden.

**Comment by ismaelhamed** [comment]
Agree, it makes more sense. Actually, looks like they just log an empty/null error in the JVM.
