### ISSUE TITLE
The Storage Plugins page looks to have broken code under the Journals section. 

### ISSUE THREAD

**Issue by izavala** [akkadotnet/akka.net#3732]
The _Persistance, Storage plugins_ page looks to have a broken section of code in the configurations example. The block of code shown does not look complete and it seems to be missing the actual configuration code. 

[`Storage plugins page `](https://getakka.net/articles/persistence/storage-plugins.html
)

![screenshot 2](https://user-images.githubusercontent.com/46451831/54050015-c7daf100-41a3-11e9-95cc-c6d66894c042.png)

**Comment by sean-gilliam** [comment]
Nice catch. It looks like some line numbers got shifted around for both the Journals and Snapshot store examples. Looks like shifted by 5 lines. That page can be found here https://github.com/akkadotnet/akka.net/blob/dev/docs/articles/persistence/storage-plugins.md

The journals section looks like it should be changed to ../../../src/core/Akka.Persistence/persistence.conf#L201-L207

and the snapshot store should be changed to 
../../../src/core/Akka.Persistence/persistence.conf#L209-L215
