### ISSUE TITLE
CoordinatedShutdown Memory Leak

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3735]
Version: Akka.NET v1.3.11

Based on the investigation I did for issue #2640, I found that while the lion's share of leaked memory came from the `ForkJoinExecutor` and `PinnedDispatcher`s not being shutdown correctly as a result of an `IScheduler` bug, there was also a small amount of memory leaked as a result of some of the closures over the `ActorSystem` used inside the `CoordinatedShutdown` class as well.

I haven't fully investigated this yet, but I intend to make some headway on that ASAP in order to ensure that `ActorSystem`s don't hang around after being shutdown inside an Akka.NET process.

**Comment by EJantzerGitHub** [comment]
What I have found :
adding "coordinated-shutdown.run-by-clr-shutdown-hook = off" avoids the leak on InitClrHook and the existing test harness and tests from 2640 pass.

My application that needs to do actor system restarts during its lifetime still leaks memory

When I connect the 2640 test harness to an active seed node, dotMemory shows a steady growth in the dotNetty buffers over time

**Comment by Aaronontheweb** [comment]
This is a very useful piece of information @EJantzerGitHub - here's what I think is happening:

https://github.com/akkadotnet/akka.net/blob/04a5eb2a076bb336a231ca8a7ba126be705178ee/src/core/Akka/Actor/CoordinatedShutdown.cs#L675-L679

This event is effectively closing over the `CoordinatedShutdown` and subsequent `ActorSystem` objects, and if the `ActorSystem` shuts down it never unregisters against that hook - therefore all of the dormant memory retained by each terminated `ActorSystem` in a given process never gets GCed. I think that's the source of the leak.

I'm playing around with some of the sources for `CoordinatedShutdown` now in an effort to get #3711 implemented for the first Akka.NET v1.4.0 beta, but I think I can address this too and verify it using  https://github.com/Aaronontheweb/Akka.NET264BugRepro
