### ISSUE TITLE
Checking the existence of an actor before sending a message via PipeTo

### ISSUE THREAD

**Issue by VladimirLuzhin** [akkadotnet/akka.net#3742]
Good day! 

Is it possible to somehow verify that the actor exists before sending a message via PipeTo? 
It is just possible that some kind of operation took too long and the actor’s reference became irrelevant.

Thanks in advance for the answer!

**Comment by avber** [comment]
Try

test = Context.System.ActorSelection("/user/test").Anchor;
compare = test.Equals(ActorRefs.Nobody);

**Comment by VladimirLuzhin** [comment]
ActorSelection will throw an ActorNotFoundException if the actor does not exist

**Comment by Horusiath** [comment]
@VladimirLuzhin If you have only actor path, you can resolve its `IActorRef` by calling:

```csharp
var selection = system.ActorSelection(actorPath);
var identity = await selection.Ask<ActorIdentity>(new Identify(null), timeout: TimeSpan.FromSeconds(5));
if (identity.Subject != null)
{
     var actorRef = identity.Subject;
}
```

 You can also call `Context.Watch(actorRef)` over target `IActorRef` to observe it's liveness. In case if that actor will terminate, all watcher actors will receive `Terminated` message informing about which actor has died.

PS: I'm closing this issue. We try to use github issues only to track development issues. For the future, please use [gitter channel](https://gitter.im/akkadotnet/akka.net) or post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/akka.net) with *akka.net* tag.
