### ISSUE TITLE
FR: Distributed Publish Subscribe in Cluster excludeRoles

### ISSUE THREAD

**Issue by avber** [akkadotnet/akka.net#3747]
Could you consider the following change to Distributed Publish Subscribe?

Add excludeRoles. It would allow using DPS on all cluster nodes EXCEPT some nodes.

E.g. on all cluster nodes EXCEPT lighthouse.

akka.cluster.pub-sub {
 
  excludeRoles = ["role1", "roleN"]
}

**Comment by Horusiath** [comment]
@avber what problem does it solve, that couldn't be solved with existing role mechanism?

**Comment by avber** [comment]
Existing role mechanism

From the docs
 --Start the mediator on members tagged with this role.
  role = ""

> if you're configuring akka.cluster.pub-sub.role with different roles, this means that you'll create different spaces. Each distributed pub/sub mediator will only see mediators having the same role.

If I understand it correctly, only one role can be specified. You have to assign a second role to a cluster node for it to participate in some pubsub group. Extra actors would be deployed to this node due to router configuration. It might not be desirable.

Even if I wanted one way messaging, it' prevented in the code
`if (!string.IsNullOrEmpty(_settings.Role) && !_cluster.SelfRoles.Contains(_settings.Role))
throw new ArgumentException($"The cluster member [{_cluster.SelfAddress}] doesn't have the role [{_settings.Role}]"`

It's not possible to override it because all Receive<> calls are in DistributedPubSubMediator constructor.


IMO node exclusion based on multiple role names gives more flexibility and requires configuration on fewer nodes.

**Comment by Horusiath** [comment]
>  You have to assign a second role to a cluster node for it to participate in some pubsub group. 

Yes, and it's pretty standard pattern to assign multiple roles and use them as node capabilities. There's nothing uncommon in a single node having 4-5 different roles. It also makes very visible and very easy to reason about which node can do what things. Example:

Node A - roles: [worker, dist-pub-sub, sharding, eu-west-1]
Node B - roles: [worker, dist-pub-sub, sharding, eu-west-1]
Node C - roles: [client, dist-pub-sub, eu-west-1]
Node D - roles: [lighthouse, eu-west-1]

When you see the roles, you can immediately conclude, what capabilities each node has (it's easy to figure out convention), without even looking at the rest of the configuration, which can be hundred lines of code, different on each node.
