### ISSUE TITLE
Call PBM commands from code.

### ISSUE THREAD

**Issue by leo12chandu** [akkadotnet/akka.net#3748]
- Which Akka.Net version you are using - 1.3.11
- On which platform you are using Akka.Net - Windows/and Linux docker
- A list of steps to reproduce the issue. Or an gist or github repo which can be easily used to reproduce your case.

Is there a way to issue pbm commands from code without having to create a System.Diagnostics.Process("pbm.exe")? 

This [link](https://cmd.petabridge.com/articles/commands/custom-commands.html#handling-commands) seems to show we could Ask('/user/pbmListener/clusterHandler', message) but what is the command/message (Ask parameter) we have to pass to execute "`pbm <IP:Port> cluster show`"?

**Comment by Aaronontheweb** [comment]
@leo12chandu I'll recreate this issue on the appropriate repo

**Comment by Aaronontheweb** [comment]
You actually can do this now https://cmd.petabridge.com/articles/clients/index.html#ipbmclient-programmatic-client
