### ISSUE TITLE
Detect Remote unavailable

### ISSUE THREAD

**Issue by auxua** [akkadotnet/akka.net#3756]
Hi,

Currently, I am using Akka.net having ActorSystems on different machines in the network. When trying to send (tell) messages from one actor to a remote actor which is not available (e.g., machine is running, but no ActorSystem), I get errors in the log induced by the underlying tcp-connection level but not in the top-level code of mine in the Actors. Is there a way to enforce this? (Maybe a HOCON-option?)

The first approach, using Ask with explicit confirmation instead of Tell is not useful, as the network is configured for "one-way" connections - which is not working with the Ask/Reply scheme.

Is there a way to get the information stated above?

**Comment by Horusiath** [comment]
@auxua what do you mean by ` the network is configured for "one-way" connections`? Your actor systems won't work with each other if they won't be able to send messages to each other.

**Comment by auxua** [comment]
Due to network administration, there are two networks (A, B). Systems in network A are allowed to create (tcp) connections to systems in Network B. Vice versa, systems of B are not allowed to create connections to network A. 

In fact, when my Actor in A sends a message to an Actor in system in B, it works fine. If the machine/ip in B exists, but there is no Actor running, I see errors in As Log, but not in Code. 

When using Ask, I do not get the response from the system in B. 

Therefore I am in search of an integrated feedback on delivery success

**Comment by Horusiath** [comment]
I don't think, this will work that way - if you're using Akka.Remote, it requires all communicating nodes to be able to connect to each other. This is required to make core features (like Ask you've mentioned, but also watchers and some system messages) work.

You can potentially build your own network communication layer using either [actors](https://getakka.net/articles/networking/io.html) or [streams](https://getakka.net/articles/streams/workingwithstreamingio.html) (IMHO latter is way easier) or just integrate some 3rd party networking stack. But this way you'll not be able to make use features like watchers or actor transport transparency mechanism.

**Comment by auxua** [comment]
I am ok, if this edge-case of my project cannot rely on some of the core features like the Ask-approach. I'm struggling as I see the information I want to see in the actual log file. So this information is consumed somewhere and hidden to the program while showing to the user/console.

The obvious Workaround, catching the log and parsing it at runtime is a horrible solution I do not want to bring in.

**Comment by Horusiath** [comment]
Usually, when you have situation like this:

> When trying to send (tell) messages from one actor to a remote actor which is not available (e.g., machine is running, but no ActorSystem)

The actual way to work with this issue is to first obtain an `IActorRef` to a given actor. Example:

```csharp
var selection = Context.System.ActorSelection(actorPath);
selection.Tell(new Identify(null));
// wait or timeout for ActorIdentity to arrive back
Receive<ActorIdentity>(msg => var actorRef = msg.Subject); // Subject can be null
```

This way you can work with that `actorRef` directly, being sure it's there. You can also watch over it, to get informed when actor terminates (either because it's stopped or actor system is shut down):

```csharp
Context.Watch(actorRef);
// current actor will receive Terminated message, when actor dies
Receive<Terminated>(terminated => terminated.ActorRef);
```

All of these mechanics depend on two actors being able to send messages to each other. I don't think it's possible to have actor-actor communication in Akka.NET having only one-way connection.
