### ISSUE TITLE
Akka.Persistence in memory Journal is not storing/recovering events

### ISSUE THREAD

**Issue by amarcute** [akkadotnet/akka.net#3760]
I'm exploring Akka.Persistence to persist and recover actor events. I tried it with different plugins - In Memeory, SQL Server and MongoDB. 

The in memory plugin is saving journal events & also not able to recover (as it is not able to save). It works fine with the other two plugins. 

I'm using Akka.Persistence 1.3.12 along Akka 1.3.12 Nugets
Visual Studio 2017 Prof (version 15.8.16) on Windows 
.Net Framework 4.6.2 Console Application

HOCON config:
  <akka>
    <hocon>
      <![CDATA[
          # In-memory journal plugin.
          akka.persistence.journal.inmem {
              # Class name of the plugin.
              class = "Akka.Persistence.Journal.MemoryJournal, Akka.Persistence"
              # Dispatcher for the plugin actor.
              plugin-dispatcher = "akka.actor.default-dispatcher"
          }

          # In-memory snapshot store plugin.
          akka.persistence.snapshot-store.inmem {
              # Class name of the plugin.
              class = "Akka.Persistence.Snapshot.MemorySnapshotStore, Akka.Persistence"
              # Dispatcher for the plugin actor.
              plugin-dispatcher = "akka.actor.default-dispatcher"
          }
      ]]>
    </hocon>
  </akka>

Am I missing something here? I can provide more details as needed.

**Comment by valdisz** [comment]
I will look into it

**Comment by valdisz** [comment]
@amarcute can you be more specific? Please describe the whole case or better give code example.

**Comment by valdisz** [comment]
Just in case... In Memory journal is meant for testing and will not persist information between restarts as it literally saves everything in RAM while app is running.
