### ISSUE TITLE
TypeExtensions.TypeQualifiedName includes strict assembly references for generic arguments

### ISSUE THREAD

**Issue by jameswilddev** [akkadotnet/akka.net#3767]
- Akka.NET 1.3.12
- Windows 10 64-bit (.NET Core 2.2).

The following code:
```
using Akka.Util;
using System;

namespace QuickTest
{
    public sealed class OtherClassA { }

    public sealed class OtherClassB { }

    public sealed class OtherClassC { }

    public sealed class ParentClass<T1, T2, T3>
    {
        public sealed class ChildClass
        {

        }
    }

    public sealed class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine(TypeExtensions.TypeQualifiedName(typeof(ParentClass<OtherClassA, OtherClassB, OtherClassC>.ChildClass)));
            Console.ReadLine();
        }
    }
}
```

Produces the following result:

```
QuickTest.ParentClass`3+ChildClass[[QuickTest.OtherClassA, QuickTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[QuickTest.OtherClassB, QuickTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[QuickTest.OtherClassC, QuickTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], QuickTest
```

This, as seen, includes fairly strict assembly references for generic arguments (`, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`), while it does not for non-generic types (and this appears to be very much intentional given the [current source](https://github.com/akkadotnet/akka.net/blob/5ca783fef57a23f9e0ee3d4c826c77e8b9155d6b/src/core/Akka/Util/TypeExtensions.cs#L67)).

This method is used when describing a type for the serialization manifest, and I do not feel it should ever be making a strict (versioned) assembly reference.

**Comment by jameswilddev** [comment]
I feel it should probably do what Hyperion does [here](https://github.com/akkadotnet/Hyperion/blob/9b4ed1a3002f49f373bc8285dbe0e567ec671fc7/src/Hyperion/Extensions/TypeEx.cs#L219).

**Comment by Aaronontheweb** [comment]
@jameswilddev we should port those changes over

**Comment by valdisz** [comment]
@jameswilddev @Aaronontheweb working on this problem
