### ISSUE TITLE
How to remove the unused dependency files?

### ISSUE THREAD

**Issue by woodywu** [akkadotnet/akka.net#3776]
I found that there so many dependency files while release my application. Is there any way to remove the useless files? Please give me a help.

Thank you.
                                                                                                                                                                                 
Akka.dll                                                  
Akka.Remote.dll                                           
Akka.Remote.xml                                           
Akka.xml                                                  
AkkaPractice.Shared.dll                                   
AkkaPractice.Shared.pdb                                   
DotNetty.Buffers.dll                                      
DotNetty.Buffers.xml                                      
DotNetty.Codecs.dll                                       
DotNetty.Codecs.xml                                       
DotNetty.Common.dll                                       
DotNetty.Common.xml                                       
DotNetty.Handlers.dll                                     
DotNetty.Handlers.xml                                     
DotNetty.Transport.dll                                    
DotNetty.Transport.xml                                    
Google.Protobuf.dll                                       
Google.Protobuf.xml                                       
Microsoft.Extensions.DependencyInjection.Abstractions.dll 
Microsoft.Extensions.DependencyInjection.Abstractions.xml 
Microsoft.Extensions.Logging.Abstractions.dll             
Microsoft.Extensions.Logging.Abstractions.xml             
Microsoft.Extensions.Logging.dll                          
Microsoft.Extensions.Logging.xml                          
Microsoft.Win32.Primitives.dll                            
netstandard.dll                                           
Newtonsoft.Json.dll                                       
Newtonsoft.Json.xml                                       
PureAkkaClient.exe                                        
PureAkkaClient.exe.config                                 
PureAkkaClient.pdb                                        
System.AppContext.dll                                     
System.Collections.Concurrent.dll                         
System.Collections.dll                                    
System.Collections.Immutable.dll                          
System.Collections.Immutable.xml                          
System.Collections.NonGeneric.dll                         
System.Collections.Specialized.dll                        
System.ComponentModel.dll                                 
System.ComponentModel.EventBasedAsync.dll                 
System.ComponentModel.Primitives.dll                      
System.ComponentModel.TypeConverter.dll                   
System.Console.dll                                        
System.Data.Common.dll                                    
System.Diagnostics.Contracts.dll                          
System.Diagnostics.Debug.dll                              
System.Diagnostics.DiagnosticSource.dll                   
System.Diagnostics.DiagnosticSource.xml                   
System.Diagnostics.FileVersionInfo.dll                    
System.Diagnostics.Process.dll                            
System.Diagnostics.StackTrace.dll                         
System.Diagnostics.TextWriterTraceListener.dll            
System.Diagnostics.Tools.dll                              
System.Diagnostics.TraceSource.dll                        
System.Diagnostics.Tracing.dll                            
System.Drawing.Primitives.dll                             
System.Dynamic.Runtime.dll                                
System.Globalization.Calendars.dll                        
System.Globalization.dll                                  
System.Globalization.Extensions.dll                       
System.IO.Compression.dll                                 
System.IO.Compression.ZipFile.dll                         
System.IO.dll                                             
System.IO.FileSystem.dll                                  
System.IO.FileSystem.DriveInfo.dll                        
System.IO.FileSystem.Primitives.dll                       
System.IO.FileSystem.Watcher.dll                          
System.IO.IsolatedStorage.dll                             
System.IO.MemoryMappedFiles.dll                           
System.IO.Pipes.dll                                       
System.IO.UnmanagedMemoryStream.dll                       
System.Linq.dll                                           
System.Linq.Expressions.dll                               
System.Linq.Parallel.dll                                  
System.Linq.Queryable.dll                                 
System.Net.Http.dll                                       
System.Net.NameResolution.dll                             
System.Net.NetworkInformation.dll                         
System.Net.Ping.dll                                       
System.Net.Primitives.dll                                 
System.Net.Requests.dll                                   
System.Net.Security.dll                                   
System.Net.Sockets.dll                                    
System.Net.WebHeaderCollection.dll                        
System.Net.WebSockets.Client.dll                          
System.Net.WebSockets.dll                                 
System.ObjectModel.dll                                    
System.Reflection.dll                                     
System.Reflection.Extensions.dll                          
System.Reflection.Primitives.dll                          
System.Resources.Reader.dll                               
System.Resources.ResourceManager.dll                      
System.Resources.Writer.dll                               
System.Runtime.CompilerServices.Unsafe.dll                
System.Runtime.CompilerServices.Unsafe.xml                
System.Runtime.CompilerServices.VisualC.dll               
System.Runtime.dll                                        
System.Runtime.Extensions.dll                             
System.Runtime.Handles.dll                                
System.Runtime.InteropServices.dll                        
System.Runtime.InteropServices.RuntimeInformation.dll     
System.Runtime.Numerics.dll                               
System.Runtime.Serialization.Formatters.dll               
System.Runtime.Serialization.Json.dll                     
System.Runtime.Serialization.Primitives.dll               
System.Runtime.Serialization.Xml.dll                      
System.Security.Claims.dll                                
System.Security.Cryptography.Algorithms.dll               
System.Security.Cryptography.Csp.dll                      
System.Security.Cryptography.Encoding.dll                 
System.Security.Cryptography.Primitives.dll               
System.Security.Cryptography.X509Certificates.dll         
System.Security.Principal.dll                             
System.Security.SecureString.dll                          
System.Text.Encoding.dll                                  
System.Text.Encoding.Extensions.dll                       
System.Text.RegularExpressions.dll                        
System.Threading.dll                                      
System.Threading.Overlapped.dll                           
System.Threading.Tasks.dll                                
System.Threading.Tasks.Extensions.dll                     
System.Threading.Tasks.Extensions.xml                     
System.Threading.Tasks.Parallel.dll                       
System.Threading.Thread.dll                               
System.Threading.ThreadPool.dll                           
System.Threading.Timer.dll                                
System.ValueTuple.dll                                     
System.Xml.ReaderWriter.dll                               
System.Xml.XDocument.dll                                  
System.Xml.XmlDocument.dll                                
System.Xml.XmlSerializer.dll                              
System.Xml.XPath.dll                                      
System.Xml.XPath.XDocument.dll

**Comment by Aaronontheweb** [comment]
@woodywu unfortunately, this is a side effect of .NET Core and the way the packaging system works for distributing dependencies now. Self-contained deployments will copy over all of these files and they're all going to be used so long as they're referenced by any one of the upstream packages.
