### ISSUE TITLE
Non-working links for Contributing in README

### ISSUE THREAD

**Issue by mzc9** [akkadotnet/akka.net#3798]
In the Contributing section of README.md, the links "Critical Issues" , "Stories Up For Grabs" , and " issues categorized in the Help! column" do not work.  They reach http://www.waffle.io/akkadotnet/akka.net

**Comment by Aaronontheweb** [comment]
@mzc9 we've deprecated Waffle.io - so we should probably just get rid of those.

**Comment by mzc9** [comment]
So point to https://getakka.net/community/contributor-guidelines.html ?

**Comment by Aaronontheweb** [comment]
We should probably just link to the Github labels page of "up for grabs" and "good for first time contributors" issues, i.e. https://github.com/akkadotnet/akka.net/labels/good%20for%20first-time%20contributors

Should probably link to that from https://getakka.net/community/contributor-guidelines.html too

**Comment by Aaronontheweb** [comment]
I think you need to send this PR to our repo

**Comment by mzc9** [comment]
OOPS.  :-( 
Sorry.

**Comment by Aaronontheweb** [comment]
No big deal!

**Comment by marsop** [comment]
@Aaronontheweb if I am not mistaken, there are no links pointing to waffle in the current `Readme.md` therefore this issue can be safely closed..

**Comment by Aaronontheweb** [comment]
Ah, yes it can. Thank you.
