### ISSUE TITLE
build script failing

### ISSUE THREAD

**Issue by zbynek001** [akkadotnet/akka.net#3807]
when running the build locally via command line:
```
build Build
```

it fails with `NullReferenceException` after this change: a85e63e38c5e7e76ffce87d08f2d368889525375 ("added Azure Pipelines")

```
...
Finished Target: Clean
Starting Target: AssemblyInfo (==> Clean)
Finished Target: AssemblyInfo
Starting Target: ComputeIncrementalChanges
Skipping Incrementalist - not enabled for this build
Finished Target: ComputeIncrementalChanges
Starting Target: Build (==> AssemblyInfo, ComputeIncrementalChanges)
Checking inside C:\Projects\GitHub\_My\akka.net\bin\incrementalist.txt for changes
Found changes via Incrementalist? false - searched inside C:\Projects\GitHub\_My\akka.net\bin\incrementalist.txt
Running build failed.
Error:
System.NullReferenceException: Object reference not set to an instance of an object.
   at FSI_0005.Build.clo@171-7.Invoke(Unit _arg2) in C:\Projects\GitHub\_My\akka.net\build.fsx:line 182
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
Starting FinalTarget: KillCreatedProcesses
Shutting down dotnet build-server
dotnet build-server shutdown
Shutting down MSBuild server...
...
```
or is it just an issue on my end?

**Comment by Aaronontheweb** [comment]
@zbynek001 works on the build server - issue might be that you need to clean out your local files. If you try a clean clone of the project do you still get this issue?

**Comment by zbynek001** [comment]
tried it with a clean copy of dev, still the same issue. strange

**Comment by mika76** [comment]
Yeah also getting this with fresh clone...

**Comment by davebowler** [comment]
Same problem for me. Cloned 10 minutes ago.

**Comment by Aaronontheweb** [comment]
I'll look into it

**Comment by Aaronontheweb** [comment]
Ok, been able to reproduce it - if you pass in a build configuration that doesn't trigger the use of [Incrementalist](https://github.com/petabridge/Incrementalist), such as `./build.cmd nuget`, then you get this error.

We shouldn't be attempting to do an incremental build under these circumstances anyway, so I'll make sure this step gets skipped.

**Comment by Aaronontheweb** [comment]
This is now fixed in the `dev` branch
