### ISSUE TITLE
Issue with dns resolving using system.tcp

### ISSUE THREAD

**Issue by mika76** [akkadotnet/akka.net#3809]
When creating a new issue, please make sure the following information is part of your issue description. (if applicable). Thank You!

- Which Akka.Net version you are using
1.3.13

- On which platform you are using Akka.Net
Windows 10 running in Parallels on Mac - using .net 4.6.2

- A list of steps to reproduce the issue. Or an gist or github repo which can be easily used to reproduce your case.

my ip config looks like this...
```
Windows IP Configuration


Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe----------f492:703b%8
   IPv4 Address. . . . . . . . . . . : 192.168.1.156
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.1.1

Ethernet adapter Npcap Loopback Adapter:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe---------:559%15
   Autoconfiguration IPv4 Address. . : 169.254.5.89
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :
```

I have an actor which is trying to connect to a tcp service running on the same machine using the code

```c#
var port = 7000;
var endpoint = new DnsEndPoint("192.168.1.156", port, System.Net.Sockets.AddressFamily.InterNetwork);

Context.System.Tcp().Tell(new Tcp.Connect(endpoint));
```

But it always fails connecting with the following logs...

```
[DEBUG][24/05/2019 7:28:53 PM][Thread 0003][akka://GFS8000/system/IO-TCP] now supervising akka://GFS8000/system/IO-TCP/$a
[DEBUG][24/05/2019 7:28:53 PM][Thread 0003][[akka://GFS8000/system/IO-TCP/$a#466248074]] Resolving 192.168.1.156 before connecting
[DEBUG][24/05/2019 7:28:53 PM][Thread 0003][akka://GFS8000/system/IO-TCP/$a] Started (Akka.IO.TcpOutgoingConnection)
[DEBUG][24/05/2019 7:28:53 PM][Thread 0003][akka://GFS8000/user/MachineRouter/NetworkAdapter-Floor] now watched by [akka://GFS8000/system/IO-TCP/$a#466248074]
[DEBUG][24/05/2019 7:28:53 PM][Thread 0003][akka://GFS8000/system] now supervising akka://GFS8000/system/$a
[DEBUG][24/05/2019 7:28:53 PM][Thread 0003][akka://GFS8000/system/$a] Started (Akka.IO.SimpleDnsManager)
[DEBUG][24/05/2019 7:28:53 PM][Thread 0003][akka://GFS8000/system/$a] now supervising akka://GFS8000/system/$a/$a
[DEBUG][24/05/2019 7:28:53 PM][Thread 0003][[akka://GFS8000/system/$a#1414173804]] Resolution request for 192.168.1.156 from [akka://GFS8000/system/IO-TCP/$a#466248074]
[DEBUG][24/05/2019 7:28:53 PM][Thread 0003][akka://GFS8000/system/$a/$a] Started (Akka.IO.InetAddressDnsResolver)
[DEBUG][24/05/2019 7:28:53 PM][Thread 0003][[akka://GFS8000/system/IO-TCP/$a#466248074]] Attempting connection to [169.254.5.89:7000]
[DEBUG][24/05/2019 7:28:59 PM][Thread 0004][[akka://GFS8000/system/IO-TCP/$a#466248074]] Could not establish connection because finishConnect never returned true (consider increasing akka.io.tcp.finish-connect-retries)
```

*NOTE* how the IP address changes from the one specified (192.168.1.156) to the autoconfiguration one (169.254.5.89) - even though I specifically wrote the first one...

**Comment by mika76** [comment]
Hmm it seems to be the Npcap Loopback Adapter causing issue - when I disable it it connects. Funny thing is that this does not cause problems when using a normal C# TCP class and connecting manually - so something in Akka is clashing but I cannot tell what...

**Comment by Aaronontheweb** [comment]
Definitely looks like a network address translation issue - would you mind taking a look at the DNS resolution code and see if we're doing something weird? We use Akka.IO heavily in [Petabridge.Cmd](https://cmd.petabridge.com/) and haven't run into any issues like this.

**Comment by mika76** [comment]
Sure, will do...

**Comment by mika76** [comment]
I think this can be closed - After removing the npcap loopback adapted I never had an issue like this again so I would chalk it down to weird virtualization and move on. I did have a look at the time at the dns code and could not see anything wrong...

**Comment by Aaronontheweb** [comment]
Thanks @mika76
