### ISSUE TITLE
Inconsistent threading behaviour between .NET Full and .NET Core versions

### ISSUE THREAD

**Issue by vadimart92** [akkadotnet/akka.net#3813]
Akka version: 1.3.13
When run this [repro](https://gist.github.com/vadimart92/91cb9ddb1ce624116360585f2baffcdd) the result value under .net full framework will be null, but under .net core it will be "secretValue".

It's related to missing constants `UNSAFE_THREADING;APPDOMAIN` for NetStandardLibVersion
https://github.com/akkadotnet/akka.net/blob/a3963cd1af604cf3ebee00358382da2882a09bff/src/core/Akka/Akka.csproj#L37-L43

The question is: it's a bug or feature for .net core version?

**Comment by Aaronontheweb** [comment]
@vadimart92 `AsyncLocal`, as far as I know, is totally unsupported when used between actor messaging processing instances - because we don't use async contexts except for when a developer explicitly uses `async` / `await`. Actor message processing is thread-based. I'd imagine the results you're seeing there are probably more the result of differences in the CLR's handling of that between runtimes rather than what Akka.NET is doing.

We're going to be getting rid of all of those additional compilation symbols in Akka.NET v1.4.0. No longer needed on .NET Standard 2.0.

**Comment by vadimart92** [comment]
@Aaronontheweb thanks for quick reply,
the real reason why async context is not preserved in full framework version of akka is because of ThreadPool.UnsafeQueueUserWorkItem usage (compiled with those constants only).
Take a look at this [example](https://gist.github.com/vadimart92/7a8376356ba44dea2462b7256b40b0ac), results are same on desktop and core runtime.

So in fact .net standard version of akka 1.3 accidentally supports AsyncContext (in full trust environment).

But if `UNSAFE_THREADING` symbol will be removed, .net standard 2.0 version of akka will use types like FullThreadPoolExecutorServiceImpl (AsyncContext will not be preserved), right?

**Comment by Horusiath** [comment]
@vadimart92 I think, the general note here should be - do not use AsyncLocal together with actors. It doesn't matter if it accidentally works/doesn't work at the moment. When using actors, you give them ownership of the state and how it's managed. AsyncLocal contradicts this, as it gives the state control to external source (TPL machine in this case).

Under some circumstances, it's possible to use `[ThreadStatic]` attribute together with actors - as it uses much lower level mechanics specific to threads themselves - but in 99.99% of the cases this is a bad idea, that sooner or later will cause issues.

**Comment by Aaronontheweb** [comment]
> the real reason why async context is not preserved in full framework version of akka is because of ThreadPool.UnsafeQueueUserWorkItem usage (compiled with those constants only).

I did not know that! Appreciate the information.

**Comment by vadimart92** [comment]
@Horusiath I totally agree, but in my case there is something like this:
```csharp
class WorkerActor : UntypedActor
{
    protected override void OnReceive(object message) =>
        Sender.Tell(new ThirdPartyCode().Execute(), Self);
}

class ThirdPartyCode {
    private static readonly AsyncLocal<string> _context = new AsyncLocal<string>();
    public static string Context => _context.Value;
    
    public string Execute() {
        _context.Value ??= Guid.NewGuid().ToString();//this breaks on .net standard version
        // Parallel.For(1, 10, (i)=> {
        //    some code that use ThirdPartyCode.Context value
        //});
        return "results";
    }
}
```
and it works on full framework, so i created this issue to understand should i fix it in my code or just wait for v. 1.4
The hard part is the only ability to use empty ExecutionContext is invoke UnsafeQueueUserWorkItem.
