### ISSUE TITLE
How to deal with exceptions when using the ask pattern

### ISSUE THREAD

**Issue by BartHuls** [akkadotnet/akka.net#3834]
In my application to access some actosrs we are using the ask pattern

ResultMessage result = await Context.ActorSelection(ActorPaths.TestActor.Path).Ask<ResultMessage>(new RequestMessage());

In the receice van the actor an exception can be throw. How can I catch this correctly.
Now I have a big try catch and in the catch it's "Telling" the sender a Failure message like:
Sender.Tell(new Failure { Exception = e }, Self);

Now I get the Exception:
 Unable to cast object of type 'Akka.Actor.Failure' to type '....Message'.
Cause: System.InvalidCastException: Unable to cast object of type 'Akka.Actor.Failure' to type '....Message'. which is logical

How must I handle this situation.

**Comment by ismaelhamed** [comment]
@BartHuls Use `PipeTo` with Ask instead of awaiting. That way you don't need to cast anything.

**Comment by BartHuls** [comment]
@ismaelhamed Thanks for the info. The PipeTo I looked into it.
Then I get something like:  `.PipeTo(Context.Self,null,OnSuccess,OnFailure);`
The only thing is that I don't know what to send back in the OnSucces and OnFailure.

I'm looking into a more global way of Exception handling like the BackoffSupervisor, But that does not seems to work

**Comment by ismaelhamed** [comment]
```csharp
   someActor.Ask("Whatever", TimeSpan.FromSeconds(3))
       .PipeTo(Self, failure: ex => new Status.Failure(ex));
```
This code will let you catch, for instance, a timeout exception and return a `Status.Failure` message instead if `someActor` does not reply in time. And it will also `PipeTo` self anything it replies in case of success.

**Comment by BartHuls** [comment]
I have implemented the code, The PipeTo forwards the result nicely to the Actor.
For test I'm throwing an exception in the Actor (someActor).  The result is and  stays null.
How can I check that an exception has occured on "someactor"

**Comment by ismaelhamed** [comment]
@BartHuls as per [documentation](https://getakka.net/articles/actors/receive-actor-api.html#ask-send-and-receive-future): if you want to complete the `Task` with an exception, you have to catch the exception in `someActor` and return a failure message instead, this is not done automatically.

**Comment by BartHuls** [comment]
Ah, Ok, I thought that the framework would handle this (that would be a nice feature)
