### ISSUE TITLE
NetCorePolyfill.cs prevents usage of System.Serializable attribute on netstandard2.0 projects

### ISSUE THREAD

**Issue by john-cullen** [akkadotnet/akka.net#3836]
When Akka 1.3.13 is referenced in a netstandard2.0 project you cannot apply the `System.Serializable` or `System.NonSerialized` attributes to any types as Akka defines it's own.

https://github.com/akkadotnet/akka.net/blame/master/src/core/Akka/Util/Internal/NetCorePolyfills.cs

The following class will fail to compile with the error message `The type 'SerializableAttribute' exists in both 'Akka, Version=1.3.13.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

```csharp
[System.Serializable]
public class Example { }
```

**Comment by Aaronontheweb** [comment]
@john-cullen this is fixed already in v1.4.0 (current dev) and we will be releasing beta1 of that ASAP.
