### ISSUE TITLE
Count the number of restart cycles of an Actor

### ISSUE THREAD

**Issue by BartHuls** [akkadotnet/akka.net#3838]
Is there an easy way to get the number of restart cycles of an Actor.
As default SupervisorStrategy an actor restarts, but how can I get the number of restarts of this actor

**Comment by Aaronontheweb** [comment]
This information is already built into the `ActorCell`:

https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/ChildrenContainer/Internal/ChildStats.cs

And this information can be accessed by subclassing the `SupevisorStrategy`:

https://github.com/akkadotnet/akka.net/blob/18aa2c1867eaad28da6eaa6398047b4c65612dbd/src/core/Akka/Actor/SupervisorStrategy.cs#L71-L93
