### ISSUE TITLE
question: is IactorRef.Tell Thread safe

### ISSUE THREAD

**Issue by luchunminglu** [akkadotnet/akka.net#3860]
actorRef.Tell(message, ActorRefs.NoSender);

is it thread safe?
message is immutable

**Comment by Horusiath** [comment]
Yes, the `Tell` message is thread safe and maintains order in between two actors - *so actor A `Tell`ing some messages to actor B can count on them being delivered in order they were send* - but not across multiple actors.

Messages must be immutable or at least you as an user must guarantee that mutable components of the message are not being accessed from elsewhere (therefore once send, the recipient actor is an **owner** of that data).
