### ISSUE TITLE
Question: RoundRobinPool ReceiveActor, possible to handle only one message at a time

### ISSUE THREAD

**Issue by BartHuls** [akkadotnet/akka.net#3895]
Hi,

I have a ReceiveActor in a RoundRobinPool which also receives messages (besides receiving the normal messages) by using the Ask method for that actor like: 

await Context.ActorSelection(Path).Ask<Response>(Request);

The call is done from another actor and in some cases this can be done from two different Actors simultaneously.

Is there a way that the different messages can be handled after each other even the receiver makes part of a pool of actors. The Ask method must not only wait for the result, but also wait if the actor (read pool) has no other requests in process

**Comment by Horusiath** [comment]
@BartHuls the major purpose of routers is to parallelize incoming workload. Handling messages "after-each-other" implies sequential behavior, which is exactly the opposite. Additionally round-robin router ensures, that messages will be served with specific pattern (every next message is served by next actor in a circular pool).

You can use consistent hashing router to enforce that messages with the same consistent hash will be always served by the same actor (as long as pool is not resized), but this still doesn't guarantee particular ordering: this is only guaranteed when the same pair of actors communicate with each other.

You can also use stashing to dequeue incoming messages until the desired message arrives, and once it does, put all stashed messages back to the actor's mailbox:

```csharp
class MyActor : ActorBase, IWithUnboundedStash 
{
     public IStash Stash { get; set; }
 
     protected overrride bool Receive(object message)
     {
          switch(message)
          {
              // stash all incoming messages until "expected" arrives
              case "expected": Stash.UnstashAll(); return true;
              default: Stash.Stash(); return true;
          }
     }
}
```
