### ISSUE TITLE
Exception is swallowed during XUnit testing

### ISSUE THREAD

**Issue by Dmdv** [akkadotnet/akka.net#3900]
akka.net version 1.3.14
Platform : .NET CORE 2.2
UnitTest: XUnit2

Steps to reproduce

1. Declare 2 actors.
2. Instantiate 1 actor in TestKit class descendand.
3. Instantiate 2 actor inside of 1 actor constructor using Context.System.ActorOf<>
4. After point 2 try to instantiate actor 2 using ActorOfAsTestActorRef

When run in unit test session, the InvalidActorNameException is expected, but the exception is swallowed, the test is green, although in debug tab you can see that the exception is thrown

**Comment by Aaronontheweb** [comment]
This is because the exception is thrown on an actor's background thread. It's not going to be thrown on the foreground thread with XUnit, hence why your test doesn't fail.
