### ISSUE TITLE
LocalActorRefProvider ResolveActorRef returns the _deadLetters IActorRef with an unknown actor path

### ISSUE THREAD

**Issue by kaleho** [akkadotnet/akka.net#3902]
Akka.Net version: 1.3.14
Platform: Windows/Docker

I am currently working on the journal plugin for Azure Table storage.

At the end of replaying events the deserialized persistent message is returned but the test fails due the following reason.

When there is no actor path the default PersistentMessageSerializer calls the ResolveActorPath which returns the deadLetters actor ref as the sender.
https://github.com/akkadotnet/akka.net/blob/8f9d19fa481599056e36ad1d817c2d4149a38198/src/core/Akka/Actor/ActorRefProvider.cs#L410

The JournalSpec Journal_should_serialize_events is expecting the ActorRefs.NoSender reference causing the test to fail. 
https://github.com/akkadotnet/akka.net/blob/8f9d19fa481599056e36ad1d817c2d4149a38198/src/core/Akka.Persistence.TCK/Journal/JournalSpec.cs#L308

The AbstractQueryExecutor is implemented this way in the ReadEvent method so it passes.
https://github.com/akkadotnet/akka.net/blob/8f9d19fa481599056e36ad1d817c2d4149a38198/src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs#L765

I have implemented the Azure plugin to override that to the NoSender value to get the test to pass.

It is a fairly simple change and I can create the PR but would like confirmation that it is appropriate to do so.

**Comment by Aaronontheweb** [comment]
@kaleho we just fixed this in 1.3.14, but we need to update the way we call the serializer in Akka.Persistence.Azure in order to do it correctly. I'll send in a PR to illustrate how to do it.
