### ISSUE TITLE
Found missing porting of Akka.Remote.ResendUnfulfillableException patch from Akka

### ISSUE THREAD

**Issue by seungyongshim** [akkadotnet/akka.net#3905]
Excuse, me
I had the issue #3890. 
Akka 1.3.13

Yesterday, I found relative issue "Fix Akka.Remote.ResendUnfulfillableException after transport failure detection" for Akka (https://github.com/akka/akka/pull/23129).
It is not porting from Akka, yet. But I found  https://github.com/akka/akka/issues/23010#issuecomment-307590625

Please, make me feel safe.

Best Regards

**Comment by Aaronontheweb** [comment]
@seungyongshim I'm on it

**Comment by seungyongshim** [comment]
Currently, our system dies every two to three days. #3890,
Could you release the beta2 with patch? 
We are faster-follower for Akka.NET. And we want to make continuous progress together with Akka.NET.

Best Regards.

**Comment by Aaronontheweb** [comment]
Sure thing - we can do that.

**Comment by Aaronontheweb** [comment]
Reproduction spec on #3914 has verified the existence of this bug.

**Comment by Aaronontheweb** [comment]
Including this in 1.3.15 and 1.4.0-beta2

**Comment by Aaronontheweb** [comment]
@seungyongshim v1.4.0-beta2 is live, and v1.3.15 should be a few minutes behind it: https://github.com/akkadotnet/akka.net/pull/3931
