### ISSUE TITLE
Issue/question

### ISSUE THREAD

**Issue by PetrPejcel** [akkadotnet/akka.net#3917]
Hello, 
We are using akka.net 1.3.12.0 on windows server 2012 R2 standard. 
We get following dead letters:

- DeadLetter captured: InboundPayload
- DeadLetter captured: AckIdleCheckTimer
- DeadLetter captured: HandleListenerRegistered
- DeadLetter captured: StopReading

Is there any reason why this happens? What is the root cause?
Thanks for any help.

**Comment by Horusiath** [comment]
@PetrPejcel without having the actual code or reproducible example, all I can tell is that these messages are related to the akka.remote transport communication. 

If the these are logged during application shutdown, this doesn't necessarily mean anything wrong: as the entire communication is asynchronous, it's possible that while actor system is terminating there still are some messages in-flight that will never reach their destination (as the target actors have been stopped already).

**Comment by PetrPejcel** [comment]
@Horusiath Thanks for answer. 
Unfortunately this is not happening during shutdown, but during "normal" application run. Strange think is it started during time we did not touch anything like akka updates, or our code. Could it be because of some network changes for example or windows server updates?

**Comment by Horusiath** [comment]
I may be the case, that you connections disassociate (which happens when network connection breaks for any reason), hower I must admit I've never seen these messages logged as dead letters in that case (could it be that you're using different logging level or custom dead letter handling).

**Comment by Aaronontheweb** [comment]
Going to close this as it's not clear this is an issue with Akka.NET, but it could be if you're running on IIS that one of the processes running there was AppPool-Recycled, which would effectively terminate and recreate a node.
