### ISSUE TITLE
Deprecate PersistentFSM+State.Using to deter usage in user code

### ISSUE THREAD

**Issue by aloker** [akkadotnet/akka.net#3955]
PersistentFSM+State.Using is meant for internal usage only (unlike FSMBase+State.Using).

https://github.com/akkadotnet/akka.net/blob/ca9916097b5efc06b7e9fbd408306f2df456a3da/src/core/Akka.Persistence/Fsm/PersistentFSM.cs#L381-L390

Internally, calls to it can be replaced with Copy, so the method itself can be dropped or marked internal, but as a non-breaking change it should be marked [Obsolete] to discourage usage in user code.

JVM equivalent https://github.com/akka/akka/pull/23740

PR: #3956

**Comment by Aaronontheweb** [comment]
closed via #3956
