### ISSUE TITLE
Persistence Migration

### ISSUE THREAD

**Issue by Zetanova** [akkadotnet/akka.net#3971]
To migrate/copy or sync from one persistent plugin to an other is currently painful 
because of some missing features.

1) Query.ReadJournal and/or WriteJournal are missing an option to query the last SeqNr of then PersistenceId from user-space.
Currently the the only way is to read all events of an PID and take the SeqNr from the last event.
This limit the performance of a resume migration/sync

2) There is no option to resume a PersistenceIds query or detected changes since the last query time. To let a ```ReadJournal.PersistenceIds``` stream run and register for each PID a separate  ```ReadJournal.EventsByPersistenceId``` is not possible for larger PID counts. 

3) The LoopMessageSuccess feature of WriteJournal is not documented and maybe not working from user-space? 

Here is my current mirgation snipset from sql to eventstore.
Whats missing is:
-) To resume a migration without to query every PersistentId again. 
-) Not to read already copied events from the destination journal for the LastSeqNr.
-) Backpressure or failure the stream over WriteMessagesSuccess
-) Host the migration stream long lived, to sync/copy every old and NEW event in the background. 

```csharp
Logger.LogInformation("akka migrating");

            var readJournal = PersistenceQuery.Get(System)
                .ReadJournalFor<SqlReadJournal>("akka.persistence.query.journal.sql");

            Source<string, NotUsed> source = readJournal.CurrentPersistenceIds();

            var mat = ActorMaterializer.Create(System);

            var persistence = Persistence.Instance.Apply(System);

            var journal = persistence.JournalFor("akka.persistence.journal.eventstore");

            var destReadJournal = PersistenceQuery.Get(System)
                .ReadJournalFor<EventStoreReadJournal>("akka.persistence.query.journal.eventstore");

            var journalSink = Sink.ActorRef<WriteMessages>(journal, 
                new WriteMessages(Enumerable.Empty<IPersistentEnvelope>(), ActorRefs.Nobody, 0));

            await source
                .SelectAsync(1, async pid =>
                {
                    var env = await destReadJournal.CurrentEventsByPersistenceId(pid, 0, long.MaxValue)
                        .RunWith(Sink.LastOrDefault<EventEnvelope>(), mat);                        
                    return (PID: pid, MaxSeq: env is null ? 0L : env.SequenceNr);
                })
                .SelectAsync(1, async part =>
                {
                    await readJournal.CurrentEventsByPersistenceId(part.PID, part.MaxSeq, long.MaxValue)
                        .Select(n => new AtomicWrite(new Persistent(n.Event, n.SequenceNr, n.PersistenceId)))
                        .Grouped(100)
                        .Select(n => new WriteMessages(n, ActorRefs.Nobody, 0))
                        .AlsoTo(journalSink)
                        .RunWith(Sink.Ignore<WriteMessages>(), mat);
                    return part;
                })
                .RunForeach(part =>
                {
                    Logger.LogDebug($"akka migrate part {part} imported");
                }, mat);

            
            Logger.LogInformation("akka migrated");
```

**Comment by ismaelhamed** [comment]
Regarding resumable persistence queries: IMO, managing consumer offsets is an user-application implementation detail. For instance, we store the latest `ordering` or `sequenceNr` (depending on whether this is an `EventsByPersistenceId` or `EventsByTag` type of stream) for every stream and whenever an event is successfully processed.

**Comment by Zetanova** [comment]
@ismaelhamed  I didnt write about "resumable persistence queries" implementation inside Akka Core libery, i worte that there is no option to query the highest SeqNr without reading all events from user-space.

**Comment by Zetanova** [comment]
A query interface  with ```ReadJournal.AllEvents(offset)``` with constant ordering and a ```ReadJournal.LastestEvent()``` would be enough to migrate/copy everything from one journal to an other journal performant and resumable.

**Comment by Aaronontheweb** [comment]
The all events query solves much of this issue today. Do we still need something dedicated here?

**Comment by Zetanova** [comment]
Yes, the AllEvents and CurrentAllEvents got implemented after.
And i think its possible with them to migrate from one provider to the other.

An other problem for migration is that its currently not possible to migrate 
from and to the same Persistence Plugin Provider with to different connection settings

but I close this issue

**Comment by Aaronontheweb** [comment]
> An other problem for migration is that its currently not possible to migrate
> from and to the same Persistence Plugin Provider with to different connection settings

Yes, you currently need two different `ActorSystem` instances in the same process to do this - having done it before. Still something we can take a look at in the future if you want to keep this issue open.
