### ISSUE TITLE
 The type initializer for '<StartupCode$Library1>.$Library1' threw an exception.

### ISSUE THREAD

**Issue by louthy** [akkadotnet/akka.net#401]
Hi, I am trying to get Akka.net working for the first time on an existing web-application, all of the core web-app is in C#, the Akka related setup and computations are all F#.  I have built from the source today.

As soon as I hit System.create an exception is thrown in the serializer setup.

I decided to try this out in a console-app and everything worked fine.  But when I set-up a brand new web-app and invoke the same code (from Application_Start in Global.asax) I get the same error I got in my existing web-app.  So this seems to be related to web applications. but I'm not 100% sure where to start.

Below is a link with a test-repro.

https://www.dropbox.com/s/h861ev4m8glo05d/TestWebAkka.rar?dl=0

Exception

Method not found: 'Void Nessos.FsPickler.BinarySerializer..ctor(Microsoft.FSharp.Core.FSharpOption`1<Boolean>, Microsoft.FSharp.Core.FSharpOption`1<Nessos.FsPickler.ITypeNameConverter>)'. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.MissingMethodException: Method not found: 'Void Nessos.FsPickler.BinarySerializer..ctor(Microsoft.FSharp.Core.FSharpOption`1<Boolean>, Microsoft.FSharp.Core.FSharpOption`1<Nessos.FsPickler.ITypeNameConverter>)'.

Source Error: 

Line 210:    open Quotations.Patterns
Line 211:
Line 212:    type ExprSerializer(system) =
Line 213:        
Line 214:        inherit Serializer(system)

Source File:  
\Akka.FSharp\FsApi.fs    Line:  212 

Stack Trace: 

[MissingMethodException: Method not found: 'Void Nessos.FsPickler.BinarySerializer..ctor(Microsoft.FSharp.Core.FSharpOption`1<Boolean>, Microsoft.FSharp.Core.FSharpOption`1<Nessos.FsPickler.ITypeNameConverter>)'.]
   Akka.ExprSerializer..ctor(ExtendedActorSystem system) in \akka.net\src\core\Akka.FSharp\FsApi.fs:212
   Akka.System.create(String name, Config config) in \akka.net\src\core\Akka.FSharp\FsApi.fs:274
   <StartupCode$Library1>.$Library1..cctor() in \Library1\Library1.fs:8

[TypeInitializationException: The type initializer for '<StartupCode$Library1>.$Library1' threw an exception.]
   Library1.get_startActing() +31
   WebApplication1.Global.Application_Start(Object sender, EventArgs e) in \WebApplication1\Global.asax.cs:16

[HttpException (0x80004005): The type initializer for '<StartupCode$Library1>.$Library1' threw an exception.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +9905705
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): The type initializer for '<StartupCode$Library1>.$Library1' threw an exception.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9885060
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254

Setup:

Windows 8.1 64bit
IIS 8.5

**Comment by aprooks** [comment]
I'm having exactly same issue. Starting akka system within Owin context. 

here are the list of dependencies:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Akka" version="1.0.2" targetFramework="net45" />
  <package id="Akka.FSharp" version="1.0.2" targetFramework="net45" />
  <package id="FsPickler" version="0.9.11" targetFramework="net45" />
  <package id="FSPowerPack.Core.Community" version="3.0.0.0" targetFramework="net45" />
  <package id="FSPowerPack.Linq.Community" version="3.0.0.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR.Core" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.Owin" version="2.1.0" targetFramework="net45" />
  <package id="Microsoft.Owin.Security" version="2.1.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="6.0.4" targetFramework="net45" />
  <package id="Owin" version="1.0" targetFramework="net45" />
</packages>
```
code example

``` 
module myserver=

    let config = new HubConfiguration(EnableDetailedErrors = true)

    type MyWebStartup() =
            member x.Configuration(app:Owin.IAppBuilder) =                
                let system = System.create "my-system" (Configuration.defaultConfig()) 
                Owin.OwinExtensions.MapSignalR(app, "/signalr", config) |> ignore

    [<assembly: Microsoft.Owin.OwinStartup(typeof<MyWebStartup>)>]
    do()

```

**Comment by Aaronontheweb** [comment]
@aprooks saw someone report an issue with WebAPI too. I'll take a look at this starting on Monday.

**Comment by aprooks** [comment]
I am using  `ActorSystem.create` for now. Which is working fine. The exception is thrown somewhere from within expression serialization support https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.FSharp/FsApi.fs#L344

**Comment by kunjee17** [comment]
Any solution for this. I was trying to integrate with Servicestack and faced same issue. All code of actor is in library project. 

I also tried using `ActorSystem.create` but got same issue. 

Let me know if any further detail is required.

**Comment by kunjee17** [comment]
Is there any hard dependency on Json. net 7.0 version. Because things failed with error that it can't load that version.

**Comment by Horusiath** [comment]
@kunjee17 JSON.NET v7 is have to (mostly because of lack of good discriminated union compatibility in earlier versions). Additionally if you want to use readonly getters syntax from C# 6, you'll need JSON.NET v8 to correctly serialize them.

**Comment by kunjee17** [comment]
@horusiath thanks for quick reply. I have 8.0.2 version of Json.net. Still facing issue. Is it possible that AKKA is picking up from gac. F# interactive is picking up from azure installation.

**Comment by Horusiath** [comment]
@kunjee17 could you paste list of referenced dependencies? Crux of this issue was actually wrong version of FsPickler rather than Newtonsoft.Json.

**Comment by kunjee17** [comment]
1.7.2 version of fspickler. 
I think people seriously love Json. I have four dependency library just for that in single project. ^o^

**Comment by kunjee17** [comment]
@Horusiath Akkling will work? I tried but face some other issue.

**Comment by kunjee17** [comment]
Today I was trying to debug and it broke on system initialization only. I have created [sample project](https://github.com/kunjee17/SSAkkaFsharp) to reproduce error. 

PS: Error is typical Json .Net error. (At least google is showing that. Many entries in SO.) But I couldn't solve it. Any help would be appreciated.

**Comment by Horusiath** [comment]
@kunjee17 some of the akka code request for Newtonsoft.Json in version 7.0.1, while you've referenced that package in v8.0.2. This is standard case of referencing conflicting assemblies and it's not necessarily connected to akka. In that case assembly binding redirects may be necessary. Read this [SO thread](http://stackoverflow.com/questions/21498074/how-can-i-fix-assembly-version-conflicts-with-json-net-after-updating-nuget-pack).

**Comment by kunjee17** [comment]
@Horusiath I will check for both. Replacing VS Fsharp.core with nuget package and also assemblies redirect. And let you know. Thanks for reply. :)

**Comment by kunjee17** [comment]
@Horusiath you are rock star. Finally things work. I have to added assembly redirecting to C# Web wrapper project I was having for both Json.Net and Jspickler. Below is the code for future reference. 

In web config. 

```
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.4.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="8.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="FsPickler" publicKeyToken="null" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.21.0" newVersion="1.8.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime> 
```

PS: My actor code is in another library. C# web project is invoking that library but still I needed to add this redirect to make it work.
