### ISSUE TITLE
Typo in doc

### ISSUE THREAD

**Issue by ColinPM** [akkadotnet/akka.net#4044]
Page at https://getakka.net/articles/testing/multi-node-testing.html
Paragraph contains a spurious 't ':

... write tests **t** which validate your application's ability to correctly recover....

**Comment by Aaronontheweb** [comment]
@ColinPM thanks! I'll mark this issue as "up for grabs"

**Comment by KonH** [comment]
@Aaronontheweb 
Hello! That issue was already fixed in https://github.com/akkadotnet/akka.net/pull/4391, can you please close it?

**Comment by Aaronontheweb** [comment]
yessir!
