### ISSUE TITLE
Improve MNTR output readability

### ISSUE THREAD

**Issue by IgorFedchenko** [akkadotnet/akka.net#4059]
There are actually two points here: 
- make MNTR output simpler to use by other programmers, who are using nuget package
- make it simpler to review failure when debugging Azure Pipelines output for PR validation in Akka.NET

Right now, there is a nice [tool](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.MultiNodeTestRunner.Shared/Persistence/VisualizerPersistentTestRunStore.cs) that allows to review some basic information about test results on html page:
![image](https://user-images.githubusercontent.com/9683660/69457623-88c6ed00-0d7e-11ea-8b09-86b95d5aa62a.png)

This html file is generated near the folders with logs of each test/node.
There is no much details here, and when some of the tests are failing, you have to go into folder, open several text log files with parallel timelines and spend some time on it.
What would be nice is if we could get some aggregated logs with single timeline somewhere on the page above, so that we could easily review failed test logs here, maybe with some visualization of any critical places (i.e. logged exception might be displayed on the graph). Right now it seems like failed test is not showing it's timeline at all.

The second part of the improvement could be to add MNTR nodes logs into Azure Pipelines job output. So that even before downloading any of build artifacts you had a chance to make quick search there for some info. And, of course, would be nice to be able to see what assertion failed during multi-node test - right now we can only see the fact that some particular node failed:
![image](https://user-images.githubusercontent.com/9683660/69458186-ddb73300-0d7f-11ea-9281-c07610ed9e5e.png)

Maybe some other improvements could be done here?

**Comment by Aaronontheweb** [comment]
I'm happy with our progress here. I'll mark this as closed.
