### ISSUE TITLE
How to test actor that uses DistributedPubSub Mediator?

### ISSUE THREAD

**Issue by MichalKosowski** [akkadotnet/akka.net#4064]
Hi,

I am trying to write tests for my actors. We are using DistributePubSub feature in our project, so every actor has in the constructor:

`mediator = DistributedPubSub.Get(Context.System).Mediator;`

When I write test, I am getting NullReferenceException on this line, exactly as in old issue reported here on StackOverflow: https://stackoverflow.com/questions/41249465/how-to-test-distributedpubsub-with-the-testkit-in-akka-net

I tried to use suggestion in the above  post, but that leads to me to another exception:

> System.TypeLoadException: 'Method 'get_SerializationInformation' in type 'Akka.Remote.RemoteActorRefProvider' from assembly 'Akka.Remote, Version=1.3.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

Hmm any thoughts? Is that event possible? If not, any workarounds for this? 🤔

**Comment by Aaronontheweb** [comment]
> System.TypeLoadException: 'Method 'get_SerializationInformation' in type 'Akka.Remote.RemoteActorRefProvider' from assembly 'Akka.Remote, Version=1.3.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

You need to upgrade the version of Akka.NET you're using - since there are new API calls occurring past v1.3.6
