### ISSUE TITLE
DI in .net Core

### ISSUE THREAD

**Issue by atrauzzi** [akkadotnet/akka.net#4065]
I'm interested in ensuring my actors can make use of DI. I'm running in an .net Core project using the Microsoft-bundled DI system in .net Core.

I've read [the documentation](https://getakka.net/articles/actors/dependency-injection.html), although unfortunately I didn't find it helpful. Specifically: I'm not sure how I would go about implementing this interface. Are there any examples of implementing it for .net Core? ([I've also asked on gitter](https://gitter.im/akkadotnet/akka.net?at=5dd9e271f3ea522f2658695b), but no responses as of yet)

Would it not make sense to have a supporting nuget package that implements this interface for the MS DI system?  It seems like a very common use case with .net Core given that it ships with a DI abstraction.

**Comment by nagytech** [comment]
Sorry, @atrauzzi.  I did see your question on Gitter and I've been meaning to respond.  

You mentioned looking at the documentation, but did you follow the links to this page?https://getakka.net/articles/actors/di-core.html

If you're interested in implementing the interface, the di-core page walks through how to create a DI container provider using CastleWindsor as an example.  It should be similar to create one for netcore.

**Comment by atrauzzi** [comment]
Yeah, so I'm not sure if it's just how it's presented, but I don't find the docs helpful in giving me a clear idea of the lifecycle here.  Am I supposed to implement the resolver and then associate it with my `ActorSystem`? Or do I call it prior to providing actors to my `ActorSystem`?

Just to bump the 2nd part of my post, I really think it would be nice if there was an officially supplied implementation of the Microsoft DI based resolver. It's part of the platform and the contracts are intended to offer a way to abstract over other DI frameworks that wish to implement it.

Seems like a very safe bet!

**Comment by nagytech** [comment]
@atrauzzi  I've been able to work through the example linked previously and this is a starting point for discussion and further work.

https://github.com/nagytech/Akka.DI.DotNetCore

The main problem I encountered was that .NET Core DI doesn't supply a way for us to look up types by name after the provider is built.  So, I've had to create a custom IServiceCollection that tracks the registered types.

I'm not sure about the process for making this an officially supported library.  It definitely needs some unit test coverage and CI/CD attention.  In the meantime, feel free to use it as-is and provide some feedback on how it works for you.

**Comment by atrauzzi** [comment]
Thanks @nagytech!

What do you think about this person's approach: https://github.com/cecilphillip/Akka.DI.Microsoft/blob/master/src/Akka.DI.Microsoft/MicrosoftDependencyResolver.cs

**Comment by nagytech** [comment]
Good find.  Looks pretty similar except for the GetType issue I mentioned earlier.

**Comment by Aaronontheweb** [comment]
Resolved via https://getakka.net/articles/actors/dependency-injection.html#integrating-with-microsoftextensionsdependencyinjection
