### ISSUE TITLE
Akka.Cluster.Sharding

### ISSUE THREAD

**Issue by samuelfrancisco** [akkadotnet/akka.net#4074]
I am using Akka.Cluster.Sharding to model command handlers and event handlers at a CQRS application.

If two messages are sent to an actor in a shard region, while the actor is instantiated by the first message, the second message ends up being received before the first by the actor.

**Comment by Aaronontheweb** [comment]
I'm sorry, I'm not sure I understand the issue - are you saying that the actor processes the messages out of order? That's not really possible if it's the same actor as both messages have to pass through the same mailbox in FIFO order. If the two messages are sent to the same shard region _from different nodes_ then it's possible that those messages may be received out of your desired order - network latency and OS scheduling could cause that.

**Comment by samuelfrancisco** [comment]
There are two type of actors involved in the processes. The first one is a simple Receive Actor used to discover witch actor to send the message, based on message infos. This first actor instantiate the second Receiver Actor using an Shard Region, to guarantee that the Handler is unique at the cluster.
In a cluster may there many "Router" actors send messages to the same "Handler". The issue occurs in that scenery. When the "Handler" actor are being instantiated by a "Router" actor, a second "Router" actor sends a message to the same "Handler" actor, in the Cluster Region. The second message are being received first by the "Handler" actor. Apparently, the second message goes into the Actor queue first.

**Comment by Aaronontheweb** [comment]
Akka.Cluster.Sharding works by extracting a unique entity ID for each actor managed within a shard region - any messages that have the same entity ID extracted from them will all be sent the same single instance of an actor. You'll need separate entity IDs in order to have more than one type of handler actor.
