### ISSUE TITLE
Question. When using ClusteredPoolRouter, Why destroy the Routee as soon as it becomes Unwatch?

### ISSUE THREAD

**Issue by jiyeongj** [akkadotnet/akka.net#4078]
- Akka 1.3.15
- Windows 10

- Senario
   - Step 1.
      - Node1(Router): akka://ClusterLab@localhost:8091/user/FooActor/**c1**
      - Node2(Routee): akka.tcp://ClusterLab@localhost:8092/**remote**/akka.tcp/ClusterLab@localhost:8091/user/FooActor/**c1**
   - Step 2.
      - Node2 Crash
   - Step 3.
      - Node1(Router): akka://ClusterLab@localhost:8091/user/FooActor/  **<- c1 was destroyed. I don't understand it.**
      - cluster show  
         Node1 up  
         Node2 up **unreachable**  

I think c1 should still be alive until it's down, even if it's unreachable.

```
[DEBUG][2019-12-03 오전 8:31:03][Thread 0008][[akka://ClusterLab/system/remote-watcher#876657349]] 
  Unwatching: 
  [
     akka://ClusterLab/user/FooActor   
     ->  
     akka.tcp://ClusterLab@localhost:8092/remote
         /akka.tcp/ClusterLab@localhost:8091/user/FooActor/c1
  ]
```

<br/>
<br/>

- Node1
```
	actor {
		provider = "cluster"
		deployment {
			/FooActor {
				router = round-robin-pool
				nr-of-instances = 2

				cluster {
					enabled = on
                                        allow-local-routees = off
                                        use-role = Worker
                                        max-nr-of-instances-per-node = 1
				}
			}
		}
	}
```
- Node2
```
	actor {
		provider = "cluster"
	}
```

**Comment by Aaronontheweb** [comment]
This might be a bug - might be that we're using Akka.Remote failure detection rules on remotely deployed routees (in which case this behavior is intentional) instead of Akka.Cluster failure detection rules...

**Comment by nagytech** [comment]
From what I can see, the setting `allow-local-routees = off` on Node1 will prevent routees from running on Node1.  So, `c1` will only ever run on Node2.  And, when Node2 crashes, `c1` will be destroyed.

I'm almost certain that is the issue, but let me know if I have the wrong idea.

**Comment by Aaronontheweb** [comment]
Yep, that's correct.
