### ISSUE TITLE
SqliteSnapshotStore is not getting table name from config

### ISSUE THREAD

**Issue by maratoss** [akkadotnet/akka.net#4080]
- akka version 1.3.15
- windows 10
- table name in SqliteSnapshotStore is hardcoded and does not get the value from cinfig

i created the PR to show the problem and seems that is breaking changes
https://github.com/akkadotnet/akka.net/pull/4079

**Comment by Aaronontheweb** [comment]
Yep, sure looks like a bug. Thanks for reporting it and for sending a PR.
