### ISSUE TITLE
V1.0 Milestones

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#409]
So, me and @Aaronontheweb have been talking, we both want to see a somewhat
near future release of Akka.NET V1.0.

We know that there are a lot of features currently missing compared to JVM Akka.
e.g. Akka.IO, Akka.HTTP etc.

However, we think that those features are not mandatory for V1.0, they can be added in a later release.

So I'd like to know what you others think are "must have" features/issues to be fixed before V1?

My personal list:

* Documentation, both C# XML docs and WIKI pages that are up to date with the current API. 
* Better validation and exceptions, e.g. in some places we use Type.GetType(somestring) and don't validate if the result is what we expect.
* All standard mailboxes fully implemented + full mailbox configuration support and stashing handling
* Full dispatcher support, the `MessageDispatcher` class is currently not complete and lacks configuration, this is needed to for the mailbox support to be complete.
* Decide if a fluent config API should be supported or not, and if yes, implement it 
* Fix race conditions in `Inbox`

I've left out Akka.Remote and Akka.Cluster, others have better knowledge of what must be done there. cc @Aaronontheweb @smalldave and @akkadotnet/developers 

And Akka.TestKit cc. @HCanber

**Comment by nvivo** [comment]
As a new user of the library, I'm wondering what happened to 1.0 on Oct 31 at this point. Apart from the semver thing, did you decide what matters for the release?

**Comment by rogeralsing** [comment]
@nvivo life got in the way of that plan :-) all of us were a bit inactive from oct to dec, hollidays, christmas etc, nobody wants to write docs at those times.

We are taking care of those things now.
It is mostly the docs that needs to be done to go 1.0 on the core and remote libs.
