### ISSUE TITLE
Akka.Cluster.Sharding documentation - need to explain how to shut down entities when remember-entities=on

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4096]
Version: 1.3.16

When running an Akka.Cluster.Sharding setup with `storage-mode = persistence` and `remember-entities = on`, it turns out that it is impossible to permanently kill any entity actors even if this is the desired outcome.

I can send along a small reproduction example in short order, but the quick version: entity actors that terminate themselves via `Context.Stop` are always restarted by Akka.Cluster.Sharding within a few seconds and these actors are also automatically created when an Akka.Cluster.Sharding node recreates following a process restart of a singleton cluster.

**Comment by hwanders** [comment]
According to the comment on `RestartEntity` (`When an remembering entries and the entity stops without issuing a <see cref="Passivate"/>, we restart it after a back off using this message.`) this might be the desired behaviour.

Perhaps calling `Context.Stop` alone does not convey the desired intent of terminating the entity.
Adding a specific message (`Terminate` or something similar) would make the API clearer (it might cause the same behaviour as the `Passivate` message but perhaps there are other cleanup tasks involved). A little paragraph about terminating entities would be a nice addition to the docs.
For persisistent actors there are special steps involved anyway (I guess, manually deleting snapshots and the journal is required).

**Comment by ismaelhamed** [comment]
@hwanders is right. To permanently stop entities when `remember-entities` is enabled, use Passivate. Otherwise they will be recreated after a rebalance or restart.

**Comment by Aaronontheweb** [comment]
In that case, this is a really documentation issue.

**Comment by ismaelhamed** [comment]
To further clarify: this behavior should be the same whether the user chooses `persistence` or `ddata` as the `storage-mode`. Except that, according to this  https://github.com/akkadotnet/akka.net/pull/3199#issuecomment-354660858, the current Distributed Data implementation in Akka.NET doesn't support durable storage. It's worth checking whether this limitation still exists.

**Comment by Aaronontheweb** [comment]
I think the issue with DData has to do with its wire format, but @Horusiath would know for certain
