### ISSUE TITLE
Petabridge.cmd cluster tail logging time is different from our country time

### ISSUE THREAD

**Issue by kimbyungeun** [akkadotnet/akka.net#4098]
- Akka 1.13.16
- Windows 10

This is an additional question about the https://github.com/petabridge/petabridge.cmd-issues/issues/31

> we don't localize timezones at all in the logging system there. It's all done in UTC: https://github.com/akkadotnet/akka.net/blob/51ed45fbcef31c6012e5ffe612e9b0a4b9367fba/src/core/Akka/Event/LogEvent.cs#L51

**Petabridge.cmd** `cluster tail` log time and our country time are not the same. 

I understood.

However, **cluster** `heartbeatSender` time and our country time are the same.

Why is the `heartbeatSender time` and `Our country time` the same?

![image](https://user-images.githubusercontent.com/18045312/70873154-bf93ca00-1fef-11ea-912f-989eff5097c1.png)

@jiyeongj @hhko @seungyongshim

**Comment by Aaronontheweb** [comment]
> Why is the heartbeatSender time and Our country time the same?

That's a good question - these should be the same `LogEvent`s coming out of the log. The only difference would be the `ILogFormatter` at the very end that prints them to the `Console`. Are you using any custom loggers?

**Comment by kimbyungeun** [comment]
#### Thank you for the quick answer first.
* app.config nlog setting.
* There is no Timezone related setting.
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true" throwExceptions="false">
    <targets>
      <target name="ColoredConsoleTarget" 
			  xsi:type="ColoredConsole" 
			  layout="[${date:format=yyyy/MM/dd HH\:mm\:ss.fff}][${pad:padding=5:inner=${threadid}}][${pad:padding=5:inner=${level:uppercase=true}}]${event-context:item=logSource} ${message} ${exception:format=tostring}" />
      <target name="FileTarget" 
			  xsi:type="File" 
			  keepFileOpen="True" 
			  concurrentwrites="False" 
			  openFileCacheTimeout="30" 
			  filename="./log/app.log" 
			  archiveFileName="./log/backup/app.{##}.log" 
			  archiveEvery="Day" 
			  archiveAboveSize="1073741824" 
			  archiveNumbering="DateAndSequence" 
			  archiveDateFormat="yyyyMMdd_HHmmss" 
			  maxArchiveFiles="7" 
			  encoding="Unicode" 
			  layout="[${date:format=yyyy/MM/dd HH\:mm\:ss.fff}][${pad:padding=5:inner=${threadid}}][${pad:padding=5:inner=${level:uppercase=true}}]${event-context:item=logSource} ${message} ${exception:format=tostring}" />
    </targets>
    <rules>
      <logger name="*" minLevel="Debug" appendTo="FileTarget" />
      <logger name="*" minLevel="Trace" appendTo="ColoredConsoleTarget" />
    </rules>
  </nlog>
```
