### ISSUE TITLE
Small documentation error

### ISSUE THREAD

**Issue by peheje** [akkadotnet/akka.net#4116]
In https://getakka.net/articles/intro/tutorial-3.html

After you PoisonPill an actor, should you not unit test that it is in fact not present? 

`!s.Ids.Contains("device1")`

```
  // using awaitAssert to retry because it might take longer for the groupActor
    // to see the Terminated, that order is undefined
    probe.AwaitAssert(() =>
    {
        groupActor.Tell(new RequestDeviceList(requestId: 1), probe.Ref);
        probe.ExpectMsg<ReplyDeviceList>(s => s.RequestId == 1 && s.Ids.Contains("device2"));
    });

```

**Comment by F0b0s** [comment]
@Aaronontheweb it can be closed because [Tutorial improvements #6057](https://github.com/akkadotnet/akka.net/pull/6057) fixed it.
