### ISSUE TITLE
Support double wildcards in actor deployment config

### ISSUE THREAD

**Issue by stijnherreman** [akkadotnet/akka.net#4136]
Akka supports double wildcards in the actor deployment configuration. This is documented [here](https://doc.akka.io/docs/akka/2.5.4/scala/general/configuration.html#actor-deployment-configuration) (it's missing in the current docs):

> you can use double-wildcards in the last position to match all child actors and their children recursively: `/someParent/**`

The relevant PR for this feature is https://github.com/akka/akka/pull/20525. See https://github.com/akka/akka/blob/6278968af56f36b8ff3fd4a0a443e5218bceb838/akka-actor/src/main/scala/akka/util/WildcardIndex.scala for current version of this file.

It would be great to have this available in Akka.NET too. This will allow simplifying configuration from
```
"/foo/*" {
	dispatcher = bar
}
"/foo/*/*" {
	dispatcher = bar
}
"/foo/*/*/*" {
	dispatcher = bar
}
```
to
```
"/foo/**" {
	dispatcher = bar
}
```

**Comment by Aaronontheweb** [comment]
This will be released as part of Akka.NET v1.4.11
