### ISSUE TITLE
Cluster Sharding Entity Actor Path

### ISSUE THREAD

**Issue by yesh-nadella** [akkadotnet/akka.net#4161]
This [documentation ](https://github.com/akkadotnet/akka.net/blob/dev/docs/articles/clustering/cluster-sharding.md/#integrating-cluster-sharding-with-persistent-actors) says that "For each entity actor path will follow /user/{typeName}/{shardId}/{entityId} pattern". However, when I was looking at the actor path for a cluster sharding entity actor, the actor is under the system actor, not the user actor. The path I see is /system/{guardianName}/{shardName}/{shardId}/{entityId}. 

Is this a typo in the documentation or am I not understanding it correctly? 

Version

- Akka 1.3.4
- Akka.Cluster 1.3.4
- Akka.Cluster.Sharding 1.3.2-beta54

Running Akka.Net on windows platform

**Comment by Aaronontheweb** [comment]
@yesh-nadella yes, that's a typo in the documentation. I'll fix it.
