### ISSUE TITLE
Reduce Public API Surface

### ISSUE THREAD

**Issue by cptjazz** [akkadotnet/akka.net#4223]
At the moment there are several "helper" types (especially in namespaces ending in `.Internal`) and implementations of interfaces that are `public` but should rather be `internal`. Sometimes this fact is communicated in the XML comments, e. g. "internal API, use at own risk."

In a matter of increasing maintainability and allow for more freedom in changing internal implementations I propose to reduce the public surface of the library, i. e. make more types `internal`. 

Ironically, at this point, the proposed goal can only be reached by introducing breaking changes and making the mentioned types internal.
This greatly depends on the release strategies that are planned. Is the upcoming 1.4.x already introducing many breaking changes? Then I would propose to gradually start internalizing helper types too.
Is it non-breaking? Then I would recommend marking internal types with the `ObsoleteAttribute` to communicate to users that in e. g. 1.5.x or later those types will go out of order.

What is you opinion on this topic?
I would volunteer to do a few PRs depending on the decided strategy.

**Comment by sean-gilliam** [comment]
This is a topic that comes up every few years. Often waffling between how open and extensible we should make Akka.NET. It was decided a while back that we shouldn't really hamper the user if they truly have a need to extend our framework with the express notion that these apis have no guarantees.  So we moved all our internal apis to the Internal namespace or mark them as [InternalApi] and added the warning to the documentation.

Correct me if I'm wrong  @akkadotnet/contributors @akkadotnet/core

**Comment by cptjazz** [comment]
You have a point in that, regarding the building blocks of this framework itself. But what about all the "helpful" extension methods for string manipulation or collections, e. g. in `Akka/Util/Internal/`? I don't think those should be public because it is not the intent of this library to ship helpful string functions.
Those methods show up on IntelliSense and might be accidentally used by people.

**Comment by Aaronontheweb** [comment]
> But what about all the "helpful" extension methods for string manipulation or collections, e. g. in Akka/Util/Internal/? I don't think those should be public because it is not the intent of this library to ship helpful string functions.

We can get rid of that stuff from the public API as far as I'm concerned.

**Comment by cptjazz** [comment]
@Aaronontheweb, if I were to add PRs in the next weeks, would you like to phase those types out over the next versions (`[Obsolete]` them), or just make them internal directly?

I'll give this topic a few more days of discussion before I do any PRs.

**Comment by Aaronontheweb** [comment]
as we're a couple weeks away from releasing v1.4.0 - I'd go ahead and just change some of them to `internal` right away if you can get them in quickly. Otherwise, they'll have to be marked as obsolete and then made `internal` in v1.5.0.

**Comment by Aaronontheweb** [comment]
@cptjazz any additional PRs to make here? Merged the other two.

**Comment by cptjazz** [comment]
Question for me here is, what's the direction to go for non-helper types that define the basic Akka framework? 
Keep only interfaces and contract-like abstract base classes public and internalize more implementations or go with what @sean-gilliam said and have implementations publicly accessible?
I for one would go with the first option, providing public contracts and mechanisms and keep implementations internal. 

For example for the descendants of `ICancelable` could be easily made internal without preventing users to supply their own implementations, same for `IChildrenContainer`, *etc.*

Depending on this fundamental design decision I'll either close this issue or try to create another PR in the next days.

**Comment by Aaronontheweb** [comment]
@cptjazz so stuff that is essential to Akka.NET, we should do what @sean-gilliam said: leave it public but mark it with the `[InternalApi]` attribute if needed. For instance, if we made it so `IActorRefProvider` was totally `internal` we wouldn't be able to extend Akka.NET with tools like [Phobos](https://phobos.petabridge.com/).

The stuff that should be pruned should be extension methods that aren't used or target things beyond the scope of Akka.NET itself.

**Comment by Aaronontheweb** [comment]
For the time being, we're going to move forward with these changes as-is. Have to get 1.4.0 out the door.
