### ISSUE TITLE
Akka.NET v1.4.0 backwards compat: HOCON API

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4232]
Version: 1.4.0

Bit of a critical issue here - in order for us to maintain backwards compatibility with earlier versions of Akka.NET, we'll need to take some of the classes we've removed / changed:

* [  ] `Akka.Configuration.Config`
* [  ] `Akka.Configuration.ConfigurationFactory`

and alias them on top of the new stand-alone HOCON equivalent types. Otherwise, just about every third party Akka.NET plugin and application will break and not be binary compatible upon upgrading to Akka.NET v1.4.0.

There are two approaches for solving this issue:

1. Say "screw it" and let people take the brunt of upgrading their plugins;
2. Rename all of the `HOCON` primitivites so the class names don't clash with the ones included in Akka.NET already, add facade classes in Akka.NET that match the original types, and keep the Akka.NET API surface area targeted the new HOCON primitives still - since the facades can be safely downcast back into them.

Funnily enough, I just submitted a PR to HOCON that undid this type of change that @Arkatufus was trying to implement https://github.com/akkadotnet/HOCON/pull/228 - that's what made me realize what he might have been trying to do (my bad.) So we need to pick a strategy. Naturally, I pick number 2 - backwards compatibility won't cost us much and there's no one really using HOCON 2.0 yet, so I think we can afford to iterate on the API one more time there.

cc @akkadotnet/core @akkadotnet/contributors

**Comment by Arkatufus** [comment]
I'm all for solution 2 myself.
The problem with `ConfigurationFactory` is that its a static class. You can't inherit it, and there is no safe and clean way to make a facade of it.

What backward compatibility problem do you see in the `Config` class? Is it the new behavior where it throws when a node path is not found?

**Comment by Aaronontheweb** [comment]
The biggest issue is that the Config object used to live under the Akka.Configuration namespace, but now it's part of the Hocon namespace - and so any piece of 1.3.* and earlier Akka.NET code that worked with HOCON directly will have to be updated. In addition, the signature for things like ActorSystem.Create will be different now as it'll require a different type.

One thing we could do is attempt to subclass Hocon.Config with Akka.Configuration.Config and change all of the API calls accordingly - I'm not sure how messy that would get though.

**Comment by cptjazz** [comment]
Not sure, but this sounds as if type forwarding could help here? 
https://docs.microsoft.com/en-us/dotnet/standard/assembly/type-forwarding

**Comment by Aaronontheweb** [comment]
That's an amazing suggestion - didn't even know that was an option.

**Comment by Aaronontheweb** [comment]
This definitely should have helped: https://github.com/akkadotnet/akka.net/pull/4248

**Comment by Aaronontheweb** [comment]
This is not going to be possible, after doing some experimentation here.

Users are going to need to change `Akka.Configuration.Config` to `Hocon.Config` inside their applications. As part of the Akka.NET v1.4.0 rollout, we'll include a migration guide for this.

Ultimately this is the lesser of two evils - we can get creative with shading the `Hocon.Config` class with an `Akka.Configuration.Config` wrapper (just tried this) but that introduces a number of other internal problems from within Akka.NET and doesn't necessarily guarantee that the user will have binary compatibility, given that the signatures, extension methods, and exception types are still different.

Judgement call is that the end-user changes are simpler than trying to get clever behind the scenes, and simple is better.
