### ISSUE TITLE
Akka.net Stashing missing messages of same type

### ISSUE THREAD

**Issue by zhygis** [akkadotnet/akka.net#4245]
Akka.net 1.3.17
Framework dotNetCore 3.1

The  problem, that I am facing with, happens between 3 actors as follows: 
Coordinator actor tells a messages of the same type in the loop (3 messages in total):
```
 var req = new AddNewFinancialClusterRequest(command.Context, command.UserContext,
                    EntityId.From(actionResult.Id), actionResult.Data);
Context.ActorSelection(ActorPaths.NewFinancialClusterActor.Path).Tell(req);
```
Then NewFinancialClusterActor is initially in Ready() state and receives first message, that is OK, and transfers itself to Working state.
Then Coordinator actor sends second AddNewFinancialClusterRequest message it received and Stash.Stash() called.
Then Third actor FinancialClusterActor sends response to NewFinancialClusterActor 
 ` Context.ActorSelection(ActorPaths.NewFinancialClusterActor.Path).Tell(resp); `
Response is received this is OK NewFinancialClusterActor becomes Ready again and unstashes all messages of type AddNewFinancialClusterRequest
Coordinator actor tells last message, which is not received by NewFinancialClusterActor 
Unstashed messages AddNewFinancialClusterRequest are not received when NewFinancialClusterActor is in Ready state.
```
public class NewFinancialClusterActor : ReceiveActorBase<NewFinancialClusterActor>, IWithUnboundedStash
    {
        public NewFinancialClusterActor(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            SetReceiveTimeout(TimeSpan.FromMinutes(1));
            Ready();
        }

        public IStash Stash { get; set; }

        private void Ready()
        {
            Receive<AddNewFinancialClusterRequest>(req =>
            {
//tells to the actors request, that finally send response of type ResponseMessage<FinancialClusterData> back to this actor to notify of  finish work.
               Context.ActorSelection(ActorPaths.FinancialPlanCoordinatorActor.Path).Tell(req);
                Become(Working);

            });
        }

        private void Working()
        {

            Receive<AddNewFinancialClusterRequest>(o =>
            {
                Logger.LogWarning($"Stashing message with DefaultFinancialClusterId: {o.DefaultFinancialClusterId}");
                Stash.Stash();
            });

            Receive<ResponseMessage<FinancialClusterData>>(resp =>
            {
                Logger.LogWarning($"Received from financial plan with id {resp.Data.SourceId.Value}");
                Become(BecomeReady);
              


            });            
        }

        private void BecomeReady()
        {
            Stash.UnstashAll();
            Become(Ready);
        }


    }
```
as mentioned above Coordinator actor tells 3 messages to NewFinancialClusterActor
```
var req = new AddNewFinancialClusterRequest(command.Context, command.UserContext,
                    EntityId.From(actionResult.Id), actionResult.Data);
Context.ActorSelection(ActorPaths.NewFinancialClusterActor.Path).Tell(req);

```
To conclude, I have received only first one message and received response from the FinancialClusterActor
to notify that work is done and it can be become working again than, after that nothing happened.
The whole concept is taken [from:](https://petabridge.com/blog/top-7-akkadotnet-stumbling-blocks/) 
paragraph: 4. Executing long-running actions inside an actor’s Receive method
I need to process all 3 messages one by one, once FinancialClusterActor notifies NewFinancialClusterActor, that it can become ready again and take next message from the queue, that Coordinator actor has sent before.

**Comment by zhygis** [comment]
Made it work a bit changed the code,
```
 public class NewFinancialClusterActor : ReceiveActorBase<NewFinancialClusterActor>, IWithUnboundedStash
    {
        public NewFinancialClusterActor(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            SetReceiveTimeout(TimeSpan.FromMinutes(1));
            Become(Ready);
        }

        public IStash Stash { get; set; }

        private HashSet<long> _awaitingPlans;

        private void Ready()
        {
            Receive<AddNewFinancialClusterRequest>(req =>
            {

                Logger.LogWarning($"Received message with default cluster id {req.DefaultFinancialClusterId.Value}");
                using (var scope = CreateScope())
                {
                    var unitOfWork = scope.ServiceProvider.GetService<IUnitOfWork>();
                    var planRepo = scope.ServiceProvider.GetService<IFinancialPlanRepository>();
                    using (unitOfWork)
                    {
                        unitOfWork.BeginNoTransaction();
                        var plans = planRepo.GetAll().Result.Where(x => x.WorkflowStatusId != WorkflowStatus.Approved.Id).Select(x=>x.Id.Value);
                        _awaitingPlans = new HashSet<long>(plans);
                        unitOfWork.End();
                    }
                }

                Context.ActorSelection(ActorPaths.FinancialPlanCoordinatorActor.Path).Tell(req);
                Become(Working);

            });
        }

        private void Working()
        {
            Receive<AddNewFinancialClusterRequest>(o =>
            {
                Logger.LogWarning($"Stashing message with DefaultFinancialClusterId: {o.DefaultFinancialClusterId}");
                Stash.Stash();
            });

            Receive<ResponseMessage<FinancialClusterCreatedResponse>>(resp =>
            {
                Logger.LogWarning($"Received from financial plan with id {resp.Data.FinancialPlanId} and SourceId {resp.Data.SourceId}");
                _awaitingPlans.Remove(resp.Data.FinancialPlanId);

                if (!_awaitingPlans.Any())
                {
                    Stash.UnstashAll();
                    Become(Ready);
                }

            });

            Receive<ReceiveTimeout>(e =>
            {
                Logger.LogWarning($"Receive timeout prior to receive that confirmation from the Financial plan that actor have been added");
                Logger.LogWarning($"Remaining financial plans, that financial cluster is not created: {string.Join(",", _awaitingPlans)}");
            });
        }


        //private void BecomeReady()
        //{
        //    Stash.UnstashAll();
        //    Become(Ready);
        //}


    }
```
The only thing that I changed, is usded Become(Ready) directly in the message handler, and same made to in the constructor.

**Comment by Aaronontheweb** [comment]
The type of error you're describing is not possible with the Stash - the stash _is_ programmed to avoid stashing duplicate messages, but it does this based on an identifier used by the ActorCell which gets incremented on a per-message basis:

https://github.com/akkadotnet/akka.net/blob/6293948ef086b0ed58ddf1ebc4c0a02291ae1f89/src/core/Akka/Actor/ActorCell.DefaultMessages.cs#L65-L66

https://github.com/akkadotnet/akka.net/blob/6293948ef086b0ed58ddf1ebc4c0a02291ae1f89/src/core/Akka/Actor/Stash/Internal/AbstractStash.cs#L72-L76

You will get an exception if this occurs.

This looks to me more like an issue with the way your actor messaging flow is designed - for instance, if you get a response while you're in the `Working` state then you don't handle the message and the flow will break, and in addition to that you're not handling the `ReceiveTimeout` message you'll receive given the `SetReceiveTimeout(TimeSpan.FromMinutes(1));`

It's very unlikely this is an issue with our framework given that this is a very common use case for stashing.

**Comment by Aaronontheweb** [comment]
Oh good! I didn't see your comment earlier as I was still in the midst of writing mine - glad you figured it out.
