### ISSUE TITLE
"The given key was not present in the dictionary" exception

### ISSUE THREAD

**Issue by dnickless** [akkadotnet/akka.net#4246]
Here's one more worrying log message from our client's production environment (Akka.NET 1.3.15, DotNetty 0.6.0):

`2020-02-23 22:11:14.4501		Error	Calculation	[ERROR][2/23/2020 6:11:14 PM][Thread 0025][akka://xxx/system/endpointManager/endpointWriter-akka.tcp%3A%2F%2F361e3abc-703b-4b94-a3f3-99c4a79a4e6e%40yyy.xxx.com%3A56064-391/endpointReader-akka.tcp%3A%2F%2F361e3abc-703b-4b94-a3f3-99c4a79a4e6e%40yyy.xxx.com%3A56064-1] The given key was not present in the dictionary.
Cause: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary'2.get_Item(TKey key)
   at Akka.Remote.EndpointReader.UpdateSavedState(Link key, ResendState expectedState)
   at Akka.Remote.EndpointReader.SaveState()
   at Akka.Actor.ActorCell.FinishTerminate()
`

A concurrency issue somewhere? `TryGet` might solve the issue but who knows what this really means...

**Comment by Aaronontheweb** [comment]
https://github.com/akkadotnet/akka.net/blob/6293948ef086b0ed58ddf1ebc4c0a02291ae1f89/src/core/Akka.Remote/Endpoint.cs#L1996-L2009

Looks like it happens on the `[key]` operation here on the `ConcurrentDictionary` - I'll take a look at refactoring that code. Looks like an unhandled case with the compare and swap recursion we use there.

**Comment by Aaronontheweb** [comment]
included this into Akka.NET v1.3.18: https://github.com/akkadotnet/akka.net/releases/tag/1.3.18

**Comment by dnickless** [comment]
Thanks, @Aaronontheweb, extremely appreciated - that thing *just* made it into our patch release. Happy clients, happy me! ;)
