### ISSUE TITLE
Add HOCON environment variable substitution example for Akka.Remote / Akka.Cluster bootstrapping

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4278]

**Comment by ismaelhamed** [comment]
You need the stand-alone HOCON library for this, right? I mean, there's no way to make this work right now, or is it?

**Comment by Aaronontheweb** [comment]
Yes, that's correct.

**Comment by Aaronontheweb** [comment]
I think we're going to drop this from the v1.5 milestone. Akka.Hosting has largely eliminated the need for this.

**Comment by Aaronontheweb** [comment]
No longer needed due to https://github.com/akkadotnet/Akka.Hosting
