### ISSUE TITLE
Serialization of HOCON config runs in a StackOverflowException

### ISSUE THREAD

**Issue by robinkah23** [akkadotnet/akka.net#4300]
As already mentioned in https://github.com/akkadotnet/Hyperion/issues/169 we are not able to serialize the app.hocon configuration with Akka.Cluster 1.4.1-rc1 and Hyperion 0.9.15 in .Net Core 3.1. Attachted you can find an example, which runs in a StackOverflowException. Is there a workaround? 

[HyperionStackOverflow.zip](https://github.com/akkadotnet/akka.net/files/4297759/HyperionStackOverflow.zip)

The critical code is

        static void Main(string[] args)
        {
            var hocon = HoconConfigurationFactory.Default();
            var serializer = new Serializer();
            using (var file = File.Create("foo.bin"))
            {
                // Here: StackOverflowException
                serializer.Serialize(hocon, file);
                file.Flush();
            }

            var deserializer = new Serializer();
            using (var file = File.Open("foo.bin", FileMode.Open))
            {
                var restored = deserializer.Deserialize<Config>(file);
                Console.ReadLine();
            }
        }

**Comment by Aaronontheweb** [comment]
Thanks - this will be fixed shortly. We're rolling back the stand-alone HOCON changes.

**Comment by Aaronontheweb** [comment]
Resolved via https://github.com/akkadotnet/akka.net/pull/4299

**Comment by robinkah23** [comment]
Thanks!
