### ISSUE TITLE
The RemotePingPong benchmark of Akka 1.4.1 is slower than Akka 1.3.16

### ISSUE THREAD

**Issue by ShawnYun** [akkadotnet/akka.net#4329]
- Akka.Net version : Akka 1.4.1 and Akka 1.3.16
- On which platform you are using Akka.Net : Windows 10 x64
- Question :
    I run the RemotePingPong benchmark test of Akka 1.4.1 and Akka 1.3.16. Then the result is below:
    You can see that 1.3.16 performs better than 1.4.1. This confused me because I saw that 1.4.1 was 
    optimized for DotNetty TCP Transport.

    **The figure above is 1.3.16 and the figure below is 1.4.1.**
![Akka1.3.16](https://user-images.githubusercontent.com/42930111/76500614-cd84aa00-647b-11ea-871e-c72f6e6d62d6.png)
![Akka1.4.1](https://user-images.githubusercontent.com/42930111/76500846-4126b700-647c-11ea-843c-39152ed7bf6b.png)

**Comment by Aaronontheweb** [comment]
We explain the details about the new batching system here https://getakka.net/articles/remoting/performance.html

**First round of the RemotePingPong benchmark falls below the default batching threshold of 30 msg / batch and will always fall below it.** For real-world use cases where message traffic is really that low, you should do what the article suggests and disable batching.

On my hardware, I consistently get 174,000 msg / s per connection on Akka.Remote using the default settings on rounds 2-6 of the benchmark. Your mileage may vary - looks like on your hardware the I/O batching doesn't make much of a difference. The reasons why that might be: different OS, different hardware, different runtime version (all of our benchmarks target .NET Core 3.1.)

You can disable the batching system in its entirety through configuration; the link I included earlier will show you how.

**Comment by Aaronontheweb** [comment]
I also took the liberty of producing a YouTube video today to help explain this in more detail:

https://www.youtube.com/watch?v=mP3amXEntmQ&feature=youtu.be

**Comment by Tommo-L** [comment]
I also run the benchmark in my local env. It seems v1.3.16 is better than v1.4.1

v1.3.15 benchmark code: https://github.com/akkadotnet/akka.net/releases/tag/1.3.16
v1.4.1 benchmark code: https://github.com/akkadotnet/akka.net/tree/dev/src/benchmark/RemotePingPong

Results:

Case1:
![image](https://user-images.githubusercontent.com/43396869/76728500-d59d5c00-6791-11ea-8f92-91656eee79db.png)

![image](https://user-images.githubusercontent.com/43396869/76729020-219cd080-6793-11ea-8747-2fcf8c07f09c.png)


Case2:
![image](https://user-images.githubusercontent.com/43396869/76728520-e1891e00-6791-11ea-97ee-302f10c32ab9.png)

![image](https://user-images.githubusercontent.com/43396869/76731903-662b6a80-6799-11ea-9cba-e515ac3d2f19.png)

**Comment by Tommo-L** [comment]
Sorry, mistake for v1.3.16 config. v1.4.1 is a little better than v1.3.16.
