### ISSUE TITLE
App.config loading broken in Akka.NET v1.4.1

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4330]
This is broken in the latest release of Akka.Net 1.4.1.  Please reopen this issue.   It is no longer automatically loading the akka section in the app.config file.  Reverting back to 1.3.18 works fine.

_Originally posted by @ejohn54 in https://github.com/akkadotnet/akka.net/issues/671#issuecomment-598302342_

**Comment by ejohn54** [comment]
It looks like commit c19b2d01 changed the method ActorSystem.Create(string name) to use 
`return CreateAndStartSystem(name, ConfigurationFactory.Default());`

where before it used
`return CreateAndStartSystem(name, ConfigurationFactory.Load());`

The ConfigurationFactory.Default() uses the "Akka.Configuration.Pigeon.conf" resource, where .Load() loads it from app.config or web.config
