### ISSUE TITLE
The release main page and each version page have a different format.

### ISSUE THREAD

**Issue by kimbyungeun** [akkadotnet/akka.net#4338]
The release main page and each version page have a different format.
It seems different than before, but is it intended?

####  **Release main page : akka.net v1.4.2**
* https://github.com/akkadotnet/akka.net/releases
#### **Each version page : Akka.NET v1.4.1**
* https://github.com/akkadotnet/akka.net/releases/tag/1.4.1

![image](https://user-images.githubusercontent.com/18045312/76595654-8cee6480-653f-11ea-912a-43fe7a2cec94.png)

![image](https://user-images.githubusercontent.com/18045312/76595984-6bda4380-6540-11ea-9d6d-d427ff2c7b08.png)

**Comment by Aaronontheweb** [comment]
Yeah, sorry about that - I had to go and edit the capitalization afterwards. Azure DevOps uses the name of the repository by default which is all lower case.
