### ISSUE TITLE
No connection string for Sql Event Journal was specified

### ISSUE THREAD

**Issue by ismaelhamed** [akkadotnet/akka.net#4343]
**Akka**: 1.4.2 (but might be affecting more versions)

Looks like the preprocessor directive `CONFIGURATION` is not defined for NETStandard, which in this case is preventing from loading the `connection-string-name` from configuration.

https://github.com/akkadotnet/akka.net/blob/345c601a0d0263aa3ba0e069af2f9188d1261ece/src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs#L258

**Comment by Aaronontheweb** [comment]
thanks for reporting this are you planning on submitting a PR? If so, we'll do a new 1.4.3 release ASAP.

**Comment by ismaelhamed** [comment]
Maybe there's more to it than I anticipated. 

If I'm not mistaken, the following code will only retrieve the `connetionString` from an `app.config`, but what if this was an ASP.NET Core using an `appsettings.json`? Wouldn't we need to use `Microsoft.Extensions.Configuration` instead in that case?

https://github.com/akkadotnet/akka.net/blob/345c601a0d0263aa3ba0e069af2f9188d1261ece/src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs#L258-L265

**Comment by Arkatufus** [comment]
The `CONFIGURATION` compiler directive is `App.config` specific, `Microsoft.Extensions.Configuration` support is on the development road map, but it won't be implemented just yet.
