### ISSUE TITLE
Resolve Mailboxes

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#436]
The implementation in `Mailboxes.GetMailboxType` is lacking.
The scala code does much more to ensure the correct mailbox is resolved.

In order to do this correctly, we also need to add dispatcher configuration support.

Related to #429

**Comment by rogeralsing** [comment]
#611 #452

**Comment by rogeralsing** [comment]
We need to throw some love at the message queues.
We now have `BoundedMessageQueue`, but we need some enhancement and refactoring to the whole message queue infrastructure.
The BoundedMessageQueue needs to be able to be injected with a ref to `DeadLetters`

**Comment by Aaronontheweb** [comment]
@rogeralsing don't want to bother you while you're on vacation, but should this be part of the scope for V1? Kind of sounds like it.

**Comment by irperez** [comment]
This was a blocking issue for #453 when I took a look.

**Comment by Aaronontheweb** [comment]
@cconstantin didn't you implement this recently?

**Comment by cconstantin** [comment]
@Aaronontheweb I did add the dispatcher configuration support. There are still some differences in how we configure and instantiate mailboxes, it's worth a closer look I think.

**Comment by Aaronontheweb** [comment]
Implemented this in 1.1.
