### ISSUE TITLE
No `DeferAsync`  method in FSharp Persistence API

### ISSUE THREAD

**Issue by fluxlife** [akkadotnet/akka.net#4396]
When creating a new issue, please make sure the following information is part of your issue description. (if applicable). Thank You!

- Which Akka.Net version you are using
- On which platform you are using Akka.Net
- A list of steps to reproduce the issue. Or an gist or github repo which can be easily used to reproduce your case.

Akka.Net Version: 1.4.4
Platform: Net Core 3.1 / FSharp

Currently the F# Persistent Actor API does not expose the C# Persistent Actor method `DeferAsync`. 

Requesting it be added to the FSharp Persistent API 

PR: #4395

**Comment by Aaronontheweb** [comment]
Closed via #4395
