### ISSUE TITLE
Akka.DistributedData.ORDictionary Unable to cast object of type

### ISSUE THREAD

**Issue by huzaifak** [akkadotnet/akka.net#4400]
Which Akka.Net version you are using
1.4.5

- On which platform you are using Akka.Net
.Net 4.7

Akka logs are producing the below error with the latest release of akka, and no ddata is being replicated to any other node in the cluster.

We use akka clustering with multiple nodes and a singleton, singleton makes most of the changes to the ddata.

Akka.Actor.OneForOneStrategy Unable to cast object of type 'Akka.DistributedData.ORDictionary`2[System.ValueTuple`2[System.Guid,System.UInt16],Akka.DistributedData.LWWRegister`1[Ouroboros.IStreamSessionPayloadProgress]]' to type 'Akka.DistributedData.LWWDictionary`2[System.ValueTuple`2[System.Guid,System.UInt16],Ouroboros.IStreamSessionPayloadProgress]'.

**Comment by Aaronontheweb** [comment]
So looks like this is an issue with `LWWDictionary` - right?

**Comment by huzaifak** [comment]
yes for this one we are using LWWDictionaryRegistry.
