### ISSUE TITLE
Add ReadMajorityPlus consistency to DistributedData

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/akka.net#4415]
Port ReadMajorityPlus consistency from scala Akka to Akka.NET and the required serialize/deserialize code.
The required Protobuff wire format is already added in #4414

https://github.com/akka/akka/blob/master/akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala#L439-L444
https://github.com/akka/akka/blob/master/akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatorMessageSerializer.scala#L342-L390

**Comment by zbynek001** [comment]
i think this is done in #5146

**Comment by Aaronontheweb** [comment]
Correct!
