### ISSUE TITLE
Suppress warning CS1591 Missing XML comment for publicly visible type or member?

### ISSUE THREAD

**Issue by HCanber** [akkadotnet/akka.net#442]
We have 1800+ warnings. Most of them are [CS1591 Missing XML comment for publicly visible type or member](http://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=EN-US&k=k%28CS1591%29;k%28TargetFrameworkMoniker-.NETFramework,Version%3Dv4.5%29&rd=true) .
I think we might risk missing important, valuable warnings, so I think we should suppress CS1591. Agree?

**Comment by sean-gilliam** [comment]
We've added a ton of documentation since this issue was raised. I feel confident about leaving those warnings in place.
