### ISSUE TITLE
Async Await in Untyped Actor

### ISSUE THREAD

**Issue by niku2907** [akkadotnet/akka.net#4420]
I m using Akka.Net 1.4.1 in Windows 10 environment. 
I m using async await tasks within Untyped actor and so far have not run into any issues. As expected, only the current message is processed until await for a task is completed within the OnReceive method. 
However, I could not find this as a documented behavior. All the posts talk about using ReceiveAsync to have this behavior. 
Could you confirm the behavior of using Async/Await inside OnReceive method of Untyped Actors?

**Comment by Aaronontheweb** [comment]
StackOverFlow is the appropriate place for this question and I see you asked already there: https://stackoverflow.com/questions/61885050/akka-net-async-await-behavior-in-untyped-actor - the answer that was given appears to be correct.
