### ISSUE TITLE
Document and include examples of how to use ActorSystemSetup

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4433]
Version: 1.4.7 and later

Need to document how to use `ActorSystemSetup` implemented in https://github.com/akkadotnet/akka.net/issues/4426 - I'm using it myself right now in a private alpha build of Akka.NET and this feature _rocks_. We can totally rewrite the DI system to be immutable using it, among other things. Lots of great potential between now and into the future.

What I'd recommend doing:

1. [ ] Document programmatic configuration of serializers and serialization bindings using `SerializationSetup`
2. [ ] Document creation of `ActorSystemSetup` and its use in bootstrapping `Config` inside the `ActorSystem`

As an optional approach: document how to use the `Setup` class to pass in programmatic configuration for `ActorSystemExtension` objects - this is what we're looking at doing for some of our external projects at Petabridge right now and the technique is highly repeatable.

**Comment by CumpsD** [comment]
Looking forward to this. Using DI to wire it up instead of fiddling with hocon sounds so much better.

**Comment by CumpsD** [comment]
@Aaronontheweb, any raw example you might have? Not necessarily documentation-quality ready.

**Comment by Aaronontheweb** [comment]
@CumpsD this spec here shows how to use the new `SerializationSetup` to do programmatic binding of serialization targets: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Tests/Serialization/SerializationSetupSpec.cs

That's a good one to look at since it's a real end-to-end implementation actually used by Akka.NET and not just a toy setup.
