### ISSUE TITLE
Akka.Remote cookies are not honored

### ISSUE THREAD

**Issue by petrikero** [akkadotnet/akka.net#4447]
I tried using the Akka.Remote cookies to avoid having two servers accidentally talk to each other, but the feature doesn't seem to work.

I tested using Akka.Net v1.4.7 and v1.4.4 which both produced the same results. I tested on Windows, but the issue seems platform-agnostic.

The relevant configs on the two nodes are:
`akka {
  remote {
    require-cookie = on
    secure-cookie = "first"
  }
}`
and
`akka {
  remote {
    require-cookie = on
    secure-cookie = "second"
  }
}`

Regardless of the differing cookies, the nodes connected just as without the cookies. Luckily, it's fairly easy for us to implement our own cookies on top of Akka.

**Comment by Aaronontheweb** [comment]
We don't support this feature in Akka.NET and it was removed from JVM Akka because it never really worked in the first place.
