### ISSUE TITLE
Persistent actor is not suspended while persisting snapshots

### ISSUE THREAD

**Issue by andersstorhaug** [akkadotnet/akka.net#4451]
Akka.NET v1.4.7

According to [Akka JVM docs](https://doc.akka.io/docs/akka/current/typed/persistence-snapshot.html):

> When a snapshot is triggered, incoming commands are stashed until the snapshot has been saved.

It seems though that the implementation in [`Eventsourced.cs` L219](https://github.com/akkadotnet/akka.net/blob/1.4.7/src/core/Akka.Persistence/Eventsourced.cs#L219) does not have this behavior.

So, at current, snapshots must be immutable in order to avoid threading issues, such as `Collection was modified` exceptions during serialization in journals.

In an example that I have, using `RunAsync` resolved the problem which confirmed that this was the source of the issue.

```csharp
RunTask(async () =>
{
    // By awaiting the response, the actor is suspended until the persist succeeds or fails
    var result = await SnapshotStore.Ask(new SaveSnapshot(new SnapshotMetadata(SnapshotterId, SnapshotSequenceNr), _state));

    if (result is SaveSnapshotFailure failure)
    {
        _log.Error(failure.Cause, "Failed to persist snapshot");
    }
});
```

**Comment by andersstorhaug** [comment]
Looking into this a little further on the JVM side of things, to be fair it looks like support for mutable snapshots was merged [somewhat recently](https://github.com/akka/akka/pull/26274/files/5c315026bbdeb725162d3699e50113053a674551) in Feb 2019.

**Comment by andersstorhaug** [comment]
Just adding, this behavior is a bit insidious.. ran into this problem again in a different spot. Appeared that the snapshot number was being recorded incorrectly, spent quite a lot of time trying to figure out why.

Turns out, it was due to this behavior - needed to ensure that the snapshot had deep copies of POCOs, etc.

**Comment by ismaelhamed** [comment]
You are looking at the **Akka Typed** documentation, AFAIK persistence in classical Akka does not behave the same. Also, classical Akka requires all messages to be immutable, and since you are putting your state inside a message (`SaveSnapshot`), then it needs to be immutable as well.

**Comment by andersstorhaug** [comment]
That makes sense, however it is a bit unfortunate. One of the benefits to the Actor model of course is that actor code is executed in a single-threaded context and naturally, any local actor state will take advantage of that. And, given that snapshots will generally contain local actor state, this is likely a common pitfall.

So, at the very least shouldn't there be something in the docs that points this out? For normal users I'd imagine that it's not 100% clear up-front that the persistence journal is another actor (it certainly would not have to be implemented this way).

Also, out of curiosity, how much leeway is there for Akka .NET to deviate from classic JVM Akka? I can understand if the goal is to have complete feature/behavior parity.

**Comment by Aaronontheweb** [comment]
> So, at the very least shouldn't there be something in the docs that points this out? For normal users I'd imagine that it's not 100% clear up-front that the persistence journal is another actor (it certainly would not have to be implemented this way).

Yes, there should be

**Comment by andersstorhaug** [comment]
I'm good with closing this issue if it would make sense to open another to cover this in docs.

**Comment by Aaronontheweb** [comment]
@andersstorhaug sounds good - we should make another issue to clarify this in the documentation.
