### ISSUE TITLE
Create a full example with aspnet core

### ISSUE THREAD

**Issue by nikolalukovic** [akkadotnet/akka.net#4454]
I'm struggling to find a full CRUD example that integrates Akka.net with asp.net core WebApi. All examples I can find on the internet are 4 years old, or too rudimentary or just some weird examples with Console app. It would be nice if we can see a full CRUD example integration with Dependency Injection and DB access, on asp.net core WebApi.

**Comment by Aaronontheweb** [comment]
https://github.com/petabridge/akkadotnet-cluster-workshop 
https://github.com/Aaronontheweb/InMemoryCQRSReplication
https://github.com/petabridge/Cluster.WebCrawler

Do none of these work?

**Comment by nikolalukovic** [comment]
When i googled aspnet core and akka none of these popped out 😭
Thanks!

**Comment by Aaronontheweb** [comment]
We should keep this issue open and do a better job promoting them

**Comment by MattHartz** [comment]
@Aaronontheweb Do we have any more basic samples? As someone who is new to akka, those are pretty complicated. I would love to see a sample project that is just a crud application. A starter project if you will. :) thank you!

**Comment by nikolalukovic** [comment]
bump

**Comment by Aaronontheweb** [comment]
Please see https://github.com/akkadotnet/akka.net/tree/dev/src/examples/AspNetCore/Samples.Akka.AspNetCore

**Comment by ChrisBaker812** [comment]
I know this is a very old post, which says something in and of itself, but it's now 2025 and I still cannot find a simple CRUD application using ASP.net core and WebApi. All your examples are at 20,000 feet and most, if not all, don't walk through creating an application from start to finish, just isolated, code explanations. If you want developers to use it then I suggest starting simple, say something like a car hire business or hotel booking business (but simplified obviously, not the whole thing), from start to finish. I can find this for MS Orleans. Also, I suggest not putting random links to irrelevant examples please.

Many thanks. 

I do really love the concept of AKKA.net, but I am finding it really hard to get into because of the above.

**Comment by Aaronontheweb** [comment]
Thanks for the candid feedback. I appreciate it.

> I know this is a very old post, which says something in and of itself, but it's now 2025 and I still cannot find a simple CRUD application using ASP.net core and WebApi. All your examples are at 20,000 feet and most, if not all, don't walk through creating an application from start to finish, just isolated, code explanations. 

I rewrote [Akka.NET Bootcamp](https://petabridge.com/bootcamp/lessons/) earlier this year and had planned on adding a new unit that does ASP.NET Core + Akka.NET from scratch as part of that later this year. I still intend on doing that.

And we have been building examples of how to do this - see https://github.com/petabridge/akkadotnet-code-samples, https://github.com/petabridge/DrawTogether.NET (Blazor Server w/ ASP.NET Core Identity, Aspire) etc. Those probably need to be advertised better from the main Akka.NET website.

> Also, I suggest not putting random links to irrelevant examples please.

https://github.com/petabridge/akkadotnet-code-samples/tree/master/src/clustering/sharding-sqlserver - is that an irrelevant example, even though it ships with a Web UI and an explanation of how things work?

**Comment by ChrisBaker812** [comment]
I'm going through the bootcamp at the moment, but I would prefer that it focussed on something that I would do in my day to day job, which is generally LOB applications that involve a mix of CRUD and WebApi of some sort or another. This would make the framework easier to put into context, I don't think a wordcounter really helps, not that it's not useful, it's just not real world enough. If you do the CRUD stuff later on in the bootcamp, and I've just not got far enough into it yet, I apologise (building a wordcounter is putting me off). I also find walking through already written code tedious and would prefer a worked example. It appears that any examples of using AKKA.net are in a highly distributed environment and being at a Phd level of understanding. Useful as they probably are, and great that the framework can do it, it's just not what I need to learn and understand and then build my understanding upon.

My comment was referring specifically to this link https://github.com/akkadotnet/akka.net/tree/dev/src/examples/AspNetCore/Samples.Akka.AspNetCore which wasn't what the OP had asked about.

I'll have another look at the link you have subsequently added and see if that helps. Thanks for the reply. It is a great framework, however, it is a very different way of thinking, and sometimes, different ways need a little more prompting. 

I hope this makes sense and is not meant to demine the work you have done, I would just like to try out the framework but in a way that fits my context. Get me started and I could perhaps help by building an example that may be useful to others. On the other hand, perhaps what I am asking for is just not what AKKA.net was built for and is just too simple. Anyway, thanks for the reply.

Incidentally this is probably my 3rd attempt at using AKKA.net. I first got interested in it in a Pluralsight course, if my memory serves me well, about 10 or so years ago (VS 2012!). I thought the landscape for it would have changed in that time, it appears that's not the case. Which is a shame as I can see its potential.
