### ISSUE TITLE
Lightbend Split Brain Resolver now OSS

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#4458]
FYI

The previously proprietary split brain resolver for Akka Cluster is now OSS:
https://github.com/akka/akka/pull/29099

**Comment by Aaronontheweb** [comment]
It's been part of Akka.NET for about 3 years: https://getakka.net/articles/clustering/split-brain-resolver.html

**Comment by rogeralsing** [comment]
No it hasn't.

"While this feature is based on Lightbend Reactive Platform Split Brain Resolver feature description, however its implementation is a result of free contribution and interpretation of Akka.NET team. Lightbend doesn't take any responsibility for the state and correctness of it."
