### ISSUE TITLE
akka.net wiki has a broken link to the old documentation

### ISSUE THREAD

**Issue by AndreasHassing** [akkadotnet/akka.net#4480]
https://github.com/akkadotnet/akka.net/wiki

links to http://akkanetdocfx.azurewebsites.net/ which does not exist.

**Comment by AndreasHassing** [comment]
As an aside: most of the links online to Akka.net F#-specific documentation are broken - a search for "akka.net fsharp/f#" reveals these broken links.

**Comment by Aaronontheweb** [comment]
We should probably get rid of the wiki - that hasn't been touched in 5+ years probably.

**Comment by Arkatufus** [comment]
Removed the sponsor and index page, fixed the home page
We still need the scala conversion guide
