### ISSUE TITLE
ClusterUpEvent seems to have issues with Serialiazation

### ISSUE THREAD

**Issue by pm-mw** [akkadotnet/akka.net#4481]
- Which Akka.Net version you are using: 1.4.8
- On which platform you are using Akka.Net: Win10

We are using the following implementation to check when a node is up and running within an Akka cluster

```
  protected void WaitUntilClusterIsUp() {
            var cluster = Akka.Cluster.Cluster.Get(ActorSystemInfo.ActorSystem);
            cluster.RegisterOnMemberUp(ClusterMemberAdded);

            _clusterUpEvent.WaitOne();
            _clusterUpEvent.Reset();
        }
       
        private void ClusterMemberAdded() {
            _clusterUpEvent.Set();
        }
```

This works fine.

In our integration tests we want to set the following option in the akkaconfig, to check that all messages are serializable:

`actor
    {
        provider=cluster
        serialize-messages = on
}`

If the serialize-message option is on, the call in the above method of    _clusterUpEvent.WaitOne(); does not return.

**Comment by Aaronontheweb** [comment]
Do you see any serialization error messages show up in the log at all?

**Comment by pm-mw** [comment]
no, not really

**Comment by Aaronontheweb** [comment]
Does the test pass if `serialize-messages = off` ?

**Comment by coldwarrl** [comment]
yes, than all works fine

**Comment by pm-mw** [comment]
yes, then all works fine

**Comment by Aaronontheweb** [comment]
Can you try turning the `akka.loglevel = DEBUG` and then tell me if anything shows up there? Or, if you run with the debugger and disable "Just My Code" in Visual Studio - do you get an exception stemming from inside any of the Akka.NET code? You might need to enable SourceLink to do this: http://www.aaronstannard.com/visual-studio-sourcelink-setup/

**Comment by pm-mw** [comment]
the log level was already on debug.

I got this exception now 
`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Akka.Remote
  StackTrace:
   at Akka.Remote.RemoteActorRefProvider.get_Transport() in -src\core\Akka.Remote\RemoteActorRefProvider.cs:line 156
`
Does this help ?

**Comment by Aaronontheweb** [comment]
@pm-mw that can happen periodically - occurs when we try to grab the `Akka.Remote` address so we can include it inside the `LogSource` of `/system` actors when they first launch - and some of those actors start before the transport is bound. Nothing to be worried about.

We'll create a reproduction spec with `serialize-messages = on` and see if we run into that again here. I believe we might already have one - I recall fixing this early on in the v1.4 development cycle.

**Comment by Arkatufus** [comment]
@pm-mw Am I right to assume that, in your code, `_clusterUpEvent` is an `EventWaitHandle` and that this is possibly a thread deadlock problem?

**Comment by Arkatufus** [comment]
@pm-mw do you use `JoinAsync()` in your code?

**Comment by pm-mw** [comment]
yes, _clusterUpEvent is a ManualResetEvent. I might be a deadlock, actually it looks like such a thing, since the application freezes. Is this the wrong pattern to wait until a node is joined the cluster ? It is just a bit weird that it works with serialize = off all the time.

No, we do not use Cluster.JoinAsync() currently.

**Comment by Arkatufus** [comment]
@pm-mw can you try this and see if this fixes your problem?
```
        private bool WaitUntilClusterIsUp()
        {
            var timeout = TimeSpan.FromSeconds(10);

            var oldContext = SynchronizationContext.Current;
            SynchronizationContext.SetSynchronizationContext(new SynchronizationContext());
            var result = _clusterUpEvent.WaitOne(timeout);
            _clusterUpEvent.Reset();
            SynchronizationContext.SetSynchronizationContext(oldContext);
            return result;
        }

        [Fact]
        public void A_cluster_must_not_deadlock_when_waiting()
        {
            _cluster.RegisterOnMemberUp(() => {
                _clusterUpEvent.Set();
            });

            _cluster.Join(_selfAddress);
            WaitUntilClusterIsUp().Should().BeTrue();
        }
```

**Comment by Arkatufus** [comment]
@pm-mw Can you try this and see if this fix your problem?
```
        // Returns true if cluster went up within the stated timeout
        private bool WaitUntilClusterIsUp(TimeSpan timeout)
        {
            var oldContext = SynchronizationContext.Current;
            SynchronizationContext.SetSynchronizationContext(new SynchronizationContext());
            var result = _clusterUpEvent.WaitOne(timeout);
            _clusterUpEvent.Reset();
            SynchronizationContext.SetSynchronizationContext(oldContext);
            return result;
        }

        [Fact]
        public void A_cluster_must_not_deadlock_when_waiting()
        {
            var timeout = TimeSpan.FromSeconds(10);

            _cluster.RegisterOnMemberUp(() => {
                _clusterUpEvent.Set();
            });

            _cluster.Join(_selfAddress);
            WaitUntilClusterIsUp(timeout).Should().BeTrue();
        }
```

**Comment by Arkatufus** [comment]
`RegisterOnMemberUp()` should be called before `Join()`

**Comment by Arkatufus** [comment]
@pm-mw 
This is a much safer way to wait:
```
        private bool _clusterIsUp;

        // Spin until _clusterIsUp flag is set or timeout expires
        private async Task WaitUntilClusterIsUp(TimeSpan timeout)
        {
            var stopwatch = Stopwatch.StartNew();
            while(!_clusterIsUp && stopwatch.Elapsed < timeout)
                await Task.Delay(100); // Wait for 100 ms and retest
            stopwatch.Stop();
        }

        [Fact]
        public async Task A_cluster_must_not_deadlock_when_waiting()
        {
            var timeout = TimeSpan.FromSeconds(10);

            _cluster.RegisterOnMemberUp(() => {
                _clusterIsUp = true;
            });

            // Delay needed to avoid a race condition between creation time of 
            // MemberUp listener actor and publish time of the MemberUp event 
            await Task.Delay(200); 

            _cluster.Join(_selfAddress);
            await WaitUntilClusterIsUp(timeout);
            _clusterIsUp.Should().BeTrue();
        }
```

**Comment by coldwarrl** [comment]
I have tried the last one but when serialize = on, _clusterIsUP is false (if serialize = off, _clusterIsUp is true)

I do not call explicitly  
```_cluster.Join(_selfAddress);```

but have in my config
```
..
remote
{
    dot-netty.tcp
    {
        port=8420
        hostname="localhost"
    }
}

cluster{
    seed-nodes=["akka.tcp://cluster@localhost:8420", "akka.tcp://cluster@localhost:8421"]
    roles=["application", "database"]
    }
}
```

**Comment by pm-mw** [comment]
I have tried the last one but when serialize = on, _clusterIsUP is false (if serialize = off, _clusterIsUp is true)

I do not call explicitly
_cluster.Join(_selfAddress);

but have in my config

..
remote
{
    dot-netty.tcp
    {
        port=8420
        hostname="localhost"
    }
}

cluster{
    seed-nodes=["akka.tcp://cluster@localhost:8420", "akka.tcp://cluster@localhost:8421"]
    roles=["application", "database"]
    }
}
