### ISSUE TITLE
Code examples in documentation are incomplete (Persistence - deferring actions)

### ISSUE THREAD

**Issue by kpko** [akkadotnet/akka.net#4482]
Hi,

I stumbled across this by reading the Akka.net documentation. It seems like the code examples in the section "Deferring actions ..." under Persistence => Event Sourcing are incomplete: https://getakka.net/articles/persistence/event-sourcing.html#deferring-actions-until-preceding-persist-handlers-have-executed - at least this is how it looks like on my machine:
![image](https://user-images.githubusercontent.com/835010/85079334-e0b7bc00-b1c6-11ea-88e1-ef869934ffe7.png)
![image](https://user-images.githubusercontent.com/835010/85079355-eb725100-b1c6-11ea-8dea-765cb51a734c.png)

Is this an error or am I missing something? Are these code examples still accessible somewhere? If so I would submit a pull request.

Thanks!

**Comment by ismaelhamed** [comment]
Yes it is. These are the complete examples for now:

https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Docs.Tests/Persistence/PersistentActor/Defer.cs
https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Docs.Tests/Persistence/PersistentActor/DeferWithPersist.cs
