### ISSUE TITLE
Question: Possible to implement authentication in custom transport?

### ISSUE THREAD

**Issue by kpko** [akkadotnet/akka.net#4483]
Hi,

I'm using Akka.net since a few weeks in an event-driven work-distribution system and I'm having a great productivity boost thanks to Akka.net - thanks everyone! :-)

Short preamble: At the moment I have a lot of smaller jobs that I distribute in a cluster (non-akka.cluster). I have a server node and a several worker nodes - the worker nodes subscribe to a stream of jobs via gRPC (server side streaming). The server node decides which worker will get the job (depending on a map of capabilities and requirements for the job). Sometimes there are resources that the worker fetches from the server, also via gRPC. 

I was thinking about skipping gRPC completely and using the built-in Akka.Cluster to enable the nodes to communicate. This would enable me to use the Akka routers, distributed pub-sub, AtLeastOnceDeliveryActors via Akka.Persistence and so on. My only problem at the moment is that I want my users to be able to deploy worker nodes to whatever environment the like: AWS, Azure, on-premise servers (for example for jobs that need to access on-premise databases) and as sensible messages get transferred between the nodes, I want to have some kind of authentication mechanism. As I understood so far Akka.Cluster uses a TCP transport as default and the only security mechanism available would be TLS. It's recommended to create a VPN - that seems to be pretty complex between AWS, Azure, on-premise machines and maybe containers though.

The documentation states that it's relatively simple to create a custom transport, because functionality like serialization and the cluster protocol are handled at another layer. Is it possible to implement a custom transport for cross-node (cross-datacenter) communication (e.g. via gRPC) that uses authentication?

Thanks!

**Comment by Arkatufus** [comment]
You certainly can. You can, for example, take the original `Akka.Remote.Transport.DotNetty.DotNettyTransport` class and replace `Akka.Remote.Transport.DotNetty.TcpTransport`, `Akka.Remote.Transport.DotNetty.TcpHandlers`, and `Akka.Remote.Transport.DotNetty.TcpAssociationHandle` with your own implementation. You can, for example, encrypt/decrypt the outgoing raw data, or tag it with your own authentication scheme.

Or you can create an authentication envelope and wraps every outgoing message with it, you unwrap the message on the receiving end and process the authentication message there.

**Comment by Arkatufus** [comment]
I will close this discussion for now. Feel free to reopen it if you have further questions.
