### ISSUE TITLE
Akka.Net performance on Single Console Application (.Net Core on windows)

### ISSUE THREAD

**Issue by glikoz** [akkadotnet/akka.net#4494]
If I use Akka.net in a single app domain (single process) still it will use serialization during messaging?

- I am using the latest version of Akka.Net
- Windows Environment
- No Client/Server  Just one Console Application

**Comment by snekbaev** [comment]
AFAIR, no for perf reasons. You can opt-in though (for testing for example).

**Comment by Danthar** [comment]
No they dont. Messages consumed by local actors are not serialized. If you want that. You can turn it on in Hocon.
Check the docs at https://getakka.net/articles/configuration/akka.html and the setting   serialize-messages
