### ISSUE TITLE
Is it safe to "Tell" message from Non-Actor Classes via Global ActorContext ?

### ISSUE THREAD

**Issue by glikoz** [akkadotnet/akka.net#4495]
I have object instances in the deep place of the system's object hierarchy. They are not Actor but they have a state and the system needs to know their state changes. Defining Global Static ActorContext (like Serilog's static Log class) or giving them an IActorRef reference is a safe approach? Or If an instance needs to "TELL" something it must be Actor?

**Comment by ondrejpialek** [comment]
Hi,

Firstly, https://gitter.im/akkadotnet/akka.net might be a better place to ask such questions.

Now to your point - yes it is safe. A good example is bridging the gap from MVC controller to Akka. You just need to get hold of an `IActorRef` that you need and use Tell or even Ask if you need a reply. If you need something more advanced, like receiving multiple replies or simply messages over time, you can create an `Inbox` and use that to receive replies/messages. No need to turn your class into an Actor if that would be too much work. See https://getakka.net/articles/actors/inbox.html

**Comment by Aaronontheweb** [comment]
Yep, @ondrejpialek 's answer is right - it's perfectly safe to tell an actor a message from outside the `ActorSystem`. We do it all the time in our applications.

**Comment by glikoz** [comment]
Thanks for 

> Hi,
> 
> Firstly, https://gitter.im/akkadotnet/akka.net might be a better place to ask such questions.
> 
> Now to your point - yes it is safe. A good example is bridging the gap from MVC controller to Akka. You just need to get hold of an `IActorRef` that you need and use `Tell` or even `Ask` if you need a reply. If you need something more advanced, like receiving multiple replies or simply messages over time, you can create an `Inbox` and use that to receive replies/messages. No need to turn your class into an Actor if that would be too much work. See https://getakka.net/articles/actors/inbox.html

Thanks for explonation and link.

**Comment by glikoz** [comment]
> Yep, @ondrejpialek 's answer is right - it's perfectly safe to tell an actor a message from outside the `ActorSystem`. We do it all the time in our applications.

Thanks.
