### ISSUE TITLE
Copyright header extra lines affecting docfx snippets in the docs

### ISSUE THREAD

**Issue by ismaelhamed** [akkadotnet/akka.net#4497]
As noticed by @kpko in #4482, the range of lines specified by the range parameter in some docfx snippets are now wrong due to the copyright header added recently.

This is obvious in the [event-sourcing](https://getakka.net/articles/persistence/event-sourcing.html#deferring-actions-until-preceding-persist-handlers-have-executed) article, for instance.

**Comment by Arkatufus** [comment]
#4508 should fix all the affected documents, thanks for finding this 👍
