### ISSUE TITLE
Is there a way to seperate network resource for different actors in akka remote?

### ISSUE THREAD

**Issue by Qiao-Jin** [akkadotnet/akka.net#4522]
- Which Akka.Net version you are using

Akka.remote 1.4.7

- On which platform you are using Akka.Net

Microsoft Visual Studio Community 2019

- A list of steps to reproduce the issue.

Startup 2 clients which employ akka.remote to communicate between actors as follows, where all actors are extended from ReceiveActor:

![image](https://user-images.githubusercontent.com/43407364/87651035-20050880-c785-11ea-82b6-db5b2495429e.png)

Then send a lot of (i.e. 5 millions) messages from actor a to actor c in one thread, while sending several messages from actor b to actor d in another. Even though the two message streams are sent at the same time, messages from actor b cannot be received by actor d in time (i.e. received some minutes after the messages are sent, as it takes minutes for messages from actor a to c to be received).

So are all akka remote messages handled in one messages queue even though they are from and to different actors? Is there a way for messages from actor b to d received in time, i.e. seperate network resource for different actors in akka remote?

**Comment by Aaronontheweb** [comment]
@Qiao-Jin so in Akka.Remote today, all messaging is handled over a single TCP connection between nodes and messages should get interleaved based on the order in which they're received by the local `EndpointWriter` actor in the `ActorSystem` that hosts actors a and b. If actor a puts several million messages into the queue before actor b has a chance to commit any of its messages, actor b will have to wait until all of actor a's messages are serialized and flushed onto the wire transport.

We might be able to improve this with https://github.com/akkadotnet/akka.net/issues/4436 but you might still have some issues there - best way to solve this issue would be to deploy actors c and d onto two different `ActorSystem`s so each has their own individual connection back to the `ActorSystem` that hosts a and b.
