### ISSUE TITLE
Fix bounded stashing

### ISSUE THREAD

**Issue by HCanber** [akkadotnet/akka.net#453]
Once #452 **Implement bounded message queues** has been implemented bounded stashing can be fixed.
- Check if `BoundedStashImpl` needs updating
- Remove the `Obsolete` attribute on `WithBoundedStash` that warns the user that bounded stashing is not supported.
- Add tests to `ActorWithStashSpec` that verifies blocking and `PushTimeOut`

**Comment by Aaronontheweb** [comment]
@HCanber does this still need to be done?

**Comment by HCanber** [comment]
Yes, it does. It should be fairly simple now that #452 is implemented. The main thing is writing tests. It should probably go into a new test class `ActorWithBoundedStashSpec`, see https://github.com/akka/akka/blob/8485cd2ebb46d2fba851c41c03e34436e498c005/akka-actor-tests/src/test/scala/akka/actor/ActorWithBoundedStashSpec.scala
for inspiration

**Comment by Aaronontheweb** [comment]
@HCanber do you want to take this one or should I mark it as up for grabs?

**Comment by irperez** [comment]
Guys, I've been looking into this one, but I'm kind of stuck on one particular spot while unit testing.  I'm new to akka, so please be gentle :)

In particular, I'm calling context.Props.Mailbox inside the AbstractStash class.  And this is always = empty string.  And this is causing me a lot of headache as I'm not able to find how to get this to be any other value than an empty string.

Now just so its clear, here is the code I used so far in the constructor:

```C#
protected AbstractStash(IActorContext context, int capacity = 100)
        {
            var actorCell = (ActorCell)context;
            var mailbox = actorCell.Mailbox as IDequeBasedMailbox;
            if(mailbox == null)
            {
                string message = @"DequeBasedMailbox required, got: " + actorCell.Mailbox.GetType().Name + @"
An (unbounded) deque-based mailbox can be configured as follows:
    my-custom-mailbox {
        mailbox-type = ""Akka.Dispatch.UnboundedDequeBasedMailbox""
    }";
                throw new NotSupportedException(message);
            }
            _theStash = new LinkedList<Envelope>();
            _actorCell = actorCell;

            // TODO: capacity needs to come from dispatcher or mailbox config
            // https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/Stash.scala#L126            

            var dispatcher = context.System.Settings.Config.GetConfig(context.Props.Dispatcher);
            var fallback = dispatcher.WithFallback(context.System.Settings.Config.GetConfig(Mailboxes.DefaultMailboxId));
            Configuration.Config config = null;
            if (context.Props.Mailbox != string.Empty)
            {
                if (context.Props.Mailbox == Mailboxes.DefaultMailboxId)
                {
                    config = fallback;
                }
                else
                {
                    config = context.System.Settings.Config.GetConfig(context.Props.Mailbox).WithFallback(fallback);
                }
                _capacity = config.GetInt("stash-capacity");
            }                        
            _capacity = capacity;
        }
```

Now if you look towards the bottom half of the constructor; this code came from scala mainly.  I tweaked it a bit to work a little better in C# and put some things in if statements so I could debug a little easier.

The main issue I'm having is context.Props.Mailbox will never be changed.  

Here is my HOCON configuration:

```HOCON
akka {
            log-config-on-start = off
            stdout-loglevel = INFO
            loglevel = ERROR
            actor {
              debug {
                  receive = on
                  autoreceive = on
                  lifecycle = on
                  event-stream = on
                  unhandled = on
              }
              deployment {
                /BoundedStashActor {
                  mailbox {
                    stash-capacity = 5
                  }
                }
              }
            }          
          }
```

Now my guess is that this configuration is off somewhere, I'm just not sure where exactly.  Or my other guess is that there is a bug in the test framework when it comes to mailbox initialization.  

Now I checked the original akka scala code and the documentation.  I can't find a clear example of how to setup the mailbox configuration in the HOCON in regards to bounded stashes.  So this was my best guess.  Can someone confirm this is correct?

I'm new to akka so I'm asking what you guys think I should do here.

**Comment by rogeralsing** [comment]
There is a lot of mailbox related configuration settings missing in our implementation.
I'm not sure we even read the mailbox section of the configuration right now.

**Comment by irperez** [comment]
I did take a peak at how we load the configuration and I couldn't find anything which led to my confusion.  Ok, at least I understand that.  Maybe I can take a peek into at least reading and loading the configuration into the config object.  Let me see what I can do.
