### ISSUE TITLE
Cleanup NetFrameworkLibVersion variable

### ISSUE THREAD

**Issue by huysentruitw** [akkadotnet/akka.net#4558]
The variable [`NetFrameworkLibVersion`](https://github.com/akkadotnet/akka.net/blob/dev/src/common.props#L21) seems no longer used as a target, only in conditions. Is it safe to remove it from conditions and remove related things like the `#if UNSAFE_THREADING` pre-compiler blocks?

![image](https://user-images.githubusercontent.com/4618744/92140933-0e99bd80-ee12-11ea-9780-934218b42ee9.png)

**Comment by Aaronontheweb** [comment]
@huysentruitw yep, it's safe to remove it.

**Comment by Aaronontheweb** [comment]
And it should be safe to remove those `#ifdef` blocks - those are all left-overs from supporting .NET Core 1.1
