### ISSUE TITLE
Xunit reporting info messages:  dead letters encountered

### ISSUE THREAD

**Issue by BartHuls** [akkadotnet/akka.net#4569]
Hi,

During the execution of the integration tests (1.4.10 i.c.w. .net core 3.1.8) i'm starting and stopping an actor system.
this system containt of multiple actors (25)  which can be up to 5 levels deep.

To stop the actors (the ones which are connected to an Hirarchy). I'm first sending (Tell) a message to this actor. The actor passes is through to the children and and stops itself by executing the  Context.Stop(Self); method.

Af this all is done i'm waiting if all these ators are stopped (in the PostStop of the actor I'm sending a message to the "coordinator") I'm terminating the actor system by:
await CoordinatedShutdown.Get(ActorSystem).Run(CoordinatedShutdown.ClrExitReason.Instance);

In my xunit log file i'm still getting several info messages like:

[INFO][9/11/2020 12:38:37 PM][Thread 0144][akka://ActorSystem/user/Coordinator/Actor-100/Actor-1001/Actor-10011] 
Message [StopActorRequest] 
from akka://ActorSystem/user/Coordinator/Actor-100/Actor-1001 to akka://ActorSystem/user/Coordinator/Actor-100/Actor-1001/Actor-10011 
was not delivered. [2] dead letters encountered. 
If this is not an expected behavior then akka://ActorSystem/user/Coordinator/Actor-100/Actor-1001/Actor-10011 may have terminated unexpectedly. 
This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
 
Any ideas?

Regards,
Bart

**Comment by Aaronontheweb** [comment]
Hi Bart,

This is probably harmless and can happen when you shut actors down - some of them received the `Terminate` message (generated by `Context.Stop`) prior to receiving the `StopActorRequest` and shut down right away. This could be because when you terminate a parent actor, that actor must kill all of its children first before it can be shut down. Does that sound like what is happening here?

**Comment by BartHuls** [comment]
Hi Aaron,

Yes that looks like it. It could be possible that the children are not shutdown (the message goes from parent to children) and in the meantime it's shutting down. 
Is this even necessary and is await CoordinatedShutdown.Get(ActorSystem).Run(CoordinatedShutdown.ClrExitReason.Instance); enough

**Comment by BartHuls** [comment]
Hi Aaron,

Changed the way that I'm closing down the actors. On a higher level I'm using the Context.Stop method.
The only thing what i'm now seeing is a "ActorTaskSchedulerMessage" 


```
[INFO][9/15/2020 9:43:53 AM][Thread 0029][akka://aaaa/user/bbbb/14351/14353] 
Message [ActorTaskSchedulerMessage] from akka://aaaa/user/bbbb/14351/14353 
to akka://aaaa/user/bbbb/14351/14353 was not delivered. [1] dead letters encountered. If this is not an expected behavior 
then akka://aaaa/user/bbbb/14351/14353 may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

```

**Comment by Aaronontheweb** [comment]
`ActorTaskSchedulerMessage` - this means an actor was waiting on an `await` operation at the time it was killed.
