### ISSUE TITLE
Trace logs with full messages road (Feature request)

### ISSUE THREAD

**Issue by tometchy** [akkadotnet/akka.net#4575]
Hi, thanks for creating such a great framework.

I spent some time debugging akka.net app and came to conclusion, that for debugging purposes it would be nice to have TRACE log level which should show messages road, for example that _message X was sent from actor Y_ or that _message X reached actor Z mailbox_, or that _actor Z started processing message X_.
Because it would be trace level, the whole message should be printed out (at least with `ToString`, or maybe with some structural way).

There are tools for _traditional object oriented code_ which do the corresponding thing - log every method call with every argument on trace log level, this will solve the same purpose as those tools.

**Comment by Aaronontheweb** [comment]
We (Petabridge) sell this as an add-on to Akka.NET, which performs end-to-end distributed tracing of actor messaging including over the network: https://phobos.petabridge.com/

**Comment by tometchy** [comment]
I see, you give very much free of cost so it's understandable. Please consider adding few simple logs (just with default logger the one from `Context.GetLogger()`), it would be nice, but I understand your point if you don't wont to.

My feedback is that at the current stage of our project investing in phobos is too much, but debugging messages sometimes is really difficult, much more difficult than usual method calls in regular code.
But maybe in some time we will buy phobos as _apm_ for production runtime, not as tool for debugging.

**Comment by Aaronontheweb** [comment]
@tometchy what additional logs would you need? I believe we have some pretty verbose ones when the `akka.actor.debug` settings are enabled:

```
debug {
      # enable function of Actor.loggable(), which is to log any received message
      # at DEBUG level, see the “Testing Actor Systems” section of the Akka
      # Documentation at http://akka.io/docs
      receive = off
 
      # enable DEBUG logging of all AutoReceiveMessages (Kill, PoisonPill et.c.)
      autoreceive = off
 
      # enable DEBUG logging of actor lifecycle changes
      lifecycle = off
 
      # enable DEBUG logging of all LoggingFSMs for events, transitions and timers
      fsm = off
 
      # enable DEBUG logging of subscription changes on the eventStream
      event-stream = off
 
      # enable DEBUG logging of unhandled messages
      unhandled = off
 
      # enable WARN logging of misconfigured routers
      router-misconfiguration = off
    }
```

**Comment by tometchy** [comment]
I knew that there are `debug` settings, but didn't know about `debug.receive`, this one looks like one I was looking for. Thank you :)
