### ISSUE TITLE
There is no way to configure local deployment via HOCON 

### ISSUE THREAD

**Issue by IgorFedchenko** [akkadotnet/akka.net#4596]
There is a `Props.WithDeploy(...)` method to set deployment with code, and we can do `.WithDeploy(Deploy.Local)` to configure local deployment.

We have `serialize-creators` [option](https://github.com/akkadotnet/akka.net/blob/3705c8c701c8fc16c037e23ab34ad3b0880b32f2/src/core/Akka/Configuration/Pigeon.conf#L106) that allows to make sure all props are serializable. And, as noted in this option docs, we can ignore props that are not going to be deployed remotely, via `deploy.scope = LocalScope` setting.

So, there are use cases, when we need to be able to explicitly set deployment as local for some actor's props, but there is no way to do that via configuration - `Deploy` object configuration parsing does not support this, it's scope is always set to `Deploy.NoScopeGiven`: https://github.com/akkadotnet/akka.net/blob/3705c8c701c8fc16c037e23ab34ad3b0880b32f2/src/core/Akka/Actor/Deployer.cs#L125

We should add support for `deploy.scope` there (with `LocalScope` and `NoScopeGiven` values to specify). or something like that. And update `serialize-creators` option comment to point to the place where/how exactly this local scope can be configured.

**Comment by Aaronontheweb** [comment]
Copying what I wrote in Gitter chat about this issue:

> is what you need a work-around for being able to mark an actor as "don't serialize my props when serialize-all-creators is on?"
> or is there a bigger structural bug with Akka.NET's serialize-all-creators option?
> if it's the first issue, believe there is a marker interface we can use that will tell Akka.NET to skip this actor
> if it's the second issue, we should definitely add it to the current sprint
> could you help me understand that @IgorFedchenko ?

**Comment by Aaronontheweb** [comment]
So this is a pretty rare edge case:

1. Want to run with `serialize-creators = on`;
2. Don't have the ability to access the `Props` of the instantiated actor directly, and those `Props` include non-serializable constructor arguments;
3. Need to try to influence that behavior via HOCON since the `ActorOf` callsite can't be directly modified by the consumer.

**Comment by Aaronontheweb** [comment]
I'll leave it open in case it's more common than previously assumed - but giving it the "won't fix" label for now.
