### ISSUE TITLE
Provide .NET 5.0 support for MultiNode TestKit

### ISSUE THREAD

**Issue by pm-mw** [akkadotnet/akka.net#4602]
Could you provide support  for .NET 5.0 (runtime) for the MultiNode Testkit (runner), so we can use it for assemblies  targeting .NET 5?
Thanks!

**Comment by Aaronontheweb** [comment]
Yep, we can get to work on this

**Comment by Aaronontheweb** [comment]
@eaba this is finished now, correct? Should be available in the 1.4.15 nightlies?
