### ISSUE TITLE
Need to harden `Option<T>` to avoid gotcha bugs

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/akka.net#4604]
The current implementation of `Option<T>` is lacking consistency and creates more problem than it actually solves.
1. It allows for a Some(null), which is, contractually broken (should be partially fixed in #4603).
2. It doesn't differentiate between Some and None, all we can go on with is to trust the `HasValue` property.
3. It allows access to null Value, which defeats the purpose of avoiding null reference propagation in the first place
    - Proper implementation is to stop null propagation immediately by throwing an exception

All in all, this allows for null to propagate inspite the use of `Option<T>` as a guard.

There are a few improvement options that can be taken:
1. (#4603) Assign `false` to `HasValue` if the passed value is null.
    This is the simplest "fix", it still doesn't differentiate between None, Some(null), and Some(T). You can still access the null value if you're not being careful and check for `Option<T>.HasValue()`. Might propagate into unexpected bug somewhere else. Can be slightly mitigated by:
2. Throw an exception if a null value is being accessed.
    This will stop any further null propagation. This guard will warn any possible code problem _during runtime_, making bug fixes faster. The problem is that, the more burried and rare a code is, the longer it will take to finally catch this exception, and it might happen in a critical timing during runtime.
3. Throw an exception if a null is passed into the contructor.
    This will guarantee that an `Option<T>` will always contain a value, unless it is reference equal to the `None` instance, the only `Option<T>` instance allowed to have a null value, which will throw if accessed. Slightly higher bug catch rate compared to option 2, but still can create problem down the road.
4. Replace `Option<T>` struct with `IOption<T>` interface and `Some<T>` and `None<T>` concrete class.
    - This is akin to open invasive radical surgery. All in all, it has the same benefit as option 3, with the added benefit that we can use switch...case based on the type returned by a function, exactly like coding in scala, making porting a lot easier.
    - This is how `Option<T>` is implemented in scala.
    - Actually works on primitive types since `Some` and `None` does not depend on a null value to define the state of `Option`
    - Some and None are clearly defined by the class type, and depending on how draconian we want to be, we can restrict certain methods to the concrete class, making sure that the user conciously aware of what they are using when coding.
    - **This is highly disruptive**, and **will cause** a major rewrite on all code paths that uses `Option<T>` as it is not a simple copy-paste and/or search-replace fix. On the flip side, this will make those code more robust and might uncover previously uncaught bugs in the system.
5. Improve upon option 4 and only allow creation of `IOption<T>` instances through a factory pattern.
    - This will slightly improve the experience of using `IOption<T>`, since the instance factory can automate `Some` or `None` instantiation decision based on the value passed into it. Can be a bit tricky to support primitive types.

**Comment by IgorFedchenko** [comment]
@Arkatufus Sounds good I think.
So, instead of writing
```csharp
Option<object> opt = new Option(new object());
return opt.HasValue; // true

Option<object> opt = Option<object>.None;
return opt.HasValue; // false
return opt.Value; // null, but should not have access to Value here

Option<object> opt = new Option(null); // throw
```

We will have something like
```csharp
IOption<object> opt = Option.For(new object()); // Some<object>
return opt is Some<object>; // true

IOption<object> opt = new None<object>; // None<object>
return opt is Some<object>; // false
return opt is Some<object> some ? some.Value : throw Exception("no value"); // better way of checking for Value

IOption<object> opt = Option.For(null); // None<object> or throw or Null<object>?
return opt.HasValue(); // extension method, shortcut for `opt is Some`
```

So, the main profit is that right now you can access `Value` of `Option.None` object (you can forget or ignore `HasValue` check), while in new implementation you will have to cast to `Some` first, so you can not skip this explicit check for value existence.

Right?

**Comment by Arkatufus** [comment]
More or less.
The scala-ish way of doing it is
```c#
IOption<int> result = Myfunction();
switch(result){
  case Some<int> myInt:
    // process result here
    break;
  case None<int> _:
    // a null result
    return;
}

// or

int ThisReturnsInt() {
    MyFunction() switch {
        Some<int> myInt => myInt * 2,
        _ =>throw new Exception("processing failed");
    }
}
```

**Comment by sddania** [comment]
In order to implement a good "functional" option type, i would suggest to create a method "bind" as expressed here: https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core-optionmodule.html#bind
this is helpfull in order to "chain" computation and validation as expressed here: https://fsharpforfunandprofit.com/rop/
