### ISSUE TITLE
Question: Is there any way to get notification that Recovery is done on persisted actors ?

### ISSUE THREAD

**Issue by larsbuch** [akkadotnet/akka.net#4619]
For resilience if the last state needs some handling and perhaps continuation on last message (which changed the status).

I do not know if there is a hidden function for this (then it seems missing for the documentation) or if that is not existing then this is a feature request.

**Comment by Horusiath** [comment]
@larsbuch as mentioned in [docs](https://getakka.net/articles/persistence/architecture.html) persistent actors contain `IsRecovering` property flag which is true, when actor is in the middle of recovery cycle.

**Comment by larsbuch** [comment]
Thank you for the answer @Horusiath . 
I had hoped for something to subscribe to so to have it reactively so I missed that IsRecovering flag. 

I will try to do it with another flag and sending a message to self "check your self if work is needed". I will contribute to the docs when I have solved my problem. Right now I am misusing the snapshot function which is not the best way to do it but ...

**Comment by Aaronontheweb** [comment]
There is a method you can also override that gets invoked when a persistent actor is finished recovering: [`OnReplaySuccess()`](https://getakka.net/api/Akka.Persistence.Eventsourced.html#Akka_Persistence_Eventsourced_OnReplaySuccess)

You can override that and invoke code once your actor has finished successfully recovering.

In the event of a failure recovery, you can also override how your actor handles that by overriding [the `OnRecoveryFailure` method](https://getakka.net/api/Akka.Persistence.Eventsourced.html#Akka_Persistence_Eventsourced_OnRecoveryFailure_Exception_System_Object_).

Hope that helps!

**Comment by larsbuch** [comment]
Thank you for the answer @Aaronontheweb . I missed the OnReplaySuccess was virtual and was precisely what I needed. I will continue on my project to make it easier to start with akka.net for some things.

**Comment by Aaronontheweb** [comment]
Glad to hear it - please let us know if you have any further questions
