### ISSUE TITLE
Default ask timeout different than expected

### ISSUE THREAD

**Issue by tometchy** [akkadotnet/akka.net#4620]
Hi everyone.

- Which Akka.Net: **1.4.8**
- On which platform you are using Akka.Net: **NetCore 2.1 (C# 7.3)**

In documentation (https://getakka.net/articles/configuration/akka.html) I see that default timeout for asking is _infinite_.
I don't set ask-timeout explicite and I have set logging out configuration on startup and it says the same: _ask-timeout : infinite_.

When I provide my own config key with value _infinite_ then it's value received with `GetTimeSpan` is _-00:00:00.0010000_.
When I try to get not existing value from config then I have (default) value: _00:00:00_.

But when I try to read ask-timeout value (which I didn't set explicite) it has value _00:00:00_ like when I try to get some not existing value from config. Why is that, why it behaves different when I set _inifite_ by myself?

And why _inifite_ value is so strange, not for example `TimeSpan.MaxValue`?

![akka-infinite](https://user-images.githubusercontent.com/39067049/98796906-373ec480-240c-11eb-9ebc-d06954db302a.png)

**Comment by Aaronontheweb** [comment]
That inconsistency looks like it might be a bug - are you just using the default HOCON configuration?

**Comment by tometchy** [comment]
I load configuration with fallbacks and have my own values there (but it's not the case) then parse it with `ConfigurationFactory.ParseString`.

Fallbacks are not the reason, because simplified version behaves the same way:
``` csharp
            var config = ConfigurationFactory.ParseString(@"
akka.actor.another-timeout = infinite
");
            ActorSystem actorSystem = ActorSystem.Create("Q", config);
            
            var notExisting = config.GetTimeSpan("xyz");
            var askTimeout = config.GetTimeSpan("akka.actor.ask-timeout");
            var myInfiniteTimespan = config.GetTimeSpan("akka.actor.another-timeout");
```

Here you see it:
![akka-infinite-simple](https://user-images.githubusercontent.com/39067049/98852104-76463780-2457-11eb-9300-eb551c309ad7.png)

When I add `akka.log-config-on-start = on` then I see in output that ask-timeout is infinite:
![log-config](https://user-images.githubusercontent.com/39067049/98852813-890d3c00-2458-11eb-8cf7-ae513defd118.png)

Btw. how to check whether _infinite_ value has been passed?

**Comment by ismaelhamed** [comment]
If you specify `infinite` for a TimeSpan, it uses `Timeout.InfiniteTimespan` (-1 milliseconds) under the hood; on the other hand, if you set it to null, then it uses the default value for TimeSpan, which is `00:00:00`.

**Comment by ismaelhamed** [comment]
@tometchy can we close this one, or do you need further information?

**Comment by tometchy** [comment]
In my view it's a bug, I suggest to check it (is's easy as I posted
snippets) and if somehow it's correct behaviour then of course it can be
closed.

On Wednesday, November 18, 2020, Ismael Hamed <notifications@github.com>
wrote:
> @tometchy can we close this one, or do you need further information?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/AClQUhLYNasdmU6yn1_woRO1NEeHqHF0ygdMOgyjKWpLEqmqaBBeaEpt8IoeAZrGL3M-cLXHz_Jwaq5ArifMjMvpBuT2Fw_fqjFbK0pvbswleB4Mx505OC-nhqzwV_j9U14yft8vKBjrCxy4MGi9vjgdAXucx7i6cwrUYwu1_fsCuh01J8Ijwz-wrH-RXJc-T88A8HSn5-f4nWP8tdlDgTUftB4CZKE3Szf45KNJgQ=s0-d-e1-ft#https://github.com/notifications/beacon/AJKB3KO4DLMXNG3BVY6BCMDSQOH2HA5CNFSM4TRZBIJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFN6BPLQ.gif>

**Comment by zbynek001** [comment]
@tometchy  you are comparing different things. Your `config` doesn't have any fallback values, so there are only values you define in the string you parse via `ConfigurationFactory.ParseString`.
If you want to check the "real" config with fallback, you should check `actorSystem.Settings.Config`

**Comment by tometchy** [comment]
You're right, now I see it. So it can be closed.
