### ISSUE TITLE
Both _scheduler and _task can be null inside ActorTaskScheduler

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4645]
https://github.com/akkadotnet/akka.net/blob/ec01db19f1c49aecc6e3e828d264156a628ebadf/src/core/Akka/Dispatch/SysMsg/ISystemMessage.cs#L635

And the way this code is called inside `ActorCell`:

https://github.com/akkadotnet/akka.net/blob/ec01db19f1c49aecc6e3e828d264156a628ebadf/src/core/Akka/Actor/ActorCell.DefaultMessages.cs#L337-L351

Can potentially throw an NRE depending on the content included inside the message that is sent back to the actor. I haven't seen any user reports of that occurring in the ~5-6 years we've had this code so if it can happen it's probably rare, but still - this looks like a bit of a footgun.

**Comment by Arkatufus** [comment]
In the current code base, it is impossible for the scheduler to be null, because the method is only called from within an instance of `ActorTaskScheduler` and it always provide a `this` as the scheduler.

**Comment by Arkatufus** [comment]
The only case where _scheduler and _task are nulls is the case where Exception is set.
