### ISSUE TITLE
Deprecate PatternMatch

### ISSUE THREAD

**Issue by ismaelhamed** [akkadotnet/akka.net#4658]
I guess this wouldn't hurt, and it will also serve as a reminder to refactor any file we touch in Akka.NET that still uses it. 

I will send a PR if this is fine:

```csharp
/// <summary>
/// Class PatternMatch.
/// </summary>
[Obsolete("Use instead the pattern matching feature introduced in C# 7.0")]
public static class PatternMatch
```

**Comment by Aaronontheweb** [comment]
Yes, let's do that
