### ISSUE TITLE
Add Timestamp and missing properties to Akka.Persistence.Query.EventEnvelope

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4668]
This information is sometimes stored or derived as part of the `Offset` on the `EventEnevelope`: 

https://github.com/akkadotnet/akka.net/blob/77babf022eb7c06ecd8d12919af2441fed3b2fe1/src/core/Akka.Persistence.Query/Offset.cs#L50-L84

However, it looks to me like this is an oversight in the design of the `EventEnvelope`. There's no reason it shouldn't have an explicit timestamp appended to it given that this data is commonplace inside the Akka.Persistence journal.

We should create an issue and add some constructor overloads (can't modify the existing signatures - breaks binary compatibility) that time a Timestamp and exposed that as a public property on `EventEnvelope`.

_Originally posted by @Aaronontheweb in https://github.com/akkadotnet/akka.net/discussions/4665#discussioncomment-205528_

**Comment by ismaelhamed** [comment]
We want this at work, so I might just borrow some time to look into it.

**Comment by Arkatufus** [comment]
You mean misusing the Sequence object to store a timestamp value?
Maybe we should make a Timestamp class deriving from Offset?

**Comment by ismaelhamed** [comment]
We are missing [#28383](https://github.com/akka/akka/pull/28383). I already started working on this, and will probably have it finished on Monday.

**Comment by Arkatufus** [comment]
Thanks, @ismaelhamed! 👍

**Comment by Horusiath** [comment]
If I remember correctly, the main reason for absence of timestamp fields was that timestamps are based on wall clocks, which are not consistent in multimachine environment, therefore not reliable in distributed systems. They can be useful in user domain, but in this case they're not part of the envelope but user event type. 

How to make a persistent queries based on user defined parameters? I think akka team never answered to that question.

**Comment by ismaelhamed** [comment]
Since the timestamp represents the time the event was stores, some clock sincronization is required. But ultimately, the user can override the journal's `WriteEvent` method and let the underlying datastore take care of it.

I mostly see this being used for metrics and observability though. IMO this [comment](https://github.com/akka/akka/issues/28331#issuecomment-564311565) makes a fair point, and you can see why they eventually added support for this.
