### ISSUE TITLE
Akka.Persistence.EventStore 1.3.0 nuget package is depending on deprecated EventStore.ClientAPI.NetCore

### ISSUE THREAD

**Issue by catnip-se** [akkadotnet/akka.net#4670]
The latest nuget package for Akka.Persistence.EventStore has dependecies to the EventStore.ClientAPI.NetCore which is deprecated. 
EventStore.Client >= v5.0.0 should be used. Please release updated packages using EventStore.Client version >=5.0.0 and 20.0.0.

**Comment by Aaronontheweb** [comment]
Guess we're going to need to move this out of the AkkaNetContrib organization and bring it into this org...

**Comment by Aaronontheweb** [comment]
Fixed - we've had lots of new Akka.Persistence.EventStore releases since: https://github.com/akkadotnet/Akka.Persistence.EventStore
