### ISSUE TITLE
How to use Akka.DependencyInjection with Akka.TestKit?

### ISSUE THREAD

**Issue by seungyongshim** [akkadotnet/akka.net#4733]
- Akka.Net 1.4.15
- .Net 5

Excuse, me.
I can't found sample code. How to use TestKit with BootstrapSetup?
- https://github.com/seungyongshim/Mirero.Akka.Extensions.DependencyInjection

Best regards

**Comment by seungyongshim** [comment]
## my sample
- `TestClass` can't extends `Testkit`, because `ActorSystemSetup` depends `sp`
```csharp
public class TestClass
{
        [Fact]
        public async Task Check_Child_Actor_Recieved_Messages()
        {
            // Arrange
            var host = Host.CreateDefaultBuilder()
                           .ConfigureServices(services =>
                           {
                               services.AddSingleton(sp =>
                                   new TestKit(BootstrapSetup.Create()
                                                             .And(ServiceProviderSetup.Create(sp))));
                               services.AddSingleton(sp => sp.GetService<TestKit>().Sys);
                               services.AddSingleton(sp => sp.GetService<TestKit>().TestActor);
                               services.AddSingleton<IPropsFactory<ChildActor>, PropsFactory<ChildActor, MockChildActor>>();
                           })
                           .UseAkka(sys =>
                           {
                               sys.ActorOf(sys.PropsFactory<ParentActor>().Create(), "Parent");
                           })
                           .Build();

            await host.StartAsync();

            var testKit = host.Services.GetService<TestKit>();

            // Act
            testKit.ActorSelection("/user/Parent").Tell("Hello");

            // Assert
            testKit.ExpectMsg<string>().Should().Be("Hello, Kid");
            testKit.ExpectMsg<string>().Should().Be("Hello, Kid");

            var child1 = await testKit.Sys.ActorSelection("/user/Parent/Child1").ResolveOne(5.Seconds());
            child1.Path.Name.Should().Be("Child1");

            var child2 = await testKit.Sys.ActorSelection("/user/Parent/Child2").ResolveOne(5.Seconds());
            child2.Path.Name.Should().Be("Child2");

            await host.StopAsync();
        }
}
```

**Comment by IgorFedchenko** [comment]
Hi @seungyongshim!

I think, you can get some ideas from this sources: https://github.com/akkadotnet/akka.net/blob/cb54b5587fa053a7f83dd59d53bb48d031a31335/src/contrib/dependencyinjection/Akka.DependencyInjection.Tests/ActorServiceProviderPropsWithScopesSpecs.cs#L21

Basically, when using `AkkaSpec`, you have your ActorSystem initialized for you in base class - and you can configure it's initialization by passing additional setup into `base()` constructor. That's what `ActorServiceProviderPropsWithScopesSpecs` is doing.

Our spec uses `AkkaDiFixture` to initialize `IServiceProvider` buy simply building it from `ServiceCollection`: https://github.com/akkadotnet/akka.net/blob/cb54b5587fa053a7f83dd59d53bb48d031a31335/src/contrib/dependencyinjection/Akka.DependencyInjection.Tests/AkkaDiFixture.cs#L105. You can do the same, or start full-blown host (as you are doing in your sample) inside that fixture class (you might want to use `IAsyncLifefime` interface and override `InitializeAsync` method for optimization - [sample](https://github.com/akkadotnet/Akka.Streams.Kafka/blob/03d1bcda61df3f044af9b1cdc2f7f9ea02645414/src/Akka.Streams.Kafka.Tests/KafkaFixture.cs#L20)).

Also, if you are not using anything from built-in `Sys` actor system, you can just create your own `ActorSystem` with your setup in your test method (almost like you are doing in your sample, just do not create `TestKit` instance - use `ActorSystem.Create` method to create your own system instead).

Does it make sense?

**Comment by Arkatufus** [comment]
@seungyongshim I've updated the DI sample to use IHostedService. You can check it [here](https://github.com/akkadotnet/akka.net/pull/4767) for now, while it is waiting to be merged.
