### ISSUE TITLE
Slow transactions when unreachable seed node in cluster

### ISSUE THREAD

**Issue by pacama95** [akkadotnet/akka.net#4737]
Hello team,

We are implementing an ASP Net Core application which is hosted in three different machines. In order to share information between the machines we have implemented an Akka cluster with three seed nodes, one per machine. We are using Akka.DistributedCache to accomplish this. The hocon file used by each application looks like this:
`akka 
{
    actor
    {
        provider = "cluster"
    }   
    loggers =
    [
        "Akka.Logger.NLog.NLogLogger, Akka.Logger.NLog"
    ]
    remote
    {
        dot-netty
        {
            tcp
            {
                port = _8001_
                hostname = "_machine1_"
                enable-ssl = true
                ssl
                {
                    suppress-validation = true
                    certificate
                    {
                        path="_path to a certificate_"
                    }
                }
            }
        }
    }
	cluster
    {
	name = "3ds-transaction-verse"
        seed-nodes =
        [
            "akka.ssl.tcp://3ds-transaction-verse@localhost:8001"
            "akka.ssl.tcp://3ds-transaction-verse@localhost:8002"
            "akka.ssl.tcp://3ds-transaction-verse@localhost:8003"
        ]
        roles = ["distributed-cache"]
    }
}`
Note: this is the hocon file for one of the applications, the other application's hocon files are setted with their respective ports and specific parameters.

Our problem scenario is the following: when the cluster is consolidated and everything is working as expected, if one of the machines is shutdown, the node hosted in that machine is marked as unreachble by the other machines(as expected) but the transactions on the distributed cache start to fail by timeout.
We thought that the system will be able to keep working when one of the nodes stops working, but it is not the case. 
Our doubt here is if this is it a normal behavior?

Thank you.

**Comment by to11mtm** [comment]
> if one of the machines is shutdown, the node hosted in that machine is marked as unreachble by the other machines(as expected) but the transactions on the distributed cache start to fail by timeout.

I would ask whether they are ever going from Unreachable to Down; I could be mistaken but I don't believe that DData excludes unreachable from a quorum decision (after all, that could indicate a data discrepancy).

The other question I would have is what write consistency you have selected?
From docs:
> update will propagate to more than a half nodes in a cluster (or nodes given a configured role) before response will be emitted.

Now, I could be incorrect on this assumption, but I would guess that in this case `WriteMajority` is expecting to be able to write to at least half of the nodes in the cluster (and is not including itself in that for one reason or another.) May have to dig depeer on this.

**Comment by pacama95** [comment]
Hi,

Thank you for your response.
The selected consistency is WriteAll, so I think the root of the problem is that write consistency. When a seed node from the cluster is in unreachable status then the transaction are slowered by the tiemout specified at the write consistency, isn't it?

**Comment by to11mtm** [comment]
I think you figured this out based in Gitter chat, I'll put some notes here for others however.

- `WriteAll` will fail if any nodes in a cluster are 'unreachable' and not yet 'downed'/removed.
- You should take care with `WriteMajority` and very small clusters (i.e. 3 or less). 

From a design standpoint, I'm a huge fan of having integration test cases for your use scenarios. I.e. take some time to set up some integration tests with a cluster so that the behavior when a node is unreachable/etc is understood and documented. This will also keep you safer in the future, if someone decides to 'optimize' the write/read consistency later and it changes other behaviors.

**Comment by pacama95** [comment]
Hi Drew,

Thank for your help.
Yes, I found out the problem. I will take into account your suggestions.
