### ISSUE TITLE
on singleton-proxy setting buffer-size to 0 via Hocon fail on exception

### ISSUE THREAD

**Issue by gcohen12** [akkadotnet/akka.net#4763]
on Akka.Cluster.Tools 1.4.8.0
Windows OS
set config with 

akka.cluster{
  singleton{
            singleton-name= "CoordinatorActor",
            role="Coordinator"
            hand-over-retry-interval = @@HandOverRetryInterval@@
            min-number-of-hand-over-retries = @@MinNumberOfHandOverRetries@@
          }

          singleton-proxy {
              # The actor name of the singleton actor that is started by the ClusterSingletonManager
              singleton-name = "CoordinatorActor",

              # The role of the cluster nodes where the singleton can be deployed. 
              # If the role is not specified then any node will do.
              role = "Coordinator"

              # Interval at which the proxy will try to resolve the singleton instance.
              singleton-identification-interval = 1s

              # If the location of the singleton is unknown the proxy will buffer this
              # number of messages and deliver them when the singleton is identified. 
              # When the buffer is full old messages will be dropped when new messages are
              # sent via the proxy.
              # Use 0 to disable buffering, i.e. messages will be dropped immediately if
              # the location of the singleton is unknown.
              # Maximum allowed buffer size is 10000.
              buffer-size = 1 	#0 is not working - AKKA bug
            }
}

**Comment by Aaronontheweb** [comment]
Thanks for reporting this @gcohen12 - we will review / hopefully fix it as part of our sprint starting on Monday.
