### ISSUE TITLE
EventFilter Expect filters out events from standard output

### ISSUE THREAD

**Issue by IgorFedchenko** [akkadotnet/akka.net#4773]
As @brah-mcdude pointed out in Gitter: EventFilter.Error.Expect(..) mutes events from standard output:
![image](https://user-images.githubusercontent.com/9683660/107347116-87dec000-6ad6-11eb-9193-85ebf2ef1bed.png)

**Comment by brah-mcdude** [comment]
In order for "Open additional output for this result" Test Explorer message to show up, you must include:
Console.SetOut(NUnit.Framework.TestContext.Out); // in [SetUp]
This issue seems to only be relevant to NUnit (I don't know how to reproduce on Xunit2 etc).

**Comment by IgorFedchenko** [comment]
From @Aaronontheweb in Gitter chat:
> I noticed an issue with this and Debug messages this weekend @IgorFedchenko @brah-mcdude
so there is something off there
the ITestOutputHelper is still printing it out
so there might be something upstream that is overriding the logging settings for filtering

**Comment by IgorFedchenko** [comment]
All right, so the reason is following:

In `EventFilterApplier` we are muting events while making assertion. Not sure why:
https://github.com/akkadotnet/akka.net/blob/076d8de5b260a75c82b2a0151e56fce410d24cd4/src/core/Akka.TestKit/EventFilter/Internal/EventFilterApplier.cs#L282

Internally, this ends up with `TestEventListener` not printing events to the `Console`:
https://github.com/akkadotnet/akka.net/blob/b76b98af84232b45327cc8d0a336d39434d9018c/src/core/Akka.TestKit/EventFilter/TestEventListener.cs#L63

Now, for XUnit there is a separate logger that subscribes to `LogEvent` events from `System.EventStream` and prints them to the `ITestOutputHelper`:
https://github.com/akkadotnet/akka.net/blob/b76b98af84232b45327cc8d0a336d39434d9018c/src/contrib/testkits/Akka.TestKit.Xunit/TestKit.cs#L126

For `NUnit` there is nothing like that - and we have to use `Console.SetOut(TestContext.Out);` to redirect console output to NUnit output sink. But we could do the same thing that XUnit does and have dedicated logger which will use `TestContext.WriteLine` for writing events to the output without interaction with console.

Based on that, here is a workaround everyone can use:
```csharp
public class LoggingActor : ReceiveActor
{
	public LoggingActor(TextWriter writer) => Receive<LogEvent>(e => writer.WriteLine(e.ToString()));
}

// this code should be inside [SetUp], no Console output redirect needed anymore
var loggingActor = Sys.ActorOf(Props.Create(() => new LoggingActor(TestContext.Out)));
Sys.EventStream.Subscribe<LogEvent>(loggingActor);
```

This way, all logging events are getting written to the test adapter output without interaction with console.

**Comment by IgorFedchenko** [comment]
@Danthar @Aaronontheweb  Do you guys think we need something like this to be added to NUnit testkit plugin? So that it was independent from the Console?

**Comment by Danthar** [comment]
It would the behaviour online with the x unit testkit. So I'm all for it.
But would we include this as default behavior, or provide it as a tool in
combination with some docs. I'm for the first option. But that would be a
breaking change.

Op do 11 feb. 2021 22:08 schreef Igor Fedchenko <notifications@github.com>:
