### ISSUE TITLE
Null message causes crash of DeadLetterListener

### ISSUE THREAD

**Issue by object** [akkadotnet/akka.net#4815]
Akka doesn't support sending NULL messages between actors, however DeadLetterListener should not crash because of unhandled NULL message. If such message appears in the system, it causes failure in LogDeadLetter method which tries to evaluate its type. Because of the failure it's not possible to find out the message origin and recipient.

I am sending a PR for this issue shortly.

**Comment by Aaronontheweb** [comment]
Oh boy - that's a nasty one...
