### ISSUE TITLE
DequeWrapperMessageQueue does not correctly EnqueueFirst

### ISSUE THREAD

**Issue by HCanber** [akkadotnet/akka.net#482]
This is a tricky one. :)
@rogeralsing originally used a Stack as PrependBuffer, then came me and @Aaronontheweb along and said it was wrong, and that a Queue should be used in #424. That was wrong. It fixed the stashing problem, but introduced a new one.
``` C#
q.EnqueueFirst(A)
q.EnqueueFirst(B)

q.Dequeue() //returns A, should be B
q.Dequeue() //returns B, should be A
```

So a Stack _should_ be used internally.

However this introduced a problem that @Aaronontheweb wrote about in #424:
>items that are being prepended to the front of the mailbox can't jump ahead of the other messages that were previously scheduled to be prepended. The PrependBuffer needs to maintain the same FIFO order that the Stash does.

I think what #424 should have fixed was to UnstashAll messages in reverse order. So either we do that or we create an overload in `DequeWrapperMessageQueue` that takes an `IEnumerable` that respects fifo order.

**Comment by Aaronontheweb** [comment]
@HCanber @rogeralsing did we already fix this?

**Comment by rogeralsing** [comment]
Dont think we have

**Comment by HCanber** [comment]
Can't find any commits that suggests this has been fixed.

**Comment by Aaronontheweb** [comment]
@HCanber @rogeralsing ok, we should definitely fix this before V1 then. Any takers?
