### ISSUE TITLE
how to installed the akka client to unity？

### ISSUE THREAD

**Issue by diybl** [akkadotnet/akka.net#4846]
is there some example？

**Comment by Arkatufus** [comment]
By Unity, do you mean the Unity game engine?

**Comment by Arkatufus** [comment]
@diybl By Unity, do you mean the Unity game engine?

**Comment by Arkatufus** [comment]
@diybl 
If by Unity you mean Microsoft Unity dependency injection framework, you might want to switch to Microsoft.Extensions.DependencyInjection instead.

If by Unity you mean Unity3D game engine, you can try this repo: https://github.com/Arkatufus/Akka.Unity.Sample
Its a bit outdated, but you can use it as a starting point.
