### ISSUE TITLE
Change Akka.Cluster dependency on Microsoft.Bcl.Immutable to System.Collections.Immutable

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#485]
Looks like within the past week or so (October 10th) Microsoft's moved the System.Collections.Immutable stuff to a new NuGet package:

http://www.nuget.org/packages/Microsoft.Bcl.Immutable/1.1.32-beta

> This package has been renamed to System.Collections.Immutable. Please reference the System.Collections.Immutable NuGet package from your projects instead of this package.

We should update Akka.Cluster's dependency to reflect this http://www.nuget.org/packages/System.Collections.Immutable/1.1.32-beta ONCE IT'S OUT OF PRE-RELEASE.

**Comment by rogeralsing** [comment]
Are we doing this or should it be closed?

**Comment by Aaronontheweb** [comment]
We'll do this, but not as part of V1.

**Comment by DamianReeves** [comment]
Any chance of relooking at this. I can't reference the new System.Collections.Immutable in my project because of Akka.Cluster's dependency on the old package.

**Comment by Aaronontheweb** [comment]
@DamianReeves yessir - looks like as of May 11th System.Collections.Immutable is out of pre-release so we can reference it.

Would you like to send a PR with the reference changed or should I do it?

**Comment by rogeralsing** [comment]
This could be worth a look https://t.co/LqznNv3VjQ apparently, it has better perf than BCL

**Comment by DavidHoerster** [comment]
Is this being worked on - I can help here.  Also, is the CodePlex project something to consider, or would that be a separate task since it's more of a breaking change?

**Comment by Aaronontheweb** [comment]
@DavidHoerster I ended up including this one in my latest PR - but I have some new issues i'm opening where I could use your help!
