### ISSUE TITLE
Akka.Cluster bug report

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#486]
Going to organize this into more individual issues, but I wanted to jot down my observations based on an actual integration with Akka.Cluster across three different services:

Akka.Cluster `Warning` messages appear to throw a string / log formatting exception, specifically the "attempted to join cluster with incorrect actor system name" message.

The following Akka.Cluster consistent hash group configuration does not appear to actually route any messages to the appropriate nodes:

````
/notificationsRouter{
                      router = consistent-hashing-group
                      nr-of-instances = 100
                      routees.paths = ["/user/api"]
                      cluster {
                        enabled = on
                        allow-local-routees = off
                        use-role = notifications
                      }
                    }
````

Associated Props:

    RemoteConsistentHashRouter = system.ActorOf(Props.Empty.WithRouter(new FromConfig()), "notificationsRouter");

The Akka.Remote functions for quarantining / gating connections appear to be overly aggressive in conjunction with Akka.Cluster - the cluster can very quickly move itself into a deadlocked state during startup, due to rapid connect / retry attempts. This does not normally happen in the course of standalone Akka.Remote operation (I've had nodes reestablish communication minutes later without issue.)

Self-joining seed nodes have a bit of trouble marking themselves as available - it looks like the first literal node to appear in the seed list gets preference for cluster leadership and "up" status. Not sure if this is a bug or not, but documenting it because it seems odd.

**Comment by Aaronontheweb** [comment]
@smalldave I've been able to run the MultiNodeTests over and over and over again and I get consistent results each time now. This has given me some confidence that the MultiNodeTestKit is working as expected.

**Comment by smalldave** [comment]
@Aaronontheweb have you only seen consistent passes fails or have you made any changes to make this happen?

**Comment by Aaronontheweb** [comment]
@smalldave the results are very consistent now. Got the `ClusterDeathWatchSpec` passing in #606. `InitialHeartbeatSpec` consistently fails but that's because most of it hasn't been implemented. All of the other tests pass with no issues at the moment.

My confidence in the MultiNodeTestRunner is solid - the reporting I get out of it is understandable and it's especially helpful to go through the JSON file it produces on completed runs.

And the child process debugger you recommended is a godsend; been using that a bunch.

http://blogs.msdn.com/b/visualstudioalm/archive/2014/11/24/introducing-the-child-process-debugging-power-tool.aspx

**Comment by Aaronontheweb** [comment]
Going to close this for now - the explicit bugs on this list have been addressed. Will create separate issues for new ones. Looks like the MultiNodeTestKit is able to run under most circumstances too.
