### ISSUE TITLE
Missing routees with round-robin-group on Azure Kubernetes

### ISSUE THREAD

**Issue by catnip-se** [akkadotnet/akka.net#4872]
Hi,

I'm having problem with Akka.Net 1.4.18 cluster aware routing where the router has not added all routees.
For test purposes we have a small hosted service in .NETCore and deployed two instances of it to Azure Kubernetes with the following deployment config.

```
 deployment {
	/commandrouter {
		router = round-robin-group
		routees.paths = ["/user/messageworker"]
		nr-of-instances = 2
		cluster {
			enabled = on
			allow-local-routees = on
		}
	}
}
```
In the service startup we have:

```
// Create worker
MyActorSystem.ActorOf(MessageActor.PropsOf(), "messageworker");
// Create router
var routerProps = Props.Empty.WithRouter(FromConfig.Instance);
_router = MyActorSystem.ActorOf(routerProps, "commandrouter");
```

The service is periodically sending messages to the local router instance but only 1 out of 2 messages are delivered and when asking the router for the routees only one routee seems to be correct.

In the first service instance (akka-cluster-0.akka-cluster:) we see:
```
#### Getting routees ######  
Akka.Routing.ActorSelectionRoutee, <ActorIdentity>: [akka://AkkaTest/user/messageworker#1265902127] - MessageId=0 
Akka.Routing.ActorSelectionRoutee, <ActorIdentity>:  - MessageId=1 
``` 		
where only the local routee is found.

and in the second one (akka-cluster-1.akka-cluster):
```
#### Getting routees ######
Akka.Routing.ActorSelectionRoutee, <ActorIdentity>: [akka.tcp://AkkaTest@akka-cluster-0.akka-cluster:5511/user/messageworker#1265902127] - MessageId=0
Routee = Akka.Routing.ActorSelectionRoutee, <ActorIdentity>:  - MessageId=1
```
where the remote routee is found, but not the local one.

So in this case all messages that are delievered (1 out of 2) are handled in the akka-cluster-0.akka-cluster service.

The get routee result is not the same everytime the services are started, sometimes only the local routee is found in both services.

pbm show cluster output:
```
	akka.tcp://AkkaTest@akka-cluster-0.akka-cluster:5511 | [] | up |  | 1.0.0
	akka.tcp://AkkaTest@akka-cluster-1.akka-cluster:5511 | [] | up |  | 1.0.0
	akka.tcp://AkkaTest@lighthouse-0.lighthouse:4053 | [lighthouse] | up |  | 1.4.0
	akka.tcp://AkkaTest@lighthouse-1.lighthouse:4053 | [lighthouse] | up |  | 1.4.0
	akka.tcp://AkkaTest@lighthouse-2.lighthouse:4053 | [lighthouse] | up |  | 1.4.0
```

Am I doing something in the wrong order here or is my configuration wrong?

Maybe not related but we also see a lot of debug messages like:
`[DEBUG][03/24/2021 11:37:17][Thread 0019][akka.tcp://AkkaTest@akka-cluster-1.akka-cluster:5511/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FAkkaTest%4010.244.0.1%3A42828-6] Association between local [tcp://AkkaTest@0.0.0.0:5511] and remote [tcp://AkkaTest@10.244.0.1:42828] was disassociated because the ProtocolStateActor failed: Unknown`

**Comment by Aaronontheweb** [comment]
Assigning this one to @IgorFedchenko

**Comment by IgorFedchenko** [comment]
Hi @catnip-se 

The configuration and code setup you are using looks good to me. 
I have created simple reproduction spec based on the data you provided (see #4885), but it works as expected, which means that this is either some edge case which has to be tested, or some non-Akka.NET problem (i.e. some Kubernetes configuration issue, etc).

To investigate this, I need some more details - if I will just put my code from the spec into docker container and run it in K8 we will most likely get the same results (both routees will be discovered).

Ideally would be to have the full source to reproduce the problem - maybe you can help with that? GitHub repo, or `zip` file containing solution sources. If this is not possible - please give as much info/source code as you can. Need to understand why in my case routees are discovered, and in your case they are not.

**Comment by catnip-se** [comment]
Thanks, I will try to put together a minimal solution reproducing the problem.

**Comment by catnip-se** [comment]
Hi @IgorFedchenko , I have attached a zip-file containing a solution that will reproduce the problem. In contrast to the problem in the original post, I have tested this on a local Docker Desktop, single-node kubernetes cluster. The outcome is the same though. 

One thing I have noticed is that when starting with two replicas, none of the instances correctly discovers the routees but when scaling up to 3 or 4 instances all new instances correctly discover routees. And if then restarting one of the two first pods, routees are discovered for that pod after restart. I have included some log files for that scenario.

One more thing I wonder about is, if a router fails to discover a routee, shouldn't messages be routed only to those routees that are actually discovered? Otherwise messages will be lost, as in this case.

[Akka.RoutingProblem_4872.zip](https://github.com/akkadotnet/akka.net/files/6254609/Akka.RoutingProblem_4872.zip)

Dockerfile and build script are located in the Service folder.

**Comment by catnip-se** [comment]
Hi, any estimate when this can be looked into? 
I'm having the same problem with consistent-hashing-group.

**Comment by IgorFedchenko** [comment]
Hi @catnip-se . I have to reassign this to Aaron for now, I think he will reply to you soon.

**Comment by catnip-se** [comment]
Ok, I think I have found the cause of this problem. It turned out to be a configuration problem after all. I hadn't defined any roles for the cluster and deployment. After adding the roles it works as expected. I guess the lost messages were somehow routed to lighthouse in this case. But I think the router should only route messages to nodes with valid routee actor paths.

**Comment by Aaronontheweb** [comment]
> But I think the router should only route messages to nodes with valid routee actor paths.

That's the end-user, to ensure that. We don't want to be in the business of asking our users "are you sure you meant to do X?" particularly when that involves querying actor selections across nodes. Glad you resolved your issue.
