### ISSUE TITLE
Create Setup class that allows users to customize Newtonsoft.Json serializer settings

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4877]
> https://github.com/akkadotnet/akka.net/blob/523e15c43c3927a8e14c34bd4647afdb7bf14dac/src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs#L237
> 
> Looks like this bit of code is causing havoc on exception (de)serialization. Any way to bypass it for exceptions?

You can always subclass the `NewtonsoftJsonSerializer` to bypass it. Maybe we can expose a `Setup` that will allow users to pass in custom converters and other types of programmatic configuration elements for the default JSON serializer. We already allow the `SerializerSetup` in Akka.NET which can specify serialization bindings programmatically.

_Originally posted by @Aaronontheweb in https://github.com/akkadotnet/akka.net/issues/3903#issuecomment-795597345_

----

Based on the referenced issue above, we should create [a `Setup` class](https://getakka.net/articles/concepts/configuration.html#programmatic-configuration-with-setup) that allows users to pass in customized settings for the `Newtonsoft.Json` serializer used by default.

This `Setup` would not change _any_ serialization bindings as that's already handled by [the `SerializerSetup` type](https://getakka.net/articles/networking/serialization.html#configuring-serialization-bindings-programmatically).

However, this class should allow users to customize the `NewtonSoftSerializerSettings` including converters and so on:

https://github.com/akkadotnet/akka.net/blob/21762b90ac1d7db670487dda1368d84c61d693e5/src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs#L27-L108

**Comment by Arkatufus** [comment]
Will a bad setup break Akka internal serialization?

**Comment by Aaronontheweb** [comment]
All Akka.Remote / Persistence / Cluster serialization is done via Protobuf anyway.
