### ISSUE TITLE
Akka.DependencyInjection.Tests AkkaDiFixture has problems causing the running to never stop

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/akka.net#4919]
Since we are using the new DI integration for Netcore in production. I went looking for ways to unit test akka Actors with the new DI integration.  And i found the UnitTests in the Akka.DependencyInjection.Tests project and copied that.

Then i ran into the issue that the TestRunner hangs after completion of tests. This has to do with the IClassFixture which uses the AkkaDiFixture.

This fixture class starts a netcore host to bootstrap the ServiceCollection. However it has 2 problems:

- It does Host.StopAsync().GetAwaiter().Result.Wait()
- Even if you implement the proper IAsyncLifetime interface which allows for proper async disposal, it still blocks the TestRunner.

Currently the CI for Akka does not notice this, but that does not mean its not happening ;)

**Comment by Aaronontheweb** [comment]
Nice catch @Danthar
