### ISSUE TITLE
Dependency Injection is not retrieving delegates

### ISSUE THREAD

**Issue by bauersystems** [akkadotnet/akka.net#4921]
- Akka version: 1.4.18
- Akka.DependencyInjection version: 1.4.18
- Platform: Windows 10
- Steps to reproduce:

Create a simple delegate:
`public delegate IActorRef BatchManagerActorProvider();`

Add the delegate as a Singleton:
`
services.AddSingleton<BatchManagerActorProvider>(provider =>
{
    IActorRef batchManagerActor = actorSystem.ActorOf(BatchManagerActor.CreateProps(), "batchManager");
    return () => batchManagerActor;
});
`

Attempt to retrieve the delegate via the Service Provider:
`var Actor = ServiceProvider.For(Context.System).Provider.GetService(typeof(BatchManagerActorProvider));`

Retrieving the delegate within an MVC controller works perfectly, so the delegate is registered successfully. Retrieving a standard class from the Service Provider in an Actor works perfectly too.

**Comment by Arkatufus** [comment]
How do you provide `actorSystem` in the singleton factory?
With Microsoft DI, you have to be careful with how you set up your DI. You have to make sure that the instance you're trying to access is actually instantiated when it is invoked/accessed in the service provider.

**Comment by Arkatufus** [comment]
Please see #4922
In the PR, I've outlined the correct instantiation of instances for the DI to work, if you're trying to access the actor system using the service provider itself.
In essence, you have to wrap the `ActorSystem` itself as a singleton inside the `ServiceProvider`, (in the PR case, using IHostedService), and then immediately starts it after the service provider is created. If you're using microsoft hosted service worker template or ASP.NET, the `IHostedService.StartAsync` method will be invoked automatically when the host application is run, making sure that the `ActorSystem` is available to any services registered in the `ServiceProvider`.

**Comment by bauersystems** [comment]
Regarding the `ActorSystem` I create it as a singleton and then pull it from dependency injection in the delegate singleton factory. Sorry, I left that part out above to keep it brief.

#4922 is not quite what I meant. Accessing the delegate outside the `ActorSystem` works great, when I try to access it from within an actor, I get a null value assigned.

I'll put together a gist over the next couple of days to demonstrate it.

**Comment by Arkatufus** [comment]
OK. I'll wait for your gist.
In the mean time, I've updated the PR to include a case where the delegate is being called from inside an actor.

**Comment by bauersystems** [comment]
Check out the following repository https://github.com/bauersystems/AkkaDelegateDiExample

In the ActorServices.cs file on lines 28 & 29, if you change between the two CreateProps methods, you will see that:
- Using the Akka ServiceProvider causes an error saying that the InjectableActorProvider hasn't been registered;
- However passing in the provider used to register the MainActor singleton works successfully.

**Comment by aloker** [comment]
https://github.com/bauersystems/AkkaDelegateDiExample/blob/f1ca0135614150a092bd5dc4df12688a6a112169/ActorServices.cs#L16

You are calling BuildServiceProvider here before the delegates are even registered. You'll end up with two service providers in your app,. The one passed to InitialiseActorSystem does not know about the delegates.

Instead, try creating the actor system lazily:

```c#
services. AddSingleton(serviceProvider => InitialiseActorSystem(serviceProvider));
```

**Comment by bauersystems** [comment]
Thanks @aloker that fixed my problem.
