### ISSUE TITLE
Microsoft.Extensions.Logging Integration

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4937]
Based on the data so far, our rework of Akka.DependencyInjection to integrate with Microsoft.Extensions.DependencyInjection has been quite successful and popular with users even though the package has only been available for a short period of time thus far.

I'm interested in doing something similar with Microsoft.Extensions.Logging or perhaps the logging system in general:

- Create a new `Setup` type that allows for programmatic configuration of Akka.NET's loggers (the input type would be a `Props` to start the underlying logging actor)
- Allow downstream logging libraries to subclass or somehow extend aforementioned `Setup` to include references to programmatically configured serializers such as a `Microsoft.Extensions.Logging.ILogger` or a `Serilog.ILogger`

I wonder if this might help make it easier to connect Akka.NET with additional logging systems and infrastructure developed by users. Akka.NET is still going to use its `ILoggingAdapter` to produce logs from inside its actors, but making it easier to pipe that data out to another configured logger has always been the goal of the `Akka.Logger*` NuGet packages. This might be an easier way of doing that.

>N.B. it's self-defeating and bad to use an external `ILogger` directly inside an actor instead of an `ILoggingAdapter`, and you should immediately change your code if you're doing this today.

**Comment by markusschaber** [comment]
There's already a 3rd party implementation: https://www.nuget.org/packages/Akka.Logger.Extensions.Logging/1.4.22

I did not try it yet myself, but maybe it can be "adopted" or integrated as the official solution?

**Comment by Aaronontheweb** [comment]
We now have a prototype of `ILogger` support built into Akka.Hosting: https://github.com/akkadotnet/Akka.Hosting/releases/tag/0.4.0

Recommend giving that a try - that's going to be out likely "official" solution.
