### ISSUE TITLE
Timed out ClientResponseTunnel blocks pub-sub communications

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/akka.net#4971]
Timed out ClientResponseTunnel blocks further communication between ClusterClientReceptionist and the DistributedPubSubMediator.
A work around is to keep the response tunnel actor from timing out by sending periodic keep alive ping messages, but this is not optimal and is not how it intended to work.

**Comment by Aaronontheweb** [comment]
This is not a bug, right?

**Comment by simonlaroche** [comment]
To be clear, this occurs if a Cluster Client subscribes to a topic with the DistributedPubSubMediator and no messages are published to the topic within the `akka.cluster.client.receptionist.response-tunnel-receive-timeout`.
