### ISSUE TITLE
Documentation flaw for "Forward"

### ISSUE THREAD

**Issue by dnickless** [akkadotnet/akka.net#4973]
https://getakka.net/articles/actors/receive-actor-api.html#forward-message states
![image](https://user-images.githubusercontent.com/985774/115659020-33f42100-a33a-11eb-90ff-94971541651a.png)
which I don't think is correct or even possible (nowadays?) looking at the sources: https://github.com/akkadotnet/akka.net/blob/21762b90ac1d7db670487dda1368d84c61d693e5/src/core/Akka/Actor/ActorRef.cs#L208

**Comment by Aaronontheweb** [comment]
@dnickless yep, that's definitely a documentation error.
