### ISSUE TITLE
Extreme startup time of `ActorSystem` in WinForms

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#499]
When starting an `ActorSystem` in a windows forms app, I get this warning. and the startup time seems to be around that timespan also (5 sec)

```
[WARNING][2014-11-16 18:59:56][Thread 0009][EventStream(fractal)] 
Logger EventStream(fractal) did not respond within 00:00:05 to InitializeLogger(bus)
```

I guess that the `SynchronizationContext` is involved somehow, and that the loggers get resolved on the GUI thread or something like that.
AFAIK we still use async await when resolving loggers?
Maybe we need to specify an explicit TaskScheduler there (?)

**Comment by PatrickMcDonald** [comment]
I get this message also in F# interactive. My script is as follows:

    #r "../packages/Akka.1.0.0/lib/net45/Akka.dll"
    open Akka.Actor

    let system = ActorSystem.Create "MySystem"

**Comment by rogeralsing** [comment]
```
[DEBUG][2015-04-16 14:11:14][Thread 0009][EventStream] StandardOutLogger started
[WARNING][2015-04-16 14:11:19][Thread 0009][EventStream(fractal)] Logger EventStream(fractal) did not respond within 00:00:05 to InitializeLogger(bus)
[DEBUG][2015-04-16 14:11:19][Thread 0009][EventStream(fractal)] StandardOutLogger being removed
```

```csharp
var config = ConfigurationFactory.ParseString(@"
akka {  
    log-config-on-start = on
    stdout-loglevel = DEBUG
    loglevel = ERROR   
}");
ActorSystem system = ActorSystem.Create("fractal",config);
```

**Comment by rogeralsing** [comment]
This have been solved somehow somewhere. it is no longer an issue
