### ISSUE TITLE
Persistent actor receives duplicated events after restart during recovery with akka 2.6.14

### ISSUE THREAD

**Issue by thedevd** [akkadotnet/akka.net#5004]
Although there is already a ticket on this issue (https://github.com/akkadotnet/akka.net/issues/1403), but there it was mentioned that v2.4 is supposed to have the fix. But I am facing the same problem with version 2.6.14 where I see during recovery, same event is replayed twice and thus RecoveryCompleted() event is also seen twice.

**Comment by patriknw** [comment]
Thanks for reporting. Can you describe how to reproduce the issue in more detail. It would be great if you have example code or example application that we can run.

**Comment by thedevd** [comment]
Sorry to bother, but I resolved it. It seems the problem of creating PersistentActor in another Actor as child just to watch it in case if it dies. So after I removed that testing/debugging piece of code, it started working. So closing this, no need to work.

**Comment by patriknw** [comment]
and  note that this is akka.net repository. JVM Akka is at  https://github.com/akka/akka
