### ISSUE TITLE
No way to provide IServiceCollection to MultiNodeClusterSpec created ActorSystem

### ISSUE THREAD

**Issue by chris-sung** [akkadotnet/akka.net#5027]
- Which Akka.Net version you are using
 1.4.20
- On which platform you are using Akka.Net
 net5

Hey guys, I've been digging MNTR testing and having a hard time providing IServiceCollection to **MultiNodeClusterSpec** derived classes since **MultiNodeClusterSpec** constructor only accepts Config, no **ActorSystemSetup**.

It seems manual creating of ActorSystem is possible here:

https://github.com/akkadotnet/akka.net/blob/b5f6552a719cb75686686af69e8744f77bf47e3f/src/core/Akka.Remote.TestKit/MultiNodeSpec.cs#L394-L410

But this is not:
https://github.com/akkadotnet/akka.net/blob/b5f6552a719cb75686686af69e8744f77bf47e3f/src/core/Akka.Cluster.TestKit/MultiNodeClusterSpec.cs#L151-L158

Am I missing something? is there any way other than copy-pasta MultiNodeClusterSpec.cs and reimplement it?

**Comment by Aaronontheweb** [comment]
> Hey guys, I've been digging MNTR testing and having a hard time providing IServiceCollection to MultiNodeClusterSpec derived classes since MultiNodeClusterSpec constructor only accepts Config, no ActorSystemSetup.

I think that's the fix - we just need to allow the MNTR to accept an `ActorSystemSetup`. 

@Arkatufus do you think this is doable for v1.4.21?

**Comment by Arkatufus** [comment]
I'll work on it
