### ISSUE TITLE
Cluster Sharding - Deprecating Persistence State Store

### ISSUE THREAD

**Issue by christallire** [akkadotnet/akka.net#5049]
- Which Akka.Net version you are using
1.4.20
- On which platform you are using Akka.Net
net5

Hi guys,
I'm not sure why akka team is deprecating the persistence state store and DData is the default mode, is there a plan to do the same on akka.net?

ref: https://doc.akka.io/docs/akka/current/typed/cluster-sharding.html#state-store

**Comment by Aaronontheweb** [comment]
@christallire so Akka.Cluster.Sharding came out of beta last February (when Akka.NET v1.4 was released) - the bulk of that effort was getting Akka.DistributedData out of beta as well. 

We're still working on some issues that prevent DData from replacing 100% of the functionality that Akka.Persistence provides today, for instance: 

* https://github.com/akkadotnet/akka.net/issues/5022
* https://github.com/akkadotnet/akka.net/issues/4873
* https://github.com/akkadotnet/akka.net/issues/3083

This is all being worked on aggressively by our team now though, as there are many more users switching over to DData. We will probably be able to deprecate Akka.Persistence support after Akka.NET 2.0 or 1.5 is released.

**Comment by to11mtm** [comment]
> 
> 
>     * Which Akka.Net version you are using
>       1.4.20
> 
>     * On which platform you are using Akka.Net
>       net5
> 
> 
> Hi guys,
> I'm not sure why akka team is deprecating the persistence state store and DData is the default mode, is there a plan to do the same on akka.net?
> 
> ref: https://doc.akka.io/docs/akka/current/typed/cluster-sharding.html#state-store

There's a couple reasons that JVM akka is trying to deprecate the persistence state store, although my understanding was the maintaining of both setups is a bit of a hassle.

However, there's a bit more nuance to the changes in JVM Akka. In addition to DData, there is the `EventSourced` based API [here's a PR that even has a cool PDF with details](https://github.com/akka/akka/pull/29219) which is to my understanding still able to use Persistence under the hood.

They also outline some cases in [this issue](https://github.com/akka/akka/issues/27763) describing some of the reasons that you may want to be careful in considering the switch to DData.

**Comment by christallire** [comment]
@to11mtm Thanks for such a detailed explanation. cool PDF tho.

**Comment by ismaelhamed** [comment]
In fact @zbynek001 started working on it #4629

**Comment by Aaronontheweb** [comment]
This has been completed as part of 1.5.
