### ISSUE TITLE
Akka.Cluster.Sharding: entity actors should run on `akka.actor.default-dispatcher`, not `akka.actor.internal-dispatcher`

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#5063]
**Version Information**
Version of Akka.NET? v1.4.20
Which Akka.NET Modules? Akka.Cluster.Sharding

**Describe the bug**
It looks like the the actual entity actors started by Akka.Cluster.Sharding are running on the `/system` dispatcher, which is not ideal as it consumes the same cycles that are needed for things like the sharding actors themselves.

**Expected behavior**
Sharded entity actors should run on the `/user` actor hierarchy.

**Actual behavior**
To be determined - needs investigation.

**Comment by ismaelhamed** [comment]
Dispatcher for entity actors is set at this line: 

https://github.com/akkadotnet/akka.net/blob/2715c36ee20640ad343ffd02a73fbce0d5cf9f0e/src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs#L1173

... which defaults to `Dispatchers.DefaultDispatcherId` if not set, or uses the dispatcher specified by the user in the `entityProps` parameter in `ClusterSharding.Start()`, AFAICT

**Comment by Aaronontheweb** [comment]
Ok, seems like this is a non-issue then.
