### ISSUE TITLE
TimestampProvider not working or not being used

### ISSUE THREAD

**Issue by MartijnSchoemaker** [akkadotnet/akka.net#5076]
**Version Information**
Version of Akka.NET? 
1.4.19

Which Akka.NET Modules?
Akka.Persistence.Sql.Common.Journal

**Describe the bug**
I implemented a custom `ITimestampProvider` for SQL Persistence Journal.
I put a breakpoint in `GenerateTimestamp()` and let this method return 0. 
But every time I persist an entity I keep seeing DateTime.UtcNow.Ticks used as TimeStamp.

**To Reproduce**
1. Added customer `ITimestampProvider`. Let method return 0.
2. Add config:
` persistence : {
      journal : {
        plugin : akka.persistence.journal.sql-server
        sql-server : {
          timestamp-provider : "xx.xx.xx, xx.xx"
        }
      }`
3. Persist entity
4. Look in EventJournal table and see TimeStamp is a big long (not 0).

**Expected behavior**
Use long returned by custom `ITimestampProvider`.

**Actual behavior**
DateTime.UtcNow.Ticks is used as TimeStamp.

**Additional context**
I tried to debug this and found out that in `SqlServerJournal` line 62 is returning an instance of my own `TimetampProvider`. So that seems to work! 
https://github.com/akkadotnet/Akka.Persistence.SqlServer/blob/6f9eae1f0d17ab76adf60809e2a631d8acfa2e82/src/Akka.Persistence.SqlServer/Journal/SqlServerJournal.cs#L62

But another thing I saw in the source is that in `AbstractQueryExecutor` the TimestampProvider is passed as parameter, but only the property is set. It seems that the property is never used.
https://github.com/akkadotnet/akka.net/blob/55c117566bb7176351a4e2bc40e471e87f8eecfc/src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs#L319

In InsertBatchAsync as timestamp is used 'DateTime.UtcNow.Ticks'. I should expect the TimestampProvider being used here?
https://github.com/akkadotnet/akka.net/blob/55c117566bb7176351a4e2bc40e471e87f8eecfc/src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs#L687

**Screenshots**
<img width="1561" alt="Schermafbeelding 2021-06-07 om 13 33 48" src="https://user-images.githubusercontent.com/2683569/121014682-89757780-c79a-11eb-9524-b6dd0ba7bfda.png">
<img width="1138" alt="Schermafbeelding 2021-06-07 om 13 30 55" src="https://user-images.githubusercontent.com/2683569/121015099-e7a25a80-c79a-11eb-947c-6814821e8422.png">
<img width="1015" alt="Schermafbeelding 2021-06-07 om 13 30 23" src="https://user-images.githubusercontent.com/2683569/121015105-e96c1e00-c79a-11eb-85f4-0c06a83b44cf.png">

**Comment by Aaronontheweb** [comment]
This looks like a bug alright! We'll see if we can get this patched before we do v1.4.21 later this week.

**Comment by Aaronontheweb** [comment]
Should actually be a pretty trivial fix - just need to have the timestamp provider call there instead of `DateTime.UtcNow.Ticks`.

**Comment by MartijnSchoemaker** [comment]
Yes indeed. Thats what I thought as well. But I'm not really into the code, so I thought probably I missed something and I did something wrong... 😊

**Comment by Aaronontheweb** [comment]
@MartijnSchoemaker feel free to send us a PR if you want! 👍

**Comment by ismaelhamed** [comment]
Since the concept of `TimestampProvider` does not exist in the JVM, this was an oversight while porting the `Timestamp` support for envelopes.

**Comment by Aaronontheweb** [comment]
@ismaelhamed I figured as much - no big deal. This is the first time in ~7 years I've ever heard of someone actually customizing the `ITimestampProvider`....

**Comment by MartijnSchoemaker** [comment]
We get a list of mutations of an object from another party every 5 weeks.
In that data are mutations for example for 3 days ago. We need to be able to get the state of the object for a specific date. So its neccesary for us to add mutations (events) with a date in the past. 
Thats why I was happy that I found the timestamp provider.😅

**Comment by Aaronontheweb** [comment]
@MartijnSchoemaker makes sense!

**Comment by MartijnSchoemaker** [comment]
@Aaronontheweb 
We're now using **Akka.Persistence.Query.Sql** version **1.4.21** and I'm trying to implement `ITimestampProvider`. But my change seems not be applied to the **Akka.Persistence.Sql.Common** package. 

**Akka.Persistence.Query.Sql 1.4.21** uses **Akka.Persistence.Sql.Common 1.4.21-beta** package. I decompiled the dll from that NuGet package but it's still using `DateTime.UtcNow.Ticks` instead of the `ITimestampProvider`. As you can see in the image. This is also the case for all newer versions of ***.Common**.

<img width="1095" alt="Schermafbeelding 2021-08-11 om 10 30 10" src="https://user-images.githubusercontent.com/2683569/128996666-44bb07d9-fe55-4bfd-a392-2c5460052c83.png">
