### ISSUE TITLE
 `IDependencyResolver.GetService<T>()` is returning `object` rather than `<T>`

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#5086]
During upgrading to 1.4.21-beta1 we saw that `IDependencyResolver.GetService<T>()` is returning `object`. Is there a specific reason why it is not directly returning `<T>`?
Now we need to cast it to `T` before we can use the object.

_Originally posted by @wesselkranenborg in https://github.com/akkadotnet/akka.net/discussions/5070#discussioncomment-840243_

We should update the API to change this.

**Comment by wesselkranenborg** [comment]
Thanks for solving this, this will ease the update and saves a lot of casts.

**Comment by Aaronontheweb** [comment]
No problem!
