### ISSUE TITLE
Converting Source to Observable deadlocks on interaction with Reactive Extensions

### ISSUE THREAD

**Issue by TheAngryByrd** [akkadotnet/akka.net#5111]
**Version Information**
Version of Akka.NET?  1.4.21
Which Akka.NET Modules? Akka.Streams

**Describe the bug**
Converting a `Source` to an `Observable` seems to deadlock on interaction with Reactive Extensions.  Meaning any calls that fall under `System.Reactive.Linq` such as `Select` stop the `Observable` from producing any values.

**To Reproduce**

1. Create a `Source` from some data
2. Convert that `Source` to and `Observable`
3. Try to use `Select` on that `Observable`
4. Subscribe to that `Observable` then wait until it produces (in this case it doesn't)

https://github.com/TheAngryByrd/akka-stream-observable-deadlock-repro

**Expected behavior**

Ability to use any of `System.Reactive`'s functions on an `Observable`

**Actual behavior**

Doesn't have the ability to use any of `System.Reactive`'s functions on an `Observable`

**Screenshots**
n/a

**Environment**

```bash
.NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.300/
 ```

**Additional context**

**Comment by Arkatufus** [comment]
This is by design. When you do a `Select`, the selector automatically pulls from the source, emptying everything in the enumerable source. The `Subscribe` call came in after everything was emptied, making it look like a "deadlock", when it is actually waiting on a completed source, which does nothing.

In essence, a `Select` only works properly if you have a publisher backed source.

**Comment by Aaronontheweb** [comment]
@Arkatufus would a `PreMaterialize` call to get the `IObservable` resolve this issue in that case?

**Comment by Arkatufus** [comment]
@Aaronontheweb yes, one solution would be something like this:
```
var observer = new MyObserver<string>(this);
var (observable, sink) = Sink.AsObservable<int>().PreMaterialize(Materializer);
observable.Select(i => i.ToString()).Subscribe(observer);

Source.From(new[] { 1, 2, 3 }).RunWith(sink, Materializer);
```

**Comment by Aaronontheweb** [comment]
Does that resolve your issue @TheAngryByrd ?

**Comment by TheAngryByrd** [comment]
> This is by design. When you use `AsObservable`, the logic automatically pulls from the source, emptying everything in the enumerable source. The `Subscribe` call came in after everything was emptied, making it look like a "deadlock", when it is actually waiting on a completed source, which does nothing.
> 
> In your context, an `AsObservable` only works properly if you have a publisher backed source or if you start streaming data after you subscribed to the `IObservable`.

Thank you, this explanation makes sense.  I can make some accommodations to make sure it know it's a `hot` observable.

---

As the docs issues states, this can be confusing as the observable is `hot` immediately after its call to `AsObservable`. Would it make sense to start the `Pull` on the first time something was subscribed? Such as move the [initial pull call](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Streams/Implementation/Sinks.cs#L1208) to the [Subscribe](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Streams/Implementation/Sinks.cs#L1216) implementation? Or potentially have a separate implementation that starts this as `cold` rather than `hot`?

**Comment by Aaronontheweb** [comment]
> Would it make sense to start the Pull on the first time something was subscribed? Such as move the initial pull call to the Subscribe implementation? 

I think it would

> Or potentially have a separate implementation that starts this as cold rather than hot?

I can't imagine a use case where it's useful to start draining the source before anyone is subscribed to it. Maybe we should update the Rx Interop?

**Comment by Aaronontheweb** [comment]
cc @Arkatufus do you agree with the above or am I missing something?

**Comment by Arkatufus** [comment]
We can always change `AsObservable<T>()` to `AsObservable<T>(bool pullImmediately = true)`?
This will make the observable to wait until the first subscribe call, but then again the same problem would happen with all the subscribers after the first.
Another option would be to create an overload `AsObservable<T>(IObserver[] observers)`.

**Comment by TheAngryByrd** [comment]
> This will make the observable to wait until the first subscribe call, but then again the same problem would happen with all the subscribers after the first.

Rx does have this concept with the idea of a [IConnectableObservable](https://docs.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh211748(v=vs.103)).  Short story, it lets the caller dictate when it should start the pump but you assume after that you know that subscribing after that point you will miss messages.

**Comment by TheAngryByrd** [comment]
For future reference, I solved my cold/hot problem by using [Observable.Create](https://docs.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh229114(v=vs.103)) since I have a reference to `System.Reactive`  While this doesn't support multiple subscribers, using `IConnectableObservable/Connect()/Publish()` works fine if that is needed. In my case it was not.

Code:

```fsharp

/// See: https://github.com/dotnet/reactive/blob/9f2a8090cea4bf931d4ac3ad071f4df147f4df50/Rx.NET/Source/src/System.Reactive/Concurrency/TaskHelpers.cs#L32
let getSingleExeception(t : Task) =
    if t.Exception.InnerException |> isNull |> not then
        t.Exception.InnerException
    else
        upcast t.Exception

/// Maps task completion to observer emits
/// See: https://github.com/dotnet/reactive/blob/9f2a8090cea4bf931d4ac3ad071f4df147f4df50/Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs#L155
let emitTaskResult (o :IObserver<_>) (t : Task)  =
    match t.Status with
    | TaskStatus.RanToCompletion -> o.OnCompleted ()
    | TaskStatus.Faulted -> t |> getSingleExeception |> o.OnError
    | TaskStatus.Canceled -> t |> TaskCanceledException |> o.OnError
    | _ -> ()

let toObservable (materializer : IMaterializer) (source : Source<_,_>) =
    Observable.Create<_>(fun (o: IObserver<'c>) ->
        try
            source.RunForeach((fun i -> o.OnNext i), materializer)
                .ContinueWith(emitTaskResult o)                
            |> ignore
        with e -> o.OnError e
        Disposable.Empty
    )
```
