### ISSUE TITLE
CircuitBreaker's Open state should return a faulted Task instead of throwing

### ISSUE THREAD

**Issue by ismaelhamed** [akkadotnet/akka.net#5117]
**Version Information**  
Akka 1.4.21

**Describe the bug**  
CircuitBreaker's `Open` and `HalfOpen` states should return a faulted `Task` with the `OpenCircuitException` exception instead of throwing.

**To Reproduce**

```csharp
circuitBreaker.WithCircuitBreaker(dangerousAsyncOperation)
    .PipeTo(Self, failure: exception => new Success.Failure(exception));
```

**Expected behavior**  
Be able to handle the `OpenCircuitException` with just the `PipeTo`, without needing to add another `ContinueWith` to the mix.

**Actual behavior**  
`OpenCircuitException` cannot be handled in the failure callback, and the actor restarts due to the unhadled exception.

**Proposed fix**  
Return a faulted `Task`:

```csharp
public override Task Invoke(Func<Task> body) => Task.FromException(
    new OpenCircuitException(_breaker.LastCaughtException, RemainingDuration()));

```

...instead of throwing

```csharp
public override Task Invoke(Func<Task> body) =>
    throw new OpenCircuitException(_breaker.LastCaughtException, RemainingDuration());
```

**Comment by Aaronontheweb** [comment]
Agree - do we need to break the existing API in order to do this?

**Comment by ismaelhamed** [comment]
Not the API, but if someone is wrapping the calls to the CB in a `try... catch` (for whatever reason), that won't work anymore. I couldn't find anything like that in our code base except for this piece in the `SnapshotStore`:

```csharp
try
{
    ReceivePluginInternal(message);
    _breaker.WithCircuitBreaker(() => DeleteAsync(saveSnapshotFailure.Metadata));
}
finally
{
    senderPersistentActor.Tell(message);
}
```

But I don't think the intent was to catch any exception throwing in the CB but in the call to `ReceivePluginInternal`. In fact, [here is the same code in scala](https://github.com/akka/akka/blob/031886a7b32530228f34176cd41bba9d344f43bd/akka-persistence/src/main/scala/akka/persistence/snapshot/SnapshotStore.scala#L71), and AFAIK you cannot catch exceptions wrapped in a `Future` with a `try... catch` either.

**Comment by ismaelhamed** [comment]
@Aaronontheweb any thoughts?

**Comment by Aaronontheweb** [comment]
Looks good to me - let's go for it.

**Comment by Aaronontheweb** [comment]
Sorry for the delay on getting back to you on this @ismaelhamed - this change looks safe.
