### ISSUE TITLE
ddata replicator stops but doesn't look like it can be restarted easily

### ISSUE THREAD

**Issue by andyfurnival** [akkadotnet/akka.net#5129]
**Is your feature request related to a problem? Please describe.**
I  got this error raised in my system `Stopping distributed-data Replicator due to load or startup failure in durable store, caused by: "failed to load durable distributed-data"` which was caused by a sudden large spike in memory causing OOM. The issue was momentary, and whilst the rest of the actor system remained up and working (memory recovered), the ddata replicator never started back up.  This occurred on 2 of 7 nodes, so there was a trigger, but not cataclysmic event, which leads me to believe it may be possible to have a more fault tolerant supervisor strategy for the ddata replicator.

**Describe the solution you'd like**
looking at the code, I wonder if it can be improved to at least try again over a short period of time, maybe try 3 times over 30 seconds, to let the system get back into order?    We have this today for the supervisor
```
 protected override SupervisorStrategy SupervisorStrategy() => new OneForOneStrategy(e =>
        {
            var fromDurableStore = Equals(Sender, _durableStore) && !Equals(Sender, Context.System.DeadLetters);
            if ((e is LoadFailedException || e is ActorInitializationException) && fromDurableStore)
            {
                _log.Error(e,
                    "Stopping distributed-data Replicator due to load or startup failure in durable store, caused by: {0}",
                    e.Message);
                Context.Stop(Self);
                return Directive.Stop;
            }
            else return Actor.SupervisorStrategy.DefaultDecider.Decide(e);
        });
```

to something like this (may be something to make more configurable perhaps)
```
protected override SupervisorStrategy SupervisorStrategy() => new OneForOneStrategy(3, TimeSpan.FromSeconds(30), e =>
        {
            var fromDurableStore = Equals(Sender, _durableStore) && !Equals(Sender, Context.System.DeadLetters);
            if ((e is LoadFailedException || e is ActorInitializationException) && fromDurableStore)
            {
                _log.Error(e,
                    "Stopping distributed-data Replicator due to load or startup failure in durable store, caused by: {0}",
                    e.Message);
                Context.Stop(Self);
                return Directive.Stop;
            }
            else return Actor.SupervisorStrategy.DefaultDecider.Decide(e);
        });
```
If my data is going to become inconsistent across the cluster if replicator fails and cannot restart, I may have to consider shutting down the failed node, so as not to process messages, where I may rely on replicated data being present. I could very likely do this without exposing any new functionality from akka.net I believe, assuming I can watch the replicator actor, but it maybe something to consider as ddata is used more, to have some sort of cluster failsafe if replication fails.

**Describe alternatives you've considered**
I've looked to see if I can watch the replicator actor, and some how restart it myself. I've not tried it yet, but the code looks like it could be immutable, and unrecoverable from user code.

**Additional context**

**Comment by Aaronontheweb** [comment]
It should be possible to wrap the replicator in [a `BackoffSupervisor` and have that recreate the actor](https://getakka.net/articles/concepts/supervision.html#delayed-restarts-with-the-backoffsupervisor-pattern) using an exponential retry + backoff strategy in the event that it fails. Would that work?

**Comment by andyfurnival** [comment]
I think it would, I think this would be better having exponential back off, as that could try for a bit longer before giving in

**Comment by Aaronontheweb** [comment]
> I think it would, I think this would be better having exponential back off, as that could try for a bit longer before giving in

You should be able to wrap the replicator in a `BackoffSupervisor` today in your own code without having to wait for an update. Do you want to give that a try and let us know if it helps things?

**Comment by Aaronontheweb** [comment]
And if that doesn't work, we can certainly try to fix it some other way.

**Comment by andyfurnival** [comment]
I’ll give it a go, when I was looking into it earlier, it looked like I couldn’t really access the actor lifecycle, as it’s created by something internal (something that also supports akka extension) - I’ve not got the code in front of me to check 

If that doesn’t work, I’ll see if I can alter the implementation itself and see how that goes

**Comment by Aaronontheweb** [comment]
You're right - looks like this is being done internally by the plugin:

```csharp
using Akka.DistributedData;
using static Akka.DistributedData.Dsl;

var replicator = DistributedData.Get(system).Replicator;
var key = new ORSetKey<string>("keyA");
var readConsistency = ReadLocal.Instance;

var response = await replicator.Ask<Replicator.IGetResponse>(Get(key, readConsistency));
if (response.IsSuccessful) 
{
    var data = response.Get(key);    
}
```

I had assumed that you had to create the replicator manually and get an `IActorRef` back to it. Not sure where I got that idea from. So this is something we'll have to patch on our end then.

**Comment by andyfurnival** [comment]
Made a suggested PR for this https://github.com/akkadotnet/akka.net/pull/5143

**Comment by ismaelhamed** [comment]
> I had assumed that you had to create the replicator manually and get an `IActorRef` back to it. Not sure where I got that idea from. So this is something we'll have to patch on our end then.

That's how it should work (via `Replicator.Props` since the `DistributedData` extension is for convenience), but the `Replicator` is marked `internal` in Akka.NET

**Comment by ismaelhamed** [comment]
@Aaronontheweb `Replicator` is already sealed, but it needs to be public. Currently you cannot access it from outside `Akka.DistributedData`.

Now, regarding the issue itself, I'm curious as to why the `Replicator` just shuts down when there's a problem with its durable store, instead of restarting.

**Comment by Aaronontheweb** [comment]
@ismaelhamed this is why, I believe:

https://github.com/akkadotnet/akka.net/blob/21762b90ac1d7db670487dda1368d84c61d693e5/src/contrib/cluster/Akka.DistributedData/Replicator.cs#L425-L437

**Comment by ismaelhamed** [comment]
My thoughts exactly. It seems unlikely that the Akka team didn't thought of that, or that nobody in the Scala/Java community has ever faced this problem before.

**Comment by Aaronontheweb** [comment]
@ismaelhamed so given that, is the approach to use a `BackoffSupervisor` here fundamentally misguided? If the Replicator fails at startup, there isn't much state that can be diverged since the replication process is only just starting

**Comment by ismaelhamed** [comment]
The proposed solution looks right to me. But maybe we're missing something, just saying.
