### ISSUE TITLE
Modify Ask

### ISSUE THREAD

**Issue by HCanber** [akkadotnet/akka.net#516]
This example illustrate two problems with `Ask` returning a Task inside actors:
``` C#
actor.Ask<int>("Hi").ContinueWith(t => {
   stateVariable += t.Result;
   Sender.Tell(t.Result, Self);
}
```
1. The continuation is executed outside the actor context, so `Self` & `Sender` will have undefined values.
2. The concurrency constraint is broken, so mutating state is unsafe.

However, `Ask` and awaitng an answer is very valuable from the outside world so we need to have that there.

One suggestion is to remove Ask as pattern from inside the actors, but keep it for actors accessed from the outside:
- Change `ActorRef` to an interface. When returning an actor from `ActorSystem.ActorOf` we return a new interface with the (working) name `OutsideActorRef`. It inherits from `ActorRef` but does not add anything new. 
- Move the `Ask` support from `ActorRef` to `OutsideActorRef`.
- We might need to add a new interface `OutsideActorSystem` that contains the new `ActorOf`s and it's returned from `ActorSystem.Create`. (`IActorContext.System` would still return `ActorSystem` with the normal `ActorOf`s)

**Comment by rogeralsing** [comment]
As this is now also safe to use from the async api, Im closing this
