### ISSUE TITLE
The pbm cmd cluster-sharding region-stats shows wrong entity numbers

### ISSUE THREAD

**Issue by fscavo** [akkadotnet/akka.net#5218]
**Version Information**
Version of Akka.NET? 1.4.24
Which Akka.NET Modules?
Akka.Cluster
Akka.Cluster.Sharding

**Describe the bug**
The following command shows 47 entities
```
[127.0.0.1:9110] pbm> cluster-sharding region-stats -r user
akka.tcp://notification-service@172.16.0.145:2552 | [service] | up |  | 1.0.0 [coordinator](user) | shards: 0 | entities: 0
akka.tcp://notification-service@172.16.7.249:2552 | [service] | up |  | 1.0.0 | shards: 1 | entities: 47
akka.tcp://notification-service@172.16.10.1:2552 | [service] | up |  | 1.0.0 | shards: 0 | entities: 0
```
while this command shows no entities under system actor
```
[127.0.0.1:9110] pbm> actor hierarchy -s akka.tcp://notification-service@172.16.0.145:2552/system -d 5
```
**Expected behavior**
I expect the same amount of entities being shown under system actor

**Actual behavior**
No entity has been shown under system actor

**Comment by Aaronontheweb** [comment]
@fscavo I think this is because you're querying the wrong node in this case:

```
[127.0.0.1:9110] pbm> actor hierarchy -s akka.tcp://notification-service@172.16.0.145:2552/system -d 5
```

`akka.tcp://notification-service@172.16.7.249:2552` is the node that has all of the entities in the original readout above.

Let me see if there's an issue with getting a print out of `/system` actors, however. That could be an issue.

**Comment by fscavo** [comment]
> @fscavo I think this is because you're querying the wrong node in this case:
> 
> ```
> [127.0.0.1:9110] pbm> actor hierarchy -s akka.tcp://notification-service@172.16.0.145:2552/system -d 5
> ```
> 
> `akka.tcp://notification-service@172.16.7.249:2552` is the node that has all of the entities in the original readout above.
> 
> Let me see if there's an issue with getting a print out of `/system` actors, however. That could be an issue.

You are right. I thought I would get the hierarchy of all actors in actor system from any node :)

**Comment by Aaronontheweb** [comment]
@fscavo With a little bit of work, we could probably manage that through the Akka.Cluster `pbm` module
