### ISSUE TITLE
akka.actor.guardian-supervisor-strategy set to Akka.Actor.StoppingSupervisorStrategy doesn't terminates system

### ISSUE THREAD

**Issue by tometchy** [akkadotnet/akka.net#5245]
**Version Information**
Version of Akka.NET? 1.4.24
Which Akka.NET Modules? Akka

**Describe the bug**
Default guardian strategy `guardian-supervisor-strategy = "Akka.Actor.DefaultSupervisorStrategy"` is to restart. There is also a possibility to set guardian strategy to _Akka.Actor.StoppingSupervisorStrategy_ which in my view should terminate whole actor system. I didn't find this information in Akka.Net docs, but this is what I feel is desired and also Akka says similar in theirs docs:
> When the guardian escalates a failure, the root guardian’s response will be to terminate the guardian, which in effect will shut down the whole actor system.

_https://doc.akka.io/docs/akka/2.5/general/supervision.html_

**To Reproduce**
To reproduce simply run this app:
``` csharp
using System;
using Akka.Actor;
using Akka.Configuration;

namespace Bug
{
    static class Program
    {
        static void Main()
        {
            var system = ActorSystem.Create("Q", ConfigurationFactory.ParseString(@"akka.actor.guardian-supervisor-strategy = ""Akka.Actor.StoppingSupervisorStrategy"""));
            var gonnaBlowUp = system.ActorOf(Props.Create(() => new GonnaBlowUp()));
            
            gonnaBlowUp.Tell(new object());
            
            Console.WriteLine("Waiting for system termination");
            system.WhenTerminated.Wait();
            Console.WriteLine("System terminated");
        }
    }

    public class GonnaBlowUp : ReceiveActor
    {
        public GonnaBlowUp() => ReceiveAny(_ => throw new Exception("Blowing up!"));
    }
}
```

**Expected behavior**
I want my app to be terminated when failure is escalated to _the top_.

**Actual behavior**
Setting _akka.actor.guardian-supervisor-strategy_ to `Akka.Actor.StoppingSupervisorStrategy` stops actor (doesn't restart it), but actor system is still up. 

**Environment**
Running on Windows in .Net Core 3.1

**Comment by Aaronontheweb** [comment]
So it looks to me like:

1. The current `Akka.Actor.StoppingSupervisorStrategy` implementation is correct and working as intended - it's supposed to stop the terminated actor being supervised, not the actor doing the supervising;
2. You need a `SupervisorStrategy` implementation that will terminate the `ActorSystem` upon failure and set that as the `akka.actor.guardian-supervisor-strategy` to the FQN of that type.

Off the top of my head, you could create something like:

```csharp
var strategy = new OneForOneStrategy(ex => {
    Context.Parent.Tell(PoisonPill.Instance);
    return Directive.Escalate;
});
```

And wrap that into its own type and load it via `akka.actor.guardian-supervisor-strategy` - does that make sense?

**Comment by Aaronontheweb** [comment]
Actually, looks like the `UserGuardian` just has to send itself a `PoisonPill` in the `SupervisorStrategy` to shut the `ActorSystem` down:

https://github.com/akkadotnet/akka.net/blob/f5cb089772cc837b7b94d3a11dfa91194563ea19/src/core/Akka/Actor/BuiltInActors.cs#L92-L103

So I'd rewrite my earlier sample to

```csharp
var strategy = new OneForOneStrategy(ex => {
    Context.Stop(Self); // immediately shut down
    return Directive.Escalate;
});
```csharp

**Comment by tometchy** [comment]
Seems correct, so it should be something like _Akka.Actor.EscalatingSupervisorStrategy_.
For now I will try to wrap it and create some custom workaround, but it would be nice not to need to hack it like this.

> Actually, looks like the UserGuardian just has to send itself a PoisonPill in the SupervisorStrategy to shut the ActorSystem down:

That seems correct, I know it because in my happy path I finish with telling poison pill to parent (guardian actor) and everything quits correctly.

But in my view this:
``` csharp
var strategy = new OneForOneStrategy(ex => {
    Context.Parent.Tell(PoisonPill.Instance);
    return Directive.Escalate;
});
```
is ugly, because if we are escalating, then we should not need to do anything else (tell parent by ourself). One will wonder, what will happen after change like this:
``` csharp
var strategy = new OneForOneStrategy(ex => {
    Context.Parent.Tell(PoisonPill.Instance);
    return Directive.Resume;
});
```
and it seems that it will work the same way, as returned directive in this case doesn't matter, because we tell poison pill to parent that way or another.

**Comment by Aaronontheweb** [comment]
Correct - the directive doesn't really matter. Killing the guardian is what makes this work.

> For now I will try to wrap it and create some custom workaround, but it would be nice not to need to hack it like this.

What most users _want_ is restarting / resiliency - your use case, which sounds like it's for a client application, is the exception. That's why we make things like this configurable though!

**Comment by tometchy** [comment]
True, it's great that it's configurable :) But I can imagine such need in
server application too, no to recreate node from the node, but if something
really bad has happened, to escalate it up and let orchestrator for exaple
Kubernates, handle it, and recreate whole pod.

On Thursday, September 2, 2021, Aaron Stannard ***@***.***>
wrote:
> Correct - the directive doesn't really matter. Killing the guardian is
what makes this work.
>
> For now I will try to wrap it and create some custom workaround, but it
would be nice not to need to hack it like this.
>
> What most users want is restarting / resiliency - your use case, which
sounds like it's for a client application, is the exception. That's why we
make things like this configurable though!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. <
https://ci5.googleusercontent.com/proxy/qIjRVwNV4xquBDsoOUrxkc4s0B_Rm0kIx1k2JVeVTGCCeDVyUOQUXxQHBykOTRXO8Dl6w2yEFDcb3Z7y7RnImGY7V_qAeLxfm8Akvuzr_XVqtY7LJHO2EGosVPqamVBqVZAv7oGz4gV59tI8UeZsX166v_XRhup-q1RA8ATs0dqhVuxR47qlN-TnRq7030StqoJxaUeiddFaRtyoInyCeGky2FpEuecsw04Vx9dZ8g=s0-d-e1-ft#https://github.com/notifications/beacon/AJKB3KMGTS2SUG4XINYCTDTT76FVNA5CNFSM5DI7IVL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGZMIYTQ.gif>

**Comment by tometchy** [comment]
I've got good news, nasty hacking not needed, look:

_Program.cs_
```csharp
using System;
using System.Linq;
using Akka.Actor;
using Akka.Configuration;

namespace AkkaNetEscalating
{
    static class Program
    {
        static void Main(string[] args)
        {
            Config configuration = Config.Empty;

            if(args.Any() && string.Equals(args.First(), "escalate", StringComparison.InvariantCultureIgnoreCase))
                configuration = ConfigurationFactory.ParseString(@"akka.actor.guardian-supervisor-strategy = ""AkkaNetEscalating.EscalatingSupervisorStrategy, AkkaNetEscalating""");
            else
                configuration = ConfigurationFactory.ParseString(@"akka.actor.guardian-supervisor-strategy = ""Akka.Actor.StoppingSupervisorStrategy""");

            var system = ActorSystem.Create("Q", configuration);
            var gonnaBlowUp = system.ActorOf(Props.Create(() => new GonnaBlowUp()));

            gonnaBlowUp.Tell(new object());

            Console.WriteLine("Waiting for system termination");
            system.WhenTerminated.Wait();
            Console.WriteLine("System terminated");
        }
    }

    public class GonnaBlowUp : ReceiveActor
    {
        public GonnaBlowUp() => ReceiveAny(_ => throw new Exception("Blowing up!"));
    }

    public class EscalatingSupervisorStrategy :  SupervisorStrategyConfigurator
    {
        public override SupervisorStrategy Create() => new OneForOneStrategy(ex => Directive.Escalate);
    }
}
```

_AkkaNetEscalating.csproj_
``` csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka" Version="1.4.25" />
  </ItemGroup>

</Project>
```

And invoking with simple `dotnet run` or `dotnet run escalate` and it works as I wanted :)

For now I will use it this way, but I hope _EscalatingSupervisorStrategy_ will end up in core library - if you want I can find free time some evening and pull request it.

**Comment by Aaronontheweb** [comment]
I'd accept a pull request for `Akka.Actor.EscalatingSupervisorStrategy` - if you wanted to put it in the same file as `StoppingSupervisorStrategy`
