### ISSUE TITLE
Child & GetChildren for TestActorRef

### ISSUE THREAD

**Issue by Anber** [akkadotnet/akka.net#528]
InternalTestActorRef.Create(…) doesn't replace ReservedActorRef to real actor ref. Is it a bug?

**Comment by HCanber** [comment]
I'm not sure what you mean.  What kind of errors do you encounter?
Note, that `ReservedActorRef` isn't used any more in the `dev` branch, but the error you're seeing might still be there so pleas provide more info.

**Comment by Anber** [comment]
Hm… I don't sure where I found ReservedActorRef, but now Context.Child works properly.
