### ISSUE TITLE
Akka.Persistence.Sql.Common: add separate tags table for indexing individual tags

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#5296]
**Is your feature request related to a problem? Please describe.**
Right now all of our tags in Akka.Persistence.SqlServer and other related plugins are simply stored as comma-delimited text that is, effectively, not indexed:

https://github.com/akkadotnet/Akka.Persistence.SqlServer/blob/ccf62119cf99daf9ea77edd1f7596d74f53ea5a6/src/Akka.Persistence.SqlServer/Journal/SqlServerQueryExecutor.cs#L56-L78

When we perform a "read by tags" query, it performs a full table scan of all items in the Akka.Persistence.Journal:

https://github.com/akkadotnet/Akka.Persistence.SqlServer/blob/ccf62119cf99daf9ea77edd1f7596d74f53ea5a6/src/Akka.Persistence.SqlServer/Journal/SqlServerQueryExecutor.cs#L35-L41

For any reasonably large journal (i.e. millions of events or more) this is going to be non-performant.

**Describe the solution you'd like**
I'm trying to decide if it would be better to:

1. Add a second "index" table for specific tags or
2. Materialize the "events by tag" data into a second, denormalized table in order to avoid joins. Advantage of this approach: can be made to work in non-relational environments, especially if we denormalize the full set of sequence numbers and persistent entity ids too, which should allow for safe deletion from both collections.

The idea in either case - avoid full table scans and use an index to query events by tag.

**Describe alternatives you've considered**
One alternative is to simply leave as-is and maybe have users implement their own custom journals.

**Additional context**
One nasty thing about introducing this change is how we'd make it backwards compatible with current journal implementations - there would, essentially, need to be an ETL process or tool of some kind introduced.

**Comment by Aaronontheweb** [comment]
cc @ismaelhamed @to11mtm

**Comment by malclear** [comment]
One thing to note about how tags are currently stored: they are unordered in the semicolon-delimited list. The tags "A", "B", and "C" will appear in any order in the `Tags` field: 

- ";A;B;C;"
- ";A;C;B;"
- ";B;C;A;"
- etc.

**Comment by Aaronontheweb** [comment]
@malclear and that works today because the SQL we use has a `LIKE` cause for filtering through the tags - which makes it even more non-performant, IMHO.

What I'd propose as part of an ETL process is parsing that field - each tag into its own row.

**Comment by malclear** [comment]
Would that mean duplicating the payload for each tag? If so, that's not insignificant. I think a many-to-many join table, or a tag-specific child table would be better for us.

**Comment by Aaronontheweb** [comment]
@malclear yeah, after thinking about it - for SQL it has to be less expensive to just rely on an index rather than denormalization.

**Comment by ismaelhamed** [comment]
This was eventually addressed in the `akka-persistence-jdbc` plugin, see [#467](https://github.com/akka/akka-persistence-jdbc/pull/467) and original issue [#194](https://github.com/akka/akka-persistence-jdbc/issues/194)

IMO, we should put all the effort in the `Akka.Persistence.Linq2Db` plugin moving forward. After all, `Akka.Persistence.Sql.Common` has served its purpose just fine for many users for all these years (given its limitations).

**Comment by Aaronontheweb** [comment]
> IMO, we should put all the effort in the Akka.Persistence.Linq2Db plugin moving forward. After all, Akka.Persistence.Sql.Common has served its purpose just fine for many users for all these years (given its limitations).

Yes. We should.

**Comment by Aaronontheweb** [comment]
Done as part of Akka.Persistence.Sql in August of this year.
