### ISSUE TITLE
UDP Connected: Unhandled message SocketReceived

### ISSUE THREAD

**Issue by jjmSE** [akkadotnet/akka.net#5318]
**Version Information**
Version of Akka.NET? 1.4.25
Which Akka.NET Modules? Akka.IO

**Describe the bug**
When communication with the device is complete, we send a UdpConnected.Disconnect message to close the socket. 
After that, we receive UdpConnected.Disconnected but we see an unhandled message in UdpConnection actor: 

  Message [SocketReceived] to [akka://dlmshe/system/IO-UDP-CONN/$a#267206278] was not delivered. [1] dead letters 
  encountered. If this is not an expected behavior then [akka://dlmshe/system/IO-UDP-CONN/$a#267206278] may have 
  terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 
  'akka.log-dead-letters-during-shutdown'.

**Expected behavior**
UDP socket is closed successfully. 

**Actual behavior**
UDP socket is closed successfully but we see an unhandled message. 

**Environment**
Windows
.NET Framework 4.8

![DeadLetter](https://user-images.githubusercontent.com/92517977/137302757-d6ec206f-5baf-4e73-95d0-e95ebf5713de.PNG)
[akka_seq_logs.csv](https://github.com/akkadotnet/akka.net/files/7345357/akka_seq_logs.csv)

**Comment by Arkatufus** [comment]
This is now trivial to fix after #5404 is merged in. We just need to add IDeadLetterSuppresion to SocketReceived.
