### ISSUE TITLE
[PERF] Bound port growth over time

### ISSUE THREAD

**Issue by oruscukg** [akkadotnet/akka.net#5321]
Hi!
We have a system built on Akka.NET with one server and many clients. Clients and the server exchange TCP messages frequently. At the same time, the number of BOUNDED ports on the server grows. We know about bug #2575 and are using Akka v1.4.
Do we understand it correctly that regularly restarting the Akka System with an increase in the number of BOUNDED ports is the only way to avoid this problem?

**Comment by Aaronontheweb** [comment]
Hi @oruscukg 

The number of bound ports should increase linearly with the number of connected clients - however, those ports should be freed when clients disconnect (gracefully or ungracefully). If ports are remaining open after a client disconnects then that's a resource leak we'll need to investigate.

Some questions for you:

1. Which parts of Akka.NET are you using for networking with your clients? Akka.Remote? Akka.IO?
2. Can you provide us with some data showing the port growth over time? What would really help us is being able to contrast the number of bound ports vs. number of connected clients, as that's a strong indicator that something untoward is happening in the network layer.
3. Any other additional information - i.e. does this happen on Windows? Linux? Are there some scenarios that drive up the port count more than others?
