### ISSUE TITLE
Generic property injection on the purpose of plugins

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#533]
Since C# doesn't offer multiple inheritance (like Scala via traits) sometimes there is a need to bypass that problem by using composition over inheritance. Example is stashing with `StashFactory.CreateStash`: we use framework to automatically inject stash into actors marked with `IActorStash` interface.

This feature may be however used more often (we already could use it for example in logging and cluster actor initialization), and also be utilized by plugins. I've already found two use cases in one of the possible designs of Akka.Persistence plugin.

Should we provide some kind of a generic actor creation interceptor mechanism or should we dump the responsibility on shoulders of Akka users?

**Comment by HCanber** [comment]
I like it, however I have two things I'd like to discuss.

__1__
_Created_ and  _Terminated_ are well defined concepts for an actor. An actor is created and terminated once, and only once, but the methods `AfterActorCreated` and `BeforeActorTerminated` are called several times during an actor's lifecycle. They are called every time the _underlying_ actor instance (i.e. the class that the user writes) is created/terminated.

Unfortunately there's no term for the underlying instance. In our, as well as Akka JVM's code, the only time (as I know of) a user is exposed to the underlying instance is in `TestActorRef` which has a property called `UnderlyingActor`. So maybe we should use that term?

I.e. call the methods `AfterUnderlyingActorCreated` and `BeforeUnderlyingActorTerminated`.

__2__
Do we really need to check every actor instance? 
``` C#
public interface IActorProducerPlugin
{
  bool CanBeAppliedTo(ActorBase actor);
  ...
}
```

Or could we change this to:
``` C#
public interface IActorProducerPlugin
{
  bool CanBeAppliedTo(Type actorType);
  ...
}
```

This would allow us to check the actor type once, build a pipeline with only the plugins applicable to the actor type and then store the pipeline (per type). Whenever `AfterUnderlyingActorCreated` and `BeforeUnderlyingActorTerminated` is to be called, we get the pipeline for the actor (type) and call the method, i.e. no need to call `CanBeAppliedTo` every time.

**Comment by Horusiath** [comment]
Considering **1.** - I think that we should create some term for process of replacing underlying actor (if canonical Akka doesn't have one already) and use it for associated actions. Taken [this description image](http://doc.akka.io/docs/akka/snapshot/_images/actor_lifecycle.png) my proposition would be *Reincarnation* - in this case methods could be called `AfterActorCreated` &rArr; `AfterReincarnated` and `BeforeActorTerminated` &rArr; `BeforeReincarnated`.

**2.** - I was also thinking about it. When I was developing this feature, I've thought that by providing an actor instance we may give users more possibilities. Now I see, that this is not the case, since this method will always be called on fresh actor instance. So here I agree with you.

**Comment by HCanber** [comment]
1. 

> Reincarnation is the religious or philosophical concept that the soul or spirit, _after biological death_, can begin a new life in a new body.
> [Wikipedia](http://en.wikipedia.org/wiki/Reincarnation) 

So in order to be reincarnated the actor has had to die first which is not true the first time `AfterActorCreated` is called.

_Reincarnation_ can be used to describe what happens during restarts.

**Comment by rogeralsing** [comment]
Akka documentation use the word `incarnation` for the underlying actor instance life.
Would `AfterIncarnated` or `AfterIncarnate` work?

>1.
embodied in flesh; given a bodily ...

**Comment by HCanber** [comment]
Yep!

**Comment by Aaronontheweb** [comment]
I like @HCanber 's #2 suggestion - that'll help keep the costs of actor startup at a minimum.

**Comment by Horusiath** [comment]
Ok, i'll fix that one. Summarizing: replace single plugin pipeline into set of Actor type specific ones, and refactor current `IActorProducerPlugin` interface into something like this:

```
interface IActorProducerPlugin {
    bool CanBeAppliedTo(Type actorType);
    void AfterIncarnated (ActorBase actor, IActorContext context);
    void BeforeIncarnated (ActorBase actor, IActorContext context);
}
```

**Comment by Aaronontheweb** [comment]
So can we consider this feature "implemented" then?

**Comment by rogeralsing** [comment]
Done.
