### ISSUE TITLE
Documentation, custom repo or github wiki?

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#536]
Some qustions regarding how we should document have been brought up recently.

I think we have three options to assess.

1. Keep documentation in the akka.net wiki
1. Move documentation into the akka.net repo as `.MD` files
1. Move documentation into it's own repository, as `.MD` files, to not interfere with the code base.

The current Wiki approach is kind of nice, but it comes with some drawbacks, you can't deal with folder structures, all pages must reside directly under the wiki root.
This is a limitation of the Gollum Wiki derivate that Github uses.

If we move the `.MD` files into a repository, we can better manage pull requests for docs, include other resources as images/movies.
either the akka.net repo or it's own doc repo.

Thoughts?

**Comment by SeanKilleen** [comment]
:+1: for 2nd option. In addition to making docs readily accessible, I think it's possible that this could serve as a nice reminder to update documentation along with commits, and make it easier to do so as part of pull requests, etc.

**Comment by rogeralsing** [comment]
Done.
