### ISSUE TITLE
Custom serializer did not resolve to actual type

### ISSUE THREAD

**Issue by shablenko-sednor** [akkadotnet/akka.net#5371]
**Version Information**
Version of Akka.NET - 1.4.27
Which Akka.NET Modules:
1. Akka.Persistence 1.4.27
2. Akka.Persistence.PostgreSql 1.4.25

**Describe the bug**
I'm trying to define custom serializer following [doc](https://getakka.net/articles/networking/serialization.html)

Tried to use HOCON config first

```hocon
akka.actor {
  serializers {
    my-message = "project.Serializer.MessageSerializer"
  }

  serialization-bindings {
    "project.Message.BaseMessage" = my-message
  }

  serialize-messages = on
}
```

Did not work, got following warnings

```
[WARNING][11/9/2021 3:58:18 PM][Thread 0001][ActorSystem(MyActorSystem)] The type name for serializer 'my-message' did not resolve to an actual Type: 'project.Serializer.MessageSerializer'
[WARNING][11/9/2021 3:58:18 PM][Thread 0001][ActorSystem(MyActorSystem)] The type name for message/serializer binding '' did not resolve to an actual Type: 'project'
```

Tried to use programmatic way

```c#
var serializationSettings =
SerializationSetup.Create(actorSystem =>
  ImmutableHashSet<SerializerDetails>.Empty.Add(
    SerializerDetails.Create("my_messages",
      new MessageSerializer(actorSystem),
      ImmutableHashSet<Type>.Empty.Add(typeof(BaseMessage)))));
var config = ConfigurationFactory.ParseString(HoconConfigurationFactory.FromFile("app.hocon").ToString());
var bootstrapSetup = BootstrapSetup.Create().WithConfig(config);
var systemSetup = ActorSystemSetup.Create(serializationSettings, bootstrapSetup);
MyActorSystem = ActorSystem.Create("MyActorSystem", systemSetup);
```

Got following error

```
[ERROR][11/9/2021 3:50:38 PM][Thread 0018][[akka://MyActorSystem/user]] Swallowing exception during message send
Cause: System.Runtime.Serialization.SerializationException: Failed to serialize and deserialize payload object [Akka.Persistence.Journal.AsyncWriteJournal+Desequenced]. Envelope: [<Akka.Persistence.Journal.AsyncWriteJournal+Desequenced> from [akka://MyActorSystem/deadLetters]], Actor type: [Akka.Persistence.Journal.AsyncWriteJournal+Resequencer]
 ---> Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type project.Message.PongMessage. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'Message.Persistent.Payload.UserId', line 1, position 333.
```

My messages extend class `BaseMessage`
I wanted to have a single serializer which implements `SerializerWithStringManifest`

**Comment by shablenko-sednor** [comment]
Any thoughts on this one? It is critical for me, would be glad to see any workarounds or fixes

**Comment by Aaronontheweb** [comment]
Sorry about this - do you still need help with this? Tagging @Arkatufus

**Comment by Arkatufus** [comment]
@shablenko-sednor Have you tried to use an fully qualified class name in your serializer configuration?
For example, if your project is compiled into assembly "project.dll", you should provide a fully qualified class name of "project.Serializer.MessageSerializer, project". Note the addition of assembly name at the end of the string, the full name should be in the format of "[namespace].[class_name], [assembly_name]"

**Comment by Arkatufus** [comment]
@shablenko-sednor 
I've confirmed it, it failed because dotnet could not resolve "project.Serializer.MessageSerializer" into a concrete type.
You can test it inside your project by using `Type.GetType("project.Serializer.MessageSerializer")` and it will return null instead of a Type. The same thing goes with the `serialization-bindings` section, the type name must resolve to a concrete type when you pass it into `Type.GetType()`.

For the programmatic approach, in your serializer class, did you override the `Identifier` property? you will need to provide an identifier greater than 100 as anything 100 and below is used as internal serializer identifier.
