### ISSUE TITLE
Failed to deserialize payload object when deserializing ActorSelectionMessage with payload ...

### ISSUE THREAD

**Issue by fscavo** [akkadotnet/akka.net#5383]
**Version Information**
Version of Akka.NET?  1.4.24
Which Akka.NET Modules? Akka.Cluster

**Describe the bug**
Our services throws SerizalizationException when sending a message to a singleton actor.

**Comment by Aaronontheweb** [comment]
Do you have a copy of the serialization exception error message that was thrown? This would be very helpful to diagnose this error.

**Comment by fscavo** [comment]
This is the full message

> Failed to deserialize payload object when deserializing ActorSelectionMessage with payload [SerializerId=14, Manifest=A] addressed to [user,cache-abb-advices-found] Cannot find serializer with id [14] (manifest [A]). The most probable reason is that the configuration entry 'akka.actor.serializers' is not in sync between the two systems

And here is the call stask
> System.Runtime.Serialization.SerializationException:
   at Akka.Remote.Serialization.MessageContainerSerializer.FromBinary (Akka.Remote, Version=1.4.24.0, Culture=neutral, PublicKeyToken=null)
   at Akka.Serialization.Serialization.Deserialize (Akka, Version=1.4.24.0, Culture=neutral, PublicKeyToken=null)
   at Akka.Remote.MessageSerializer.Deserialize (Akka.Remote, Version=1.4.24.0, Culture=neutral, PublicKeyToken=null)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch (Akka.Remote, Version=1.4.24.0, Culture=neutral, PublicKeyToken=null)
   at Akka.Remote.EndpointReader.<Reading>b__11_0 (Akka.Remote, Version=1.4.24.0, Culture=neutral, PublicKeyToken=null)
Inner exception System.Runtime.Serialization.SerializationException handled at Akka.Remote.Serialization.MessageContainerSerializer.FromBinary:
   at Akka.Serialization.Serialization.Deserialize (Akka, Version=1.4.24.0, Culture=neutral, PublicKeyToken=null)
   at Akka.Remote.Serialization.WrappedPayloadSupport.PayloadFrom (Akka.Remote, Version=1.4.24.0, Culture=neutral, PublicKeyToken=null)
   at Akka.Remote.Serialization.MessageContainerSerializer.FromBinary (Akka.Remote, Version=1.4.24.0, Culture=neutral, PublicKeyToken=null)

**Comment by Aaronontheweb** [comment]
If you try doing the following:

```
yourConfig.WithFallback(ClusterSingletonManager.DefaultConfig())
```

I think that should resolve this issue. This is something I want to fix with automatic loading in the future.

**Comment by fscavo** [comment]
@Aaronontheweb Thanks!
May I ask you to elaborate on this issue?

**Comment by fscavo** [comment]
I thought it might be helpful to post here the configuration
```csharp
var defaultAkkaConfiguration = ConfigurationFactory.ParseString($@"
                akka {{
                    log-config-on-start = on
                    loglevel = {akkaSettings.AkkaLogLevel},
                    loggers  = [ ""Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog"" ]
                    suppress-json-serializer-warning = on
                    actor {{
                        ask-timeout = 15s
                        serializers {{
                            hyperion = ""Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion""
                        }}
                        serialization-bindings {{
                            ""System.Object"" = hyperion
                        }}
                        serialize-messages = {(akkaSettings.ForceMessagesSerialization ? "on" : "off")}
                        serialize-creators = {(akkaSettings.ForceCreatorsSerialization ? "on" : "off")}
                    }}
                }}");
```
```csharp
var akkaPersistenceConfiguration = ConfigurationFactory.ParseString($@"
                akka.persistence {{
                    journal {{
                        plugin = ""akka.persistence.journal.sql-server""
                        sql-server {{
                            class = ""Akka.Persistence.SqlServer.Journal.{(akkaSettings.Persistence.Journal.UseBatchingJournal ? "Batching" : string.Empty)}SqlServerJournal, Akka.Persistence.SqlServer""
                            schema-name = dbo
                            auto-initialize = on
                            connection-string = ""{GetDbConnectionString()}""
                            metadata-table-name = AkkaPersistenceMetadata
                            table-name = AkkaPersistenceEventJournal
                            circuit-breaker {{
                                call-timeout = 50s
                            }}
                            event-adapters = {{
                                {GetConfigFromDictionary(akkaSettings.Persistence.Journal.EventAdapters)}
                            }}
                            event-adapter-bindings = {{
                                {GetConfigFromDictionary(akkaSettings.Persistence.Journal.EventAdapterBindings)}
                            }}
                        }}
                    }}
                    snapshot-store {{
                        plugin = ""akka.persistence.snapshot-store.sql-server""
                        sql-server {{
                            class = ""Akka.Persistence.SqlServer.Snapshot.SqlServerSnapshotStore, Akka.Persistence.SqlServer""
                            schema-name = dbo
                            auto-initialize = on
                            connection-string = ""{GetDbConnectionString()}""
                            table-name = AkkaPersistenceSnapshotStore
                            circuit-breaker {{
                                call-timeout = 50s
                            }}
                        }}
                    }}
                    query {{
                        journal {{
                            sql-server {{
                                class = ""Akka.Persistence.Query.Sql.SqlReadJournalProvider, Akka.Persistence.Query.Sql""
                                max-buffer-size = {akkaSettings.Persistence.Query.MaxBufferSize}
                                refresh-interval = {akkaSettings.Persistence.Query.RefreshInterval}
                            }}
                        }}
                    }}
                }}");
```
```csharp
var config = configurationProviders
                .OrderByDescending(c => c.Priority)
                .Where(c => c.Get() != null)
                .Aggregate(Config.Empty, (config, provider) =>
                {
                    logger.LogInformation("Using additional Akka configuration from {Provider}: {Config}", provider.GetType().Name, provider.Get().ToString());
                    return config.WithFallback(provider.Get());
                })
                .WithFallback(GetDispatcherConfig());

            if (akkaSettings.EnableCluster)
            {
                config = config.WithFallback(ConfigurationFactory.ParseString(GetClusterConfig()));
            }

            return config
                .WithFallback(akkaPersistenceConfiguration)
                .WithFallback(defaultAkkaConfiguration);
```

**Comment by Aaronontheweb** [comment]
So the issue here is that unless this method gets called:

https://github.com/akkadotnet/akka.net/blob/e27220a09ed10d71bc32cb73f4002641b0faaf94/src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManagerSettings.cs#L28-L37

By default the Akka.Cluster.Singleton serializer is not loaded, which you can see is `serializerId=14` here:

https://github.com/akkadotnet/akka.net/blob/e27220a09ed10d71bc32cb73f4002641b0faaf94/src/contrib/cluster/Akka.Cluster.Tools/Singleton/reference.conf#L72-L81

So in those cases, to solve these serialization errors, you need to manually load the `ClusterSingletonManager.DefaultConfig()` to make sure those serialization bindings are available to Akka.Remote.

**Comment by fscavo** [comment]
I think this has solved the issue.
Thanks @Aaronontheweb

**Comment by Aaronontheweb** [comment]
Tagging this on https://github.com/akkadotnet/HOCON/issues/48
