### ISSUE TITLE
Akka.Cluster.Sharding needs better documentation.

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/akka.net#5401]
Akka.Cluster.Sharding documentation needs to be expanded:
- Mention the importance of node roles.
- A short tutorial on how to set up a simple sharded cluster from zero, maybe use the simple shopping cart sample but break it down from zero.

**Comment by Dirnei** [comment]
The most important part of it would be the `.WithRole("myrole")` when creating the ClusterShardingSettings

```csharp
return ClusterSharding.Get(system).Start(
    typeName: actorName,
    entityProps: DependencyResolver.For(system).Props<T>(),
    settings: ClusterShardingSettings.Create(system).WithRole(role),
    messageExtractor: hashCodeMessageExtractor
);
```

If this is not present it only works within the same actor system. As soon as you start up a second system, the proxy will not be able to reach the shard.

**Comment by Aaronontheweb** [comment]
Merged - take a look at the updated documentation later today. Should be live in 20-25 minutes.

**Comment by Aaronontheweb** [comment]
https://getakka.net/articles/clustering/cluster-sharding.html
