### ISSUE TITLE
Need to set version range for all standard `System.*` packages

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#5411]
We probably need to align all of our `System.*` packages on a common version range - see https://github.com/akkadotnet/akka.net/pull/5365#issuecomment-984763805

Separate issue from this PR, but I'm seeing a trend here...

_Originally posted by @Aaronontheweb in https://github.com/akkadotnet/akka.net/pull/5403#discussion_r761265129_

**Comment by Aaronontheweb** [comment]
We probably need to set a target version range for:

* Microsoft.Extensions.*
* System.Collections.Immutable
* System.Threading.Channels
* Any other base packages that automatically get bumped when a new .NET version is released

Low end of the range should be lowest supported LTS release of .NET (3.1, currently)

High end of the range should be unbounded.

Does that make sense? cc @akkadotnet/contributors

**Comment by ismaelhamed** [comment]
Yes. We've had no problem with Akka so far but can't say the same with other third-party libraries.

**Comment by Aaronontheweb** [comment]
We aren't heavy power users of any of these libraries (so we don't use the bleeding edge stuff that's most likely to change between versions) and the API changes that coincide with major new platform releases are mostly trivial. So I think this version range strategy should be fine for our users.
