### ISSUE TITLE
Plugin proposal: Akka.Dispatchers.Hopac

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#543]
Since Akka.NET allows us to use custom dispatchers in order to manage OS resources, we may create a custom Dispatcher using [Hopac](https://github.com/Hopac/Hopac) instead of Tasks or Threads. Since Hopac jobs are highly optimized (they could be significantly faster than TPL, see link), there is possibility to have some performance gain from this change. Hopac also introduces many other primitives (channels, actors etc.) which may be usefull in other parts of the Akka.NET framework... and supports Mono better than current TPL implementation.

This is more _measure and research_ type of task. I hope to use Hopac dispatcher to have higher performance than with TPL, but to be sure, one need to create that library and create some metrics to compare.
### Prerequisites
- Knowledge of Hopac API.
- Knowledge of Akka dispatchers and resource management.
### Links
- [Parallel reduce: Hopac vs Asyncs vs Tasks](http://vaskir.blogspot.com/2015/01/parallel-reduce-hopac-vs-asyncs-vs-tasks.html)

**Comment by VesaKarvonen** [comment]
Interesting proposal...  Don't hesitate to ask for questions or report issues.  Hopac is quite aggressively optimized, but it is not magic&mdash;for best results one still need to understand what is going on.  Hopac also provides a fairly large number of primitives, or to put it another way, a wide vocabulary, for expressing concurrent constructs and it requires some knowledge to make best use of it.  However, I believe that learning the vocabulary is not wasted time as the underlying ideas are quite fundamental.

**Comment by anishpateluk** [comment]
Leveraging hopac as dispatcher in akka.net is very intriguing. Has any movement been made on this?

**Comment by Danthar** [comment]
@anishpateluk No. But its up for grabs. So anyone who feels like a challenge is welcome to take a crack at it.

**Comment by sean-gilliam** [comment]
@akkadotnet/core Should we move this proposal to the AkkaNetContrib org?

**Comment by Rattenkrieg** [comment]
By the way I decided to grab this issue some time ago, but due to my depth-first approach I found myself reading CML book at the moment.

**Comment by Danthar** [comment]
Agree with @sean-gilliam we should move this.

**Comment by sean-gilliam** [comment]
Moved issue to AkkaNetContrib/Home#24
