### ISSUE TITLE
Akka.TestKit: take dependency on FluentAssertions?

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#5432]
We should probably just take a dependency on FluentAssertions in the TestKit. I don't know why we haven't yet. 

I'll make a bigger issue for this and we'll revisit that prior to releasing v1.4.30.

_Originally posted by @Aaronontheweb in https://github.com/akkadotnet/akka.net/pull/5430#discussion_r769172219_

**Comment by Aaronontheweb** [comment]
Any reason why we shouldn't take a reference on FluentAssertions inside the Akka.TestKit?

cc @akkadotnet/core @akkadotnet/contributors

**Comment by Danthar** [comment]
- We are using it heavily in our own tests. And its exposed through the samples as well. 
- Reason we haven't before is because the TestKit in itself doesn't need it. 

Saw the referring PR: feels a bit like overkill to pull that in just for 1 line of code. But you might put more value on my previous comments. ¯\_(ツ)_/¯

**Comment by Aaronontheweb** [comment]
> Saw the referring PR: feels a bit like overkill to pull that in just for 1 line of code. But you might put more value on my previous comments. ¯_(ツ)_/¯

I removed it in https://github.com/akkadotnet/akka.net/pull/5433

**Comment by IgorFedchenko** [comment]
If we need it in TestKit, I do not see any reason why not to add this reference.

**Comment by Aaronontheweb** [comment]
> If we need it in TestKit, I do not see any reason why not to add this reference.

So far we haven't needed it, but we could probably replace a lot of "homegrown" stuff with it. I'm a bit conflicted about that since I like to keep external dependencies to a minimum.... But I also like to keep our own code to a minimum too...

**Comment by IgorFedchenko** [comment]
Ah, that makes sense.
Then to me it sounds like we are thinking of making TestKit refactoring to make it cleaner/more readable/easier to understand by other devs. 
If that's the case, there is a value of adding FluentAssertions reference. Especially if there are some volunteers to perform this refactoring :)

**Comment by Aaronontheweb** [comment]
This is already done in v1.5.
