### ISSUE TITLE
Project referencing MultiNodeTestRunner fails with Unexpected CopyLocal flag

### ISSUE THREAD

**Issue by mchandschuh** [akkadotnet/akka.net#5443]
**Version Information**
Version of Akka.NET?  1.4.29
Which Akka.NET Modules? Akka.MultiNodeTestRunner, Akka.Cluster.TestKit, Akka.TestKit.NUnit3 (1.3.8)

**Describe the bug**
Here's a [repository](https://github.com/mchandschuh/akka-multi-node-test-runner-build-failure) that reproduces the issue

**Expected behavior**
Build should work without issue.

**Actual behavior**
Build fails with `Unexpected CopyLocal flag`

**Screenshots**
![image](https://user-images.githubusercontent.com/531416/146626083-22a029c3-7cc9-4401-8d03-e155ccaec9f4.png)

<details>

Build FAILED.

       "C:\src\github\mchandschuh\akka-multi-node-test-runner-build-failure\TestProject1\TestProject1.sln" (default target) (1:2) ->
       "C:\src\github\mchandschuh\akka-multi-node-test-runner-build-failure\TestProject1\TestProject1\TestProject1.csproj" (default target) (2:6) ->
       (ResolveAssemblyReferences target) ->
         C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(2304,5): error MSB4018: The "ResolveAssemblyReference" task failed unexpectedly. [C:\src\github\mchandschuh\akka-multi-node-test-runner-build-failure\TestProject1\TestProject1\TestProject
1.csproj]
       C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(2304,5): error MSB4018: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Unexpected CopyLocal flag. [C:\src\github\mchandschuh\akka-multi-node-test-runner-bui
ld-failure\TestProject1\TestProject1\TestProject1.csproj]
       C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(2304,5): error MSB4018:    at Microsoft.Build.Tasks.CopyLocalStateUtility.IsCopyLocal(CopyLocalState state) [C:\src\github\mchandschuh\akka-multi-node-test-runner-build-failure\TestProject1
\TestProject1\TestProject1.csproj]
       C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(2304,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.LogResults(ReferenceTable dependencyTable, List`1 idealAssemblyRemappings, List`1 idealAssemblyRemappingsIdentit
ies, List`1 generalResolutionExceptions) [C:\src\github\mchandschuh\akka-multi-node-test-runner-build-failure\TestProject1\TestProject1\TestProject1.csproj]
       C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(2304,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName g
etAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader) [C:\src\gi
thub\mchandschuh\akka-multi-node-test-runner-build-failure\TestProject1\TestProject1\TestProject1.csproj]
       C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(2304,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute() [C:\src\github\mchandschuh\akka-multi-node-test-runner-build-failure\TestProject1\TestProject1\TestPro
ject1.csproj]
       C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(2304,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\src\github\mchandschuh\akka-multi-node-test-runner-build-fai
lure\TestProject1\TestProject1\TestProject1.csproj]
       C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(2304,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, Ite
mBucket bucket, TaskExecutionMode howToExecuteTask) [C:\src\github\mchandschuh\akka-multi-node-test-runner-build-failure\TestProject1\TestProject1\TestProject1.csproj]

</details>
**Environment**
![image](https://user-images.githubusercontent.com/531416/146626129-1b19b2ca-fba2-40fb-99e6-bdc7687b5edf.png)

**Comment by Arkatufus** [comment]
@mchandschuh We'll look into this as soon as possible, thank you for reporting the bug.

**Comment by Arkatufus** [comment]
@mchandschuh I would recommend to use the new multi node package `Akka.MultiNode.TestAdapter` instead of using the old `Akka.MultiNodeTestRunner`.
I do spot some possible problem with your setup:
- Our multi node test runner only supports Xunit test framework
- `Akka.TestKit.NUnit3` is a very old package, we are trying to upgrade it to the latest Akka.NET, but the current build only supports Akka.NET 1.3.8, which is quite ancient.
