### ISSUE TITLE
Avoid running jobs in forked projects

### ISSUE THREAD

**Issue by ismaelhamed** [akkadotnet/akka.net#5468]
Typically, if you don't want *workflows* to run on your forked repo, you can go to **Settings > Actions > Actions permissions** and **Disable Actions for this repository**. 

But IMO, `workflows` should be disabled except for the main repo (as a matter of courtesy). Hopefully, GitHub will have actions disabled by default (opt-in) in the future.

**Comment by Aaronontheweb** [comment]
Funnily enough, we have jobs _disabled_ in the main repository at the moment and are still relying on Azure DevOps to do this. That may change in the future (Github Actions could simplify some issues for us.)
