### ISSUE TITLE
Need to develop way to iterate through Fallback Deploy, RouterConfig, etc during deployment

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#550]
Right now `Deploy`, `RouterConfig`, and other pieces of configuration plumbing have a `WithFallback` function just like their partners in canonical Akka, but we aren't using the fallback values anywhere in `Deployer`s, `ActorRefProvider`s, et al.

We need to do the following:

1. Define some reliable __merge__ behavior for fallbacks, just like how we do with `Config`.
1. Invoke the merges at the time of deployment, serialization, actor ref creation, etc...

Scala Akka has code like this (taken from their `RemoteActorRefProvider`) that handles the merging through pattern matching and aggregation:

````
Iterator(props.deploy) ++ deployment.iterator reduce ((a, b) ⇒ b withFallback a) match {
        case d @ Deploy(_, _, _, RemoteScope(addr), _, _) ⇒
````

See: https://github.com/akka/akka/blob/cb05725c1ec8a09e9bfd57dd093911dd41c7b288/akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala#L273

We should do likewise, as it will help make it easier to do remote and local deployments through configuration.

**Comment by rogeralsing** [comment]
There is more to it I think, currently the config is not serializable so if the deploy contains a config setting, we need to be able to pass the config over the wire.

**Comment by Aaronontheweb** [comment]
I'm not sure if the raw Config section itself needs to be serialized, but it's output (all of the `Deploy` / `RouterConfig` stuff) definitely needs to be, including fallbacks.

**Comment by rogeralsing** [comment]
Was this solved?
