### ISSUE TITLE
Remove `PersistenceBenchmark`

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#5506]
Our Akka.Persistence benchmarks are pretty ancient https://github.com/akkadotnet/akka.net/blob/dev/src/benchmark/PersistenceBenchmark/Program.cs

I'll see about adding some BenchmarkDotNet ones.

_Originally posted by @Aaronontheweb in https://github.com/akkadotnet/akka.net/issues/5505#issuecomment-1011780570_

---

We should delete the `PersistenceBenchmark` - byte rotted and we'd prefer a BenchmarkDotNet solution here.

**Comment by Aaronontheweb** [comment]
Still have to remove the old benchmarks even if we have a decent replacement for them now

**Comment by dengia** [comment]
Hi @Aaronontheweb, I went through benchmarks:
PersistentBenchamarks --> Akka.Cluster.Benchmarks/Persistence
PingPong  --> Akka.Benchmarks/Actor/PingPongBenchmarks.cs
SerializationBenchmarks --> Akka.Benchmarks/Actor/Serialization
RemotePingPong --> ?
SpawnBenchmark --> ?
Question: is this correct? If yes, shall I remove those three old benchmarks with decent replacement?

**Comment by Aaronontheweb** [comment]
@dengia those benchmarks are fine, it's just this folder that needs to be deleted https://github.com/akkadotnet/akka.net/tree/dev/src/benchmark/PersistenceBenchmark
