### ISSUE TITLE
Disassociated because "the ProtocolStateActor failed: Unknown"

### ISSUE THREAD

**Issue by fscavo** [akkadotnet/akka.net#5507]
Version of Akka.NET? 1.4.31 
Which Akka.NET Modules?
- Akka.Cluster
- Akka.Cluster.Sharding

The services running in Kubernetes keep showing the following DEBUG log 
``` 
[Akka.Remote.Transport.ProtocolStateActor] Association between local ["tcp://navigation-v2-service@0.0.0.0:2552"] and remote ["tcp://navigation-v2-service@[::ffff:172.18.4.235]:60214"] was disassociated because "the ProtocolStateActor failed: Unknown"
```
We run one service with lighthouse deployed in different POD
172.18.4.235 is the host-ip where the service pod runs

**Comment by fscavo** [comment]
But I don't get the reason why the service is trying to connect to Kubernetes node tcp://navigation-v2-service@[::ffff:172.18.4.235]:60214

**Comment by Aaronontheweb** [comment]
Ah I missed that - so that's not even an `ActorSystem` you're connecting to.

There are two reasons I can think of why this would occur:

1. A non-Akka.NET service in your K8s cluster is connecting to your Akka.Remote endpoint, but can't run the handshake protocol, which is why this error would occur.
2. You're using a system like [Akka.Management](https://github.com/akkadotnet/Akka.Management) to discover K8s nodes to form a cluster and due to how it's configured it's discovering and attempting to connect to non-Akka.NET services on the outbound side.

**Comment by Aaronontheweb** [comment]
Do you have a suspicion on which of these possibilities it could be? Or any additional ones I might be missing?

**Comment by fscavo** [comment]
We don't Akka,Management in our services and all services are Akka.NET based. I can' tell whether this issue existed prior version 1.4.31 or not because this is the first time I see after I've set the log level to DEBUG.

**Comment by Aaronontheweb** [comment]
`"tcp://navigation-v2-service@0.0.0.0:2552"` - ah, this might be simpler. This looks like a possible configuration issue to me. Could post a copy of your `akka.remote.dot-netty` config for both of these nodes?

**Comment by fscavo** [comment]
This is the configuration that we use in all services
```
dot-netty.tcp {
  public-hostname = {clusterInfo.CurrentHost.Host}
  public-port = {clusterInfo.CurrentHost.Port}
  hostname = 0.0.0.0
  port = {platformSettings.ClusterPort}
  maximum-frame-size = 2MB
  send-buffer-size = 2MB
  receive-buffer-size = 2MB
}
```

**Comment by Aaronontheweb** [comment]
And neither of these service instances are supposed to communicate with each other, correct?

**Comment by fscavo** [comment]
Not directly, we use messaging broker like event grid and service bus

**Comment by Aaronontheweb** [comment]
I wonder if it's possible that these actor addresses got leaked to each other by accident - possibly through a serialized `IActorRef` or more directly through a piece of shared infrastructure (Lighthouse maybe?)

**Comment by fscavo** [comment]
I've run a service that does only create an actor system with the same akka configuration as our service's. The issue is still there, though.
This is the actor hierarchy of this service. As you see nothing special :)
/user
/user/actor-system-terminator
/user/blob-storage-actor
/user/pbm-local-clients
/user/pbm-uptime
/user/petabridge.cmd
/user/petabridge.cmd/127.0.0.1%3A37556
/user/petabridge.cmd/127.0.0.1%3A37556/handler
/user/petabridge.cmd-log-memorizer
/user/remote-connection-history
/user/remote-stats

**Comment by Aaronontheweb** [comment]
And these two services each connect to a separate set of Lighthouse nodes, right?

**Comment by Aaronontheweb** [comment]
Somehow the address of one of those nodes was leaked to the other, just trying to narrow down how it could happen. I agree that it doesn't look like your actors are doing anything too complicated.

**Comment by fscavo** [comment]
Every service connects to different lighthouse.

**Comment by Aaronontheweb** [comment]
Could you please send me an email - aaron@petabridge.com ? this is a relatively minor problem but I do want to solve the mystery of why it's happening and I think a live video call would help a lot.

**Comment by Aaronontheweb** [comment]
Going to close this issue because it appeared to be an app-specific configuration issue rather than a generalized Akka.NET problem.
