### ISSUE TITLE
Unhandled exception. Akka.Remote.RemoteTransportException: No transport is loaded for protocol: [akka], available protocols: [akka.tcp]

### ISSUE THREAD

**Issue by lgphp** [akkadotnet/akka.net#5513]
i have a ActorServer writed by Java ,  use artery's remote, then i use Akka.NET writed a client ,  then client can't associate the server. how should i do ?

**Comment by Aaronontheweb** [comment]
The two services will not be able to communicate with each other - wire protocols are two different. If you want these services to interface together you'll either need to use a custom protocol built on top of gRPC / Web API or perhaps some socket interchange using Akka.IO.
