### ISSUE TITLE
An Akka.NET node running in a console-less environment may crash

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/akka.net#5524]
**Version Information**
Version of Akka.NET? All .NET Framework build
Which Akka.NET Modules? StandardOutLogger

**Describe the bug**
This bug is very edge casey, it is not an Akka.NET bug per se, but a bug of the underlying framework. Any Akka.NET build that is running in a console-less environment have a risk of random outage due to a bug in the .NET Framework Console code.

When you deploy a .NET Framework application as a windows service, both Console.Out and Console.Error are set to StreamWriter.Null. Problem is, StreamWriter.Null is a singleton class, so when a program outputs a normal and error console message at the same time, they collide inside the internal TextWriter instance, which is not thread save.

The exact exception thrown will be:
```
Probable I/O race condition detected while copying memory.
The I/O package is not thread safe by default.
In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods.
This also applies to classes like StreamWriter and StreamReader.
```

**To Reproduce**
See this [StackOverflow discussion](https://stackoverflow.com/questions/33915790/console-out-and-console-error-race-condition-error-in-a-windows-service-written).

**Expected behavior**
Node should not crash the process.

**Actual behavior**
Process died, downing the Node.

**Environment**
Any, as long as it is console-less

**Comment by Aaronontheweb** [comment]
This issue is already fixed in .NET Core and I don't really feel like going back and changing the way the `StandardOutLogger` works to accommodate this in versions of .NET Framework that are essentially being deprecated. Going to mark as "won't fix."
