### ISSUE TITLE
ClusterSingletonProxy keeps trying to identify singleton at ...

### ISSUE THREAD

**Issue by fscavo** [akkadotnet/akka.net#5525]
**Version Information**
Version of Akka.NET?  1.4.32
Which Akka.NET Modules?
Akka.Cluster
Akka.Cluster.Sharding

The cluster has only one member. The proxy keeps sending itself identify message periodically. Is this something normal and can be ignored?

**Comment by Aaronontheweb** [comment]
This is normal behavior:

https://github.com/akkadotnet/akka.net/blob/44c51f6786df0f97914381bd1c8b7f84013f7c0e/src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonProxy.cs#L128-L137

The `ClusterSingletonProxy` will try to identify where the singleton is located periodically on a timer - we have some `DEBUG` level logging that gets triggered each time this recurring message is processed.
