### ISSUE TITLE
Fix the "Mailing List" link in the homepage

### ISSUE THREAD

**Issue by nvivo** [akkadotnet/akka.net#554]
On http://akkadotnet.github.io/, the link to the Mailing List page should remove the language parameter.

From: https://groups.google.com/forum/?hl=sv#!forum/akkadotnet-user-list
To: https://groups.google.com/forum/#!forum/akkadotnet-user-list

Because the hl=sv forces the language, and it took some time for me to get what was going on there.

**Comment by SeanKilleen** [comment]
I think this might be best posted in the [Template repository](https://github.com/akkadotnet/template.akkadotnet.github.com). I'll post it there, reference this, and submit a PR.

**Comment by SeanKilleen** [comment]
FYI, I've created an Issue and pull request over in what I believe is the appropriate repository. We may wish to close this issue in favor of that one.

**Comment by Aaronontheweb** [comment]
Thanks for fixing this, @SeanKilleen and @nvivo - we really appreciate it!
