### ISSUE TITLE
Docs: `Unsubscribe` does not terminate Topic Actor

### ISSUE THREAD

**Issue by eaba** [akkadotnet/akka.net#5563]
**Please describe what you are trying to understand**
https://getakka.net/articles/clustering/distributed-publish-subscribe.html#publish
> ...or you can explicitly remove entries with DistributedPubSubMediator.Unsubscribe

Actors are automatically removed from the registry when they are terminated. [ _**Actors are terminated if there are zero subscribers and no new subscriber within a given deadline - the default is 2 minutes. You can change the deadline by setting `removed-time-to-live` to a desired duration**_]

**Comment by Aaronontheweb** [comment]
This is correct - and this should be added.

We should also talk about when `DeadLetter`s are produced in DistributedPubSub too, since that's not been clear - per the issues we've just recently resolved.

**Comment by eaba** [comment]
> This is correct - and this should be added.
> 
> We should also talk about when `DeadLetter`s are produced in DistributedPubSub too, since that's not been clear - per the issues we've just recently resolved.

Noted
