### ISSUE TITLE
Akka.DependencyInjection failed to instantiate actor because IServiceProvider was disposed

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/akka.net#5654]
**Version Information**
Version of Akka.NET? 1.4.32
Which Akka.NET Modules? Akka.DependencyProvider

**Describe the bug**
Akka.DependencyProvider fails to instantiate actors because IServiceProvider has been disposed.
![image](https://user-images.githubusercontent.com/8293237/153915745-4c3ae0e2-1170-4d38-a95e-dcd11cb15d71.png)

**To Reproduce**
No reproduction yet.

**Comment by Arkatufus** [comment]
@ismaelhamed could be, I've been scratching my head on this one for weeks. I'll give this a go and see if it reproduces the problem, thanks for the heads up!

**Comment by Aaronontheweb** [comment]
Going to mark this as "won't fix" - a hiesenbug if there ever was one.
