### ISSUE TITLE
Add ability to write MultiNodeTestkit output to multiple destinations (message sink)

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#567]
I'm going to propose that we make the following changes to the `MultiNodeTestKit`:

1. Add the concept of a "message sink" - a generic destination for log messages. Multiple message sinks can be run in parallel: a sink to the console, a sink to file, a sink to a socket, etc... The goal of each message sink is to organize log messages in accordance with each medium.
2. Make the message sinks enabled for a particular test run configurable as optional arguments on the `MultiNodeTestRunner` command line. Keep it so the default behavior is **console-only**, but you can optionally enable output to file, network, etc...

Any thought on this? cc @smalldave @akkadotnet/developers

**Comment by smalldave** [comment]
Sounds good. Wondering if there is some way to intercept messages to actors and use that to log messages?

**Comment by rogeralsing** [comment]
Could possibly be solved with the monitor infrastructure we are planning

**Comment by Aaronontheweb** [comment]
I'm thinking that I'm going to add a lightweight actor system inside the `MultiNodeTestRunner` to sequence and order messages for orderly writes to the console and other sinks.

@rogeralsing Having some monitoring infrastructure will absolutely help with the multinode tests, especially tracking things like failures, restarts, and timeouts inside the `/system/` actors.

**Comment by Aaronontheweb** [comment]
@smalldave I made some changes yesterday that will allow us to change the logging configuration for all `Akka.Cluster.Tests` in one place. I can turn "log-all-messages=on" and pipe everything to the console for each node, and this code snippet you wrote:

```csharp
 process.OutputDataReceived +=
                                (sender, line) => Console.WriteLine("[Node{0}]{1}", nodeIndex, line.Data);
```

Should pipe all messages from every individual node into the main `MultiNodeTestRunner` process, as long as each of those nodes is configured to use a logger that writes to console. We just need an actor to sequence the messages as they arrive from each child process.

**Comment by Aaronontheweb** [comment]
@smalldave so I have this implemented now - need to do a bunch of cleanup (and sadly, add a layer of unit tests for testing the test runner :\) but here's what some of the aggregated output for the `ConsoleSink` looks like:

[RUNNER][2:47 AM]: Results for Akka.Cluster.Tests.MultiNode.ClusterDeathWatchMul
tiNode1.ConvergenceSpecTests
[RUNNER][2:47 AM]: Start time: 2/3/2015 2:47:17 AM
[RUNNER][2:47 AM]:  --> Node 1: PASS [00:00:23.5693678 elapsed]
[RUNNER][2:47 AM]:  --> Node 2: PASS [00:00:23.5673694 elapsed]
[RUNNER][2:47 AM]:  --> Node 3: PASS [00:00:23.5593666 elapsed]
[RUNNER][2:47 AM]:  --> Node 4: PASS [00:00:23.5583672 elapsed]
[RUNNER][2:47 AM]:  --> Node 5: PASS [00:00:23.5623674 elapsed]
[RUNNER][2:47 AM]: End time: 2/3/2015 2:47:41 AM
[RUNNER][2:47 AM]: FINAL RESULT: PASS after 00:00:23.6513725.

I tweaked a couple of things inside the `MultiNodeTestRunner` and now have everything getting logged to standard I/O and redirected to a lightweight actor system that splits all log messages out into a tree structure.

Going to try to get all of this stuff cleaned up by Wednesday, but it's now a lot easier for me to see where tests may or may not be failing than it was before.

**Comment by smalldave** [comment]
Looks good. Those real results. The test appears to have passed?
