### ISSUE TITLE
Enforce strict timeouts for MultiNodeSpecs

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#572]
Currently seeing scenarios where some tests appear to hang indefinitely. Need to add some guarantees that within the `MultiNodeTestRunner` that we explicitly kill hung tests and mark them as failures for nodes who failed to report in.

**Comment by smalldave** [comment]
Also getting this. Not sure why, didn't happen before. Generally the tests end up waiting on EnterBarrier and that should timeout.

**Comment by Aaronontheweb** [comment]
@smalldave is it possible that I missed some of your commits when I merged / rebased everything on ad3b810d6fba53b7ffaca7c48528abfeaa93e49c ?

**Comment by smalldave** [comment]
Possibly or something else has affected it. I just went back to multinodetest branch on my fork. that is not hanging (it is failing though :()

**Comment by Aaronontheweb** [comment]
I'm not getting any failures on my local branch - but it does hang :\

**Comment by Aaronontheweb** [comment]
@smalldave can you do a diff between what's in the current `/dev/` branch versus your `multinodetest` banch and see if there's an major differences aside from the XML-DOC comments I added?

**Comment by smalldave** [comment]
Finally got around to looking at this.
Anything changed here? Tests aren't hanging on the dev branch for me.

**Comment by Aaronontheweb** [comment]
@smalldave I'll double check later today - almost done with my MultiNodeTestRunner changes which should make the event stream a little easier to follow and save to disk.

**Comment by rogeralsing** [comment]
I think this comes from the akka-persistence merge, where actors needs to do extra stuff on lifecycle events.
I agree this seems odd, might be better off triggering this extra logic from within the actor cell, right?

Skickat från Outlook




On Mon, Feb 2, 2015 at 10:17 AM -0800, "Aaron Stannard" <notifications@github.com> wrote:












@smalldave I'll double check later today - almost done with my MultiNodeTestRunner changes which should make the event stream a little easier to follow and save to disk.

**Comment by Aaronontheweb** [comment]
@rogeralsing might be the case, but I have another slightly more embarrassing (for me) theory below.

@smalldave turns out the entire test suite was running without indefinite timeouts, but I'm a moron and didn't realize that there was a `Console.ReadKey` that I needed to hit before the program exited :(

(sooooooooo I think the MultiNodeTestKit is actually running just fine. I'll be over here, minding my own business :walking: )

**Comment by smalldave** [comment]
Oops :). Either you did some kind of jedi mind trick on me or I did see them hang myself.
Anyway hope that is sorted..

**Comment by smalldave** [comment]
And should probably get rid of that readkey?

**Comment by Aaronontheweb** [comment]
@smalldave yeah, I'll get rid of that in my PR. Since we wait for each process to close down that should take care of the details.
