### ISSUE TITLE
Need Serialization tests for all actor primitives

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#573]
Per #569, need to add some tests to `Akka.Tests.Serialization` that explicitly test the serializability of all  of the following primitives:

1. Props
1. Deploy
1. RouterConfig
1. Address
1. ActorPath
1. Config (?)

Should we break this up into one issue for each?

**Comment by rogeralsing** [comment]
I'm taking this one

**Comment by Aaronontheweb** [comment]
Resolved as of #581

**Comment by AlbertoMonteiro** [comment]
@Aaronontheweb @rogeralsing the meaning of Serializability is the same that those links explain

- https://msdn.microsoft.com/pt-br/library/ms710099(v=vs.85).aspx
- https://en.wikipedia.org/wiki/Serializability

**Comment by Aaronontheweb** [comment]
We're referring to Serialization, not Serializability - being able to guarantee that a primitive Akka.NET type can be represented as a byte array
