### ISSUE TITLE
Bumping out preconfigured JSON serializer seems to be not possible although it should be

### ISSUE THREAD

**Issue by jonnydee** [akkadotnet/akka.net#5737]
**Version Information**

- Version of Akka.NET: 1.4.33
- Akka.NET Modules: Akka, Akka.Remote

**Bug Description**

Apparently, with bugfix https://github.com/akkadotnet/akka.net/issues/5569 it should be possible to [bump registered serializers out](https://gitter.im/akkadotnet/akka.net?at=61f2c33d6d9ba23328e1b6c9) of the [Akka Serializer ID Code Table](https://getakka.net/articles/serialization/serializer-codes.html) by overriding specific serializer types registered with a dedicated ID as follows:

```hocon
akka.actor.serialization-identifiers {
    "Some.Namespace.To.ThrowingSerializer, SomeAssembly" = 1
}
```

However, it seems like a proper replacement does not take place.

**Steps to Reproduce**

1. Create a sample application with `Akka.Remote` as dependency and in a simple Akka configuration just configure remoting and enable configuration logging with `akka.log-config-on-start = on`.

2. Start application and look at the logged configuration section `serialization-identifiers`. It should look similar to:

   ```hocon
   serialization-identifiers : {
       "Akka.Serialization.ByteArraySerializer, Akka" : 4
       "Akka.Serialization.NewtonSoftJsonSerializer, Akka" : 1
       "Akka.Remote.Serialization.ProtobufSerializer, Akka.Remote" : 2
       "Akka.Remote.Serialization.DaemonMsgCreateSerializer, Akka.Remote" : 3
       "Akka.Remote.Serialization.MessageContainerSerializer, Akka.Remote" : 6
       "Akka.Remote.Serialization.MiscMessageSerializer, Akka.Remote" : 16
       "Akka.Remote.Serialization.PrimitiveSerializers, Akka.Remote" : 17
       "Akka.Remote.Serialization.SystemMessageSerializer, Akka.Remote" : 22
   }
   ```

3. Create a custom serializer `ThrowingSerializer` within namespace `Some.Namespace.To` and assembly `SomeAssembly`:

   ```csharp
    class ThrowingSerializer : Akka.Serialization.Serializer
    {
        public ThrowingSerializer(ExtendedActorSystem system) : base(system) { }

        public override bool IncludeManifest { get; } = false;

        public override object FromBinary(byte[] bytes, Type type)
            => throw new ArgumentException($"ILLEGAL MESSAGE TYPE: {type}");

        public override byte[] ToBinary(object obj)
            => throw new ArgumentException($"ILLEGAL MESSAGE TYPE: {obj?.GetType()}");
    }
    ```

4. Put the following sections into Akka's configuration:

   ```hocon
   akka.actor {
       serializers {
           throwingSerializer = "Some.Namespace.To.ThrowingSerializer, SomeAssembly"
       }
       serialization-identifiers {
           "Some.Namespace.To.ThrowingSerializer, SomeAssembly" = 1
       }
   }
   ```

5. Restart application and look at the logged `serialization-identifiers` section again. It now contains two entires which map to ID `1`.

**Expected behavior**

The `serialization-identifiers` section should only contain a single entry which maps to ID `1` (i.e. `"Some.Namespace.To.ThrowingSerializer, SomeAssembly"`):

```hocon
serialization-identifiers : {
    "Akka.Serialization.ByteArraySerializer, Akka" : 4
    "Akka.Remote.Serialization.ProtobufSerializer, Akka.Remote" : 2
    "Akka.Remote.Serialization.DaemonMsgCreateSerializer, Akka.Remote" : 3
    "Akka.Remote.Serialization.MessageContainerSerializer, Akka.Remote" : 6
    "Akka.Remote.Serialization.MiscMessageSerializer, Akka.Remote" : 16
    "Akka.Remote.Serialization.PrimitiveSerializers, Akka.Remote" : 17
    "Akka.Remote.Serialization.SystemMessageSerializer, Akka.Remote" : 22
    "Some.Namespace.To.ThrowingSerializer, SomeAssembly" : 1
}
```

**Actual behavior**

The finally logged configuration `serialization-identifiers` section now has two entries mapping to ID `1`:

```hocon
serialization-identifiers : {
    "Akka.Serialization.ByteArraySerializer, Akka" : 4
    "Akka.Serialization.NewtonSoftJsonSerializer, Akka" : 1
    "Akka.Remote.Serialization.ProtobufSerializer, Akka.Remote" : 2
    "Akka.Remote.Serialization.DaemonMsgCreateSerializer, Akka.Remote" : 3
    "Akka.Remote.Serialization.MessageContainerSerializer, Akka.Remote" : 6
    "Akka.Remote.Serialization.MiscMessageSerializer, Akka.Remote" : 16
    "Akka.Remote.Serialization.PrimitiveSerializers, Akka.Remote" : 17
    "Akka.Remote.Serialization.SystemMessageSerializer, Akka.Remote" : 22
    "Some.Namespace.To.ThrowingSerializer, SomeAssembly" : 1
}
```

**Environment**

- Windows 10
- .NET Framework 4.8

**Additional context**

I am not sure if my expectation that a replacement should take place is correct. But according to a [Gitter comment](https://gitter.im/akkadotnet/akka.net?at=61ec60255dc6213cd4f5a91a) existing `serialization-identifiers` can be overridden in order to

> essentially "bump" the Newtonsoft.Json serializer out of the picture
> so whenever a message tries to load that upon deserialization your implementation should be used instead

If the existence of two entries in the logged `serialization-identifiers` configuration section is expected behavior then how can I verify that the `Newtonsoft.Json` serializer won't be used in any circumstances anymore?

**Comment by Arkatufus** [comment]
Due to the way HOCON is being parsed, this is not possible. However, you can force HOCON to override the value of the default settings to something that you know would not be used in the future. For example, you can decide that any serializer identification above 1,000,000 should be ignored, add the following settings to your HOCON:

```
serialization-identifiers {
  "Akka.Serialization.NewtonSoftJsonSerializer, Akka" : 1000001
}
```

If you ever see this serializer ID in the future, you'll know that something in your settings is wrong.

**Comment by Arkatufus** [comment]
Item replacement in HOCON can only happen on key collision, since the keys are different, there is no way to replace the identifiers.
To enable replacement, we would have to invert the way the settings declared from [serializer class name]:[id] to [id]:[serializer class name]

**Comment by Aaronontheweb** [comment]
Ok got it, so you have to replace the Newtonsoft.Json ID with another integer and then add a new serializer in its place with the id of 1. The step that @jonnydee was missing, and what we are missing in our documentation is the first step - need to reset the ID of Newtonsoft.Json. Could we document that here? https://getakka.net/articles/serialization/codes.html

**Comment by Aaronontheweb** [comment]
cc @Arkatufus

**Comment by Arkatufus** [comment]
Will do

**Comment by jonnydee** [comment]
@Arkatufus I'm afraid the workaround of using some unused ID for Newtonsoft.Json doesn't help for my use case. The goal is to make it impossible for an attacker to send a message which will be deserialized with Newtonsoft.Json. But using the workaround outlined here would mean the attacker just needed to know the new ID of the Newtonsoft.Json serializer and configure the ID in his Actor System, too. I do understand, however, that this workaround is the best we can get. So I hope it'll suffice...
