### ISSUE TITLE
Mark all ActorBase.Around[X] methods as internal?

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#583]
I noticed the following when I was writing some of my own actors today - that my own user-level actors could override any of these lifecycle methods:

```csharp
        /// <summary>
        ///     Can be overridden to intercept calls to `preRestart`. Calls `preRestart` by default.
        /// </summary>
        /// <param name="cause">The cause.</param>
        /// <param name="message">The message.</param>
        public virtual void AroundPreRestart(Exception cause, object message)
        {
            PreRestart(cause, message);
        }
```

And most of the other lifecycle methods found here: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/ActorBase.Lifecycle.cs

Are these *supposed* to be overrideable by user-level actors? Or are these methods only meant to be overridden by Akka.NET built-in actor types?

I'm a bit confused - can anyone shed some light on this? cc @akkadotnet/developers

**Comment by Aaronontheweb** [comment]
@Horusiath, but shouldn't that abstraction be invisible to me when I'm working on a simple `ReceiveActor` or `UntypedActor` - couldn't I theoretically break the behavior of Akka.Persistence if I overrode the wrong method?

**Comment by Horusiath** [comment]
@Aaronontheweb theoretically there are many places, where overriding actor-associated virtual methods could potentially break actor behavior (eg. `PostStop` method), but we enable to do so anyway.

> With great power comes great responsibility

**Comment by Aaronontheweb** [comment]
Welp, looks like canonical Akka does indeed expose this stuff. That settles it then.
