### ISSUE TITLE
Akka.NET v0.8 planned release

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#586]
Hi gang!

I wanted to propose a new stable release of Akka.NET with a tentative ship date of February 11th.

Here's what will be included in Akka.NET v0.8:

1. All of @jcwrequests work on adding dependency injection support for Ninject, Autofac, and CastleWindsor. These will all ship as independent NuGet packages.
1. Remote deployment of routers and routees, per #198 
1. Fixes for serialization on all actor primitives per @rogeralsing's work on #581 
1. New beta release of Akka.Cluster, which should include support for cluster-deployed `Pool` routers.
1. And if @Horusiath blesses it, I would like to propose an alpha release of Akka.Persistence so early adopters can start kicking the tires on it.

Any other notable changes that should be included in this release? Anything we should delay? Other thoughts?

**Comment by Horusiath** [comment]
![You have my sword](http://lizapalmer.com/wp-content/uploads/2013/10/aragorn.jpg)

... at least for basic Akka.Persistence, F# API is not ready yet ;)

**Comment by rogeralsing** [comment]
@Horusiath <3 oxox

**Comment by Aaronontheweb** [comment]
@Horusiath 
![whiskey-approval](https://cloud.githubusercontent.com/assets/326939/6016289/84c549f6-ab34-11e4-9ba3-0909152c8c1c.gif)

**Comment by mmisztal1980** [comment]
![](http://makeameme.org/media/created/heavy-breathing.jpg)

**Comment by skotzko** [comment]
![excited wrestler](https://cloud.githubusercontent.com/assets/311226/6033502/5ac01f72-abcb-11e4-8b3b-edc71394fa84.gif)

**Comment by weitaolee** [comment]
great

**Comment by nvivo** [comment]
Awaiting impatiently. =)

**Comment by Aaronontheweb** [comment]
It's on - coming on February 11th!

**Comment by Aaronontheweb** [comment]
All of the technical work for this release is finished. Cleaning up release notes and docs for the new DI and Persistence libraries. Should be out this afternoon PST.

**Comment by nvivo** [comment]
Hi @Aaronontheweb, please note I updated the DI documentation yesterday based on the current design. There is a small formatting issue I still need to fix though.

**Comment by Aaronontheweb** [comment]
@nvivo thanks for sending that in - makes my job easier :)

**Comment by rogeralsing** [comment]
Released so closing this
