### ISSUE TITLE
Akka solution file won't open in Xamarin studio

### ISSUE THREAD

**Issue by skotzko** [akkadotnet/akka.net#590]
The base solution file, `Akka.sln`, will not open in Xamarin Studio and throws an error: "Load operation failed. Argument is out of range. Parameter name: count"

I was able to recreate this on 2 machines. 
Steps to reproduce: open the `Akka.sln` file.

Here are the full system / version details, and a screenshot of the error.

![screen shot 2015-02-05 at 7 37 58 pm](https://cloud.githubusercontent.com/assets/311226/6074231/95a23716-ad6e-11e4-8d36-35f61ee41256.png)

## xamarin version details
Xamarin Studio
Version 5.7 (build 661)
Installation UUID: b5be8091-7a30-4207-bfdc-7ba90c953daf
Runtime:
	Mono 3.12.0 ((detached/a813491)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 312000068

Apple Developer Tools
Xcode 6.1 (6602)
Build 6A1052c

Xamarin.iOS
Not Installed

Xamarin.Android
Not Installed

Xamarin.Mac
Not Installed

Build Information
Release ID: 507000661
Git revision: b70bab61da996da29045ea8ee8aed1a6faedbe78
Build date: 2015-01-05 16:31:31-05
Xamarin addins: 82f6c71490562d6cd125a09287f441902fdac3d7

Operating System
Mac OS X 10.10.1
Darwin Andrews-MacBook-Air-4.local 14.0.0 Darwin Kernel Version 14.0.0
    Fri Sep 19 00:26:44 PDT 2014
    root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64

**Comment by skotzko** [comment]
Follow up: I found some links saying that all components (Xamarin.iOS, etc) need to be installed. Tried that, but didn't work. Still get the same error.

**Comment by Aaronontheweb** [comment]
Would @mattnischan know?

**Comment by mattnischan** [comment]
I can't say that I've run into this, but I haven't loaded the solution in a while.

I can try it on my OSX VM later and see what I come up with.

**Comment by Aaronontheweb** [comment]
Cool, thanks @mattnischan !

**Comment by skotzko** [comment]
@mattnischan were you able to find anything on this?

**Comment by rogeralsing** [comment]
I noticed that the same problem exists in monodevelop in older versions, but works fine with the latest release of their site.

Skickat från min iPhone

**Comment by skotzko** [comment]
@rogeralsing cool. @migueldeicaza asked me to also file this in Xamarin's tracking system, so it also lives there now. [Here's the link](https://bugzilla.xamarin.com/show_bug.cgi?id=27611).

**Comment by skotzko** [comment]
This issue is now resolved. Unclear whether it was an update on Xamarin's end or something in the project, but it works now.
