### ISSUE TITLE
Rename `SetHandler` method that accepts an `Inlet` and an `Outlet` to `SetHandlers`

### ISSUE THREAD

**Issue by ismaelhamed** [akkadotnet/akka.net#5921]
**Version Information**
Akka 1.4.37
Akka Streams

**Describe the issue**
Method `SetHandler` that accepts both an `Inlet` and an `Outlet` should be named `SetHandlers` (plural). This looks like a small typo, but it made me think we didn't have that feature implemented when I first looked.

**Comment by Aaronontheweb** [comment]
Do we just need to add a new overload to do this?

**Comment by ismaelhamed** [comment]
In order to avoid a breaking change we could add a new method with the correct name (`SetHandlers`) and deprecate the current one. 

BTW, and you guys have probably already thought about this, but prior to releasing Akka.NET 1.5 it might be a good idea doing some cleanup and removing most of the methods already marked as `Obsolete`. Otherwise I don't think it's ever going to happen ;)

**Comment by Aaronontheweb** [comment]
@ismaelhamed 

> BTW, and you guys have probably already thought about this, but prior to releasing Akka.NET 1.5 it might be a good idea doing some cleanup and removing most of the methods already marked as Obsolete. Otherwise I don't think it's ever going to happen ;)

100% - planning on deleting the old MNTR and Akka.DI libraries next week, for starters.
