### ISSUE TITLE
[PERF]Akka.Cluster.Sharding becomes unresponsive when sending multiple messages for different entities at same time

### ISSUE THREAD

**Issue by vladud** [akkadotnet/akka.net#5948]
**Version Information**
1.4.36 (but encountered issue on older versions also, haven't tried 1.4.38 yet but pretty sure it will be the same)
Akka.Cluster.Sharding, HashCodeMessageExtractor

**Describe the performance issue**
Is there a known throughput limitation for the amount of concurrent (or really close) calls to a shard region for different entities? I didn't find one written anywhere...
I'm experiencing heartbeat delays and node unreachable logs whenever there are multiple calls to a shard region for different entities. 
Also the node seems to become stuck/slow and it can take some time to recover. 

**Data and Specs**
You can find a simulation of this behavior here: https://github.com/vladud/TestAkkaClusterPerformance
(relevant code here: https://github.com/vladud/TestAkkaClusterPerformance/blob/main/src/TestAkkaCluster/AkkaService.cs and https://github.com/vladud/TestAkkaClusterPerformance/blob/main/src/TestAkkaCluster/LazyWorker.cs)
It's basically just a lighthouse and cluster node and I'm sending 1000 messages to the shard region. The cluster node becomes unresponsive and LH marks him as unreachable. 
I should point out that I'm simulating here some kind of execution by sleeping for 500ms inside the Worker actor. But the issue reproduces even when doing normal processing, I/O, db calls. etc. Actually it happens even sooner then.
Also here I'm sending messages in process, when using remoting the issue happens again sooner.

Even when trying to send "batches" of messages, rather than all together the results are not great. Basically it seems it can manage only batches of 20messages with delays of 400ms in between batches (and even then at the end the cluster node marks LH as being unreachable). 
I'm also doing a "warmup" which is basically making sure the actors are up before I send all the messages at the same time. For the warmup I'm not doing thread sleep inside the actor and it seems to be enough to not block the node. But in a real life scenario this didn't really work and I had to send messages in small batch sizes with delays between them. Without this warmup the cluster becomes unresponsive even sooner (even when doing batches of 20messages and delays of 400ms).

You can run runScenarios.ps1 to simulate the behavior. You can also run manually and set different parameters in defaultTestParams.json but at least from my tests across multiple machines (but with similar specs) the results seemed quite consistent.
**.\runScenarios.ps1 -scenario NoBatchCausingUnreachable**
  - it sends 1000 messages in a foreach loop and on each message the actors sleep for 500ms.
**.\runScenarios.ps1 -scenario NoBatchCausingUnreachable**
  - it sends 1000 messages in batches of 50 messages with a delay of 200ms between them.
**.\runScenarios.ps1 -scenario WithBatchNoUnreachable**
  - it sends 1000 messages in batches of 10 messages with a delay of 500ms between them.

**Expected behavior**
I assume this limitation is not normal because it is quite a low threshold, maybe I'm missing something obvious, some misconfiguration or something...

**Actual behavior**
Is there a benchmark for how many messages for unique entities the shard cluster can handle? Aren't the heartbeats and gossip sent/handled regardless of the fact that the shard region is busy or not?

**Environment**
win, .net 4.8, .net standard 2.1, .net 6.0, doesn't seem to matter

**Additional context**
CPU/RAM usage is low, so it's not an issue of resources.

**Comment by ismaelhamed** [comment]
@vladud you're blocking inside the actor, and that's a [NoNo](https://manuel.bernhardt.io/2017/05/15/akka-anti-patterns-blocking/) in Akka.

```csharp
public class LazyWorker : ReceiveActor
{
    private readonly ILoggingAdapter _log = Logging.GetLogger(Context);

    public LazyWorker()
    {
        ReceiveAsync<DoWork>((doWork) =>
        {
            if (doWork.IsWarmup)
            {
                _log.Info($"{doWork.EntityId}: I'm all warmed-up!");
                return Task.CompletedTask;
            }

            return DoNothing(doWork);
        });
    }

    private Task DoNothing(DoWork doWork)
    {
        var delayMs = doWork.Shift;
        _log.Info($"{doWork.EntityId}: Warking hard for {delayMs}ms");
        return Task.Delay(TimeSpan.FromMilliseconds(delayMs));
    }
}
```

**Comment by vladud** [comment]
Damn.. that should have been obvious.
Ok, I'll try switching to ReceiveAsync and not block in the real world code and I expect I'll get same improvement as in this demo.

Thanks!

**Comment by Aaronontheweb** [comment]
Can we mark this one as closed then?

**Comment by vladud** [comment]
Yes, after switching to async and not blocking anymore I'm not having performance issues anymore.
