### ISSUE TITLE
AKKA.NET Cluster Serialization Error

### ISSUE THREAD

**Issue by JsAndDotNet** [akkadotnet/akka.net#5986]
**Version Information**
Version of Akka.NET? 1.4.38
Which Akka.NET Modules? Akka.Cluster

**Describe the bug**
I am trying to create an AKKA cluster, however, when I try to send information to the cluster, I get the following error:

> [WARNING][09/06/2022 13:41:07][Thread 0024]
> [akka.tcp://ClusterSystem@localhost:2550/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FClusterSystem%40localhost%3A2551-1/endpointWriter/endpointReader-akka.tcp%3A%2F%2FClusterSystem%40localhost%3A2551-1] 
> Deserialization failed for message with serializer id [6] and manifest []. 
> Transient association error (association remains live). Failed to deserialize payload object 
> when deserializing ActorSelectionMessage with payload [SerializerId=9, Manifest=A] addressed to 
> [system,distributedPubSubMediator]. Could not find any internal Akka.NET serializer with Id [9]. 
> Please create an issue in our GitHub at [https://github.com/akkadotnet/akka.net].. 
> Serializer Id [6] is used to instantiate 
> [Akka.Remote.Serialization.MessageContainerSerializer, Akka.Remote]. 
> You can add it by adding a fallback to your ActorSystem configuration by using
> [RemoteConfigFactory.Default()].
> Cause: System.Runtime.Serialization.SerializationException: 
> Failed to deserialize payload object when deserializing ActorSelectionMessage with payload 
> [SerializerId=9, Manifest=A] addressed to [system,distributedPubSubMediator]. 
> Could not find any internal Akka.NET serializer with Id [9]. 
> Please create an issue in our GitHub at [https://github.com/akkadotnet/akka.net].

**To Reproduce**
I've created a super basic sample project - [here](https://github.com/JsAndDotNet/AKKA.NET-Cluster).

- [SimpleCluster](https://github.com/JsAndDotNet/AKKA.NET-Cluster/tree/main/SimpleAkkaDotNetCluster/SimpleCluster) is the cluster
- [SimpleClusterCaller](https://github.com/JsAndDotNet/AKKA.NET-Cluster/tree/main/SimpleAkkaDotNetCluster/SimpleClusterCaller) is the client.

Repro:
1. Open the project in VS2022.
2. Run `SimpleCluster`
3. Run `SimpleClusterCaller`

**Expected behavior**
Expect to be able to connect to the cluster and use any/all nodes.

**Actual behavior**
Error - see above for error description.

**Environment**
Windows 
.NET 6 (6.0.203)

**Additional context**

I have looked at the docs for [akka cluster](https://getakka.net/articles/configuration/modules/akka.cluster.html), as well as [Reactive Applications with Akka.NET](https//www.manning.com/books/reactive-applications-with-akka-net) and other issues such as [this](https://github.com/akkadotnet/akka.net/issues/3031) (after which I tried changing the hocon), but I can't work out what the problem is.

I tried updating everything to 1.4.39, but this seemed to create more errors, so I reverted to 1.4.38.

Any help would be much appreciated please!

**Comment by Aaronontheweb** [comment]
No problem - as a sidenote, it probably won't happen until next year but we're probably going to gradually start deprecating `ClusterClient` and replace it with gRPC + Akka.Streams. There are a number of reasons for doing that, but the big one is that it makes it easier for "non-Akka.NET" services to interact with an Akka.NET cluster, especially when those services are written in different languages (i.e. a React.JS front-end that wants to talk to a .NET 6 Akka.NET cluster.)

However, lots of users still currently use `ClusterClient` and it's fully supported. Just thought I'd color your experience with a message from the future ;)

**Comment by JsAndDotNet** [comment]
Hi @Aaronontheweb .

I no longer get the error.

However, now it doesn't do anything at all.

I've spent hours trying to work it out (and have re-checked the akka.net samples), but I don't know what's wrong?

Appreciate this goes beyond the issue, but please could you help?

I updated the git [repo](https://github.com/JsAndDotNet/AKKA.NET-Cluster) with your suggestion (and didn't commit all my other attempts to get it working following that to avoid confusion)

**Comment by Aaronontheweb** [comment]
You need to uncomment this: https://github.com/JsAndDotNet/AKKA.NET-Cluster/blob/2da653d5dea535b05a773183952b303a8286b5d1/SimpleAkkaDotNetCluster/SimpleClusterCaller/Program.cs#L57-L58

And make sure that the first parameter is the local path of the actor _on the cluster_ you want to contact.

**Comment by JsAndDotNet** [comment]
Thanks for getting back to me. 

I've now [updated,](https://github.com/JsAndDotNet/AKKA.NET-Cluster/blob/04c7d58c3697d970cb5e02c63adb366b07504b2e/SimpleAkkaDotNetCluster/SimpleClusterCaller/Program.cs#L57) but it's still just hanging. I'll have another look on Monday with a clear head.

Thanks again. J

**Comment by JsAndDotNet** [comment]
I can't get it working. I have read a lot of material and tried a good few things, but am hitting a dead end. The fact there's no errors most of the time makes it very hard to work out.

The AKKA.NET Samples have a cluster, but not something that calls that cluster. If the sample could be updated to have both a cluster AND calling app, that would be really helpful to people getting started.

**Comment by Arkatufus** [comment]
@JsAndDotNet I have a working ClusterClient and ClusterClientReceptionist sample, hope this helps: https://github.com/Arkatufus/Akka.Net.Samples/tree/master/ClusterClient

**Comment by Arkatufus** [comment]
@JsAndDotNet I've made a pull request on your original repo with changes to make it work. I've added some comments to explain the quirks related to working with external `Ask` and `ClusterClient`. Hope it helps.
https://github.com/JsAndDotNet/AKKA.NET-Cluster/pull/1

**Comment by JsAndDotNet** [comment]
Thank you @Arkatufus  and @Aaronontheweb for your help with this. Really appreciate the effort you've gone to. 😍

**Comment by Aaronontheweb** [comment]
No problem, based on this issue we decided to streamline `ClusterClient` creation inside Akka.Hosting, which we've just released to NuGet a few minutes ago: https://github.com/akkadotnet/Akka.Hosting/releases/tag/0.3.3
