### ISSUE TITLE
Need value-based equality for Props

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#600]
Per @rogeralsing's comment on #581 

> We should add new issues for serializing `SupervisorStrategy` [see #599] and how to verify that `Props` have been properly serialized. (they do get serialized correctly, we can just not do an Equals compare on them)

This might also relate to #550 and #546

**Comment by rogeralsing** [comment]
One thought I had, maybe we could just ignore equality for props, and instead make a test based on comparing actor behavior. e.g. create a props with args and other settings, create an actor from it, examine behavior from it.
Serialize the props. create a new actor based on the serialized props, examine the behavior from it.

if both actors behave the same, the props did serialize successfully.

**Comment by Aaronontheweb** [comment]
@rogeralsing we really only need this for unit testing, right?

**Comment by rogeralsing** [comment]
Yes

**Comment by Aaronontheweb** [comment]
In that case, anything should be fine - can even compare the stringified output of serialization of the `Props` together if it really came down to that.

**Comment by rogeralsing** [comment]
I'm putting this one on hold, there is no benefit from this except from testing purposes
