### ISSUE TITLE
Akka.Persistence: Allow `RecoverAsync`

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#6022]
**Is your feature request related to a problem? Please describe.**

Ran into this issue while working with an end-user: user recovers a `SnapshotOffer` or a persisted event of some kind, but needs to refresh an authentication / bearer token in-line in order to complete recovery for a specific entity.

We support `CommandAsync` on the `PersistentActor` API surface right now, but not a `RecoverAsync` option - therefore sending an HTTP request to refresh a token either has to be done synchronously or the user has to develop some additional messaging + an additional post-`Recovery` behavior in order to handle this.

**Describe the solution you'd like**

It would be better if we just allowed some of the `Recover` delegates to similarly support `RecoverAsync` the way we do for `CommandAsync` once a `PersistentActor` has already recovered.

We should also make this backwards compatible for Akka.NET v1.4.

**Describe alternatives you've considered**

>  therefore sending an HTTP request to refresh a token either has to be done synchronously or the user has to develop some additional messaging + an additional post-`Recovery` behavior in order to handle this.

This is how the user is currently handling it, which is less than ideal.

**Additional context**

We'll need to port this to 1.5 also.

**Comment by ismaelhamed** [comment]
Though I get the sentiment, user should be wary of not doing any side-effects as part of their recovering, and do so only upon receiving a `RecoveryCompleted` event or in the `OnReplaySuccess` (we typically use the later). That means *some additional messaging + an additional post-Recovery behavior* as you said, but, in truth, that's the Akka Way.

**Comment by Aaronontheweb** [comment]
I think you’re right - the other issue here, after thinking about it more, is doing that async work in recovery contributes to the possibility of a recovery timeout. Post recovery command handling is really the way to go here. I’ll close this issue.
