### ISSUE TITLE
Akka.TestKit.Xunit2 - Issues with Xunit running tests concurrently

### ISSUE THREAD

**Issue by garethjames-imburse** [akkadotnet/akka.net#6105]
**Version Information**
v1.4.39
Akka.TestKit.Xunit2

**Describe the performance issue**
We have a solution with ~1,000 Xunit tests. When running with the default xunit configuration, random tests will timeout at random stages (`ExpectMsg`, `Ask` etc.), even when timeout thresholds are set to 30 seconds.

However, when we configure Xunit in all assemblies so that the maximum number of parallel threads per assembly is 1, all tests pass consistently:

```json
{
  "$schema": "https://xunit.net/schema/current/xunit.runner.schema.json",
  "maxParallelThreads": 1
}
```

**Expected behavior**
Expect that we should be able to run tests concurrently.

**Environment**
Windows / .NET 6.0 / Visual Studio 2022 and dotnet CLI.

**Additional context**
We're struggling to understand what's happening to cause some tests to wait so long. Is there any guidance that can be offered by way of best practices or gotchas to ensure tests can be run concurrently without issue?

**Comment by Aaronontheweb** [comment]
We don't run Akka.NET's own test suite concurrently for this reason - neither do we run the Phobos test suites et al. The reason being for this is that when tests have strict timing windows (i.e. this operation must be completed in 100ms or less) the side effects from multiple tests all sharing the same `ThreadPool` and CPUs result in a lot of false negatives. We have spent _years_ trying to improve this, including rewriting the entire Akka.TestKit to be natively `async Task` in Akka.NET v1.5 - it's a tedious problem that occurs in any highly concurrent / highly-time-sensitive test suite.

I wish I had a better answer for you - but in the meantime, I'll offer some advice that can make this easier:

1. **Don't "overfit" short timeouts / completion times** - if we're testing a piece of code that is supposed to complete or timeout within 100ms, it's probably a good idea to make sure our assertion timeframe is significantly more generous. Factors such as OS clock resolution (20ms, usually) are enough to guarantee a test failure here even without the side effects of running multiple things in parallel. This is a problem we constantly run into with the Akka.Streams test suite in particular.
2. **Make most timeouts effectively infinite for operations that simply need to return an expected result** - when I say "effectively infinite" I don't mean literally infinite - that will hang your test suite when things don't work as expected. I mean that if you expect an operation to complete within 5s, give it 60. If the operation still couldn't complete on-time then that's a bug with the underlying code, not an issue with running tests concurrently.
3. **Relax the expected order in which work should be completed in tests** - another category of race condition that blows up many of our tests are "strict ordering" assertions. These don't often get discovered until we're running on a congested, under-powered build agent - developers can get away with these strict orderings on fast developer hardware but not on slow build systems. Using a library like FluentAssertions, you can assert that you received all of the expected results _without also asserting that they arrived in the exact, specified order_. If the operations don't need to be completed in that order, then make sure you don't assert that in the tests.
