### ISSUE TITLE
Stash.UnstashAll() raises exception when there are no stashed items

### ISSUE THREAD

**Issue by skotzko** [akkadotnet/akka.net#612]
This occurs in v0.7.1.

**Comment by Aaronontheweb** [comment]
Let's try to reproduce this in a unit test.

**Comment by nvivo** [comment]
I think this is not actually a bug, but just me misinterpreting the errors displayed by akka.

I was using a TypedActor, and when an exception is thrown in the Handle method, it shows in the log as a "TargetInvocationException", but it actually is wrapping my own exception and I didn't pay attention.

UnstashAll is not throwing exceptions. This may be closed.

**Comment by Aaronontheweb** [comment]
Haha, thanks @nvivo - I panicked a little bit because this would be a severe bug. Thanks for calling off the dogs :p
