### ISSUE TITLE
Shard Passivate During AsyncCommand Breaks Persists Within Subsequent AsyncCommand Handlers

### ISSUE THREAD

**Issue by danielstuartparker** [akkadotnet/akka.net#6157]
**Version Information**
Akka.NET version 1.4.43 
Modules:
Akka version 1.4.43
Akka.Persistence version 1.4.43
Akka.Cluster version 1.4.43
Akka.Cluster.Sharding version 1.4.43

**Describe the bug**
If a shard is passivated around the same time as an async command is sent, then the async handler will run, but any Persist calls within the handler won't complete properly. Instead, the WriteMessageSuccessful message ends up in the dead letter queue.

**To Reproduce**
Checkout the project:
[Github Repo](https://github.com/danielstuartparker/akka-net-cluster-shard-passivate-async-command-persist-repro)
Run the program.
You will see the following output on the console:
Actor Starting
Async Command Received
Async Command Processed
Async Command Results Persisted
Passivating Shard
NonAsyncMessage Received
NonAsyncMessage Persisted
AsyncMessage Received
Actor Stopped

**Expected behavior**
The AsyncMessage should reach the Persist code block the same way the NonAsyncMessage does, and have the following output:
Actor Starting
Async Command Received
Async Command Processed
Async Command Results Persisted
Passivating Shard
NonAsyncMessage Received
NonAsyncMessage Persisted
AsyncMessage Received
AsyncMessage Persisted
Actor Stopped

The CommandAsync handler should complete the Persist callback the same way the Command handler completes the Persist callback. According to the docs for [ReceivePersistentActor.CommandAsync](https://getakka.net/api/Akka.Persistence.ReceivePersistentActor.html#Akka_Persistence_ReceivePersistentActor_CommandAsync_System_Type_System_Predicate_System_Object__System_Func_System_Object_System_Threading_Tasks_Task__) the actor should be suspended until the task completes, including calls to Perist.

The other behavior that I would expect is the shard could stop before the async command, and be brought back to life to run the async command.

**Actual behavior**
It appears like the actor is stopped during a handler for CommandAsync, before the Persist is completed. Whereas, in the same situation, the Persist in a non-async Command handler is completed before the actor is stopped.

**Environment**
Windows 11, netcoreapp3.1

**Additional context**
I am concerned about the affect this could have during rebalancing or just passivating my shards if they haven't been active in a while.

**Comment by Arkatufus** [comment]
This is by design. The way `CommandAsync` works is by creating a detached `Task` that uses a callback to resume the actor context.
If the actor was stopped using a `PosionPill`, the actor will be stopped unconditionally, and any results are sent to `DeadLetters`.

The proper way to do this is to defer the actor stop operation. 
1. Track your running async operation using a counter, 
    - Increase the counter on the start of any async operation
    - Decrease the counter on the completion of any async operation
    - Check if a stop operation is in progress after you decrease the counter
    - Only allow the actor to stop when this counter is 0
2. Use a custom stop message than the `PosionPill` when you call `Passivate()`
3. Add a `Command<T>()` handler to handle that custom stop message.
    - Use a boolean field as a flag to mark that a stop operation is in progress

I've done a PR on your reproduction repository to reflect this.
