### ISSUE TITLE
Akka.Persistence: returning `string.Empty` in `IWriteEventAdapter` can overwrite valid manifest

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#6159]
**Version Information**
Version of Akka.NET? v1.4.44, 1.5.0-alpha1
Which Akka.NET Modules? Akka.Persistence, Akka.Cluster.Sharding

**Describe the bug**

While working with the `OldCoordinatorStateMigrationEventAdapter`

https://github.com/akkadotnet/akka.net/blob/1b96294db2de1a85e670e3829c7c93a1f7a93687/src/contrib/cluster/Akka.Cluster.Sharding/OldCoordinatorStateMigrationEventAdapter.cs#L16-L36

I noticed that the rows in my SQL Server database for testing purposes had the following in their "manifest" column:

![image](https://user-images.githubusercontent.com/326939/194651713-9ef19790-b5ca-4320-a1ca-7e7e7f7d0a46.png)

Those messages should belong to `serializerId=13`, the sharding serializer. Instead they belong to the `StringSerializer`.

**To Reproduce**

Create any `IWriteEventAdapter` and implement the `Manifest` method to return `string.Empty` in combination with a `StringWithManifest` serializer.

**Expected behavior**

Original manifest is preserved unless `string.IsNullOrEmpty` returns `false` for the `IWriteEventAdapter.Manifest` method.

**Actual behavior**
What actually happened and how did it differ from your expectations?

Original manifest is overwritten with a `System.String` type.

**Additional context**

It seems like this would be a major issue for anyone using tags et al unless everyone is using Newtonsoft.Json / Hyperion, which embed type metadata directly into the payloads. Either that or it's a bug with the new Akka.Cluster.Sharding code in v1.5.

**Comment by to11mtm** [comment]
Can/should we check this against other versions?

I know in general, our 'manifest' handling is, to be polite, in dire need of improvement (Akka.Persistence.Linq2Db tagtable PR handles manifests 'properly', although of course past events are anyone's guess due to current impl.)

**Comment by Aaronontheweb** [comment]
So it's the base persistence plugin that has the error, I believe:

https://github.com/akkadotnet/akka.net/blob/bf543ff8e2e200369366fc7acc1df4a73471deb6/src/core/Akka.Persistence/Journal/WriteJournal.cs#L69-L71

Key method call is the `WithManifest` method:

https://github.com/akkadotnet/akka.net/blob/bf543ff8e2e200369366fc7acc1df4a73471deb6/src/core/Akka.Persistence/Persistent.cs#L366

There should be a `string.IsNullOrEmpty` check in this method, to indicate that this value is not specified.

One thing we could do for v1.5, which would be an improvement, is to break this API and have it return an `Option<string>` for manifest instead. That way the intent is much clearer.

**Comment by Aaronontheweb** [comment]
So two questions:

**What do we want to do for v1.4?**

I'd argue to keep the existing API but change the key line in the `WithManifest` line to read:

```csharp
public IPersistentRepresentation WithManifest(string manifest)
        {
            return Manifest == manifest || string.IsNullOrEmpty(manifest) ? this : new Persistent(payload: Payload, sequenceNr: SequenceNr, persistenceId: PersistenceId, manifest: manifest, isDeleted: IsDeleted, sender: Sender, writerGuid: WriterGuid, Timestamp);
        }
```

There could be side effects there and testing _all_ of them is probably not feasible. So another option for v1.4 is to do nothing.

**What do we want to do for v1.5?**

Breaking the `IWriteEventAdapter` interface to force users to return an `Option<string>` for `Manifest(object event)` would be a bigger improvement - that way any changes in behavior must be explicitly addressed by the end-user. That might be preferable over a silent behavior change like the one I proposed for v1.4.

**Comment by Aaronontheweb** [comment]
@akkadotnet/contributors @akkadotnet/core any feedback on making changes here for v1.4?

**Comment by Arkatufus** [comment]
This is not a bug in the `WriteJournal` code, its a bug in the `OldCoordinatorStateMigrationEventAdapter` code.
Instead of returning an empty string manifest, it should be forwarding the correct manifest for the event it is storing into the journal.

**Comment by Arkatufus** [comment]
We should not make any change to v1.4 because this problem is unique to the new cluster sharding.

**Comment by Arkatufus** [comment]
I've made a draft PR #6176 to try and fix this, comments are welcome

**Comment by Arkatufus** [comment]
@zbynek001 
By the way, the `OldCoordinatorStateMigrationEventAdapter` class looks very sketchy. Is it supposed to adapt `ShardCoordinator.ShardHomeAllocated()` events to plain string when reading from the journal?

**Comment by Aaronontheweb** [comment]
Yeah this might be a red herring based on some undocumented behavior in the `OldCoordinationStateMigrationEventAdapter` (it now actually does persist strings directly for remembered entities - had no idea.)
