### ISSUE TITLE
Akka.Cluster.Sharding: if a `ShardRegion` for entityA is already running on current node, why not just return `ShardRegionA` when user requests a `ShardRegionProxy` for A

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#6178]
**Is your feature request related to a problem? Please describe.**

`ShardRegionProxy` and `ShardRegion` effectively form identical (in the end) functions from the POV of end-user routing - in v1.4 and v1.5 today, if I'm on node localhost:9110 and I do:

```csharp
var shardRegion = ClusterSharding.Get(sys).StartRegion("a", ....);
var shardRegionProxy = ClusterSharding.Get(sys).StartProxy("a", ....);
```

Then

```csharp
shardRegion.Equals(shardRegionProxy) == false; // these are two different actors
```

This performs a bunch of duplicative work behind the scenes in-process to sync the `ShardRegionProxy` and `ShardRegion` within the same process for the same entity type.

**Describe the solution you'd like**

After looking at the `ClusterSharding` internals, I think it'd be pretty easy to check to see if we already have a `ShardRegion` for type A running and simple return it, rather than create a `ShardRegionProxy`.

```csharp
shardRegion.Equals(shardRegionProxy) == true; // the `ShardRegionProxy`
```

This is an edge-case optimization in instances where users create shard regions and proxies for the same entity in the same process - I don't know how common it is but we've seen it more than once. In the event that a user starts a proxy first and shard region second this optimization will not work and I'm 100% fine with that.

**Describe alternatives you've considered**

Is there any negative impact that could emerge from doing this? Side effects?

**Comment by ingted** [comment]
Doesn't the transparency of the proxy matter? @@a

**Comment by Aaronontheweb** [comment]
@ingted I don't think so - one of the benefits of Akka.Cluster.Sharding is the location transparency of entities.

**Comment by to11mtm** [comment]
> I don't know how common it is but we've seen it more than once. In the event that a user starts a proxy first and shard region second this optimization will not work and I'm 100% fine with that.

I think this is actually -good-, because there could be some advanced use cases where you may want to -temporarily- host a region yourself. (Mind you, I can't think of any, but hey you -can- do that with the existing setup AFAIK.)

So, having this condition present at least allows for such scenarios rather than locking users in.

**Comment by ingted** [comment]
Is it possible that a region is dead (unable to recover at the node again) but the proxy is still alive performing its duty?

**Comment by Aaronontheweb** [comment]
> at a region is dead (unable to recover at the node again) but the proxy is still alive performing its duty?

No, they'd both be toast unless a user explicitly killed the ShardRegion `IActorRef` but not the proxy - in which case that's not the framework's problem.

**Comment by Aaronontheweb** [comment]
I think I'm going to close this as a "not planned" - I think @to11mtm is right here. This is a pretty far-fetched use case so we might as well let the API stay flexible rather than locking users in.
