### ISSUE TITLE
Nuget install Akka.Streams.TestKit 1.5.0-alpha2

### ISSUE THREAD

**Issue by ingted** [akkadotnet/akka.net#6251]
![image](https://user-images.githubusercontent.com/4289161/201801752-c6688870-a85a-4654-9d43-a6f81cd70bb6.png)

**Comment by ingted** [comment]
Just using VS try to add a reference to an empty F# project, then it failed...

**Comment by Aaronontheweb** [comment]
Yeah this is a screw up on our part - we'll get that fixed.
