### ISSUE TITLE
`TestActorRef` can not catch exceptions on asynchronous methods 

### ISSUE THREAD

**Issue by Nican** [akkadotnet/akka.net#6265]
**Version Information**
Version of Akka.NET? `Akka 1.4.46`
Which Akka.NET Modules? `Akka.TestKit 1.4.46`, `xunit 2.4.1`

**Describe the bug**
I am attempting to test the behavior of Actors. I am not very good at it yet, so every once in a while there is an exception, and the test just swallows the exception, and I have to go search why `ExpectMsg` is timing out.  

I have found the best way to test the actor behavior is with `TestActorRef.Receive`, but it only works for synchronous methods.

**To Reproduce**
Test actor:
```C#
public class ExceptionActor : ReceiveActor
{
    public record GiveError();
    public record GiveErrorAsync();
    public ExceptionActor()
    {
        Receive<GiveError>((b) =>
        {
            throw new Exception("WAT");
        });

        ReceiveAsync<GiveErrorAsync>(async (b) =>
        {
            await Task.Delay(TimeSpan.FromSeconds(0.1));
            throw new Exception("WATASYNC");
        });
    }
}
```

This test fails (Expected behavior):
```C#
    [Fact]
    public void GetException()
    {
        var props = Props.Create<ExceptionActor>();
        var subject = new TestActorRef<ExceptionActor>(Sys, props, null, "testA");
        subject.Receive(new ExceptionActor.GiveError());
    }
```

This test does not fail (Not expected behavior): 
```C#
    [Fact]
    public void GetExceptionAsync()
    {
        var props = Props.Create<ExceptionActor>();
        var subject = new TestActorRef<ExceptionActor>(Sys, props, null, "testB");
        subject.Receive(new ExceptionActor.GiveErrorAsync());
    }
```

**Expected behavior**
To have a `ReceiveAsync` method for asynchronous method handling. 
OR 
Some mechanism that automatically watches for any unhandled exceptions in tests, and have the test failure display the information.

**Actual behavior**
Unhandled exceptions disappear.

**Environment**
.NET Core v7 on Windows

**Additional context**
I am fairly new to akka.net, but I am loving it. I am following the instructions on [Testing Actor Systems](https://getakka.net/articles/actors/testing-actor-systems.html), and it feels like I am missing something. Are there no better ways to watch that unhandled exceptions exist?

**Comment by Aaronontheweb** [comment]
Possibly related: https://github.com/akkadotnet/akka.net/issues/6279

**Comment by Aaronontheweb** [comment]
Actually, #6279 is definitely not related. This looks to me more like a lapse in the `TestActorRef` test suites itself.

@Arkatufus can you take a look at this for 1.4.47?

**Comment by Arkatufus** [comment]
Will do, I'll give a stab at this.
