### ISSUE TITLE
Akka.Streams: `System.NotSupportedException` when disposing stage with materialized `IAsyncEnumerable`

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#6280]
**Version Information**
Version of Akka.NET? v1.4.46, v1.5.0-alpha3
Which Akka.NET Modules? Akka.Streams

**Describe the bug**

When running a `Source<T>` built from an `IAsyncEnumerable<T>`, any attempt to dispose the `IAsyncEnumerable<T>` via its `DisposeAsync()` method results in the following exception being thrown:

```text
[WARNING][11/30/2022 4:36:06 PM][Thread 0008][LogSource (akka://OpsCenter)] Failed to dispose IAsyncEnumerator asynchronously
Cause: System.NotSupportedException: Specified method is not supported.
   at OpsCenter.ClusterState.Subscriptions.ClusterStreamManager.GetEnvironmentEventStream(String environmentId, ClusterStreamConfig config, CancellationToken cancellationToken)+System.IAsyncDisposable.DisposeAsync()
   at Akka.Streams.Implementation.Fusing.AsyncEnumerable`1.Logic.OnDownstreamFinish()
```

**To Reproduce**

I don't have a clean reproduction of this issue yet, but using the following in LinqPad with Akka.NET v1.4.46 installed:

```csharp
async Task Main()
{
		var actorSystem = ActorSystem.Create("MySys");

		using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(3));

		var (actorRef, src) = Source.ActorRef<int>(1000, OverflowStrategy.DropHead)
		.PreMaterialize(actorSystem.Materializer());
		
		Task.Run(() => {
			foreach(var i in Enumerable.Range(0, 100)){
				actorRef.Tell(i);
			}	
			//  shut down the stream
			//actorRef.Tell(PoisonPill.Instance);
		});


		await Source.From(() => src.RunAsAsyncEnumerable(actorSystem.Materializer())).RunForeach(i => Console.WriteLine($"{DateTime.UtcNow}: {i}"), actorSystem.Materializer());
}
```

I was able to trigger another bug with this stage:

```text
[ERROR][11/30/2022 9:02:21 PM][Thread 0082][[akka://MySys/user/StreamSupervisor-10/Flow-0-0-unknown-operation#943292100]] Error in stage [EnumerableSource]: Should never reach this code
Cause: System.InvalidOperationException: Should never reach this code
   at Akka.Streams.Implementation.Fusing.AsyncEnumerable`1.Logic.OnPull()
   at Akka.Streams.Implementation.Fusing.GraphInterpreter.Execute(Int32 eventLimit)
--- End of stack trace from previous location ---
   at UserQuery.Main() in C:\Users\aaron\AppData
```

As for the error with this code - I'll try another reproduction but I think it happens when `IActorContext` used to materialize the `IAsyncEnumerable` source is terminated.

**Expected behavior**

`IAsyncEnumerable` stages should be able to shut down correctly.

**Actual behavior**

The `IAsyncEnumerable` stage errs in various ways, which aren't properly supported right now.

**Comment by to11mtm** [comment]
I know I brought it up on Discord but to put it on record..

Is it worth making this change in https://github.com/akkadotnet/akka.net/pull/6268/ ?
```
++        public IAsyncEnumerable<TOut> RunAsAsyncEnumerableBuffer(
++            IMaterializer materializer,
++            int maxBuffer = 16)
++        {
++            return this.RunWith(
++                Sink.ChannelReader<TOut>(maxBuffer, true)
++                    .MapMaterializedValue(r => r.ReadAllAsync()), materializer);
++        }

        //Existing method, add obsolete
        /// <summary>
        /// Shortcut for running this <see cref="Source{TOut,TMat}"/> as an <see cref="IAsyncEnumerable{TOut}"/>.
--        /// The given enumerable is re-runnable but will cause a re-materialization of the stream each time.
++      /// The given enumerable is not re-runnable.
        /// This is implemented using a SourceQueue and will buffer elements and/or backpressure,
        /// based on the buffer values provided.
        /// </summary>
        /// <param name="materializer">The materializer to use for each enumeration</param>
        /// <param name="minBuffer">The minimum input buffer size</param>
        /// <param name="maxBuffer">The Max input buffer size.</param>
++        [Obsolete("minBuffer is No longer respected, Please use new overload",false)]
        public IAsyncEnumerable<TOut> RunAsAsyncEnumerableBuffer(
            IMaterializer materializer, int minBuffer = 4,
            int maxBuffer = 16) =>
--            new StreamsAsyncEnumerableRerunnable<TOut,TMat>(
--                this, materializer,minBuffer,maxBuffer);
++          return RunAsAsyncEnumerableBuffer(materializer,maxBuffer);
```

The main difference is that the `IAsyncEnumerable` is not 're-runnable` but TBH I'm not sure that's worth keeping.

**Comment by Aaronontheweb** [comment]
I think so - having more consistent / clean termination behavior is probably best. If users want re-runnable IAsyncEnumerables they'd be better off restarting the graph IMHO.

**Comment by Aaronontheweb** [comment]
Looks like we have a test case that _should_ cover this already 

https://github.com/akkadotnet/akka.net/blob/ae953d0595290c073acc71aed80077a880346574/src/core/Akka.Streams.Tests/Dsl/AsyncEnumerableSpec.cs#L208-L228

Stepping through with the debugger, I don't see it throw in this test. It does consistently in my reproduction application though.

**Comment by Aaronontheweb** [comment]
Related: https://github.com/dotnet/runtime/issues/51176

**Comment by Aaronontheweb** [comment]
Yep, this is the reason why I suspect:

https://github.com/dotnet/runtime/issues/51176#issuecomment-818875900

**Comment by Aaronontheweb** [comment]
closed via #6290

**Comment by tomachristian** [comment]
@Aaronontheweb  This problem still exists and still reproduces with the latest versions as of this writing.

**Comment by Aaronontheweb** [comment]
> @Aaronontheweb This problem still exists and still reproduces with the latest versions as of this writing.

Do you have a small sample streams graph I could see?

**Comment by tomachristian** [comment]
There isn't anything fancy we are doing to be honest:

![image](https://github.com/user-attachments/assets/c2d2b4ce-3b05-4620-a795-77f0681479ad)
![image](https://github.com/user-attachments/assets/2f19d637-866a-4f59-ab8b-3a81508806cc)
![image](https://github.com/user-attachments/assets/abc2d630-9cde-4b0f-bc13-6c14dc27cb53)

I don't know what much more to provide :(

**Comment by Aaronontheweb** [comment]
@tomachristian which version of .NET are you running on?

**Comment by tomachristian** [comment]
.NET 8

**Comment by Aaronontheweb** [comment]
@tomachristian ty, I've opened a new issue for this on #7381 because even though the exceptions and stages are the same, I suspect the bug is probably a variant of this one

**Comment by tomachristian** [comment]
Thank you very very much, @Aaronontheweb !
