### ISSUE TITLE
Memory footprint

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#629]
I've been profiling the Akka.NET footprint today.
It was not as good as I expected.
We seem to be at about 1300ish bytes per actor when they are fully created.
This is far too expensive.

I found a few problems.

1. Dispatchers are being recreated per actor, so each actor has its own dispatcher..
1. Watchers is eagerly initialized per actor as a HashSet. 
1. Same goes for WhatchedBy
1. Same goes for TerminateQueue

There should be a good amount of bytes to save by fixing the above issues.
e.g. replace hashset to some other structure, or make it lazy initialized or with a lower capacity

**Comment by Aaronontheweb** [comment]
Oooff on item 1 on that list. That's a big one.

As for the others, I would make them all Lazy

**Comment by Aaronontheweb** [comment]
Added this to V1 milestone
