### ISSUE TITLE
'No such host is known' when akka.net container trying to reach from VM02 to seed node in VM01

### ISSUE THREAD

**Issue by josan84** [akkadotnet/akka.net#6292]
Hi,

I've got two Akka.Net services running in two different VMs in the cloud, one in VM01 and one in VM02.
In VM01 I've got the service A that feeds data (and it's also the seed node) to service B (in VM02).

The configuration for service A is:

Dockerfile:
...
EXPOSE 2551 2660

ENV CLUSTER_IP "VM01"
ENV CLUSTER_PORT "2660"
ENV CLUSTER_SEEDS "[akka.tcp://PSystem@VM01:2551]"
...

The configuration for service B is:

Dockerfile:
...
EXPOSE 2661

ENV CLUSTER_IP "VM02"
ENV CLUSTER_PORT "2661"
ENV CLUSTER_SEEDS "[akka.tcp://PSystem@VM01:2551]"
...

The VMs can see each other after running successfully from powershell:
Test-NetConnection -ComputerName VM01 -Port 2551 (from VM02)
Test-NetConnection -ComputerName VM02 -Port 2661 (from VM01)

[WARNING][12/6/2022 1:29:14 PM][Thread 0013][akka.tcp://PSystem@VM02:2661/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FPSystem%40VM01%3A2551-1/endpointWriter] AssociationError [akka.tcp://PSystem@VM02:2661] -> akka.tcp://PSystem@VM01:2551: Error [Association failed with akka.tcp://PSystem@VM01:2551] []
[WARNING][12/6/2022 1:29:14 PM][Thread 0013][remoting (akka://PSystem)] Tried to associate with unreachable remote address [akka.tcp://PSystem@VM01:2551]. Address is now gated for 5000 ms, all messages to this address will be delivered to dead letters. Reason: [Association failed with akka.tcp://PSystem@VM01:2551] Caused by: [System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context)
   at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped)
--- End of stack trace from previous location ---
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.ResolveNameAsync(DnsEndPoint address, AddressFamily addressFamily)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.DnsToIPEndpoint(DnsEndPoint dns)
   at Akka.Remote.Transport.DotNetty.TcpTransport.MapEndpointAsync(EndPoint socketAddress)
   at Akka.Remote.Transport.DotNetty.TcpTransport.AssociateInternal(Address remoteAddress)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.Associate(Address remoteAddress)]

Could someone advise please?

NB: the containers have run successfully before locally in VM01 with a different configuration, so it must be an Akka configuration thing that I'm missing.

Thanks!

**Comment by josan84** [comment]
Thanks for the suggestion, that didn't work either.

Is there any other way I can test the connection with the seed node, where I don't need to start a service, using akka.tcp://PSystem@VM01:2551 ?

**Comment by josan84** [comment]
I have also tried with a simple remote connection:

Configuration for VM01:

` Config config = ConfigurationFactory.ParseString(@"
akka {  
    actor {
        provider = remote
    }
    remote {
        dot-netty.tcp {
            port = 2551
            hostname = 0.0.0.0         
            public-hostname = VM01
        }
    }
}
"); `
   
Configuration for VM02:
` var config = ConfigurationFactory.ParseString(@"
akka {  
    actor {
        provider = remote
    }
    remote {
        dot-netty.tcp {
		    port = 2661
		    hostname = 0.0.0.0
                    public-hostname = VM02
        }
    }
}
");`

And sending messages from VM02 with `system.ActorSelection("akka.tcp://PSystem@VM01:2551/user/actorsample"`

The same, it works locally by replacing public-hostname by localhost.  However, I get the same 'No such host is known.' as above. Any ideas?

Thanks

**Comment by josan84** [comment]
Replacing hostnames (VM01 and VM02) by IP address has worked.

Thanks

**Comment by Aaronontheweb** [comment]
Ah ok, so in that case it was that those DNS records weren't available or correct - the `No such host is known` error is a failure to resolve via DNS.

**Comment by josan84** [comment]
Not sure why it wouldn't resolve, using Test-NetConnection from inside the container works:
_Test-NetConnection -ComputerName VM01 -Port 2551_

Why not from the Akka.Net services?

**Comment by Aaronontheweb** [comment]
We just use `System.IO.Dns` to resolve DNS prior to binding sockets locally (the IP layer doesn't support it) and prior to establishing an outbound connection via Akka.Remote - so this is just built-in .NET standard library function calls; Akka.Remote doesn't do anything special.

When running on VM02, try running your `Test-NetConnection` command again and see if that resolves - the problem here is ultimately that .NET's own DNS system can't resolve the addresses being used and that's also a system-layer problem.

**Comment by josan84** [comment]
I could have tried this before, it worked by using the FQDN.
