### ISSUE TITLE
Cache dispatchers

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#631]
Related to #629 

Currently we do not cache dispatchers, so each actor gets it's own instance of a dispatcher.
In Scala they cache it in a concurrent hashmap.
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/dispatch/Dispatchers.scala#L73

They also have the concept of a dispatcher configurator, which we don't have yet.

**Comment by Aaronontheweb** [comment]
Concurrent named registry plus something that can instantiate a dispatcher class from config?

Sounds like a good idea. Do we want to put this on the V1 milestone? If so we should assign it.

**Comment by Aaronontheweb** [comment]
Added this to the V1 milestone

**Comment by Aaronontheweb** [comment]
I'll take this one
