### ISSUE TITLE
Documentation tools

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#632]
For those of us that are working on the Markdown documentation files.
Do take a look at Atom Editors markdown support, it is fantastic.
![atommarkdown](https://cloud.githubusercontent.com/assets/647031/6210862/42e40072-b5d4-11e4-9e22-bf9acfebc6d8.png)

Live preview of docs, including syntaxhighlighting and images.

**Comment by rogeralsing** [comment]
I am also working on a better site generator, now transitioning over to Assembe.IO, a static site generator much like Jekyll but for NodeJS.

If you want to try to build and preview the site locally, clone my repo https://github.com/rogeralsing/AkkaSiteTake2

And run grunt inside the root folder.
That should generate a folder called `web` containing all the site content.

**Comment by Aaronontheweb** [comment]
I'm using MarkdownPad2 at the moment - the free edition works pretty well
