### ISSUE TITLE
Akka.Serialization: regression with `Exception` serialization in 1.4.47 (custom properties are no longer included)

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#6324]
**Version Information**
Version of Akka.NET? 1.4.47
Which Akka.NET Modules? Akka.Remote

**Describe the bug**

Need @huzk to lend a hand here (this is distilled from my chat on Discord with him)

```
we use actor system with clustering and our remote actors pass exceptions within messages to convey the cause of the failure. Often these exceptions are custom derived from applicationexception with our  error id etc. after the recent changes for the exception serialization the exception do get deserialized as the correct derived exception type but none of the custom properties are being deserialized. Akka version 1.4.47 
```

```
we just had [Serializable] attribute on our exceptions
```

Looks like this is happening inside a `Status.Failure` message with a custom `Exception`.

--- NEED HELP BELOW

**To Reproduce**

_Links to working reproductions on Github / Gitlab are very much appreciated_

**Expected behavior**

**Actual behavior**
What actually happened and how did it differ from your expectations?

**Screenshots**

**Environment**
Are you running on Linux? Windows? Docker? Which version of .NET?

**Additional context**

**Comment by huzaifak** [comment]
The issue occurs when a remote agents sends a message back to the singleton. 

For example say you have a derived custom exception class as below. When TestMessage is sent from  node A to say Node B (singleton) the deserialized message will not have EventId set to the value sent by the node A.

We are not specifically using Success.Falure in our use case.

`[Serializable]
      class TestException : ApplicationException
      {
          public int EventId;

          public TestException(string message) :base(message) {
          }
      }
		
class TestMessage {
	public string Str;
	public TestException FailureCause;
}`

**Comment by Aaronontheweb** [comment]
I think based on our chat in Discord it looks like this never worked properly and / or wasn't an Akka.NET issue. If that's incorrecnt @huzaifak please let me know and I'll reopen it.
