### ISSUE TITLE
Source.runWith constraint mismatch in F#

### ISSUE THREAD

**Issue by ingted** [akkadotnet/akka.net#6326]
**Version Information**
Version of Akka.NET? 
![image](https://user-images.githubusercontent.com/4289161/210614685-e0e1cb5c-a6dc-4f6f-b1f1-490fe287ba42.png)

Which Akka.NET Modules?
Akka.Streams

**Describe the bug**

I re-write this demo in F# (simple single .fs file)
https://github.com/akkadotnet/Akka.Hosting/tree/dev/src/Examples/Akka.Hosting.CustomJournalIdDemo

My repo:
https://github.com/ingted/Akka.Hosting.CustomJournalIdDemo.FSharp

**To Reproduce**
1. open Program.fs in VS2022 and go to line 154
2. we can see
```
Sink.ActorRef<UserCreatedEvent>(Context.Self, "complete")
```
could upcast to type
```
IGraph<SinkShape<UserCreatedEvent>, Akka.NotUsed>
```
however 
```
srj0.RunWith<Akka.NotUsed>
```
doesn't accept type parameter Akka.NotUsed

![image](https://user-images.githubusercontent.com/4289161/210615142-f5977b49-70b3-4086-b50d-16191f93c9ef.png)

**Expected behavior**
This should be buildable

**Actual behavior**
It is unable to build

**Environment**
Are you running on Linux? Windows? Docker? Which version of .NET?

Windows 2019, .net 7.101

**Comment by ingted** [comment]
My bad... I forgot to add |> ignore

**Comment by Aaronontheweb** [comment]
> My bad... I forgot to add |> ignore

No worries - still appreciate that you filed a very detailed bug report ;)
