### ISSUE TITLE
Remove `TypedActor` from 1.5 branch

### ISSUE THREAD

**Issue by ismaelhamed** [akkadotnet/akka.net#6328]
Just a reminder. Even though the type is already marked obsolete, the removal is still pending.

**Comment by Aaronontheweb** [comment]
Yep, good idea.

**Comment by F0b0s** [comment]
Can you explain what branch i need to create PR to? dev?
Also there is a
`public interface IHandle<in TMessage>`
in the same [file](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/TypedActor.cs) and it's not used, can i delete it too?

**Comment by ismaelhamed** [comment]
@F0b0s Yes, `dev` is the ongoing development branch for v1.5

IMO, anything related to the `TypedActor` (including examples and specs, if any) should go away. @Aaronontheweb @Arkatufus is really anyone out there using this implementation of typed actors?

**Comment by F0b0s** [comment]
@ismaelhamed 

> IMO, anything related to the TypedActor (including examples and specs, if any) should go away

are you sure about deleting examples? We have an example [`SymbolLookup`](https://github.com/akkadotnet/akka.net/tree/dev/src/examples/Stocks/SymbolLookup) it written at .NET Framework 4.5 and it's [`StockActor`](https://github.com/akkadotnet/akka.net/blob/dev/src/examples/Stocks/SymbolLookup/Actors/TickerActors.cs) inherits from `TypedActor`. Maybe it would be better to rewrite example for .NET Core?

**Comment by Aaronontheweb** [comment]
> @F0b0s Yes, `dev` is the ongoing development branch for v1.5
> 
> 
> 
> IMO, anything related to the `TypedActor` (including examples and specs, if any) should go away. @Aaronontheweb @Arkatufus is really anyone out there using this implementation of typed actors?

No, they're all using Untyped and Receive actors

**Comment by ismaelhamed** [comment]
> are you sure about deleting examples? We have an example [`SymbolLookup`](https://github.com/akkadotnet/akka.net/tree/dev/src/examples/Stocks/SymbolLookup) it written at .NET Framework 4.5 and it's [`StockActor`](https://github.com/akkadotnet/akka.net/blob/dev/src/examples/Stocks/SymbolLookup/Actors/TickerActors.cs) inherits from `TypedActor`. Maybe it would be better to rewrite example for .NET Core?

@F0b0s, @Aaronontheweb has the final word

**Comment by Aaronontheweb** [comment]
@F0b0s those samples aren't referenced any more from the main solution IIRC - they can be deleted or modernized onto .NET 6. I'm cool with either - would you like to work on this issue?

**Comment by F0b0s** [comment]
@Aaronontheweb now i'm looking at [Akka.Persistence.Sqlite: add Akka.Persistence.Query support](https://github.com/akkadotnet/akka.net/issues/6347)

**Comment by Aaronontheweb** [comment]
@F0b0s excellent - that would be a great one to take on.
