### ISSUE TITLE
Cannot load custom rule markdownlint-rule-titlecase

### ISSUE THREAD

**Issue by ismaelhamed** [akkadotnet/akka.net#6335]
When I try to run the markdownlint tool locally I get the following error: 

```
PS> markdownlint "docs/**/*.md" --rules "markdownlint-rule-titlecase"
PS> Cannot load custom rule markdownlint-rule-titlecase: No such rule
```

I think I have everything I need already installed, so I must be missing something:

```
PS> npm list -g

+-- markdownlint-cli@0.31.0
+-- markdownlint-rule-titlecase@0.1.0
`-- npm@9.2.0
```

**Comment by SeanKilleen** [comment]
@ismaelhamed not sure, honestly. Just tried this in my current environment which happened to be node 16.17.0 x64, npm 8.15 and it worked as expected:

```console
PS C:\Users\SeanK\Repositories\akka.net> npm install -g markdownlint-cli@0.31.0 markdownlint-rule-titlecase@0.1.0

added 35 packages, and audited 37 packages in 3s

PS C:\Users\SeanK\Repositories\akka.net> markdownlint "docs/**/*.md" --rules "markdownlint-rule-titlecase"

...no errors found, so I change a heading and run it

PS C:\Users\SeanK\Repositories\akka.net> markdownlint "docs/**/*.md" --rules "markdownlint-rule-titlecase"

docs/articles/actors/coordinated-shutdown.md:5:1 titlecase-rule Titlecase rule [Title Case: 'Expected # Coordinated Shutdown, found # Coordinated shutdown']
```

**Comment by SeanKilleen** [comment]
I tried the latest node LTS (18.13.0) and it worked as expected on my machine.

I tried that with npm v8.19.3 and v9.3.0. So I'm sorry but I can't recreate your issue and it looks fine as far as I can tell. Happy to keep digging into it if you provide further details though!

**Comment by ismaelhamed** [comment]
Thanks @SeanKilleen , there might be something off with my machine then. I'll leave this open for a while in case I figure it out.

**Comment by Aaronontheweb** [comment]
Going to mark this issue as closed unless it comes up again
