### ISSUE TITLE
Utility class `FastLazy` has a race condition

### ISSUE THREAD

**Issue by peter-perot** [akkadotnet/akka.net#6336]
**Version Information**
Version 1.4.48 and later (including 1.5.x)
Package `Akka`

**Describe the bug**
The utility class `FastLazy` has a race condition that can lead to `Value` being produced multiple times. See [FastAtomicLazy Issue #2](https://github.com/Aaronontheweb/FastAtomicLazy/issues/2).

This issue has been resolved in the meantime, so please use the latest version.

But there is another issue with this class: [FastAtomicLazy Issue #12](https://github.com/Aaronontheweb/FastAtomicLazy/issues/12). This issue is only relevant if the producer function throws an exception.

**To Reproduce**
Since the issue is a race condition, there is no simple way to reproduce it. But it's an obvious Schroedinbug described in the linked issue.

**Expected behavior**
Only one thread should produce a value.

**Actual behavior**
The code in the `producer` funcion can be executed multiple times in very rare situations since the block calling `producer` is not entered in an atomic fashion.

**Environment**
Windows, but the issue is not dependent on the environment.

**Additional context**
The `FastLazy` implementation uses a `SpinWait` which can lead to high CPU load if the code executed in the `producer` function is not extremely short (only some IL instructions).

Are you shure that this condition is holding? If not I would avoid a `SpinWait`.

**Comment by F0b0s** [comment]
@Aaronontheweb why do we have two implementation of `FastLazy<T>`:

1. [FastAtomicLazy](https://github.com/Aaronontheweb/FastAtomicLazy) where [https://github.com/Aaronontheweb/FastAtomicLazy/issues/2](https://github.com/Aaronontheweb/FastAtomicLazy/issues/2) is fixed
2. [akka.net](https://github.com/akkadotnet/akka.net) [FastLazy<T>] (https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Util/FastLazy.cs) where the same problem still exists and still in use, for example in Akka.Serialization.Serializer

I can fix the issue but can't find out in which repo :)

**Comment by Aaronontheweb** [comment]
@F0b0s let's fix the issue in https://github.com/Aaronontheweb/FastAtomicLazy and then copy that version into https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Util/FastLazy.cs
