### ISSUE TITLE
Appears to be copy pasta in Docs.Tutorials - Tutorial4

### ISSUE THREAD

**Issue by F0b0s** [akkadotnet/akka.net#6342]
When i was looking [https://github.com/akkadotnet/akka.net/issues/4116](https://github.com/akkadotnet/akka.net/issues/4116 ) i found that the same tests set probably was copy pasted for tutorial 4 and is not used by documentation.

Tutorial only use this references:
`Tutorial4/DeviceGroupSpec.cs?name=group-query-integration-test`
But `Tutorial4/DeviceGroupSpec.cs` has a set of tests not included in `group-query-integration-test` region and these tests are the same as `Tutorial3/DeviceGroupSpec` but without fixes from [#4116](https://github.com/akkadotnet/akka.net/issues/4116).

I think it would be better to delete these tests.

**Comment by F0b0s** [comment]
@Aaronontheweb can you take a look, please?

**Comment by Aaronontheweb** [comment]
Why would we remove those tests if they're doing something functional? @F0b0s

**Comment by Aaronontheweb** [comment]
What's the real issue here, in other words?

**Comment by Aaronontheweb** [comment]
Aha - got it.

**Comment by Aaronontheweb** [comment]
@F0b0s merged! Thanks for your contribution!
