### ISSUE TITLE
Akka.Persistence.Sqlite: add Akka.Persistence.Query support

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#6347]
**Is your feature request related to a problem? Please describe.**

In order to make it easy for users to learn Akka.Persistence.Query, we should make it available in a low-ceremony plugin like Akka.Persistence.Sqlite.

**Comment by Aaronontheweb** [comment]
Optionally, we could also just do this for the in-memory Akka.Persistence.

**Comment by Ahmtdncr** [comment]
Anlayamadım

**Comment by to11mtm** [comment]
@Aaronontheweb  FWIW Akka.Persistence.Linq2Db supports Persistence.Query across SQLite. There may be some edge cases (Fixed in Tag Table PR) around efficiency of Query but it should be fairly usable in current state.

**Comment by F0b0s** [comment]
@Aaronontheweb can you take a look am i on the right way with it, please.

**Comment by Aaronontheweb** [comment]
Already implemented.

**Comment by Ahmtdncr** [comment]
instagram.com/ahmett_dincerr?igshid=ZjE2NGZiNDQ=)
