### ISSUE TITLE
`DeferAsync` inside an `AroundReceive` causes a `WriteMessagesFailed` exception in Akka Persistence

### ISSUE THREAD

**Issue by lucavice** [akkadotnet/akka.net#6355]
**Version Information**
"Akka" Version="1.4.48"
"Akka.Persistence" Version="1.4.48"
"Akka.Persistence.SqlServer" Version="1.4.35"

**Describe the bug**
Using `DeferAsync` inside an `AroundReceive` causes a WriteMessagesFailed exception:

```c#
WriteMessagesFailed<cause: System.ArgumentException: The tasks argument contains no tasks. (Parameter 'tasks')
```
I'm not sure if using `DeferAsync` inside an `AroundReceive` is a legitimate use to start with, but we have in our codebase a couple of places where this is in place, and it seems that `WriteMessagesFailed` should not be an outcome.

This is the underlying reason for previously opened issue https://github.com/akkadotnet/akka.net/issues/6106, where this error was triggering the circuit breaker (I found out it had nothing to do with concurrent recoveries).

I'm not sure if this issue belongs to the `Akka.Persistence.SqlServer` repo project, or if it's a symptom of something else.
It's also important to note that this happens only with `Akka.Persistence.SqlServer.Journal.SqlServerJournal` and NOT with the batching journal `Akka.Persistence.SqlServer.Journal.BatchingSqlServerJournal`

**To Reproduce**
I created a console app to reproduce the issue:
https://github.com/lucavice/AkkaNetBugRepro

For context, here is the `MyPersistentActor.cs` in the linked repo that generates the issue:

```c#
public class MyPersistentActor : ReceivePersistentActor
{

    public MyPersistentActor()
    {
        Recover<Ping>(p => true);
        
        Command<Ping>(p =>
        {
            Persist("", _ => {});
        });
    }

    protected override bool AroundReceive(Receive r, object message)
    {
        var result = base.AroundReceive(r, message);

        Console.WriteLine($"Message received {message} from {Sender.Path}");

        if (message is WriteMessagesFailed wmf)
        {
            Console.WriteLine($"WriteMessagesFailed received: {wmf.Cause}");
            Context.Stop(Self);
        }

        if (!IsRecovering && message is Ping)
        {
            // This defer async causes the bug
            DeferAsync( "", _ => Sender.Tell(new Pong()));
        }
        
        return result;
    }

    public override string PersistenceId => "MyId";
}
```

After configuring your own `connection-string` in `Program.cs`, the console app will output:
```
Message received Ping { } from akka://system/user/senderActor
Message received Akka.Persistence.RecoveryPermitGranted from akka://system/system/recoveryPermitter
Message received LoadSnapshotResult<toSeqNr: 9223372036854775807, snapshot: > from akka://system/deadLetters
Message received RecoverySuccess<highestSequenceNr: 0> from akka://system/deadLetters
Message received Ping { } from akka://system/user/senderActor
Message received Akka.Persistence.WriteMessagesSuccessful from akka://system/system/akka.persistence.journal.sql-server
Message received WriteMessageSuccess<actorInstanceId: 1, message: Persistent<pid: MyId, seqNr: 1, deleted: False, manifest: , sender: [akka://system/user/senderActor#280056127], payload: , writerGuid: 98d52bf2-2343-43a8-883f-96b6bc360ab8>> from
 akka://system/user/senderActor
Message received WriteMessagesFailed<cause: System.ArgumentException: The tasks argument contains no tasks. (Parameter 'tasks')
   at System.Threading.Tasks.TaskFactory.CheckMultiContinuationTasksAndCopy(Task[] tasks)
   at System.Threading.Tasks.TaskFactory`1.ContinueWhenAllImpl(Task[] tasks, Func`2 continuationFunction, Action`1 continuationAction, TaskContinuationOptions continuationOptions, CancellationToken cancellationToken, TaskScheduler scheduler)
   at Akka.Persistence.Sql.Common.Journal.SqlJournal.WriteMessagesAsync(IEnumerable`1 messages)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
   at Akka.Persistence.Journal.AsyncWriteJournal.<>c__DisplayClass21_0.<<HandleWriteMessages>g__ExecuteBatch|2>d.MoveNext()> from akka://system/system/akka.persistence.journal.sql-server
WriteMessagesFailed received: System.ArgumentException: The tasks argument contains no tasks. (Parameter 'tasks')
   at System.Threading.Tasks.TaskFactory.CheckMultiContinuationTasksAndCopy(Task[] tasks)
   at System.Threading.Tasks.TaskFactory`1.ContinueWhenAllImpl(Task[] tasks, Func`2 continuationFunction, Action`1 continuationAction, TaskContinuationOptions continuationOptions, CancellationToken cancellationToken, TaskScheduler scheduler)
   at Akka.Persistence.Sql.Common.Journal.SqlJournal.WriteMessagesAsync(IEnumerable`1 messages)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
   at Akka.Persistence.Journal.AsyncWriteJournal.<>c__DisplayClass21_0.<<HandleWriteMessages>g__ExecuteBatch|2>d.MoveNext()
```

**Environment**
Windows 11 on .NET 6

**Comment by to11mtm** [comment]
One odd side-comment on this.

At one point I was investigating using a segmented-linked-list in place of `LinkedList<T>`  within Akka.Net.

While it was a wash in performance (i.e. no benefit), I *did* distinctly notice that using such within Akka.Persistence internals led to unit tests failing (as opposed to Stash/etc where I experienced no problems.)

**Comment by Aaronontheweb** [comment]
I'll add this to our triage list - thank you @lucavice

**Comment by Aaronontheweb** [comment]
> I'm not sure if using DeferAsync inside an AroundReceive is a legitimate use to start with, but we have in our codebase a couple of places where this is in place, and it seems that WriteMessagesFailed should not be an outcome.

No, it's not supported and we don't plan on supporting it either. What were you trying to accomplish here @lucavice ?
