### ISSUE TITLE
Dangerous conversion operator in AtomicBoolean.cs

### ISSUE THREAD

**Issue by Baardi** [akkadotnet/akka.net#6392]
https://github.com/akkadotnet/akka.net/blob/192e9a886838ccb678be7287733a7cf5f6a983ad/src/core/Akka/Util/AtomicBoolean.cs#L91

I understand why it was added. It enables direct assignment to an AtomicBoolean variable.

e.g. 
```cs
AtomicBoolean myBool = true;
myBool = false;
// etc.
```

But I would consider conversion from bool to AtomicBool to be dangerous. this is basically a new allocation for the AtomicBool class itself, and this allocation isn't easily seen by other threads, as far as I understand. Although I do see it is generally allocated in the same place, and that we would be generally fine, but I don't see the C# standard guaranteeing it
Instead what should be promoted is to assign directly to the property of the original class.

```cs
AtomicBoolean myBool = new AtomicBoolean(true);
myBool.Value = false;
// etc.
```

By removing this dangerous implicit operator. This way you don't promote dangerous behaviour

**Comment by Baardi** [comment]
The same kind of dangerous conversion is also found in AtomicReference 

https://github.com/akkadotnet/akka.net/blob/192e9a886838ccb678be7287733a7cf5f6a983ad/src/core/Akka/Util/AtomicReference.cs#L95

**Comment by Aaronontheweb** [comment]
I don't think there are any / many instances of these used in public APIs, so while I think you're correct on the merits of the change there's not any practical risks here to Akka.NET users at the moment. It'd be a good idea to remove these APIs and enforce the thread-safe calls everywhere.

**Comment by Aaronontheweb** [comment]
> https://github.com/akkadotnet/akka.net/blob/192e9a886838ccb678be7287733a7cf5f6a983ad/src/core/Akka/Util/AtomicBoolean.cs#L91
> 
> I understand why it was added. It enables direct assignment to an AtomicBoolean variable.
> 
> e.g.
> 
> ```cs
> AtomicBoolean myBool = true;
> myBool = false;
> // etc.
> ```
> 
> But I would consider conversion from bool to AtomicBool to be dangerous. this is basically a new allocation for the AtomicBool class itself, and this allocation isn't easily seen by other threads, as far as I understand. Although I do see it is generally allocated in the same place, and that we would be generally fine, but I don't see the C# standard guaranteeing it Instead what should be promoted is to assign directly to the property of the original class.
> 
> ```cs
> AtomicBoolean myBool = new AtomicBoolean(true);
> myBool.Value = false;
> // etc.
> ```
> 
> By removing this dangerous implicit operator. This way you don't promote dangerous behaviour

After reviewing the code, I don't believe this is dangerous at all due to how the `AtomicBoolean.Value` property is implemented:

https://github.com/akkadotnet/akka.net/blob/053199edd6d3045605a7010e6ea0454073840286/src/core/Akka/Util/AtomicBoolean.cs#L37-L48

1. We insert a memory barrier during reads, which synchronizes memory access
2. We perform an `Interlocked.Exchange` during writes, which atomically swaps out the `int` value we use to represent the `bool` internally.

I believe we have our bases covered here and there's nothing inherently dangerous about the conversion operators. Happy to be proven wrong if that's not the case.

In the case of `AtomicReference<T>` we perform `volatile` reads and writes - which I believe should cover us (although it's not as robust as CAS).

I think this is a non-issue.

**Comment by Baardi** [comment]
> 

The problem isn't what assignment to Value does. That's perfectly fine.
I'm referring to the conversion operator that allocates an entirely new AtomicBoolean, in an entirely new place in memory. And the constructor doesn't have a memory barrier. This means that you might create a new AtomicBoolean in memory, the other threads won't necessarily see it. This is the behaviour I was referring to, that I thought was dangerous.

The reason I found this in the first place was due to typing AtomicBoolean in Visual Studio, and Visual Studio suggested this package. I decided not to use it, so in the end, I guess I care that much about how this issue is being resolved, but I still think that it's a bit dangerous to use

**Comment by Aaronontheweb** [comment]
I don't see your last reply on here @Baardi but I'll quote it from the email notification:

> The problem isn't what assignment to Value does. That's perfectly fine.
> I'm referring to the conversion operator that allocates an entirely new AtomicBoolean, in an entirely new place in memory. And the constructor doesn't have a memory barrier. This means that you might create a new AtomicBoolean in memory, the other threads won't necessarily see it. This is the behaviour I was referring to, that I thought was dangerous.
> 
> The reason I found this in the first place was due to typing AtomicBoolean in Visual Studio, and Visual Studio suggested this package. I decided not to use it, so in the end, I guess I care that much about how this issue is being resolved, but I still think that it's a bit dangerous to use

If you're `new`-ing up a new `AtomicBoolean`, that's an entirely new thread-safe object - no different than passing an `IEnumerable<T>` into the constructor of a `ConcurrentBag<T>`. There's zero need to synchronize the constructor.

What I can see happening though is and end-user screwing up and going-back-and-forth using conversion operators from / to `Atomic___`. These are really kind of meant to be internal APIs but yes, better safe than sorry. I've opened a PR here: https://github.com/akkadotnet/akka.net/pull/6429

**Comment by Baardi** [comment]
> I don't see your last reply on here @Baardi but I'll quote it from the email notification:
> 
> > The problem isn't what assignment to Value does. That's perfectly fine.
> > I'm referring to the conversion operator that allocates an entirely new AtomicBoolean, in an entirely new place in memory. And the constructor doesn't have a memory barrier. This means that you might create a new AtomicBoolean in memory, the other threads won't necessarily see it. This is the behaviour I was referring to, that I thought was dangerous.
> > The reason I found this in the first place was due to typing AtomicBoolean in Visual Studio, and Visual Studio suggested this package. I decided not to use it, so in the end, I guess I care that much about how this issue is being resolved, but I still think that it's a bit dangerous to use

I removed it as I wanted to make a more thought out answer, but it appears that you received the notification regardless.

> If you're `new`-ing up a new `AtomicBoolean`, that's an entirely new thread-safe object - no different than passing an `IEnumerable<T>` into the constructor of a `ConcurrentBag<T>`. There's zero need to synchronize the constructor.
> 
> What I can see happening though is and end-user screwing up and going-back-and-forth using conversion operators from / to `Atomic___`. These are really kind of meant to be internal APIs but yes, better safe than sorry. I've opened a PR here: #6429

This was exatcly what I was referring to. I agree to AtomicBoolean -> bool being safe, just not bool -> AtomicBoolean, since it enables direct assignment to the reference itself, instead of the underlying bool-value.
I guess it's a bit nitpicky of me though, I agree that internal stuff shouldn't matter that much.
