### ISSUE TITLE
ActorSystem.Create throws PlatformNotSupportedException on net7.0-android

### ISSUE THREAD

**Issue by whoteit92** [akkadotnet/akka.net#6459]
**Version Information**
1.4.49
Akka.NET

**Describe the bug**
We have an application that we decided to port to .NET MAUI to have it also be available on Android. When the application is run on Android, the following exception is thrown.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.get_BackgroundColor()
   at System.Console.get_BackgroundColor()
   at System.Reflection.RuntimePropertyInfo.StaticGetterAdapterFrame[ConsoleColor](StaticGetter`1 getter, Object _)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Reflection.PropertyInfo.GetValue(Object obj)
   at Akka.Actor.Internal.ActorSystemImpl.Start()
   at Akka.Actor.ActorSystem.CreateAndStartSystem(String name, Config withFallback, ActorSystemSetup setup)
   at Akka.Actor.ActorSystem.Create(String name, ActorSystemSetup setup)

**To Reproduce**
1. Create a .NET MAUI project targeting .NET 7.0
2. Add Akka.NET NuGet package
3. Call ActorSystem.Create (name and ActorSystemSetup overload)
4. Above exception will be thrown.

_Links to working reproductions on Github / Gitlab are very much appreciated_

**Expected behavior**
Either catch the exception thrown by the below line (ActorSystemImpl.cs) or add a compiler directive to not execute it on Android.
typeof(Console).GetProperty("BackgroundColor").GetValue(null); // HACK: Only needed for MONO

**Actual behavior**
PlatformNotSupportedException

**Environment**
Works fine on Linux and Windows. Throws on Android. Unable to test on iOS.

**Additional context**

**Comment by Aaronontheweb** [comment]
Ah, so it's this line that throws?

https://github.com/akkadotnet/akka.net/blob/46d680f20c6e014c0b710192ce03daec38c3e148/src/core/Akka/Actor/Internal/ActorSystemImpl.cs#L213-L214

That's _ancient_ code - I bet it can be removed safely these days.

**Comment by Aaronontheweb** [comment]
Added a PR to remove it here https://github.com/akkadotnet/akka.net/pull/6463

**Comment by whoteit92** [comment]
Thank you for the quick response, I will validate the official fix when the PR is merged (already validated that removing that line fixes the issue on our fork).

**Comment by Aaronontheweb** [comment]
@whoteit92 sounds good - that bit of code was added there probably in 2015, when Mono was the only real game in town to run Akka.NET on POSIX systems. Not needed anymore in the days of .NET Core (and Mono probably fixed that bug at some point.)
