### ISSUE TITLE
`NewtonSoftJsonSerializer` throws a `StackOverflow` exception when trying to deserialize an `object` field

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/akka.net#6502]
**Version Information**
Version of Akka.NET? 1.4.49/1.5.0
Which Akka.NET Modules? Akka

**Describe the bug**
`NewtonSoftJsonSerializer` throws a `StackOverflow` exception when trying to deserialize a class with an `object` field/property when assingned a `JObject` instance.

**To Reproduce**
#6503

**Expected behavior**
Should deserialize successfully

**Actual behavior**
Throws `StackOverflow`

**Environment**
Any

**Comment by Aaronontheweb** [comment]
We'll release a fix for this in 1.4.50 and 1.5.1

**Comment by Aaronontheweb** [comment]
Is there any relation to these types of issues? https://github.com/akkadotnet/akka.net/issues/4463

i.e. is this all Newtonsoft.Json type-conversion issues?

**Comment by Arkatufus** [comment]
That issue is actually by design, we are replacing int, decimal, and float with a JObject so that we can preserve the value type inside an anonymous object across the wire.

**Comment by Arkatufus** [comment]
Note that we're not replacing long and double as those are actually the default Newtonsoft Json behavior

**Comment by Aaronontheweb** [comment]
> That issue is actually by design, we are replacing int, decimal, and float with a JObject so that we can preserve the value type inside an anonymous object across the wire.

Which issue?

**Comment by Arkatufus** [comment]
I was replying to your comment on issue #4463

**Comment by Aaronontheweb** [comment]
Ah ok, so close that then?

**Comment by Arkatufus** [comment]
Either close that issue, or reconsider our JSON wire format to not replace value types

**Comment by Aaronontheweb** [comment]
Done

**Comment by Arkatufus** [comment]
These are the corresponding lines:
https://github.com/akkadotnet/akka.net/blob/f92c609a0c21127bfbf763474e41bf6810c4441f/src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs#L432-L438

https://github.com/akkadotnet/akka.net/blob/f92c609a0c21127bfbf763474e41bf6810c4441f/src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs#L455-L464
