### ISSUE TITLE
Wiki: Add ASP.NET Deployment Scenario

### ISSUE THREAD

**Issue by SeanKilleen** [akkadotnet/akka.net#655]
On the [Deployment Scenarios page](http://getakka.net/wiki/Use%20case%20and%20Deployment%20Scenarios), I noticed there is an empty section for ASP.NET.

Adding it here in case someone wants to take it on (may do so myself).

**Comment by Aaronontheweb** [comment]
This is a great idea. Go for it!

**Comment by SeanKilleen** [comment]
If nobody else jumps on it first, I'll try to do a quick "Hello World" example, especially now that we have support for some IoC containers. I'm by no means an authority, so I'll open a WIP pull request as I go and we can squash at the end.

Question: Since it would be a heck of a long example, I'm assuming that we'd want to add this to the `examples` directory and link to it, perhaps with a small snippet in the docs themselves. Is that in line with your thoughts on it?

**Comment by Aaronontheweb** [comment]
Should have a sample, but it doesn't belong in this repo imho.

**Comment by Aaronontheweb** [comment]
Finished publishing our sample earlier today: **[ASP.NET and Windows Serivce Microservices with Akka.Cluster](https://github.com/petabridge/akkadotnet-code-samples/tree/master/Cluster.WebCrawler)** - probably overkill with the clustering and microservice stuff.

**Comment by rogeralsing** [comment]
Thats a great example, but I think the example that should be described on the wiki should be smaller.
something along the lines of;

1. Create a console app
1. Nuget topshelf, akka.remote
1. Create an actor system
1. bla bla
1. Done.

It could absolutely link to a larger example.

Other thoughts?

**Comment by SeanKilleen** [comment]
@rogeralsing I'd like to see the larger asp.net example as well as a topshelf service example. While I agree that it's probably larger, I think a lot of people will want to understand various contexts and integration points they may not have otherwise thought of.

**Comment by SeanKilleen** [comment]
Closing this as the issue has moved to https://github.com/akkadotnet/getakka.net/issues/18.
