### ISSUE TITLE
Wiki: Add Windows Service Deployment Scenario

### ISSUE THREAD

**Issue by SeanKilleen** [akkadotnet/akka.net#656]
On the [Deployment Scenarios page](http://getakka.net/wiki/Use%20case%20and%20Deployment%20Scenarios), I noticed there is an empty section for Windows Service.

Adding it here in case someone wants to take it on (may do so myself).

**Comment by Aaronontheweb** [comment]
Also a good idea. Please do so :)

**Comment by Danthar** [comment]
I would defer Windows Service integration to TopShelf. No need to roll your own. Integration would be easy. Simply implement a container class that knows how to setup, start and stop your ActorSystem.
Then have TopShelf use that as its service.

**Comment by annymsMthd** [comment]
+1 for TopShelf

**Comment by Aaronontheweb** [comment]
TopShelf sounds like the best practice - I haven't used it myself but after looking at it yesterday I'm convinced. http://topshelf-project.com/ - made by Chris Patterson, some dude who's behind MassTransit.

**Comment by SeanKilleen** [comment]
Closing this as I've opened a corresponding issue in the getakka.net repository at https://github.com/akkadotnet/getakka.net/issues/17
