### ISSUE TITLE
Wiki: Carats in links to other pages

### ISSUE THREAD

**Issue by SeanKilleen** [akkadotnet/akka.net#657]
I noticed that several links on the wiki (which is nice, by the way) have `^` in their names.

Is this intentional? If not, I could jump in to help clean it up.

### Screenshot
![image](https://cloud.githubusercontent.com/assets/2148318/6267258/65cdbea0-b810-11e4-99bf-a13239bd60a7.png)

**Comment by rogeralsing** [comment]
The "^" is for code blocks that have a corresponding wiki page.

e.g.

`abcde` would not be linked<br/>
`ActorSystem` would be linked since there is such page.
Maybe underline would have been a better representation for links than ^ :)
It is inserted by JQuery if I recall correctly.

**Comment by SeanKilleen** [comment]
Ahh, that makes sense. I do agree that an underline is likely more intuitive for links than the `^`; 

Perhaps I'll look into updating the jQuery snippet to insert a class that adds an underline instead.

**Comment by SeanKilleen** [comment]
Closing this -- wiki is in another repo now and also upon further reflection, it doesn't matter much at all. :)
