### ISSUE TITLE
Wiki: Missing image in "Actor System" page

### ISSUE THREAD

**Issue by SeanKilleen** [akkadotnet/akka.net#658]
An image appears to be missing from the [Actor System page](http://getakka.net/wiki/ActorSystem).
Minor; just noting for future reference.

### Screenshot
![image](https://cloud.githubusercontent.com/assets/2148318/6267231/29cd3412-b810-11e4-982b-f8c7d65d434f.png)

**Comment by rogeralsing** [comment]
Fixed.
Thanks!
