### ISSUE TITLE
Wiki: Missing link to HOCON spec?

### ISSUE THREAD

**Issue by SeanKilleen** [akkadotnet/akka.net#659]
Reading through the [Configuration docs](http://getakka.net/wiki/Configuration), it looks like a link to the HOCON spec might be missing.

Minor; adding so someone (perhaps me) can address.

### Screenshot
![image](https://cloud.githubusercontent.com/assets/2148318/6268589/0a9b8f24-b81c-11e4-8fe8-3c6ac0c91098.png)

**Comment by rogeralsing** [comment]
Fixed.
Thanks for reporting!
