### ISSUE TITLE
Duplicate `ReadIsolationLevel` initialization

### ISSUE THREAD

**Issue by VasilievSerg** [akkadotnet/akka.net#6657]
Hello again. :)
I found one more suspicious code fragment via the PVS-Studio analyzer. 

The code:
```
protected BatchingSqlJournalSetup(....
  IsolationLevel readIsolationLevel,
  IsolationLevel writeIsolationLevel,
  ....)
{
  ....
  WriteIsolationLevel = writeIsolationLevel;
  ReadIsolationLevel = readIsolationLevel; // <=
  ReadIsolationLevel = writeIsolationLevel; // <=
  ....
}
```

Link to the sources: [link](https://github.com/akkadotnet/akka.net/blob/2fe0143447e0a06421a5acfc1ae03b61cad2429f/src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs#L405). 

It looks like the second assignment to `ReadIsolationLevel` is erroneous.

**Comment by Arkatufus** [comment]
Thanks, we'll delete the extra code
