### ISSUE TITLE
Plugin proposal: Akka.Persistence.Azure

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#668]
Add **Journal** and **SnapshotStore** implementations using Windows Azure Table Storage and Blobs on the backend. Since Windows Azure may be considered an important part of a .NET dev culture, I think it should be placed in contrib lib with major support from Akka.NET community.

Minimal Journal configuration necessary to make plugin work with Akka.Persistence correctly:

``` hocon
akka.persistence.journal {
  plugin = "akka.persistence.journal.azure"
  azure {
      class = "Akka.Persistence.Azure.CloudTableJournal, Akka.Persistence.Azure"
      plugin-dispatcher = "akka.actor.default-dispatcher"

      # connection string to cloud tables storage
      storage-connection-string= "DefaultEndpointsProtocol=https;AccountName=account-name;AccountKey=account-key"
  }
}
```

For SnapshotStore, it seems that Windows Azure Blob storage may be more appropriate implementation, than the tables. In that case this is minimal configuration necessary to make plugin work with Akka.Persistence correctly:

``` hocon
akka.persistence.snapshot-store {
  plugin = "akka.persistence.snapshot-store.azure"
  azure {
    class = "Akka.Persistence.Azure.CloudBlobSnapshotStore, Akka.Persistence.Azure"
    plugin-dispatcher = "akka.persistence.dispatchers.default-plugin-dispatcher"

     # connection string to cloud blob storage engine
     storage-connection-string= "DefaultEndpointsProtocol=https;AccountName=account-name;AccountKey=account-key"
  }
}
```

Integration tests can be done fairly simply using `Akka.Persistence.TestKit` library (see [Akka.Persistence.TestKit.Tests](https://github.com/akkadotnet/akka.net/tree/dev/src/core/Akka.Persistence.TestKit.Tests) for more details).

References:
- [MemoryJournal](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Persistence/Journal/MemoryJournal.cs) implementation based on `AsyncWriteProxy`. Other option is to use `SyncWriteJournal` instead (see canonical Akka's [LevelDbJournal](https://github.com/akka/akka/tree/master/akka-persistence/src/main/scala/akka/persistence/journal/leveldb))
- [LocalSnapshotStore](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Persistence/Snapshot/LocalSnapshotStore.cs) implementation.

**Comment by rogeralsing** [comment]
We should add a test base for integration tests imo.
That should be possible, right?

Predefined model + predefined data and tests on that.
The implementor overrides some methods for their implementation.
That would make it supereasy to verify that implementations behave the same.

**Comment by Horusiath** [comment]
@rogeralsing isn't `Akka.Persistence.TestKit` exactly what you're talking about? It's created to validate compatibility of custom persistence storages with Akka.Persistence.

**Comment by rogeralsing** [comment]
Doh, ignore my comment, my impression was that the persistence testkit was for end users building systems that uses persistence, not for devs creating providers. my bad :-)

**Comment by 4deeptech** [comment]
Guys, I have put together an implementation for this and had not seen this proposal. If somebody wants to review it, there is one Journal implementation for Table storage and two Snapshot implementations, one for Table and one for Blob.  All tests pass using the TestKit.  It also supports sharding across storage accounts with up to 16 accounts.  Tests configure 16 all using the same string. Pretty much first foray into OSS so may comment on whatever I have done that looks incorrect, inefficient, or doesn't follow certain standards.  https://github.com/4deeptech/Akka.Persistence.Azure

**Comment by Horusiath** [comment]
@4deeptech I've taken a look at your plugin. It looks good, but my only problem is that it's cheating users trying to make permanent delete. As Akka.Persistence supports both soft and hard deletes I think, that users who explicitly requested for a permanent delete, did so because they really mean it ;) Implementing both of them as logical flag switch looks clearly like work against user's intention to me.

**Comment by 4deeptech** [comment]
@Horusiath Ha...yes, we had a discussion about that.  I modified it to perform the permanent delete and refactored a few things.  Interested to see about performance.  Any word on #754?  I guess I should go find the pingpong test referenced.

**Comment by Silv3rcircl3** [comment]
Can this be closed since @4deeptech implemented the plugin?

**Comment by aph5nt** [comment]
@Silv3rcircl3 there are some breaking changes since 1.0.5; Azure presistance must be updated first

**Comment by aph5nt** [comment]
also.. the blob storage is reading snapshots based on the prefix. so if you have a snapshots named game and game-view then akka will try to restore state of game actor with the snapshot of the game view actor.

**Comment by Silv3rcircl3** [comment]
We now have a Azure persistence plugin, see https://github.com/alexvaluyskiy/Akka.Persistence.Azure
