### ISSUE TITLE
Akka.FSharp: need to pin `FSharp.Core` package version to 6.0

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#6687]
**Version Information**
Version of Akka.NET? v1.4.47 and later
Which Akka.NET Modules? Akka.FSharp, Akka.Persistence.FSharp

**Describe the bug**

A [F# Akka.NET user reported in Discord](https://discord.com/channels/974500337396375553/1100774536267432007) that Akka.NET triggers a NuGet package downgrade warning when installing into a .NET 6 solution in F#:

```
  Akka1.5.3Test.fsproj: [NU1605] Detected package downgrade: FSharp.Core from 7.0.0 to 6.0.5. Reference the package directly from the project to select a different version. 
 Akka1.5.3Test -> Akka.FSharp 1.5.4 -> FSharp.Core (>= 7.0.0) 
 Akka1.5.3Test -> FSharp.Core (>= 6.0.5)
```

**To Reproduce**

Full repo from @hkirk here https://github.com/hkirk/Akka1.5.3Test 

**Expected behavior**

Akka.FSharp should install normally into a .NET 6 application with no NuGet package downgrade warnings.

**Screenshots**

**Environment**

.NET 6 and below - anything below .NET 7.

**Additional context**

Obviously this doesn't happen - the issue occurred in Akka.NET v1.4.47 when we removed explicit references to Akka.FSharp here https://github.com/akkadotnet/akka.net/pull/6641 and bumped to 7.x here https://github.com/akkadotnet/akka.net/pull/6402.

Both of these PRs should be reverted.

**Comment by Aaronontheweb** [comment]
> Both of these PRs should be reverted.

And FSharp.Core should be set to 6.x

**Comment by Aaronontheweb** [comment]
https://github.com/dotnet/fsharp/blob/main/docs/fsharp-core-notes.md#package-authors-should-pin-their-fsharpcore-reference

**Comment by Aaronontheweb** [comment]
We should also, and this can be done in a separate PR, tell Dependabot not to upgrade FSharp.Core.

**Comment by hkirk** [comment]
Hej @Aaronontheweb I still get this error on version 1.5.4-1.5.7.

I've updated the repository with newest version of Akka and Akka.FSharp

**Comment by hkirk** [comment]
I have a potential fix (work around) here: https://github.com/hkirk/Akka1.5.3Test/tree/work_around
But not sure this is the correct way.
