### ISSUE TITLE
wiki: "Remoting" page cites a paper without link

### ISSUE THREAD

**Issue by xunilrj** [akkadotnet/akka.net#669]
http://getakka.net/wiki/Remoting

Although the paper is cited I can not found the paper link (nor its name).

"The key for enabling this is to go from remote to local by way of optimization instead of trying to go from local to remote by way of generalization. See this classic paper for a detailed discussion on why the second approach is bound to fail."

**Comment by rogeralsing** [comment]
Thanks for reporting, the missing link have been added to the page.
