### ISSUE TITLE
Nuget releasenotes Markdown formatting

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#670]
The nuget release notes are unformatted Markdown.
Is there any way to fix this?
e.g. running a markdown converter when publishing?

The current form is not very easy on the eye

![releasenotes](https://cloud.githubusercontent.com/assets/647031/6326409/a19ea7c0-bb51-11e4-8a7e-cdea6382f7ee.png)

**Comment by Aaronontheweb** [comment]
Yeah, not very easy on the eyes - do NuGet packages support any form of markup language at all? Or is it just plain text?

**Comment by Aaronontheweb** [comment]
It also looks like a lot of the whitespace I added to the release notes was stripped, too.
