### ISSUE TITLE
Moving to the new .NET Foundation CLA

### ISSUE THREAD

**Issue by ChrisSfanos** [akkadotnet/akka.net#6705]
Hi akkadotnet admins - the .NET Foundation is moving all projects to the new CLA service.  We need to make a set of config changes to your project to get that setup.  Please drop me a note at chris.sfanos @ dotnetfoundation.org to chat - either we can do the work for you or you can cover it - whichever you prefer

Thanks
Chris
.NET Foundation Operations Team

**Comment by Aaronontheweb** [comment]
Hi @ChrisSfanos - I think https://github.com/akkadotnet/.github/pull/15 should have taken care of this.

**Comment by ChrisSfanos** [comment]
I believe is is wrapped up
