### ISSUE TITLE
Load Akka Config from App.config automatically

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#671]
I would love to be able to remove the following boilerplate code from Akka.NET apps if possible:

```csharp
var section = (AkkaConfigurationSection)ConfigurationManager.GetSection("akka");
var config = section.AkkaConfig;
var actorSystem = ActorSystem.Create("MySystem", config);
```

And just have the following call, which would automatically load configuration sections in via ConfigurationManager:

```csharp
var actorSystem = ActorSystem.Create("MySystem");
```

Any objections to this?

**Comment by nvivo** [comment]
I think this makes sense.

Also, very soon the internal behavior will probably need some change to work with the new [config providers from asp.net vnext](http://whereslou.com/2014/05/23/asp-net-vnext-moving-parts-iconfiguration/), that don't require xml files. In that case, akka can load the settings directly from some hocon file with some `config.AddHoconFile('akka.config')`.

**Comment by rogeralsing** [comment]
This is already how it works...

**Comment by rogeralsing** [comment]
https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/ActorSystem.cs#L96

**Comment by Aaronontheweb** [comment]
@rogeralsing here's what `ConfigurationFactory.Load()` currently does:

```csharp
 var section = new AkkaConfigurationSection();
 Config config = section.AkkaConfig;

return config;
```

https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Configuration/ConfigurationFactory.cs#L38

This returns a blank `Config`, not the `Config` stored in App.Config or Web.config.

Needs to be changed to using the `ConfigurationManager` to load from App.config.

**Comment by rogeralsing** [comment]
Ohhh. that is a bug in that case.

**Comment by Aaronontheweb** [comment]
I'm having Bootcamp attendees use this in Unit 2 - would love to have a hotfix for this for them in the near future :p

**Comment by ejohn54** [comment]
This is broken in the latest release of Akka.Net 1.4.1.  Please reopen this issue.   It is no longer automatically loading the akka section in the app.config file.  Reverting back to 1.3.18 works fine.

**Comment by Aaronontheweb** [comment]
Open a new issue.

**Comment by Aaronontheweb** [comment]
I took care of it - #4330
