### ISSUE TITLE
Akka.Cluster.Sharding: automatically handle `ShardingEnvelope` and `StartEntity` without forcing user to define handlers

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#6717]
**Is your feature request related to a problem? Please describe.**

We have two built-in message types inside Akka.Cluster.Sharding that are designed to be routed automatically to entity actors:

**`ShardEnvelope`** - used to wrap normal messages with `EntityId` data so they can be routed correctly to the appropriate entity actor.

https://github.com/akkadotnet/akka.net/blob/24dec7fcae02933c2e0e430b9d0737457a9aff30/src/contrib/cluster/Akka.Cluster.Sharding/ShardedDaemonProcess.cs#L76-L93

*This message is going to be used heavily in our reliable delivery system going forward*

**`ShardRegion.StartEntity`** - used to power `remember-entities=on` and [currently we tell users they have to support this in their message extractors](https://getakka.net/articles/clustering/cluster-sharding.html#remembering-entities).

https://github.com/akkadotnet/akka.net/blob/7533c92a3a36f0e0ddeb0c47c2e358dff0aacac5/src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs#L99-L141

**Describe the solution you'd like**

The `ShardRegion` should just handle both of these messages automatically, without requiring users to manually handle them inside their own message extractors. We know what these messages are for and we have all the data we need to route them, so why not?

**Additional context**

It is possible that there can be a performance impact to doing this, as we now have to filter the messages twice instead of once - but erroring on the side of having better DX here seems like a no-brainer.

**Comment by Aaronontheweb** [comment]
So this is a bit of a problem:

https://github.com/akkadotnet/akka.net/blob/b7ec44683af3d85b265798737d93e150b056918e/src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs#L1426-L1444

In order for this system to work properly, and we have to solve the same issue we ran into when implementing the `GetEntityLocation` query:

https://github.com/akkadotnet/akka.net/pull/6101#discussion_r973395050

> One thing that is awkward about this query is that the `ShardExtractor` has to support the `ShardRegion.StartEntity` type in order for this to work - the reason being is that even though we already know what the entity id is, the extractors that resolve the `ShardId` are looking for an _input message_ to generate the `ShardId`, not the `EntityId`. Therefore I have to smuggle the `EnttityId` back through a `ShardRegion.StartEntity` message. That makes this a bit hacky but it's the best compromise I could make.

Really, the `ExtractShardId` and `ExtractEntityId` should have been designed to be monadic:

```csharp
public delegate Option<(EntityId, Msg)> ExtractEntityId(Msg message);

 public delegate ShardId ExtractShardId(EntityId entityId);
```

The benefits of doing it that way:

1. Can generically route messages and queries that aren't explicitly defined by the user's custom method;
2. More performant - can operate off of the `EntityId` directly without needing to extract it from the message for a second time (reduces per-message routing costs); and
3. Better separation of concerns TBH - extracting the `EntityId` from the message is the user's job. Extracting the `ShardId` from the `EntityId` is mostly handled by Akka.NET infrastructure anyway (although it can and should still be customizable.)

But since they're not, that leave us in a pickle. We can either:

1. Add yet another set of overloads to the sharding creation methods to use "properly designed" methods that separate concerns more cleanly - obsolete the older methods;
2. Break the APIs in v1.6 and replace them;
3. Do a combination of both; or
4. Do nothing.

We should make a decision, but my guess is that the size and scope of this decision puts things somewhat out of reach for now.

**Comment by ismaelhamed** [comment]
> ShardRegion.StartEntity - used to power remember-entities=on and [currently we tell users they have to support this in their message extractors](https://getakka.net/articles/clustering/cluster-sharding.html#remembering-entities).

Wow! Since when do we need to handle `StartEntity` in the `EntityId()` method? AFAIK, that's only a concern when extracting the `ShardId`.

> Really, the ExtractShardId and ExtractEntityId should have been designed to be monadic:

IMO, any improvements to the internals of the project that deviate from how the JVM works, it'd be wiser to bring them up with the original Team/Community so that they can also benefit from them.

**Comment by Aaronontheweb** [comment]
@ismaelhamed it's always been that way - we do handle it automatically here for a specific type of query:

https://github.com/akkadotnet/akka.net/blob/4f27bac819bba8e78b89ad0e59913114a84bbee3/src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs#L951-L959

Technically it's true - the message only needs to be handled by the `ShardExtractor`, but the routing system doesn't do anything special for it - typically it passes the input into the `ExtractEntityId` method and then passes the extracted EntityId back into the ShardId. My proposal in this case is to automatically handle these messages but not needing to pass the message content itself in as input to the `ShardId` method anymore.

> IMO, any improvements to the internals of the project that deviate from how the JVM works, it'd be wiser to bring them up with the original Team/Community so that they can also benefit from them.

So looking at how Akka 2.6.19 does things:

https://github.com/akka/akka/blob/3843e0f34d8a5c4e2e6a9b9112839fd483c45907/akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala#L52-L62

```scala
@InternalApi private[akka] class ExtractorAdapter[E, M](delegate: ShardingMessageExtractor[E, M])
    extends ShardingMessageExtractor[Any, M] {
  override def entityId(message: Any): String = {
    message match {
      case ShardingEnvelope(entityId, _) => entityId null
      case ClassicStartEntity(entityId)  => entityId
      case msg                           => delegate.entityId(msg.asInstanceOf[E])
    }
  }

  override def shardId(entityId: String): String = delegate.shardId(entityId)
```

They also do what I'm proposing here - and they redesigned their extractors to work as I described above: only the `entityId` is needed as input.

**Comment by ismaelhamed** [comment]
The `ExtractorAdapter` seems like a good compromise (no need to touch how things currently work in Akka Classic, for better or worse). And we've already brought Akka Typed structures in the past (i.e., the `ShardingEnvelope` wasn't a thing until we ported the `ShardedDaemonProcess`)

**Comment by Aaronontheweb** [comment]
> 

In order for that adapter structure to work, we have to deprecate the old `ShardExtractor` API and make it work off of an `EntityId` only - which I'm all for.

**Comment by Aaronontheweb** [comment]
On #6863 I've been able to implement the basic structures needed to support this without any breaking changes - and it looks like there is automatic handling for `StartEntity` in two different places (both the base `HashCodeMessageExtractor` and inside the `ShardRegion` itself.) Going to clean that up next.
