### ISSUE TITLE
Naming Of Actor System

### ISSUE THREAD

**Issue by ashutoshraina** [akkadotnet/akka.net#672]
Trying to create an ActorSystem like this will throw 
```
var actorSystem = ActorSystem.Create("My System");
```

Currently in ActorSystemImpl the following bits ensure that the code will throw an exception.

```
if(!Regex.Match(name, "^[a-zA-Z0-9][a-zA-Z0-9-]*$").Success)
                throw new ArgumentException(
                    "invalid ActorSystem name [" + name +
                    "], must contain only word characters (i.e. [a-zA-Z0-9] plus non-leading '-')");
```

Shouldn't this information be also in the summary documentation of ActorSystem ?

**Comment by Aaronontheweb** [comment]
Yes, we should add an XML-DOC comment for this. ActorSystem names have to be URL-friendly.
