### ISSUE TITLE
getakka.net documentation is broken

### ISSUE THREAD

**Issue by xnoreq** [akkadotnet/akka.net#6758]
This is what it looks like in my browser (Firefox 114):
![image](https://github.com/akkadotnet/akka.net/assets/4028859/2f0747a7-a251-443c-9b57-ea1c98185282)

Console shows multiple errors:
- downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: https://getakka.net/styles/glyphicons-halflings-regular-W4DYDFZM.woff2 
- downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:400 stretch:100 src index:2): status=2147746065 source: https://getakka.net/styles/glyphicons-halflings-regular-JOUF32XT.woff 
- non-wellformed XML error for address "https://getakka.net/articles/deployment/console.html"

**Comment by Aaronontheweb** [comment]
Yeah this was broken due a DocFx upgrade.

We've fixed some of the homepage issues as of this morning here: https://github.com/akkadotnet/akka.net/pull/6756

We're getting the code samples fixed today @Arkatufus
