### ISSUE TITLE
Wiki: Contributing page missing link to Developer Guidelines

### ISSUE THREAD

**Issue by SeanKilleen** [akkadotnet/akka.net#683]
Hi all,

Noticed this on the wiki when reading up on the [Contributing to akka.net](http://getakka.net/wiki/Contributing%20to%20Akka.NET) page:

![image](https://cloud.githubusercontent.com/assets/2148318/6412798/7dd6f43e-be56-11e4-8512-52c7d8b4de1b.png)

**Comment by SeanKilleen** [comment]
Apologies for the large screenshot.

**Comment by rogeralsing** [comment]
This has been corrected, closing
