### ISSUE TITLE
Delay in message processing

### ISSUE THREAD

**Issue by mnoroozi1990** [akkadotnet/akka.net#6842]
Hello everybody.
I have a scenario that an actor must send a PUT restApi request to an external service.
There is a restriction in the destination service that serves my request, **Interval between requests must be atleast 500 ms**.

for the first solution I used a Thread.Sleep for the delay between my requests, but that made an inconsistency in actor's behavior. I read about this inconsistency that is related to dispatcher behavior.
My question is,
Is there a way to have a delay in an actor message handling?

Thanks in advance.

**Comment by Aaronontheweb** [comment]
Akka.Streams with throttling is what you want for this type of thing - it's very robust at working with rates.

Here's a relevant sample I made demonstrating how to rate-limit work to 10/s https://replit.com/@Aaronontheweb/AkkaStreamsThrottling?v=1

You can change that to 2/s fairly easily.
