### ISSUE TITLE
WatchWith PoisonPill.Instance, PoisonPill is not stopping actor

### ISSUE THREAD

**Issue by hcavazin** [akkadotnet/akka.net#6870]
**Version Information**
1.5.7

In the example below the PoisonPill is being received as a normal message by the Actor.

private class WatchChildWithPoisonPillActor : ReceiveActor
{
        public WatchChildWithPoisonPillActor()
        {
            var child = Context.MyActorOf(() => new GenericActor());
            Context.WatchWith(child, PoisonPill.Instance);
            Context.Stop(child);
        }
}

**Expected behavior**
Stop actor.

**Actual behavior**
Message received by the actor as an ordinary message.

**Environment**
Windows, .NET 6

**Comment by Aaronontheweb** [comment]
ah yeah, I don't think this will work due to the messaging pathways this message travels in (it goes through the `/system` message handling) - so what you want here is a suicide pact between the actors, right?

**Comment by Aaronontheweb** [comment]
@hcavazin did you see my previous reply?

**Comment by Aaronontheweb** [comment]
Going to mark this as closed for now - feel free to reply back any time.

**Comment by hcavazin** [comment]
Hello, sorry for the delay in my response.
Exactly, I expected an Akka.Actor.DeathPactException.

**Comment by Aaronontheweb** [comment]
> Exactly, I expected an Akka.Actor.DeathPactException.

Use the regular `Contexrt.Watch` and then don't handle the `Terminated` message in order to trigger one of those.

**Comment by hcavazin** [comment]
Thanks!
