### ISSUE TITLE
Running a NUnit test results in MissingMethodException from Akka.TestKit

### ISSUE THREAD

**Issue by akaranta** [akkadotnet/akka.net#6907]
**Version Information**

Version of Akka.NET? 

1.5.12

Which Akka.NET Modules? 

Akka.TestKit

**Describe the bug**

After updating Akka.net 1.3.18 -> 1.5.12 when trying to run NUnit test we get 

1) Error : DaCluster.Tests.DamageCalculatorTest.TestException
System.MissingMethodException : Method not found: 'Akka.Actor.IActorRef Akka.Actor.IInternalActorRef.GetChild(System.Collections.Generic.IEnumerable`1<System.String>)'.
   at Akka.TestKit.TestKitBase.InitializeTest(ActorSystem system, Config config, String actorSystemName, String testActorName)
   at Akka.TestKit.TestKitBase..ctor(ITestKitAssertions assertions, ActorSystem system, String testActorName)
   at Akka.TestKit.NUnit3.TestKit..ctor(ActorSystem system) in C:\work\Akka.TestKit.NUnit\src\Akka.TestKit.NUnit3\TestKit.cs:line 35
   at DaCluster.Tests.DamageCalculatorTest..ctor()

**To Reproduce**

I don't have a minimal reproduction case as of now. If the problem is not self evident, I can try to create one.

**Expected behavior**

Unit test can be run without exceptions from Akka.

**Actual behavior**
Exception thrown from 

**Environment**

Running on .NET 4.7.2 on Windows desktop

**Comment by Aaronontheweb** [comment]
Could you show us what the CTOR of your test looks like? We might have missed something when we modernized the NUnit testkit earlier this year.

**Comment by akaranta** [comment]
There is no explicit constructor, i.e. the compiler generates the default constructor that takes no parameters. And calls the base class constructor.

Here's what the test class in question looks like. I stripped out the contents of the test methods. As the test fails before they get called I would think that they are not significant here.

`
using Akka.TestKit.NUnit3;
...
    [TestFixture]
    public class DamageCalculatorTest : TestKit {

        [Test]
        public void TestMessage() {
            // test code ...
        }

        [Test]
        public void TestException() {
            // test code ...
        }
  
    }
`

**Comment by Aaronontheweb** [comment]
thanks @akaranta - we will look into this!

**Comment by Arkatufus** [comment]
@akaranta Are you using Akka.TestKit.NUnit and which version are you using

**Comment by akaranta** [comment]
Yes, we use Akka.TestKit.Nunit3 1.3.8, which is the latest version.

The other Akka packages are 1.5.12, being
Akka 
Akka.Cluster
Akka.Cluster.Tools
Akka.Persistence
Akka.Remote

**Comment by Aaronontheweb** [comment]
@akaranta ah, the issue here is that we need to deprecate the Akka.TestKit.NUnit3 package - the canonical package is Akka.TestKit.NUnit now and that targets Akka.NET v1.5 and NUnit3. Please try switching to that package. I'll login to nuget.org today and deprecate the NUnit3 package with a notice.

**Comment by akaranta** [comment]
Thanks @Aaronontheweb ! I confirm that removing Akka.TestKit.NUnit3 and adding (the latest version of) Akka.TestKit.NUnit resolved the issue.

**Comment by Aaronontheweb** [comment]
Thank you! I added the deprecation warning here as well: https://www.nuget.org/packages/Akka.TestKit.NUnit3/
