### ISSUE TITLE
akka .net toStringWithAddress null exception

### ISSUE THREAD

**Issue by Rafaelcraftero** [akkadotnet/akka.net#6923]
**Version Information**
Akka 1.4.51
Which Akka.NET Modules?
Akka 1.4.51
**Describe the bug**
This bug always appear when I start whatever the project that contains Akka

**To Reproduce**
1. Go to a project that uses akka
2. Click on Build and run on debug mode
3. See error

**Expected behavior**
This error does not appear when I run the project

**Actual behavior**
If you run on debug mode, it will stop the solution and will send you to the toStringWithAddress method in ActorPath.cs. If you click on continue everything works correctly but everytime a project is loaded it happen again.

**Screenshots**
![image](https://github.com/akkadotnet/akka.net/assets/15800095/568e2784-7d86-49de-98fc-76d173a8ea68)

**Environment**
Are you running on Linux? Windows? Docker? Which version of .NET?
Windows, last .NET version
**Additional context**

**Comment by Aaronontheweb** [comment]
This is a handled exception thrown at startup by the logging system - it's nothing to worry about. We try to grab the address if it's available, but if the socket runs long then it's not.

**Comment by Aaronontheweb** [comment]
I would recommend ignoring handled exceptions when debugging: https://stackoverflow.com/questions/11183099/how-to-make-visual-studio-break-only-on-unhandled-exceptions
