### ISSUE TITLE
Mono experience

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#694]
We do have a problem in the fact that the core team does have too little Mono experience.
I think we should try to improve on this topic.

So first question to our Mono friends;

What is the simplest way to code and debug stuff in Mono land?
I have Sharpdevelop installed in Ubuntu,  but that can not open vs2012 solutions.
How do you deal with this?

**Comment by rogeralsing** [comment]
How do I build Akka.NET on mono?

`bash build.sh Build`
Throws and says "Project in imports is empty" on the fsproj files.

**Comment by ZigMeowNyan** [comment]
While SharpDevelop is nice, I'm pretty sure the "official" IDE for mono is [MonoDevelop](http://www.monodevelop.com). It's cross-platform (Win/Mac/Linux), although the Windows and Mac versions are distributed as "Xamarin Studio", which is essentially a branded MonoDevelop with some Xamarin plugins irrelevant to Akka.  I guess you could also build vanilla MonoDevelop from source, but it makes more sense to just use the same packaging as everyone else.

It might be worthwhile to attempt to build Akka in MonoDevelop/XamarinStudio on windows first, and then look into making sure you've got all the package dependencies in your Linux distro afterwards. On that note, I downloaded the dev branch of Akka.net, opened it up in Xamarin Studio 5.1 (current version is 5.7) on Windows and hit Rebuild in the **Debug** configuration. Everything seemed to work except for the following three projects:

* Akka.TestKit
* Akka.Remote.TestKit
* Akka.Cluster.Tests

They all failed with the same error - "**This project type is not supported by Xamarin Studio.**" Here's a screenshot for you:

![image](https://cloud.githubusercontent.com/assets/3219710/6769674/c75fdb02-d062-11e4-87b3-35310c671b2e.png)


Seems like the built-in Unit Test project type isn't handled by Xamarin/MonoDevelop. But at least the core system builds. Seems like you could probably open this on Linux with the MonoDevelop IDE with little effort and attempt a build.

Also of note is the recent OSS-ing of MSBuild, which is might make an impact on the cross-platform toolchains. But it seems like Mono's XBuild currently handles most of what's needed.

**Comment by rogeralsing** [comment]
![remoting](https://cloud.githubusercontent.com/assets/647031/6983520/3c678380-da1f-11e4-8280-d05017a88fbe.png)

@Aaronontheweb any idea whats causing that?

**Comment by Aaronontheweb** [comment]
I saw this on my dedicated Ubuntu machine too. Just realized that I introduced a bug in the `RelativeActorPath` class when I was trying to work around the Mono URI issues - so it could be that.

The other cause of this issue was a simple port binding problem - saw some issues where binding to port 0 for outbound connections intermittently failed. I'm not familiar enough with POSIX sockets to know why just yet.

Your inbound server is probably working fine - it's been the outbound one that's been acting suspect.

**Comment by Aaronontheweb** [comment]
This should work fine now - just ran all of the Akka.Cluster and Akka.Remote samples locally on Ubuntu 14.04 with the latest version of Mono.

**Comment by rogeralsing** [comment]
The project still references the old version of Helios.
And even with the updated version, it does not succeed to listen to the server Port under Rasbian.

**Comment by Aaronontheweb** [comment]
@rogeralsing thanks :)

Sounds like RaspberryPI doesn't allow inbound connections by default - good to know!

**Comment by rogeralsing** [comment]
The server now runs fine on the RPI, turned out that it was the RPI Firewall `iptables` causing it, stopping this service solved the problem.

**Comment by rogeralsing** [comment]
As far as I can tell, we play nicely with Mono.
If the Raspberry PI issues are real issues, they seems to be related to the Mono threadpool, not Akka.NET itself.

Should we consider this one done?

**Comment by stefansedich** [comment]
Mmm have we tried with mono 4 on the pi? I was hoping to do more over my
break looking into mono  but my internet access was horrible at best.

I have ran with remoting in production under mono so far without a hitch so
I am happy with that part.

Cheers

**Comment by rogeralsing** [comment]
Any pointers to how to get mono 4 on the rpi?

**Comment by stefansedich** [comment]
No sorry have not done it myself yet.

**Comment by ZigMeowNyan** [comment]
The current mono release is still [3.12.1](http://www.mono-project.com/download/) from March 7th. They've [drafted the release notes for 4.0](http://www.mono-project.com/docs/about-mono/releases/4.0.0/), but it hasn't actually been released yet despite the link being tossed around social media.

If you want to try version 4 (which has apparently merged in a lot of code from .NET core), you'll probably have to [build it from source](http://www.mono-project.com/docs/compiling-mono/linux/), either by compiling locally on the Pi or through a cross-compiler. Not sure which branch is relevant, though the above draft notes mention [commit 519ddb9895af5639de5ba0361af54a8d585c4070](https://github.com/mono/mono/commit/519ddb9895af5639de5ba0361af54a8d585c4070). That commit is showing on the master branch, so maybe building from git would be enough.
