### ISSUE TITLE
VS 2022 debugging two windows using SynchronizedDispatcher actors throws access violation

### ISSUE THREAD

**Issue by minesworld** [akkadotnet/akka.net#6965]
**Version Information**
Akka.NET 1.5.13 

**Describe the bug**
Given: WinUI3 window (AppSDK) having a TextBox bound to the window instance displaying a string which gets updated by an Actor dispatched synchronized. This `CounterDisplayActor` gets its Ticks from another non synchronized Actor  `TimeSourceActor`. The UI bindings are done via `CommunityToolkit.MVVM` `OberservableObject` and `ObservableProperty`.

**Debugging** the app having a **single** window works. But Visual Studio 2022 will throw an `access violation` when trying to debug it having `App.xml.cs` opening **two** windows.

Starting the app with two windows **without** debugging works fine...

**To Reproduce**
1. download https://github.com/minesworld/AkkaSychronizedDispatcherBug
2. build the project
3. start with debugging
4. should throw an error
5. start without debugging
6. should work open two windows showing a text box counting up
7. disable the second `new MainWindow().Activate();` in `App.xaml.cs` `OnLaunched` and try again with debugging, should work without an access violation

**Expected behavior**
debugging should always work

**Environment**
Windows 11 22621.2428
AppSDK 1.4.231008000
VisualStudio 2022 17.7.5

**Comment by minesworld** [comment]
Question: is `Akka.NET` responsible for this? 

Filed that bug because it might be a side effect of an other underlying issue...

PS: sorry if my repo name is discriminating

Edited: did another project calling the `TextBox` `Text` setter directly, no difference. Even commenting out that call does make no difference. So it is either Akka.net, VisualStudio or AppSDK ...

**Comment by minesworld** [comment]
Update: I investigates a little bit further - it seems the VS 2022 behaviour has nothing do to with creating synchronized dispatchers. Same `Access violation` is thrown when creating "normal" actors which will update via the windows `DispatcherQueue `. 

In all cases the actors are created within the create method of the windows after `this.InitializeComponent` .  Next thing I will try is having the Actors created from a running Actor....

**Comment by to11mtm** [comment]
Part of me is thinking that you should try one of the virtual hooks on `Window`. My WPF is -very- rusty, but I would wonder whether `BeginInit` or `OnInitialized` would be better choices...

The big question is where the Window's `SynchorinzationContext` is active; i.e. it may not be active in the constructor, but it might be in one of those methods, or another method I'm not aware of... My apologies again for not knowing WPF better 😅.

**Comment by minesworld** [comment]
Test creating the actor via an running actor - as all other projects tried, runs fine without debugging, fails on debugging with `Access violation` ... Hmm. Could be a VS 2022 debugger bug?? Strange...

**Comment by to11mtm** [comment]
Maybe add this to where the actor is getting created?

```
if (SynchronizationContext.Current == null)
{
  Debugger.Break();
}
```

**Comment by minesworld** [comment]
```
if (SynchronizationContext.Current == null)
{
  Debugger.Break();
}
```

does not break. I also added some `Debug.WriteLine` before/after creating the Actors. The Actors get created on **both windows**.

I would have been surpised if there would be no `SynchronizationContext` but a `DispatcherQueue `from within the `Window `creation method...

The strange thing is, the `'Access violation` **only happens on debugging**...

The VS 2022 solution now contains different projects all failing on debug.  

Have added a project having the `TextBox` in its own `Page` . The `Actor` updating the bound value is created on the `Loaded` event by messaging another running `Actor`.  Makes no difference, runs fine without debugging but fails on debugging.

**Comment by minesworld** [comment]
Seems to be unrelated to Akka.net . Happens when two Windows get opened without any Akka.net code in place. 

Sorry

**Comment by minesworld** [comment]
Filed the bug as https://github.com/microsoft/microsoft-ui-xaml/issues/9008
