### ISSUE TITLE
ActorPath.ToStringWithAddress is given null address parameter

### ISSUE THREAD

**Issue by minesworld** [akkadotnet/akka.net#6966]
**Version Information**
1.5.13
Remote 1.5.13

**Describe the bug**
Configuring a simple remote server as in the ChatServer example crashes the program.

Same issue as described on StackOverflow https://stackoverflow.com/questions/69983136/akka-net-net-framework-akka-remote-config-always-errors-on-start-then-works

**To Reproduce**
1. Download Akka.net github repo
2. open solution in VS 2022 on Windows 11 22H2
3. start the **ChatServer** example

**Expected behavior**
should just run 

**Actual behavior**
throws `System.NullReferenceException`

**Screenshots**
![image](https://github.com/akkadotnet/akka.net/assets/10605116/70455165-a105-429c-bb4a-c9a580536878)

**Additional context**
Adding a check in `ActorPath.ToStringWithAddress` if the given address is null works (e.g. the server listens), but I have no clue about the side effects and why a `null` `address` is given

```
        private string ToStringWithAddress(Address address, bool includeUid)
        {
            if (address == null ||  IgnoreActorRef.IsIgnoreRefPath(this))
            {
                // we never change address for IgnoreActorRef
                return ToString();
            }

            long? uid = null;
            if (includeUid && _uid != ActorCell.UndefinedUid)
                uid = _uid;

            if (_address.Host != null && _address.Port.HasValue)
                return Join(_address.ToString().AsSpan(), uid);

            return Join(address.ToString().AsSpan(), uid);
        }
```

**Comment by Arkatufus** [comment]
@minesworld make sure that you have visual studio to ignore handled exceptions.

Not a bug.

**Comment by ilmax** [comment]
@Arkatufus sorry to ping you on a closed issue, but I am a bit annoyed by this exception and was checking if there's something I can do to avoid it. It happens to me 100% of the times when starting the application.

Can you point me out to some comments/explain me why this is not a bug?

The exception I'm hitting is from [here](https://github.com/akkadotnet/akka.net/blob/0cb28818a7225f4e0f12a1769486e1cdd22ddb5f/src/core/Akka/Event/Logging.cs#L110) where `system.AsInstanceOf<ExtendedActorSystem>().Provider.DefaultAddress` always return null.

What are the issue changing the code to something akin to the following:

```csharp
public static string FromActorRef(IActorRef a, ActorSystem system)
{
    try
    {
        var defaultAddress = system.AsInstanceOf<ExtendedActorSystem>().Provider.DefaultAddress;
        if (defaultAddress is null)
        {
            return a.Path.ToString();
        }
        return a.Path.ToStringWithAddress(defaultAddress);
    }
    catch // can fail if the ActorSystem (remoting) is not completely started yet
    {
        return a.Path.ToString();
    }
}
```

**Comment by Arkatufus** [comment]
@ilmax You can read the original attempt to fix this and the reason why we didn't here: https://github.com/akkadotnet/akka.net/pull/5454#issuecomment-998327201

Your fix might be good, we'll look into it.
