### ISSUE TITLE
Implement serialization constructor to all Akka exceptions

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#701]
Sometimes a default JSON.NET serializer throws an exception while trying to serialize messages having another exception as a payload. Therefore I think we should implement `Exception(SerializationInfo info, StreamingContext context)` for `AkkaException` and all actor system exceptions.

**Comment by Aaronontheweb** [comment]
Good idea

**Comment by HCanber** [comment]
I've seen a few of these constructors in our code base that are `public`. No need for that, `protected` is enough.

**Comment by alex-bogomaz** [comment]
Should this constructor be added to all exceptions derived from AkkaException, including exceptions in "Akka.Persistence" and "Akka.Remote" ?

**Comment by Aaronontheweb** [comment]
@alex-bogomaz yes, those should be lumped in under this issue as well

**Comment by Aaronontheweb** [comment]
Closed per #713
