### ISSUE TITLE
Severe Bug: Group routers are unable to watch routees declared through configuration

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#703]
This is a major limitation with `Group` routers that I came across today.

From `RoutedActorCell`: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Routing/RoutedActorCell.cs#L94
```csharp
private void Watch(Routee routee)
{
    var actorRef = routee as ActorRefRoutee;
    if (actorRef != null) base.Watch(actorRef.Actor);
}
```

If you use any constructor other than this one on any `Group` router https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Routing/RouterConfig.cs#L97
```csharp
protected Group(IEnumerable<ActorRef> routees)
```

then all of your routees will be `ActorSelectionRoutee` instances and `DeathWatch` only works for `ActorRef`, therefore your group router will not be notified when any of its recipients die and it will not remove those routees from its state.

This is a severe bug - it means that any Group router declared through configuration (or programmatically, using the constructors that take paths instead of `ActorRef`) doesn't handle routee terminations correctly.

## Possible Solutions
A few ways to solve this:

1. Have `Group` routers automatically try to resolve their `ActorSelectionRoutee`s to `ActorRef`s on startup. Messy, but it can work.
2. Modify `DeathWatch` to work with `ICanTell` instead of `ActorRef`.
3. Create an `ActorRef` instance that can wrap an `ActorSelection` and solve the problem that way.

Thoughts?

**Comment by rogeralsing** [comment]
Group routers in JVM Akka only supports actorselection.
The ActorRef overload was added by us for convenience.
I don't think this is a bug, we need to check how JVM Akka handles this

**Comment by Aaronontheweb** [comment]
Looking at the JVM implementation, it looks like their `RoutedActorCell` is designed the same way.

However, hear me out - let's do a smell test on this scenario an Akka.Cluster user reported to me this week.

If you're routing to two actors and one of them dies, 50% of your messages start getting delivered to dead letters instead of being routed. This is exactly what happens with all `ClusterGroupRouter`s when a node goes down.

Does this seem like the behavior someone would expect?

**Comment by Aaronontheweb** [comment]
(for clustering, I can solve this problem via the cluster state - but this is still a problem for everyday Akka core users with a group router)

**Comment by Aaronontheweb** [comment]
Actually... bleh... even though I really don't like it.... What happens if a user passes in an invalid actor path to a `Group` router? How are we supposed to death watch that, since it can NEVER resolve to an actor ref?

I guess that's the point - `Group` routers are like having unsafe sex. If you want to be safe, always bring your `Pool` router with you.

**Comment by rogeralsing** [comment]
Ask in the Akka jvm gitter/google group, Id be surprised if that is how it behaves on JVM.
They probably have a solution for it, and we should align to that solution IMO.

**Comment by Aaronontheweb** [comment]
Good idea

**Comment by rogeralsing** [comment]
They actually changed from having ActorRef's to only paths somewhere around march last year or so.
There has to be some theoretical reason behind it.

**Comment by rogeralsing** [comment]
I've been thinking about this now.
Since an actor selection can be an entire group of actors, due to wildcard matching.
I dont see how deathwatch could ever be applied correctly here.

**Comment by Aaronontheweb** [comment]
Yeah, I suspect you're right. However, that makes me think that `Group` routers should be considered dangerous. Only use it in scenarios where the routees don't get terminated unless the router / entire process is being terminated too.

**Comment by Aaronontheweb** [comment]
Official answer from the TypeSafe mailing list:

>Hi Aaron,
>
> By design a Group Router doesn't watch the routees. Since they are actor paths they could map to a wildcard, or a failed actor can be replaced by a new actor at the same path and start receiving messages from the router.

Not a bug, this is by design. We can close it out.
