### ISSUE TITLE
Issues with DI Support

### ISSUE THREAD

**Issue by stefansedich** [akkadotnet/akka.net#706]
Looking over the DI support I spot what I see as a fairly big issue (for disposable components referenced within an actor), we do not handle releasing any components, for example in Autofac support we resolve on a root IContainer but we do not handle lifetime scopes or anything like that, if we had disposable services injected into actors these would not be disposed when the actor is done with.

Ideally the actors life cycle should be wrapped by an ILifetimeScope which is disposed of when the actor is, that would ensure we clean up things properly.

Thoughts?

Thanks
Stefan

**Comment by Horusiath** [comment]
I found it hard to achieve by any external plugin/framework. Actors have their own life cycle, which does not cover with what you may usually expect - i.e. don't expect that actor will be GCed simply when you stop sending messages to it.

Right now we can deal with it in several ways:

1. Let your actor implement `IDisposable` interface and dispose it's resources there.
2. Override `PostStop` method and dispose your objects at the end.
3. Create your own pipeline plugin and use it's `BeforeIncarnated` method to release resources.

Option no. 3 gives some chances, that it can be used at DI plugin level, but I don't know internals of specific DIs enough to be sure for that.

**Comment by stefansedich** [comment]
I think at the moment if we have some guidance around using the various plugins, i.e. if using autofac ensure you use ExternallyOwned or use an Owned<T> and handle disposing the dependencies on your own inside your actor etc...

I have not really looked too deeply into how IOC is implemented to see how it could actually be resolved properly to use lifetime scopes etc but I think some guidance around these things could be a good start, thoughts?


Thanks
Stefan

**Comment by Aaronontheweb** [comment]
Senor @Horusiath did a better job than I could explaining how to tackle this issue. 

> I think at the moment if we have some guidance around using the various plugins, i.e. if using autofac ensure you use ExternallyOwned or use an Owned and handle disposing the dependencies on your own inside your actor etc...

I think you're right on @stefansedich - that does need to be explained better. I've never used Autofac, but would you mind sending a PR to amend this page in our docs explaining just that? 

https://github.com/akkadotnet/akka.net/blob/dev/documentation/wiki/Dependency%20injection.md

Maybe also include that in the XML-DOC comments for the module too. Does that sound like a good start?

**Comment by Aaronontheweb** [comment]
So @jcwrequests wrote a really detailed proposal for how to solve this problem here: http://www.message-flow.com/2015/03/ioc-contrib-design-flaw.html

I have a couple of questions for him here:

1. For remote-deployed actors and actors who aren't deployed with any sort of DI support, what's the default release behavior? No-op?
2. The `Release` method needs to be tied to the `IndirectActorProducer` so it has access to the original DI container - is that correct? Just want to make sure I understand.

CC @HCanber @rogeralsing @nvivo @rodrigovidal - what do you guys think of @jcwrequests's idea? Seems like a reasonable way to solve this problem to me (automate releasing of injected objects)

**Comment by Aaronontheweb** [comment]
Whoops, meant to include @Horusiath too

**Comment by rogeralsing** [comment]
One thing that I think we might have missed in this whole discussion is that `IndirectActorProducer` is a part of `Props` and `Props` can be shared.
e.g. for routees in a pool.

So we can not rely on `IndirectActorPruducer` is unique for each actor instance.

**Comment by jcwrequests** [comment]
@rogerasling so this call needs to be done at the system level back to the container. So instead of relying on Props to call IndirectActorProducer I would have to have some sort of lambda fed to the system that is bound to the container. In theory does that sound like it would resolve the issue you have described? @aaronontheweb @hcanber @nvivo @Horusiath @rodrigovidal Sorry if I missed anybody sending this from a phone which is not the best UX. 😊

**Comment by rogeralsing** [comment]
The suggested solution you have with the `Release` method should work if it like you have suggested has an `ActorBase` argument.
But implementors of the producer must understand that the producer can be shared for many actors, so it doesnt somehow assumes uniqueness.

**Comment by jcwrequests** [comment]
@rogeralsing Okay I understand. This was actually mentioned on the JVM side as well when I did my initial research. This may be something that can be constraint or verified during system startup to ensure the system does not get into a compromised state. Now with the help of @stefansedich we should be able to accomplish this with AutoFac and I know it can be done with Castle Windsor. So then you think it's okay that I move forward with coding?

**Comment by rogeralsing** [comment]
yepp :-)

**Comment by jcwrequests** [comment]
@rogeralsing @stefansedich @Horusiath @Aaronontheweb @stefanalfbo I just wanted to add that I have started the preliminary work and all that is left is @stefansedich AutoFac re-implementation and addition of some tests before I put in a PR. If you want to see what I have so far check out my repo [repo](https://github.com/jcwrequests/akka.net/commit/d706fefb98a20ec26037d7aba1dcf1a2472986e0)

**Comment by jcwrequests** [comment]
@Aaronontheweb @rogeralsing @stefansedich @Horusiath @stefanalfbo I have put in a PR to patch this issue. I have worked with @stefansedich to get the AutoFac implementation to follow best practices. Also I have created three new sample projects for DI to demonstrate using the three containers.
