### ISSUE TITLE
[TestKit] SupervisorStrategy for TestActor is unused

### ISSUE THREAD

**Issue by roee88** [akkadotnet/akka.net#7062]
**Version Information**

v1.5

**Describe the bug**

https://github.com/akkadotnet/akka.net/pull/4148 added `public IActorRef ChildActorOf(Props props, string name, SupervisorStrategy supervisorStrategy)` and similar methods to TestKitBase. However, the `supervisorStrategy` does not take effect.

It looks like `InternalTestActor` doesn't override `SupervisorStrategy()` to actually use its private `_supervisorStrategy`. See https://github.com/akkadotnet/akka.net/blob/0782c7dc069618e20a3791aaab667076f487ad96/src/core/Akka.TestKit/Internal/InternalTestActor.cs#L24

**Comment by Aaronontheweb** [comment]
Thanks, we'll look into this
