### ISSUE TITLE
Scheduler should never allow a TimeSpan.Zero or equivalent value for its interval

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#709]
Creates an infinite loop and spams an actor's mailbox faster than it can process. Need to use a `Guard.Assert` statement to prevent this value from being captured.

This issue was directly responsible for an Akka.Cluster bug that took @smalldave and I a long time to track down.

**Comment by HCanber** [comment]
Do you mean `Scheduler.Schedule` and `Scheduler.ScheduleOnce`? In that case it will be handled by me in #468.

**Comment by Aaronontheweb** [comment]
@HCanber yessir, those methods are what I meant - doesn't matter so much for `ScheduleOnce` but it makes a huge difference for the interval for `Schedule`
