### ISSUE TITLE
Messages are irregularly lost.

### ISSUE THREAD

**Issue by kimbyungeun** [akkadotnet/akka.net#7137]
**I am always grateful for the support from the Akka.NET team.**

## Version Information
- Akka.NET 1.5.13.0
- Akka.Cluster 1.5.13.0
- Akka.Serialization.Hyperion
- .NET Framework 4.7 (Upgrading to .NET 7 is not possible.)
- Windows Server 2012

## Describe the bug
![image](https://github.com/akkadotnet/akka.net/assets/18045312/6eca3b8e-2f1b-4316-849f-b51abc86db33)

#### Error Description:
- Messages are lost at a very low and irregular frequency.
- No Dead Letters are detected on the sender's side.
- The loss of messages occurs sporadically, but the next message is received normally.
- We believe that the issue is more likely due to our misuse rather than a flaw in Akka.NET.

#### Question 1:
- There are no Dead Letters in the sending Actor.
- Is it possible that the message has reached the receiving Actor and exists in the Mailbox, but has not been processed?

#### Question 2:
- Could the problem have been caused by using excessively large buffer sizes?
  - Send buffer size: 200MB (send-buffer-size = 209715200b)
  - Receive buffer size: 200MB (receive-buffer-size = 209715200b)
  - Maximum frame size: 100MB (maximum-frame-size = 104857600b)

#### Question 3:
- I am attaching the configuration for review. Could you please check if there is any issue with the settings and provide advice?

```
akka 
{
	system.name = "cluster-system"

	service
	{
		name = "Inference.Window.Service"
		description = "Inference.Window.Service"
	}

	stdout-loglevel = DEBUG
	loglevel = DEBUG
	log-config-on-start = off
	loggers = ["Akka.Logger.NLog.NLogLogger, Akka.Logger.NLog"]

	actor
	{
		provider = cluster
		guardian-supervisor-strategy = "Inference.Window.Service.ActorService.UserSupervisorStrategy, Inference.Window.Service"
		
		serializers.hyperion = "Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion"
		serialization-bindings { "System.Object" = hyperion }
		
		debug
		{
			receive = off         # Default off
			autoreceive = off     # Default off
			lifecycle = on        # Default off
			event-stream = off    # Default off
			unhandled = on        # Default off
		}
	}

	remote
	{
		dot-netty.tcp 
		{
			public-hostname = 127.0.0.1
			port = 8941

			send-buffer-size    = 209715200b  # 200MB
			receive-buffer-size = 209715200b  # 200MB
			maximum-frame-size  = 104857600b  # 100MB
		}
		
		transport-failure-detector
		{
			heartbeat-interval = 5s                # Default = 4s
			acceptable-heartbeat-pause = 480s      # Default = 120s
		}
	}

	# cluster client 설정
	extensions = ["Akka.Cluster.Tools.Client.ClusterClientReceptionistExtensionProvider, Akka.Cluster.Tools"]

	cluster 
	{
		debug 
		{
			# log heartbeat events (very verbose, useful mostly when debugging heartbeating issues)
			verbose-heartbeat-logging = off

			# log gossip merge events (very verbose, useful when debugging convergence issues)
			verbose-receive-gossip-logging = off
		}	

		# Unreachable Node Downing Strategy
		# https://getakka.net/articles/clustering/split-brain-resolver.html
		downing-provider-class = "Akka.Cluster.SplitBrainResolver, Akka.Cluster"
		down-removal-margin = 20s
		
		split-brain-resolver.active-strategy = keep-majority
		split-brain-resolver.stable-after = 20s

		seed-nodes = 
		[
			"akka.tcp://cluster-system@127.0.0.1:4061"
		]

		roles = [inferencewindow]

		auto-down-unreachable-after = off
		gossip-interval = 5s  # how often should the node send out gossip information?
		gossip-time-to-live = 30s # discard incoming gossip messages if not handled within this duration

		use-dispatcher = cluster-dispatcher						
		run-coordinated-shutdown-when-down = on
		allow-weakly-up-members = on            # Default = off

		failure-detector                        # Cluster
		{
			threshold = 8.0                      # Default = 8.0
			min-std-deviation = 100ms           # Default = 100ms
			expected-response-after = 120s      # Default = 1s

			heartbeat-interval = 5s             # Default = 1s
			acceptable-heartbeat-pause = 480s   # Default = 3s
		}
	}
}

cluster-dispatcher 
{
	type = "Dispatcher"
	executor = "fork-join-executor"
	fork-join-executor 
	{
		parallelism-min = 10
		parallelism-max = 10
	}
}
```

**Comment by Aaronontheweb** [comment]
Are you sending any messages through a clustered router or distributed pub sub?

**Comment by kimbyungeun** [comment]
@Aaronontheweb Thank you for your response.

We're sending messages via the ClusterClient. 
There are two scenarios where we suspect messages might be getting lost, and both involve sending messages from outside the cluster using the ClusterClient.

* CollectActor : actor outside the cluster
* InferenceActor : clustered router actor
* CollectActor -> Tell(new ClusterClient()) -> InferenceActor

Below are the settings for the Cluster Client.

**cluster client** 
```
# cluster client 설정
extensions = ["Akka.Cluster.Tools.Client.ClusterClientReceptionistExtensionProvider, Akka.Cluster.Tools"]

cluster 
{ 
    ...
	
	client 
	{
		initial-contacts = 
		[
			"akka.tcp://mls-cluster-system@127.0.0.1:4061/system/receptionist"
		]

		heartbeat-interval = 5s
		acceptable-heartbeat-pause = 480s

		buffer-size = 10000
	}
	
    ...	
}
```

**cluster client singleton**
```
# cluster client 설정
extensions = ["Akka.Cluster.Tools.Client.ClusterClientReceptionistExtensionProvider, Akka.Cluster.Tools"]

cluster 
{
	...

	seed-nodes = 
	[
		"akka.tcp://mls-cluster-system@127.0.0.1:4061"
	]

	roles = [api]

	singleton
	{
		singleton-name = "singleton"
		role = "api"
		hand-over-retry-interval = 1s
		min-number-of-hand-over-retries = 10
	}
       ...
}
```

**Comment by kimbyungeun** [comment]
@Aaronontheweb Thanks again for your support and guidance!

We have decided to discontinue the use of ClueterClient, with some changes to be made to certain Cluster router actors and gRPC configurations. Consequently, we are closing the related issue.
