### ISSUE TITLE
Serialization bug: all int's get serialized into longs

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#715]
Noticed this when I was doing some work on Akka.Cluster and didn't really think it was a big deal until now.

Say I have the following constructor on an actor:

```csharp
public DownloadCoordinator(CrawlJob job, ActorRef commander, ActorRef downloadsTracker, int maxConcurrentDownloads)
{
 ....
}
```

Declared the constructor signature member `maxConcurrentDownloads` as int.

And let's say I want to remote deploy a copy of this actor with the following `Props`:

```csharp
Props.Create(() => new DownloadCoordinator(someJob, someActor, someotherActor, 50));
```

Harmless constant value of 50.

When this actor attempts to get deployed, the `ActivatorProducer` explodes into an angry inferno and crashes https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/Props.cs#L518

```csharp
public ActorBase Produce()
{
     return Activator.CreateInstance(_actorType, _args).AsInstanceOf<ActorBase>();
}
```

Throws a `MissingMethodException` - reason being? It's trying to pass 50 as a `long`, rather than an `int`, into the `DownloadCoordinator` constructor. Since there's no automatic cast available, the operation fails.

How should we go about fixing this?

**Comment by rogeralsing** [comment]
We can maybe surrogate ints/floats to carry a type manifest. But that would have a serious impact on message size.
Longterm solution would be to not use json for typed data. But I do not know of another serializer that would fit our needs.

**Comment by rogeralsing** [comment]
We should be on the lookout for a polymorphic serializer with surrogate support. That also dont require objects to be annotated or implement serialization interfaces.

...or we make one..

**Comment by rogeralsing** [comment]
I assume the main problem here is that the `Props` has a list of args that are typed as `object`.
So when deserializing, there is no way for json.net to know the intended numeric type.

A quick hack could be to create a generic type with a single value.
Eg `Arg<T> : Arg` with a typed property of type T.
Then replace the object array in props with an array of `Arg` 
Not pretty but would solve the problem, w/o affecting user api.

**Comment by Aaronontheweb** [comment]
@rogeralsing the issue also happens with sending remote messages too - i.e. if your actor is expecting a message of type INT to arrive from the network it'll never come. . Found that in one of the multi-node tests and worked around it by just expecting `long`. Same issue as `Props`.

I was able to work around the issue by just expecting  a `long` in this case too, but I think it's reasonable for the user to expect what they send to be reflected by what they receive.

One idea would be to use type hints, which is what the default `DataContractJsonSerializer` does - does anything like that exist for JSON.NET? And would that solve the problem?

**Comment by Aaronontheweb** [comment]
Does #699 resolves this @rogeralsing ?

**Comment by rogeralsing** [comment]
No, Ill handle that in a new PR, 
Got to experiment a bit first on what works.

**Comment by Aaronontheweb** [comment]
:+1:

**Comment by rogeralsing** [comment]
#725 fixes this
