### ISSUE TITLE
Using ReceivePersistentActor with IWithUnboundedStash causes NullReferenceException in Eventsourced.AroundPostStop

### ISSUE THREAD

**Issue by adeliab** [akkadotnet/akka.net#7184]
**Version Information**
Version of Akka.NET? 1.5.15 & 1.5.20
Which Akka.NET Modules? Akka.Persistence

**Describe the bug**
We have an actor which used to be a ReceiveActor with IWithUnboundedStash. This actor was running and deployed on Azure. 
We then changed this actor to be a ReceivePersistentActor, keeping the IWithUnboundedStash interface. 
We deployed this change to Azure and saw NullReferenceException happening:
```
System.NullReferenceException:
   at Akka.Persistence.Eventsourced.AroundPostStop (Akka.Persistence, Version=1.5.20.0, Culture=neutral, PublicKeyToken=null)
   at Akka.Actor.ActorCell.FinishTerminate (Akka, Version=1.5.20.0, Culture=neutral, PublicKeyToken=null)
```
The peak of the exceptions seem to happen during deployment (maybe because the actors were shut down?). And afterwards it seems to happen every 3 hours.
The exception doesn't seem to happen consistently. In our azure test environment where we only instantiate 1 actor, I didn't see the exception happening all the time on deployment. It was more consistent in our acceptance environment where there are more instances of the actor.

After our chat on Discord, I've removed the IWithUnboundedStash and deployed the actor again. The first deployment, the exception still happened. Subsequent deployment after that, the exception doesn't happen anymore (checked with 7 deployments not generating the exception).

**To Reproduce**
1. Implement ReceiveActor with IWithUnboundedStash
2. Deploy actor, instantiate many actors in the application
3. Change actor type to ReceivePersistentActor, don't remove IWithUnboundedStash
4. Deploy application

_Links to working reproductions on Github / Gitlab are very much appreciated_
Here's the simplified version of the Actors as requested:
[AkkaPersistenceNreActors.zip](https://github.com/akkadotnet/akka.net/files/15197191/AkkaPersistenceNreActors.zip)

**Expected behavior**
- No exception should happen or there should be an error Analyzer preventing IWithUnboundedStash to be used with ReceivePersistentActor
- Documentation updated if IWithUnboundedStash is not supposed to be used with ReceivePersistentActor

**Actual behavior**
NullReferenceException occurs

**Screenshots**
The image below shows the exceptions happening every 3 hours.
![image](https://github.com/akkadotnet/akka.net/assets/7829826/97869bb6-db01-43b7-9a5b-be85a0370514)

The deployment flows and when exception occurred:
![image](https://github.com/akkadotnet/akka.net/assets/7829826/8e435c53-6962-418a-90ff-6f2b837da932)

**Environment**
Linux, .NET 8

**Additional context**
- We use Cluster and Sharding. Persistence with Azure Table Storage.
- I suspect the exceptions to continue every 3 hours because of the actor passivation time, which is set to 6 hours? But i'm wondering why is it grouped every 3 hours - the actors were not created at the same time so I would expect to see a more sporadic occurrences of the exceptions

**Comment by Arkatufus** [comment]
@adeliab Remove the `public IStash Stash { get; } = default!;` line. 
`ReceivePersistentActor` has an internal stashing implementation, by declaring that line you're overriding that implementation and broke the actor.

![image](https://github.com/akkadotnet/akka.net/assets/8293237/c2fecc56-c36c-4064-a65d-0b7a3d3a3eb4)

**Comment by adeliab** [comment]
@Arkatufus yes I did remove that (see the deployment flow image) but it took a 2nd deployment of that change for the exception to disappear. So the exception was resolved eventually with that change. Aaron asked me for the C# of the actors to see why it was flaky when both are used and if the analyzer should be improved.
If there's no fix to be done on the package side, I think it would still be helpful to:
- Make the analyzer more strict
- Update documentation to explicitly mention that ReceivePersistentActor shouldn't be used with IWithUnboundedStash

**Comment by Arkatufus** [comment]
> * Update documentation to explicitly mention that ReceivePersistentActor shouldn't be used with IWithUnboundedStash

this is **100% incorrect**, `ReceivePersistentActor` already implements `IWithUnboundedStash`, re-declaring it in your class declaration **would not break your code**. Please read my answer above.
