### ISSUE TITLE
Some error messages are not logged unless info logging is turned on

### ISSUE THREAD

**Issue by oyzar** [akkadotnet/akka.net#7185]
**Describe the bug**

        public static void Error<T1, T2, T3, T4>(this ILoggingAdapter log, Exception cause, string format, T1 arg1,
            T2 arg2, T3 arg3, T4 arg4)
        {
            if (!log.IsInfoEnabled)
                return;

            log.Log(LogLevel.ErrorLevel, cause, format, arg1, arg2, arg3, arg4);
        }
        
        this should be IsErrorEnabled

**Comment by Aaronontheweb** [comment]
I believe this has been fixed via #7185
