### ISSUE TITLE
SandCastle fails when processing Akka.TestKit due to malformed XML-DOC tag

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#720]
Related to my comments on #719 

When SandCastle runs with full references to Akka.TestKit the last line we see in the build file is the following:

```xml
BuildAssembler : warning : ShowMissingComponent: [N:Akka.TestKit] Missing <summary> documentation [D:\Repositories\olympus\akka.net\bin\doc\Working\BuildReferenceTopics.proj]
BuildAssembler : error : Unexpected end tag. Line 19, position 16. (Line Number: 19; Line Position: 16; Source URI: '') [D:\Repositories\olympus\akka.net\bin\doc\Working\BuildReferenceTopics.proj]
  CopyFromIndexComponent: "reflection" in-memory cache entries used: 15 of 15.
  CopyFromIndexComponent: "comments" in-memory cache entries used: 14 of 30.
Done Building Project "D:\Repositories\olympus\akka.net\bin\doc\Working\BuildReferenceTopics.proj" (default targets) -- FAILED.

```

Based on [this old issue from the SandCastle project](http://shfb.codeplex.com/discussions/452473), looks like this is the problem:

> The error isn't related to the BuildReferenceTopics.proj file. It's more likely bad XML comments or perhaps an imported code block. Set the BuildAssembler Verbosity project property to All Messages. It will then report the member ID of each topic. The comments of the last one shown before the exception will be the place to start looking. 

BTW, the latest tooling for SandCastle can now be found here on Github - it's still being actively maintained: https://github.com/EWSoftware/SHFB

### What's the best way to find the malformed tag and fix this issue, so we can get API docs for TestKit?

**Comment by Aaronontheweb** [comment]
Leaving this issue open until I can confirm that SandCastle has made friends with Akka.TestKit :p

**Comment by Aaronontheweb** [comment]
cc @sean-gilliam tried running SandCastle with Akka.TestKit locally after merging in your changes. Still fails :(

**Comment by sean-gilliam** [comment]
@Aaronontheweb I'll try looking into it some more when I've got the time.

**Comment by HCanber** [comment]
I pulled out all comments from the *.cs files under Akka.TestKit, stripped away `///` and put `<ABC>` ... `</ABC>` around everything, basically turning everything into a giant xml file. Then I validated the file online hoping it would report some problems, like an unclosed tag or something, but no. No errors; it was well formed.

**Comment by sean-gilliam** [comment]
cc @Aaronontheweb  and @HCanber 

turns out Sandcastle will error out if it encounters a pre tag within a code tag due an internal HTML code colorizer. 

see https://shfb.codeplex.com/discussions/12084

**Comment by Aaronontheweb** [comment]
Nice catch, @sean-gilliam - that sounds like the culprit.

**Comment by Aaronontheweb** [comment]
@sean-gilliam fixed it with his PR. Here's the results; http://petabridge-ci.cloudapp.net/repository/download/AkkaNet_AkkaNetWeeklyApiDoc/244:id/bin/doc/html/d75eb659-6335-53f6-af7a-81814a21ab7f.htm?guest=1

**Comment by HCanber** [comment]
Note to self (if I ever need to revisit this).
The `<code>` tag used in C# xml documentation comments may look like the html `<code>` tag, but it's not.

`<code>` is a tag used for _multiline code_ (in HTML it's for inline code)
`<c>` is used for _inline code_
see https://msdn.microsoft.com/en-us/library/vstudio/5ast78ax(v=vs.110).aspx

Somewhat confusing.

|C# Doc Tag | HTML equivalent|
|-----------------|---------------|
|`<c>...</c>`|`<code>...</code>`|
|`<code>...</code>`|`<pre><code>...</code></pre>`|

Thanks, @sean-gilliam for finding this and fixing other problems/typos with our docs. Thanks @Aaronontheweb for getting SandCastle docs up and running. And thank you MS for the confusion!
![](http://upload.wikimedia.org/wikipedia/commons/3/3b/Paris_Tuileries_Garden_Facepalm_statue.jpg)

**Comment by sean-gilliam** [comment]
no problemo. glad i could help :)
