### ISSUE TITLE
F# API: Configuration.load is broken

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#722]
@jorgef drew my attention, that `Configuration.load()`, which is responsible for returning configuration from *.config files, fails silently returning empty HOCON node. 

Is this somewhat related to #679 ?

**Comment by Aaronontheweb** [comment]
@Horusiath does the `ConfigurationManager` behave differently for FSharp? Should be the same.

Oh snap, you know what it might be - we need to reference `System.Configuration` in `Akka.FSharp` in order for this to work.

**Comment by rodrigovidal** [comment]
Is it fixed?

**Comment by Horusiath** [comment]
It looks so. I've created a test case in Akka.FSharp.Tests to check if loading is performed without problems.
