### ISSUE TITLE
`Ask` and `ContinueWith` might cause memory leak

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/akka.net#7228]
> The user reporting this has replied that the main cause for the memory leak was ASP.NET `PinnedBlockMemoryPool` not releasing its accumulated buffer, eventually causing OOM (https://github.com/dotnet/aspnetcore/issues/55490).
>
> There is also a concern that an `Ask` operation paired with a `ContinueWith` might cause the `Ask` temporary actor to be pinned in memory and might be a contributing factor. We will need to look into this more.

_Originally posted by @Arkatufus in https://github.com/akkadotnet/akka.net/issues/7203#issuecomment-2147613146_

**Comment by Aaronontheweb** [comment]
No, this is not right - you can't cause a memory leak just by using `ContinueWith` using `Ask<T>` - you'd have to be doing something that causes the temporary `IActorRef` on `Ask<T>` to be rooted, and that `IActorRef` isn't even returned by the caller.
