### ISSUE TITLE
HOCON plugin Visual Studio

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#723]
We were talking about this on the last meeting - since HOCON is not supported by default on Visual Studio (and Xamarin Studio as well), we could think about IDE plugin for this. This issue has two major topics:
- Currently HOCON is built into Akka package itself. It should probably be moved to separate project and used by both the plugin and Akka.
- It would be nice if it could provide any kind of IntelliSense. This is problematic however since config nodes have no statically defined schema and furthermore it can be changed by included packages. My proposition was to create a hocon metadata file as embedded resource in each Akka package, that could change the schema. Plugin could read hocon schema from metadata embedded in referenced Akka dll files and provide IntelliSense based on it. It should be possible.

**Comment by rogeralsing** [comment]
Maybe we can get some pointers from @hmemcpy, he has done some work on similar stuff for Fake afaik.

**Comment by hmemcpy** [comment]
Hello :) sorry for the dumb question, but HOCON is...? :)

**Comment by hmemcpy** [comment]
Oh, right :) https://github.com/typesafehub/config/blob/master/HOCON.md

I'd be happy to help, but I recently became a dad, so it leaves very little time for OTHER pet projects... My best advice would be to look at https://github.com/madskristensen/WebEssentials2013 by @madskristensen, and piggy-back off that. Lots of great examples there.

**Comment by Aaronontheweb** [comment]
@hmemcpy congratulations on becoming a dad!

We'll take a look at the samples you pointed out :)

**Comment by hmemcpy** [comment]
Thanks! And good luck, I'll be happy to help, if I can!

**Comment by DamianReeves** [comment]
+1 for making HOCON its own library

**Comment by rogeralsing** [comment]
HOCON as its own library or not is a hard question IMO.
Typesafe has HOCON as its own library, but its also baked into Akka.

Under what namespace should HOCON live if it is a separate library? Cant really be Akka IMO.

I have thought about doing this for a long time but Im not sure its the best way forward for Akka.NET as a project.

Thoughts?

**Comment by stefansedich** [comment]
I like hocon. I feel it living on it's own makes sense.

Does an umbrella organisation that owns all of these projects also make
sense? Typesafe.NET :D

**Comment by rogeralsing** [comment]
Do you guys think that HOCON would be used outside of Akka.NET if we extract it?
For 3rd party configurations?

**Comment by stefansedich** [comment]
I would use it over web.config if I had the choice.

**Comment by DamianReeves** [comment]
First of all HOCON has some solid features on its own as a configuration system. Secondly it would offer users the opportunity to use a familiar config system for non Akka development.

**Comment by DamianReeves** [comment]
The fallback feature is actually pretty useful too. Being able to parse HOCON from various sources and setup this fallback hierarchy offers some benefits that are not offered in the tool chain until in Asp.net vNext whose config system still has some sour points.

**Comment by nvivo** [comment]
I was wondering, is this project related to the current implementation in any way? https://github.com/4agenda/OGS.HOCON

Anyway, I think it would be great to be able to use HOCON in other projects. I thought about reimplementing the parser using antlr, as the current one doesn't give many clues about errors. With the new configuration system in asp.net vnext, HOCON has a great chance of success.

**Comment by rogeralsing** [comment]
@nvivo cool, hadnt seen that one before.
I'll have to dig deeper into that and see pros/cons over our implementation.

**Comment by haighis** [comment]
I think it's a great idea to move HOCON to it's own library.

**Comment by Aaronontheweb** [comment]
that's really cool @nvivo!

I think moving HOCON to its own library is a good idea too. I love the thought of coupling it with some better tooling for error validation and some intellisense.

**Comment by haighis** [comment]
I would like to step up and implement this as it's own library.

**Comment by Aaronontheweb** [comment]
cc @haighis I think that's awesome Paul. I want to support you in doing that. 

https://github.com/akkadotnet/hocon - here's a repo I created for you.

Personally, I would love to see a lot more test coverage around implementing the HOCON spec when we have it as a stand-alone project. I think that would be awesome.

When you're ready to send in a pull request, ping me on Gitter and I'll make sure we we get some continuous integration set up for you.

**Comment by haighis** [comment]
And by Paul do you mean John (aka haighis)? or has someone else stepped up before me to take this on?

**Comment by Aaronontheweb** [comment]
@haighis whoops, I meant you John - had a brainfart and got your first name wrong :p

**Comment by rogeralsing** [comment]
Listening to the beatles much? :P

Anyway, there are a few features in HOCON that we currently does not support:

* Self referencing substitutions. this will require some major rewrite of the hocon parser as each node needs to remember old values that has been set earlier. - **Hard**
* Fallback substitutions, the spec says that if a substitution is not found in the hocon document, it _could_ look up values elsewhere,e.g. environment variables. - **Easy**
* Includes over `file(..)`  or `url(...)`,  currently we only support includes over a literal string, e.g. ` foo : { include : something }` where "something" could then be resolved using a callback.
Normally, the "something" is a filename, but the spec doesnt really say that it has to be, but ` foo : { include : url(someurl)}` should also be supported - **Medium**

Non spec related, but this is a task that would be nice to get done.

* Immutable nodes. currently, we use the same structure for parsing as we do for the final result. we should probably split this into two different trees, one possibly mutable for parsing,and one immutable for the public    API - **Easy** (if we just provide a different immutable tree over the current classes)

**Comment by cessationoftime** [comment]
I think any HOCON plugin should also contain a debugger visualizer. Viewing Config objects in the debugger is currently unpleasant.  I've actually built a debugger visualizer to do this which I can contribute.  It consists of multiple tabs, the first tab displays the contents of the primary config and subsequent tabs display the contents of each fallback configuration.

**Comment by sean-gilliam** [comment]
This issue probably should be directed to our HOCON repo.

https://github.com/akkadotnet/HOCON
