### ISSUE TITLE
Allow Akka.Discovery to be used with Akka.Cluster.Tools.ClusterClient

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/akka.net#7243]
**Is your feature request related to a problem? Please describe.**

In a dynamic environment, it is often hard to setup ClusterClient because the target ActorSystem receptionist will have a dynamic address

**Describe the solution you'd like**

Integrate dynamic contact point lookup a-la Akka.Management.ClusterBootstrap by leveraging Akka.Discovery:

* [x] Implement #7242
* [ ] Implement Akka.Cluster.Tools.Client.Discovery to do contact point lookup during runtime

**Comment by Arkatufus** [comment]
## Potential problems in implementing Akka.Cluster.Tools.Client.Discovery

### Network architecture difference
* ClusterBootstrap is needed once and only once because it is a peer-to-peer architecture.
* Cluster.Client.Discovery needs to be able to run multiple times because it is a client-server architecture. The client will need to run the discovery process everytime the current cluster receptionist it is connected to is dissociated.

### Configuration problem
Will need to figure out a new way to express this configuration in HOCON. We can probably use "akka.cluster.client.discovery-method" to signal that Cluster.Client needs to use a discovery mechanism instead of using "akka.cluster.client.initial-contacts`

**Comment by Aaronontheweb** [comment]
> Cluster.Client.Discovery needs to be able to run multiple times because it is a client-server architecture. The client will need to run the discovery process everytime the current cluster receptionist it is connected to is dissociated.

That's a good point, but isn't that just a method call on the `ServiceDiscovery` object?

**Comment by Arkatufus** [comment]
> > Cluster.Client.Discovery needs to be able to run multiple times because it is a client-server architecture. The client will need to run the discovery process everytime the current cluster receptionist it is connected to is dissociated.
> 
> That's a good point, but isn't that just a method call on the `ServiceDiscovery` object?

Yes, the point is in Cluster.Bootstrap, the plugin shuts down immediately after cluster was formed, so we could not just use Cluster.Bootstrap code to implement it with Cluster.Client. We'd need to figure out a way to detect dissociated receptionists and retry the discovery.

**Comment by Aaronontheweb** [comment]
> We'd need to figure out a way to detect dissociated receptionists and retry the discovery.

I don't think we actually need to do much here - the built-in Discovery plugins already account for this (i.e. in Akka.Discovery.Azure we have that dead-man's switch mechanism to do this; in K8s and AWS we just scan the environment metadata again), all that we need to do for the `ClusterClient` side of things is specify that if we're running with Akka.Discovery enabled then we'll need to re-populate the set of available receptionists by calling the Discovery plugin again. That should be a fairly small change.
