### ISSUE TITLE
Make timeouts used in TestKit(Base) class configurable

### ISSUE THREAD

**Issue by b8rni** [akkadotnet/akka.net#7259]
Unit tests often fail with timeout errors because of parallel execution of independent unit tests regarding the TestKit class. If the system is under heavy load, then it seems that the timeouts are to close...

To reproduce the problem you can try to start a cpu stress test and execute the "Failing_Test" until an Exception will be thrown. Usually it takes less than 10 repetitions until an error will occur (on my dev system):

[Fact]
public async Task Failing_Test() {
  var tasks = Enumerable.Range(0, 100).Select(_ => Task.Run(() => new TestKit()));
  
  var actors = await Task.WhenAll(tasks);
  foreach (var actor in actors) {
    actor.Dispose();
  }    
}

### Possible errors:
1. ![image](https://github.com/akkadotnet/akka.net/assets/153644837/ec9d2a0f-cebd-4bba-a2ff-5c7218d28cf3)
2. ![image](https://github.com/akkadotnet/akka.net/assets/153644837/9d4a4159-9f51-42f3-a054-847b5cee7e44)

### It would be nice if it would be possible to configure the following timeouts:
1. ![image](https://github.com/akkadotnet/akka.net/assets/153644837/0b2f8f1a-3072-4bbf-a48c-ba419a18b666)
3. ![image](https://github.com/akkadotnet/akka.net/assets/153644837/c8f0e7e1-f172-48b0-8464-a2704c20d1bd)

**Comment by Aaronontheweb** [comment]
A bunch of these default timeouts are configurable in the testkit, but yes those two are not. We run into these same issues inside the Akka.NET test suite itself and I'm always interested in whatever we can do to fix them.
