### ISSUE TITLE
Nuget install start page

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#727]
Json.NET adds a start page like this when you install the nuget package.
We should have the same IMO.
Some links to the site, and maybe to Petabridge's bootcamp?

It adds some cred to the product imo

![intropage](https://cloud.githubusercontent.com/assets/647031/6619704/55d23b58-c8cc-11e4-85b7-fae629b81083.png)

**Comment by Aaronontheweb** [comment]
Yeah, I think we should add a dedicated landing page to http://getakka.net/ that NuGet opens to - link to the Akka.NET Bootcamp, this Repo, our Gitter chat, our tag on StackOverflow, and all of the relevant spots on getakka.net

**Comment by danbarua** [comment]
There was quite a big push back on this: https://github.com/JamesNK/Newtonsoft.Json/pull/387

**Comment by Danthar** [comment]
To quote DamianH "We all love the lib, but we all don't like having a browser open every time we do a package install. It's borderline obnoxious. Thank you." 

Absolutely agree with that sentiment.

**Comment by Aaronontheweb** [comment]
Reading the comments on JSON.NET wasn't as cut and dried to me as I thought it would be. Seems to be a vocal minority of people who rage out over it and a bunch of other people who think "meh."

I'm not in a rush to add this to our NuGet packages either way - we still have a lot of work to do on updating the documentation on http://getakka.net/. I'd like to see how well that content serves to actually help get new Akka.NET user's questions answered and how many people actually find the site.

In the event that we get a surge of questions from people who've somehow managed to miss the thousands of pages of API docs, our wiki, http://learnakka.net/, and are still stuck on Akka.NET 101 - then in that case blasting open a browser every time they install a package to that content might be just what the doctor ordered :p 

Thankfully though - this project tends to attract developers who have a reasonable grasp on architecture and therefore do a lot of research beforehand. So I think that might be less of a problem for our audience at this stage.

I'll leave it open for now if anyone feels any differently.

**Comment by rogeralsing** [comment]
Closing this as most people seem to get irritated with start pages.
