### ISSUE TITLE
Item can be handed downstream from a SelectAsync stage even though a earlier item throws a exception

### ISSUE THREAD

**Issue by MattiasJakobsson** [akkadotnet/akka.net#7330]
**Version Information**
Version of Akka.NET? 1.5.27.1
Which Akka.NET Modules? Akka.Streams

**Describe the bug**
This might be intended behavior, I just want to file this here if it isn't.
I've run into a issue with the SelectAsync with high parallelism and failures where a later item could be returned downstream before the stream fails if a exception is thrown inside SelectAsync.
I think I've hunted the issue down to [this row](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Streams/Implementation/Fusing/Ops.cs#L2647) where, in case of a failed task, it's trying to push the next item downstream and there is a race condition where the next item will either be run through the rest of the graph or the stream will fail before.
In my case this meant I could miss messages because I would restart the stream on failures but maybe from a later position then I would like. The workaround is pretty simple though, I just never throw a exception from the SelectAsync and handle that in a select stage after.

If this isn't a intended behavior I wouldn't mind having a look at fixing this, I just want to confirm it's a bug before doing anything.

**To Reproduce**
1. Create a stream with a SelectAsync stage with high parallelism (I used 100 in my case) where some item will throw a exception (not the first one).
2. Handle the result in a later stage.
3. Observe that a item that got to the SelectAsync after a item that throws a exception might arrive at the later stage even though the exception should fail the stream.

**Expected behavior**
I would expect that a item that got into a SelectAsync (with any parallelism) after a item that throws a exception would never be handed downstream before the stream is failed.

**Actual behavior**
In some cases a item that got into a SelectAsync after a item that throws a exception will be handed downstream.

**Environment**
Ubuntu 22.04.4 LTS

**Comment by Aaronontheweb** [comment]
Interesting, thanks @MattiasJakobsson we will look into this

**Comment by Arkatufus** [comment]
@MattiasJakobsson 
What stage/flow do you use after the `.SelectAsync()` stage? I could not reproduce the issue you're describing with this unit test:

```csharp
[Fact]
public async Task A_Flow_with_SelectAsync_must_signal_error_at_appropriate_time_from_SelectAsync()
{
    var output = new List<int>();
    await this.AssertAllStagesStoppedAsync(async () => {
        var probe = Source.From(Enumerable.Range(1, 500))
            .WithAttributes(ActorAttributes.CreateSupervisionStrategy(Deciders.StoppingDecider))
            .SelectAsync(100, n =>
            {
                if (n % 10 == 0)
                    return Task.Run(async () =>
                    {
                        await Task.Delay(300.Milliseconds());
                        throw new TestException("err2");
                        return n;
                    }); 

                return Task.Run(async () =>
                {
                    await Task.Delay(50.Milliseconds());
                    return n;
                });
            })
            .Select(i =>
            {
                output.Add(i);
                return i;
            })
            .RunWith(this.SinkProbe<int>(), Materializer);
        
        (await probe.AsyncBuilder()
            .Request(100)
            .ExpectNextN(Enumerable.Range(1, 9))
            .ExpectErrorAsync()).InnerException!.Message.Should().Be("err2");
        
        await probe.ExpectNoMsgAsync(TimeSpan.FromMilliseconds(200));
        
        output.Should().BeEquivalentTo(Enumerable.Range(1, 9));
    }, Materializer);
}
```

In the unit test, even when we're running 100 parallel tasks, the result always stops at 10 when the exception occured.

**Comment by Arkatufus** [comment]
You do make a good point that in the scala version, the logic always fails the stage if any tasks did not return a success, so we should update the code to reflect that.

**Comment by MattiasJakobsson** [comment]
@Arkatufus In my case I have another SelectAsync with 1 parallel task after. It's a rare case though, my testcase is similar to yours but with 10000 messages in the source and random failure. It fails maybe 1/10 times. I'll see if I can make a generic version of my test and put it in a pr. I might have time to do that later today.

**Comment by Arkatufus** [comment]
@MattiasJakobsson 
Found the bug, yes, you are correct, it is a fairly rare race condition at that `continue` code.

Basically, if a task failed when the code is inside that loop in the `PushOne()` method, there is a small possibility that the message will be dequeued before it managed to call its async callback, so the `HolderComplete()` callback never gets called and that exception never get re-thrown.

**Comment by Arkatufus** [comment]
Since this is a race condition bug, I can't make a regression unit test for the bug, so I'm documenting the unit test I've used to find this here for future reference:

```csharp
[Theory]
[Repeat(10000)]
public async Task A_Flow_with_SelectAsync_must_signal_error_at_appropriate_time_from_SelectAsync(int _)
{
    var failurePoint = ThreadLocalRandom.Current.Next(3, 50);
    var output = new List<int>();
    (await Awaiting(async () =>
        {
            await Source.From(Enumerable.Range(1, 500))
                .SelectAsync(100, n =>
                {
                    if (n % failurePoint == 0)
                        return Task.Run<int>(async () =>
                        {
                            await Task.Delay(ThreadLocalRandom.Current.Next(100, 200).Milliseconds());
                            throw new TestException("err2");
                        });

                    return Task.Run(async () =>
                    {
                        await Task.Delay(ThreadLocalRandom.Current.Next(20, 50).Milliseconds());
                        return n;
                    });
                })
                .Select(i =>
                {
                    output.Add(i);
                    return i;
                })
                .RunWith(Sink.Ignore<int>(), Materializer)
                .ShouldCompleteWithin(5.Seconds());
        }).Should().ThrowAsync<AggregateException>())
        .WithInnerExceptionExactly<TestException>()
        .WithMessage("err2");

    output.Count.Should().Be(failurePoint - 1);
}
```
