### ISSUE TITLE
Under normal network conditions and with low cluster load, Spark encounters AssociationError reported by Akka

### ISSUE THREAD

**Issue by run597** [akkadotnet/akka.net#7340]
**Version Information**
Version release 2.2
akka-remote and akka-actor

**Describe the bug**
When using Spark, I encountered two errors related to Akka (version 2.2): 1) In the Spark driver logs, it indicates an AssociationError. 2) In the executor logs, it mentions Driver Disassociated. The cluster's network is functioning normally, yet these issues occur periodically and restarting Spark resolves them temporarily. I'd like to inquire about possible scenarios that could lead to these two errors.
<img width="1328" alt="截屏2024-09-20 09 01 35" src="https://github.com/user-attachments/assets/2a2957df-012c-47c7-b48a-029b47966acb">
<img width="1340" alt="截屏2024-09-20 09 06 22" src="https://github.com/user-attachments/assets/b91cb3a8-bae6-4f52-bc44-85268f5fc986">

**Comment by Aaronontheweb** [comment]
I think you're looking for https://github.com/akka/akka
