### ISSUE TITLE
Default serializer don't support F# discriminated unions

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#737]
It turned out that default Akka JSON.NET serializer is not able to properly deserialize discriminated unions. We need to address this problem before reaching 1.0. 

As I found, @thinkbeforecoding already solved this problem in one of his publications ([code](https://github.com/thinkbeforecoding/FsUno.Prod/blob/master/FsUno.Persistence.EventStore/Serialization.fs)). Unfortunatelly due to lack of licence I don't know if we can use this solution. It will also introduce direct dependency between **Akka.FSharp** and **Newtonsoft.Json**.

**Comment by Horusiath** [comment]
I've tracked this down to Newtonsoft.Json - reason of failure is `TypeNameHandling.All`, which serializes unions to form, where they cannot be deserialized back by JSON serializer. Changing this option to `TypeNameHandling.Objects` resolves the problem, but it breaks serialization of other Akka primitives.

**Comment by rogeralsing** [comment]
Is there anything we can do about it in the jsonconverter?

**Comment by Horusiath** [comment]
We could write our custom [DiscriminatedUnionConverter](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/DiscriminatedUnionConverter.cs), but to be honest I think it should be solved at the source (JSON.NET). I've already submitted an issue and maybe try to fix it directly there.

**Comment by Horusiath** [comment]
As I've seen, this bug has been solved in Newtosoft.Json and should be applied in incoming version of the library ([issue tracker](https://github.com/JamesNK/Newtonsoft.Json/issues/512#issuecomment-84275613))

**Comment by rogeralsing** [comment]
:+1:

**Comment by Aaronontheweb** [comment]
@Horusiath @rogeralsing mark this as closed for now or keep it open? It's out of our hands until the next JSON.NET release.

**Comment by HCanber** [comment]
Keep it open, so we don't forget about it. It's still a bug for us.

**Comment by Aaronontheweb** [comment]
Have a fix in-place for now per #827, but this should be revisited as a new issue in the future once an updated version of JSON.NET ships.
