### ISSUE TITLE
FluentConfig puts extra quotes in DefaultDispatcher(this FluentConfig self, DispatcherType dispatcherType, int throughput = 100, TimeSpan? throughputDeadlineTimeout = null)

### ISSUE THREAD

**Issue by kantora** [akkadotnet/akka.net#739]
So when just trying to use
FluentConfig.Begin()
                    .DefaultDispatcher(DispatcherType.PinnedDispatcher)
                    .Build();

system fails with "Unhandled Exception: System.NotSupportedException: Could not resolve dispatcher
type 'PinnedDispatcher' for path akka.actor.default-dispatcher"

I've manage to find this in decompiled sources:
Extensions.AsInstanceOf<FluentConfigInternals>((object) self).AppendLine(string.Format("akka.actor.default-dispatcher.type = '{0}'", (object) type));

Suppose you should remove single quotes from it.

**Comment by HCanber** [comment]
We should remove FluentConfig entirely as it was an experiment, right @rogeralsing ?

**Comment by rogeralsing** [comment]
Yes, if anyone use it, it could be moved to my repo untill everyone have migrated to app/web config

Skickat från min iPhone

**Comment by rogeralsing** [comment]
Closed due to obsoleting
