### ISSUE TITLE
Group Routing is busted in Akka.Cluster

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#743]
MultiNodeTest for clustered consistent hash routing can reliably produce it. The messages coming in from the cluster event publisher cause erratic race conditions with the routees table inside group routers at the moment. Need to investigate further - have no idea why pool routers are so stable but grouped ones are not when it comes to the influx of subscribed cluster gossip messages.

**Comment by annymsMthd** [comment]
Fixed

**Comment by rogeralsing** [comment]
Can we close this one?
