### ISSUE TITLE
Need to document all logging configuration options

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#744]
It's really difficult to figure out how to simply turn on verbose logging across the board right now. Need a "so easy that it's impossible to screw up" guide that explains how to do this easily

**Comment by stefansedich** [comment]
I will grab this one @Aaronontheweb any more ideas you have on what you want to cover?

**Comment by Aaronontheweb** [comment]
@stefansedich yeah, basically how to turn on verbose logging for Akka Core and Akka.Remote and Akka.Cluster. Each one has different options and we just need to get that information down in one place.

**Comment by Aaronontheweb** [comment]
CC @smalldave David might have some other ideas too

**Comment by smalldave** [comment]
I was thinking each module / extension could by convention expose config that turns on verbose logging for that module. Would make it easy to use (and document).
