### ISSUE TITLE
Form a non-profit foundation for collective ownership of project resources

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#747]
To keep akka.net completely OSS and prevent the project from going down the same route as many others before us, e.g. ServiceStack, RavenDB, PostSharp and many more.
They were once true opensource and are now all pay for commercial use.

I'd suggest that we start a non-profit foundation for collective ownership.

The F# foundation uses this kind of setup and I'd like to see the same for akka.net

There are some concerns from my side at least, let's take the getakka.net domain for example, which is currently owned by petabridge, I ofc does not distrust @Aaronontheweb or @skotzko, but business is business, companies get bought up etc. there is no guarantee that the team have access to the current domain name in a few years.
There have also been some non public discussions regarding the name of the project lately.

There are no "kind" money, so to protect the project from any such issues. e.g. ownership of resources whose value have been generated by the community. I'd like to see that all such resources get assimilated into a foundation as mentioned above.

I envision that resources like: domains, logo, name, license type, guarantees of openness etc would be included in such setup.

Thoughts on this?

**Comment by Horusiath** [comment]
:+1:

**Comment by skotzko** [comment]
Glad you brought this up, @rogeralsing. @aaronontheweb and I are totally in favor of this, and actually want to do this for Helios also which powers clustering etc. 

While Petabridge may create some proprietary Akka.Net extensions/tooling at some point in the future, we are fully in support of putting these assets in trust to protect/preserve the community resources from any future business circumstances (and would also provide a community edition of any such tooling). What happened with all those other projects having their FOSS option stripped away sucks, and goes against what we stand for.

**Comment by rogeralsing** [comment]
I see no issues with companies building and selling their own products around akka.net.
But the core of the project should be under some sort of protected.

There are a few options.

F# foundation
.NET foundation
Or we form a new foundation ourselves.

I'm a control freak so personally the latter feels safest, but maybe the other two works fine too. (?)

**Comment by HCanber** [comment]
:+1:

**Comment by rogeralsing** [comment]
cc @tpetricek

What is required in order to form this sort of foundation?
How does it work? its like a company w/o a work permit, but that is allowed to own things?

**Comment by tpetricek** [comment]
To be honest, forming a US non-profit is quite painful. @ReedCopsey did most of the work for F# foundation and so he is better person to answer the technicalities of this.

It is basically a "US corporation" that has to some additional paperwork to get the "non-profit status". In practice, the status means that US companies donating money do not have to pay tax on this - though I think being non-profit is mainly making the organization more credible. There are some legal requirements (have board, various documents, have regular meetings) etc. It is doable, but I'm kind of glad we waited long enough before actually doing this for the F# Foundation.

You can also have open membership (with board elections) or closed membership (with nominated members). The open membership again makes the foundation more credible (I think), but adds a lot of additional work.

I'm going to ask at the next F# Foundation board meeting to see if we could help. We have not quite figured out how to support open-source projects beyond the "core F# components". The .NET Foundation seems to be focused on primarily assets/code hosting, so perhaps they are more close fit (but then, more things in .NET Foundation are "basically MSFT owned").

**Comment by ReedCopsey** [comment]
@rogeralsing I'd be happy to discuss this with you, but I will say, right off the bat, you're probably better off trying to include this under the umbrella of an existing organization unless there's a very good reason not to do so.

A lot of the issues depend a lot on what jurisdiction you use and organize, as well as your goals in terms of setup and management.  As @tpetricek mentioned, there's potentially a huge amount of work involved in setting up a non-profit (though it depends on a large number of factors), as well as a not insignificant long term commitment that arises from moving the assets under that umbrella.

If you'd like, perhaps you (and @skotzko and @Aaronontheweb ?) and I could have a brief discussion on Skype or similar to discuss what's involved and the repercussions of doing this.

**Comment by rogeralsing** [comment]
@ReedCopsey sounds good to me

@akkadotnet/developers anyone else want to be in on such dialog?

**Comment by stefansedich** [comment]
Happy to help where I can @rogeralsing really like the idea of this.

**Comment by drr00t** [comment]
Hi,

I don know much about community management, but did you already take a look how ZeroMQ community was organized? Follow a link http://zguide.zeromq.org/page:all#the-community

**Comment by sean-gilliam** [comment]
Currently moving towards that end. Details soon-ish.
