### ISSUE TITLE
Add performance benchmark for Akka.Persistence

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#754]
I think, that just like we have a PingPong benchmark, we should introduce a similar one using a `GuaranteedDeliveryActor` and it's `Deliver`->`ConfirmDelivery` characteristics. Other thing worth benchmarking would be `PersistentActor` recovery speed for various number of journaled events.

**Comment by Aaronontheweb** [comment]
Can this be closed then?

**Comment by Horusiath** [comment]
I think so. Ping @4deeptech
