### ISSUE TITLE
Need to implement RemoteDeploymentWatcher

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#758]
Relatively new addition to Akka.Remote - https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/RemoteDeploymentWatcher.scala

They separated `RemoteDeploymentWatcher`, for watching remote-deployed actors, from the `RemoteWatcher` - used for watching remote actors regardless of how they were deployed.

We should add this to Akka.Remote (in Akka.NET) and port any relevant specs.

**Comment by maxim-s** [comment]
I'll do it

**Comment by rogeralsing** [comment]
This one have been merged, closing.

(correct me if Im wrong)
