### ISSUE TITLE
Implement RemotingTerminator

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#774]
Special termination hook for cleanly shutting down transports within Akka.Remote. Depends on #327

**Comment by smalldave** [comment]
@Aaronontheweb check out RemotingTerminator branch on my fork.
Also RestartNodeSpec branch has cluster test for #918

**Comment by Horusiath** [comment]
Could this one be closed?

**Comment by Aaronontheweb** [comment]
Hasn't been implemented yet. Caused a bunch of side-effects. I'll have to take a closer look at @smalldave's code and give it another try.
