### ISSUE TITLE
Severe performance loss in the last few days

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#777]
Our throughput have gone from 35 mil to 20 mil messages / sec on my machine since the last few pull requests.

Thats almost 50%, 
Any ideas where this comes from?

**Comment by rogeralsing** [comment]
This could be a false alarm, I've reverted back to a revision that is 2 months old, and I'm still seeing bad throughput.
Hopefully, it is just my computer that is b0rked somehow.
Anyone else that can verify this?
Do you know what numbers you use to see in the benchmark, are they still the same?

**Comment by stefansedich** [comment]
Give me a bit just running the tests myself will post my results.

**Comment by stefansedich** [comment]
@rogeralsing my results:

Worker threads:         1023
OSVersion:              Microsoft Windows NT 6.2.9200.0
ProcessorCount:         8
ClockSpeed:             2501 MHZ
Actor Count:            16
Messages sent/received: 30000000  (3e7)

ActorBase    first start time:  8.10 ms
ReceiveActor first start time: 21.41 ms

            ActorBase                          ReceiveActor
Throughput, Msgs/sec, Start [ms], Total [ms],  Msgs/sec, Start [ms], Total [ms]
         1,  3615000,       3.08,    8300.35,   3384000,       4.87,    8868.40
         5, 12981000,       2.92,    2314.51,  12024000,       3.63,    2498.88
        10, 16547000,       2.50,    1816.33,  15923000,       2.64,    1886.94
        15, 19417000,       2.61,    1547.85,  18575000,       3.24,    1618.25
        20, 20120000,       2.58,    1494.32,  19218000,       3.88,    1565.53
        30, 19710000,       2.92,    1525.02,  18137000,       3.26,    1657.63
        40, 19607000,       3.05,    1533.83,  17172000,       3.48,    1750.49
        50, 21770000,       2.82,    1381.30,  21676000,       2.97,    1387.21
        60, 22692000,       3.32,    1325.91,  20380000,       3.74,    1476.16
        70, 23584000,       7.82,    1280.73,  18326000,       5.59,    1642.82
        80, 21171000,       3.02,    1421.01,  19317000,       3.60,    1556.86
        90, 19096000,       2.85,    1574.14,  17182000,       2.78,    1749.57
       100, 17889000,       3.38,    1680.48,  17574000,       4.23,    1711.74
       200, 20202000,       2.71,    1488.53,  20477000,       2.90,    1468.35
       300, 21428000,       3.51,    1404.17,  21613000,       2.93,    1391.24
       400, 24291000,       3.27,    1239.17,  21321000,       2.81,    1410.73
       500, 24732000,       2.61,    1215.76,  23419000,       2.87,    1284.18
       600, 23659000,       2.84,    1270.87,  22539000,       3.91,    1335.03
       700, 24711000,       5.26,    1219.76,  23094000,       4.70,    1304.10
       800, 24291000,       4.42,    1239.95,  24429000,       2.65,    1230.81
       900, 23734000,       2.88,    1267.03,  22935000,       4.44,    1312.53
Done..

**Comment by rogeralsing** [comment]
Those are about the same numbers as I see, but they have always been around 34ish mil per sec before.
But reverting back monts still doesnt help. so I'm not sure what is going on.

**Comment by stefansedich** [comment]
I went back 4 months to f8c70bc5aea5a753e6cde897a96a11519bb75cf8:

Worker threads:         1023
OSVersion:              Microsoft Windows NT 6.2.9200.0
ProcessorCount:         8
ClockSpeed:             2501 MHZ
Actor Count:            16
Messages sent/received: 30000000  (3e7)

ActorBase    first start time:  4.41 ms
ReceiveActor first start time: 15.82 ms

            ActorBase                          ReceiveActor
Throughput, Msgs/sec, Start [ms], Total [ms],  Msgs/sec, Start [ms], Total [ms]
         1,  4248000,       2.69,    7065.08,   4378000,       2.55,    6854.39
         5, 15007000,       2.99,    2002.84,  14409000,       2.18,    2084.19
        10, 19206000,       2.65,    1564.96,  17472000,       3.10,    1720.52
        15, 21321000,       2.13,    1409.93,  21216000,       2.31,    1416.87
        20, 19169000,       2.18,    1567.93,  18248000,       5.14,    1649.64
        30, 24772000,       2.17,    1213.44,  25125000,       4.22,    1198.80
        40, 24350000,       2.17,    1234.69,  19543000,       5.49,    1541.18
        50, 22675000,       2.99,    1326.57,  25641000,       2.25,    1172.95
        60, 23734000,       2.25,    1266.98,  20107000,       2.89,    1495.05
        70, 21961000,       5.02,    1371.59,  27297000,       2.24,    1101.26
        80, 27497000,       2.55,    1094.39,  21567000,       2.26,    1393.80
        90, 20675000,       2.93,    1454.03,  22075000,       3.16,    1363.05
       100, 27624000,       2.19,    1088.70,  24291000,       2.23,    1237.82
       200, 27881000,       2.21,    1078.73,  24350000,       2.23,    1234.88
       300, 21186000,       4.02,    1420.14,  23809000,       2.94,    1263.81
       400, 26408000,       2.19,    1138.22,  28957000,       2.44,    1038.73
       500, 26338000,       2.30,    1142.16,  22744000,       3.05,    1322.95
       600, 23255000,       4.76,    1294.84,  28571000,       2.79,    1053.13
       700, 30272000,       2.41,     993.68,  24610000,       2.23,    1221.72
       800, 22404000,       3.00,    1342.36,  24834000,       3.01,    1211.93
       900, 31120000,       2.32,     967.19,  27397000,       2.38,    1098.25
Done..

**Comment by stefansedich** [comment]
Really hard to get any consistent numbers from these tests @rogeralsing and hard to make sense of the results :(.

**Comment by rogeralsing** [comment]
I've reverted back 6 months, still the same lame throughput.
So it's definitely my computer that acts out some how.
No idea what can be causing it though,

Closing since revisions that have worked fine works bad on my machine now. so cant be code related.

**Comment by rogeralsing** [comment]
I found the issue.

It turned out to be Hyper-V, when virtualization is enabled on the computer, you can not set processor min/max perf in Windows 8.
Thus, your power saver options does not affect perf.

Disabling Hyper-V and resetting power options to High Performance solves the issue...
