### ISSUE TITLE
akka.net.io namespace 

### ISSUE THREAD

**Issue by bobanco** [akkadotnet/akka.net#788]
Hi Guys, 

Firstly, i want to say thanks to all who did effort for porting this nice framework to .net community, i want to use the actor model to build fault tolerant telecom project which perfectly fits my requirements, since java/scala has the akka.io package in order to work with underlying TCP,UDP sockets i was not able to find the corresponding implementation in akka.net, so i want to ask is there any progress over the IO namespace or any plans for this to be ported in future? 

Thanks in advance,
Bob.

**Comment by Aaronontheweb** [comment]
hey @bobanco - welcome to the project!

@Horusiath has done some exploratory work on Akka.IO and to be honest it's an essential ingredient for some of the important mobile scenarios we want to enable (running Akka.NET clients on Xamarin / Windows Phone that can communicate with an Akka.NET cluster.)

**We will port Akka.IO to Akka.NET**, but at the moment don't have any dedicated resources for it. The core team is pretty focused on Akka.NET core, Akka.Cluster, and Akka.Persistence at the moment - but our contributor base is expanding every week and this would be a project we'd be happy to see some  pull requests for.

**Comment by willieferguson** [comment]
I have completed most of the Akka IO port (TCP driver only). I'm busy porting the remainder of the Akka IO specs, and ironing out some inconsistencies between .NET IO and JVM IO. But it should be done in the next couple of days.

https://github.com/willieferguson/akka.net/tree/AkkaIO

**Comment by rogeralsing** [comment]
@willieferguson that is awesome!! :+1:

**Comment by bobanco** [comment]
@willieferguson Thanks for your effort to port the IO part, i will test the  TCP driver and will let you know if there are any issues.

**Comment by willieferguson** [comment]
@bobanco The current branch on my fork is broken. I've ported most of the test (not all pushed yet). Once all the tests are ported, I will experiment with various implementation of SocketChannel - the adapter for .NET sockets. I should have an working alpha version next week.

I've also started with the Akka Streams port and plan to have an alpha version in June.

**Comment by Horusiath** [comment]
@willieferguson How much of the Akka.Streams did you ported already? There are multiple attempts for this, including mine.

**Comment by Horusiath** [comment]
@willieferguson would you consider a PR for this one? If it's not finished yet but it's close-to-complete point, I think we could make a separate branch for it and make able to contribute from rest of the community. How do you think @akkadotnet/developers ?

**Comment by willieferguson** [comment]
@Horusiath - I'm currently travelling with limited internet connectivity. I will create a PR early next week when I get back home. I need to merge upstream and squash my commits before I do that.

I've looked at your Akka.Streams port and have some comments. Maybe we should start a new issue to discuss streams and align efforts on the port.

**Comment by rogeralsing** [comment]
@willieferguson can we make a detailed document/issue on what is missing from the current implementation?
(or is there already one?)

If anyone is going to contrib to this, we need to know where to start.

40% of the tests seems to fail on my machine _sometimes_ is that anything you have seen before?

**Comment by willieferguson** [comment]
@rogeralsing, I have ported most of the outstanding classes and will create a PR for them tomorrow. I will then add a task list to this issue, detailing outstanding work. 

What we need most is people willing use and test. @bobanco, are you still planning on using Akka IO? I will start work an a project next week that will use Akka IO extensively, and should get some result on quality and performance from that.

I've seen 2 test that fails intermittently, but nothing like 40%.

**Comment by bobanco** [comment]
@willieferguson i have started integrating Akka IO into my project, actually am building SMPP server and client but it's far away from testing phase so i couldn't say anything right now, as i have tested with some basic server and client it worked well.

**Comment by willieferguson** [comment]
@rogeralsing: I'm currently aware of the following outstanding items on the IO port (I will keep this list updated as they get implemented):

- [X] DNS: Port DNS cache
- [ ] TCP: Port File IO  (in progress by @willieferguson)
- [ ] TCP: Port missing tests in TcpConnectionSpec and port TcpIntegrationSpec
- [ ] ByteString: Port missing members
- [ ] ByteString: Port tests
- [ ] ByteIterator: Port missing members
- [ ] ByteIterator: Port tests

**Comment by willieferguson** [comment]
@rogeralsing, I've created a Akka Remote transport based on Akka IO. Should this go into the Akka.Remoting assembly?

**Comment by rogeralsing** [comment]
@willieferguson nice! :) 
I think we should make a contrib package of that first. e.g. Akka.Remote.AkkaIOTransport or something like that.
This way we can evaluate it for some time

cc @akkadotnet/developers  whats your thoughts on this?

**Comment by Horusiath** [comment]
Regardless, separate contrib package is always possitive diversity :+1:  

The questions I'd like to get an answer for are:

1. What about SSL support? (I don't see it pointed out)
2. It would be nice to see akka-oriented performance comparison of both Helios and Akka.IO (nr. of messages passed / sec, memory footprint etc.).
3. I always wanted to ask TypeSafe, if they have a plan for switching from Netty to Akka.IO eventually? ;)

**Comment by rogeralsing** [comment]
@Horusiath yes there have been plans on the JVM side for a long time to switch to Akka.IO AFAIK.

cc @rkuhn, what happened to that effort?

**Comment by rkuhn** [comment]
Switching to the message-based Akka IO is a lot less attractive than switching to Akka Streams—which gives a rather rich toolset for dealing with the associated issues. The current solution is rather complex since it is not built upon a proper stream abstraction. This answers why we have not yet pursued this issue: first we need to finish Streams.

**Comment by rogeralsing** [comment]
@rkuhn is that work eventually going to replace the base Netty transport?
Or will you build streams ontop of Netty?

**Comment by rkuhn** [comment]
Streams have everything from the network up, so we’ll eventually replace Netty completely.

**Comment by rogeralsing** [comment]
:+1:

**Comment by rogeralsing** [comment]
@akkadotnet/developers how comfortable are we about migrating the Akka.IO branch into main?
It seems to be fairly complete, if its possible to build and run an Akka transport ontop of it.

The problem with feature branches is that they get very little attention.
Most bugs and contributions pop up when the bits are easy to access for other devs.

So I think we should migrate it over to the Dev branch.

**Comment by Horusiath** [comment]
:+1:

**Comment by willieferguson** [comment]
I will add the IO Transport, port the missing TCP tests and look at the intermittent test failures ASAP.

@Horusiath: TLS is currently not supported. I will look at options for TLS support next week, as I require this.

The current Transport implementation API will not work well with streams, but once steams are implemented one can implement a generic stream transport, which could then be plugged with any stream.

**Comment by Aaronontheweb** [comment]
How's the test coverage thus far?

**Comment by rogeralsing** [comment]
There is like 35 tests all passing for it.

**Comment by Aaronontheweb** [comment]
Ok, can we add two PRs then:

1. A documentation PR to https://github.com/akkadotnet/getakka.net
2. A code PR to this one

cc @willieferguson would you be comfortable writing a small markdown document for Akka.IO that explains to someone who's never used it before how it works?

**Comment by willieferguson** [comment]
@Aaronontheweb, Sure, I will write a getting started guide and create a PR on getakka.net. Can we link to akka.io for more detail?

**Comment by willieferguson** [comment]
@akkadotnet/developers, I'm now reasonably comfortable with the quality of I/O and there is now a doc page on getakka.net. Should we merge into dev?

**Comment by Horusiath** [comment]
It looks fine for me. At the moment I'd like to see only two things:

1. List of things not done/tested yet in Akka.IO. @willieferguson you've written it, but is it up to date?
2. Part of the process is to document all public API (so public components only) with .NET xml comments.

It's not so pleasant part of the work, but it should be done at some point. However it could also be completed after the merge if rest of the devs will agree.

**Comment by Aaronontheweb** [comment]
I agree with @Horusiath - need to add some XML-DOC comments since that shows up in our API docs: http://api.getakka.net/docs/stable/html/5590F8C9.htm

**Comment by Aaronontheweb** [comment]
So we've brought in most of Akka.IO into dev. What else needs to be done here?

**Comment by willieferguson** [comment]
The checklist above is still accurate. I am almost done with File IO and missing members on ByteString/ ByteIterator and will send PR for them soon.

**Comment by Horusiath** [comment]
I think, we can close this - eventual issues will be solved in separate tasks.
