### ISSUE TITLE
Unreliable Save/Restore snapshot for GuaranteedDeliveryActor

### ISSUE THREAD

**Issue by aprooks** [akkadotnet/akka.net#789]
hi, I was trying to implement a GuaranteedDelivery sample: https://github.com/aprooks/akka.net/commit/2f25bd9e3eed9deb483fef7be9fdc5bbf063470c

and found, that if you throw exception right after  saving snapshot, new instance is reloaded with an old journal, and `foo` message is lost:

```
            deliverer.Tell(new Message("foo"));
            System.Threading.Thread.Sleep(1000);  //Remove this and restores none 
            deliverer.Tell("boom");
```

Did I miss something? Is there's a way to have a 100% guarantee of not missing a message?

**Comment by Horusiath** [comment]
@aprooks thx for the note. It looks like a bug from snapshot store point of view - for some reason when the actor restarts it sends a request to snapshot store for the latest version of it's state, but snapshot store is not responding correctly - it doesn't save a snapshot on local file system on time, neither it returns data from the currently saving snapshots log.

**Comment by aprooks** [comment]
@Horusiath thak you for confirmation.

**Comment by Horusiath** [comment]
I've recreated the same issue using JVM akka persistence code ([sample](https://gist.github.com/Horusiath/bd00d33a130e4add2491)). Tracker: akka/akka#17139

**Comment by Aaronontheweb** [comment]
Nice @Horusiath !

**Comment by Horusiath** [comment]
As discussed on Akka JVM thread, this is not a bug. Akka.Persistence mechanism uses snapshotting only as optimization technique. It shouldn't be used solely without event's persistence as it's not a safe mechanism in environment when infrastructure is not error-proof (basically any non-academic case).
