### ISSUE TITLE
GetAkka.NET Team page

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#790]
As we are getting more and more contributors. and we have less and less time to maintain the project site.
Maybe we should try to automate things a little.
The Team page is pretty much useless right now. there are new contributors that are not listed there.

So, maybe we should just pull project statistics from github and generate the team page from that?
`https://api.github.com/repos/akkadotnet/akka.net/stats/contributors`

That should be enough to get the top x contributors, and generate a list similar to the contributors list here on github.

Thoughts?
We could still have a static part where we present the core team members.
But imo, it would be fair to list non core members too.

**Comment by Aaronontheweb** [comment]
I like it - I'm big on the idea of recognizing our contributors publicly for their effort. That's what makes me enjoy reading the Github issues, pull requests, and Gitter chat every morning. Let's do something to support our guys and girls.

**Comment by rogeralsing** [comment]
I've put together a minimal ajax solution to aggregate the data from Github.
This should probably be done at site generation stage instead of dynamic from client side.
http://getakka.net/pages/team

So what more should we show here?
Add the same kind of commit-graph as github has per developer?
Anything else?
