### ISSUE TITLE
Create a contributor license agreement for Akka.NET

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#791]
I got pinged on this issue a few minutes ago https://github.com/datastax/csharp-driver/issues/85

And realized that we need something like this in order to be fully-compliant with Apache 2.0 going forward.

First, we'll need to create a contributor license agreement (CLA.)

We'll have to create a bot that prompts for signatures from new contributors on pull requests and reminds them to e-sign a document before we can accept.

It's not a big deal - the primary purpose of the CLA is basically to make it easier to do source code copyright and attribution, so we can attribute work to the Akka.NET project rather than every individual contributor on each individual file.

Most projects never need this, but we're at the size now where it's worth discussing.

**Comment by rogeralsing** [comment]
Can the copyright be on a non existing legal entity? Eg akka.net project?
As that is not a person, company, organisation nor foundation. The copyright is pretty much assigned to dev/null (??)

**Comment by Aaronontheweb** [comment]
Yes, in order for it to have any legal teeth there does need to be an entity. So this is related to #747

**Comment by avalanche123** [comment]
BTW, if you're still interested, we've just open sourced the CLA Enforcer - https://github.com/datastax/cla-enforcer.

Cheers!

**Comment by sean-gilliam** [comment]
Currently moving towards that end. Details soon-ish.
