### ISSUE TITLE
RPI-Mono benchmark deadlock

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#797]
There seems to be some sort of RC in the local provider when running RPI-Mono.
Running the PingPong benchmark hangs the application indefinitely.

The system does start up, but just freezes when trying to perform the actual benchmarking.

**Comment by rogeralsing** [comment]
```csharp
await Task.WhenAll(tasks.ToArray());
```
That line never completes

**Comment by rogeralsing** [comment]
I've tried this with both the `MonoConcurrentQueue` and the built `ConcurrentQueue`, same issue.

Is anyone seeing deadlocks in the PingPong benchmark on other versions of Mono?
That is, if you run the PingPong app repeatedly, does it ever hang in the middle of a run?

**Comment by rogeralsing** [comment]
Looks like we have a RC in the mailbox implementation.
And I would not be super surprised if it is present in .NET too and that this is what we are seeing sometimes in our failed build.
I suspect the RC only makes itself visible on very low end machines.

At least on the RPI, it ends up with a mailbox with status busy, and x messages left in the queue.
But the mailbox run have already exited so there is no one that can set the status back to idle to make it start processing again.

The good news is that the messages are at least not lost, they are present in the mailbox.
So the problem is somewhere at the end of the mailbox run code.

**Comment by rogeralsing** [comment]
Debugging the mailbox.

I've replaced the mailbox `Schedule` with the following code

```
/// <summary>
/// Schedules this instance.
/// </summary>
protected override void Schedule()
{
    //only schedule if we idle
    if (Interlocked.Exchange(ref status, MailboxStatus.Busy) == MailboxStatus.Idle)
    {
        Interlocked.Exchange(ref stage, 1); //<-----
        ThreadPool.UnsafeQueueUserWorkItem(_ =>
        {
            Interlocked.Exchange(ref stage, 3); //<-----
            Run();
        }, null);
        Interlocked.Exchange(ref stage, 2); //<-----

    }
}
```

The mailbox ends up with debug state `2`, that is, we have scheduled the mailbox run, but the mailbox run never executes, if it did, it would be stage `3`

So, for some reason, when we schedule actions to the ThreadPool, they sometimes get lost or stuck, I'm not sure why this happens..

This is not a case of a saturated threadpool because that would eventually complete given enough time. in our case, the action never starts to execute no matter how much time we give it..

cc @migueldeicaza any ideas why the threadpool swallows random actions?

**Comment by rogeralsing** [comment]
Here is a link to my debug branch :
https://github.com/rogeralsing/akka.net/tree/mono-trheadpool

Compile the project under "Mono Debug" (compile in VS.NET or whatever)
then run the pingpong app in the RPI:
`mono PingPong.exe`

_Sometimes_, it freeze and gives a result like the screenshot below:

![error](https://cloud.githubusercontent.com/assets/647031/6998155/2cf7e1c4-dbd7-11e4-9a5a-a1425eb40552.png)

It can take a while to get the actual problem, but eventually it will appear.

"Stage 2" is Scheduled but not executed.

**Comment by rogeralsing** [comment]
I have tried this with mono 3.10 and the issue is still there.

**Comment by imkow** [comment]
the lastest mono is 3.12 and beta is 4.0

**Comment by rogeralsing** [comment]
I'm unable to find the cause for this.
Any help would be welcome :)

The problem is super easy to reproduce, just grab the PingPong benchmark code from the source repo and run on a Raspberry PI2, it will from time to time freeze up

**Comment by davzucky** [comment]
@rogeralsing  
I tried to look at the debug branch you are referencing, however it doesn't exist anymore [https://github.com/rogeralsing/akka.net/tree/mono-trheadpool](https://github.com/rogeralsing/akka.net/tree/mono-trheadpool).
do you still need help ?

**Comment by Aaronontheweb** [comment]
This can be closed now. Can run Akka.NET on Mono 4.4.2, including Clustering and Remoting.
