### ISSUE TITLE
Akka.Net with asp.net REST API

### ISSUE THREAD

**Issue by tru3d3v** [akkadotnet/akka.net#804]
Hi,

I want to ask, How to calling Akka Actor as Json Result in asp.net Web Api Controller?

advice me please.

**Comment by stefansedich** [comment]
Hi @tru3d3v,

Not sure I follow what you are trying to achieve, mind sharing some more details? I might also suggest taking this over to gitter https://gitter.im/akkadotnet/akka.net and starting the discussion there.



Cheers
Stefan

**Comment by rogeralsing** [comment]
Something along the lines of this should do the trick for you:

```csharp
public class ActorController : ApiController
 {
     public async Task<IHttpActionResult> GetProduct(int id)
     {
         var result = await MyStaticStuff.SomeActor.Ask<MyResult>(new SomeMessage(id));
         return Ok(result);
     }
 }
```

Where:
`MyStaticStuff.SomeActor` is an `IActorRef` that you have stored in a static var.
e.g. created in Application start.

`MyResult` is the type of the data you want your actor to return.
`SomeMessage` is the message you want to send from the controller to the actor.

**Comment by tru3d3v** [comment]
Hi @rogeralsing

That's what I mean

Thank you for your advice :)
