### ISSUE TITLE
Production users?

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#807]
cross post of https://github.com/akkadotnet/getakka.net/issues/4

Do we have any companies here that would like to be listed on the site?
Or even better, is there anyone that would make a public statement about it?

**Comment by Aaronontheweb** [comment]
We know a bunch, but it might be tough for them to get permission to talk about it. So this might take a little bit of time to do.

**Comment by Aaronontheweb** [comment]
We've got a bunch we're in touch with; we're working on getting some stories from them ;) - takes a while for the pig to go through the snake.
