### ISSUE TITLE
Docs: move from CloudCopy --> azure-cli

### ISSUE THREAD

**Issue by SeanKilleen** [akkadotnet/akka.net#813]
Per #811, the docs are hosted via CDN and MS Azure blobs. 

CloudCopy is currently used to get things up to Azure, but it is gross/old/slow and Akka deserves the new hotness.

This issue is to track moving to the azure-cli on the build server to publish the docs in a way that doesn't make @Aaronontheweb sad.

### Research Steps
- [x] Ensure the azure-cli makes sense on the build server
- [x] Ensure security around publishing certs
- [x] Further explore the current docs build process
- [x] Understand azure-cli methods for copying files / directories
- [x] Find out whether whole directories can be uploaded, or whether we need to iterate over every file.

### Pre-requisites:
* Install [Azure-PowerShell](https://github.com/Azure/azure-powershell) via the Web Platform Installer on the server
* Run powershell as the build server user/service account
* Run `Get-AzurePublishSettingsFile`. This will open a web site where you login to Azure and then download the file. (your credentials will presumably have access to the blob)
* Run `Import-AzurePublishSettingsFile "C:\Path\To\File"`, which should import those management credentials. 
* At this point, the credentials will be in place to manage storage blobs via PowerShell.

### Likely Code Changes: 

* Change the build process to call powershell with the specific Azure command(s) to upload the files
 * `Get-Help Start-CopyAzureStorageBlob` will be a good place for us to start.

**Comment by Aaronontheweb** [comment]
> in a way that doesn't make @Aaronontheweb sad.

I wish more pull requests stipulated this as a functional requirement :p

**Comment by SeanKilleen** [comment]
@Aaronontheweb what OS is the build server? Need to figure out whether I'm gearing more towards Azure PowerShell or azure-xplat-cli.

**Comment by Aaronontheweb** [comment]
@SeanKilleen Windows Server 2012 - we'll be adding some Ubuntu build servers for Mono but they won't be responsible for the doc generation (SandCastle is Windows only IIRC.)

**Comment by SeanKilleen** [comment]
:+1:

**Comment by SeanKilleen** [comment]
@Aaronontheweb I created #818 which I think actually provides us with a better option. I'm combing through the syntax commands for it now and will create a PR against that. Closing this in the meantime.

I'll still try to make sure you're not sad.
