### ISSUE TITLE
Docs: Move from CloudCopy --> AzCopy

### ISSUE THREAD

**Issue by SeanKilleen** [akkadotnet/akka.net#818]
[AzCopy](http://azure.microsoft.com/en-us/documentation/articles/storage-use-azcopy/) is Microsoft's tool for copying files to Azure storage blog.

I think the Azure PowerShell tools unfortunately mostly support copying between blobs.

As of now, I recommend this instead of Azure PowerShell tools.

### Build Server Changes
- [x] Move [Azure Storage Tools](http://azure.microsoft.com/en-us/documentation/articles/storage-use-azcopy/) into the tools directory

### Code Changes
- [x] Understand current syntax of build process for copying items using AzCopy
- [x] Replace CloudCopy call with a command-line call to AzCopy

### Testing
Not sure I can really help out with this one since it has to be done on the build server. I'll do my best to launch the command locally and at least ensure that it fails in an understandable way.

**Comment by Aaronontheweb** [comment]
@SeanKilleen if we can make this work with a local copy of the AzCopy binary, per #819, then that'll make life a lot easier all around :p

**Comment by SeanKilleen** [comment]
@Aaronontheweb 100% agreed, already put that into #819 for that exact reason. Wasn't thinking it through during my initial write-up.

**Comment by Aaronontheweb** [comment]
Still have some bugs I need to sort out with AzCopy - setting right content-headers and such.

**Comment by SeanKilleen** [comment]
@Aaronontheweb sorry that I don't have more visibility into what you're seeing. If you want to post a little more about it here (error messages, general background, etc.) I can try to do some legwork on it.

**Comment by Aaronontheweb** [comment]
no error messages - just not seeing the results I expect inside Azure blob storage.

Saw two problems basically:

1. Some content didn't look like it was being overwritten correctly (replacing an existing blob with a local file from source)
2. Uploaded content had the incorrect MIME type

Just closed a PR that fixes problem 2 - going to see if the issue with problem 1 was related to something else I was doing last night.

**Comment by Aaronontheweb** [comment]
@SeanKilleen turns out that the content not being overwritten correctly is an Azure CDN issue... I need to find a way to set a better default content-cache expiration header.

Might just disable the CDN for now and serve everything directly from blob storage.

**Comment by Aaronontheweb** [comment]
But otherwise, everything else is working.

**Comment by Aaronontheweb** [comment]
In order to use this with the CDN we'll need to be able to tell AzCopy to do this for each file: https://msdn.microsoft.com/en-us/library/gg680306.aspx

Not a big deal though. We'll just disable the CDN for now.
