### ISSUE TITLE
Ship weekly pre-release of Akka.NET packages to NuGet

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#837]
Per @nvivo's comments on #835 

> Would be nice to have a new "rc" on nuget before releasing the next version, so we can better check this and the other issues.

Going to propose that we ship a weekly pre-release build of all packages onto NuGet for the bleeding edge users. Any opposition or alternatives to this idea we should discuss?

**Comment by nvivo** [comment]
It would be nice to have a nightly build as this project moves at light speed. 

But this may pollute nuget too much.  I know some projects use myget for this.

**Comment by nvivo** [comment]
Note: nightly builds would be separated from RCs,  those could be on nuget directly.

**Comment by Aaronontheweb** [comment]
@nvivo our CI server (TeamCity) has a built-in module for acting as a local NuGet repository. I could do nightly builds there for the die-hards and still do a weekly build to nuget.org.

**Comment by nvivo** [comment]
Nice. If you set it up, I'll use it for testing in my apps. It's easier than constantly switching nuget references for local references and back.

**Comment by Aaronontheweb** [comment]
@nvivo that's good feedback - thanks. I'll look into setting that up on TeamCity once I'm back from .NET Fringe

**Comment by Aaronontheweb** [comment]
We now have *nightly* NuGet builds available from our CI server. See the full details here:

http://getakka.net/docs/akka-developers/nightly-builds
