### ISSUE TITLE
Rewrite NuGet build script so each individual package upload gets retryed on failure

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#838]
Right now a NuGet release is "all or nothing" - if one NuGet package gets uploaded but the others fail, then the entire job fails permanently and I have to manually upload all packages.

We should rewrite the FAKE script to wrap each individual package upload in a retry and allow them to continue independent of eachother.

**Comment by Aaronontheweb** [comment]
Still an issue - described it in detail on #1492

**Comment by Silv3rcircl3** [comment]
Can we close this one? If I remember correctly it was an issue with the nuget.exe wasn't it?

**Comment by Aaronontheweb** [comment]
Yes, close it
