### ISSUE TITLE
Akka.Cluster still listed as prerelease on NuGet

### ISSUE THREAD

**Issue by pcwiek** [akkadotnet/akka.net#844]
Hi there!

[Akka.Cluster](http://www.nuget.org/packages/Akka.Cluster/) still seems to be marked as prerelease, because the package has `-pre{buildnumber?}` in the name. Is that intentional and should it be treated as prerelease, or was it just an oversight and it should be just 1.0.0 'stable'?

**Comment by rogeralsing** [comment]
Cluster and Persistence is still prerelease.
Akka core, remote, F# API and Testkit are V1.

**Comment by pcwiek** [comment]
Ah, OK, thanks for confirmation.

Since I have some trouble setting up clustering correctly, I'll probably use Remoting for now as a 'simpler' solution (which would also work, at least for now) and move to Cluster once it hits 1.0 - and once I learn how to configure it so it actually works.
