### ISSUE TITLE
DateTime Concerns

### ISSUE THREAD

**Issue by mj1856** [akkadotnet/akka.net#846]
In many places throughout the code the current time is retrieved by calling `DateTime.Now`.

For example, here are just a few of the lines I found:

````csharp
return Receiver.Ask(new Get(DateTime.Now + timeout), Timeout.InfiniteTimeSpan);
```

```csharp
var cancelable = Context.System.Scheduler.ScheduleTellOnceCancelable(next.Deadline - DateTime.Now, Self, new Kick(), Self);
```

This is not a good practice, as it means that code could fail during [daylight saving time](http://stackoverflow.com/tags/dst/info) transitions.

`DateTime.Now` returns the local date and time based on the time zone setting of the computer that the code is running on, however it does *not* take that time zone into account when doing math.

There are few valid choices for remedies:

1. You could track all values in UTC, which does not have DST transitions.  The current time would be obtained by calling `DateTime.UtcNow`.

2. If the local time is relevant, then you need to be working with `DateTimeOffset` values instead of `DateTime` values.  The fields and properties would have to change, and the current time would come from `DateTimeOffset.Now`.

3. You could consider using the [Noda Time](http://nodatime.org) library, in which case the individual values could be stored in any of `Instant`, `OffsetDateTime`, or `ZonedDateTime`, depending on exactly what purpose they serve.

See also the following articles on my blog:
- http://codeofmatt.com/2013/04/25/the-case-against-datetime-now/
- http://codeofmatt.com/2015/03/06/common-daylight-saving-time-mistakes-for-net-developers/

**Comment by Aaronontheweb** [comment]
I think we should just switch to UTC on those calls - since we're really only using the current time to measure elapsed time, right?

**Comment by rogeralsing** [comment]
@Aaronontheweb yepp

**Comment by mj1856** [comment]
That would probably be the simplest thing to do to avoid DST issues.

**Comment by mj1856** [comment]
Though - you may also want to consider what to do with existing data.  If the value is persisted anywhere, then switching to UTC would mean possibly comparing the previous local data with the new UTC value.   If that's something you're concerned with, the `DateTimeOffset` approach would solve it.

**Comment by Aaronontheweb** [comment]
@mj1856 I'll take a deeper look at the code base, but most of those calls appear to be for things that are ephemeral to the state of an Akka.NET application as it runs in-memory. Scheduled recurring messages and so forth.

I'll look closely to see if the local clock gets accidentally exposed to the end-user anywhere they might need to store something.

But the TL;DR; of it is that I think we'll probably be ok just switching it.

**Comment by kekekeks** [comment]
If current time is used for internal scheduling purposes, anything that uses current UTC/Local time is unreliable. System time can be arbitrary changed by *anything*. So, it's better to use [GetTickCount64](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724411%28v=vs.85%29.aspx) ([CLOCK_MONOTONIC](http://pubs.opengroup.org/onlinepubs/000095399/functions/clock_getres.html) for *nix) which never goes backward and increments monotonically.

**Comment by kekekeks** [comment]
I've checked referencesource and Mono sources. `Task.Delay` uses `Timer` and `Timer` is based on monotonic clock.

**Comment by kekekeks** [comment]
Mono's Stopwatch and Environment.TickCount [use CLOCK_MONOTONIC](https://github.com/mono/mono/blob/b02523cfd1d3143b47ede88d46f717f22fc19c82/mono/utils/mono-time.c#L130). So it's safe to just use `Stopwatch` every time we need to measure elapsed time. On Windows one should use `GetTickCount64` for regular monotonic clock and `Stopwatch` for high resolution monotonic clock (`Stopwatch` has more overhead on Windows platform).

**Comment by HCanber** [comment]
All time related calls should go through `ITimeProvider` (https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/Scheduler/ITimeProvider.cs) and not be made directly to underlying system time. Right now `ITimeProvider` only delivers UTC time (as a `DateTimeOffset`), but we should add more functions to it. 
Why? Because then we can swap the `ITimeProvider` implementation to something else during tests,allowing us to write test that don't depend on real time, but on time that can be controlled in the test.

So for stopwatch we could add a `IStopwatch CreateStopwatch(bool start=true)` and rewrite @kekekeks implementation of monotonic clock (see #876) into an `IStopwatch` and return it from `DateTimeOffsetNowTimeProvider` (which probably should be renamed to something like `SystemTimeProvider` and let `TaskBasedScheduler` delegate calls to it).

**Comment by HCanber** [comment]
I seem to have mixed up two concepts here. :) 
Monotonic clock should be moved into `ITimeProvider` as well as exposing stopwatch-functionality.

**Comment by HCanber** [comment]
> `Stopwatch` has more overhead on Windows platform

@kekekeks Looking at your PR https://github.com/akkadotnet/akka.net/pull/876/files#diff-acc01fe0c12b1eaa67908bf90766ac05R7.
On windows, `Elapsed` property calls  [GetTickCount64](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724411%28v=vs.85%29.aspx) instead of `Stopwatch.Elapsed` (which in turn queries
the highres timer by calling [QueryPerformanceCounter](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644904(v=vs.85).aspx)). So calling [QueryPerformanceCounter](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644904(v=vs.85).aspx) is more expensive than [GetTickCount64](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724411%28v=vs.85%29.aspx)?

**Comment by kekekeks** [comment]
@HCanber
>So calling QueryPerformanceCounter is more expensive than GetTickCount64?

See [this](http://www.drdobbs.com/windows/win32-performance-measurement-options/184416651) article. TL;DR: QueryPerformanceCounter is ~88 times more expensive.

**Comment by HCanber** [comment]
We should definitely switch to use a monotonic clock instead of subtracting `DateTime.Now`:s, but I'm not sure exactly how, yet. We seem to have four different uses of `DateTime.Now` (in around 20 places):

- Get a timestamp, a `long` (monotonic clock ticks). See `StandardMetrics` in ClusterMetricsCollector.cs
- The current time, See `SnapshotStore` in Akka.Persistance. This should probably change to use `DateTimeOffset`
- Measuring intervals, i.e. the time since a point a time. See `ChildRestartStats`. This seems to be the most common useage of `DateTime.Now`
- The current time for meta data / logging / debug messages.

We have around 30 places where we use `DateTime.UtcNow`. I haven't looked into what it's used for, but my guess is it's used for the same reasons as for `DateTime.Now`.

No uses of `DateTime.Today`.

I'd like to think about this for a while and try different ideas I have.

**Comment by mj1856** [comment]
@kekekeks - That article is 12 years old.  Are you sure it's still accurate?  I'm not sure about the perf cost on modern hardware.

Some of it is likely true still, but not sure about the cost overhead.  According to [this post](http://stackoverflow.com/a/24015406/634824), `QueryPerformanceCounter` (`Stopwatch`) should be used for profiling short-lived activities, while `GetTickCount64` should be used for longer running operations.  Still, it shouldn't be used in situations where the machine might restart, or when comparing values from multiple machines.

Still, any of those are better than using `DateTime.Now`, which would be prone to daylight saving time, or any of the `Now` or `UtcNow` methods, as they can be altered by user or machine adjustments to the RTC.

I've actually never used `GetTickCount64` in a .NET application - but I suppose it might make sense for certain scenarios.

**Comment by kekekeks** [comment]
@mj1856 
> Still, it shouldn't be used in situations where the machine might restart, or when comparing values from multiple machines.

`QueryPerformanceCounter` accesses HPET (hardware device), `GetTickCount`/`GetTickCount64` just reads a value already stored in the system memory that is periodically updated by OS.
> Still, it shouldn't be used in situations where the machine might restart, or when comparing values from multiple machines.

It's *monotonic* clock. It ticks from some *unspecified* point in the past monotonically. You can't compare its value from different machines. The only guarantee is that it never goes backward and increments monotonically.
BTW, we can use something like NTP to get an accurate value of monotonic clock on remote machine. So we can calculate the offset between local monotonic clock and some cluster coordinated time (initially obtained from cluster leader or something like that), and then use it for synchronization between machines. This way we can guarantee that time is actually synchronized.

>I've actually never used GetTickCount64 in a .NET application

People usually use `Timer`, `Task.Delay`, `Stopwatch` or just don't care about NTP, daylight saving time, etc.

**Comment by Aaronontheweb** [comment]
> BTW, we can use something like NTP to get an accurate value of monotonic clock on remote machine. 

For our purposes, I don't think this is necessary - all of the scheduling in Akka.NET is done locally. Just needs to happen on regular intervals, not at specific dates and times.

As for time-ordered network events, our built-in ones use vector clocks that don't take any dependencies on the CLR time system:

https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Cluster/VectorClock.cs

**Comment by nvivo** [comment]
A little late for the discussion... I completely agree on moving from DateTime to a monotonic clock.

But does akka.net spend so much time requesting the current time that it requires worrying about the performance of QueryPerformanceCounter? I can call this method 8 million times/second on my laptop on debug mode attached to visual studio with energy savings on. This goes to 20 million/second on release mode... 

From what I measured, it's ~4 times slower than DateTime.UtcNow, and ~8 times slower than Environment.TickCount. But should it matter?

![image](https://cloud.githubusercontent.com/assets/202449/7265239/f07e4682-e86c-11e4-99a8-d1ca64102c58.png)

All I'm saying is that maybe we should first see what is really required. Does Akka.net need nanosecond precision? Then Stopwatch is the best answer. If it's used for scheduling, maybe `Environment.TickCount` works. Does it need both? So expose both.

For reference, TPL uses Timers, which [use Environment.TickCount until Windows 7](http://referencesource.microsoft.com/#mscorlib/system/threading/timer.cs,68), that means you can't schedule tasks for more than 29 days anyway. If it works for TPL, should work for Akka.

Apparently [the Mono people agree](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Threading/Timer.cs#L178).

**Comment by Aaronontheweb** [comment]
@nvivo the performance is less of a concern than DST / users tampering with the clock IMHO. 

> For reference, TPL uses Timers, which use Environment.TickCount until Windows 7, that means you can't schedule tasks for more than 29 days anyway. If it works for TPL, should work for Akka.

The design concerns that the TPL and Akka.NET have overlap by only a very small amount.  Discuss designs on their own merits; not by appealing to the authority of another library. Stick to what's important for Akka. 

In this case - raises a question I hadn't thought about: what mechanism is most effective for ensuring consistent scheduling over very long periods of time? Wrap TickCount in an `unchecked` block?

Users should be able to have long-running actors that run for months without restart - and they should be able to use a scheduler that entire time.

**Comment by Aaronontheweb** [comment]
Looks like the answer to my question lies in the comments on https://msdn.microsoft.com/en-us/library/windows/desktop/ms724411%28v=vs.85%29.aspx

> If GetTickCount is 49.7 days, how long is GetTickCount64?
> It's ~585 million years.

> Tergiver
> 2/14/2011
> GetTickCount64 is in milliseconds, not ticks
> Despite the name, it returns the number of milliseconds of uptime, not ticks.

Sounds like @kekekeks's PR should work for that scenario then.

**Comment by nvivo** [comment]
Just a side note,  the int32 part shouldn't affect  anything in a system running for more than 29 or 47 days. 

But that's a good solution anyway.

**Comment by rogeralsing** [comment]
Can this be closed? we did merge the Monotonic clock PR

**Comment by kekekeks** [comment]
Motonic clock is yet to be integrated into the code base.

**Comment by kekekeks** [comment]
I think we can close this.
