### ISSUE TITLE
[critical bug] Akka.Tests timing out since PRs after v1.0 release

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#847]
Happening on multiple different PRs now. I recommend not accepting any pull requests until we understand why.

http://petabridge-ci.cloudapp.net/viewLog.html?buildId=624&buildTypeId=AkkaNet_AkkaNetPrBuild&guest=1

cc @rogeralsing @Horusiath any chance that the new specs we've added since the v1 release can cause a livelock or infinite loop?

**Comment by rogeralsing** [comment]
Can we make a test run where we disable the "AsyncAwait" spec ?
I know that XUnit 1.x have some problems with the CallContext stuff we use when running with the debugger in VS. 
Maybe it has some effect on the build server too (?) unlikely but we can try

**Comment by Aaronontheweb** [comment]
@rogeralsing that's a good idea - try sending a review-only PR that ignores those tests

**Comment by rogeralsing** [comment]
Some info on code 42 and teamcity here http://stackoverflow.com/questions/13937635/teamcity-not-executing-msbuild-command-line

Anything relecant?

**Comment by Aaronontheweb** [comment]
Observed the hang happen on a live run:

Step 1/1: Akka.Tests.dll: Akka.Tests.Dispatch.ActorAsyncAwaitSpec.Actor_should_be_able_to_resume_suspend - culprit

**Comment by rogeralsing** [comment]
Ouch oh well, not much we can do about it, xUnit does not play well with flowing async state.

**Comment by Aaronontheweb** [comment]
@rogeralsing yep, you're right about that - the one thing we can do though is mark that test as `async` and return a `Task` if it's not already. I talked about this issue to one of the .NET Fringe attendees and he indicated that he'd run into this issue with XUnit also and that part of the problem is that it expects `async` all the way down if it's used at all.

**Comment by rogeralsing** [comment]
It's already async Task.
When debugging that test, the test runner blows up with the following stacktrace:
![xunit](https://cloud.githubusercontent.com/assets/647031/7164614/9ea0dce6-e3a1-11e4-8da5-ee0834909b46.png)

Seems like xUnit is trying to delete files ??
I don't even understand how that test can cause that.

**Comment by rogeralsing** [comment]
Ummm never mind, this seems to happen in debug mode for every test on my machine ATM.
Ignore me..

**Comment by Aaronontheweb** [comment]
I think we can close this issue. Will need to be something we consider for our upgrade to XUnit 2.0.
