### ISSUE TITLE
ClusterRouterGroup not removing downed nodes

### ISSUE THREAD

**Issue by annymsMthd** [akkadotnet/akka.net#849]
We have traced this one to line 78 in https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Routing/RoutedActorCell.cs

The type of the routee is an ActorSelectionRoutee, not ActorRefRoutee,  and it is being ignored and not removed. 

Also line 173 in https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Routing/RouterConfig.cs looks like where the routees are created.

**Comment by Aaronontheweb** [comment]
Related to #743

**Comment by Aaronontheweb** [comment]
I'll look into this one

**Comment by Aaronontheweb** [comment]
First glance - still having lots of issues with my multi-node tests aimed at this behavior even after making some changes to `RouterConfig`. Not totally sure what the issue is yet.

**Comment by annymsMthd** [comment]
Working on this in a branch on my repo. This looks like it goes deep. I've fixed up the router stuff but it looks like it exposes some issues with ActorSelection. I have tests failing on Group Routers and i chased it down the rabbit hole.

akka:
https://github.com/akka/akka/blob/8485cd2ebb46d2fba851c41c03e34436e498c005/akka-actor/src/main/scala/akka/actor/ActorSelection.scala

us:
https://github.com/akkadotnet/akka.net/blob/8ac06436f53df7e1622e7a107abc6c2823d72799/src/core/Akka/Actor/ActorSelection.cs

I'm way too tired for recursion tonight but I will start on this fresh tomorrow.

**Comment by annymsMthd** [comment]
#953

**Comment by Aaronontheweb** [comment]
Is this considered to be "fixed" now?

**Comment by annymsMthd** [comment]
The dlls with the nightly package are still marked 1.0.1 and I'm not seeing
the changed messages. I need to check this when I get home

**Comment by Aaronontheweb** [comment]
Argh! Damn TeamCity. I'm getting weird stuff from the feed too.
In that case, go to the build server and download the artifacts from there.

**Comment by annymsMthd** [comment]
I'm investigating

**Comment by annymsMthd** [comment]
This is working properly now in our cluster with the nightly build.
