### ISSUE TITLE
PinnedDispatcher - uses single thread for all actors instead of creating persanal thread for every actor

### ISSUE THREAD

**Issue by kantora** [akkadotnet/akka.net#850]
In version 0.8.x it created personal thread for every actor. But now it uses single thread for all actors under same dispatcher (so, if you put PinnedDispatcher as default dispatcher - all actors in system will work in single thread without any multythreading).

Also I've found unused variable "running" in it. So, I suppose that thread will last forever, even after actor's death.

**Comment by rogeralsing** [comment]
cc @Aaronontheweb, the new dispatcherconfig stuff seems to have broken this

From Java docs:

### PinnedDispatcher

This dispatcher dedicates **a unique thread for each actor using it**; i.e. each actor will have its own thread pool with only one thread in the pool.

- Sharability: None
- Mailboxes: Any, creates one per Actor
- Use cases: Bulkheading
- Driven by: Any akka.dispatch.ThreadPoolExecutorConfigurator
by default a "thread-pool-executor

**Comment by Aaronontheweb** [comment]
Yep, this is a case of me not knowing how the pinned dispatcher works. I'll fix this and add some garbage collection to it also.
