### ISSUE TITLE
Nested Ask async await causes null-pointer exception in ActorTaskScheduler

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/akka.net#855]
When nesting Ask statements as described in this gist: https://gist.github.com/Danthar/d1fe5581a6ba13ca6e30
A problem occurs causing the first Ask to never return. An exception from the ActorTaskScheduler seems to be the culprit.

**Comment by rogeralsing** [comment]
The issue have been identified to be at:
https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Dispatch/ActorTaskScheduler.cs#L56

Ambient state can be null in cases where e.g. a `TaskCompletionSource` is beeing completed from the outside, e.g. in a `FutureActorRef` while the awaiting code is under the `ActorTaskScheduler` control.

**Comment by rogeralsing** [comment]
PR merged
