### ISSUE TITLE
Akka.TestKit and Akka.Cluster

### ISSUE THREAD

**Issue by pcwiek** [akkadotnet/akka.net#865]
It seems that when running the TestKit fixture, any actor that has:

     cluster = Cluster.Get(Context.System);

inside ends up with:

    Akka.Actor.ActorInitializationException: Exception during creation 
     ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
     ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at Akka.Cluster.ClusterSettings..ctor(Config config, String systemName)
       at Akka.Cluster.Cluster..ctor(ActorSystemImpl system)
       at Akka.Cluster.ClusterExtension.CreateExtension(ExtendedActorSystem system)
       at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.CreateExtension(ExtendedActorSystem system)
       at System.Lazy`1.CreateValue()
       at System.Lazy`1.LazyInitValue()
       at Akka.Actor.Internals.ActorSystemImpl.TryGetExtension(Type extensionType, Object& extension)
       at Akka.Actor.Internals.ActorSystemImpl.GetExtension(IExtensionId extensionId)
       at Akka.Actor.ExtensionIdProvider`1.Get(ActorSystem system)
       at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.Get(ActorSystem system)
       at Akka.Actor.ActorSystemWithExtensions.WithExtension[T,TI](ActorSystem system)
        ...
Is there any way to test cluster-using actors right now? Or should I just hack around it for now and do a conditional initialization of the cluster?

I saw that Akka has 'special' fixtures to deal with cluster tests. If it's not ported - that's fine, I just want to know how to proceed.

**Comment by Aaronontheweb** [comment]
You shouldn't need to do anything special to get clustered tests to play nice with Akka.TestKit - take a look at https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Cluster.Tests/ClusterSpec.cs

doesn't use a custom fixture or anything

**Comment by pcwiek** [comment]
Hm, interesting. Browsing through that test makes me wonder:

1. I can see that I can't use `AkkaSpec`, just `TestKit`. I hope it doesn't change anything. By the way, is there there a plan to upgrade `Akka.TestKit` to reference XUnit 2.0, because now it holds a strict dependency on XUnit 1.9.2..?

2. It *seems* be that the configuration is missing in my test. Right now cluster is taken from `App.config` when the application is running in a regular way - at least I think so, I had nothing overridden in code, so I assume it takes the cluster, actor ref provider etc straight from config. Now I'm not sure if there's a clean way to override (or, technically, supply) it *just* for test, because the test runner most probably doesn't look into any `App.config` in any project.

So, having an actor with a cluster inside:

    public class TestActor : ReceiveActor
    {
        private readonly Cluster cluster = Cluster.Get(Context.System);
    }

is there a way to inject configuration from the test method for testing purposes, for example to `Sys` actor system...? 
I'll have a chance to play with it more tomorrow and I'll poke around `TestKitSettings`. :)

Also, sorry in advance for too many potentially dumb questions. I found no writeup on how to use the test kit, so it's just trial and error for me. I'm aware it may be a bit annoying to you guys. :)

**Comment by Aaronontheweb** [comment]
> By the way, is there there a plan to upgrade Akka.TestKit to reference XUnit 2.0, because now it holds a strict dependency on XUnit 1.9.2..?

Yes, we're going to test this out soon - and we'd be open to a pull request that does this ;)

As for the rest of your questions - I'm not as familiar with the semantics of the testkit so I'm just going to cc @HCanber and see if he's available to help clarify

**Comment by HCanber** [comment]
`AkkaSpec` is only for internal use only. `TestKit` is what you should use.

`TestKit` has a few overloads, one that takes a configuration object, or a string with configuration. The config is passed on to the `Sys` actor system. To use it, just create a constructor in your test class, and in the call to `base` specify the config.

``` C#
public class MyTest : TestKit
{
  public MyTest () : base(@"akka.actor.provider = ""Akka.Cluster.ClusterActorRefProvider, Akka.Cluster""") { }
  ...
}
```

Docs for TestKit are missing. But I've written a few blogposts on it here: http://blog.canberger.se/p/akkanet.html

**Comment by pcwiek** [comment]
Perfect, thanks! I'll try it out tomorrow :)

**Comment by annymsMthd** [comment]
#888 is the upgrade to XUnit 2.0. The details of what to do with the testkit, create a new one for 2.0, are still up for debate.

**Comment by rogeralsing** [comment]
Labels for this one?
