### ISSUE TITLE
Missing constructor overload on ScatterGatherFirstCompletedPool

### ISSUE THREAD

**Issue by nvivo** [akkadotnet/akka.net#871]
ScatterGatherFirstCompletedPool is missing an overload that allows `new ScatterGatherFirstCompletedPool(nrOfInstances, within)`

The scala version appears to expose this:
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/routing/ScatterGatherFirstCompleted.scala#L116

Currently, the only way to pass this value is using the more verbose version `ScatterGatherFirstCompletedPool(int nrOfInstances, Resizer resizer, SupervisorStrategy supervisorStrategy, string routerDispatcher, TimeSpan within, bool usePoolDispatcher = false);`

**Comment by rogeralsing** [comment]
Done in #1008
