### ISSUE TITLE
Code cleanup: Check empty file 'TailChoppingPool.cs'

### ISSUE THREAD

**Issue by nvivo** [akkadotnet/akka.net#872]
There is an empty TailChoppingPool.cs file [here](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Routing/TailChoppingPool.cs) that is probably intended to be removed, as all the logic is implemented in TailChoppingRoutingLogic.cs. 

Opening this just in case someone is cleaning up the sources.

**Comment by elbaloo** [comment]
This seems to be already fixed by #1005.
