### ISSUE TITLE
Early outbound user messages prevents cluster nodes from joining on RPI(possibly mono or lowend HW)

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#874]
After digging around some more with the Raspberry PI Cluster support, I've found that even if I start up two nodes on the RPI only, they still can not communicate and fail with an association exception.
So that rules out network issues as far as I can tell. 
localhost to localhost still fail, and there is no firewall on the RPI.
While the remoting chat works fine.

I figure that if things don't work 100% on the RPI, it could be similar problems on other Mono OS'es
On what OS'es have we verified cluster support?
Ubuntu and iOS?
Debian?

**Comment by rogeralsing** [comment]
I found the issue.
I was running the Petabridge WebCrawler example, and it seems that the crawler service is too fast sending messages at start up.
Removing the all code except the cluster start up makes everything work just fine.

So there is possibly an RC bug in the cluster that on a low end machine tries to talk too early or something like that.  cc @Aaronontheweb @smalldave 

Once booted, everything works nicely..

**Comment by smalldave** [comment]
Oops didn't mean to close that

**Comment by Aaronontheweb** [comment]
This is an interesting issue... I've used Akka.Remote in production on Windows where the inbound receiver was under tremendous loads immediately after joining - so I wonder if the issue here is that the cluster joining stuff is too sensitive to latency right now?

**Comment by rogeralsing** [comment]
Possibly related to #1062  (?)

**Comment by Aaronontheweb** [comment]
Closing this - there were lots of possible causes that could have been responsible for this, but my money is on the race condition we fixed inside the `Cluster` constructor that caused it to deadlock or the race conditions inside Helios 1.4.1. Happen to reopen if it crops up again.
