### ISSUE TITLE
DeathWatch AddressTerminated issue

### ISSUE THREAD

**Issue by annymsMthd** [akkadotnet/akka.net#887]
Just found this one out doing multinode tests.
JVM: https://github.com/akka/akka/blob/8485cd2ebb46d2fba851c41c03e34436e498c005/akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala line 165

NET: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/ActorCell.DeathWatch.cs line 255

**Comment by annymsMthd** [comment]
Fixed in #888

**Comment by Aaronontheweb** [comment]
@annymsMthd would you mind breaking this out into its own PR, so we can get this fix in separately from any of the discussions around XUnit 2? Or would that be a big pain in the ass?

**Comment by annymsMthd** [comment]
Crap I didn't see this. I can do that first thing tomorrow
