### ISSUE TITLE
Underlying transport closed error in chat example

### ISSUE THREAD

**Issue by petersondrew** [akkadotnet/akka.net#889]
I'm just starting to work with akka and have been working on a client/server setup using tcp remoting.
During testing, after the client disconnects, the server throws up errors like this:
```
2015-04-23 09:57:57.1648|ERROR||Akka.Remote.Transport.ProtocolStateActor|Underly
ing transport closed.|
2015-04-23 09:57:57.1908|ERROR||Akka.Remote.EndpointWriter|AssociationError [akk
a.tcp://sqlbackup@localhost:2552] <- akka.tcp://sqlbackupclient@localhost:49588:
Error [Shut down address: akka.tcp://sqlbackupclient@localhost:49588] [   at Akk
a.Remote.EndpointReader.HandleDisassociated(DisassociateInfo info)
   at Akka.Remote.EndpointReader.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]|
2015-04-23 09:57:57.1908|ERROR||Akka.Actor.OneForOneStrategy|Shut down address:
akka.tcp://sqlbackupclient@localhost:49588|
```
At first I thought I was doing something wrong, but after playing around with the Chat example, I see that the server also throws the underlying transport closed error in the example.

Should these messages be at the `ERROR` level in this case, or Is there any way to avoid these types of errors when a client disconnects gracefully?

**Comment by rogeralsing** [comment]
I suppose @Aaronontheweb is the one to answer this.
But AFAIK, there is no way for one system to tell another "bye bye Im disconnecting now" and gracefully shut down.
Is there @Aaronontheweb ?

**Comment by petersondrew** [comment]
Thanks for jumping in @rogeralsing. If it is indeed the case that there is no way of determining when a disconnect was graceful, should it instead be logged at a lesser log level such as WARN?

**Comment by Aaronontheweb** [comment]
Ugh, my anti-virus closed chrome to delete tracking cookies when I was in the middle of writing up my reply.

Sorry for the delay! I totally missed this.

The only way to gracefully shut down a transport is to explicitly call `Disassociate` on the transport, something that really can only happen when `ActorSystem.Shutdown` is called or Akka.Cluster downs a node. Under those circumstances an error *should* not be thrown.

The error you're seeing now is what happens if you kill a process - it's not a clean shutdown. The socket gets closed from the side that's shutting down and it throw an exception on the side staying open. Ultimately it's not a "fatal" error but it's still severe enough to be worth logging.

That being said - I'm pretty sure our clean shutdown code is racy; the transport gets closed before acknowledgement of the `Disassociate` message on TCP.

**Comment by petersondrew** [comment]
@Aaronontheweb This seems to be happening even when the actor system is wrapped in a ``using`` statement, though I think in my test the program terminates immediately after the actor system goes out of scope so it could indeed be a race condition.  
I will play with it some more and see if that is indeed the case. Thanks for getting back to me.

**Comment by Ranmoro** [comment]
How, in this example subscribe to a `Disassociate` event and other similar warnings in the data transport? To be able to close the lost connection.

If you disable the client - `RemoteActorRef.IsTerminated` property on the server does not change.
How use this property?

I think that would be useful to complement the example

**Comment by Ranmoro** [comment]
`system.EventStream.Subscribe(actorServer, typeof(DisassociatedEvent));`

**Comment by beatsm** [comment]
I have noticed this with all the examples that use the remoting infrastructure. I have been playing about with the code and regardless of how I shutdown a client actor system this error appears.

@Aaronontheweb must be right in that the clean shutdown code is racy but I have not been able to produce a condition where it works.I have not been able to confirm if this is racy as there is a lot of code between ActorSystem.Shutdown and the transports stuff and my experience of the code base is lacking.  

If anyone has any pointers to where to look let me know and I see what I can figure out.

**Comment by Danthar** [comment]
Old issue. Remoting has some known issues, which are already addressed since the opening of this issue, or currently being addressed.
