### ISSUE TITLE
Cluster rejoin behavior

### ISSUE THREAD

**Issue by annymsMthd** [akkadotnet/akka.net#918]
I have a node trying to rejoin the cluster. It was previously part of the cluster before being reset. Now when the node attempts to join:

Cluster Node [akka.tcp://ClusterSystem@172.16.1.36:8100] - Starting up...

It waits at this message. On the leader node:

Existing member [UniqueAddress: (akka.tcp://ClusterSystem@172.16.1.36:8100, 900595072)] is trying to join, ignoring

This message repeats over and over and the node is never added to the cluster.

**Comment by annymsMthd** [comment]
@Aaronontheweb @smalldave

**Comment by annymsMthd** [comment]
Existing member [UniqueAddress: (akka.tcp://ClusterSystem@172.16.1.36:8100, 1641121334)] is trying to join, ignoring

When i shut the node down and try again. Looks like the id changed but the node is still being ignored

**Comment by Aaronontheweb** [comment]
Possibly related to #774

**Comment by rogeralsing** [comment]
```csharp
 // check by address without uid to make sure that node with same host:port is not allowed
 // to join until previous node with that host:port has been removed from the cluster

// ^ WAT? checking w/o UID

 var alreadyMember = localMembers.Any(m => m.Address == node.Address);
 var isUnreachable = !_latestGossip.Overview.Reachability.IsReachable(node);

 if (alreadyMember) _log.Info("Existing member [{0}] is trying to join, ignoring", node);
```

**Comment by rogeralsing** [comment]
hmm scala does this to

```scala
      // check by address without uid to make sure that node with same host:port is not allowed
      // to join until previous node with that host:port has been removed from the cluster
      val alreadyMember = localMembers.exists(_.address == node.address)
      val isUnreachable = !latestGossip.overview.reachability.isReachable(node)

      if (alreadyMember)
```

**Comment by rogeralsing** [comment]
`      // to join until previous node with that host:port has been removed from the cluster`

I assume the comment above is the important one.

**Comment by annymsMthd** [comment]
Exactly. It looks like the node isn't being removed properly.

**Comment by rogeralsing** [comment]
The only place stuff is removed from `localMembers` is in `Downing`.
Either that code is b0rked, or the `Member` equality ops are.

**Comment by annymsMthd** [comment]
Say we restart a service and the node is only down for a few seconds. That is were i see this sometimes.

**Comment by annymsMthd** [comment]
I'm on this one. We are doing a cluster bug hunt atm

**Comment by annymsMthd** [comment]
Running the nightly build in our cluster. This is fixed. The node will now be downed and allowed to rejoin.
