### ISSUE TITLE
Akka.NET Scaffolding

### ISSUE THREAD

**Issue by shersh** [akkadotnet/akka.net#928]
What about creating scaffolding tool like (https://code.visualstudio.com/docs/ASPnet5) ?

"yo akka"

**Comment by skotzko** [comment]
I was just thinking about this last night while playing w/ OmniSharp and the yeoman generators for it.

**Comment by sean-gilliam** [comment]
the generator in that example is on github https://github.com/OmniSharp/generator-aspnet

**Comment by nicklanng** [comment]
What sort of options do you think should be included in the generator?
Eg:
- Language choice: C# / F#
- Target Framework: 3.0, 4.0, 4.5, Mono 4.0.2
- Project type: Solution, standalone project, project in existing solution
- Package manager: Nuget, Paket

**Comment by rogeralsing** [comment]
>Target Framework: 3.0, 4.0

Those are not supported

**Comment by sean-gilliam** [comment]
Closing due to a generator project being recently contributed.

Please refer to https://github.com/akkadotnet/generator-akkadotnet
