### ISSUE TITLE
akka.loglevel = OFF doesn't work

### ISSUE THREAD

**Issue by nvivo** [akkadotnet/akka.net#940]
[Pigeon.conf states](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Configuration/Pigeon.conf#L27) `akka.loglevel = OFF` should work, but actually causes an exception:

```
Unknown LogLevel: "OFF". Valid values are: "DEBUG", "INFO", "WARNING", "ERROR"
```

**Comment by rogeralsing** [comment]
Fix for this have been merged. closing
