### ISSUE TITLE
Plugin proposal: Akka.Persistence.PostgreSQL

### ISSUE THREAD

**Issue by davidflerlage** [akkadotnet/akka.net#944]
I just finished the initial implementation of a PostgreSQL persistence plugin.  I am hoping to submit a pull request later today or tomorrow.  If you are curious, you can find the code here: https://github.com/davidflerlage/akka.net/tree/akka-persistence-postgresql.

This plugin is largely a port of the Sql Server plugin, with some inspiration from the JVM Akka PostgreSQL plugin, https://github.com/okumin/akka-persistence-sql-async.  There is some duplication between the Sql Server and PostgreSql plugins that we might want to address.  I imagine that any future sql plugins will also need some of the same code.

I have a question about the best way to handle database initialization on the build server during automated testing.  I see two main options:

1) Drop and create the database each time.
2) Drop and recreate just the tables each time.

In either case, I would provide a script.

The Sql Server plugin uses LocalDb, so it can easily recreate the database each time the tests run.  I do not think PostgreSQL has a LocalDb equivalent, so that's not really an option here.  I also don't think integrated security is an option, so user credentials need to be persisted somewhere.

I am leaning towards option 1, but I am eager to hear everyone's thoughts.

**Comment by Horusiath** [comment]
@davidflerlage The Akka.Persistence.SqlServer plugin will be rewritten to using ADO.NET async API soon - we know that this could probably introduce some problems with testing. Also we decided that only limited set of the persistence plugins should be part of akka core repository and have official support. @akkadotnet/developers should we include PostrgreSQL to our contrib repo and give support to it?

**Comment by annymsMthd** [comment]
+1

**Comment by skotzko** [comment]
+1

**Comment by taswar** [comment]
+1

**Comment by davidflerlage** [comment]
I refactored my plugin to use the new Sql.Common project.  I am pretty much done with this plugin, but I am experiencing some random test failures.  I am trying to track the issue down.  The tests run fine when run individually and in small groups, but not when all of them are run together.

**Comment by Horusiath** [comment]
Merged
