### ISSUE TITLE
Managing changes in F# API

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#952]
I want to discuss about some release issues concerning Akka F# API with other people from this community. Since `Akka.FSharp` hit 1.0 version we as @akkadotnet/developers decided that some commitment is associated with this - we believe that API integrity and reliability is important thing. 

However there are new ideas around there (i.e. #935), which looks very promising and have positive feedback right now, but may also break backward compatibility. This is part of general problem with Akka F# API, which is new thing in Akka world. There are a lot of new ideas, but unlike the API ported so far, they are not battle tested and sometimes eventual progress may lead to breaking the compatibility with existing version of the API.

Question is: how do we want to deal with possible changes in the API, while maintaining it's integrity?

1. First idea is to include all changes in `-Pre` branch until 2.0 version of the API will come out. Problem is that Akka 2.0 plans are a distant future and not everyone may notice the difference.
2. Other idea was to create a separate package (`Akka.FSharp.Experimental`?), where backward compatibility rules would not apply. Only problem I see here is that if there will be other dedicated packages for integrating F# API with other Akka plugins, experimental API would be either not available to them or could introduce *split personality* / packages replication.
3. Other idea is to provide Akka.FSharp.Experimental API as a separate namespace inside existing Akka.FSharp package. It could be a mirror of the core, so that people could use work using either `open Akka.FSharp` or `open Akka.FSharp.Experimental` without necessity of importing both of them.
4. [from @raymens ] start versioning F# API on it's own. 

This is open discussion and all feedback or ideas are appreciated.

**Comment by raymens** [comment]
There's a 4th option, versioning the F# API on it's own (e.g.: F# API 2.0 with a dependency on Akka.net 1.0>= & <2.0). But that would probably mean it's on v10.0 within a year if you apply SemVer and I guess Akka.net wants to version all packages equally.

I would love to have the newest bits available on NuGet, but I do would like them to be tested though. Not like them being some sort of nightlies.

My vote would be for mixing option 2 and 3, having an Experimental package that has it's own namespace. Like the `Akka.Fsharp.Experimental`.

**Comment by DominicFinn** [comment]
At the moment there are 1,789 nuget downloads of akka.net fsharp. I don't know but I would imagine there's not much in the way of akka.net f# production code 'ducks'. With this in mind, wouldn't it be ok to just introduce the breaking changes sooner rather than later especially as the lib is picking up traction now. You could document the migration. Not ideal but perhaps pragmatic.

**Comment by jtmueller** [comment]
I like number 3, myself. I would probably ignore the stable namespace and go straight for the experimental one, and just deal with breaking changes as they occur. But some people will appreciate having the choice, and a few extra kilobytes from having both API's in one assembly isn't going to kill anyone.

**Comment by Neftedollar** [comment]
My choice 2

**Comment by raymens** [comment]
The problem with choice number 3 is that for every changed/new experimental feature the projects using the stable API will have an update waiting too, that actually doesn't change/fix anything for the stable users.

**Comment by rogeralsing** [comment]
I'd go for 3. even if there might be version increments that havent updated the main api. I think it's still an OK tradeoff to avoid too many packages and friction.

**Comment by rodrigovidal** [comment]
I think that the correct way to handle this is the 4th option. Akka.FSharp already has its own package. Using semantic versioning the user can choose if wants to update or not.

**Comment by runiner** [comment]
I'd go for @raymens 's idea of different numbering in F# API

**Comment by Adron** [comment]
4th. I don't like the idea of having namespacing like in 3. That just pushes out more work in rewrites or updates. As for 1 and 2, I vote :-1:

**Comment by neoeinstein** [comment]
I will also put in a vote for the Akka.FSharp package being versioned independently. So long as the dependency version ranges are appropriate and follow SemVer, I think we end up better off.

**Comment by Adron** [comment]
+1 SemVer

**Comment by Horusiath** [comment]
After discussion with the rest of the @akkadotnet/developers we decided, that `Akka.FSharp` will be versioned and released separately from the rest of akka packages. Since F# API is still evolving, we want to maintain a good pace of improvements and continuous feedback. For that, sticking hardly to Akka.NET core release cycle is not effective.
