### ISSUE TITLE
RoundRobinPool constructor API inconsistency

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/akka.net#967]
I noticed the `RoundRobinPool`, when compared with Akka, has an extra constructor. This has been noticed before, and remarked by @Aaronontheweb that it probably should be removed.

akkadotnet reference:
https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Routing/RoundRobin.cs

scala reference:
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/routing/RoundRobin.scala

So im creating this issue so that its not forgotten with the next big release. This issue should probably be marked towards some future release.

**Comment by jordansjones** [comment]
The extra constructor was added to for unit testing purposes: 7ad8c505ae579efce07e15f405a37557a3d72224

**Comment by Danthar** [comment]
Sorry i should have been more specific. 
@jordansjones You are referring to the constructor which accepts the nrOfInstances. That one is not the issue. That constructor is also in Akka.

Im referring to this one:

          /// <summary>
        /// Simple form of RoundRobin constructor
        /// </summary>
        /// <param name="nrOfInstances">The nr of instances.</param>
        /// <param name="resizer">A <see cref="Resizer"/> for specifying how to grow the pool of underlying routees based on pressure</param>
        public RoundRobinPool(int nrOfInstances, Resizer resizer) : base(nrOfInstances, resizer, DefaultStrategy, null) { }

**Comment by Danthar** [comment]
Closed as "Wont Fix". See corresponding PR for more info
