### ISSUE TITLE
Scheduler configuration and aligning with JVM implementation

### ISSUE THREAD

**Issue by stefansedich** [akkadotnet/akka.net#968]
Just want to open up a discussion into providing configuration for the scheduler implementation. At the moment we do not make use of the scheduler section in the config and hard code to always creating the TaskBasedScheduler.

If you look at the current scheduler configuration section which has carried over from the JVM:

      # Used to set the behavior of the scheduler.
      # Changing the default values may change the system behavior drastically so make
      # sure you know what you're doing! See the Scheduler section of the Akka
      # Documentation for more details.
      scheduler {
        # The LightArrayRevolverScheduler is used as the default scheduler in the
        # system. It does not execute the scheduled tasks on exact time, but on every
        # tick, it will run everything that is (over)due. You can increase or decrease
        # the accuracy of the execution timing by specifying smaller or larger tick
        # duration. If you are scheduling a lot of tasks you should consider increasing
        # the ticks per wheel.
        # Note that it might take up to 1 tick to stop the Timer, so setting the
        # tick-duration to a high value will make shutting down the actor system
        # take longer.
        tick-duration = 10ms
 
        # The timer uses a circular wheel of buckets to store the timer tasks.
        # This should be set such that the majority of scheduled timeouts (for high
        # scheduling frequency) will be shorter than one rotation of the wheel
        # (ticks-per-wheel * ticks-duration)
        # THIS MUST BE A POWER OF TWO!
        ticks-per-wheel = 512
 
        # This setting selects the timer implementation which shall be loaded at
        # system start-up.
        # The class given here must implement the akka.actor.Scheduler interface
        # and offer a public constructor which takes three arguments:
        #  1) com.typesafe.config.Config
        #  2) akka.event.LoggingAdapter
        #  3) java.util.concurrent.ThreadFactory
        implementation = "Akka.Actor.TaskBasedScheduler"
 
        # When shutting down the scheduler, there will typically be a thread which
        # needs to be stopped, and this timeout determines how long to wait for
        # that to happen. In case of timeout the shutdown of the actor system will
        # proceed without running possibly still enqueued tasks.
        shutdown-timeout = 5s
      }

So looking at this and something I have actually already implemented is to make use of the "implementation" setting to create the scheduler instance, but even then our constructor does not line  up with the JVMs implementation.

Do we have any thoughts about how to go ahead with this? if happy to deviate we can add only support for the implementation configuration setting and remove the irrelevant settings, or do we look at fixing scheduling so that it lines up. @HCanber you might be best to add some input here.

**Comment by Aaronontheweb** [comment]
Have you thought at all about using the hashed wheel timer approach they use in the JVM? Any reason why that's better or worse than what we are using now?

**Comment by rogeralsing** [comment]
If I recall correctly, @Aaronontheweb we did dive into the impl details of scheduling way back in the early days. and came to the conclusion that the Threaded Timers, which are used by TPL in .NET do use a similar approach as the JVM impl.
And that there was little benefit to touching this.

I'm all for supporting other implementations, so I'm not dissing the effort.

**Comment by rogeralsing** [comment]
Related to #982

**Comment by stefansedich** [comment]
Cool thanks @rogeralsing I missed all of this progress, I will update my PR for using the implementation type name and send that through today.

**Comment by stefansedich** [comment]
Closing this off as I have submitted a PR (#994) that allows selecting the implementation.
