### ISSUE TITLE
Merge Akka.ClusterSharding and Akka.ClusterSingleton

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#975]
1. I think it isn't necessary to have separate projects/packages for cluster sharding and cluster singleton packages. Let's merge them together and publish as a single NuGet package, when they'll be ready.
2. As I've said I think that `Akka.ClusterSharding` namespace and `ClusterSharding` extension class inside it will be having conflicting names, which will be irritating for the end user. Therefore we should rename either of them (my proposition was renaming `Akka.ClusterSharding` &rArr; `Akka.Cluster.Sharding`).

**Comment by rogeralsing** [comment]
This works for me. anyone else have any objection to doing so?
cc @akkadotnet/developers

**Comment by annymsMthd** [comment]
+1

**Comment by jberzy** [comment]
+1 for the idea of merging the projects and renaming namespaces, but I think we should consider a neutral name for the project. There are a couple of other yet-to-be ported features that wouldn't really be suitable under the cluster sharding namespace/project. JVM akka recently moved client, pubsub and singleton into an akka-cluster-tools project and sharding into akka-cluster-sharding.

**Comment by Aaronontheweb** [comment]
> I think we should consider a neutral name for the project. There are a couple of other yet-to-be ported features that wouldn't really be suitable under the cluster sharding namespace/project. JVM akka recently moved client, pubsub and singleton into an akka-cluster-tools project and sharding into akka-cluster-sharding.

Let's follow what the JVM does then.

Akka.Cluster.Sharding and Akka.Cluster.Tools - separate NuGet packages.

The reason for this makes a lot of sense too - ClusterSingleton doesn't depend on Akka.Persistence. ClusterSharding does.

Let's stick with that?

**Comment by Aaronontheweb** [comment]
BTW, I think the namespaces should be

`Akka.Cluster.[X]`

That's how they're organized in the JVM too.

**Comment by rogeralsing** [comment]
:+1:

**Comment by jberzy** [comment]
Sounds good to me

**Comment by Horusiath** [comment]
I'll take that and make PR soon.
