### ISSUE TITLE
Akka on .Net Core/PCL

### ISSUE THREAD

**Issue by ehaskins** [akkadotnet/akka.net#992]
I'm interested in running Akka.net on .Net Core in ASP.net vNext. That currently isn't supported, but it doesn't look like it'd be insurmountable to make Akka's core a PCL.
- Using System.Configuration - Could this be extracted into a separate library?
- Using IClonable - Some precompiler statements should resolve that
- Using System.Runtime.Serialization namespace
- Using System.Runtime.Remoting namespace

I've only spent about an hour looking at this, so I'm probably missing something harder, but has anyone given this more serious thought or consideration?

**Comment by Aaronontheweb** [comment]
@ehaskins I haven't given this much thought - this is the second or third time it's come up though.

> Using System.Configuration - Could this be extracted into a separate library?

What we really use this for is automatically loading Akka.NET configuration automatically from App.config / Web.config. Removing this into its own separate library would be a major breaking change to today's API. Everyone's apps would still "run," but without their configuration baked into configuration - it's actually the worse kind of breaking change: the "fails at runtime" type.

As for the other stuff, I'm sure we could refactor our usage of `ICloneable` and I'm not sure if we even need those other two namespaces.

**Comment by rogeralsing** [comment]
`System.Runtime.Serialization` is used in our exception types, they have ctors using `SerializationInfo`
`System.Runtime.Remoting` is used in the async await task scheduler

`ICloneable` could probably be removed, only Address uses it

**Comment by nvivo** [comment]
.NET Core needs to be considered a new "target" for compilation, and this will require some changes. If you look into the CoreFx repo, there is a lot of "#ifdefs" to compile things differently for .NET Core vs .NET. It's a similar but different API.

* System.Configuration - won't be required as .NET Core can load hocon files directly with an "UseHoconConfig()" extension

* System.Runtime.Remoting - I doubt this will be a requirement from CallContext on .NET Core, it may simply not be a dependency there

Most things can be solved by "ifdefs". But .NET Core is probably a year away, and doing this at this time in the "dev" branch is very uncertain. They said they are still deciding if more libraries will be ported.

Someone could try on a personal branch to see what would take.

**Comment by adamhathcock** [comment]
Is there a feature branch started?  I'd like to look at it and help as this is of interest to me as well.

**Comment by nvivo** [comment]
@adamhathcock 

I don't think there is a branch for that yet, otherwise @Aaronontheweb would have mentioned it. Right now, the best thing for you is to fork and create your own experimental branch to see where it goes.

Once you have something, create a PR for analysis. Since this is a new target, I guess it will take time and lots of feedback before it gets merged. But it needs to start somewhere.

**Comment by adamhathcock** [comment]
I guess I was hoping @ehaskins had one or something.  I wouldn't be sure what to do about the multi-project setup as VS2015 has xproj now for targetting .NET Core.

I just haven't done enough reading about best practices for all the next gen project setup.  I got something attempting builds but it felt ugly.

**Comment by rogeralsing** [comment]
We discussed this yesterday and we in the core team is not going to involve ourselves in this_right now_, as this is not where our main user base is focused and the effort will distract us from finishing more important tasks.

That being said, if anyone is willing to give this a try, please do so

**Comment by Aaronontheweb** [comment]
@rogeralsing beat me to the punch!

One day in the future, this might make a lot of sense for our users - but that's not where they are today. Hell, judging from the volume of "do you support .NET 4.0?" questions we get we're still considered to be bleeding edge in some circles by being .NET 4.5-only.

That being said, I would love to see a prototype of this in someone's fork as I'm personally interested in using it myself.

**Comment by ehaskins** [comment]
@adamhathcock @adamhathcock All I've done so far, is convert the Akka project to a PCL to see how many compile errors I'd get. Feel free to take a look at it [in the PCL branch of my fork.](https://github.com/ehaskins/akka.net/tree/PCL) I hadn't decided if I'll have the time to tackle this.

**Comment by adamhathcock** [comment]
I've made my own branch and I got HelloAkka to work:
https://github.com/akkadotnet/akka.net/compare/dev...adamhathcock:coreclr?expand=1

.NET Core is still very much in flux but we're trying to use it anyway.  I've used a pre-beta6 to get some more of the reflection classes in.  VS 2015 RC defaults to beta4.

I'd like people just to glance at some of the things I had to do just to see if there might be something better or different.  I think the most questionable thing is the removal of CallContext as I really didn't know what to do there besides try ThreadStatic.

**Comment by rogeralsing** [comment]
@adamhathcock awesome! :)

**Comment by adamhathcock** [comment]
Finally figured out how to execute unit tests.  I'll think I'll leave it at there for now and wait for more beta milestones.

Hopefully, the CallContext thing is just not exposed yet.  From my understanding, it's needed to move static state along with async/await and I don't know any other mechanism that would work.

**Comment by adamhathcock** [comment]
By happenstance, I literally found in the answer just after typing my last comment.  AsyncLocal<T> in DNX replaces CallContext.  Just updated the branch.

Okay, really trying not to overwhelm the discussion here :)

**Comment by nvivo** [comment]
Funny that AsyncLocal seems to be available from .net 4.5 (at least msdn says so) , and I didn't see it before.

I didn't look into it yet, but I wonder why @StephenCleary didn't mention it when we asked him about options to flow context. Is this new or is this also being deprecated?  If this is available in plain old .NET,  maybe it's an option for the current flow issues.

**Comment by StephenCleary** [comment]
AsyncLocal is coming in 4.6 (it's not in 4.5). It's essentially a wrapper around the logical call context.

**Comment by nvivo** [comment]
Thanks for the clarification @StephenCleary.

Right, at MSDN (https://msdn.microsoft.com/en-us/library/dn906268(v=vs.110).aspx), the top of the page says both 4.5 and 4.6, but at the bottom it says only 4.6. That's why I was confused, only looked at the top.

**Comment by adamhathcock** [comment]
I've updated the DNX usage to beta6.  I haven't attempted anything hard like Remote.

Targets are now .NET 4.5, DNX .NET 4.5.1 and DNX .NET CORE 5.0.  Tests pass and the HelloWorld and FaultTolerance samples work.

**Comment by rogeralsing** [comment]
Awesome! :+1:

**Comment by adamhathcock** [comment]
I'd like to keep this up.  Have you guys considered moving to xproj?  You can still target net 4.5 as well as dnx.  The downsides are the you can't reference a xproj from a csproj (this will be fixed) nor build a non-dnx executable.  Just DLLs.  

I guess those are two big downsides currently :)

**Comment by adamhathcock** [comment]
Updated again to beta 7.  

Need to get a Net Core version of Wire and Helios to really dive deeper.

**Comment by adamhathcock** [comment]
Another issue:  Type.GetType() (e.g. used for loading a logging actor) only works for the current executing assembly.  Need to redo this.

Hopefully https://github.com/akkadotnet/akka.net/issues/1263 is still on the cards (soon :) )

**Comment by rogeralsing** [comment]
@adamhathcock huh, Type.GetType does not accept fully qualified type names ?

**Comment by adamhathcock** [comment]
Under DNX, there aren't necessarily Assemblies and no AppDomains.  From my understanding, the static Assembly methods only really works for the current project.  Certain Assembly methods just don't work either.  I'm guessing Type.GetType(string) under DNX only will find types in the current (or maybe just the entry) project.  

To find all loaded types, usage of ILibraryManager (https://github.com/aspnet/dnx/blob/master/src/Microsoft.Dnx.Runtime.Abstractions/ILibraryManager.cs) is how you do it.  Looks like they've abstracted the concept of Assemblies and Projects behind the Library object.

You can get it either dependency injected or statically use CallContextServiceLocator to get the IServiceProvider and get it.

**Comment by nvivo** [comment]
2 cents here...

I remember seeing some explanation on a community standup about this. It seems the task of locating assemblies was moved out of the runtime into DNX, because it may need to locate a package in another folder or compile from source. In the end, assemblies still exist at runtime, but the runtime acts more as "read only". Type.GetType probably sees whatever was passed by DNX, but doesn't cause anything to load if it isn't.

If needed, it seems [there is a way](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L67) to load assemblies later, but as a explicit call, so in theory the behavior could be replicated. I couldn't figure out if this is the expected way to do it or how exactly to call it. Maybe stackoverflow or an issue on their repo could answer the proper way to do this.

**Comment by adamhathcock** [comment]
The logger I tested definitely was in an assembly that was used.  It just wasn't in the entry assembly.  Type.GetType didn't work for anything in that assembly (in my watch window) but it did for the entry assembly.  I stopped there knowing several of the Assembly.Get* methods (Entry, Executing) don't work but GetCurrent does work.

I guess I need to test it further.  In my own code, I don't load types or assemblies except from ILibraryManager because of things I've run into.  Maybe it will be more clear when they start documenting :)

**Comment by nvivo** [comment]
If you're adding a logger as usual, putting the assembly side by side in the same folder, it won't be loaded automatically by .NET. Only explicit dependencies are loaded, that is, the ones the compiler adds to the IL manifest. If I'm not mistaken (may be wrong here), even today, csc filters out from the manifest references you have but don't actually use.

So, DNX won't load them automatically just because they're in the same folder.

See if this helps: https://github.com/aspnet/dnx/issues/1412

**Comment by adamhathcock** [comment]
This is an explicit dependency.  The second assembly has code being used by the entry assembly.  It ought to show in ILibraryManager but Type.GetType didn't work.

I'll do some more explicit testing tomorrow my time and get back to you.

**Comment by adamhathcock** [comment]
I did a test repo: https://github.com/adamhathcock/dnx-test/blob/master/src/ConsoleApp1/Program.cs

Type.GetType doesn't work.  If I get the Assembly object, Assembly.GetType doesn't work.  If I do Assembly.GetTypes then the type is in the list.

**Comment by adamhathcock** [comment]
Just realized I did something.  Assembly.GetType(string) does work.  Type.GetType(string) doesn't

**Comment by ronnyek** [comment]
Now that api's are stabilizing with recent rc1 release, has anyone played with this any more? I'm very interested to see how much of akka is gonna run on core clr. I can run monoruntime for now, but I'd really be interested in real coreclr support.

**Comment by Aaronontheweb** [comment]
Since there's still a lot of healthy discussion on here, going to re-open this up as part of an ongoing conversation

**Comment by adamhathcock** [comment]
Just updated my branch again to RC1 and latest Dev: https://github.com/akkadotnet/akka.net/compare/dev...adamhathcock:coreclr?expand=1

Everything seems fine.  I haven't addressed the logging thing but I know Type.GetType() works now.  I'd like to use Wire but that's not NETCore'd yet.  I haven't attempted to target any of the "standard" targets introduced in RC1 (and will change names in RC2)

Just a screenshot to show what I've ported.  I'd like to contribute to an official branch.

![image](https://cloud.githubusercontent.com/assets/527620/11392956/d5ea5d36-9354-11e5-8f91-9e82bc342611.png)

**Comment by adamhathcock** [comment]
Now just updating against master: https://github.com/akkadotnet/akka.net/compare/master...adamhathcock:coreclr?expand=1

I want to remote but it will involve understanding Google.ProtocolBuffers and the new version Google.Protobuf (which is 3.0 beta and supports NET Core) but that seems daunting to me at the moment.

**Comment by goodisontoffee** [comment]
I would also be extremely interested in this being a possibility.

**Comment by adamhathcock** [comment]
Updated my branch to 1.0.6 with some minor fixes.

Working on building this internal to my company to use on .NET Core on some projects we've got.

**Comment by Neftedollar** [comment]
@adamhathcock thank you, Adam.

**Comment by lnaie** [comment]
Actually it would be great to have something as akka fully or partially ready when dotnet core goes live.

**Comment by janaka** [comment]
@adamhathcock is your branch just for the actors or the entire Akka.net? or is actors the only part that needs porting code wise?

**Comment by Silv3rcircl3** [comment]
Working on it, see #2153
