### ISSUE TITLE
Move persistence providers into their own repositories

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#998]
After discussing with @akkadotnet/developers, we decided to move the persistence providers into their own repositores so that they can have their own release cycles and project management.

**Comment by Aaronontheweb** [comment]
I'd recommend leaving the SQL Core stuff that's shared by SQL Server and PostGRES either in this repository, or have it reside in its own.

**Comment by LukeTillman** [comment]
Random thought, but maybe the SQL plugins could just be condensed into a single "ADO.NET" plugin? Similar to how SQL support is done in the Scala version via a JDBC plugin:

https://github.com/dnvriend/akka-persistence-jdbc

That way you'd end up with the shared SQL stuff there too instead of in its own library.

**Comment by rogeralsing** [comment]
>I'd recommend leaving the SQL Core stuff that's shared by SQL Server and PostGRES either in this repository, or have it reside in its own.

The annoying thing with having it in the core repo s that if you run all tests, you will se a lot of failing tests, unless you have both sql server and postgres installed and configured correctly.

**Comment by Aaronontheweb** [comment]
Working on executing this now.

**Comment by Aaronontheweb** [comment]
Akka.Persistence.PostgreSql is now properly setup with CI and build system support. Need to add release-mode CI support for publishing updated NuGet packages as well as nightly integration builds for the latest changes to Akka.Persistence itself, but that will be trivial to add.

**Comment by rogeralsing** [comment]
Are all of them moved or is this still work in progress?

**Comment by Aaronontheweb** [comment]
Still a work in progress - need to get SQL tests to pass (working on config), rinse and repeat the entire process for Cassandra, and then I need to submit a PR that removes all of them.
